Repository paritytech/polkadot-sdk, pull requests merged in 2023-11, with the labels that each got.

#2104 Bump ec-utils version
  Cargo.lock
  substrate/primitives/crypto/ec-utils/Cargo.toml
  substrate/primitives/crypto/ec-utils/src/lib.rs
Labels: A1-insubstantial, T0-node

#2097 upgraded review-bot to 2.2.0
  .github/workflows/review-bot.yml
Labels: R0-silent

#2115 [ci] Update rust nightly in ci image
  .github/workflows/fmt-check.yml
  .gitlab-ci.yml
Labels: R0-silent

#1189 [NPoS] Paging reward payouts in order to scale rewardable nominators
  Cargo.lock
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/pallet_staking.rs
  prdoc/pr_1289.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/babe/src/mock.rs
  substrate/frame/babe/src/tests.rs
  substrate/frame/beefy/src/mock.rs
  substrate/frame/beefy/src/tests.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
  substrate/frame/fast-unstake/src/benchmarking.rs
  substrate/frame/fast-unstake/src/lib.rs
  substrate/frame/fast-unstake/src/mock.rs
  substrate/frame/grandpa/src/mock.rs
  substrate/frame/grandpa/src/tests.rs
  substrate/frame/nomination-pools/benchmarking/src/mock.rs
  substrate/frame/nomination-pools/src/mock.rs
  substrate/frame/nomination-pools/test-staking/src/mock.rs
  substrate/frame/offences/benchmarking/src/mock.rs
  substrate/frame/root-offences/src/lib.rs
  substrate/frame/root-offences/src/mock.rs
  substrate/frame/session/benchmarking/src/mock.rs
  substrate/frame/staking/CHANGELOG.md
  substrate/frame/staking/README.md
  substrate/frame/staking/runtime-api/Cargo.toml
  substrate/frame/staking/runtime-api/src/lib.rs
  substrate/frame/staking/src/benchmarking.rs
  substrate/frame/staking/src/ledger.rs
  substrate/frame/staking/src/lib.rs
  substrate/frame/staking/src/migrations.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/tests.rs
  substrate/frame/staking/src/weights.rs
  substrate/primitives/staking/src/lib.rs
Labels: A3-backport, T1-FRAME, T8-polkadot, D2-substantial

#2106 remove gum dependency on jaeger
  Cargo.lock
  polkadot/node/core/pvf/execute-worker/Cargo.toml
  polkadot/node/core/pvf/prepare-worker/Cargo.toml
  polkadot/node/gum/Cargo.toml
  polkadot/node/gum/src/lib.rs
Labels: T0-node

#2120 [ci] Revert CI_IMAGE variable
  .gitlab-ci.yml
Labels: R0-silent

#2021 Direct XCM `ExportMessage` fees for different bridges to different receiver accounts
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
  polkadot/runtime/rococo/src/xcm_config.rs
  polkadot/runtime/westend/src/xcm_config.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/xcm-builder/src/fee_handling.rs
  polkadot/xcm/xcm-builder/src/lib.rs
  polkadot/xcm/xcm-builder/src/tests/mock.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  polkadot/xcm/xcm-executor/src/traits/fee_manager.rs
Labels: T6-XCM, T15-bridges

#1714 Improve FRAME storage docs
  substrate/frame/bags-list/Cargo.toml
  substrate/frame/support/procedural/src/lib.rs
  substrate/frame/support/src/lib.rs
  substrate/frame/support/src/storage/types/counted_map.rs
  substrate/frame/support/src/storage/types/counted_nmap.rs
  substrate/frame/support/src/storage/types/double_map.rs
  substrate/frame/support/src/storage/types/map.rs
  substrate/frame/support/src/storage/types/mod.rs
  substrate/frame/support/src/storage/types/nmap.rs
  substrate/frame/support/src/storage/types/value.rs
Labels: T1-FRAME, T11-documentation

#2112 remove transitional code wrt executor parameters
  polkadot/runtime/parachains/src/runtime_api_impl/v7.rs
Labels: T0-node

#2050 fix substrate-node-template generation
  substrate/scripts/ci/node-template-release.sh
  substrate/scripts/ci/node-template-release/src/main.rs
Labels: R0-silent

#2018 Build workers for testing on demand
  polkadot/node/core/pvf/src/testing.rs
Labels: T0-node

#2118 [FRAME] Short-circuit fungible self transfer
  bridges/primitives/relayers/src/lib.rs
  cumulus/primitives/utility/src/lib.rs
  polkadot/xcm/xcm-builder/src/fungibles_adapter.rs
  substrate/frame/balances/src/tests/currency_tests.rs
  substrate/frame/broker/src/test_fungibles.rs
  substrate/frame/nis/src/lib.rs
  substrate/frame/support/src/traits/tokens/fungible/item_of.rs
  substrate/frame/support/src/traits/tokens/fungible/regular.rs
  substrate/frame/support/src/traits/tokens/fungibles/regular.rs
  substrate/frame/support/src/traits/tokens/pay.rs
Labels: T1-FRAME

#2127 Fix for failed pipeline `test-doc`
  substrate/frame/support/src/storage/types/map.rs
Labels: T1-FRAME

#2114 Bandersnatch dependency update
  .config/zepter.yaml
  Cargo.lock
  substrate/primitives/core/Cargo.toml
  substrate/primitives/crypto/ec-utils/Cargo.toml
Labels: T0-node

#2128 Added `bridge-hub-westend-runtime` to the `short-benchmarks` pipeline
  .gitlab/pipeline/short-benchmarks.yml
Labels: T9-cumulus

#1809 Make `ExecResult` encodable
  substrate/frame/contracts/src/exec.rs
Labels: A1-insubstantial, T7-smart_contracts

#2131 impl Clone for `MemoryKeystore`
  substrate/primitives/keystore/src/testing.rs
Labels: R0-silent

#2129 XCM MultiAssets: sort after reanchoring
  polkadot/xcm/src/v3/multiasset.rs
Labels: T6-XCM

#1932 Create new trait for non-dedup storage decode
  substrate/frame/support/src/storage/bounded_btree_map.rs
  substrate/frame/support/src/storage/bounded_btree_set.rs
  substrate/frame/support/src/storage/mod.rs
  substrate/frame/support/src/storage/types/double_map.rs
  substrate/frame/support/src/storage/types/map.rs
  substrate/frame/support/src/storage/types/value.rs
Labels: I2-bug, T1-FRAME, D0-easy

#2139 [testnet] Allow governance to control fees for Rococo <> Westend bridge
  Cargo.lock
  bridges/bin/runtime-common/src/messages_benchmarking.rs
  bridges/bin/runtime-common/src/messages_generation.rs
  bridges/primitives/chain-asset-hub-rococo/src/lib.rs
  bridges/primitives/chain-asset-hub-westend/src/lib.rs
  bridges/primitives/chain-asset-hub-wococo/src/lib.rs
  bridges/primitives/chain-bridge-hub-rococo/src/lib.rs
  bridges/primitives/chain-bridge-hub-westend/src/lib.rs
  bridges/primitives/chain-bridge-hub-wococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases.rs
Labels: R0-silent, T15-bridges

#2145 skip trigger for review bot on draft PRs
  .github/workflows/review-trigger.yml
Labels: R0-silent

#2144 substrate: sysinfo: Expose failed hardware requirements
  Cargo.lock
  cumulus/parachain-template/node/src/service.rs
  cumulus/polkadot-parachain/src/service.rs
  polkadot/node/service/src/lib.rs
  substrate/bin/node/cli/src/service.rs
  substrate/client/sysinfo/Cargo.toml
  substrate/client/sysinfo/src/sysinfo.rs
Labels: R0-silent, T0-node

#2148 Update Kusama Parachains Bootnode
  cumulus/parachains/chain-specs/asset-hub-kusama.json
  cumulus/parachains/chain-specs/bridge-hub-kusama.json
Labels: R0-silent

#2045 Do not request blocks below the common number when syncing
  substrate/client/network/sync/src/blocks.rs
  substrate/client/network/sync/src/chain_sync.rs
  substrate/client/network/sync/src/chain_sync/test.rs
Labels: R0-silent, T0-node

#2132 Convert `SyncingEngine::run` to use `tokio::select!` instead of polling
  substrate/client/network/sync/Cargo.toml
  substrate/client/network/sync/src/block_announce_validator.rs
  substrate/client/network/sync/src/engine.rs
  substrate/client/network/sync/src/pending_responses.rs
Labels: R0-silent, T0-node

#1583 Add deprecation checklist document for Substrate
  docs/DEPRECATION_CHECKLIST.md
Labels: T11-documentation

#1192 Tracking/limiting memory allocator
  Cargo.lock
  polkadot/node/core/pvf/common/src/error.rs
  polkadot/node/core/pvf/common/src/executor_intf.rs
  polkadot/node/core/pvf/common/src/prepare.rs
  polkadot/node/core/pvf/prepare-worker/Cargo.toml
  polkadot/node/core/pvf/prepare-worker/benches/prepare_rococo_runtime.rs
  polkadot/node/core/pvf/prepare-worker/src/executor_intf.rs
  polkadot/node/core/pvf/prepare-worker/src/lib.rs
  polkadot/node/core/pvf/src/metrics.rs
  polkadot/node/core/pvf/src/prepare/pool.rs
  polkadot/node/core/pvf/src/prepare/worker_intf.rs
  polkadot/node/core/pvf/src/testing.rs
  polkadot/node/core/pvf/tests/it/adder.rs
  polkadot/node/core/pvf/tests/it/main.rs
  polkadot/node/malus/Cargo.toml
  polkadot/node/tracking-allocator/Cargo.toml
  polkadot/node/tracking-allocator/src/lib.rs
  polkadot/primitives/src/v6/executor_params.rs
  polkadot/src/main.rs
Labels: A0-needs_burnin

#2099 `sc-block-builder`: Remove `BlockBuilderProvider`
  Cargo.lock
  cumulus/test/client/src/block_builder.rs
  cumulus/test/service/benches/block_import.rs
  cumulus/test/service/benches/block_import_glutton.rs
  cumulus/test/service/benches/block_production.rs
  cumulus/test/service/benches/block_production_glutton.rs
  cumulus/test/service/benches/validate_block.rs
  cumulus/test/service/src/bench_utils.rs
  polkadot/node/test/client/src/block_builder.rs
  substrate/bin/node/cli/benches/block_production.rs
  substrate/bin/node/testing/src/bench.rs
  substrate/client/basic-authorship/Cargo.toml
  substrate/client/basic-authorship/src/basic_authorship.rs
  substrate/client/block-builder/Cargo.toml
  substrate/client/block-builder/src/lib.rs
  substrate/client/consensus/aura/src/lib.rs
  substrate/client/consensus/babe/src/tests.rs
  substrate/client/consensus/beefy/src/tests.rs
  substrate/client/consensus/grandpa/rpc/src/lib.rs
  substrate/client/consensus/grandpa/src/finality_proof.rs
  substrate/client/consensus/grandpa/src/tests.rs
  substrate/client/consensus/grandpa/src/voting_rule.rs
  substrate/client/consensus/grandpa/src/warp_proof.rs
  substrate/client/merkle-mountain-range/src/test_utils.rs
  substrate/client/network/bitswap/src/lib.rs
  substrate/client/network/sync/src/chain_sync/test.rs
  substrate/client/network/test/src/block_import.rs
  substrate/client/network/test/src/lib.rs
  substrate/client/offchain/src/lib.rs
  substrate/client/rpc-spec-v2/src/archive/tests.rs
  substrate/client/rpc-spec-v2/src/chain_head/subscription/inner.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
  substrate/client/rpc/src/chain/tests.rs
  substrate/client/rpc/src/dev/tests.rs
  substrate/client/rpc/src/state/tests.rs
  substrate/client/service/Cargo.toml
  substrate/client/service/src/client/client.rs
  substrate/client/service/test/src/client/mod.rs
  substrate/client/transaction-pool/tests/pool.rs
  substrate/primitives/api/src/lib.rs
  substrate/primitives/api/test/tests/runtime_calls.rs
  substrate/test-utils/runtime/client/src/block_builder_ext.rs
  substrate/test-utils/runtime/client/src/trait_tests.rs
  substrate/test-utils/runtime/src/lib.rs
  substrate/utils/frame/benchmarking-cli/src/block/bench.rs
  substrate/utils/frame/benchmarking-cli/src/block/cmd.rs
  substrate/utils/frame/benchmarking-cli/src/extrinsic/bench.rs
  substrate/utils/frame/benchmarking-cli/src/extrinsic/cmd.rs
  substrate/utils/frame/benchmarking-cli/src/overhead/cmd.rs
Labels: T0-node

#2048 Identity pallet improvements
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/pallet_identity.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/pallet_identity.rs
  substrate/bin/node/runtime/src/impls.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/alliance/src/lib.rs
  substrate/frame/alliance/src/mock.rs
  substrate/frame/alliance/src/tests.rs
  substrate/frame/identity/src/benchmarking.rs
  substrate/frame/identity/src/legacy.rs
  substrate/frame/identity/src/lib.rs
  substrate/frame/identity/src/tests.rs
  substrate/frame/identity/src/types.rs
  substrate/frame/identity/src/weights.rs
Labels: T2-pallets

#2147 cumulus test runtime: remove `GenesisExt`
  cumulus/test/client/src/lib.rs
  cumulus/test/runtime/src/lib.rs
  cumulus/test/runtime/src/test_pallet.rs
  cumulus/test/service/src/chain_spec.rs
  cumulus/zombienet/tests/0002-pov_recovery.toml
  cumulus/zombienet/tests/0005-migrate_solo_to_para.toml
Labels: T10-tests

#2151 Speed up try runtime checks for pallet-bags-list
  substrate/frame/bags-list/src/list/mod.rs
Labels: T10-tests

#2153 Speed up nominator state checks in staking pallet
  substrate/frame/staking/src/pallet/impls.rs
Labels: T10-tests

#2150 Update bootnode lists
  cumulus/parachains/chain-specs/asset-hub-kusama.json
  cumulus/parachains/chain-specs/asset-hub-polkadot.json
  cumulus/parachains/chain-specs/asset-hub-rococo.json
  cumulus/parachains/chain-specs/asset-hub-westend.json
  cumulus/parachains/chain-specs/bridge-hub-polkadot.json
  cumulus/parachains/chain-specs/bridge-hub-rococo.json
  cumulus/parachains/chain-specs/bridge-hub-westend.json
  cumulus/parachains/chain-specs/collectives-polkadot.json
  cumulus/parachains/chain-specs/collectives-westend.json
  cumulus/parachains/chain-specs/contracts-rococo.json
  polkadot/node/service/chain-specs/rococo.json
  polkadot/node/service/chain-specs/westend.json
Labels: R0-silent

#2156 Tracking allocator: mark `Spinlock::unlock()` as unsafe and provide a safety contract
  polkadot/node/tracking-allocator/src/lib.rs
Labels: T0-node

#2161 Fix update-ui-tests.sh
  scripts/update-ui-tests.sh
Labels: R0-silent

#2159 [CI] Update deps
  .gitlab/pipeline/check.yml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/glutton/glutton-kusama/Cargo.toml
  substrate/frame/bags-list/Cargo.toml
Labels: R0-silent

#2143 Get rid of `NetworkService` in `ChainSync`
  substrate/bin/minimal/runtime/Cargo.toml
  substrate/client/network/sync/src/chain_sync.rs
  substrate/client/network/sync/src/chain_sync/test.rs
  substrate/client/network/sync/src/engine.rs
Labels: R0-silent, T0-node

#2168 `serde_json`: bumped to 1.0.108
  Cargo.lock
  cumulus/client/relay-chain-rpc-interface/Cargo.toml
  cumulus/parachain-template/node/Cargo.toml
  cumulus/parachains/integration-tests/emulated/common/Cargo.toml
  cumulus/polkadot-parachain/Cargo.toml
  cumulus/test/service/Cargo.toml
  polkadot/node/service/Cargo.toml
  polkadot/node/test/service/Cargo.toml
  polkadot/node/zombienet-backchannel/Cargo.toml
  polkadot/runtime/common/Cargo.toml
  polkadot/runtime/parachains/Cargo.toml
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/test-runtime/Cargo.toml
  polkadot/runtime/westend/Cargo.toml
  substrate/bin/minimal/node/Cargo.toml
  substrate/bin/node-template/node/Cargo.toml
  substrate/bin/node-template/runtime/Cargo.toml
  substrate/bin/node/bench/Cargo.toml
  substrate/bin/node/cli/Cargo.toml
  substrate/bin/node/executor/Cargo.toml
  substrate/bin/node/runtime/Cargo.toml
  substrate/bin/utils/chain-spec-builder/Cargo.toml
  substrate/client/chain-spec/Cargo.toml
  substrate/client/cli/Cargo.toml
  substrate/client/consensus/babe/rpc/Cargo.toml
  substrate/client/consensus/beefy/rpc/Cargo.toml
  substrate/client/consensus/grandpa/Cargo.toml
  substrate/client/keystore/Cargo.toml
  substrate/client/merkle-mountain-range/rpc/Cargo.toml
  substrate/client/network/Cargo.toml
  substrate/client/rpc-api/Cargo.toml
  substrate/client/rpc-servers/Cargo.toml
  substrate/client/rpc-spec-v2/Cargo.toml
  substrate/client/rpc/Cargo.toml
  substrate/client/service/Cargo.toml
  substrate/client/sync-state-rpc/Cargo.toml
  substrate/client/sysinfo/Cargo.toml
  substrate/client/telemetry/Cargo.toml
  substrate/client/transaction-pool/api/Cargo.toml
  substrate/frame/support/Cargo.toml
  substrate/frame/transaction-payment/Cargo.toml
  substrate/frame/transaction-payment/asset-tx-payment/Cargo.toml
  substrate/primitives/consensus/sassafras/Cargo.toml
  substrate/primitives/core/Cargo.toml
  substrate/primitives/genesis-builder/Cargo.toml
  substrate/primitives/rpc/Cargo.toml
  substrate/primitives/runtime/Cargo.toml
  substrate/test-utils/client/Cargo.toml
  substrate/test-utils/runtime/Cargo.toml
  substrate/utils/frame/benchmarking-cli/Cargo.toml
  substrate/utils/frame/rpc/state-trie-migration-rpc/Cargo.toml
  substrate/utils/frame/try-runtime/cli/Cargo.toml
Labels: T0-node

#1982 Add force remove vesting
  polkadot/runtime/rococo/src/weights/pallet_vesting.rs
  polkadot/runtime/westend/src/weights/pallet_vesting.rs
  substrate/frame/vesting/src/benchmarking.rs
  substrate/frame/vesting/src/lib.rs
  substrate/frame/vesting/src/tests.rs
  substrate/frame/vesting/src/weights.rs
Labels: I5-enhancement, T2-pallets

#2173 rename benchmark
  substrate/frame/alliance/src/benchmarking.rs
Labels: T2-pallets, T10-tests, T12-benchmarks

#2179 minor: overseer availability-distribution message declaration update
  polkadot/node/overseer/src/lib.rs
Labels: T0-node, T8-polkadot

#1805 TryDecodeEntireState check for storage types and pallets
  prdoc/pr_1805.prdoc
  substrate/bin/node-template/runtime/src/lib.rs
  substrate/frame/executive/src/lib.rs
  substrate/frame/glutton/src/lib.rs
  substrate/frame/support/Cargo.toml
  substrate/frame/support/procedural/src/pallet/expand/event.rs
  substrate/frame/support/procedural/src/pallet/expand/storage.rs
  substrate/frame/support/procedural/src/pallet/parse/storage.rs
  substrate/frame/support/src/storage/generator/mod.rs
  substrate/frame/support/src/storage/types/counted_map.rs
  substrate/frame/support/src/storage/types/counted_nmap.rs
  substrate/frame/support/src/storage/types/mod.rs
  substrate/frame/support/src/storage/types/value.rs
  substrate/frame/support/src/traits.rs
  substrate/frame/support/src/traits/storage.rs
  substrate/frame/support/src/traits/try_runtime/decode_entire_state.rs
  substrate/frame/support/src/traits/try_runtime/mod.rs
  substrate/frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr
  substrate/frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen_unnamed.stderr
Labels: T1-FRAME

#1297 Initialise on-chain `StorageVersion` for pallets added after genesis
  substrate/frame/executive/src/lib.rs
  substrate/frame/support/procedural/src/pallet/expand/hooks.rs
  substrate/frame/support/src/lib.rs
  substrate/frame/support/src/migrations.rs
  substrate/frame/support/src/traits.rs
  substrate/frame/support/src/traits/hooks.rs
  substrate/frame/support/src/traits/metadata.rs
  substrate/frame/support/test/tests/pallet.rs
Labels: T1-FRAME

#2191 zombienet_tests: Fix genesis error in 0006-parachains-max-tranche0.toml
  polkadot/zombienet_tests/functional/0006-parachains-max-tranche0.toml
Labels: R0-silent, T10-tests

#2187 mark pallet-asset-rate optional in polkadot-runtime-common
  polkadot/runtime/common/Cargo.toml
Labels: R0-silent

#2205 Fix "slashaed" typo
  substrate/frame/referenda/src/lib.rs
Labels: R0-silent, T11-documentation

#2202 Disable incoming light-client connections for minimal relay node
  cumulus/client/relay-chain-minimal-node/src/network.rs
Labels: T0-node, T9-cumulus

#2107 XCM builder pattern
  Cargo.lock
  polkadot/xcm/procedural/Cargo.toml
  polkadot/xcm/procedural/src/builder_pattern.rs
  polkadot/xcm/procedural/src/lib.rs
  polkadot/xcm/procedural/tests/ui.rs
  polkadot/xcm/procedural/tests/ui/builder_pattern.rs
  polkadot/xcm/procedural/tests/ui/builder_pattern.stderr
  polkadot/xcm/src/v3/mod.rs
  polkadot/xcm/xcm-simulator/example/src/lib.rs
  prdoc/pr_2107.prdoc
Labels: T6-XCM

#2204 [testnets][xcm-emulator] add bridge-hub-westend and hook it up to emulator
  Cargo.lock
  Cargo.toml
  cumulus/parachains/integration-tests/emulated/bridges/bridge-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/bridges/bridge-hub-westend/src/tests/example.rs
  cumulus/parachains/integration-tests/emulated/bridges/bridge-hub-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/bridges/bridge-hub-westend/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/common/Cargo.toml
  cumulus/parachains/integration-tests/emulated/common/src/constants.rs
  cumulus/parachains/integration-tests/emulated/common/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
Labels: R0-silent

#2197 feat(frame-support-procedural): add `automaticaly_derived` attr to `NoBound` derives
  substrate/frame/support/procedural/src/no_bound/clone.rs
  substrate/frame/support/procedural/src/no_bound/debug.rs
  substrate/frame/support/procedural/src/no_bound/default.rs
  substrate/frame/support/procedural/src/no_bound/partial_eq.rs
  substrate/frame/support/test/tests/derive_no_bound.rs
Labels: T1-FRAME

#2165 Add `sudo::remove_key`
  polkadot/runtime/rococo/src/weights/pallet_sudo.rs
  polkadot/runtime/westend/src/weights/pallet_sudo.rs
  prdoc/pr_2165.prdoc
  substrate/frame/sudo/src/benchmarking.rs
  substrate/frame/sudo/src/lib.rs
  substrate/frame/sudo/src/mock.rs
  substrate/frame/sudo/src/tests.rs
  substrate/frame/sudo/src/weights.rs
Labels: T2-pallets

#2135 Adding gitspiegel-trigger workflow
  .github/workflows/gitspiegel-trigger.yml
Labels: R0-silent

#2214 validate-block: Fix `TrieCache` implementation
  Cargo.lock
  cumulus/pallets/parachain-system/Cargo.toml
  cumulus/pallets/parachain-system/src/validate_block/tests.rs
  cumulus/pallets/parachain-system/src/validate_block/trie_cache.rs
  cumulus/test/runtime/src/test_pallet.rs
  substrate/primitives/state-machine/src/trie_backend.rs
  substrate/test-utils/client/src/client_ext.rs
  substrate/test-utils/client/src/lib.rs
Labels: T9-cumulus

#2190 `sc-chain-spec`: add support for custom host functions
  substrate/bin/utils/chain-spec-builder/src/lib.rs
  substrate/client/chain-spec/src/chain_spec.rs
  substrate/client/chain-spec/src/genesis_config_builder.rs
Labels: T0-node

#2232 integrations-test: `build_genesis_storage` name fix
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-rococo/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-westend/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-rococo/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-westend/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/testing/penpal/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/relays/rococo/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/relays/westend/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/common/src/lib.rs
Labels: T10-tests

#2223 Add prospective-parachain subsystem to minimal-relay-node + QoL improvements
  Cargo.lock
  cumulus/client/relay-chain-minimal-node/Cargo.toml
  cumulus/client/relay-chain-minimal-node/src/collator_overseer.rs
  cumulus/client/relay-chain-minimal-node/src/lib.rs
  cumulus/client/relay-chain-rpc-interface/src/rpc_client.rs
  cumulus/client/service/src/lib.rs
Labels: T0-node, T9-cumulus

#2231 Make PalletInfo fields public
  polkadot/xcm/src/v3/mod.rs
Labels: R0-silent, T6-XCM

#2230 BridgeHub Runtimes: Change registration order of `MessageQueue` pallet
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
Labels: R0-silent

#2229 Rococo: Build two versions of the wasm binary
  polkadot/node/service/src/chain_spec.rs
  polkadot/runtime/rococo/build.rs
  polkadot/runtime/rococo/constants/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
Labels: R0-silent

#2224 Add RadiumBlock Bootnodes for parachains
  cumulus/parachains/chain-specs/asset-hub-kusama.json
  cumulus/parachains/chain-specs/asset-hub-polkadot.json
  cumulus/parachains/chain-specs/asset-hub-westend.json
  cumulus/parachains/chain-specs/bridge-hub-kusama.json
  cumulus/parachains/chain-specs/bridge-hub-polkadot.json
  cumulus/parachains/chain-specs/bridge-hub-westend.json
  cumulus/parachains/chain-specs/collectives-polkadot.json
Labels: R0-silent

#2239 Remove unnecessary map_error
  polkadot/xcm/xcm-builder/src/routing.rs
Labels: T6-XCM

#2029 Add descriptions to all published crates
  cumulus/client/cli/Cargo.toml
  cumulus/client/collator/Cargo.toml
  cumulus/client/relay-chain-inprocess-interface/Cargo.toml
  cumulus/client/relay-chain-interface/Cargo.toml
  cumulus/client/relay-chain-minimal-node/Cargo.toml
  cumulus/client/relay-chain-rpc-interface/Cargo.toml
  cumulus/client/service/Cargo.toml
  cumulus/pallets/xcm/Cargo.toml
  cumulus/pallets/xcmp-queue/Cargo.toml
  cumulus/parachains/pallets/parachain-info/Cargo.toml
  cumulus/parachains/pallets/ping/Cargo.toml
  cumulus/primitives/aura/Cargo.toml
  cumulus/primitives/core/Cargo.toml
  cumulus/primitives/parachain-inherent/Cargo.toml
  cumulus/primitives/utility/Cargo.toml
  cumulus/test/relay-sproof-builder/Cargo.toml
  polkadot/erasure-coding/Cargo.toml
  polkadot/node/collation-generation/Cargo.toml
  polkadot/node/core/approval-voting/Cargo.toml
  polkadot/node/core/av-store/Cargo.toml
  polkadot/node/core/backing/Cargo.toml
  polkadot/node/core/bitfield-signing/Cargo.toml
  polkadot/node/core/chain-api/Cargo.toml
  polkadot/node/core/dispute-coordinator/Cargo.toml
  polkadot/node/core/parachains-inherent/Cargo.toml
  polkadot/node/core/prospective-parachains/Cargo.toml
  polkadot/node/core/provisioner/Cargo.toml
  polkadot/node/core/runtime-api/Cargo.toml
  polkadot/node/network/approval-distribution/Cargo.toml
  polkadot/node/network/availability-distribution/Cargo.toml
  polkadot/node/network/availability-recovery/Cargo.toml
  polkadot/node/network/bitfield-distribution/Cargo.toml
  polkadot/node/network/bridge/Cargo.toml
  polkadot/node/network/collator-protocol/Cargo.toml
  polkadot/node/network/dispute-distribution/Cargo.toml
  polkadot/node/network/gossip-support/Cargo.toml
  polkadot/node/overseer/Cargo.toml
  polkadot/node/service/Cargo.toml
  polkadot/primitives/Cargo.toml
  polkadot/rpc/Cargo.toml
  polkadot/runtime/common/slot_range_helper/Cargo.toml
  polkadot/runtime/metrics/Cargo.toml
  polkadot/runtime/parachains/Cargo.toml
  polkadot/statement-table/Cargo.toml
  polkadot/utils/generate-bags/Cargo.toml
  polkadot/xcm/pallet-xcm-benchmarks/Cargo.toml
  substrate/bin/minimal/runtime/Cargo.toml
Labels: R0-silent

#2259 Add license to tracking-allocator and add staging-prefix
  polkadot/node/tracking-allocator/Cargo.toml
Labels: A1-insubstantial

#2260 Don't publish frame and deps
  substrate/bin/minimal/runtime/Cargo.toml
  substrate/frame/Cargo.toml
  substrate/frame/examples/Cargo.toml
  substrate/frame/examples/frame-crate/Cargo.toml
Labels: A1-insubstantial

#2228 sc-state-db: Keep track of `LAST_PRUNED` after warp syncing
  substrate/client/state-db/src/pruning.rs
Labels: T0-node

#2261 Add license to tracking-allocator and add staging-prefix
  Cargo.lock
  polkadot/node/core/pvf/prepare-worker/Cargo.toml
  polkadot/node/tracking-allocator/Cargo.toml
Labels: A1-insubstantial

#2262 Bulk Assigner Test Implementations
  polkadot/runtime/parachains/src/assigner_bulk/mod.rs
  polkadot/runtime/parachains/src/assigner_bulk/tests.rs
Labels: T8-polkadot

#2246 Contracts move fixtures to new crate
  Cargo.lock
  Cargo.toml
  substrate/frame/contracts/Cargo.toml
  substrate/frame/contracts/fixtures/Cargo.toml
  substrate/frame/contracts/fixtures/data/account_reentrance_count_call.wat
  substrate/frame/contracts/fixtures/data/add_remove_delegate_dependency.wat
  substrate/frame/contracts/fixtures/data/balance.wat
  substrate/frame/contracts/fixtures/data/call.wat
  substrate/frame/contracts/fixtures/data/call_return_code.wat
  substrate/frame/contracts/fixtures/data/call_runtime.wat
  substrate/frame/contracts/fixtures/data/call_runtime_and_call.wat
  substrate/frame/contracts/fixtures/data/call_with_limit.wat
  substrate/frame/contracts/fixtures/data/caller_contract.wat
  substrate/frame/contracts/fixtures/data/chain_extension.wat
  substrate/frame/contracts/fixtures/data/chain_extension_temp_storage.wat
  substrate/frame/contracts/fixtures/data/create_storage_and_call.wat
  substrate/frame/contracts/fixtures/data/create_storage_and_instantiate.wat
  substrate/frame/contracts/fixtures/data/crypto_hashes.wat
  substrate/frame/contracts/fixtures/data/debug_message_invalid_utf8.wat
  substrate/frame/contracts/fixtures/data/debug_message_logging_disabled.wat
  substrate/frame/contracts/fixtures/data/debug_message_works.wat
  substrate/frame/contracts/fixtures/data/delegate_call.wat
  substrate/frame/contracts/fixtures/data/delegate_call_lib.wat
  substrate/frame/contracts/fixtures/data/delegate_call_simple.wat
  substrate/frame/contracts/fixtures/data/destroy_and_transfer.wat
  substrate/frame/contracts/fixtures/data/drain.wat
  substrate/frame/contracts/fixtures/data/dummy.wat
  substrate/frame/contracts/fixtures/data/ecdsa_recover.wat
  substrate/frame/contracts/fixtures/data/event_and_return_on_deploy.wat
  substrate/frame/contracts/fixtures/data/event_size.wat
  substrate/frame/contracts/fixtures/data/float_instruction.wat
  substrate/frame/contracts/fixtures/data/instantiate_return_code.wat
  substrate/frame/contracts/fixtures/data/invalid_contract_no_call.wat
  substrate/frame/contracts/fixtures/data/invalid_contract_no_memory.wat
  substrate/frame/contracts/fixtures/data/invalid_module.wat
  substrate/frame/contracts/fixtures/data/multi_store.wat
  substrate/frame/contracts/fixtures/data/new_set_code_hash_contract.wat
  substrate/frame/contracts/fixtures/data/ok_trap_revert.wat
  substrate/frame/contracts/fixtures/data/reentrance_count_call.wat
  substrate/frame/contracts/fixtures/data/reentrance_count_delegated_call.wat
  substrate/frame/contracts/fixtures/data/return_with_data.wat
  substrate/frame/contracts/fixtures/data/run_out_of_gas.wat
  substrate/frame/contracts/fixtures/data/run_out_of_gas_start_fn.wat
  substrate/frame/contracts/fixtures/data/seal_input_noop.wat
  substrate/frame/contracts/fixtures/data/seal_input_once.wat
  substrate/frame/contracts/fixtures/data/seal_input_twice.wat
  substrate/frame/contracts/fixtures/data/self_destruct.wat
  substrate/frame/contracts/fixtures/data/self_destructing_constructor.wat
  substrate/frame/contracts/fixtures/data/set_code_hash.wat
  substrate/frame/contracts/fixtures/data/set_empty_storage.wat
  substrate/frame/contracts/fixtures/data/sr25519_verify.wat
  substrate/frame/contracts/fixtures/data/storage_size.wat
  substrate/frame/contracts/fixtures/data/store_call.wat
  substrate/frame/contracts/fixtures/data/store_deploy.wat
  substrate/frame/contracts/fixtures/data/transfer_return_code.wat
  substrate/frame/contracts/fixtures/src/lib.rs
  substrate/frame/contracts/src/tests.rs
Labels: R0-silent

#2227 [pallet-message-queue] Implement impl_trait_for_tuples for QueuePausedQuery
  substrate/frame/support/src/traits/messages.rs
Labels: T1-FRAME

#2264 Improve `VersionedMigration` naming conventions
  polkadot/runtime/common/src/assigned_slots/migration.rs
  polkadot/runtime/common/src/paras_registrar/migration.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/xcm/pallet-xcm/src/migration.rs
  substrate/frame/society/src/migrations.rs
  substrate/frame/support/src/migrations.rs
Labels: T1-FRAME

#2086 Contracts: Add XCM traits to interface with contracts
  cumulus/parachains/runtimes/assets/asset-hub-kusama/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/assets/asset-hub-polkadot/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_xcm.rs
  polkadot/runtime/rococo/src/weights/pallet_xcm.rs
  polkadot/runtime/westend/src/weights/pallet_xcm.rs
  polkadot/xcm/pallet-xcm/Cargo.toml
  polkadot/xcm/pallet-xcm/src/benchmarking.rs
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/xcm-builder/src/controller.rs
  polkadot/xcm/xcm-builder/src/lib.rs
  polkadot/xcm/xcm-builder/src/tests/mock.rs
  polkadot/xcm/xcm-executor/src/traits/on_response.rs
  prdoc/pr_2086.prdoc
Labels: T6-XCM

#2275 Add `s` utility function to frame support
  substrate/primitives/runtime/src/lib.rs
Labels: T0-node

#2180 Unify `ChainSync` actions under one enum
  substrate/client/network/sync/src/chain_sync.rs
  substrate/client/network/sync/src/chain_sync/test.rs
  substrate/client/network/sync/src/engine.rs
Labels: R0-silent, T0-node

#2244 PVF host: Make unavailable security features print a warning
  polkadot/node/core/pvf/src/host.rs
  polkadot/node/core/pvf/src/security.rs
Labels: T0-node

#2181 pallet-grandpa: Remove `GRANDPA_AUTHORITIES_KEY`
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  substrate/client/consensus/grandpa/src/lib.rs
  substrate/frame/grandpa/src/lib.rs
  substrate/frame/grandpa/src/migrations.rs
  substrate/frame/grandpa/src/migrations/v5.rs
  substrate/primitives/consensus/grandpa/src/lib.rs
Labels: T1-FRAME

#1926 Adds syntax for marking calls feeless
  Cargo.lock
  Cargo.toml
  prdoc/pr_1926.prdoc
  substrate/bin/node/cli/Cargo.toml
  substrate/bin/node/cli/src/service.rs
  substrate/bin/node/runtime/Cargo.toml
  substrate/bin/node/runtime/src/lib.rs
  substrate/bin/node/testing/Cargo.toml
  substrate/bin/node/testing/src/keyring.rs
  substrate/frame/examples/kitchensink/src/lib.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/call.rs
  substrate/frame/support/procedural/src/lib.rs
  substrate/frame/support/procedural/src/pallet/expand/call.rs
  substrate/frame/support/procedural/src/pallet/parse/call.rs
  substrate/frame/support/src/dispatch.rs
  substrate/frame/support/src/lib.rs
  substrate/frame/support/test/tests/pallet_ui/call_feeless_invalid_closure_arg1.rs
  substrate/frame/support/test/tests/pallet_ui/call_feeless_invalid_closure_arg1.stderr
  substrate/frame/support/test/tests/pallet_ui/call_feeless_invalid_closure_arg2.rs
  substrate/frame/support/test/tests/pallet_ui/call_feeless_invalid_closure_arg2.stderr
  substrate/frame/support/test/tests/pallet_ui/call_feeless_invalid_closure_arg3.rs
  substrate/frame/support/test/tests/pallet_ui/call_feeless_invalid_closure_arg3.stderr
  substrate/frame/support/test/tests/pallet_ui/call_feeless_invalid_closure_return.rs
  substrate/frame/support/test/tests/pallet_ui/call_feeless_invalid_closure_return.stderr
  substrate/frame/support/test/tests/pallet_ui/call_feeless_invalid_type.rs
  substrate/frame/support/test/tests/pallet_ui/call_feeless_invalid_type.stderr
  substrate/frame/support/test/tests/pallet_ui/call_invalid_attr.stderr
  substrate/frame/support/test/tests/pallet_ui/call_invalid_origin_type.stderr
  substrate/frame/support/test/tests/pallet_ui/pass/feeless_call.rs
  substrate/frame/transaction-payment/skip-feeless-payment/Cargo.toml
  substrate/frame/transaction-payment/skip-feeless-payment/src/lib.rs
  substrate/frame/transaction-payment/skip-feeless-payment/src/mock.rs
  substrate/frame/transaction-payment/skip-feeless-payment/src/tests.rs
Labels: I5-enhancement, T1-FRAME

#2294 Skip zombienet CI job until PolkadotJS includes `SkipCheckIfFeeless` extension
  .gitlab/pipeline/zombienet/substrate.yml
Labels: R0-silent

#2299 Add CI to claim crates
  .github/workflows/claim-crates.yml
Labels: A1-insubstantial

#2298 doc(client/cli/src/arg_enums.rs): fix typo ✍️
  substrate/client/cli/src/arg_enums.rs
Labels: A1-insubstantial, R0-silent

#2289 review-bot: trigger only on review approvals
  .github/workflows/review-trigger.yml
Labels: R0-silent

#2287 cumulus-pov-recovery: check pov_hash instead of reencoding data
  cumulus/client/pov-recovery/src/active_candidate_recovery.rs
  cumulus/client/pov-recovery/src/lib.rs
  cumulus/client/relay-chain-minimal-node/src/collator_overseer.rs
  polkadot/node/network/availability-recovery/src/lib.rs
  polkadot/node/network/availability-recovery/src/task.rs
Labels: I9-optimisation, T9-cumulus

#2066 Fix `ecdsa_bls` verify in BEEFY primitives
  substrate/primitives/consensus/beefy/src/lib.rs
  substrate/primitives/core/src/paired_crypto.rs
Labels: T0-node

#2277 Bulk assigner tests update
  polkadot/runtime/parachains/src/assigner_bulk/mod.rs
  polkadot/runtime/parachains/src/assigner_bulk/tests.rs
  polkadot/runtime/parachains/src/mock.rs
Labels: T8-polkadot

#2288 Fix `expect_pallet` benchmarks not relaying on hard-coded `frame_system` dependency version
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/mod.rs
Labels: T6-XCM

#2305 Add details in `--dev` cli flag documentation
  substrate/client/cli/src/params/shared_params.rs
Labels: R0-silent

#2251 xcm-emulator: add Rococo<>Westend bridge and add tests for assets transfers over the bridge
  Cargo.lock
  Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-wococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-wococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-westend/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-wococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-wococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/testing/penpal/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/relays/wococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/relays/wococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/common/src/impls.rs
  cumulus/parachains/integration-tests/emulated/networks/rococo-westend-system/Cargo.toml
  cumulus/parachains/integration-tests/emulated/networks/rococo-westend-system/src/lib.rs
  cumulus/parachains/integration-tests/emulated/networks/wococo-system/Cargo.toml
  cumulus/parachains/integration-tests/emulated/networks/wococo-system/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/send_xcm.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/send_xcm.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/teleport.rs
Labels: R0-silent

#2304 PVF: fix detection of unshare-and-change-root security capability
  Cargo.lock
  polkadot/node/core/candidate-validation/src/lib.rs
  polkadot/node/core/pvf/Cargo.toml
  polkadot/node/core/pvf/benches/host_prepare_rococo_runtime.rs
  polkadot/node/core/pvf/common/src/worker/mod.rs
  polkadot/node/core/pvf/src/host.rs
  polkadot/node/core/pvf/src/security.rs
  polkadot/node/core/pvf/tests/it/main.rs
Labels: T0-node, I2-bug

#2318 Add environment to claim workflow
  .github/workflows/claim-crates.yml
Labels: A1-insubstantial

#2295 chainHead: Support multiple hashes for `chainHead_unpin` method
  Cargo.lock
  substrate/client/rpc-spec-v2/Cargo.toml
  substrate/client/rpc-spec-v2/src/chain_head/api.rs
  substrate/client/rpc-spec-v2/src/chain_head/chain_head.rs
  substrate/client/rpc-spec-v2/src/chain_head/subscription/inner.rs
  substrate/client/rpc-spec-v2/src/chain_head/subscription/mod.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement, D0-easy

#2296 chainHead: Remove `chainHead_genesis` method
  substrate/client/rpc-spec-v2/src/chain_head/api.rs
  substrate/client/rpc-spec-v2/src/chain_head/chain_head.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
  substrate/client/service/src/builder.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement, D0-easy

#1685 change prepare worker to use fork instead of threads
  Cargo.lock
  polkadot/node/core/candidate-validation/src/lib.rs
  polkadot/node/core/candidate-validation/src/tests.rs
  polkadot/node/core/pvf/benches/host_prepare_rococo_runtime.rs
  polkadot/node/core/pvf/common/Cargo.toml
  polkadot/node/core/pvf/common/src/error.rs
  polkadot/node/core/pvf/common/src/execute.rs
  polkadot/node/core/pvf/common/src/worker/mod.rs
  polkadot/node/core/pvf/execute-worker/Cargo.toml
  polkadot/node/core/pvf/execute-worker/src/lib.rs
  polkadot/node/core/pvf/prepare-worker/Cargo.toml
  polkadot/node/core/pvf/prepare-worker/src/lib.rs
  polkadot/node/core/pvf/src/error.rs
  polkadot/node/core/pvf/src/execute/queue.rs
  polkadot/node/core/pvf/src/execute/worker_intf.rs
  polkadot/node/core/pvf/src/prepare/pool.rs
  polkadot/node/core/pvf/src/prepare/worker_intf.rs
  polkadot/node/core/pvf/src/testing.rs
  polkadot/node/core/pvf/tests/it/main.rs
  polkadot/node/core/pvf/tests/it/process.rs
  polkadot/node/core/pvf/tests/it/worker_common.rs
  polkadot/roadmap/implementers-guide/src/node/utility/pvf-host-and-workers.md
  polkadot/scripts/list-syscalls/execute-worker-syscalls
  polkadot/scripts/list-syscalls/prepare-worker-syscalls
Labels: T0-node, C1-mentor

#1571 statement-distribution: support inactive local validator in grid
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  polkadot/node/network/statement-distribution/src/v2/tests/cluster.rs
  polkadot/node/network/statement-distribution/src/v2/tests/grid.rs
  polkadot/node/network/statement-distribution/src/v2/tests/mod.rs
  polkadot/node/network/statement-distribution/src/v2/tests/requests.rs
Labels: T8-polkadot

#2177 add NodeFeatures field to HostConfiguration and runtime API
  Cargo.lock
  cumulus/client/relay-chain-minimal-node/src/blockchain_rpc_client.rs
  cumulus/client/relay-chain-rpc-interface/src/rpc_client.rs
  cumulus/parachains/integration-tests/emulated/chains/relays/rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/relays/westend/src/lib.rs
  polkadot/node/core/runtime-api/src/cache.rs
  polkadot/node/core/runtime-api/src/lib.rs
  polkadot/node/core/runtime-api/src/tests.rs
  polkadot/node/subsystem-types/src/messages.rs
  polkadot/node/subsystem-types/src/runtime_client.rs
  polkadot/node/subsystem-util/src/runtime/mod.rs
  polkadot/primitives/Cargo.toml
  polkadot/primitives/src/runtime_api.rs
  polkadot/primitives/src/vstaging/mod.rs
  polkadot/runtime/parachains/src/configuration.rs
  polkadot/runtime/parachains/src/configuration/benchmarking.rs
  polkadot/runtime/parachains/src/configuration/migration.rs
  polkadot/runtime/parachains/src/configuration/migration/v10.rs
  polkadot/runtime/parachains/src/configuration/migration/v9.rs
  polkadot/runtime/parachains/src/configuration/tests.rs
  polkadot/runtime/parachains/src/runtime_api_impl/vstaging.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/runtime_parachains_configuration.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/runtime_parachains_configuration.rs
Labels: T4-runtime_API, T8-polkadot

#1248 Contracts expose pallet-xcm
  Cargo.lock
  Cargo.toml
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/contracts.rs
  polkadot/xcm/xcm-builder/src/controller.rs
  polkadot/xcm/xcm-builder/src/lib.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/contracts/Cargo.toml
  substrate/frame/contracts/fixtures/data/xcm_execute.wat
  substrate/frame/contracts/fixtures/data/xcm_send.wat
  substrate/frame/contracts/fixtures/src/lib.rs
  substrate/frame/contracts/mock-network/Cargo.toml
  substrate/frame/contracts/mock-network/src/lib.rs
  substrate/frame/contracts/mock-network/src/mocks.rs
  substrate/frame/contracts/mock-network/src/mocks/msg_queue.rs
  substrate/frame/contracts/mock-network/src/mocks/relay_message_queue.rs
  substrate/frame/contracts/mock-network/src/parachain.rs
  substrate/frame/contracts/mock-network/src/parachain/contracts_config.rs
  substrate/frame/contracts/mock-network/src/primitives.rs
  substrate/frame/contracts/mock-network/src/relay_chain.rs
  substrate/frame/contracts/mock-network/src/tests.rs
  substrate/frame/contracts/src/lib.rs
  substrate/frame/contracts/src/tests.rs
  substrate/frame/contracts/src/wasm/runtime.rs
Labels: T6-XCM, T7-smart_contracts

#2322 pallet-xcm: use XcmTeleportFilter for teleported fees in reserve transfers
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/pallet-xcm/src/tests/assets_transfer.rs
Labels: R0-silent, T6-XCM

#2317 Unify `ChainSync` actions under one enum (follow-up)
  substrate/client/network/sync/src/chain_sync.rs
  substrate/client/network/sync/src/engine.rs
  substrate/client/network/sync/src/lib.rs
  substrate/client/network/sync/src/service/mod.rs
  substrate/client/network/sync/src/service/syncing_service.rs
  substrate/client/network/sync/src/warp.rs
  substrate/client/network/test/src/lib.rs
Labels: R0-silent, T0-node

#2308 [CI] Prepare CI for Merge Queues
  .github/workflows/check-labels.yml
  .github/workflows/check-licenses.yml
  .github/workflows/check-links.yml
  .github/workflows/check-markdown.yml
  .github/workflows/check-prdoc.yml
  .github/workflows/check-publish.yml
  .github/workflows/fmt-check.yml
  .github/workflows/gitspiegel-trigger.yml
  .github/workflows/pr-custom-review.yml
  .github/workflows/review-trigger.yml
  .gitlab-ci.yml
  .gitlab/pipeline/publish.yml
  .gitlab/pipeline/zombienet/cumulus.yml
  .gitlab/pipeline/zombienet/polkadot.yml
  .gitlab/pipeline/zombienet/substrate.yml
Labels: R0-silent

#1814 Identity Deposits Relay to Parachain Migration
  Cargo.lock
  polkadot/runtime/common/Cargo.toml
  polkadot/runtime/common/src/identity_migrator.rs
  polkadot/runtime/common/src/integration_tests.rs
  polkadot/runtime/common/src/lib.rs
  polkadot/runtime/rococo/src/impls.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/mod.rs
  polkadot/runtime/rococo/src/weights/runtime_common_identity_migrator.rs
  polkadot/runtime/westend/src/impls.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/mod.rs
  polkadot/runtime/westend/src/weights/runtime_common_identity_migrator.rs
  substrate/frame/identity/src/lib.rs
  substrate/frame/identity/src/tests.rs
Labels: T14-system_parachains

#2351 frame-system: Add `last_runtime_upgrade_spec_version`
  Cargo.lock
  substrate/frame/executive/src/lib.rs
  substrate/frame/system/Cargo.toml
  substrate/frame/system/src/lib.rs
  substrate/frame/system/src/tests.rs
Labels: T1-FRAME

#2332 Added new checks to add_assignment
  polkadot/runtime/parachains/src/assigner_bulk/mod.rs
  polkadot/runtime/parachains/src/assigner_bulk/tests.rs
Labels: T8-polkadot

#2363 westend: remove SessionKeys migration already applied on-chain
  polkadot/runtime/westend/src/lib.rs
Labels: R0-silent

#2368 implementers-guide: update github link
  polkadot/roadmap/implementers-guide/book.toml
Labels: A1-insubstantial

#2354 Fix Typo: `PalletXcmExtrinsicsBenchmark`
  cumulus/parachains/runtimes/assets/asset-hub-kusama/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-polkadot/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
Labels: A1-insubstantial, T12-benchmarks

#2167 add pallet nomination-pools versioned migration to kitchensink
  polkadot/runtime/westend/src/lib.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/nomination-pools/src/migration.rs
Labels: T10-tests

#2377 fix typo
  substrate/frame/proxy/README.md
Labels: A1-insubstantial, T11-documentation

#2376 bump zombienet version `v1.3.80`
  .gitlab-ci.yml
Labels: A1-insubstantial, R0-silent, T10-tests

#2369 [NPoS] Check if staker is exposed in paged exposure storage entries
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/tests.rs
Labels: T2-pallets

#2378 Beefy: small fixes
  substrate/client/consensus/beefy/src/worker.rs
Labels: I2-bug, T15-bridges

#2250 crypto: `lazy_static` removed, light parser for address URI added
  Cargo.lock
  Cargo.toml
  substrate/frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr
  substrate/frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen_unnamed.stderr
  substrate/primitives/core/Cargo.toml
  substrate/primitives/core/fuzz/Cargo.toml
  substrate/primitives/core/fuzz/fuzz_targets/fuzz_address_uri.rs
  substrate/primitives/core/src/address_uri.rs
  substrate/primitives/core/src/crypto.rs
  substrate/primitives/core/src/lib.rs
Labels: T0-node

#2384 [trivial] asset-hubs runtimes: fix incorrect doc-comments
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
Labels: R0-silent

#2155 Do not panic if the `fdlimit` call to increase the file descriptor limit fails
  Cargo.lock
  substrate/client/cli/Cargo.toml
  substrate/client/cli/src/config.rs
  substrate/client/service/test/Cargo.toml
  substrate/client/service/test/src/lib.rs
Labels: R0-silent

#2385 Relax `force_default_xcm_version` for testnet system parachains
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/xcm_config.rs
Labels: T9-cumulus

#2381 Make collator RPC mode non-experimental
  cumulus/client/cli/src/lib.rs
Labels: T0-node, T9-cumulus

#2336 Fix migrations and add CI check for new system chains
  .gitlab/pipeline/check.yml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
Labels: R0-silent

#2389 Bump bandersnatch VRF revision
  Cargo.lock
  substrate/primitives/core/Cargo.toml
Labels: I3-annoyance

#1918 Preserve artifact cache unless stale
  Cargo.lock
  polkadot/node/core/candidate-validation/src/lib.rs
  polkadot/node/core/candidate-validation/src/tests.rs
  polkadot/node/core/pvf/Cargo.toml
  polkadot/node/core/pvf/benches/host_prepare_rococo_runtime.rs
  polkadot/node/core/pvf/common/Cargo.toml
  polkadot/node/core/pvf/common/build.rs
  polkadot/node/core/pvf/common/src/error.rs
  polkadot/node/core/pvf/common/src/lib.rs
  polkadot/node/core/pvf/common/src/prepare.rs
  polkadot/node/core/pvf/common/src/pvf.rs
  polkadot/node/core/pvf/prepare-worker/Cargo.toml
  polkadot/node/core/pvf/prepare-worker/src/lib.rs
  polkadot/node/core/pvf/src/artifacts.rs
  polkadot/node/core/pvf/src/host.rs
  polkadot/node/core/pvf/src/lib.rs
  polkadot/node/core/pvf/src/prepare/pool.rs
  polkadot/node/core/pvf/src/prepare/queue.rs
  polkadot/node/core/pvf/src/prepare/worker_intf.rs
  polkadot/node/core/pvf/src/worker_intf.rs
  polkadot/node/core/pvf/tests/it/main.rs
  substrate/utils/build-script-utils/src/version.rs
Labels: T0-node

#2397 Pools: Add `MaxUnbonding` to metadata
  substrate/frame/nomination-pools/src/lib.rs
Labels: I5-enhancement, T2-pallets

#2182 remove retry from backers on failed candidate validation
  polkadot/node/core/approval-voting/src/lib.rs
  polkadot/node/core/approval-voting/src/tests.rs
  polkadot/node/core/backing/src/lib.rs
  polkadot/node/core/backing/src/tests/mod.rs
  polkadot/node/core/backing/src/tests/prospective_parachains.rs
  polkadot/node/core/candidate-validation/src/lib.rs
  polkadot/node/core/candidate-validation/src/tests.rs
  polkadot/node/core/dispute-coordinator/src/participation/mod.rs
  polkadot/node/core/dispute-coordinator/src/participation/tests.rs
  polkadot/node/malus/src/variants/common.rs
  polkadot/node/overseer/examples/minimal-example.rs
  polkadot/node/overseer/src/tests.rs
  polkadot/node/subsystem-types/src/messages.rs
  polkadot/primitives/src/lib.rs
  polkadot/primitives/src/v6/executor_params.rs
  polkadot/primitives/src/v6/mod.rs
  polkadot/roadmap/implementers-guide/src/node/utility/pvf-host-and-workers.md
  polkadot/runtime/parachains/src/configuration/benchmarking.rs
Labels: T0-node

#2396 bump zombienet version `v1.3.82`
  .gitlab-ci.yml
  .gitlab/pipeline/zombienet.yml
  .gitlab/pipeline/zombienet/substrate.yml
  substrate/frame/transaction-payment/skip-feeless-payment/src/lib.rs
Labels: A1-insubstantial, R0-silent, T10-tests

#2174 `chain-spec-builder`: cleanup
  Cargo.lock
  substrate/bin/utils/chain-spec-builder/Cargo.toml
  substrate/bin/utils/chain-spec-builder/bin/main.rs
  substrate/bin/utils/chain-spec-builder/src/lib.rs
Labels: T0-node

#2375 Add output positional arg to undying-collator cli
  polkadot/parachain/test-parachains/undying/collator/src/cli.rs
  polkadot/parachain/test-parachains/undying/collator/src/main.rs
Labels: R0-silent, T10-tests

#2221 PVF worker: switch on seccomp networking restrictions
  polkadot/node/core/pvf/common/src/error.rs
  polkadot/node/core/pvf/common/src/execute.rs
  polkadot/node/core/pvf/common/src/lib.rs
  polkadot/node/core/pvf/common/src/worker/mod.rs
  polkadot/node/core/pvf/common/src/worker/security/seccomp.rs
  polkadot/node/core/pvf/execute-worker/src/lib.rs
  polkadot/node/core/pvf/prepare-worker/src/lib.rs
  polkadot/node/core/pvf/src/execute/worker_intf.rs
  polkadot/node/core/pvf/src/prepare/pool.rs
  polkadot/node/core/pvf/src/prepare/worker_intf.rs
  polkadot/node/core/pvf/src/security.rs
  polkadot/node/core/pvf/tests/it/process.rs
  polkadot/roadmap/implementers-guide/src/node/utility/pvf-host-and-workers.md
Labels: T0-node

#2001 cumulus-consensus-common: block import: `delayed_best_block` flag added
  cumulus/client/consensus/common/src/lib.rs
  cumulus/client/consensus/common/src/tests.rs
Labels: T0-node

#2414 added action to pass review bot on merge queue
  .github/workflows/merge-queue.yml
Labels: R0-silent

#2430 cumulus-test-service: block import fix
  cumulus/test/service/src/lib.rs
Labels: R0-silent

#2380 Deprecate `RewardDestination::Controller`
  polkadot/runtime/westend/src/weights/pallet_staking.rs
  substrate/frame/staking/src/benchmarking.rs
  substrate/frame/staking/src/lib.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/tests.rs
  substrate/frame/staking/src/weights.rs
Labels: I9-optimisation, T1-FRAME

#2434 Revert docker images tag naming to <prnum-shortsha>
  .gitlab-ci.yml
  .gitlab/pipeline/publish.yml
Labels: R0-silent

#2437 Fixes import path in benchmark macro
  substrate/bin/node-template/pallets/template/src/benchmarking.rs
  substrate/frame/asset-rate/src/benchmarking.rs
  substrate/frame/support/procedural/src/benchmark.rs
Labels: R0-silent, T12-benchmarks

#2449 Make TypeInfo for SkipCheckIfFeeless transparent, too
  substrate/frame/transaction-payment/skip-feeless-payment/src/lib.rs
Labels: A1-insubstantial, R0-silent

#1757 work with additional key values
  cumulus/primitives/parachain-inherent/src/mock.rs
Labels: R0-silent

#2411 polkadot-node-subsystems: `ChainApiBackend` added + `polkadot-debug` image version fixed
  .gitlab/pipeline/zombienet/cumulus.yml
  Cargo.lock
  cumulus/client/relay-chain-minimal-node/Cargo.toml
  cumulus/client/relay-chain-minimal-node/src/blockchain_rpc_client.rs
  cumulus/client/relay-chain-minimal-node/src/collator_overseer.rs
  polkadot/node/core/chain-api/Cargo.toml
  polkadot/node/core/chain-api/src/lib.rs
  polkadot/node/core/chain-api/src/tests.rs
  polkadot/node/overseer/src/lib.rs
  polkadot/node/subsystem-types/Cargo.toml
  polkadot/node/subsystem-types/src/lib.rs
  polkadot/node/subsystem-types/src/runtime_client.rs
Labels: T10-tests

#2456 Remove `#[macro_use]` annotation from `mod service` in all nodes.
  cumulus/parachain-template/node/src/main.rs
  cumulus/polkadot-parachain/src/main.rs
  substrate/bin/minimal/node/src/main.rs
  substrate/bin/node-template/node/src/main.rs
  substrate/bin/node/cli/src/lib.rs
Labels: R0-silent

#2463 Add `on-chain-release-build` feature for Collectives Westend
  cumulus/parachains/runtimes/collectives/collectives-westend/Cargo.toml
Labels: T14-system_parachains

#2447 CI: Disable runtime upgrade spec name check on Westend Asset Hub and fix Staking pallet migration
  .gitlab/pipeline/check.yml
  substrate/frame/staking/src/migrations.rs
Labels: R0-silent

#2446 sp-api: Move macro related re-exports to `__private`
  Cargo.lock
  cumulus/client/relay-chain-rpc-interface/Cargo.toml
  cumulus/client/relay-chain-rpc-interface/src/rpc_client.rs
  cumulus/pallets/xcmp-queue/src/tests.rs
  polkadot/node/service/src/lib.rs
  substrate/client/api/src/call_executor.rs
  substrate/client/api/src/in_mem.rs
  substrate/client/consensus/beefy/src/lib.rs
  substrate/client/consensus/beefy/src/worker.rs
  substrate/client/executor/src/wasm_runtime.rs
  substrate/client/merkle-mountain-range/rpc/src/lib.rs
  substrate/client/rpc-spec-v2/Cargo.toml
  substrate/client/rpc-spec-v2/src/archive/archive.rs
  substrate/client/rpc-spec-v2/src/chain_head/chain_head_storage.rs
  substrate/client/rpc-spec-v2/src/chain_head/test_utils.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
  substrate/client/tracing/Cargo.toml
  substrate/client/tracing/src/block/mod.rs
  substrate/frame/beefy-mmr/src/lib.rs
  substrate/frame/contracts/src/storage/meter.rs
  substrate/frame/nfts/runtime-api/Cargo.toml
  substrate/frame/nfts/runtime-api/src/lib.rs
  substrate/frame/support/test/tests/construct_runtime.rs
  substrate/primitives/api/Cargo.toml
  substrate/primitives/api/proc-macro/src/utils.rs
  substrate/primitives/api/src/lib.rs
  substrate/primitives/consensus/beefy/Cargo.toml
  substrate/primitives/consensus/beefy/src/mmr.rs
  substrate/utils/frame/benchmarking-cli/src/block/bench.rs
  substrate/utils/frame/benchmarking-cli/src/storage/write.rs
Labels: T4-runtime_API

#2472 Fix trait imports from sp-api
  Cargo.lock
  cumulus/client/relay-chain-minimal-node/src/blockchain_rpc_client.rs
  polkadot/node/subsystem-types/Cargo.toml
  polkadot/node/subsystem-types/src/runtime_client.rs
Labels: A1-insubstantial, R0-silent

#2451 Amend staking docs to account for state of controller deprecation
  substrate/frame/staking/README.md
  substrate/frame/staking/src/lib.rs
  substrate/frame/staking/src/pallet/impls.rs
Labels: R0-silent, T2-pallets, D0-easy

#2405 pallet-xcm: ensure xcm outcome is always complete, revert effects otherwise
  Cargo.lock
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases.rs
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases_over_bridge.rs
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/pallet-xcm/src/tests/assets_transfer.rs
  polkadot/xcm/pallet-xcm/src/tests/mod.rs
  polkadot/xcm/src/v3/traits.rs
  polkadot/xcm/xcm-executor/integration-tests/Cargo.toml
  polkadot/xcm/xcm-executor/integration-tests/src/lib.rs
Labels: R0-silent

#2435 pallet-staking: Converts all math operations to safe
  substrate/frame/staking/src/lib.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/slashing.rs
Labels: T2-pallets, D0-easy

#2450 Adapt test worker to profile flag
  polkadot/node/core/pvf/benches/host_prepare_rococo_runtime.rs
  polkadot/node/core/pvf/build.rs
  polkadot/node/core/pvf/src/testing.rs
  polkadot/node/core/pvf/tests/it/main.rs
  polkadot/node/core/pvf/tests/it/worker_common.rs
Labels: T0-node

#2483 Remove dmp-queue pallet from Rococo Asset Hub and Bridge Hub
  Cargo.lock
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/cumulus_pallet_dmp_queue.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/cumulus_pallet_dmp_queue.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/mod.rs
Labels: T1-FRAME

#2462 relay-chain-consensus: set a fork_choice
  cumulus/client/consensus/relay-chain/src/import_queue.rs
Labels: T0-node

#2485 Improve `UnpinHandleInner` debug
  substrate/client/api/src/client.rs
Labels: R0-silent

#2484 Derive `MaxEncodedLen` on `SlotDuration`
  substrate/primitives/consensus/slots/src/lib.rs
Labels: R0-silent

#2489 pallet-xcm: fix benchmarking
  polkadot/xcm/pallet-xcm/src/benchmarking.rs
Labels: R0-silent

#2459 [NPoS] Use EraInfo to manipulate exposure in fast-unstake tests
  substrate/frame/fast-unstake/src/mock.rs
  substrate/frame/fast-unstake/src/tests.rs
  substrate/frame/staking/src/lib.rs
Labels: T2-pallets, T10-tests

#2491 Add missing workspace members
  Cargo.toml
Labels: R0-silent

#2492 bump zombienet version `v1.3.83`
  .github/review-bot.yml
  .gitlab/pipeline/zombienet.yml
Labels: R0-silent, T10-tests

#2487 Do not pollute global base path with export genesis/wasm
  cumulus/client/cli/src/lib.rs
Labels: T9-cumulus

#2493 Zombienet: add polkadot-debug image publish as needs for cumulus tests
  .gitlab/pipeline/zombienet/cumulus.yml
Labels: R0-silent, T10-tests
