Repository paritytech/polkadot-sdk, pull requests merged in 2023-12, with the labels that each got.

#2576 Contracts: make benchmark dependencies optional in `std` feature
  substrate/frame/contracts/Cargo.toml
Labels: A1-insubstantial, R0-silent

#1577 Sassafras Consensus Pallet
  Cargo.lock
  Cargo.toml
  substrate/frame/sassafras/Cargo.toml
  substrate/frame/sassafras/README.md
  substrate/frame/sassafras/src/benchmarking.rs
  substrate/frame/sassafras/src/data/25_tickets_100_auths.bin
  substrate/frame/sassafras/src/data/benchmark-results.md
  substrate/frame/sassafras/src/data/tickets-sort.md
  substrate/frame/sassafras/src/data/tickets-sort.png
  substrate/frame/sassafras/src/lib.rs
  substrate/frame/sassafras/src/mock.rs
  substrate/frame/sassafras/src/tests.rs
  substrate/frame/sassafras/src/weights.rs
  substrate/primitives/consensus/sassafras/Cargo.toml
  substrate/primitives/consensus/sassafras/README.md
  substrate/primitives/consensus/sassafras/src/digests.rs
  substrate/primitives/consensus/sassafras/src/lib.rs
  substrate/primitives/consensus/sassafras/src/ticket.rs
  substrate/primitives/consensus/sassafras/src/vrf.rs
  substrate/primitives/core/Cargo.toml
  substrate/primitives/core/src/bandersnatch.rs
Labels: T0-node

#2583 sassafras: taplo happy
  substrate/frame/sassafras/Cargo.toml
Labels: R0-silent

#2581 Bandersnatch: ring-context generic over domain size
  substrate/primitives/consensus/sassafras/src/vrf.rs
  substrate/primitives/core/src/bandersnatch.rs
  substrate/primitives/keystore/src/testing.rs
Labels: T0-node

#2580 Removed instruction to call init.sh when buidling from source
  polkadot/README.md
Labels: R0-silent

#2142 Cleanup XCMP `QueueConfigData`
  cumulus/pallets/xcmp-queue/src/lib.rs
  cumulus/pallets/xcmp-queue/src/migration.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  prdoc/pr_2142.prdoc
Labels: T6-XCM, T1-FRAME, T8-polkadot

#2603 Align style guide for `default = [ "std" ]` vs `default = ["std"]`
  substrate/docs/STYLE_GUIDE.md
Labels: R0-silent

#2586 contracts-fixtures: Do not assume that `rustup` is installed
  substrate/frame/contracts/fixtures/build.rs
Labels: R0-silent

#2466 Cargo caching with forklift
  .gitlab-ci.yml
Labels: A1-insubstantial, R0-silent

#2591 pallet-ranked-collective: Ensure to cleanup state in `remove_member`
  prdoc/pr_2591.prdoc
  substrate/frame/ranked-collective/src/lib.rs
  substrate/frame/ranked-collective/src/tests.rs
Labels: T1-FRAME

#2476 Adds derive_impl to relay-chain and parachain runtimes
  cumulus/parachain-template/runtime/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/test/runtime/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  substrate/bin/node-template/runtime/src/lib.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/Cargo.toml
  substrate/frame/system/Cargo.toml
  substrate/frame/system/src/lib.rs
Labels: T1-FRAME

#2611 Stabilize pov-recovery zombienet
  cumulus/zombienet/tests/0002-pov_recovery.zndsl
Labels: R0-silent, T9-cumulus, T10-tests

#2614 Remove `cargo install` for Zepter and Taplo
  .gitlab/pipeline/check.yml
Labels: R0-silent

#2498 statement-distribution: Add tests for incoming acknowledgements
  Cargo.lock
  polkadot/node/network/statement-distribution/Cargo.toml
  polkadot/node/network/statement-distribution/src/lib.rs
  polkadot/node/network/statement-distribution/src/v2/tests/grid.rs
  polkadot/node/network/statement-distribution/src/v2/tests/mod.rs
Labels: R0-silent, T0-node

#2433 Add `assign_core` benchmark to bulk assigner
  polkadot/runtime/common/src/coretime/benchmarking.rs
  polkadot/runtime/common/src/coretime/mod.rs
  polkadot/runtime/parachains/Cargo.toml
  polkadot/runtime/parachains/src/assigner_bulk/mod.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/mod.rs
  polkadot/runtime/rococo/src/weights/runtime_common_coretime.rs
Labels: T8-polkadot

#2486 PVF: Add Secure Validator Mode
  .gitlab/pipeline/zombienet.yml
  Cargo.lock
  cumulus/client/relay-chain-inprocess-interface/src/lib.rs
  polkadot/cli/Cargo.toml
  polkadot/cli/src/cli.rs
  polkadot/cli/src/command.rs
  polkadot/node/core/candidate-validation/src/lib.rs
  polkadot/node/core/pvf/Cargo.toml
  polkadot/node/core/pvf/benches/host_prepare_rococo_runtime.rs
  polkadot/node/core/pvf/common/src/lib.rs
  polkadot/node/core/pvf/common/src/worker/mod.rs
  polkadot/node/core/pvf/common/src/worker/security/change_root.rs
  polkadot/node/core/pvf/common/src/worker/security/landlock.rs
  polkadot/node/core/pvf/common/src/worker/security/mod.rs
  polkadot/node/core/pvf/common/src/worker/security/seccomp.rs
  polkadot/node/core/pvf/execute-worker/src/lib.rs
  polkadot/node/core/pvf/prepare-worker/src/lib.rs
  polkadot/node/core/pvf/src/artifacts.rs
  polkadot/node/core/pvf/src/execute/worker_interface.rs
  polkadot/node/core/pvf/src/host.rs
  polkadot/node/core/pvf/src/security.rs
  polkadot/node/core/pvf/src/worker_interface.rs
  polkadot/node/core/pvf/tests/it/main.rs
  polkadot/node/core/pvf/tests/it/worker_common.rs
  polkadot/node/service/src/lib.rs
  polkadot/node/test/service/src/lib.rs
  polkadot/parachain/test-parachains/adder/collator/src/main.rs
  polkadot/parachain/test-parachains/undying/collator/src/main.rs
  polkadot/zombienet_tests/misc/0002-update-cmd.sh
  polkadot/zombienet_tests/misc/0002-upgrade-node.zndsl
  prdoc/pr_2486.prdoc
Labels: T0-node

#1574 Github Workflow migrations
  .github/scripts/common/lib.sh
  .github/workflows/check-licenses.yml
  .github/workflows/notif-burnin-label.yml
  .github/workflows/release-10_rc-automation.yml
  .github/workflows/release-99_notif-published.yml
Labels: R0-silent

#2585 Restore Sassafras
  Cargo.lock
  Cargo.toml
  benchmark.sh
  substrate/bin/node-sassafras/node/Cargo.toml
  substrate/bin/node-sassafras/node/src/chain_spec.rs
  substrate/bin/node-sassafras/runtime/Cargo.toml
  substrate/client/consensus/sassafras/Cargo.toml
  substrate/client/consensus/sassafras/README.md
  substrate/client/consensus/sassafras/src/authorship.rs
  substrate/client/consensus/sassafras/src/tests.rs
  substrate/client/consensus/sassafras/src/verification.rs
  substrate/frame/sassafras/Cargo.toml
  substrate/frame/sassafras/README.md
  substrate/frame/sassafras/src/data/benchmark-results.md
  substrate/frame/sassafras/src/lib.rs
  substrate/frame/sassafras/src/session.rs
  substrate/frame/sassafras/tickets.bin
  substrate/primitives/consensus/sassafras/README.md
  substrate/test-utils/runtime/client/Cargo.toml
  substrate/test-utils/runtime/client/src/lib.rs
  substrate/test-utils/runtime/src/lib.rs
Labels: T0-node

#2534 sp-core: Rename VrfOutput to VrfPreOutput
  polkadot/node/core/approval-voting/src/approval_db/v2/migration_helpers.rs
  polkadot/node/core/approval-voting/src/criteria.rs
  polkadot/node/core/approval-voting/src/tests.rs
  polkadot/node/network/approval-distribution/src/tests.rs
  polkadot/node/primitives/src/approval.rs
  substrate/client/consensus/babe/src/authorship.rs
  substrate/client/consensus/babe/src/tests.rs
  substrate/client/consensus/babe/src/verification.rs
  substrate/client/keystore/src/local.rs
  substrate/frame/babe/src/lib.rs
  substrate/frame/sassafras/src/lib.rs
  substrate/frame/sassafras/src/mock.rs
  substrate/primitives/consensus/babe/src/lib.rs
  substrate/primitives/consensus/sassafras/src/vrf.rs
  substrate/primitives/core/src/bandersnatch.rs
  substrate/primitives/core/src/crypto.rs
  substrate/primitives/core/src/sr25519.rs
  substrate/primitives/keystore/src/lib.rs
  substrate/primitives/keystore/src/testing.rs
Labels: R0-silent, T0-node, T1-FRAME, T8-polkadot

#2388 pallet-xcm: add new flexible `transfer_assets()` call/extrinsic
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/chains/parachains/testing/penpal/src/lib.rs
  cumulus/parachains/integration-tests/emulated/common/src/macros.rs
  cumulus/parachains/integration-tests/emulated/common/src/xcm_helpers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/swap.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/swap.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/teleport.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/pallet_xcm.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/pallet_xcm.rs
  polkadot/xcm/pallet-xcm/src/benchmarking.rs
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/pallet-xcm/src/tests/assets_transfer.rs
  polkadot/xcm/pallet-xcm/src/tests/mod.rs
  prdoc/pr_2388.prdoc
  substrate/frame/assets/src/benchmarking.rs
  substrate/frame/assets/src/lib.rs
Labels: T6-XCM, T2-pallets

#2422 Added AllSiblingSystemParachains matcher to be used at a parachain level
  Cargo.lock
  cumulus/parachains/common/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
  polkadot/runtime/rococo/constants/Cargo.toml
  polkadot/runtime/rococo/constants/src/lib.rs
  polkadot/runtime/westend/constants/Cargo.toml
  polkadot/runtime/westend/constants/src/lib.rs
Labels: R0-silent, T1-FRAME

#2564 Relax approval requirements on CI files
  .github/review-bot.yml
Labels: R0-silent

#2392 Support querying peer reputation
  substrate/client/consensus/grandpa/src/communication/tests.rs
  substrate/client/network-gossip/src/bridge.rs
  substrate/client/network-gossip/src/state_machine.rs
  substrate/client/network/src/service.rs
  substrate/client/network/src/service/traits.rs
  substrate/client/network/sync/src/service/mock.rs
  substrate/client/offchain/src/api.rs
  substrate/client/offchain/src/lib.rs
Labels: R0-silent, T0-node

#2647 [ci] Return CI_IMAGE variable
  .github/workflows/fmt-check.yml
  .gitlab-ci.yml
Labels: R0-silent

#2640 Improve inline comment for ClaimPermission extrinsic of nom pools
  substrate/frame/nomination-pools/src/lib.rs
Labels: R0-silent

#2644 Fix recursive trait bounds
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
Labels: R0-silent

#1454 feat(xcm): support json schema (for CosmWasm VM support)
  Cargo.lock
  polkadot/xcm/Cargo.toml
  polkadot/xcm/src/double_encoded.rs
  polkadot/xcm/src/v2/mod.rs
  polkadot/xcm/src/v3/junction.rs
  polkadot/xcm/src/v3/junctions.rs
  polkadot/xcm/src/v3/mod.rs
  polkadot/xcm/src/v3/multiasset.rs
  polkadot/xcm/src/v3/multilocation.rs
  polkadot/xcm/src/v3/traits.rs
  prdoc/pr_1454.prdoc
  substrate/primitives/weights/Cargo.toml
  substrate/primitives/weights/src/weight_v2.rs
Labels: T6-XCM

#2356 [FRAME] Make MQ pallet re-entrancy safe
  Cargo.lock
  cumulus/pallets/xcmp-queue/src/tests.rs
  polkadot/runtime/parachains/src/ump_tests.rs
  substrate/frame/message-queue/Cargo.toml
  substrate/frame/message-queue/src/benchmarking.rs
  substrate/frame/message-queue/src/integration_test.rs
  substrate/frame/message-queue/src/lib.rs
  substrate/frame/message-queue/src/mock.rs
  substrate/frame/message-queue/src/mock_helpers.rs
  substrate/frame/message-queue/src/tests.rs
  substrate/frame/support/src/traits/messages.rs
Labels: T1-FRAME

#2620 Remove `testnets-common`
  Cargo.lock
  Cargo.toml
  cumulus/parachains/common/src/westend.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/Cargo.toml
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/testnets-common/Cargo.toml
  cumulus/parachains/testnets-common/src/lib.rs
  cumulus/parachains/testnets-common/src/rococo.rs
  cumulus/parachains/testnets-common/src/westend.rs
  cumulus/parachains/testnets-common/src/wococo.rs
Labels: R0-silent, T14-system_parachains

#2632 Remove hashbrown from trie cache.
  Cargo.lock
  substrate/primitives/trie/Cargo.toml
  substrate/primitives/trie/src/cache/shared_cache.rs
Labels: R0-silent

#2652 Bump ark-scale version to 0.0.12
  Cargo.lock
  substrate/primitives/core/Cargo.toml
  substrate/primitives/crypto/ec-utils/Cargo.toml
Labels: A1-insubstantial, R0-silent

#2626 [NTFs] Emit CollectionMaxSupplySet on collection create
  substrate/frame/nfts/src/features/create_delete_collection.rs
  substrate/frame/nfts/src/tests.rs
Labels: R0-silent, T2-pallets

#2660 Update proc-macro-crate
  Cargo.lock
  cumulus/pallets/parachain-system/proc-macro/Cargo.toml
  polkadot/node/gum/proc-macro/Cargo.toml
  substrate/client/chain-spec/derive/Cargo.toml
  substrate/client/tracing/proc-macro/Cargo.toml
  substrate/frame/contracts/fixtures/Cargo.toml
  substrate/frame/election-provider-support/solution-type/Cargo.toml
  substrate/frame/staking/reward-curve/Cargo.toml
  substrate/frame/support/procedural/tools/Cargo.toml
  substrate/primitives/api/proc-macro/Cargo.toml
  substrate/primitives/runtime-interface/proc-macro/Cargo.toml
Labels: R0-silent

#2672 [ci] fix test-frame-ui job
  substrate/frame/support/test/tests/construct_runtime_ui/number_of_pallets_exceeds_tuple_size.stderr
  substrate/frame/support/test/tests/pallet_ui/task_condition_invalid_arg.stderr
  substrate/frame/support/test/tests/pallet_ui/task_invalid_condition.stderr
  substrate/frame/support/test/tests/pallet_ui/task_invalid_list.stderr
  substrate/frame/support/test/tests/pallet_ui/task_invalid_weight.stderr
Labels: R0-silent, T10-tests

#2679 pallet-xcm: fix test benchmarks
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/pallet-xcm/src/tests/assets_transfer.rs
Labels: R0-silent

#2444 Add feature flag to enable v2 assignments
  polkadot/node/core/approval-voting/src/criteria.rs
  polkadot/node/core/approval-voting/src/import.rs
  polkadot/node/core/approval-voting/src/tests.rs
  polkadot/node/core/dispute-coordinator/src/tests.rs
  polkadot/node/network/availability-distribution/src/pov_requester/mod.rs
  polkadot/node/network/availability-distribution/src/requester/tests.rs
  polkadot/node/network/availability-distribution/src/tests/state.rs
  polkadot/node/network/collator-protocol/src/collator_side/tests/mod.rs
  polkadot/node/network/dispute-distribution/src/tests/mod.rs
  polkadot/node/network/statement-distribution/src/legacy_v1/tests.rs
  polkadot/node/subsystem-util/src/runtime/mod.rs
  polkadot/primitives/src/vstaging/mod.rs
Labels: R0-silent, T8-polkadot

#2616 fix comment of exit_runtime
  substrate/primitives/state-machine/src/overlayed_changes/changeset.rs
  substrate/primitives/state-machine/src/overlayed_changes/mod.rs
Labels: R0-silent

#2589 Staking: Add `deprecate_controller_batch` AdminOrigin call
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/pallet_staking.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/babe/src/mock.rs
  substrate/frame/beefy/src/mock.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
  substrate/frame/fast-unstake/src/mock.rs
  substrate/frame/grandpa/src/mock.rs
  substrate/frame/nomination-pools/benchmarking/src/mock.rs
  substrate/frame/nomination-pools/test-staking/src/mock.rs
  substrate/frame/offences/benchmarking/src/mock.rs
  substrate/frame/root-offences/src/mock.rs
  substrate/frame/session/benchmarking/src/mock.rs
  substrate/frame/staking/src/benchmarking.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/tests.rs
  substrate/frame/staking/src/weights.rs
Labels: I9-optimisation, T2-pallets, T13-deprecation

#2655 Upgrade srtool GHA to v0.9.1
  .github/workflows/build-and-attach-release-runtimes.yml
Labels: R0-silent

#2687 pallet-uniques: Move migration over to `VersionedMigration`
  prdoc/pr_2687.prdoc
  substrate/frame/uniques/src/migration.rs
Labels: T1-FRAME

#2248 Add a deprecation section to the Contributing notes
  docs/contributor/CONTRIBUTING.md
  docs/contributor/DEPRECATION_CHECKLIST.md
Labels: R0-silent, T11-documentation

#2481 Ensure xcm versions over bridge (on sending chains)
  Cargo.lock
  bridges/bin/runtime-common/src/messages_xcm_extension.rs
  bridges/modules/xcm-bridge-hub-router/src/benchmarking.rs
  bridges/modules/xcm-bridge-hub-router/src/lib.rs
  bridges/modules/xcm-bridge-hub-router/src/mock.rs
  bridges/modules/xcm-bridge-hub/src/exporter.rs
  bridges/modules/xcm-bridge-hub/src/lib.rs
  bridges/modules/xcm-bridge-hub/src/mock.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/common/src/impls.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/send_xcm.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/send_xcm.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_xcm_bridge_hub_router.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_xcm_bridge_hub_router.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_westend_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/bridge_to_rococo_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases.rs
  cumulus/parachains/runtimes/test-utils/src/lib.rs
  cumulus/scripts/bridges_common.sh
  cumulus/scripts/bridges_rococo_westend.sh
  cumulus/scripts/generate_hex_encoded_call/index.js
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/pallet-xcm/src/tests/mod.rs
  polkadot/xcm/src/lib.rs
  polkadot/xcm/xcm-builder/src/tests/bridging/local_para_para.rs
  polkadot/xcm/xcm-builder/src/tests/bridging/local_relay_relay.rs
  polkadot/xcm/xcm-builder/src/tests/bridging/mod.rs
  polkadot/xcm/xcm-builder/src/tests/bridging/paid_remote_relay_relay.rs
  polkadot/xcm/xcm-builder/src/tests/bridging/remote_para_para.rs
  polkadot/xcm/xcm-builder/src/tests/bridging/remote_para_para_via_relay.rs
  polkadot/xcm/xcm-builder/src/tests/bridging/remote_relay_relay.rs
  polkadot/xcm/xcm-builder/src/universal_exports.rs
  prdoc/pr_2481.prdoc
Labels: T9-cumulus, T15-bridges

#2428 Fix ParentOrSiblings
  cumulus/parachains/common/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
Labels: R0-silent, T6-XCM

#2697 Update prdoc
  prdoc/1.5.0/pr_2625_special.prdoc
Labels: R0-silent

#2597 Make crate visible methods of `OverlayedChanges` public
  prdoc/pr_2597.prdoc
  substrate/primitives/state-machine/src/overlayed_changes/mod.rs
Labels: T0-node

#2670 [ci] Add `-D warnings` for `cargo-check-each-crate` job to fail on warnings
  .gitlab/pipeline/test.yml
  substrate/client/network/src/behaviour.rs
  substrate/client/network/src/protocol/message.rs
  substrate/client/network/src/protocol/notifications/upgrade.rs
  substrate/client/offchain/src/api.rs
  substrate/client/transaction-pool/src/graph/mod.rs
  substrate/frame/contracts/proc-macro/src/lib.rs
  substrate/primitives/api/proc-macro/src/utils.rs
  substrate/primitives/state-machine/src/lib.rs
Labels: R0-silent

#2331 Rename `ExportGenesisStateCommand` to `ExportGenesisHeadCommand` and make it respect custom genesis block builders
  Cargo.lock
  cumulus/client/cli/Cargo.toml
  cumulus/client/cli/src/lib.rs
  cumulus/parachain-template/node/src/cli.rs
  cumulus/parachain-template/node/src/command.rs
  cumulus/polkadot-parachain/src/cli.rs
  cumulus/polkadot-parachain/src/command.rs
  cumulus/test/service/src/cli.rs
  cumulus/test/service/src/genesis.rs
  cumulus/test/service/src/lib.rs
  cumulus/test/service/src/main.rs
  polkadot/parachain/test-parachains/adder/collator/src/cli.rs
  polkadot/parachain/test-parachains/undying/collator/src/cli.rs
  prdoc/pr_2331.prdoc
Labels: T9-cumulus

#2252 Add `check runtimes` GH Workflow
  .github/runtime_specs/rococo.json
  .github/runtime_specs/westend.json
  .github/scripts/check-runtime.py
  .github/scripts/common/lib.sh
  .github/workflows/build-and-attach-release-runtimes.yml
  .github/workflows/check-publish.yml
  .github/workflows/check-runtimes.yml
Labels: R0-silent

#2692 Tests for BridgeHub(s) <> remote GRANDPA chain
  Cargo.lock
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/from_grandpa_chain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/from_parachain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/helpers.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_data/from_grandpa_chain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_data/from_parachain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_data/mod.rs
  cumulus/parachains/runtimes/test-utils/src/lib.rs
Labels: R0-silent, T15-bridges

#2677 Fixes parsing for config attrs in pallet macros
  substrate/frame/support/procedural/src/derive_impl.rs
  substrate/frame/support/procedural/src/pallet/expand/call.rs
  substrate/frame/support/procedural/src/pallet/expand/error.rs
  substrate/frame/support/procedural/src/pallet/parse/call.rs
  substrate/frame/support/procedural/src/pallet/parse/error.rs
  substrate/frame/support/test/tests/derive_impl.rs
  substrate/frame/support/test/tests/pallet.rs
Labels: R0-silent, T1-FRAME

#2639 Updated benchmarks related to the Rococo/Westend bridge
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_xcm_bridge_hub_router.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_xcm_bridge_hub_router.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_grandpa.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_messages.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_parachains.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_relayers.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_bridge_grandpa.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_bridge_messages.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_bridge_parachains.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_bridge_relayers.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
Labels: R0-silent, T15-bridges

#2690 [Staking] Adds a round check at signed solution submission
  substrate/frame/election-provider-multi-phase/src/lib.rs
  substrate/frame/election-provider-multi-phase/src/mock.rs
  substrate/frame/election-provider-multi-phase/src/signed.rs
Labels: R0-silent, T1-FRAME, D0-easy

#2702 fix docker tag for polkadot image
  .github/workflows/release-50_publish-docker.yml
Labels: R0-silent

#2663 PVF: fix unshare "could not create temporary directory"; refactor
  polkadot/node/core/pvf/src/artifacts.rs
  polkadot/node/core/pvf/src/host.rs
  polkadot/node/core/pvf/tests/it/main.rs
  prdoc/pr_2663-fix-could-not-create-temporary-drectory.prdoc
Labels: T0-node, I2-bug

#2695 Add dummy impls of `fungible` and `fungibles` trait families
  substrate/frame/support/src/traits/tokens/fungible/regular.rs
  substrate/frame/support/src/traits/tokens/fungibles/regular.rs
Labels: R0-silent, T1-FRAME

#2528 Introduce subsystem benchmarking tool
  Cargo.lock
  Cargo.toml
  polkadot/node/network/availability-recovery/Cargo.toml
  polkadot/node/network/availability-recovery/src/lib.rs
  polkadot/node/network/availability-recovery/src/metrics.rs
  polkadot/node/network/availability-recovery/src/task.rs
  polkadot/node/network/availability-recovery/src/tests.rs
  polkadot/node/overseer/src/lib.rs
  polkadot/node/subsystem-bench/Cargo.toml
  polkadot/node/subsystem-bench/README.md
  polkadot/node/subsystem-bench/examples/availability_read.yaml
  polkadot/node/subsystem-bench/grafana/availability-read.json
  polkadot/node/subsystem-bench/grafana/task-cpu-usage.json
  polkadot/node/subsystem-bench/src/availability/cli.rs
  polkadot/node/subsystem-bench/src/availability/mod.rs
  polkadot/node/subsystem-bench/src/cli.rs
  polkadot/node/subsystem-bench/src/core/configuration.rs
  polkadot/node/subsystem-bench/src/core/display.rs
  polkadot/node/subsystem-bench/src/core/environment.rs
  polkadot/node/subsystem-bench/src/core/keyring.rs
  polkadot/node/subsystem-bench/src/core/mock/av_store.rs
  polkadot/node/subsystem-bench/src/core/mock/dummy.rs
  polkadot/node/subsystem-bench/src/core/mock/mod.rs
  polkadot/node/subsystem-bench/src/core/mock/network_bridge.rs
  polkadot/node/subsystem-bench/src/core/mock/runtime_api.rs
  polkadot/node/subsystem-bench/src/core/mod.rs
  polkadot/node/subsystem-bench/src/core/network.rs
  polkadot/node/subsystem-bench/src/subsystem-bench.rs
  polkadot/node/subsystem-test-helpers/Cargo.toml
  polkadot/node/subsystem-test-helpers/src/lib.rs
  polkadot/node/subsystem-test-helpers/src/mock.rs
Labels: R0-silent, T0-node, T10-tests, T12-benchmarks

#2709 [Backport] txn version bump from 1.5.0
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
Labels: R0-silent, A3-backport

#2684 Add FungibleAdapter
  cumulus/pallets/xcmp-queue/src/mock.rs
  cumulus/parachain-template/runtime/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot/runtime/rococo/src/xcm_config.rs
  polkadot/runtime/westend/src/xcm_config.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/fungible/mock.rs
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/xcm-builder/src/currency_adapter.rs
  polkadot/xcm/xcm-builder/src/fungible_adapter.rs
  polkadot/xcm/xcm-builder/src/lib.rs
  polkadot/xcm/xcm-builder/tests/mock/mod.rs
  polkadot/xcm/xcm-simulator/example/src/parachain.rs
  polkadot/xcm/xcm-simulator/example/src/relay_chain.rs
  polkadot/xcm/xcm-simulator/fuzzer/src/parachain.rs
  polkadot/xcm/xcm-simulator/fuzzer/src/relay_chain.rs
  prdoc/pr_2684.prdoc
  substrate/frame/contracts/mock-network/src/parachain.rs
  substrate/frame/contracts/mock-network/src/relay_chain.rs
Labels: T6-XCM

#2540 Add Rococo People <> Rococo Bulletin bridge support to Rococo Bridge Hub
  Cargo.lock
  bridges/modules/messages/src/weights_ext.rs
  bridges/primitives/chain-bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_common_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_bulletin_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_westend_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_messages_rococo_to_rococo_bulletin.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_messages_rococo_to_westend.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  polkadot/runtime/rococo/constants/src/lib.rs
Labels: R0-silent, T15-bridges

#2718 sc-tracing: swap atty with is-terminal
  Cargo.lock
  substrate/client/tracing/Cargo.toml
  substrate/client/tracing/src/logging/mod.rs
Labels: R0-silent

#2711 pallet-nomination-pools: Enable function for `fuzzing` feature as well
  substrate/frame/nomination-pools/src/lib.rs
Labels: R0-silent

#2334 feat: add super trait for block number
  polkadot/runtime/parachains/src/scheduler.rs
  substrate/client/consensus/beefy/src/worker.rs
  substrate/client/rpc-spec-v2/src/archive/archive.rs
  substrate/primitives/runtime/src/generic/header.rs
  substrate/primitives/runtime/src/traits.rs
Labels: R0-silent

#2707 Feature gate `do_task` in `frame_system`
  substrate/bin/node/runtime/Cargo.toml
  substrate/frame/examples/tasks/Cargo.toml
  substrate/frame/examples/tasks/src/tests.rs
  substrate/frame/support/test/Cargo.toml
  substrate/frame/support/test/tests/pallet_outer_enums_explicit.rs
  substrate/frame/support/test/tests/pallet_outer_enums_implicit.rs
  substrate/frame/system/Cargo.toml
  substrate/frame/system/src/lib.rs
Labels: R0-silent, T1-FRAME

#2712 Governance can halt and resume Rococo <> Wococo bridge pallets over XCM
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/mod.rs
Labels: R0-silent, T15-bridges

#2716 BEEFY: `expect_validator_set()` fix
  substrate/client/consensus/beefy/src/lib.rs
Labels: T0-node

#2720 parachain-system: Do not take `self` for `last_relay_block_number`
  cumulus/pallets/parachain-system/src/lib.rs
Labels: R0-silent

#2719 fix zombienet test
  .gitlab/pipeline/zombienet/polkadot.yml
  polkadot/zombienet_tests/misc/0002-upgrade-node.toml
Labels: R0-silent, T10-tests

#2694 [NPoS] Remove better solution threshold for unsigned submissions
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_2694.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/election-provider-multi-phase/src/lib.rs
  substrate/frame/election-provider-multi-phase/src/mock.rs
  substrate/frame/election-provider-multi-phase/src/unsigned.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
Labels: T1-FRAME, D0-easy

#2693 `chain-spec-builder`: Improve output path example
  substrate/bin/utils/chain-spec-builder/src/lib.rs
Labels: R0-silent

#2727 Publicly expose inaccessible `pallet_uniques` state
  substrate/frame/uniques/src/lib.rs
Labels: R0-silent

#2661 Relaxed clippy fixes/nits
  cumulus/parachain-template/node/src/rpc.rs
  cumulus/parachain-template/runtime/src/weights/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/mod.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/mod.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/contracts.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/weights/mod.rs
  cumulus/parachains/runtimes/testing/penpal/src/weights/mod.rs
  cumulus/polkadot-parachain/src/rpc.rs
  cumulus/polkadot-parachain/src/service.rs
  cumulus/primitives/parachain-inherent/src/lib.rs
  polkadot/node/malus/src/interceptor.rs
  polkadot/node/network/bridge/src/rx/mod.rs
  polkadot/node/network/bridge/src/tx/mod.rs
  polkadot/node/service/src/parachains_db/mod.rs
  polkadot/node/tracking-allocator/src/lib.rs
  polkadot/runtime/common/src/claims.rs
  polkadot/runtime/parachains/src/assigner_on_demand/mod.rs
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/procedural/src/builder_pattern.rs
  polkadot/xcm/xcm-builder/src/currency_adapter.rs
  polkadot/xcm/xcm-builder/src/tests/mock.rs
  substrate/client/chain-spec/src/genesis_config_builder.rs
  substrate/frame/alliance/src/mock.rs
  substrate/frame/assets/src/benchmarking.rs
  substrate/frame/beefy/src/mock.rs
  substrate/frame/broker/src/lib.rs
  substrate/frame/contracts/src/migration/v10.rs
  substrate/frame/contracts/src/wasm/mod.rs
  substrate/frame/election-provider-multi-phase/src/mock.rs
  substrate/frame/elections-phragmen/src/benchmarking.rs
  substrate/frame/fast-unstake/src/lib.rs
  substrate/frame/indices/src/lib.rs
  substrate/frame/lottery/src/lib.rs
  substrate/frame/paged-list/src/paged_list.rs
  substrate/frame/staking/src/benchmarking.rs
  substrate/frame/support/src/dispatch.rs
  substrate/primitives/database/src/lib.rs
  substrate/primitives/runtime-interface/proc-macro/src/utils.rs
  substrate/primitives/storage/src/lib.rs
  substrate/utils/build-script-utils/src/git.rs
  substrate/utils/build-script-utils/src/version.rs
Labels: R0-silent

#2736 Bridges subtree update
  bridges/primitives/runtime/src/chain.rs
Labels: R0-silent, T15-bridges

#2737 BEEFY: expect_validator_set() small fix
  substrate/client/consensus/beefy/src/lib.rs
Labels: R0-silent, T15-bridges

#2732 [ci] Fix node-bench-regression-guard job
  .gitlab/pipeline/test.yml
Labels: R0-silent

#2734 subsystem benchmarks: add cpu profiling
  Cargo.lock
  polkadot/node/subsystem-bench/Cargo.toml
  polkadot/node/subsystem-bench/README.md
  polkadot/node/subsystem-bench/docker/docker-compose.yml
  polkadot/node/subsystem-bench/docker/prometheus/prometheus.yml
  polkadot/node/subsystem-bench/grafana/cpu-profiling.json
  polkadot/node/subsystem-bench/src/subsystem-bench.rs
Labels: R0-silent, T0-node, T10-tests, T12-benchmarks

#2033 `UnionOf` types for merged `fungible` and `fungibles` implementations
  cumulus/parachains/runtimes/assets/common/src/local_and_foreign_assets.rs
  prdoc/pr_2033.prdoc
  substrate/frame/asset-conversion/src/lib.rs
  substrate/frame/assets/src/lib.rs
  substrate/frame/assets/src/tests.rs
  substrate/frame/assets/src/tests/sets.rs
  substrate/frame/balances/src/impl_fungible.rs
  substrate/frame/support/src/traits/misc.rs
  substrate/frame/support/src/traits/tokens/fungible/imbalance.rs
  substrate/frame/support/src/traits/tokens/fungible/item_of.rs
  substrate/frame/support/src/traits/tokens/fungible/mod.rs
  substrate/frame/support/src/traits/tokens/fungible/union_of.rs
  substrate/frame/support/src/traits/tokens/fungibles/imbalance.rs
  substrate/frame/support/src/traits/tokens/fungibles/mod.rs
  substrate/frame/support/src/traits/tokens/fungibles/union_of.rs
Labels: T1-FRAME

#2653 [NFTs] Fix consumers issue
  substrate/frame/nfts/src/features/transfer.rs
  substrate/frame/nfts/src/lib.rs
  substrate/frame/nfts/src/tests.rs
  substrate/frame/uniques/src/lib.rs
  substrate/frame/uniques/src/tests.rs
Labels: R0-silent, T2-pallets

#2609 Ref docs: runtime vs contracts
  docs/sdk/src/reference_docs/runtime_vs_smart_contract.rs
Labels: R0-silent, T11-documentation

#2741 SDK docs ref cli
  docs/sdk/src/reference_docs/cli.rs
Labels: R0-silent, T11-documentation

#2754 pallet-uniques/nfts: Small optimizations
  substrate/frame/nfts/src/features/transfer.rs
  substrate/frame/uniques/src/lib.rs
Labels: R0-silent

#2755 Add srtool GHA
  .github/scripts/common/lib.sh
  .github/workflows/srtool.yml
Labels: R0-silent

#2524 Update schnorrkel to 0.11.4
  Cargo.lock
  polkadot/node/core/approval-voting/Cargo.toml
  polkadot/node/core/approval-voting/src/approval_db/common/migration_helpers.rs
  polkadot/node/core/approval-voting/src/criteria.rs
  polkadot/node/core/approval-voting/src/tests.rs
  polkadot/node/network/approval-distribution/Cargo.toml
  polkadot/node/network/approval-distribution/src/tests.rs
  polkadot/node/primitives/Cargo.toml
  substrate/client/authority-discovery/Cargo.toml
  substrate/client/network-gossip/Cargo.toml
  substrate/client/network/Cargo.toml
  substrate/client/network/statement/Cargo.toml
  substrate/client/network/sync/Cargo.toml
  substrate/client/network/test/Cargo.toml
  substrate/client/network/transactions/Cargo.toml
  substrate/client/offchain/Cargo.toml
  substrate/client/telemetry/Cargo.toml
  substrate/primitives/core/Cargo.toml
  substrate/primitives/core/src/sr25519.rs
  substrate/primitives/io/Cargo.toml
  substrate/primitives/statement-store/Cargo.toml
Labels: R0-silent, T0-node

#2752 Fix bridges scripts to test Rococo <> Westend bridge locally
  bridges/primitives/chain-bridge-hub-rococo/src/lib.rs
  bridges/primitives/chain-bridge-hub-westend/src/lib.rs
  cumulus/scripts/bridges_rococo_westend.sh
Labels: R0-silent, T15-bridges

#2031 pallet-asset-conversion: Decoupling Native Currency Dependancy
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/swap.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/swap.rs
  cumulus/parachains/runtimes/assets/asset-hub-kusama/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-kusama/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_asset_conversion.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_asset_conversion.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/common/src/benchmarks.rs
  cumulus/parachains/runtimes/assets/common/src/lib.rs
  cumulus/parachains/runtimes/assets/common/src/local_and_foreign_assets.rs
  prdoc/pr_2031.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/asset-conversion/src/benchmarking.rs
  substrate/frame/asset-conversion/src/lib.rs
  substrate/frame/asset-conversion/src/mock.rs
  substrate/frame/asset-conversion/src/swap.rs
  substrate/frame/asset-conversion/src/tests.rs
  substrate/frame/asset-conversion/src/types.rs
  substrate/frame/asset-conversion/src/weights.rs
  substrate/frame/transaction-payment/asset-conversion-tx-payment/src/lib.rs
  substrate/frame/transaction-payment/asset-conversion-tx-payment/src/mock.rs
  substrate/frame/transaction-payment/asset-conversion-tx-payment/src/payment.rs
  substrate/frame/transaction-payment/asset-conversion-tx-payment/src/tests.rs
Labels: T1-FRAME

#2760 use a single source for simple-mermaid dependency
  Cargo.lock
  docs/sdk/Cargo.toml
  substrate/primitives/runtime/Cargo.toml
Labels: A1-insubstantial, R0-silent

#2682 Add Authorize Upgrade Pattern to Frame System
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/parachain-system/src/tests.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/frame_system.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/frame_system.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/frame_system.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/frame_system.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/frame_system.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/weights/frame_system.rs
  polkadot/runtime/rococo/src/weights/frame_system.rs
  polkadot/runtime/westend/src/weights/frame_system.rs
  prdoc/pr_2682.prdoc
  substrate/frame/support/test/tests/pallet_outer_enums_explicit.rs
  substrate/frame/support/test/tests/pallet_outer_enums_implicit.rs
  substrate/frame/system/benchmarking/src/lib.rs
  substrate/frame/system/src/lib.rs
  substrate/frame/system/src/tests.rs
  substrate/frame/system/src/weights.rs
Labels: T2-pallets, T9-cumulus

#2569 Fix clippy lints behind feature gates and introduce new CI step targeting all features
  .gitlab/pipeline/check.yml
  Cargo.toml
  bridges/modules/relayers/src/benchmarking.rs
  cumulus/pallets/xcmp-queue/src/benchmarking.rs
  cumulus/parachains/pallets/collective-content/src/benchmarking.rs
  polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  polkadot/xcm/xcm-simulator/example/src/parachain.rs
  substrate/frame/alliance/src/benchmarking.rs
  substrate/frame/bounties/src/benchmarking.rs
  substrate/frame/contracts/src/benchmarking/mod.rs
  substrate/frame/contracts/src/migration/v12.rs
  substrate/frame/democracy/src/benchmarking.rs
  substrate/frame/democracy/src/migrations/v1.rs
  substrate/frame/fast-unstake/src/benchmarking.rs
  substrate/frame/recovery/src/benchmarking.rs
  substrate/frame/sassafras/src/benchmarking.rs
  substrate/frame/scheduler/src/migration.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/state-trie-migration/src/lib.rs
  substrate/frame/uniques/src/benchmarking.rs
  substrate/primitives/core/src/paired_crypto.rs
Labels: R0-silent, I4-refactor

#2765 Fix Coretime Master
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/frame_system.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/frame_system.rs
Labels: A1-insubstantial, R0-silent

#2763 Cleanup bridges tests: with-grandpa-chain case
  bridges/primitives/runtime/src/chain.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/from_grandpa_chain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/from_parachain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/helpers.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/mod.rs
  cumulus/parachains/runtimes/test-utils/src/lib.rs
Labels: R0-silent, T10-tests, T15-bridges

#2772 Cleanup bridges tests: with-parachain case
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/from_grandpa_chain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/from_parachain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_data/from_parachain.rs
Labels: R0-silent, T10-tests, T15-bridges

#2775 Bump AH and BH runtime versions
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
Labels: R0-silent

#2777 Try to set `beacon-spec-mainnet` as default on runtime and not binary
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/polkadot-parachain/Cargo.toml
Labels: R0-silent, T15-bridges

#2779 frame-support: Print key as hex for corrupted state
  substrate/frame/support/src/storage/unhashed.rs
Labels: R0-silent

#2783 pallet-sudo: Accept `Root` origin as valid sudo
  prdoc/pr_2783.prdoc
  substrate/frame/sudo/src/lib.rs
  substrate/frame/sudo/src/tests.rs
Labels: T1-FRAME

#2786 Update Safe Call Filters
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/xcm_config.rs
Labels: A1-insubstantial, R0-silent, T14-system_parachains

#2788 Final nits for bridge-hub-test-utils
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/from_grandpa_chain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/from_parachain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/helpers.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/mod.rs
Labels: R0-silent, T10-tests, T15-bridges

#2768 incrementing sufficient accounts references with saturating_add for safety.
  substrate/frame/assets/src/functions.rs
Labels: R0-silent

#2706 fix overflow in `balance_to_point` conversion
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/nomination-pools/src/tests.rs
Labels: R0-silent

#2793 Coretime: Use `Superuser` for sending the transact calls
  polkadot/runtime/parachains/src/coretime/mod.rs
Labels: R0-silent

#2724 Improve `TryDecodeEntireState` output
  substrate/frame/executive/src/lib.rs
  substrate/frame/support/src/traits/try_runtime/decode_entire_state.rs
Labels: T1-FRAME

#2797 Remove rustdocs allowances
  docs/sdk/src/lib.rs
  docs/sdk/src/polkadot_sdk/polkadot.rs
  docs/sdk/src/polkadot_sdk/smart_contracts.rs
  docs/sdk/src/polkadot_sdk/substrate.rs
  docs/sdk/src/polkadot_sdk/xcm.rs
  docs/sdk/src/reference_docs/frame_benchmarking_weight.rs
  docs/sdk/src/reference_docs/frame_currency.rs
  docs/sdk/src/reference_docs/light_nodes.rs
Labels: R0-silent, T11-documentation

#2794 Update rust docs link in README.md
  README.md
Labels: R0-silent

#2807 Fix typo in comments
  substrate/frame/broker/src/lib.rs
Labels: R0-silent

#2799 xcm: Improve debuggability
  Cargo.lock
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  polkadot/xcm/Cargo.toml
  polkadot/xcm/src/double_encoded.rs
  polkadot/xcm/xcm-builder/src/process_xcm_message.rs
  polkadot/xcm/xcm-builder/src/tests/mock.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  prdoc/pr_2799.prdoc
  substrate/primitives/runtime/src/traits.rs
Labels: T6-XCM

#2778 Saner weights + lease calcuation fix.
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_broker.rs
  polkadot/runtime/common/src/slots/mod.rs
  polkadot/runtime/parachains/src/coretime/mod.rs
  polkadot/runtime/rococo/src/lib.rs
  substrate/frame/broker/src/benchmarking.rs
Labels: R0-silent, T8-polkadot

#2689 BEEFY: Support compatibility with Warp Sync - Allow Warp Sync for Validators
  polkadot/cli/src/command.rs
  prdoc/pr_2689.prdoc
  substrate/client/consensus/beefy/Cargo.toml
  substrate/client/consensus/beefy/src/communication/gossip.rs
  substrate/client/consensus/beefy/src/import.rs
  substrate/client/consensus/beefy/src/lib.rs
  substrate/client/consensus/beefy/src/round.rs
  substrate/client/consensus/beefy/src/tests.rs
  substrate/client/consensus/beefy/src/worker.rs
Labels: T0-node

#2612 Fix slot_duration divide by zero panic in rococo-parachain runtime
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: R0-silent

#2806 Remove unused pallet-contracts-primitives
  substrate/frame/contracts/primitives/Cargo.toml
Labels: R0-silent

#2811 Broker pallet: fix interlacing
  prdoc/pr_2811.prdoc
  substrate/frame/broker/src/dispatchable_impls.rs
  substrate/frame/broker/src/tests.rs
Labels: T1-FRAME

#2759 Development Environment Advice Reference Doc
  docs/sdk/src/reference_docs/development_environment_advice.rs
  docs/sdk/src/reference_docs/mod.rs
Labels: R0-silent

#2643 PVF: ensure job processes are cleaned up, add tests
  polkadot/node/core/pvf/common/src/execute.rs
  polkadot/node/core/pvf/execute-worker/src/lib.rs
  polkadot/node/core/pvf/prepare-worker/src/lib.rs
  polkadot/node/core/pvf/src/worker_interface.rs
  polkadot/node/core/pvf/tests/it/process.rs
Labels: R0-silent, T0-node

#2828 core-fellowship: allow infinite demotion period
  .gitlab/pipeline/test.yml
  substrate/frame/core-fellowship/src/benchmarking.rs
  substrate/frame/core-fellowship/src/lib.rs
  substrate/frame/core-fellowship/src/tests.rs
Labels: R0-silent, T2-pallets
