Repository paritytech/polkadot-sdk, pull requests merged in 2023-10, with the labels that each got.

#1322 Tvl pool staking
  polkadot/runtime/westend/src/lib.rs
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/nomination-pools/src/migration.rs
  substrate/frame/nomination-pools/src/mock.rs
  substrate/frame/nomination-pools/src/tests.rs
  substrate/frame/staking/src/lib.rs
  substrate/frame/staking/src/mock.rs
  substrate/primitives/staking/src/lib.rs
Labels: T1-FRAME

#1636 migrate alliance, fast-unstake and bags list to use derive-impl
  polkadot/xcm/xcm-builder/src/tests/pay/mock.rs
  substrate/frame/alliance/src/mock.rs
  substrate/frame/bags-list/src/mock.rs
  substrate/frame/bags-list/src/tests.rs
  substrate/frame/balances/src/lib.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
  substrate/frame/examples/kitchensink/src/tests.rs
  substrate/frame/examples/split/src/mock.rs
  substrate/frame/fast-unstake/src/mock.rs
  substrate/frame/multisig/src/tests.rs
  substrate/frame/proxy/src/tests.rs
  substrate/frame/support/procedural/src/lib.rs
Labels: R0-silent, T1-FRAME

#1763 no-bound derives: Use absolute path for `core`
  substrate/frame/support/procedural/src/lib.rs
  substrate/frame/support/procedural/src/no_bound/clone.rs
  substrate/frame/support/procedural/src/no_bound/debug.rs
  substrate/frame/support/procedural/src/no_bound/default.rs
  substrate/frame/support/procedural/src/no_bound/partial_eq.rs
  substrate/frame/support/src/tests/mod.rs
Labels: R0-silent

#1539 feat: compute pallet/storage prefix hash at compile time
  Cargo.lock
  substrate/client/basic-authorship/src/basic_authorship.rs
  substrate/frame/bags-list/remote-tests/src/snapshot.rs
  substrate/frame/bags-list/remote-tests/src/try_state.rs
  substrate/frame/paged-list/src/paged_list.rs
  substrate/frame/support/procedural/Cargo.toml
  substrate/frame/support/procedural/src/construct_runtime/mod.rs
  substrate/frame/support/procedural/src/pallet/expand/pallet_struct.rs
  substrate/frame/support/procedural/src/pallet/expand/storage.rs
  substrate/frame/support/procedural/src/pallet/mod.rs
  substrate/frame/support/procedural/src/pallet/parse/helper.rs
  substrate/frame/support/procedural/src/storage_alias.rs
  substrate/frame/support/src/storage/generator/double_map.rs
  substrate/frame/support/src/storage/generator/map.rs
  substrate/frame/support/src/storage/generator/nmap.rs
  substrate/frame/support/src/storage/generator/value.rs
  substrate/frame/support/src/storage/mod.rs
  substrate/frame/support/src/storage/types/counted_map.rs
  substrate/frame/support/src/storage/types/counted_nmap.rs
  substrate/frame/support/src/storage/types/double_map.rs
  substrate/frame/support/src/storage/types/map.rs
  substrate/frame/support/src/storage/types/nmap.rs
  substrate/frame/support/src/storage/types/value.rs
  substrate/frame/support/src/tests/storage_alias.rs
  substrate/frame/support/src/traits/metadata.rs
  substrate/frame/support/src/traits/storage.rs
  substrate/frame/tips/src/tests.rs
  substrate/frame/tx-pause/src/lib.rs
Labels: T1-FRAME

#1740 Update bridges subtree
  Cargo.lock
  Cargo.toml
  bridges/bin/runtime-common/src/priority_calculator.rs
  bridges/bin/runtime-common/src/refund_relayer_extension.rs
  bridges/primitives/chain-bridge-hub-kusama/src/lib.rs
  bridges/primitives/chain-bridge-hub-polkadot/src/lib.rs
  bridges/primitives/chain-bridge-hub-rococo/src/lib.rs
  bridges/primitives/chain-bridge-hub-wococo/src/lib.rs
  bridges/primitives/chain-kusama/src/lib.rs
  bridges/primitives/chain-polkadot-bulletin/Cargo.toml
  bridges/primitives/chain-polkadot-bulletin/src/lib.rs
  bridges/primitives/chain-polkadot/src/lib.rs
  bridges/primitives/chain-rococo/src/lib.rs
  bridges/primitives/chain-wococo/src/lib.rs
  bridges/primitives/header-chain/src/justification/verification/mod.rs
  bridges/primitives/runtime/src/chain.rs
  bridges/primitives/runtime/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_hub_rococo_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_hub_wococo_config.rs
Labels: R0-silent, A3-backport, T17-bridges

#1784 Upgraded review-bot to version 2.0.1
  .github/review-bot.yml
  .github/workflows/review-bot.yml
Labels: R0-silent

#1769 remove outdated scripts
  polkadot/scripts/build-demos.sh
  polkadot/scripts/run_all_benches.sh
Labels: R0-silent

#1799 Remove deprecated CI config files
  cumulus/.gitattributes
  cumulus/.github/dependabot.yml
  cumulus/.github/pr-custom-review.yml
  cumulus/.github/workflows/check-D-labels.yml
  cumulus/.github/workflows/check-labels.yml
  cumulus/.github/workflows/docs.yml
  cumulus/.github/workflows/fmt-check.yml
  cumulus/.github/workflows/pr-custom-review.yml
  cumulus/.github/workflows/release-01_branch-check.yml
  cumulus/.github/workflows/release-10_rc-automation.yml
  cumulus/.github/workflows/release-20_extrinsic-ordering-check-from-bin.yml
  cumulus/.github/workflows/release-21_extrinsic-ordering-check-from-two.yml
  cumulus/.github/workflows/release-30_create-draft.yml
  cumulus/.github/workflows/release-99_bot-announce.yml
  cumulus/.github/workflows/srtool.yml
  cumulus/.gitlab-ci.yml
  cumulus/scripts/ci/changelog/README.md
  polkadot/.gitattributes
  polkadot/.github/dependabot.yml
  polkadot/.github/pr-custom-review.yml
  polkadot/.github/workflows/burnin-label-notification.yml
  polkadot/.github/workflows/check-D-labels.yml
  polkadot/.github/workflows/check-bootnodes.yml
  polkadot/.github/workflows/check-labels.yml
  polkadot/.github/workflows/check-licenses.yml
  polkadot/.github/workflows/check-new-bootnodes.yml
  polkadot/.github/workflows/check-weights.yml
  polkadot/.github/workflows/honggfuzz.yml
  polkadot/.github/workflows/pr-custom-review.yml
  polkadot/.github/workflows/release-01_branch-check.yml
  polkadot/.github/workflows/release-10_candidate.yml
  polkadot/.github/workflows/release-20_extrinsic-ordering-check-from-bin.yml
  polkadot/.github/workflows/release-21_extrinsic-ordering-check-from-two.yml
  polkadot/.github/workflows/release-30_publish-draft-release.yml
  polkadot/.github/workflows/release-99_bot.yml
  polkadot/.gitlab-ci.yml
  substrate/.gitattributes
  substrate/.github/dependabot.yml
  substrate/.github/pr-custom-review.yml
  substrate/.github/stale.yml
  substrate/.github/workflows/auto-label-issues.yml
  substrate/.github/workflows/burnin-label-notification.yml
  substrate/.github/workflows/check-D-labels.yml
  substrate/.github/workflows/check-labels.yml
  substrate/.github/workflows/md-link-check.yml
  substrate/.github/workflows/mlc_config.json
  substrate/.github/workflows/monthly-tag.yml
  substrate/.github/workflows/pr-custom-review.yml
  substrate/.github/workflows/release-bot.yml
  substrate/.github/workflows/release-tagging.yml
  substrate/.gitlab-ci.yml
Labels: A1-insubstantial, R0-silent

#1780 PVF: Add back socket path parameter, use tmp socket path
  polkadot/node/core/pvf/common/src/worker/mod.rs
  polkadot/node/core/pvf/common/src/worker_dir.rs
  polkadot/node/core/pvf/execute-worker/src/lib.rs
  polkadot/node/core/pvf/prepare-worker/src/lib.rs
  polkadot/node/core/pvf/src/worker_intf.rs
Labels: T0-node

#1786 Delete full db directory with `purge-chain` subcommand
  polkadot/tests/purge_chain_works.rs
  substrate/client/cli/src/commands/purge_chain_cmd.rs
Labels: T0-node

#1477 Revive Substrate Crate
  Cargo.lock
  Cargo.toml
  substrate/Cargo.toml
  substrate/src/src/lib.rs
Labels: T13-documentation

#1790 migrate babe and authorship to use derive-impl
  substrate/frame/authorship/src/lib.rs
  substrate/frame/babe/src/mock.rs
Labels: R0-silent, T1-FRAME

#1806 chore: bump zombienter version
  .gitlab-ci.yml
Labels: A1-insubstantial, R0-silent, T12-tests

#1333 Treasury spends various asset kinds
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/treasury.rs
  cumulus/parachains/integration-tests/emulated/common/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  polkadot/runtime/common/Cargo.toml
  polkadot/runtime/common/src/impls.rs
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/mod.rs
  polkadot/runtime/rococo/src/weights/pallet_asset_rate.rs
  polkadot/runtime/rococo/src/weights/pallet_treasury.rs
  polkadot/runtime/westend/Cargo.toml
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/mod.rs
  polkadot/runtime/westend/src/weights/pallet_asset_rate.rs
  polkadot/runtime/westend/src/weights/pallet_treasury.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/asset-rate/src/lib.rs
  substrate/frame/bounties/src/tests.rs
  substrate/frame/child-bounties/src/tests.rs
  substrate/frame/support/src/traits/tokens.rs
  substrate/frame/support/src/traits/tokens/misc.rs
  substrate/frame/support/src/traits/tokens/pay.rs
  substrate/frame/tips/src/tests.rs
  substrate/frame/treasury/Cargo.toml
  substrate/frame/treasury/src/benchmarking.rs
  substrate/frame/treasury/src/lib.rs
  substrate/frame/treasury/src/tests.rs
  substrate/frame/treasury/src/weights.rs
  substrate/primitives/core/src/crypto.rs
Labels: T1-FRAME, T4-runtime_API, T10-polkadot, T11-cumulus

#1458 [xcm-emulator] Decouple the `AccountId` type from `AccountId32`
  cumulus/xcm/xcm-emulator/src/lib.rs
Labels: T16-system_parachains

#1788 Fix Asset Hub collator crashing when starting from genesis
  cumulus/polkadot-parachain/src/command.rs
  cumulus/polkadot-parachain/src/service.rs
Labels: T11-cumulus

#1578 Make CheckNonce refuse transactions signed by accounts with no providers
  substrate/bin/node/executor/tests/submit_transaction.rs
  substrate/client/service/test/src/client/mod.rs
  substrate/frame/system/src/extensions/check_nonce.rs
Labels: T1-FRAME

#1812 Check for parent of first ready block being on chain
  substrate/client/network/sync/src/blocks.rs
  substrate/client/network/sync/src/lib.rs
Labels: R0-silent, T0-node

#1803 Update bridges subtree
  bridges/bin/runtime-common/src/messages_call_ext.rs
  bridges/bin/runtime-common/src/refund_relayer_extension.rs
  bridges/modules/grandpa/src/call_ext.rs
  bridges/modules/parachains/src/call_ext.rs
Labels: R0-silent, A3-backport, T17-bridges

#1726 [xcm] Use `Weight::MAX` for `reserve_asset_deposited`, `receive_teleported_asset` benchmarks
  cumulus/parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/send.rs
  cumulus/parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/common/src/impls.rs
  cumulus/parachains/runtimes/assets/asset-hub-kusama/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-kusama/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/assets/asset-hub-polkadot/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-polkadot/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  polkadot/runtime/rococo/src/weights/xcm/mod.rs
  polkadot/runtime/rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  polkadot/runtime/westend/src/weights/xcm/mod.rs
  polkadot/runtime/westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/fungible/benchmarking.rs
Labels: T6-XCM, T16-system_parachains

#1295 remote-ext: fix state download stall on slow connections and reduce memory usage
  Cargo.lock
  substrate/utils/frame/remote-externalities/Cargo.toml
  substrate/utils/frame/remote-externalities/src/lib.rs
Labels: T0-node

#1832 upgrade to macro_magic 0.5.0
  Cargo.lock
  substrate/frame/support/Cargo.toml
  substrate/frame/support/procedural/Cargo.toml
  substrate/frame/support/procedural/src/lib.rs
Labels: R0-silent, T1-FRAME, D0-easy

#1823 Fixes path issue in derive-impl
  substrate/frame/examples/default-config/src/lib.rs
  substrate/frame/support/procedural/src/lib.rs
  substrate/frame/support/test/tests/derive_impl_ui/bad_default_impl_path.stderr
  substrate/frame/support/test/tests/derive_impl_ui/inject_runtime_type_fails_when_type_not_in_scope.stderr
Labels: R0-silent, I2-bug, T1-FRAME, T12-tests, D0-easy

#1649 Xcm emulator nits
  cumulus/parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/send.rs
  cumulus/parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/set_xcm_versions.rs
  cumulus/parachains/integration-tests/emulated/common/src/impls.rs
  cumulus/parachains/integration-tests/emulated/common/src/lib.rs
Labels: T11-cumulus, T16-system_parachains

#1850 PVF worker: bump landlock, update ABI docs
  Cargo.lock
  polkadot/node/core/pvf/common/Cargo.toml
  polkadot/node/core/pvf/common/src/worker/security.rs
Labels: T0-node

#1838 Refactor Identity to benchmark v2
  substrate/frame/identity/src/benchmarking.rs
Labels: R0-silent, I4-refactor, T2-pallets, T14-benchmarks, D0-easy

#1830 ci: bump ci image to rust 1.73.0
  .cargo/config.toml
  .gitlab-ci.yml
  .gitlab/pipeline/build.yml
  .gitlab/pipeline/test.yml
  polkadot/node/core/backing/src/tests/mod.rs
  polkadot/node/overseer/examples/minimal-example.rs
  substrate/client/cli/src/commands/inspect_node_key.rs
  substrate/client/network/common/src/role.rs
  substrate/client/network/src/protocol/notifications/behaviour.rs
  substrate/frame/contracts/src/wasm/prepare.rs
  substrate/frame/nfts/src/tests.rs
  substrate/frame/preimage/src/migration.rs
  substrate/frame/support/test/tests/construct_runtime_ui/deprecated_where_block.stderr
  substrate/frame/support/test/tests/derive_no_bound_ui/debug.stderr
  substrate/frame/support/test/tests/pallet_ui/call_argument_invalid_bound.stderr
  substrate/frame/support/test/tests/pallet_ui/call_argument_invalid_bound_2.stderr
  substrate/frame/support/test/tests/pallet_ui/call_argument_invalid_bound_3.stderr
  substrate/frame/support/test/tests/pallet_ui/dev_mode_without_arg_max_encoded_len.stderr
  substrate/frame/support/test/tests/pallet_ui/error_does_not_derive_pallet_error.stderr
  substrate/frame/support/test/tests/pallet_ui/event_field_not_member.stderr
  substrate/frame/support/test/tests/pallet_ui/inherent_check_inner_span.stderr
  substrate/frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr
  substrate/frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen_unnamed.stderr
  substrate/frame/support/test/tests/pallet_ui/storage_info_unsatisfied.stderr
  substrate/frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.stderr
  substrate/primitives/npos-elections/src/lib.rs
  substrate/primitives/runtime-interface/tests/ui/no_feature_gated_method.stderr
  substrate/utils/frame/benchmarking-cli/src/pallet/writer.rs
Labels: A1-insubstantial, R0-silent

#1854 ci: set CI_IMAGE back to (now updated) .ci-unified
  .gitlab-ci.yml
Labels: A1-insubstantial, R0-silent

#1447 allow treasury to do reserve asset transfers
  polkadot/xcm/xcm-builder/src/lib.rs
  polkadot/xcm/xcm-builder/src/location_conversion.rs
Labels: T6-XCM

#1820 Adding `try_state` hook for `Treasury` pallet
  substrate/frame/treasury/src/benchmarking.rs
  substrate/frame/treasury/src/lib.rs
  substrate/frame/treasury/src/tests.rs
Labels: T12-tests

#1257 Disabled validators runtime API
  cumulus/client/relay-chain-minimal-node/src/blockchain_rpc_client.rs
  cumulus/client/relay-chain-rpc-interface/src/rpc_client.rs
  cumulus/parachains/integration-tests/emulated/common/src/lib.rs
  polkadot/node/core/runtime-api/src/cache.rs
  polkadot/node/core/runtime-api/src/lib.rs
  polkadot/node/core/runtime-api/src/tests.rs
  polkadot/node/subsystem-types/src/messages.rs
  polkadot/node/subsystem-types/src/runtime_client.rs
  polkadot/node/subsystem-util/src/lib.rs
  polkadot/primitives/src/runtime_api.rs
  polkadot/runtime/parachains/src/runtime_api_impl/vstaging.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
Labels: T4-runtime_API

#1556 Add UMP pricing
  Cargo.lock
  cumulus/pallets/parachain-system/Cargo.toml
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/xcmp-queue/src/lib.rs
  cumulus/pallets/xcmp-queue/src/mock.rs
  cumulus/parachain-template/runtime/src/lib.rs
  cumulus/parachains/integration-tests/emulated/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/teleport.rs
  cumulus/parachains/runtimes/assets/asset-hub-kusama/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-kusama/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-polkadot/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-polkadot/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases.rs
  cumulus/parachains/runtimes/assets/test-utils/src/xcm_helpers.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/Cargo.toml
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  cumulus/primitives/utility/Cargo.toml
  cumulus/primitives/utility/src/lib.rs
  polkadot/runtime/common/src/xcm_sender.rs
  polkadot/runtime/parachains/src/dmp.rs
  polkadot/runtime/parachains/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/fungible/benchmarking.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/mock.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/mod.rs
  polkadot/xcm/src/v3/mod.rs
  substrate/frame/support/procedural/src/pallet/expand/warnings.rs
Labels: T6-XCM

#1865 Fix links to implementers' guide
  polkadot/node/collation-generation/src/lib.rs
  polkadot/node/core/pvf/src/lib.rs
  polkadot/node/network/approval-distribution/src/lib.rs
  polkadot/node/overseer/src/lib.rs
  polkadot/node/service/src/relay_chain_selection.rs
  polkadot/roadmap/implementers-guide/README.md
  polkadot/runtime/parachains/src/session_info.rs
Labels: T13-documentation

#1857 Adds instance support for composite enums
  substrate/frame/balances/src/lib.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/composite_helper.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/freeze_reason.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/hold_reason.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/lock_id.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/mod.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/slash_reason.rs
  substrate/frame/support/procedural/src/pallet/parse/composite.rs
  substrate/frame/support/src/lib.rs
  substrate/frame/support/test/tests/construct_runtime_ui.rs
  substrate/frame/support/test/tests/construct_runtime_ui/pass/composite_enum_instance.rs
Labels: R0-silent, T1-FRAME

#1852 sc-consensus-beefy: improve gossip logic
  substrate/client/consensus/beefy/src/communication/gossip.rs
  substrate/client/consensus/beefy/src/communication/mod.rs
  substrate/client/consensus/beefy/src/tests.rs
  substrate/client/consensus/beefy/src/worker.rs
Labels: T0-node

#1867 frame: use derive-impl for beefy and mmr pallets
  substrate/frame/beefy-mmr/src/mock.rs
  substrate/frame/beefy/src/mock.rs
  substrate/frame/merkle-mountain-range/src/mock.rs
Labels: T2-pallets, T12-tests

#1774 Check executor params coherence
  polkadot/node/core/candidate-validation/src/lib.rs
  polkadot/node/core/pvf/common/src/executor_intf.rs
  polkadot/node/core/pvf/execute-worker/src/lib.rs
  polkadot/primitives/src/lib.rs
  polkadot/primitives/src/v6/executor_params.rs
  polkadot/primitives/src/v6/mod.rs
  polkadot/runtime/parachains/src/configuration.rs
Labels: T8-parachains_engineering

#1868 Refactor alliance benchmarks to v2
  substrate/frame/alliance/src/benchmarking.rs
  substrate/frame/support/procedural/src/pallet/expand/warnings.rs
Labels: R0-silent, I4-refactor, T14-benchmarks

#1860 Remove clippy clone-double-ref lint noise
  .cargo/config.toml
Labels: T12-tests

#1855 Discard `Executor`
  polkadot/node/core/pvf/common/src/executor_intf.rs
  polkadot/node/core/pvf/execute-worker/src/lib.rs
  polkadot/node/core/pvf/prepare-worker/src/lib.rs
  polkadot/node/core/pvf/src/testing.rs
  substrate/frame/support/procedural/src/pallet/expand/warnings.rs
Labels: R0-silent

#1862 add link to rfc-0001 in broker README
  docs/DOCUMENTATION_GUIDELINES.md
  substrate/frame/broker/README.md
Labels: R0-silent, T13-documentation

#1828 Include polkadot version in artifact path
  Cargo.lock
  polkadot/cli/Cargo.toml
  polkadot/cli/src/cli.rs
  polkadot/node/core/pvf/src/artifacts.rs
  polkadot/node/primitives/src/lib.rs
Labels: T0-node

#1705 Paired-key Crypto Scheme
  substrate/primitives/core/src/bls.rs
  substrate/primitives/core/src/crypto.rs
  substrate/primitives/core/src/ecdsa.rs
  substrate/primitives/core/src/hexdisplay.rs
  substrate/primitives/core/src/lib.rs
  substrate/primitives/core/src/paired_crypto.rs
Labels: T0-node

#1484 Refactor staking ledger
  polkadot/runtime/parachains/src/disputes/slashing/benchmarking.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/lib.rs
  substrate/frame/session/benchmarking/src/lib.rs
  substrate/frame/staking/src/benchmarking.rs
  substrate/frame/staking/src/ledger.rs
  substrate/frame/staking/src/lib.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/slashing.rs
  substrate/frame/staking/src/tests.rs
  substrate/primitives/staking/src/lib.rs
Labels: T1-FRAME, T2-pallets

#1176 fix: GoAhead signal only set when runtime upgrade is enacted from parachain side
  polkadot/runtime/common/src/paras_registrar/mod.rs
  polkadot/runtime/parachains/src/inclusion/mod.rs
  polkadot/runtime/parachains/src/inclusion/tests.rs
  polkadot/runtime/parachains/src/lib.rs
  polkadot/runtime/parachains/src/paras/benchmarking.rs
  polkadot/runtime/parachains/src/paras/benchmarking/pvf_check.rs
  polkadot/runtime/parachains/src/paras/mod.rs
  polkadot/runtime/parachains/src/paras/tests.rs
Labels: I2-bug, T10-polkadot

#1878 Fix typos
  cumulus/client/consensus/common/src/tests.rs
  cumulus/client/relay-chain-interface/src/lib.rs
  cumulus/client/relay-chain-rpc-interface/src/light_client_worker.rs
  polkadot/roadmap/implementers-guide/src/node/disputes/dispute-coordinator.md
Labels: R0-silent

#1870 Arkworks Elliptic Curve utils overhaul
  Cargo.lock
  substrate/primitives/core/Cargo.toml
  substrate/primitives/core/src/bandersnatch.rs
  substrate/primitives/crypto/ec-utils/Cargo.toml
  substrate/primitives/crypto/ec-utils/src/bls12_377.rs
  substrate/primitives/crypto/ec-utils/src/bls12_381.rs
  substrate/primitives/crypto/ec-utils/src/bw6_761.rs
  substrate/primitives/crypto/ec-utils/src/ed_on_bls12_377.rs
  substrate/primitives/crypto/ec-utils/src/ed_on_bls12_381_bandersnatch.rs
  substrate/primitives/crypto/ec-utils/src/lib.rs
  substrate/primitives/crypto/ec-utils/src/test-data/g1_compressed_valid_test_vectors.dat
  substrate/primitives/crypto/ec-utils/src/test-data/g1_uncompressed_valid_test_vectors.dat
  substrate/primitives/crypto/ec-utils/src/test-data/g2_compressed_valid_test_vectors.dat
  substrate/primitives/crypto/ec-utils/src/test-data/g2_uncompressed_valid_test_vectors.dat
  substrate/primitives/crypto/ec-utils/src/utils.rs
Labels: T0-node

#1568 Update the alerts to use a new metric substrate_unbounded_channel_size
  substrate/scripts/ci/monitoring/alerting-rules/alerting-rules.yaml
Labels: T0-node

#1875 [CI] Add link checker
  .config/lychee.toml
  .github/workflows/check-links.yml
  .gitignore
Labels: R0-silent

#1877 sp-api: Improve error message for duplicate runtime apis
  substrate/primitives/api/proc-macro/src/impl_runtime_apis.rs
  substrate/primitives/api/test/tests/ui/impl_two_traits_with_same_name.stderr
Labels: R0-silent

#1888 sc-consensus-beefy: fix initialization when state is unavailable
  substrate/client/consensus/beefy/src/lib.rs
  substrate/client/consensus/beefy/src/tests.rs
Labels: T0-node

#1847 `extract` amount method for `fungible/s` `Imbalance`
  substrate/frame/balances/src/impl_currency.rs
  substrate/frame/support/src/traits/tokens/fungible/imbalance.rs
  substrate/frame/support/src/traits/tokens/fungibles/imbalance.rs
  substrate/frame/support/src/traits/tokens/imbalance.rs
Labels: T1-FRAME

#1892 Add missing env
  .github/workflows/release-50_publish-docker.yml
Labels: R0-silent

#1884 Workspace maintenance
  Cargo.toml
  substrate/bin/node-template/runtime/Cargo.toml
  substrate/bin/node/runtime/Cargo.toml
  substrate/primitives/consensus/sassafras/Cargo.toml
Labels: R0-silent

#1770 cleanup a few hidden imports in frame-support
  substrate/frame/staking/reward-curve/src/lib.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/inherent.rs
  substrate/frame/support/procedural/tools/src/lib.rs
  substrate/frame/support/src/lib.rs
Labels: R0-silent

#1848 [xcm] Small enhancements for `NetworkExportTable` and `xcm-builder`
  bridges/modules/xcm-bridge-hub-router/src/mock.rs
  cumulus/parachains/runtimes/assets/asset-hub-kusama/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-polkadot/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/common/src/lib.rs
  cumulus/parachains/runtimes/assets/common/src/local_and_foreign_assets.rs
  cumulus/parachains/runtimes/assets/common/src/matching.rs
  polkadot/xcm/xcm-builder/src/filter_asset_location.rs
  polkadot/xcm/xcm-builder/src/lib.rs
  polkadot/xcm/xcm-builder/src/matches_location.rs
  polkadot/xcm/xcm-builder/src/tests/bridging/paid_remote_relay_relay.rs
  polkadot/xcm/xcm-builder/src/tests/bridging/remote_para_para.rs
  polkadot/xcm/xcm-builder/src/tests/bridging/remote_para_para_via_relay.rs
  polkadot/xcm/xcm-builder/src/tests/bridging/remote_relay_relay.rs
  polkadot/xcm/xcm-builder/src/universal_exports.rs
  substrate/frame/support/src/traits.rs
  substrate/frame/support/src/traits/members.rs
Labels: T6-XCM

#1753 nit: use traits::tokens::fungible => use traits::fungible
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases.rs
  cumulus/parachains/runtimes/test-utils/src/lib.rs
  polkadot/xcm/xcm-builder/src/asset_conversion.rs
  polkadot/xcm/xcm-builder/src/fungibles_adapter.rs
  polkadot/xcm/xcm-builder/src/nonfungibles_adapter.rs
  substrate/frame/assets/src/tests.rs
  substrate/frame/balances/src/tests/mod.rs
  substrate/frame/examples/kitchensink/src/lib.rs
  substrate/frame/support/src/traits/tokens/fungible/item_of.rs
  substrate/frame/transaction-payment/asset-conversion-tx-payment/src/lib.rs
Labels: T2-pallets

#1886 ci: remove obsolete `allow_failure` annotations
  .gitlab/pipeline/check.yml
  .gitlab/pipeline/test.yml
Labels: A1-insubstantial, R0-silent

#1663 PVF worker: Maintain lists of used syscalls
  .cargo/config.toml
  .cargo/musl-g++
  .cargo/musl-gcc
  .gitlab/pipeline/test.yml
  polkadot/scripts/list-syscalls/execute-worker-syscalls
  polkadot/scripts/list-syscalls/list-syscalls.rb
  polkadot/scripts/list-syscalls/prepare-worker-syscalls
Labels: R0-silent

#1733 increase MAX_ASSETS_FOR_BUY_EXECUTION
  polkadot/xcm/xcm-builder/src/barriers.rs
Labels: T6-XCM

#1921 Fix para-scheduler migration on Rococo
  polkadot/runtime/parachains/src/scheduler/migration.rs
  prdoc/pr_1921.prdoc
  substrate/frame/support/src/migrations.rs
Labels: T2-pallets

#1919 bridges: add missing crate descriptions
  bridges/bin/runtime-common/Cargo.toml
  bridges/modules/grandpa/Cargo.toml
  bridges/modules/parachains/Cargo.toml
  bridges/primitives/test-utils/Cargo.toml
Labels: T13-documentation

#1904 Publish `penpal-runtime` crate
  cumulus/parachains/runtimes/testing/penpal/Cargo.toml
Labels: T12-tests

#1913 Start BEEFY client by default for Polkadot nodes
  polkadot/cli/src/command.rs
  polkadot/node/service/src/lib.rs
Labels: T0-node

#1910 Switch to the release env
  .github/workflows/check-licenses.yml
  .github/workflows/release-50_publish-docker.yml
Labels: R0-silent

#1909 Add Runtime Missing Crate Descriptions
  cumulus/parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  cumulus/parachains/runtimes/glutton/glutton-kusama/Cargo.toml
  cumulus/parachains/runtimes/starters/seedling/Cargo.toml
  cumulus/parachains/runtimes/starters/shell/Cargo.toml
  polkadot/core-primitives/Cargo.toml
  polkadot/runtime/common/Cargo.toml
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/rococo/constants/Cargo.toml
  polkadot/runtime/westend/Cargo.toml
  polkadot/runtime/westend/constants/Cargo.toml
  polkadot/xcm/pallet-xcm/Cargo.toml
Labels: A1-insubstantial

#1561 Trading trait and deal with metadata in Mutate trait for nonfungibles_v2
  substrate/frame/nfts/src/impl_nonfungibles.rs
  substrate/frame/support/src/traits.rs
  substrate/frame/support/src/traits/tokens/nonfungible_v2.rs
  substrate/frame/support/src/traits/tokens/nonfungibles_v2.rs
Labels: T2-pallets

#1908 upgraded review bot to v2.1.0
  .github/workflows/review-bot.yml
  .github/workflows/review-trigger.yml
Labels: R0-silent

#1898 Use prebuilt try-runtime binary in CI
  .gitlab/pipeline/check.yml
Labels: T12-tests

#1911 Cumulus: Allow aura to use initialized collation request receiver
  cumulus/client/consensus/aura/src/collators/basic.rs
  cumulus/parachain-template/node/src/service.rs
  cumulus/polkadot-parachain/src/service.rs
Labels: T0-node, T11-cumulus

#1873 [FRAME] Message Queue use proper overweight limit
  prdoc/pr_1873.prdoc
  substrate/frame/message-queue/src/integration_test.rs
  substrate/frame/message-queue/src/lib.rs
  substrate/frame/message-queue/src/mock.rs
  substrate/frame/message-queue/src/tests.rs
Labels: T1-FRAME

#1931 bump zombienet version
  .gitlab-ci.yml
Labels: A1-insubstantial, R0-silent, T12-tests

#1945 [prdoc] Start BEEFY gadget by default for Polkadot nodes
  prdoc/pr_1913.prdoc
Labels: T13-documentation

#1947 Pin PRDoc image to v0.0.5 until we are ready for v0.0.6
  .github/workflows/check-prdoc.yml
Labels: R0-silent

#1920 Do not force collators to update after enabling async backing
  polkadot/node/network/collator-protocol/src/validator_side/collation.rs
  polkadot/node/network/collator-protocol/src/validator_side/mod.rs
  polkadot/node/network/collator-protocol/src/validator_side/tests/mod.rs
  polkadot/node/network/collator-protocol/src/validator_side/tests/prospective_parachains.rs
Labels: T0-node

#1942 Expose prometheus metrics for minimal-relay-chain node in collators
  Cargo.lock
  cumulus/client/relay-chain-minimal-node/Cargo.toml
  cumulus/client/relay-chain-minimal-node/src/collator_overseer.rs
  cumulus/client/relay-chain-minimal-node/src/lib.rs
Labels: T0-node, T11-cumulus

#1935 Switch trie cache random seed
  Cargo.lock
  substrate/primitives/trie/Cargo.toml
  substrate/primitives/trie/src/cache/shared_cache.rs
Labels: R0-silent

#1949 Remove some dbgs
  cumulus/parachains/integration-tests/emulated/common/src/macros.rs
Labels: R0-silent, T6-XCM

#1950 Revert "Check for parent of first ready block being on chain (#1812)"
  substrate/client/network/sync/src/blocks.rs
  substrate/client/network/sync/src/lib.rs
Labels: R0-silent, T0-node

#1259 Handling of disabled validators in backing subsystem
  polkadot/node/core/backing/src/lib.rs
  polkadot/node/core/backing/src/tests/mod.rs
  polkadot/node/core/backing/src/tests/prospective_parachains.rs
  polkadot/node/core/provisioner/src/lib.rs
  polkadot/node/subsystem-util/src/lib.rs
  polkadot/node/subsystem-util/src/vstaging.rs
Labels: T0-node, T9-parachains_protocol

#1954 [testnet] AssetHubRococo nits
  cumulus/parachains/chain-specs/asset-hub-wococo.json
  cumulus/polkadot-parachain/chain-specs/asset-hub-rococo.json
  cumulus/polkadot-parachain/chain-specs/asset-hub-wococo.json
  cumulus/polkadot-parachain/src/chain_spec/asset_hubs.rs
  cumulus/polkadot-parachain/src/command.rs
  cumulus/scripts/bridges_common.sh
  cumulus/scripts/bridges_rococo_wococo.sh
Labels: T11-cumulus

#1436 Vstaging statement distribution omnibus
  polkadot/node/core/backing/src/lib.rs
  polkadot/node/core/prospective-parachains/src/lib.rs
  polkadot/node/network/collator-protocol/src/collator_side/mod.rs
  polkadot/node/network/collator-protocol/src/collator_side/validators_buffer.rs
  polkadot/node/network/gossip-support/src/lib.rs
  polkadot/node/network/statement-distribution/src/lib.rs
  polkadot/node/network/statement-distribution/src/v2/candidates.rs
  polkadot/node/network/statement-distribution/src/v2/cluster.rs
  polkadot/node/network/statement-distribution/src/v2/grid.rs
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  polkadot/node/network/statement-distribution/src/v2/requests.rs
  polkadot/node/network/statement-distribution/src/v2/statement_store.rs
  polkadot/node/network/statement-distribution/src/v2/tests/grid.rs
  polkadot/node/network/statement-distribution/src/v2/tests/requests.rs
Labels: R0-silent

#1856 sc-executor: Increase maximum instance count
  Cargo.lock
  substrate/client/cli/src/params/runtime_params.rs
  substrate/client/executor/wasmtime/Cargo.toml
  substrate/client/executor/wasmtime/src/instance_wrapper.rs
  substrate/client/executor/wasmtime/src/runtime.rs
Labels: T0-node

#1951 wasm-builder: manually set CARGO_TARGET_DIR
  substrate/utils/wasm-builder/src/prerequisites.rs
  substrate/utils/wasm-builder/src/wasm_project.rs
Labels: R0-silent

#1969 paras-scheduler: Fix migration to V1
  polkadot/runtime/parachains/src/assigner.rs
  polkadot/runtime/parachains/src/assigner_parachains.rs
  polkadot/runtime/parachains/src/scheduler.rs
  polkadot/runtime/parachains/src/scheduler/migration.rs
Labels: R0-silent

#1972 [testnet] BridgeHubRococo nits
  bridges/primitives/chain-bridge-hub-rococo/src/lib.rs
  bridges/primitives/chain-bridge-hub-wococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/bridges/bridge-hub-rococo/src/tests/example.rs
  cumulus/parachains/integration-tests/emulated/common/src/constants.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/README.md
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_common_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_hub_rococo_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_hub_wococo_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_grandpa_rococo_finality.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_grandpa_wococo_finality.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_messages_rococo_to_wococo.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_messages_wococo_to_rococo.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_parachains_within_rococo.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_parachains_within_wococo.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/polkadot-parachain/src/chain_spec/bridge_hubs.rs
Labels: T9-cumulus

#1565 polkadot: eradicate `LeafStatus`
  Cargo.lock
  cumulus/client/relay-chain-minimal-node/Cargo.toml
  cumulus/client/relay-chain-minimal-node/src/collator_overseer.rs
  polkadot/node/core/bitfield-signing/src/lib.rs
  polkadot/node/core/provisioner/src/lib.rs
  polkadot/node/network/availability-distribution/src/requester/mod.rs
  polkadot/node/overseer/Cargo.toml
  polkadot/node/overseer/src/dummy.rs
  polkadot/node/overseer/src/lib.rs
  polkadot/node/service/Cargo.toml
  polkadot/node/service/src/overseer.rs
  polkadot/node/subsystem-test-helpers/src/mock.rs
  polkadot/node/subsystem-types/src/lib.rs
  polkadot/node/subsystem/src/lib.rs
  polkadot/roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A1-insubstantial, T0-node, T8-polkadot

#1990 Always schedule at least one job onto a core
  polkadot/runtime/parachains/src/scheduler.rs
Labels: R0-silent

#1876 Resolve Credit to Account impls of `OnUnbalanced` trait
  substrate/frame/support/src/traits/tokens/imbalance.rs
  substrate/frame/support/src/traits/tokens/imbalance/on_unbalanced.rs
Labels: T1-FRAME

#1995 Update wasm-opt to 0.116
  Cargo.lock
  substrate/utils/wasm-builder/Cargo.toml
Labels: R0-silent

#1996 `CheckWeight`: Add more logging
  substrate/frame/support/src/dispatch.rs
  substrate/frame/system/src/extensions/check_weight.rs
  substrate/primitives/weights/src/weight_v2.rs
Labels: T1-FRAME

#1661 Make `IdentityInfo` generic in `pallet-identity`
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/alliance/src/lib.rs
  substrate/frame/alliance/src/mock.rs
  substrate/frame/identity/src/benchmarking.rs
  substrate/frame/identity/src/lib.rs
  substrate/frame/identity/src/simple.rs
  substrate/frame/identity/src/tests.rs
  substrate/frame/identity/src/types.rs
Labels: T2-pallets

#2002 polkadot: enable tikv-jemallocator/unprefixed_malloc_on_supported_platforms
  polkadot/Cargo.toml
Labels: A1-insubstantial

#1771 PVF: Add worker check during tests and benches
  Cargo.lock
  polkadot/cli/src/command.rs
  polkadot/node/core/pvf/Cargo.toml
  polkadot/node/core/pvf/benches/host_prepare_rococo_runtime.rs
  polkadot/node/core/pvf/bin/puppet_worker.rs
  polkadot/node/core/pvf/common/Cargo.toml
  polkadot/node/core/pvf/common/src/worker/mod.rs
  polkadot/node/core/pvf/src/artifacts.rs
  polkadot/node/core/pvf/src/host.rs
  polkadot/node/core/pvf/src/lib.rs
  polkadot/node/core/pvf/src/testing.rs
  polkadot/node/core/pvf/src/worker_intf.rs
  polkadot/node/core/pvf/tests/it/main.rs
  polkadot/node/core/pvf/tests/it/worker_common.rs
  polkadot/node/service/Cargo.toml
  polkadot/node/service/src/workers.rs
  polkadot/src/bin/execute-worker.rs
  polkadot/src/bin/prepare-worker.rs
  substrate/utils/build-script-utils/src/version.rs
Labels: T0-node

#2008 Remove obsolete comment.
  polkadot/runtime/parachains/src/scheduler.rs
Labels: A1-insubstantial

#1831 Improve features dev-ex
  .config/zepter.yaml
  .gitlab/pipeline/check.yml
  bridges/primitives/chain-polkadot-bulletin/Cargo.toml
  bridges/primitives/relayers/Cargo.toml
  cumulus/pallets/parachain-system/Cargo.toml
  cumulus/pallets/xcmp-queue/Cargo.toml
  cumulus/parachains/common/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-kusama/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/common/Cargo.toml
  cumulus/parachains/runtimes/assets/test-utils/Cargo.toml
  cumulus/parachains/runtimes/test-utils/Cargo.toml
  cumulus/primitives/timestamp/Cargo.toml
  cumulus/primitives/utility/Cargo.toml
  docs/STYLE_GUIDE.md
  polkadot/parachain/test-parachains/Cargo.toml
  polkadot/parachain/test-parachains/adder/Cargo.toml
  polkadot/parachain/test-parachains/undying/Cargo.toml
  polkadot/runtime/parachains/Cargo.toml
  polkadot/xcm/Cargo.toml
  polkadot/xcm/pallet-xcm-benchmarks/Cargo.toml
  polkadot/xcm/pallet-xcm/Cargo.toml
  polkadot/xcm/xcm-executor/Cargo.toml
  substrate/bin/node/runtime/Cargo.toml
  substrate/frame/asset-conversion/Cargo.toml
  substrate/frame/democracy/Cargo.toml
  substrate/frame/glutton/Cargo.toml
  substrate/frame/identity/Cargo.toml
  substrate/frame/message-queue/Cargo.toml
  substrate/frame/multisig/Cargo.toml
  substrate/frame/nfts/Cargo.toml
  substrate/frame/nomination-pools/benchmarking/Cargo.toml
  substrate/frame/referenda/Cargo.toml
  substrate/frame/society/Cargo.toml
  substrate/frame/statement/Cargo.toml
  substrate/frame/support/Cargo.toml
  substrate/primitives/api/proc-macro/Cargo.toml
  substrate/primitives/consensus/beefy/Cargo.toml
  substrate/primitives/core/Cargo.toml
  substrate/primitives/io/Cargo.toml
  substrate/primitives/merkle-mountain-range/Cargo.toml
  substrate/primitives/runtime-interface/test-wasm/Cargo.toml
  substrate/primitives/statement-store/Cargo.toml
  substrate/primitives/wasm-interface/Cargo.toml
  substrate/test-utils/runtime/Cargo.toml
Labels: R0-silent

#2012 [ci] Run check-rust-feature-propagation in pr and master
  .gitlab/pipeline/check.yml
Labels: R0-silent

#2010 basic-authorship: Improve time recording and logging
  substrate/client/basic-authorship/src/basic_authorship.rs
Labels: T0-node

#1851 Small optimisation to `--profile dev` wasm builds
  substrate/utils/wasm-builder/src/builder.rs
  substrate/utils/wasm-builder/src/wasm_project.rs
Labels: T1-FRAME

#2022 Contracts: Add benchmarks to include files
  substrate/frame/contracts/Cargo.toml
Labels: R0-silent

#2017 publish pallet-root-testing
  substrate/frame/root-testing/Cargo.toml
Labels: R0-silent

#2026 Sort the benchmarks before listing them
  substrate/utils/frame/benchmarking-cli/src/pallet/command.rs
Labels: A1-insubstantial, R0-silent

#1897 `polkadot-parachain-primitives` should not depend on `frame-support`.
  Cargo.lock
  polkadot/parachain/Cargo.toml
  polkadot/parachain/src/primitives.rs
Labels: T8-polkadot

#1914 Expose collection attributes from `Inspect` trait
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/nfts/runtime-api/src/lib.rs
  substrate/frame/nfts/src/impl_nonfungibles.rs
  substrate/frame/nfts/src/tests.rs
  substrate/frame/support/src/traits/tokens/nonfungible_v2.rs
  substrate/frame/support/src/traits/tokens/nonfungibles_v2.rs
Labels: T2-pallets, T4-runtime_API, R1-breaking_change

#2042 Removed TODO from test-case for hard-coded delivery fee estimation
  cumulus/parachains/runtimes/assets/asset-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/assets/test-utils/src/lib.rs
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases_over_bridge.rs
Labels: T9-cumulus

#2039 cumulus: fix test runtimes panic
  cumulus/parachains/runtimes/glutton/glutton-kusama/src/lib.rs
  cumulus/parachains/runtimes/starters/seedling/src/lib.rs
  cumulus/parachains/runtimes/starters/shell/src/lib.rs
  substrate/frame/aura/src/lib.rs
  substrate/frame/babe/src/lib.rs
Labels: I2-bug, T9-cumulus

#2027 sp-version: Improve the docs
  substrate/primitives/version/src/lib.rs
Labels: R0-silent

#2040 add `authorities_len` for aura
  substrate/frame/aura/src/lib.rs
  substrate/frame/aura/src/tests.rs
Labels: T1-FRAME

#1793 Resolving Compile Errors in Core Time Prep Tests
  polkadot/runtime/parachains/src/assigner.rs
  polkadot/runtime/parachains/src/assigner_on_demand/mod.rs
  polkadot/runtime/parachains/src/assigner_on_demand/tests.rs
  polkadot/runtime/parachains/src/assigner_parachains.rs
  polkadot/runtime/parachains/src/assigner_parachains/mock_helpers.rs
  polkadot/runtime/parachains/src/assigner_parachains/tests.rs
  polkadot/runtime/parachains/src/builder.rs
  polkadot/runtime/parachains/src/mock.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
  polkadot/runtime/parachains/src/scheduler.rs
  polkadot/runtime/parachains/src/scheduler/common.rs
  polkadot/runtime/parachains/src/scheduler/tests.rs
Labels: T8-polkadot

#2052 upgrade docify to 0.2.5
  Cargo.lock
  substrate/frame/bags-list/Cargo.toml
  substrate/frame/fast-unstake/Cargo.toml
  substrate/frame/paged-list/Cargo.toml
  substrate/frame/scheduler/Cargo.toml
  substrate/frame/sudo/Cargo.toml
  substrate/frame/support/Cargo.toml
  substrate/frame/timestamp/Cargo.toml
Labels: R0-silent, T1-FRAME

#1337 feat: FRAME umbrella crate.
  Cargo.lock
  Cargo.toml
  docs/mermaid/substrate_client_runtime.mmd
  docs/mermaid/substrate_simple.mmd
  docs/mermaid/substrate_with_frame.mmd
  substrate/Cargo.toml
  substrate/bin/minimal/node/Cargo.toml
  substrate/bin/minimal/node/build.rs
  substrate/bin/minimal/node/src/chain_spec.rs
  substrate/bin/minimal/node/src/cli.rs
  substrate/bin/minimal/node/src/command.rs
  substrate/bin/minimal/node/src/lib.rs
  substrate/bin/minimal/node/src/main.rs
  substrate/bin/minimal/node/src/rpc.rs
  substrate/bin/minimal/node/src/service.rs
  substrate/bin/minimal/runtime/Cargo.toml
  substrate/bin/minimal/runtime/build.rs
  substrate/bin/minimal/runtime/src/lib.rs
  substrate/client/consensus/manual-seal/src/lib.rs
  substrate/frame/Cargo.toml
  substrate/frame/examples/Cargo.toml
  substrate/frame/examples/frame-crate/Cargo.toml
  substrate/frame/examples/frame-crate/src/lib.rs
  substrate/frame/examples/src/lib.rs
  substrate/frame/src/lib.rs
  substrate/frame/sudo/src/lib.rs
  substrate/frame/sudo/src/mock.rs
  substrate/frame/support/src/lib.rs
  substrate/frame/support/test/stg_frame_crate/Cargo.toml
  substrate/frame/support/test/stg_frame_crate/frame/Cargo.toml
  substrate/frame/support/test/tests/pallet_ui/event_type_invalid_bound_no_frame_crate.rs
  substrate/frame/support/test/tests/pallet_ui/event_type_invalid_bound_no_frame_crate.stderr
  substrate/frame/system/Cargo.toml
  substrate/frame/system/src/lib.rs
  substrate/frame/timestamp/src/lib.rs
  substrate/frame/transaction-payment/src/lib.rs
  substrate/primitives/api/proc-macro/src/utils.rs
  substrate/primitives/core/src/crypto.rs
  substrate/primitives/keyring/src/ed25519.rs
  substrate/primitives/keyring/src/lib.rs
  substrate/primitives/keyring/src/sr25519.rs
  substrate/primitives/runtime/src/generic/unchecked_extrinsic.rs
  substrate/primitives/runtime/src/lib.rs
  substrate/primitives/runtime/src/traits.rs
  substrate/primitives/session/src/lib.rs
  substrate/primitives/session/src/runtime_api.rs
  substrate/primitives/weights/src/lib.rs
  substrate/src/lib.rs
Labels: R0-silent

#2056 make polkadot die graciously
  polkadot/node/core/dispute-coordinator/src/lib.rs
  polkadot/node/network/availability-recovery/src/lib.rs
Labels: A1-insubstantial, R0-silent, T8-polkadot

#1927 Enable "cargo run --bin substrate-node"
  Cargo.toml
Labels: R0-silent

#2053 level-monitor: Fix issue with warp syncing
  cumulus/client/consensus/common/src/level_monitor.rs
Labels: T0-node

#2069 upgrade to docify 0.2.6
  Cargo.lock
  substrate/frame/bags-list/Cargo.toml
  substrate/frame/fast-unstake/Cargo.toml
  substrate/frame/paged-list/Cargo.toml
  substrate/frame/scheduler/Cargo.toml
  substrate/frame/sudo/Cargo.toml
  substrate/frame/support/Cargo.toml
  substrate/frame/timestamp/Cargo.toml
Labels: R0-silent, T1-FRAME

#2054 Automatically build and attach production and dev runtimes to GH releases
  .github/workflows/build-and-attach-release-runtimes.yml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  cumulus/parachains/runtimes/glutton/glutton-kusama/Cargo.toml
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/westend/Cargo.toml
Labels: R0-silent

#2075 fix(frame-benchmarking-cli): Pass heap_pages param to WasmExecutor
  substrate/utils/frame/benchmarking-cli/src/pallet/command.rs
Labels: T1-FRAME

#2073 Improve Client CLI help readability
  Cargo.lock
  polkadot/cli/src/cli.rs
  substrate/client/cli/Cargo.toml
  substrate/client/cli/src/commands/run_cmd.rs
  substrate/client/cli/src/params/import_params.rs
  substrate/client/cli/src/params/keystore_params.rs
  substrate/client/cli/src/params/network_params.rs
  substrate/client/cli/src/params/node_key_params.rs
  substrate/client/cli/src/params/offchain_worker_params.rs
  substrate/client/cli/src/params/prometheus_params.rs
  substrate/client/cli/src/params/pruning_params.rs
  substrate/client/cli/src/params/runtime_params.rs
  substrate/client/cli/src/params/shared_params.rs
  substrate/client/cli/src/params/telemetry_params.rs
  substrate/client/cli/src/params/transaction_pool_params.rs
  substrate/client/storage-monitor/src/lib.rs
Labels: A1-insubstantial, T0-node

#2019 Improve `try-state` developer experience & fix bug
  substrate/frame/executive/src/lib.rs
  substrate/frame/support/procedural/src/pallet/expand/hooks.rs
  substrate/frame/support/src/traits/try_runtime.rs
Labels: T1-FRAME

#1976 Stop `Balances` pallet erroneously double incrementing and decrementing consumers
  substrate/frame/balances/src/lib.rs
  substrate/frame/balances/src/tests/currency_tests.rs
Labels: T1-FRAME

#2079 contracts migration: remove unnecessary panics
  .gitlab/pipeline/check.yml
  substrate/frame/contracts/src/migration.rs
Labels: T1-FRAME

#1800 Refactor transaction storage pallet to use fungible traits
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/transaction-storage/src/benchmarking.rs
  substrate/frame/transaction-storage/src/lib.rs
  substrate/frame/transaction-storage/src/mock.rs
  substrate/frame/transaction-storage/src/tests.rs
Labels: T2-pallets

#2084 Switch from `tiny-bip39` to `bip39` crate
  Cargo.lock
  substrate/client/cli/Cargo.toml
  substrate/client/cli/src/commands/generate.rs
  substrate/primitives/core/Cargo.toml
  substrate/primitives/core/src/crypto.rs
Labels: T0-node

#2051 pub `keystore_accounts/accounts_from_keys` for offchain Signer
  substrate/frame/system/src/offchain.rs
Labels: R0-silent

#2064 parachain-system: Send same event & digest as a standalone chain
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/parachain-system/src/tests.rs
  substrate/frame/system/src/lib.rs
Labels: T1-FRAME

#2009 PVF worker: Add seccomp restrictions (restrict networking)
  Cargo.lock
  polkadot/node/core/candidate-validation/src/lib.rs
  polkadot/node/core/pvf/Cargo.toml
  polkadot/node/core/pvf/benches/host_prepare_rococo_runtime.rs
  polkadot/node/core/pvf/common/Cargo.toml
  polkadot/node/core/pvf/common/src/lib.rs
  polkadot/node/core/pvf/common/src/worker/mod.rs
  polkadot/node/core/pvf/common/src/worker/security.rs
  polkadot/node/core/pvf/common/src/worker/security/landlock.rs
  polkadot/node/core/pvf/common/src/worker/security/mod.rs
  polkadot/node/core/pvf/common/src/worker/security/seccomp.rs
  polkadot/node/core/pvf/execute-worker/Cargo.toml
  polkadot/node/core/pvf/execute-worker/src/lib.rs
  polkadot/node/core/pvf/prepare-worker/Cargo.toml
  polkadot/node/core/pvf/prepare-worker/src/lib.rs
  polkadot/node/core/pvf/prepare-worker/src/memory_stats.rs
  polkadot/node/core/pvf/src/execute/worker_intf.rs
  polkadot/node/core/pvf/src/host.rs
  polkadot/node/core/pvf/src/lib.rs
  polkadot/node/core/pvf/src/prepare/worker_intf.rs
  polkadot/node/core/pvf/src/security.rs
  polkadot/node/core/pvf/src/worker_intf.rs
  polkadot/node/core/pvf/tests/it/adder.rs
  polkadot/node/core/pvf/tests/it/main.rs
  polkadot/roadmap/implementers-guide/src/node/utility/pvf-host-and-workers.md
  polkadot/scripts/list-syscalls/execute-worker-syscalls
  polkadot/scripts/list-syscalls/prepare-worker-syscalls
Labels: T0-node

#2091 Contracts migration update
  substrate/frame/contracts/src/migration.rs
Labels: R0-silent

#1999 Add test to demonstrate the failure scenario
  Cargo.lock
  substrate/client/network/sync/src/lib.rs
Labels: R0-silent, T0-node

#2088 Reduce Impact on Identity Pallet in Migration
  Cargo.lock
  polkadot/runtime/common/Cargo.toml
  polkadot/runtime/common/src/identity_migrator.rs
  polkadot/runtime/common/src/lib.rs
  polkadot/runtime/rococo/src/impls.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/pallet_identity.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/pallet_identity.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/alliance/src/mock.rs
  substrate/frame/identity/src/benchmarking.rs
  substrate/frame/identity/src/lib.rs
  substrate/frame/identity/src/tests.rs
  substrate/frame/identity/src/weights.rs
Labels: T1-FRAME

#2068 Elliptic curves utilities refactory
  Cargo.lock
  substrate/primitives/crypto/ec-utils/Cargo.toml
  substrate/primitives/crypto/ec-utils/src/bls12_377.rs
  substrate/primitives/crypto/ec-utils/src/bls12_381.rs
  substrate/primitives/crypto/ec-utils/src/bw6_761.rs
  substrate/primitives/crypto/ec-utils/src/ed_on_bls12_377.rs
  substrate/primitives/crypto/ec-utils/src/ed_on_bls12_381_bandersnatch.rs
  substrate/primitives/crypto/ec-utils/src/lib.rs
  substrate/primitives/crypto/ec-utils/src/utils.rs
Labels: T0-node

#2095 xcmp-queue: remove outdated bridging comment
  cumulus/pallets/xcmp-queue/src/bridging.rs
Labels: R0-silent

#2083 [DNM] bump zombienet version
  .gitlab-ci.yml
  polkadot/zombienet_tests/functional/0001-parachains-pvf.toml
  polkadot/zombienet_tests/functional/0002-parachains-disputes.toml
  polkadot/zombienet_tests/functional/0004-parachains-garbage-candidate.toml
  polkadot/zombienet_tests/misc/0001-paritydb.toml
Labels: A1-insubstantial, R0-silent, T10-tests

#2103 polkadot: parachains: Fix v9 host configuration migration
  polkadot/runtime/parachains/src/configuration/migration/v9.rs
Labels: A1-insubstantial, R0-silent

#1998 1953 defensive testing extrinsic
  Cargo.lock
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/Cargo.toml
  polkadot/runtime/westend/src/lib.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/root-testing/src/lib.rs
  substrate/frame/support/src/traits/misc.rs
  substrate/frame/utility/src/tests.rs
Labels: T2-pallets
