Repository paritytech/polkadot-sdk, pull requests merged in 2023-08, with the labels that each got.

#1150 fix [workspace.package] repository
  Cargo.toml
Labels: A1-insubstantial, B0-silent, C1-low, I6-documentation

#1169 CI pr-custom-review
  .github/workflows/pr-custom-review.yml
Labels: A1-insubstantial, B0-silent

#1203 PRCR - Reduced required reviews for srlabs
  .github/pr-custom-review.yml
Labels: R0-silent

#1198 ci: fix worker binaries could not be found
  .gitlab/pipeline/build.yml
  docker/malus_injected.Dockerfile
  docker/polkadot_injected_debug.Dockerfile
  docker/polkadot_injected_release.Dockerfile
  polkadot/Cargo.toml
Labels: R0-silent

#1204 Upgrade libp2p-identity to 0.1.3
  substrate/client/cli/Cargo.toml
  substrate/client/consensus/common/Cargo.toml
  substrate/client/network/bitswap/Cargo.toml
  substrate/client/network/common/Cargo.toml
  substrate/client/network/light/Cargo.toml
Labels: R0-silent

#1208 [ci] Fix check-licenses
  .github/workflows/check-D-labels.yml
  .github/workflows/check-licenses.yml
Labels: R0-silent

#1218 polkadot: less flaky dispute slashing test
  polkadot/zombienet_tests/functional/0004-parachains-disputes-past-session.toml
  polkadot/zombienet_tests/functional/0004-parachains-disputes-past-session.zndsl
Labels: R0-silent, T12-tests

#1217 deps: replace `lru` with `schnellru`
  Cargo.lock
  cumulus/client/consensus/aura/Cargo.toml
  cumulus/client/consensus/aura/src/equivocation_import_queue.rs
  cumulus/client/relay-chain-minimal-node/Cargo.toml
  cumulus/client/relay-chain-minimal-node/src/collator_overseer.rs
  cumulus/client/relay-chain-rpc-interface/Cargo.toml
  cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs
  polkadot/node/core/approval-voting/Cargo.toml
  polkadot/node/core/approval-voting/src/import.rs
  polkadot/node/core/approval-voting/src/lib.rs
  polkadot/node/core/dispute-coordinator/Cargo.toml
  polkadot/node/core/dispute-coordinator/src/lib.rs
  polkadot/node/core/dispute-coordinator/src/scraping/mod.rs
  polkadot/node/core/runtime-api/Cargo.toml
  polkadot/node/core/runtime-api/src/cache.rs
  polkadot/node/network/availability-distribution/Cargo.toml
  polkadot/node/network/availability-distribution/src/requester/session_cache.rs
  polkadot/node/network/availability-recovery/Cargo.toml
  polkadot/node/network/availability-recovery/src/lib.rs
  polkadot/node/network/dispute-distribution/Cargo.toml
  polkadot/node/network/dispute-distribution/src/lib.rs
  polkadot/node/network/dispute-distribution/src/receiver/mod.rs
  polkadot/node/overseer/Cargo.toml
  polkadot/node/overseer/src/dummy.rs
  polkadot/node/overseer/src/lib.rs
  polkadot/node/primitives/src/lib.rs
  polkadot/node/service/Cargo.toml
  polkadot/node/service/src/overseer.rs
  polkadot/node/subsystem-util/Cargo.toml
  polkadot/node/subsystem-util/src/runtime/mod.rs
  polkadot/roadmap/implementers-guide/src/node/availability/availability-recovery.md
  polkadot/roadmap/implementers-guide/src/node/disputes/dispute-coordinator.md
Labels: R0-silent, T0-node

#1201 [ci] Add missing components to CI
  .gitlab-ci.yml
  .gitlab/pipeline/build.yml
  .gitlab/pipeline/check.yml
  .gitlab/pipeline/test.yml
Labels: A1-insubstantial

#1182 update polkadot, substrate, cumulus readme
  cumulus/README.md
  polkadot/README.md
  substrate/README.md
Labels: T13-documentation

#1244 [ci] Add DAG
  .gitlab-ci.yml
  .gitlab/pipeline/build.yml
  .gitlab/pipeline/check.yml
  .gitlab/pipeline/test.yml
Labels: R0-silent

#1231 bump `zombienet` to latest version
  .gitlab-ci.yml
  .gitlab/pipeline/zombienet/cumulus.yml
  .gitlab/pipeline/zombienet/polkadot.yml
  .gitlab/pipeline/zombienet/substrate.yml
Labels: A1-insubstantial, R0-silent, T12-tests

#1166 Cleanup some files
  .gitignore
  .rustfmt.toml
  cumulus/.cargo/config.toml
  cumulus/.gitignore
  cumulus/.rustfmt.toml
  polkadot/.cargo/config.toml
  polkadot/.gitignore
  polkadot/rustfmt.toml
  substrate/.cargo/config.toml
  substrate/.git-blame-ignore-revs
  substrate/.gitignore
  substrate/rustfmt.toml
Labels: A1-insubstantial, R0-silent

#1239 PRCR - temporary disabled Audit rule
  .github/pr-custom-review.yml
Labels: R0-silent

#1206 chainSpec: Stabilize chainSpec methods to V1
  substrate/client/rpc-spec-v2/src/chain_spec/api.rs
  substrate/client/rpc-spec-v2/src/chain_spec/chain_spec.rs
  substrate/client/rpc-spec-v2/src/chain_spec/tests.rs
Labels: A0-needs_burnin, T3-RPC_API, D0-easy

#1221 Relax genesis config to not require `Default` impl
  substrate/frame/support/src/genesis_builder_helper.rs
  substrate/frame/support/src/traits/hooks.rs
Labels: T1-FRAME

#1266 Fix `test-rustdoc`
  polkadot/core-primitives/src/lib.rs
  polkadot/node/core/parachains-inherent/src/lib.rs
  polkadot/node/core/pvf/common/src/executor_intf.rs
  polkadot/node/network/bridge/src/rx/mod.rs
  polkadot/node/network/bridge/src/tx/mod.rs
  polkadot/node/network/protocol/src/authority_discovery.rs
  polkadot/node/network/protocol/src/peer_set.rs
  polkadot/node/primitives/src/disputes/mod.rs
  polkadot/node/primitives/src/lib.rs
  polkadot/node/service/src/benchmarking.rs
  polkadot/node/service/src/overseer.rs
  polkadot/node/test/client/src/block_builder.rs
  polkadot/parachain/src/lib.rs
  polkadot/primitives/src/v5/mod.rs
  polkadot/runtime/common/src/assigned_slots/migration.rs
  polkadot/runtime/common/src/elections.rs
  polkadot/runtime/common/src/lib.rs
  polkadot/runtime/common/src/purchase.rs
  polkadot/runtime/parachains/src/assigner_on_demand/mod.rs
  polkadot/runtime/parachains/src/configuration.rs
  polkadot/runtime/parachains/src/dmp.rs
  polkadot/runtime/parachains/src/hrmp.rs
  polkadot/runtime/parachains/src/inclusion/mod.rs
  polkadot/runtime/parachains/src/lib.rs
  polkadot/runtime/parachains/src/paras_inherent/misc.rs
  polkadot/runtime/parachains/src/runtime_api_impl/v5.rs
  polkadot/utils/staking-miner/src/opts.rs
  polkadot/xcm/xcm-builder/src/pay.rs
  polkadot/xcm/xcm-builder/src/process_xcm_message.rs
  substrate/frame/support/procedural/src/pallet/expand/storage.rs
Labels: R0-silent

#1240 Set test crates to nopublish
  cumulus/bridges/primitives/test-utils/Cargo.toml
  cumulus/parachain-template/node/Cargo.toml
  cumulus/parachains/integration-tests/emulated/assets/asset-hub-kusama/Cargo.toml
  cumulus/parachains/integration-tests/emulated/assets/asset-hub-polkadot/Cargo.toml
  cumulus/parachains/integration-tests/emulated/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/bridges/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/collectives/collectives-polkadot/Cargo.toml
  cumulus/parachains/integration-tests/emulated/common/Cargo.toml
  cumulus/parachains/runtimes/assets/test-utils/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/test-utils/Cargo.toml
  cumulus/parachains/runtimes/test-utils/Cargo.toml
  cumulus/parachains/runtimes/testing/penpal/Cargo.toml
  cumulus/parachains/runtimes/testing/rococo-parachain/Cargo.toml
  cumulus/test/client/Cargo.toml
  cumulus/test/relay-sproof-builder/Cargo.toml
  cumulus/test/relay-validation-worker-provider/Cargo.toml
  cumulus/test/runtime/Cargo.toml
  cumulus/test/service/Cargo.toml
  cumulus/xcm/xcm-emulator/Cargo.toml
  polkadot/xcm/xcm-simulator/fuzzer/Cargo.toml
Labels: A1-insubstantial

#1161 pallet-scheduler: Send `CallUnavailable` event if the call isn't present
  substrate/frame/scheduler/src/lib.rs
  substrate/frame/scheduler/src/tests.rs
Labels: R0-silent, T1-FRAME

#1187 Rename `VersionedRuntimeUpgrade` to `VersionedMigration`
  polkadot/runtime/common/src/assigned_slots/migration.rs
  polkadot/xcm/pallet-xcm/Cargo.toml
  polkadot/xcm/pallet-xcm/src/migration.rs
  substrate/frame/society/Cargo.toml
  substrate/frame/society/src/migrations.rs
  substrate/frame/support/src/migrations.rs
  substrate/frame/support/src/traits/hooks.rs
  substrate/frame/support/test/tests/versioned_migration.rs
Labels: T1-FRAME

#1275 [ci] Fix buildah and reorder test-doc dag
  .gitlab-ci.yml
  .gitlab/pipeline/test.yml
Labels: R0-silent

#1289 Remove old UI test
  .gitlab/pipeline/test.yml
  substrate/frame/support/test/tests/construct_runtime_ui.rs
  substrate/frame/support/test/tests/pallet_ui/genesis_default_not_satisfied.rs
  substrate/frame/support/test/tests/pallet_ui/genesis_default_not_satisfied.stderr
Labels: A1-insubstantial, R0-silent

#1241 Rename squatted crates
  Cargo.lock
  cumulus/bridges/bin/runtime-common/Cargo.toml
  cumulus/bridges/modules/xcm-bridge-hub-router/Cargo.toml
  cumulus/pallets/dmp-queue/Cargo.toml
  cumulus/pallets/parachain-system/Cargo.toml
  cumulus/pallets/xcm/Cargo.toml
  cumulus/pallets/xcmp-queue/Cargo.toml
  cumulus/parachain-template/node/Cargo.toml
  cumulus/parachain-template/runtime/Cargo.toml
  cumulus/parachains/common/Cargo.toml
  cumulus/parachains/integration-tests/emulated/assets/asset-hub-kusama/Cargo.toml
  cumulus/parachains/integration-tests/emulated/assets/asset-hub-polkadot/Cargo.toml
  cumulus/parachains/integration-tests/emulated/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/bridges/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/collectives/collectives-polkadot/Cargo.toml
  cumulus/parachains/integration-tests/emulated/common/Cargo.toml
  cumulus/parachains/pallets/ping/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-kusama/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-polkadot/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/common/Cargo.toml
  cumulus/parachains/runtimes/assets/test-utils/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-kusama/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-polkadot/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/test-utils/Cargo.toml
  cumulus/parachains/runtimes/collectives/collectives-polkadot/Cargo.toml
  cumulus/parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  cumulus/parachains/runtimes/glutton/glutton-kusama/Cargo.toml
  cumulus/parachains/runtimes/starters/shell/Cargo.toml
  cumulus/parachains/runtimes/test-utils/Cargo.toml
  cumulus/parachains/runtimes/testing/penpal/Cargo.toml
  cumulus/parachains/runtimes/testing/rococo-parachain/Cargo.toml
  cumulus/polkadot-parachain/Cargo.toml
  cumulus/primitives/core/Cargo.toml
  cumulus/primitives/utility/Cargo.toml
  cumulus/xcm/xcm-emulator/Cargo.toml
  polkadot/node/service/Cargo.toml
  polkadot/node/test/performance-test/Cargo.toml
  polkadot/runtime/common/Cargo.toml
  polkadot/runtime/kusama/Cargo.toml
  polkadot/runtime/parachains/Cargo.toml
  polkadot/runtime/polkadot/Cargo.toml
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/test-runtime/Cargo.toml
  polkadot/runtime/westend/Cargo.toml
  polkadot/utils/generate-bags/Cargo.toml
  polkadot/utils/remote-ext-tests/bags-list/Cargo.toml
  polkadot/utils/staking-miner/Cargo.toml
  polkadot/xcm/Cargo.toml
  polkadot/xcm/pallet-xcm-benchmarks/Cargo.toml
  polkadot/xcm/pallet-xcm/Cargo.toml
  polkadot/xcm/xcm-builder/Cargo.toml
  polkadot/xcm/xcm-builder/tests/mock/mod.rs
  polkadot/xcm/xcm-executor/Cargo.toml
  polkadot/xcm/xcm-executor/integration-tests/Cargo.toml
  polkadot/xcm/xcm-simulator/Cargo.toml
  polkadot/xcm/xcm-simulator/example/Cargo.toml
  polkadot/xcm/xcm-simulator/fuzzer/Cargo.toml
Labels: T10-polkadot, T11-cumulus

#1171 Symlink chain-specs json files to crate where they are used
  cumulus/polkadot-parachain/chain-specs/asset-hub-kusama.json
  cumulus/polkadot-parachain/chain-specs/asset-hub-polkadot.json
  cumulus/polkadot-parachain/chain-specs/asset-hub-westend.json
  cumulus/polkadot-parachain/chain-specs/bridge-hub-kusama.json
  cumulus/polkadot-parachain/chain-specs/bridge-hub-polkadot.json
  cumulus/polkadot-parachain/chain-specs/bridge-hub-rococo.json
  cumulus/polkadot-parachain/chain-specs/bridge-hub-westend.json
  cumulus/polkadot-parachain/chain-specs/bridge-hub-wococo.json
  cumulus/polkadot-parachain/chain-specs/collectives-polkadot.json
  cumulus/polkadot-parachain/chain-specs/collectives-westend.json
  cumulus/polkadot-parachain/chain-specs/contracts-rococo.json
  cumulus/polkadot-parachain/chain-specs/tick.json
  cumulus/polkadot-parachain/chain-specs/track.json
  cumulus/polkadot-parachain/chain-specs/trick.json
  cumulus/polkadot-parachain/src/chain_spec/bridge_hubs.rs
  cumulus/polkadot-parachain/src/command.rs
Labels: T11-cumulus

#1307 fix chain-spec path for substrate tests
  cumulus/zombienet/tests/0007-full_node_warp_sync.toml
  substrate/zombienet/0001-basic-warp-sync/test-warp-sync.toml
  substrate/zombienet/0002-validators-warp-sync/test-validators-warp-sync.toml
  substrate/zombienet/0003-block-building-warp-sync/test-block-building-warp-sync.toml
Labels: A1-insubstantial, R0-silent, T12-tests

#1317 Fix typo in statement-store/README.md
  substrate/primitives/statement-store/README.md
Labels: A1-insubstantial, R0-silent

#1316 Fix CI
  .gitlab/pipeline/build.yml
  .gitlab/pipeline/check.yml
  .gitlab/test_deterministic_wasm.sh
Labels: R0-silent

#1212 Put `GetWeight` where it belongs
  polkadot/xcm/src/lib.rs
  polkadot/xcm/src/v2/mod.rs
  polkadot/xcm/src/v2/traits.rs
  polkadot/xcm/src/v3/mod.rs
  polkadot/xcm/xcm-builder/src/weight.rs
Labels: T6-XCM

#1299 substrate: peer_store: log warn on disconnecting because of reputation
  substrate/client/network/src/peer_store.rs
Labels: A1-insubstantial, T8-parachains_engineering

#1207 PVF: Take back a stolen right
  polkadot/node/core/pvf/Cargo.toml
  polkadot/node/core/pvf/common/src/lib.rs
  polkadot/node/core/pvf/common/src/worker/mod.rs
Labels: T0-node, T10-polkadot

#1314 [ci] add more jobs for pipeline cancel, cleanup
  .gitlab-ci.yml
  cumulus/scripts/ci/changelog/.gitignore
  cumulus/scripts/ci/changelog/Gemfile
  cumulus/scripts/ci/changelog/Gemfile.lock
  cumulus/scripts/ci/changelog/README.md
  cumulus/scripts/ci/changelog/bin/changelog
  cumulus/scripts/ci/changelog/digests/.gitignore
  cumulus/scripts/ci/changelog/digests/.gitkeep
  cumulus/scripts/ci/changelog/lib/changelog.rb
  cumulus/scripts/ci/changelog/templates/change.md.tera
  cumulus/scripts/ci/changelog/templates/changes.md.tera
  cumulus/scripts/ci/changelog/templates/changes_api.md.tera
  cumulus/scripts/ci/changelog/templates/changes_client.md.tera
  cumulus/scripts/ci/changelog/templates/changes_misc.md.tera
  cumulus/scripts/ci/changelog/templates/changes_runtime.md.tera
  cumulus/scripts/ci/changelog/templates/compiler.md.tera
  cumulus/scripts/ci/changelog/templates/debug.md.tera
  cumulus/scripts/ci/changelog/templates/docker_image.md.tera
  cumulus/scripts/ci/changelog/templates/global_priority.md.tera
  cumulus/scripts/ci/changelog/templates/high_priority.md.tera
  cumulus/scripts/ci/changelog/templates/host_functions.md.tera
  cumulus/scripts/ci/changelog/templates/migrations-db.md.tera
  cumulus/scripts/ci/changelog/templates/migrations-runtime.md.tera
  cumulus/scripts/ci/changelog/templates/pre_release.md.tera
  cumulus/scripts/ci/changelog/templates/runtime.md.tera
  cumulus/scripts/ci/changelog/templates/runtimes.md.tera
  cumulus/scripts/ci/changelog/templates/template.md.tera
  cumulus/scripts/ci/changelog/test/test_basic.rb
  cumulus/scripts/ci/common/lib.sh
  cumulus/scripts/ci/create-benchmark-pr.sh
  cumulus/scripts/ci/github/check-rel-br
  cumulus/scripts/ci/github/check_labels.sh
  cumulus/scripts/ci/github/extrinsic-ordering-filter.sh
  cumulus/scripts/ci/github/runtime-version.rb
  cumulus/scripts/ci/gitlab/pipeline/benchmarks.yml
  cumulus/scripts/ci/gitlab/pipeline/build.yml
  cumulus/scripts/ci/gitlab/pipeline/integration_tests.yml
  cumulus/scripts/ci/gitlab/pipeline/publish.yml
  cumulus/scripts/ci/gitlab/pipeline/short-benchmarks.yml
  cumulus/scripts/ci/gitlab/pipeline/test.yml
  cumulus/scripts/ci/gitlab/pipeline/zombienet.yml
  cumulus/scripts/ci/gitlab/prettier.sh
  substrate/scripts/ci/common/lib.sh
  substrate/scripts/ci/github/check_labels.sh
  substrate/scripts/ci/github/generate_changelog.sh
  substrate/scripts/ci/gitlab/check-each-crate.py
  substrate/scripts/ci/gitlab/check_runtime.sh
  substrate/scripts/ci/gitlab/check_signed.sh
  substrate/scripts/ci/gitlab/ensure-deps.sh
  substrate/scripts/ci/gitlab/pipeline/build.yml
  substrate/scripts/ci/gitlab/pipeline/check.yml
  substrate/scripts/ci/gitlab/pipeline/publish.yml
  substrate/scripts/ci/gitlab/pipeline/test.yml
  substrate/scripts/ci/gitlab/pipeline/zombienet.yml
  substrate/scripts/ci/gitlab/prettier.sh
  substrate/scripts/ci/gitlab/publish_draft_release.sh
Labels: R0-silent

#1328 Remove `disable-runtime-api` feature - Fix for `test-rustdoc` CI job
  polkadot/runtime/kusama/Cargo.toml
  polkadot/runtime/kusama/src/lib.rs
  polkadot/runtime/polkadot/Cargo.toml
  polkadot/runtime/polkadot/src/lib.rs
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/Cargo.toml
  polkadot/runtime/westend/src/lib.rs
Labels: R0-silent

#1321 Remove `substrate_test_utils::test`
  Cargo.lock
  Cargo.toml
  polkadot/node/metrics/src/tests.rs
  polkadot/node/test/service/tests/build-blocks.rs
  polkadot/node/test/service/tests/call-function.rs
  polkadot/parachain/test-parachains/adder/collator/tests/integration.rs
  polkadot/parachain/test-parachains/undying/collator/tests/integration.rs
  substrate/test-utils/Cargo.toml
  substrate/test-utils/derive/Cargo.toml
  substrate/test-utils/derive/src/lib.rs
  substrate/test-utils/src/lib.rs
  substrate/test-utils/test-crate/Cargo.toml
  substrate/test-utils/test-crate/src/main.rs
  substrate/test-utils/tests/basic.rs
  substrate/test-utils/tests/ui.rs
  substrate/test-utils/tests/ui/too-many-func-parameters.rs
  substrate/test-utils/tests/ui/too-many-func-parameters.stderr
Labels: R0-silent

#1200 backing: move the min votes threshold to the runtime
  cumulus/client/relay-chain-minimal-node/src/blockchain_rpc_client.rs
  cumulus/client/relay-chain-rpc-interface/src/rpc_client.rs
  cumulus/parachains/integration-tests/emulated/common/src/lib.rs
  polkadot/node/core/backing/src/error.rs
  polkadot/node/core/backing/src/lib.rs
  polkadot/node/core/backing/src/tests/mod.rs
  polkadot/node/core/backing/src/tests/prospective_parachains.rs
  polkadot/node/core/runtime-api/src/cache.rs
  polkadot/node/core/runtime-api/src/lib.rs
  polkadot/node/core/runtime-api/src/tests.rs
  polkadot/node/network/statement-distribution/Cargo.toml
  polkadot/node/network/statement-distribution/src/vstaging/grid.rs
  polkadot/node/network/statement-distribution/src/vstaging/groups.rs
  polkadot/node/network/statement-distribution/src/vstaging/mod.rs
  polkadot/node/network/statement-distribution/src/vstaging/tests/mod.rs
  polkadot/node/primitives/src/lib.rs
  polkadot/node/subsystem-types/src/messages.rs
  polkadot/node/subsystem-types/src/runtime_client.rs
  polkadot/node/subsystem-util/src/runtime/error.rs
  polkadot/node/subsystem-util/src/runtime/mod.rs
  polkadot/primitives/src/lib.rs
  polkadot/primitives/src/runtime_api.rs
  polkadot/primitives/src/v5/mod.rs
  polkadot/runtime/kusama/src/lib.rs
  polkadot/runtime/parachains/src/configuration.rs
  polkadot/runtime/parachains/src/configuration/migration.rs
  polkadot/runtime/parachains/src/configuration/migration/v8.rs
  polkadot/runtime/parachains/src/configuration/migration/v9.rs
  polkadot/runtime/parachains/src/configuration/tests.rs
  polkadot/runtime/parachains/src/inclusion/mod.rs
  polkadot/runtime/parachains/src/inclusion/tests.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
  polkadot/runtime/parachains/src/runtime_api_impl/vstaging.rs
  polkadot/runtime/polkadot/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/statement-table/src/generic.rs
Labels: A0-needs_burnin, T4-runtime_API, T10-polkadot

#1249 Sassafras primitives
  Cargo.lock
  Cargo.toml
  substrate/client/keystore/src/local.rs
  substrate/primitives/consensus/sassafras/Cargo.toml
  substrate/primitives/consensus/sassafras/README.md
  substrate/primitives/consensus/sassafras/src/digests.rs
  substrate/primitives/consensus/sassafras/src/lib.rs
  substrate/primitives/consensus/sassafras/src/ticket.rs
  substrate/primitives/consensus/sassafras/src/vrf.rs
  substrate/primitives/core/src/bandersnatch.rs
  substrate/primitives/core/src/crypto.rs
  substrate/primitives/keystore/src/lib.rs
Labels: T0-node

#1315 Fix polkadot-node-core-pvf-prepare-worker build with jemalloc
  Cargo.lock
  polkadot/Cargo.toml
  polkadot/node/core/pvf/Cargo.toml
  polkadot/node/core/pvf/common/Cargo.toml
  polkadot/node/core/pvf/execute-worker/Cargo.toml
  polkadot/node/core/pvf/prepare-worker/Cargo.toml
Labels: T10-polkadot

#1320 Add environmental variable to track decoded instructions
  Cargo.lock
  polkadot/xcm/Cargo.toml
  polkadot/xcm/src/lib.rs
  polkadot/xcm/src/v2/multilocation.rs
  polkadot/xcm/src/v2/traits.rs
  polkadot/xcm/src/v3/junctions.rs
  polkadot/xcm/src/v3/mod.rs
  polkadot/xcm/src/v3/multilocation.rs
  polkadot/xcm/src/v3/traits.rs
  polkadot/xcm/xcm-builder/src/currency_adapter.rs
  polkadot/xcm/xcm-builder/src/matcher.rs
  polkadot/xcm/xcm-builder/src/matches_token.rs
  polkadot/xcm/xcm-executor/src/assets.rs
  polkadot/xcm/xcm-executor/src/traits/conversion.rs
Labels: T6-XCM
