Repository paritytech/polkadot-sdk, pull requests merged in 2024-03, with the labels that each got.

#3508 [Backport] Node version and spec_version bumps and ordering of the prdoc files from 1.8.0
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot/node/primitives/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/1.8.0/pr_1660.prdoc
  prdoc/1.8.0/pr_2061.prdoc
  prdoc/1.8.0/pr_2290.prdoc
  prdoc/1.8.0/pr_2903.prdoc
  prdoc/1.8.0/pr_2949-async-backing-on-all-testnet-system-chains.prdoc
  prdoc/1.8.0/pr_3007.prdoc
  prdoc/1.8.0/pr_3052.prdoc
  prdoc/1.8.0/pr_3060.prdoc
  prdoc/1.8.0/pr_3079.prdoc
  prdoc/1.8.0/pr_3154.prdoc
  prdoc/1.8.0/pr_3160.prdoc
  prdoc/1.8.0/pr_3166.prdoc
  prdoc/1.8.0/pr_3184.prdoc
  prdoc/1.8.0/pr_3212.prdoc
  prdoc/1.8.0/pr_3225.prdoc
  prdoc/1.8.0/pr_3230.prdoc
  prdoc/1.8.0/pr_3232.prdoc
  prdoc/1.8.0/pr_3243.prdoc
  prdoc/1.8.0/pr_3244.prdoc
  prdoc/1.8.0/pr_3272.prdoc
  prdoc/1.8.0/pr_3301.prdoc
  prdoc/1.8.0/pr_3308.prdoc
  prdoc/1.8.0/pr_3319.prdoc
  prdoc/1.8.0/pr_3325.prdoc
  prdoc/1.8.0/pr_3358.prdoc
  prdoc/1.8.0/pr_3361.prdoc
  prdoc/1.8.0/pr_3364.prdoc
  prdoc/1.8.0/pr_3370.prdoc
  prdoc/1.8.0/pr_3384.prdoc
  prdoc/1.8.0/pr_3395.prdoc
  prdoc/1.8.0/pr_3415.prdoc
  prdoc/1.8.0/pr_3435.prdoc
  prdoc/1.8.0/pr_3477.prdoc
Labels: R0-silent, A3-backport, D0-easy

#3539 Add `claim_assets` extrinsic to `pallet-xcm` (#3403)
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/pallet_xcm.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/pallet_xcm.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/pallet_xcm.rs
  polkadot/xcm/pallet-xcm/src/benchmarking.rs
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/pallet-xcm/src/tests/mod.rs
  polkadot/xcm/src/lib.rs
  prdoc/pr_3403.prdoc
Labels: R0-silent

#3523 Fix crash of synced parachain node run with `--sync=warp`
  prdoc/pr_3523.prdoc
  substrate/client/network/sync/src/engine.rs
  substrate/client/network/sync/src/strategy.rs
Labels: T0-node

#3517 make SelfParaId a metadata constant
  cumulus/pallets/parachain-system/src/lib.rs
Labels: R0-silent

#3545 Backport of #3340 - Fix `DepositReserveAsset`
  polkadot/xcm/xcm-executor/src/lib.rs
Labels: R0-silent, T6-XCM, I2-bug

#3233 provisioner: allow multiple cores assigned to the same para
  Cargo.lock
  polkadot/node/core/prospective-parachains/Cargo.toml
  polkadot/node/core/prospective-parachains/src/fragment_tree.rs
  polkadot/node/core/prospective-parachains/src/lib.rs
  polkadot/node/core/prospective-parachains/src/tests.rs
  polkadot/node/core/provisioner/Cargo.toml
  polkadot/node/core/provisioner/src/error.rs
  polkadot/node/core/provisioner/src/lib.rs
  polkadot/node/core/provisioner/src/tests.rs
  polkadot/node/subsystem-types/src/messages.rs
  prdoc/pr_3233.prdoc
Labels: T0-node, T8-polkadot

#3505 Remove `as frame_system::DefaultConfig` from the required syntax in `derive_impl`
  prdoc/pr_3505.prdoc
  substrate/frame/examples/default-config/src/lib.rs
  substrate/frame/support/procedural/src/derive_impl.rs
  substrate/frame/support/procedural/src/lib.rs
Labels: T1-FRAME

#2638 Finish documenting `#[pallet::xxx]` macros
  Cargo.lock
  docs/sdk/src/guides/your_first_pallet/mod.rs
  substrate/frame/support/Cargo.toml
  substrate/frame/support/procedural/src/lib.rs
  substrate/frame/support/src/lib.rs
Labels: R0-silent, T11-documentation

#3563 Contracts: Fix typo
  substrate/frame/contracts/uapi/src/host.rs
  substrate/frame/contracts/uapi/src/host/riscv32.rs
  substrate/frame/contracts/uapi/src/host/wasm32.rs
Labels: R0-silent

#3534 Remove useless Result import
  substrate/primitives/consensus/babe/src/inherents.rs
Labels: R0-silent, T0-node

#3566 Contracts call extract_from_slice in macro
  substrate/frame/contracts/uapi/src/host/wasm32.rs
Labels: R0-silent

#3504 rpc server: add prometheus label `is_rate_limited`
  Cargo.lock
  prdoc/pr_3504.prdoc
  substrate/client/rpc-servers/Cargo.toml
  substrate/client/rpc-servers/src/lib.rs
  substrate/client/rpc-servers/src/middleware/metrics.rs
  substrate/client/rpc-servers/src/middleware/mod.rs
  substrate/client/rpc-servers/src/middleware/rate_limit.rs
Labels: T0-node

#3559 [Documentation] Delete unused outdated `polkadot/testing.md`
  polkadot/doc/testing.md
Labels: R0-silent

#3456 Removed `pallet::getter` usage from `pallet-collective`
  cumulus/parachains/runtimes/collectives/collectives-westend/src/impls.rs
  prdoc/pr_3456.prdoc
  substrate/bin/node/runtime/src/impls.rs
  substrate/frame/alliance/src/mock.rs
  substrate/frame/alliance/src/tests.rs
  substrate/frame/collective/src/benchmarking.rs
  substrate/frame/collective/src/lib.rs
  substrate/frame/collective/src/tests.rs
Labels: T2-pallets

#3575 Increase 0002-validators-warp-sync timeout
  substrate/zombienet/0002-validators-warp-sync/test-validators-warp-sync.zndsl
Labels: R0-silent, T10-tests, T15-bridges

#2393 [FRAME] Use 'ready' pages in XCMP suspend logic
  cumulus/pallets/xcmp-queue/src/lib.rs
  cumulus/pallets/xcmp-queue/src/mock.rs
  prdoc/pr_2393.prdoc
  substrate/frame/message-queue/src/integration_test.rs
  substrate/frame/message-queue/src/lib.rs
  substrate/frame/message-queue/src/mock.rs
  substrate/frame/message-queue/src/tests.rs
  substrate/frame/support/src/traits/messages.rs
Labels: T2-pallets

#3377 Permissioned contract deployment
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/contracts.rs
  prdoc/pr_3377.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/contracts/mock-network/src/parachain/contracts_config.rs
  substrate/frame/contracts/src/lib.rs
  substrate/frame/contracts/src/tests.rs
Labels: T7-smart_contracts

#2934 Contracts: Charge min amount when processing deletion queue
  substrate/frame/contracts/src/storage.rs
Labels: R0-silent

#3570 Fixes snowbridge integration test
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/chains/parachains/testing/penpal/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  substrate/frame/support/Cargo.toml
Labels: R0-silent

#3586 FIX: Make `sc-network-sync` types Public
  substrate/client/network/sync/src/lib.rs
Labels: R0-silent, T0-node

#3595 sc-manual-seal: don't spawn threads in tests
  substrate/client/consensus/manual-seal/src/lib.rs
Labels: R0-silent, T0-node

#3445 chainHead/follow: Provide multiple block hashes to the initialized event
  substrate/client/rpc-spec-v2/src/chain_head/chain_head_follow.rs
  substrate/client/rpc-spec-v2/src/chain_head/event.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement, D1-medium

#3540 Contracts upload with Determinism::Enforced when possible
  prdoc/pr_3540.prdoc
  substrate/frame/contracts/src/benchmarking/code.rs
  substrate/frame/contracts/src/benchmarking/mod.rs
  substrate/frame/contracts/src/lib.rs
  substrate/frame/contracts/src/tests.rs
  substrate/frame/contracts/src/wasm/mod.rs
  substrate/frame/contracts/src/wasm/prepare.rs
  substrate/frame/contracts/src/weights.rs
Labels: T7-smart_contracts

#3564 Make `penpal-runtime`'s `TrustedReserves` more connfigurable
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/chains/parachains/testing/penpal/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  cumulus/parachains/runtimes/testing/penpal/Cargo.toml
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
Labels: R0-silent, T10-tests

#3573 ParaInherent create: update `apply_weight_limit` wrt elastic scaling
  polkadot/runtime/parachains/src/paras_inherent/mod.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
Labels: R0-silent, T8-polkadot

#3453 `nomination-pools`: add permissionless condition to `chill`
  prdoc/pr_3453.prdoc
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/nomination-pools/src/tests.rs
  substrate/frame/nomination-pools/src/weights.rs
  substrate/frame/nomination-pools/test-staking/src/lib.rs
Labels: T2-pallets

#3579 move substrate-bip39 into polkadot-sdk
  Cargo.lock
  Cargo.toml
  polkadot/node/core/approval-voting/Cargo.toml
  polkadot/node/subsystem-bench/Cargo.toml
  substrate/primitives/core/Cargo.toml
  substrate/utils/substrate-bip39/Cargo.toml
  substrate/utils/substrate-bip39/README.md
  substrate/utils/substrate-bip39/src/lib.rs
Labels: R0-silent, T0-node

#3542 Add documentation around pallet coupling
  Cargo.lock
  docs/sdk/Cargo.toml
  docs/sdk/src/polkadot_sdk/frame_runtime.rs
  docs/sdk/src/reference_docs/frame_pallet_coupling.rs
  docs/sdk/src/reference_docs/mod.rs
  substrate/frame/support/src/lib.rs
Labels: R0-silent, T11-documentation

#3602 Disable flaky test
  substrate/client/consensus/manual-seal/src/lib.rs
Labels: R0-silent

#3511 Refactor polkadot-parachain service for more code reuse
  cumulus/polkadot-parachain/src/command.rs
  cumulus/polkadot-parachain/src/service.rs
Labels: R0-silent, T0-node

#3574 fix(pallet-benchmarking): split test functions in v2
  cumulus/pallets/collator-selection/src/benchmarking.rs
  cumulus/parachains/pallets/collective-content/src/benchmarking.rs
  polkadot/runtime/common/src/identity_migrator.rs
  polkadot/runtime/parachains/src/hrmp/benchmarking.rs
  prdoc/pr_3574.prdoc
  substrate/frame/alliance/src/benchmarking.rs
  substrate/frame/identity/src/benchmarking.rs
  substrate/frame/lottery/src/benchmarking.rs
  substrate/frame/support/procedural/src/benchmark.rs
  substrate/frame/system/benchmarking/src/extensions.rs
  substrate/frame/system/benchmarking/src/lib.rs
Labels: T12-benchmarks

#3619 Contracts Bump ApiVersion and add test
  substrate/frame/contracts/proc-macro/src/lib.rs
  substrate/frame/contracts/src/lib.rs
  substrate/frame/contracts/src/wasm/mod.rs
  substrate/frame/contracts/src/wasm/runtime.rs
Labels: R0-silent

#3544 collator-protocol: Always stay connected to validators in backing group
  polkadot/node/network/collator-protocol/src/collator_side/validators_buffer.rs
  polkadot/node/network/collator-protocol/src/validator_side/mod.rs
Labels: R0-silent

#3624 Make `penpal-runtime`'s `TrustedReserves` more connfigurable (#3564) (patch for 1.7.0)
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/chains/parachains/testing/penpal/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  cumulus/parachains/runtimes/testing/penpal/Cargo.toml
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
Labels: R0-silent

#3598 benchmark: allow range trailing comma in RangeArgs
  substrate/frame/support/procedural/src/benchmark.rs
Labels: R0-silent

#3558 Contracts: Fix terminate benchmark
  substrate/frame/contracts/src/benchmarking/mod.rs
  substrate/frame/contracts/src/storage.rs
Labels: R0-silent

#3587 fix some typos
  bridges/primitives/test-utils/src/lib.rs
  cumulus/client/parachain-inherent/src/lib.rs
  cumulus/parachains/integration-tests/emulated/common/src/impls.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/people/people-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/people/people-westend/src/xcm_config.rs
  polkadot/cli/src/cli.rs
  polkadot/node/core/dispute-coordinator/src/initialized.rs
  polkadot/node/core/pvf-checker/src/lib.rs
  polkadot/node/subsystem-bench/README.md
  polkadot/node/subsystem-bench/src/lib/availability/mod.rs
  polkadot/node/subsystem-bench/src/lib/mock/av_store.rs
  polkadot/node/subsystem-bench/src/lib/network.rs
  polkadot/primitives/src/v6/slashing.rs
  polkadot/runtime/parachains/src/paras/mod.rs
  substrate/bin/node/cli/src/cli.rs
  templates/parachain/node/src/cli.rs
  templates/solochain/node/src/cli.rs
Labels: R0-silent

#3525 core: replace secp256k with k256 in crypto::ecdsa
  Cargo.lock
  substrate/primitives/core/Cargo.toml
  substrate/primitives/core/src/ecdsa.rs
Labels: R0-silent, T0-node

#3275 Asset Conversion: doc guide to address incorrect exchange rate for non-withdrawable pool
  substrate/frame/asset-conversion/src/lib.rs
Labels: R0-silent, T2-pallets

#3625 Make penpal-runtime's TrustedReserves more connfigurable (#3564) (patch for 1.8.0)
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/chains/parachains/testing/penpal/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  cumulus/parachains/runtimes/testing/penpal/Cargo.toml
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
Labels: R0-silent

#3547 Fix release docker image GHA
  .github/scripts/common/lib.sh
  .github/workflows/release-50_publish-docker.yml
  .github/workflows/release-99_notif-published.yml
Labels: R0-silent

#3636 [pallet_broker] Fix `adapt_price` behaviour at zero
  prdoc/pr_3636.prdoc
  substrate/frame/broker/src/adapt_price.rs
Labels: T2-pallets

#3641 Remove unused FullCandidateReceipt
  polkadot/primitives/src/v6/mod.rs
  polkadot/roadmap/implementers-guide/src/types/README.md
  polkadot/roadmap/implementers-guide/src/types/candidate.md
Labels: A1-insubstantial, R0-silent

#3589 Remove getters from `im-online` pallet
  prdoc/pr_3589.prdoc
  substrate/frame/im-online/src/lib.rs
  substrate/frame/im-online/src/tests.rs
Labels: T2-pallets

#3583 subsystem-bench: adjust test config to Kusama
  polkadot/node/network/availability-distribution/tests/availability-distribution-regression-bench.rs
  polkadot/node/network/availability-recovery/tests/availability-recovery-regression-bench.rs
  polkadot/node/subsystem-bench/src/lib/configuration.rs
Labels: R0-silent, T12-benchmarks

#3532 [Deprecation] Remove the deprecated Store trait
  prdoc/pr_3532.prdoc
  substrate/frame/support/procedural/src/lib.rs
  substrate/frame/support/procedural/src/pallet/expand/mod.rs
  substrate/frame/support/procedural/src/pallet/expand/store_trait.rs
  substrate/frame/support/procedural/src/pallet/parse/mod.rs
  substrate/frame/support/procedural/src/pallet/parse/pallet_struct.rs
  substrate/frame/support/src/lib.rs
  substrate/frame/support/test/tests/pallet_ui/deprecated_store_attr.rs
  substrate/frame/support/test/tests/pallet_ui/deprecated_store_attr.stderr
  substrate/frame/support/test/tests/pallet_ui/duplicate_store_attr.rs
  substrate/frame/support/test/tests/pallet_ui/duplicate_store_attr.stderr
  substrate/frame/support/test/tests/pallet_ui/pallet_struct_invalid_attr.stderr
  substrate/frame/support/test/tests/pallet_ui/store_trait_leak_private.rs
  substrate/frame/support/test/tests/pallet_ui/store_trait_leak_private.stderr
  substrate/frame/support/test/tests/storage_transaction.rs
Labels: T1-FRAME

#3643 [Collator Selection] Fix weight refund for `set_candidacy_bond`
  cumulus/pallets/collator-selection/src/lib.rs
  prdoc/pr_3643.prdoc
Labels: T2-pallets

#3637 Adds default config for assets pallet
  substrate/frame/assets/src/lib.rs
  substrate/frame/assets/src/mock.rs
Labels: R0-silent, T1-FRAME

#3458 Add a PolkaVM-based executor
  Cargo.lock
  Cargo.toml
  polkadot/node/core/pvf/common/src/executor_interface.rs
  substrate/client/executor/Cargo.toml
  substrate/client/executor/common/Cargo.toml
  substrate/client/executor/common/src/error.rs
  substrate/client/executor/common/src/lib.rs
  substrate/client/executor/common/src/runtime_blob/runtime_blob.rs
  substrate/client/executor/common/src/wasm_runtime.rs
  substrate/client/executor/polkavm/Cargo.toml
  substrate/client/executor/polkavm/README.md
  substrate/client/executor/polkavm/src/lib.rs
  substrate/client/executor/src/wasm_runtime.rs
  substrate/client/executor/wasmtime/src/instance_wrapper.rs
  substrate/client/executor/wasmtime/src/runtime.rs
  substrate/primitives/io/Cargo.toml
  substrate/primitives/io/src/global_alloc_riscv.rs
  substrate/primitives/io/src/global_alloc_wasm.rs
  substrate/primitives/io/src/lib.rs
  substrate/utils/wasm-builder/src/wasm_project.rs
Labels: R0-silent

#3653 Add api-name in `cannot query the runtime API version` warning
  polkadot/node/core/runtime-api/src/lib.rs
Labels: R0-silent

#2044 Support for `keyring` in runtimes
  .gitlab/pipeline/check.yml
  Cargo.lock
  substrate/client/cli/Cargo.toml
  substrate/client/cli/src/commands/generate.rs
  substrate/primitives/application-crypto/check-features-variants.sh
  substrate/primitives/application-crypto/src/bls377.rs
  substrate/primitives/application-crypto/src/ecdsa.rs
  substrate/primitives/application-crypto/src/ecdsa_bls377.rs
  substrate/primitives/application-crypto/src/ed25519.rs
  substrate/primitives/application-crypto/src/lib.rs
  substrate/primitives/application-crypto/src/sr25519.rs
  substrate/primitives/application-crypto/src/traits.rs
  substrate/primitives/core/Cargo.toml
  substrate/primitives/core/check-features-variants.sh
  substrate/primitives/core/src/address_uri.rs
  substrate/primitives/core/src/bandersnatch.rs
  substrate/primitives/core/src/bls.rs
  substrate/primitives/core/src/crypto.rs
  substrate/primitives/core/src/ecdsa.rs
  substrate/primitives/core/src/ed25519.rs
  substrate/primitives/core/src/lib.rs
  substrate/primitives/core/src/paired_crypto.rs
  substrate/primitives/core/src/sr25519.rs
  substrate/primitives/keyring/Cargo.toml
  substrate/primitives/keyring/check-features-variants.sh
  substrate/primitives/keyring/src/bandersnatch.rs
  substrate/primitives/keyring/src/ed25519.rs
  substrate/primitives/keyring/src/lib.rs
  substrate/primitives/keyring/src/sr25519.rs
  substrate/test-utils/runtime/Cargo.toml
Labels: R0-silent, T0-node

#1378 Construct Runtime v2
  prdoc/pr_1378.prdoc
  substrate/bin/node/runtime/Cargo.toml
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/support/Cargo.toml
  substrate/frame/support/procedural/Cargo.toml
  substrate/frame/support/procedural/src/construct_runtime/mod.rs
  substrate/frame/support/procedural/src/lib.rs
  substrate/frame/support/procedural/src/pallet/expand/tt_default_parts.rs
  substrate/frame/support/procedural/src/pallet/parse/helper.rs
  substrate/frame/support/procedural/src/runtime/expand/mod.rs
  substrate/frame/support/procedural/src/runtime/mod.rs
  substrate/frame/support/procedural/src/runtime/parse/helper.rs
  substrate/frame/support/procedural/src/runtime/parse/mod.rs
  substrate/frame/support/procedural/src/runtime/parse/pallet.rs
  substrate/frame/support/procedural/src/runtime/parse/pallet_decl.rs
  substrate/frame/support/procedural/src/runtime/parse/runtime_struct.rs
  substrate/frame/support/procedural/src/runtime/parse/runtime_types.rs
  substrate/frame/support/src/lib.rs
  substrate/frame/support/test/Cargo.toml
  substrate/frame/support/test/tests/runtime.rs
  substrate/frame/support/test/tests/runtime_legacy_ordering.rs
  substrate/frame/support/test/tests/runtime_ui.rs
  substrate/frame/support/test/tests/runtime_ui/can_only_be_attached_to_mod.rs
  substrate/frame/support/test/tests/runtime_ui/can_only_be_attached_to_mod.stderr
  substrate/frame/support/test/tests/runtime_ui/conflicting_pallet_index.rs
  substrate/frame/support/test/tests/runtime_ui/conflicting_pallet_index.stderr
  substrate/frame/support/test/tests/runtime_ui/conflicting_pallet_name.rs
  substrate/frame/support/test/tests/runtime_ui/conflicting_pallet_name.stderr
  substrate/frame/support/test/tests/runtime_ui/invalid_attribute.rs
  substrate/frame/support/test/tests/runtime_ui/invalid_attribute.stderr
  substrate/frame/support/test/tests/runtime_ui/invalid_pallet_index.rs
  substrate/frame/support/test/tests/runtime_ui/invalid_pallet_index.stderr
  substrate/frame/support/test/tests/runtime_ui/invalid_runtime_type_derive.rs
  substrate/frame/support/test/tests/runtime_ui/invalid_runtime_type_derive.stderr
  substrate/frame/support/test/tests/runtime_ui/missing_runtime.rs
  substrate/frame/support/test/tests/runtime_ui/missing_runtime.stderr
  substrate/frame/support/test/tests/runtime_ui/missing_runtime_types_derive.rs
  substrate/frame/support/test/tests/runtime_ui/missing_runtime_types_derive.stderr
  substrate/frame/support/test/tests/runtime_ui/missing_system_pallet.rs
  substrate/frame/support/test/tests/runtime_ui/missing_system_pallet.stderr
  substrate/frame/support/test/tests/runtime_ui/pass/basic.rs
  substrate/frame/support/test/tests/runtime_ui/runtime_struct.rs
  substrate/frame/support/test/tests/runtime_ui/runtime_struct.stderr
  templates/solochain/runtime/Cargo.toml
  templates/solochain/runtime/src/lib.rs
Labels: T1-FRAME

#3668 authority-discovery: Add log for debugging DHT authority records
  substrate/client/authority-discovery/src/worker.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement, D0-easy

#3677 Always print connectivity report
  polkadot/node/network/gossip-support/src/lib.rs
Labels: R0-silent

#3527 Add subsystems regression tests to CI
  .gitlab/pipeline/test.yml
  polkadot/node/network/availability-distribution/tests/availability-distribution-regression-bench.rs
  polkadot/node/network/availability-recovery/tests/availability-recovery-regression-bench.rs
  polkadot/node/subsystem-bench/src/lib/lib.rs
  polkadot/node/subsystem-bench/src/lib/usage.rs
  polkadot/node/subsystem-bench/src/lib/utils.rs
Labels: R0-silent, T12-benchmarks

#3680 Increase timeout for assertions
  bridges/testing/tests/0001-asset-transfer/roc-reaches-westend.zndsl
  bridges/testing/tests/0001-asset-transfer/wnd-reaches-rococo.zndsl
  bridges/testing/tests/0001-asset-transfer/wroc-reaches-rococo.zndsl
  bridges/testing/tests/0001-asset-transfer/wwnd-reaches-westend.zndsl
Labels: R0-silent, T10-tests

#3349 DescribeAllTerminal for HashedDescription
  polkadot/runtime/rococo/src/xcm_config.rs
  polkadot/runtime/westend/src/xcm_config.rs
Labels: R0-silent

#3639 Staking ledger bonding fixes
  prdoc/pr_3639.prdoc
  substrate/frame/staking/src/ledger.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/tests.rs
Labels: T8-polkadot, T10-tests

#3674 fix(paseo-spec): New Paseo Bootnodes
  polkadot/node/service/chain-specs/paseo.json
Labels: R0-silent

#3690 Add elastic scaling support in ParaInherent BenchBuilder
  polkadot/runtime/parachains/src/builder.rs
  polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
Labels: R0-silent, T10-tests, T12-benchmarks

#3715 Contracts use polkavm workspace deps
  Cargo.lock
  substrate/frame/contracts/fixtures/Cargo.toml
  substrate/frame/contracts/fixtures/build.rs
  substrate/frame/contracts/fixtures/build/Cargo.toml
  substrate/frame/contracts/uapi/Cargo.toml
Labels: R0-silent

#3302 collator protocol changes for elastic scaling (validator side)
  polkadot/node/collation-generation/src/lib.rs
  polkadot/node/collation-generation/src/tests.rs
  polkadot/node/core/prospective-parachains/src/lib.rs
  polkadot/node/core/prospective-parachains/src/tests.rs
  polkadot/node/network/collator-protocol/src/collator_side/collation.rs
  polkadot/node/network/collator-protocol/src/collator_side/mod.rs
  polkadot/node/network/collator-protocol/src/collator_side/tests/mod.rs
  polkadot/node/network/collator-protocol/src/collator_side/tests/prospective_parachains.rs
  polkadot/node/network/collator-protocol/src/error.rs
  polkadot/node/network/collator-protocol/src/validator_side/collation.rs
  polkadot/node/network/collator-protocol/src/validator_side/mod.rs
  polkadot/node/network/collator-protocol/src/validator_side/tests/prospective_parachains.rs
  polkadot/node/network/protocol/src/request_response/mod.rs
  polkadot/node/network/protocol/src/request_response/v1.rs
  polkadot/node/subsystem-types/src/messages.rs
  prdoc/pr_3302.prdoc
Labels: T8-polkadot, T9-cumulus

#3707 Crowdload burn remaining funds
  polkadot/runtime/common/src/crowdloan/mod.rs
Labels: R0-silent

#3654 Eliminate `experimental` feature
  cumulus/pallets/collator-selection/Cargo.toml
  cumulus/pallets/collator-selection/src/mock.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/Cargo.toml
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/Cargo.toml
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/Cargo.toml
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/Cargo.toml
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/starters/seedling/Cargo.toml
  cumulus/parachains/runtimes/starters/seedling/src/lib.rs
  cumulus/parachains/runtimes/starters/shell/Cargo.toml
  cumulus/parachains/runtimes/starters/shell/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/Cargo.toml
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/Cargo.toml
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  docs/sdk/Cargo.toml
  docs/sdk/src/polkadot_sdk/cumulus.rs
  prdoc/pr_3654.prdoc
  substrate/frame/aura/src/lib.rs
  substrate/frame/aura/src/mock.rs
  templates/parachain/runtime/Cargo.toml
  templates/parachain/runtime/src/lib.rs
  templates/solochain/runtime/Cargo.toml
  templates/solochain/runtime/src/lib.rs
Labels: T1-FRAME

#3691 Fix typo
  bridges/modules/grandpa/README.md
Labels: R0-silent

#3350 Pallet AURA: remove pallet::getter macro and write the corresponding code
  cumulus/pallets/aura-ext/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/starters/seedling/src/lib.rs
  cumulus/parachains/runtimes/starters/shell/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  prdoc/pr_3350.prdoc
  substrate/frame/aura/src/lib.rs
  substrate/frame/aura/src/tests.rs
  templates/parachain/runtime/src/lib.rs
  templates/solochain/runtime/src/lib.rs
Labels: R0-silent

#3722 Fix kusama validators getting 0 backing rewards the first session they enter the active set
  prdoc/pr_3722.prdoc
  substrate/frame/authority-discovery/src/lib.rs
  substrate/frame/session/src/lib.rs
Labels: T1-FRAME

#3700 Bridge zombienet tests: remove unneeded accounts
  bridges/testing/environments/rococo-westend/bridges_rococo_westend.sh
Labels: R0-silent, T10-tests, T15-bridges

#3730 pallet-xcm: remove extrinsics guessed weight and rely on runtime benchmarks instead
  polkadot/xcm/pallet-xcm/src/lib.rs
Labels: R0-silent

#3735 Fix kusama validators getting 0 backing rewards the first session tey enter the active set
  prdoc/pr_3722.prdoc
  substrate/frame/authority-discovery/src/lib.rs
  substrate/frame/session/src/lib.rs
Labels: R0-silent, T1-FRAME

#3733 Fix kusama validators getting 0 backing rewards the first session tey enter the active set
  prdoc/pr_3722.prdoc
  substrate/frame/authority-discovery/src/lib.rs
  substrate/frame/session/src/lib.rs
Labels: R0-silent, T1-FRAME

#3471 removed `pallet::getter` usage from cumulus pallets
  cumulus/pallets/aura-ext/src/consensus_hook.rs
  cumulus/pallets/aura-ext/src/lib.rs
  cumulus/pallets/collator-selection/src/benchmarking.rs
  cumulus/pallets/collator-selection/src/lib.rs
  cumulus/pallets/collator-selection/src/migration.rs
  cumulus/pallets/collator-selection/src/tests.rs
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/parachains/pallets/parachain-info/src/lib.rs
  prdoc/pr_3471.prdoc
Labels: T1-FRAME, T2-pallets

#3696 Add HRMP notification handlers to the xcm-executor
  cumulus/pallets/xcmp-queue/src/mock.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/people/people-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/people/people-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/starters/shell/src/xcm_config.rs
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot/runtime/rococo/src/xcm_config.rs
  polkadot/runtime/test-runtime/src/xcm_config.rs
  polkadot/runtime/westend/src/xcm_config.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/fungible/mock.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/mock.rs
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/xcm-builder/src/tests/mock.rs
  polkadot/xcm/xcm-builder/src/tests/pay/mock.rs
  polkadot/xcm/xcm-builder/tests/mock/mod.rs
  polkadot/xcm/xcm-executor/src/config.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  polkadot/xcm/xcm-executor/src/traits/hrmp.rs
  polkadot/xcm/xcm-executor/src/traits/mod.rs
  polkadot/xcm/xcm-simulator/example/src/parachain.rs
  polkadot/xcm/xcm-simulator/example/src/relay_chain.rs
  polkadot/xcm/xcm-simulator/fuzzer/src/parachain.rs
  polkadot/xcm/xcm-simulator/fuzzer/src/relay_chain.rs
  prdoc/pr_3696.prdoc
  substrate/frame/contracts/mock-network/src/parachain.rs
  substrate/frame/contracts/mock-network/src/relay_chain.rs
  templates/parachain/runtime/src/xcm_config.rs
Labels: T6-XCM

#3741 Make `availability-recovery-regression-bench` a benchmark
  .gitlab/pipeline/test.yml
  polkadot/node/network/availability-recovery/Cargo.toml
  polkadot/node/network/availability-recovery/benches/availability-recovery-regression-bench.rs
Labels: R0-silent

#3740 Removed `pallet::getter` usage from Beefy and MMR pallets
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_3740.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/beefy-mmr/src/lib.rs
  substrate/frame/beefy-mmr/src/tests.rs
  substrate/frame/beefy/src/equivocation.rs
  substrate/frame/beefy/src/lib.rs
  substrate/frame/beefy/src/tests.rs
  substrate/frame/merkle-mountain-range/src/lib.rs
  substrate/frame/merkle-mountain-range/src/mmr/storage.rs
  substrate/frame/merkle-mountain-range/src/tests.rs
Labels: T2-pallets

#3713 rpc: Enable `transaction_unstable_broadcast` RPC V2 API
  substrate/client/service/src/builder.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement, D0-easy

#3684 Implement crypto byte array newtypes in term of a shared type
  cumulus/client/network/src/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/snowbridge.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/tests.rs
  polkadot/node/service/src/benchmarking.rs
  polkadot/node/test/service/src/lib.rs
  polkadot/primitives/src/v6/mod.rs
  polkadot/primitives/test-helpers/src/lib.rs
  polkadot/runtime/common/src/purchase.rs
  polkadot/runtime/parachains/src/builder.rs
  substrate/client/authority-discovery/src/tests.rs
  substrate/client/executor/runtime-test/src/lib.rs
  substrate/client/service/test/src/client/mod.rs
  substrate/frame/contracts/src/exec.rs
  substrate/frame/sassafras/src/benchmarking.rs
  substrate/frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr
  substrate/frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen_unnamed.stderr
  substrate/primitives/core/src/bandersnatch.rs
  substrate/primitives/core/src/bls.rs
  substrate/primitives/core/src/crypto.rs
  substrate/primitives/core/src/crypto_bytes.rs
  substrate/primitives/core/src/ecdsa.rs
  substrate/primitives/core/src/ed25519.rs
  substrate/primitives/core/src/lib.rs
  substrate/primitives/core/src/paired_crypto.rs
  substrate/primitives/core/src/sr25519.rs
  substrate/primitives/keystore/src/testing.rs
  substrate/primitives/runtime/src/traits.rs
  substrate/primitives/statement-store/src/lib.rs
Labels: R0-silent, I4-refactor

#3745 chore: bump zombienet version (1.3.95)
  .gitlab/pipeline/zombienet.yml
Labels: R0-silent, T10-tests

#3585 Contracts: Test benchmarking v2
  substrate/frame/contracts/src/benchmarking/mod.rs
  substrate/frame/contracts/src/weights.rs
Labels: R0-silent

#3580 Expose `ClaimQueue` via a runtime api and use it in `collation-generation`
  Cargo.lock
  cumulus/client/relay-chain-minimal-node/src/blockchain_rpc_client.rs
  cumulus/client/relay-chain-rpc-interface/src/rpc_client.rs
  polkadot/node/collation-generation/Cargo.toml
  polkadot/node/collation-generation/src/lib.rs
  polkadot/node/collation-generation/src/tests.rs
  polkadot/node/core/runtime-api/src/cache.rs
  polkadot/node/core/runtime-api/src/lib.rs
  polkadot/node/core/runtime-api/src/tests.rs
  polkadot/node/subsystem-types/src/messages.rs
  polkadot/node/subsystem-types/src/runtime_client.rs
  polkadot/node/subsystem-util/src/lib.rs
  polkadot/primitives/src/runtime_api.rs
  polkadot/runtime/parachains/src/runtime_api_impl/vstaging.rs
  prdoc/pr_3580.prdoc
Labels: T8-polkadot

#3753 Fix typos
  bridges/bin/runtime-common/src/priority_calculator.rs
  bridges/bin/runtime-common/src/refund_relayer_extension.rs
Labels: A1-insubstantial, R0-silent

#2615 Defensive Programming in Substrate Reference Document
  Cargo.lock
  docs/sdk/Cargo.toml
  docs/sdk/src/guides/your_first_pallet/mod.rs
  docs/sdk/src/reference_docs/defensive_programming.rs
  docs/sdk/src/reference_docs/mod.rs
  docs/sdk/src/reference_docs/safe_defensive_programming.rs
  substrate/primitives/arithmetic/Cargo.toml
  substrate/primitives/arithmetic/src/fixed_point.rs
  substrate/primitives/arithmetic/src/lib.rs
  substrate/primitives/arithmetic/src/per_things.rs
Labels: R0-silent, T11-documentation

#3765 Enable PoV reclaim on `rococo-parachain`
  Cargo.lock
  cumulus/parachains/runtimes/testing/rococo-parachain/Cargo.toml
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: R0-silent, T9-cumulus

#3754 Migrates Westend to Runtime V2
  polkadot/runtime/westend/Cargo.toml
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_3754.prdoc
Labels: T8-polkadot

#3758 [Backport] version bumps and prdocs reordering 1.9.0
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot/node/primitives/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/1.9.0/pr_1378.prdoc
  prdoc/1.9.0/pr_1554.prdoc
  prdoc/1.9.0/pr_1781.prdoc
  prdoc/1.9.0/pr_2393.prdoc
  prdoc/1.9.0/pr_3002.prdoc
  prdoc/1.9.0/pr_3187.prdoc
  prdoc/1.9.0/pr_3231.prdoc
  prdoc/1.9.0/pr_3233.prdoc
  prdoc/1.9.0/pr_3324.prdoc
  prdoc/1.9.0/pr_3371.prdoc
  prdoc/1.9.0/pr_3377.prdoc
  prdoc/1.9.0/pr_3378.prdoc
  prdoc/1.9.0/pr_3403.prdoc
  prdoc/1.9.0/pr_3411.prdoc
  prdoc/1.9.0/pr_3412.prdoc
  prdoc/1.9.0/pr_3447.prdoc
  prdoc/1.9.0/pr_3453.prdoc
  prdoc/1.9.0/pr_3454.prdoc
  prdoc/1.9.0/pr_3456.prdoc
  prdoc/1.9.0/pr_3460.prdoc
  prdoc/1.9.0/pr_3491.prdoc
  prdoc/1.9.0/pr_3504.prdoc
  prdoc/1.9.0/pr_3505.prdoc
  prdoc/1.9.0/pr_3510.prdoc
  prdoc/1.9.0/pr_3513.prdoc
  prdoc/1.9.0/pr_3523.prdoc
  prdoc/1.9.0/pr_3532.prdoc
  prdoc/1.9.0/pr_3540.prdoc
  prdoc/1.9.0/pr_3574.prdoc
  prdoc/1.9.0/pr_3589.prdoc
  prdoc/1.9.0/pr_3606.prdoc
  prdoc/1.9.0/pr_3636.prdoc
  prdoc/1.9.0/pr_3639.prdoc
  prdoc/1.9.0/pr_3643.prdoc
  prdoc/1.9.0/pr_3665.prdoc
Labels: R0-silent, A3-backport, D0-easy

#3759 [Backport] Reformat release notes generation
  scripts/release/build-changelogs.sh
  scripts/release/templates/audience.md.tera
Labels: R0-silent, A3-backport, D0-easy

#3479 Elastic scaling: runtime dependency tracking and enactment
  polkadot/roadmap/implementers-guide/src/runtime/inclusion.md
  polkadot/roadmap/implementers-guide/src/runtime/parainherent.md
  polkadot/roadmap/implementers-guide/src/runtime/scheduler.md
  polkadot/runtime/parachains/src/builder.rs
  polkadot/runtime/parachains/src/inclusion/migration.rs
  polkadot/runtime/parachains/src/inclusion/mod.rs
  polkadot/runtime/parachains/src/inclusion/tests.rs
  polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs
  polkadot/runtime/parachains/src/paras_inherent/mod.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
  polkadot/runtime/parachains/src/runtime_api_impl/v7.rs
  polkadot/runtime/parachains/src/scheduler.rs
  polkadot/runtime/parachains/src/util.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/runtime_parachains_paras_inherent.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/runtime_parachains_paras_inherent.rs
  prdoc/pr_3479.prdoc
Labels: I5-enhancement, T8-polkadot

#3747 approval-voting: remove some inefficiences on startup
  polkadot/node/core/approval-voting/src/lib.rs
Labels: R0-silent, T0-node

#3782 Fix toml formatting
  substrate/primitives/arithmetic/Cargo.toml
Labels: A1-insubstantial, R0-silent

#2571 Revert `SendXcmOrigin` in Rococo & Westend
  polkadot/runtime/rococo/src/xcm_config.rs
  polkadot/runtime/westend/src/xcm_config.rs
Labels: R0-silent

#3785 Upgrade litep2p identify implementation
  Cargo.lock
  substrate/client/network/src/litep2p/discovery.rs
Labels: A1-insubstantial, R0-silent, T0-node

#3727 Snowbridge Beacon header age check
  bridges/snowbridge/pallets/ethereum-client/src/lib.rs
  bridges/snowbridge/pallets/ethereum-client/src/tests.rs
  bridges/snowbridge/parachain/pallets/ethereum-beacon-client/src/mock.rs
Labels: R0-silent

#3790 Add a linear fee multiplier (#127)
  bridges/snowbridge/pallets/inbound-queue/src/mock.rs
  bridges/snowbridge/pallets/outbound-queue/runtime-api/src/lib.rs
  bridges/snowbridge/pallets/outbound-queue/src/api.rs
  bridges/snowbridge/pallets/outbound-queue/src/lib.rs
  bridges/snowbridge/pallets/outbound-queue/src/mock.rs
  bridges/snowbridge/pallets/outbound-queue/src/test.rs
  bridges/snowbridge/pallets/system/src/lib.rs
  bridges/snowbridge/pallets/system/src/mock.rs
  bridges/snowbridge/primitives/core/src/outbound.rs
  bridges/snowbridge/primitives/core/src/pricing.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
Labels: R0-silent, T15-bridges

#3794 Snowbridge - add a linear fee multiplier to ensure safety margins
  Cargo.lock
  bridges/snowbridge/parachain/pallets/inbound-queue/src/mock.rs
  bridges/snowbridge/parachain/pallets/outbound-queue/runtime-api/src/lib.rs
  bridges/snowbridge/parachain/pallets/outbound-queue/src/api.rs
  bridges/snowbridge/parachain/pallets/outbound-queue/src/lib.rs
  bridges/snowbridge/parachain/pallets/outbound-queue/src/mock.rs
  bridges/snowbridge/parachain/pallets/outbound-queue/src/test.rs
  bridges/snowbridge/parachain/pallets/system/src/lib.rs
  bridges/snowbridge/parachain/pallets/system/src/mock.rs
  bridges/snowbridge/parachain/primitives/core/src/outbound.rs
  bridges/snowbridge/parachain/primitives/core/src/pricing.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
Labels: R0-silent

#3757 Make public addresses go first in authority discovery DHT records
  Cargo.lock
  cumulus/client/relay-chain-minimal-node/src/lib.rs
  polkadot/node/service/src/lib.rs
  substrate/bin/node/cli/src/service.rs
  substrate/client/authority-discovery/Cargo.toml
  substrate/client/authority-discovery/src/lib.rs
  substrate/client/authority-discovery/src/worker.rs
  substrate/client/network/Cargo.toml
  substrate/client/network/src/discovery.rs
Labels: R0-silent, T0-node

#3798 pallet-xcm: fix transport fees for remote reserve transfers
  polkadot/xcm/pallet-xcm/src/lib.rs
Labels: R0-silent

#3763 XCM remove extra QueryId types from traits
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/xcm-builder/src/controller.rs
  polkadot/xcm/xcm-builder/src/pay.rs
  polkadot/xcm/xcm-builder/src/tests/mock.rs
  polkadot/xcm/xcm-executor/src/traits/on_response.rs
Labels: R0-silent, T6-XCM

#3792 [pallet-xcm] fix transport fees for remote reserve transfers
  cumulus/parachains/integration-tests/emulated/common/src/macros.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-rococo/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/teleport.rs
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases.rs
  cumulus/parachains/runtimes/assets/test-utils/src/xcm_helpers.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/pallet-xcm/src/tests/assets_transfer.rs
  prdoc/pr_3792.prdoc
Labels: T6-XCM

#3768 Fix xcm config for coretime.
  polkadot/runtime/westend/src/xcm_config.rs
Labels: A1-insubstantial, R0-silent

#3732 pallet-aura: Expose `SlotDuration` as constant
  substrate/frame/aura/src/lib.rs
Labels: R0-silent

#3821 Patches for #3749
  substrate/frame/contracts/mock-network/src/tests.rs
  substrate/frame/contracts/src/lib.rs
  substrate/frame/contracts/src/wasm/runtime.rs
  substrate/frame/contracts/uapi/src/host.rs
Labels: R0-silent

#3799 [docs] Update ci image in container.md
  docs/contributor/container.md
Labels: R0-silent

#3822 [Bridges] Move chain definitions to separate folder
  Cargo.toml
  bridges/chains/chain-asset-hub-rococo/Cargo.toml
  bridges/chains/chain-asset-hub-rococo/src/lib.rs
  bridges/chains/chain-asset-hub-westend/Cargo.toml
  bridges/chains/chain-asset-hub-westend/src/lib.rs
  bridges/chains/chain-bridge-hub-cumulus/Cargo.toml
  bridges/chains/chain-bridge-hub-cumulus/src/lib.rs
  bridges/chains/chain-bridge-hub-kusama/Cargo.toml
  bridges/chains/chain-bridge-hub-kusama/src/lib.rs
  bridges/chains/chain-bridge-hub-polkadot/Cargo.toml
  bridges/chains/chain-bridge-hub-polkadot/src/lib.rs
  bridges/chains/chain-bridge-hub-rococo/Cargo.toml
  bridges/chains/chain-bridge-hub-rococo/src/lib.rs
  bridges/chains/chain-bridge-hub-westend/Cargo.toml
  bridges/chains/chain-bridge-hub-westend/src/lib.rs
  bridges/chains/chain-kusama/Cargo.toml
  bridges/chains/chain-kusama/src/lib.rs
  bridges/chains/chain-polkadot-bulletin/Cargo.toml
  bridges/chains/chain-polkadot-bulletin/src/lib.rs
  bridges/chains/chain-polkadot/Cargo.toml
  bridges/chains/chain-polkadot/src/lib.rs
  bridges/chains/chain-rococo/Cargo.toml
  bridges/chains/chain-rococo/src/lib.rs
  bridges/chains/chain-westend/Cargo.toml
  bridges/chains/chain-westend/src/lib.rs
  bridges/snowbridge/pallets/ethereum-client/Cargo.toml
  bridges/snowbridge/pallets/inbound-queue/Cargo.toml
  cumulus/client/consensus/aura/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/parachains/collectives/collectives-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/parachains/people/people-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/parachains/people/people-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/parachains/testing/penpal/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/relays/rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/relays/westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/people/people-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/Cargo.toml
  cumulus/parachains/pallets/collective-content/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/Cargo.toml
  cumulus/primitives/storage-weight-reclaim/Cargo.toml
  polkadot/Cargo.toml
  polkadot/node/core/pvf/Cargo.toml
  templates/solochain/runtime/Cargo.toml
Labels: R0-silent, T15-bridges

#3778 elastic scaling: preserve candidate ordering in provisioner
  polkadot/node/core/backing/src/error.rs
  polkadot/node/core/backing/src/lib.rs
  polkadot/node/core/backing/src/tests/mod.rs
  polkadot/node/core/provisioner/src/lib.rs
  polkadot/node/core/provisioner/src/tests.rs
  polkadot/node/overseer/src/tests.rs
  polkadot/node/subsystem-types/src/messages.rs
  polkadot/roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: R0-silent, T8-polkadot

#3723 [prdoc] Remove default audience
  prdoc/.template.prdoc
Labels: R0-silent

#3806 Refactor crypto-related traits implementations in term of Public/Signature Bytes
  substrate/primitives/application-crypto/src/lib.rs
  substrate/primitives/core/src/bandersnatch.rs
  substrate/primitives/core/src/bls.rs
  substrate/primitives/core/src/crypto.rs
  substrate/primitives/core/src/crypto_bytes.rs
  substrate/primitives/core/src/ecdsa.rs
  substrate/primitives/core/src/ed25519.rs
  substrate/primitives/core/src/lib.rs
  substrate/primitives/core/src/paired_crypto.rs
  substrate/primitives/core/src/sr25519.rs
  substrate/primitives/statement-store/src/ecies.rs
Labels: R0-silent, I4-refactor

#3698 [subsystem-benchmarks] Fix availability-write regression tests
  .gitlab/pipeline/test.yml
  polkadot/node/network/availability-distribution/Cargo.toml
  polkadot/node/network/availability-distribution/benches/availability-distribution-regression-bench.rs
  polkadot/node/network/availability-recovery/benches/availability-recovery-regression-bench.rs
  polkadot/node/subsystem-bench/Cargo.toml
  polkadot/node/subsystem-bench/src/cli/subsystem-bench.rs
  polkadot/node/subsystem-bench/src/lib/availability/mod.rs
  polkadot/node/subsystem-bench/src/lib/availability/test_state.rs
  polkadot/node/subsystem-bench/src/lib/environment.rs
  polkadot/node/subsystem-bench/src/lib/lib.rs
  polkadot/node/subsystem-bench/src/lib/mock/av_store.rs
  polkadot/node/subsystem-bench/src/lib/mock/runtime_api.rs
  polkadot/node/subsystem-bench/src/lib/usage.rs
  polkadot/node/subsystem-bench/src/lib/utils.rs
Labels: R0-silent, T12-benchmarks

#3839 pallet-xcm: fix transport fees for remote reserve transfers (#3798) - backport for 1.8
  Cargo.lock
  polkadot/xcm/pallet-xcm/src/lib.rs
Labels: R0-silent, T6-XCM

#3815 Snowbridge Beacon header age check and add linear fee multiplier to ensure safety margins
  bridges/snowbridge/pallets/ethereum-client/src/lib.rs
  bridges/snowbridge/pallets/ethereum-client/src/tests.rs
  bridges/snowbridge/pallets/inbound-queue/src/mock.rs
  bridges/snowbridge/pallets/outbound-queue/runtime-api/src/lib.rs
  bridges/snowbridge/pallets/outbound-queue/src/api.rs
  bridges/snowbridge/pallets/outbound-queue/src/lib.rs
  bridges/snowbridge/pallets/outbound-queue/src/mock.rs
  bridges/snowbridge/pallets/outbound-queue/src/test.rs
  bridges/snowbridge/pallets/system/src/lib.rs
  bridges/snowbridge/pallets/system/src/mock.rs
  bridges/snowbridge/primitives/core/src/outbound.rs
  bridges/snowbridge/primitives/core/src/pricing.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
Labels: R0-silent, T15-bridges

#3840 pallet-xcm: fix transport fees for remote reserve transfers (#3798) - backport for 1.9
  polkadot/xcm/pallet-xcm/src/lib.rs
Labels: R0-silent, T6-XCM

#3842 Fix formatting in Cargo.toml
  polkadot/node/subsystem-bench/Cargo.toml
Labels: R0-silent

#3829 [subsystem-benchmarks] Save results to json
  Cargo.lock
  polkadot/node/network/availability-distribution/benches/availability-distribution-regression-bench.rs
  polkadot/node/network/availability-recovery/benches/availability-recovery-regression-bench.rs
  polkadot/node/subsystem-bench/Cargo.toml
  polkadot/node/subsystem-bench/src/lib/environment.rs
  polkadot/node/subsystem-bench/src/lib/lib.rs
  polkadot/node/subsystem-bench/src/lib/usage.rs
  polkadot/node/subsystem-bench/src/lib/utils.rs
Labels: R0-silent, T12-benchmarks

#3646 westend: `SignedPhase` is a constant
  substrate/frame/election-provider-multi-phase/src/lib.rs
Labels: R0-silent

#3607 XCM Fee Payment Runtime API
  Cargo.lock
  Cargo.toml
  polkadot/node/service/Cargo.toml
  polkadot/node/service/src/fake_runtime_api.rs
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/Cargo.toml
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/tests.rs
  polkadot/xcm/pallet-xcm/Cargo.toml
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/src/lib.rs
  polkadot/xcm/xcm-fee-payment-runtime-api/Cargo.toml
  polkadot/xcm/xcm-fee-payment-runtime-api/src/lib.rs
  prdoc/pr_3607.prdoc
Labels: T6-XCM

#3781 add metaspan boot node to coretime-westend.json
  cumulus/parachains/chain-specs/coretime-westend.json
Labels: R0-silent

#3830 chore: bump zombienet version
  .gitlab/pipeline/zombienet.yml
Labels: R0-silent, T10-tests

#3827 testnet genesis: enable approval voting v2 assignments and coalescing
  polkadot/node/service/src/chain_spec.rs
Labels: R0-silent

#3749 pallet-xcm: Deprecate `execute` and `send` in favor of `execute_blob` and `send_blob`
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/chains/relays/westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/common/src/impls.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/send.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/swap.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/send.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/swap.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/send_xcm.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/send_xcm.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/pallet_xcm.rs
  polkadot/runtime/rococo/src/impls.rs
  polkadot/runtime/rococo/src/weights/pallet_xcm.rs
  polkadot/runtime/westend/src/impls.rs
  polkadot/runtime/westend/src/weights/pallet_xcm.rs
  polkadot/xcm/pallet-xcm/src/benchmarking.rs
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/pallet-xcm/src/tests/mod.rs
  polkadot/xcm/src/lib.rs
  polkadot/xcm/src/v4/mod.rs
  polkadot/xcm/xcm-builder/src/controller.rs
  polkadot/xcm/xcm-builder/src/lib.rs
  prdoc/pr_3749.prdoc
  substrate/frame/contracts/mock-network/src/tests.rs
  substrate/frame/contracts/src/lib.rs
  substrate/frame/contracts/src/wasm/runtime.rs
  substrate/frame/contracts/uapi/src/host.rs
Labels: T6-XCM

#3764 authority-discovery: Set intervals to start when authority keys changes
  substrate/client/authority-discovery/src/interval.rs
  substrate/client/authority-discovery/src/worker.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement, D0-easy

#3853 [ci] Collect subsystem-benchmarks results and add graphs for them
  .github/workflows/subsystem-benchmarks.yml
  .gitlab-ci.yml
  .gitlab/pipeline/publish.yml
  .gitlab/pipeline/test.yml
Labels: R0-silent

#3795 collation-generation + collator-protocol: collate on multiple assigned cores
  cumulus/client/consensus/aura/src/collators/lookahead.rs
  polkadot/node/collation-generation/src/error.rs
  polkadot/node/collation-generation/src/lib.rs
  polkadot/node/collation-generation/src/tests.rs
  polkadot/node/network/collator-protocol/src/collator_side/mod.rs
  polkadot/node/network/collator-protocol/src/collator_side/tests/mod.rs
  polkadot/node/network/collator-protocol/src/collator_side/tests/prospective_parachains.rs
  polkadot/node/network/collator-protocol/src/collator_side/validators_buffer.rs
  polkadot/node/primitives/src/lib.rs
  polkadot/node/subsystem-types/src/messages.rs
  polkadot/node/subsystem-util/src/lib.rs
  polkadot/parachain/test-parachains/adder/collator/Cargo.toml
  polkadot/parachain/test-parachains/undying/collator/Cargo.toml
  polkadot/runtime/test-runtime/src/lib.rs
  prdoc/pr_3795.prdoc
Labels: R0-silent

#3706 Extrinsic to restore corrupt staking ledgers
  polkadot/runtime/westend/src/weights/pallet_staking.rs
  prdoc/pr_3706.prdoc
  substrate/frame/balances/src/impl_currency.rs
  substrate/frame/balances/src/tests/currency_tests.rs
  substrate/frame/staking/Cargo.toml
  substrate/frame/staking/src/benchmarking.rs
  substrate/frame/staking/src/lib.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/tests.rs
  substrate/frame/staking/src/weights.rs
  substrate/frame/support/src/traits.rs
  substrate/frame/support/src/traits/tokens/currency.rs
  substrate/frame/support/src/traits/tokens/currency/lockable.rs
Labels: T2-pallets

#3849 pallet-scheduler: Unrequest call on failed lookup
  prdoc/pr_3849.prdoc
  substrate/frame/scheduler/src/lib.rs
  substrate/frame/scheduler/src/tests.rs
Labels: T1-FRAME

#3850 pallet-referenda: Detect incorrect pre-image length
  prdoc/pr_3850.prdoc
  substrate/frame/referenda/src/lib.rs
  substrate/frame/referenda/src/tests.rs
Labels: T1-FRAME

#3718 Deprecate scheduler traits v1 and v2
  prdoc/pr_3718.prdoc
  substrate/frame/scheduler/src/lib.rs
  substrate/frame/support/src/traits/schedule.rs
Labels: T1-FRAME

#3816 [prdoc] Require SemVer bump level
  prdoc/schema_user.json
Labels: R0-silent

#3817 [parachain-template] runtime API Implementations into `mod apis`
  prdoc/pr_3817.prdoc
  substrate/primitives/api/proc-macro/src/impl_runtime_apis.rs
  templates/parachain/node/src/service.rs
  templates/parachain/runtime/src/apis.rs
  templates/parachain/runtime/src/lib.rs
Labels: R0-silent

#3862 Update benchmarking README.md
  substrate/frame/benchmarking/README.md
Labels: R0-silent

#3871 Release crates io v1.7.0 staking backports
  polkadot/runtime/westend/src/weights/pallet_staking.rs
  prdoc/pr_3639.prdoc
  prdoc/pr_3706.prdoc
  substrate/frame/balances/src/impl_currency.rs
  substrate/frame/balances/src/tests/currency_tests.rs
  substrate/frame/staking/Cargo.toml
  substrate/frame/staking/src/benchmarking.rs
  substrate/frame/staking/src/ledger.rs
  substrate/frame/staking/src/lib.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/tests.rs
  substrate/frame/staking/src/weights.rs
  substrate/frame/support/src/traits.rs
  substrate/frame/support/src/traits/tokens/currency.rs
  substrate/frame/support/src/traits/tokens/currency/lockable.rs
Labels: A3-backport

#3854 Export unified ParachainHostFunctions
  Cargo.lock
  cumulus/client/service/Cargo.toml
  cumulus/client/service/src/lib.rs
  cumulus/polkadot-parachain/src/service.rs
  prdoc/pr_3854.prdoc
  templates/parachain/node/src/service.rs
Labels: T0-node, T9-cumulus

#2212 add missing syscalls for workers
  polkadot/scripts/packaging/polkadot.service
Labels: R0-silent, T0-node

#3876 [ci] fix subsystem-benchmarks gha
  .github/workflows/subsystem-benchmarks.yml
Labels: R0-silent

#3883 collation-genereation: fix tests
  polkadot/node/collation-generation/src/tests.rs
Labels: R0-silent, T10-tests

#3383 Remove transient code after `im-online` pallet removal
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
Labels: R0-silent, T2-pallets

#3873 Decorate mpsc-notification-to-protocol with the protocol name
  substrate/client/network/src/protocol/notifications/service/mod.rs
  substrate/client/utils/src/mpsc.rs
Labels: R0-silent

#3895 Fix `addresses_to_publish_respects_existing_p2p_protocol` test in sc-authority-discovery
  substrate/client/authority-discovery/src/worker.rs
  substrate/client/authority-discovery/src/worker/tests.rs
Labels: A1-insubstantial, R0-silent, T0-node

#2802 Tokens in FRAME Docs
  Cargo.lock
  docs/sdk/Cargo.toml
  docs/sdk/src/reference_docs/frame_currency.rs
  docs/sdk/src/reference_docs/frame_pallet_coupling.rs
  docs/sdk/src/reference_docs/frame_runtime_upgrades_and_migrations.rs
  docs/sdk/src/reference_docs/frame_tokens.rs
  docs/sdk/src/reference_docs/mod.rs
  substrate/frame/assets/src/lib.rs
  substrate/frame/balances/src/lib.rs
  substrate/frame/support/src/traits/tokens/currency.rs
  substrate/frame/support/src/traits/tokens/fungible/freeze.rs
  substrate/frame/support/src/traits/tokens/fungible/hold.rs
  substrate/frame/support/src/traits/tokens/fungible/imbalance.rs
  substrate/frame/support/src/traits/tokens/fungible/item_of.rs
  substrate/frame/support/src/traits/tokens/fungible/mod.rs
  substrate/frame/support/src/traits/tokens/fungible/regular.rs
  substrate/frame/support/src/traits/tokens/fungible/union_of.rs
  substrate/frame/support/src/traits/tokens/fungibles/approvals.rs
  substrate/frame/support/src/traits/tokens/fungibles/enumerable.rs
  substrate/frame/support/src/traits/tokens/fungibles/freeze.rs
  substrate/frame/support/src/traits/tokens/fungibles/hold.rs
  substrate/frame/support/src/traits/tokens/fungibles/imbalance.rs
  substrate/frame/support/src/traits/tokens/fungibles/lifetime.rs
  substrate/frame/support/src/traits/tokens/fungibles/metadata.rs
  substrate/frame/support/src/traits/tokens/fungibles/mod.rs
  substrate/frame/support/src/traits/tokens/fungibles/regular.rs
  substrate/frame/support/src/traits/tokens/fungibles/roles.rs
  substrate/frame/support/src/traits/tokens/fungibles/union_of.rs
Labels: R0-silent, T11-documentation

#3913 Revert log level changes
  polkadot/node/network/gossip-support/src/lib.rs
Labels: R0-silent
