Repository paritytech/polkadot-sdk, pull requests merged in 2024-09, with the labels that each got.

#4928 [3 / 5] Move crypto checks in the approval-distribution
  Cargo.lock
  polkadot/node/core/approval-voting/benches/approval-voting-regression-bench.rs
  polkadot/node/core/approval-voting/src/approval_checking.rs
  polkadot/node/core/approval-voting/src/criteria.rs
  polkadot/node/core/approval-voting/src/import.rs
  polkadot/node/core/approval-voting/src/lib.rs
  polkadot/node/core/approval-voting/src/persisted_entries.rs
  polkadot/node/core/approval-voting/src/tests.rs
  polkadot/node/network/approval-distribution/Cargo.toml
  polkadot/node/network/approval-distribution/src/lib.rs
  polkadot/node/network/approval-distribution/src/metrics.rs
  polkadot/node/network/approval-distribution/src/tests.rs
  polkadot/node/overseer/src/lib.rs
  polkadot/node/primitives/Cargo.toml
  polkadot/node/primitives/src/approval/criteria.rs
  polkadot/node/primitives/src/approval/mod.rs
  polkadot/node/primitives/src/approval/time.rs
  polkadot/node/service/src/overseer.rs
  polkadot/node/subsystem-bench/src/lib/approval/helpers.rs
  polkadot/node/subsystem-bench/src/lib/approval/message_generator.rs
  polkadot/node/subsystem-bench/src/lib/approval/mock_chain_selection.rs
  polkadot/node/subsystem-bench/src/lib/approval/mod.rs
  polkadot/node/subsystem-types/src/messages.rs
  polkadot/roadmap/implementers-guide/src/node/approval/approval-distribution.md
  polkadot/roadmap/implementers-guide/src/node/approval/approval-voting.md
  polkadot/roadmap/implementers-guide/src/types/overseer-protocol.md
  prdoc/pr_4928.prdoc
Labels: T0-node, T8-polkadot

#5131 Swaps for XCM delivery fees
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-westend/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/testing/penpal/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/testing/penpal/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/reserve_transfer.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/common/Cargo.toml
  cumulus/parachains/runtimes/assets/common/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/Cargo.toml
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
  polkadot/xcm/xcm-builder/src/asset_exchange/single_asset_adapter/adapter.rs
  polkadot/xcm/xcm-executor/src/config.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  prdoc/pr_5131.prdoc
Labels: T6-XCM

#5364 Improve `sc-service` API
  cumulus/client/relay-chain-minimal-node/src/lib.rs
  cumulus/client/relay-chain-minimal-node/src/network.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/cli.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/common/spec.rs
  cumulus/test/service/src/cli.rs
  cumulus/test/service/src/lib.rs
  polkadot/node/service/src/lib.rs
  polkadot/node/test/service/src/lib.rs
  prdoc/pr_5364.prdoc
  substrate/bin/node/cli/benches/block_production.rs
  substrate/bin/node/cli/benches/transaction_pool.rs
  substrate/bin/node/cli/src/service.rs
  substrate/bin/node/inspect/src/command.rs
  substrate/client/cli/src/commands/run_cmd.rs
  substrate/client/cli/src/config.rs
  substrate/client/cli/src/lib.rs
  substrate/client/cli/src/params/node_key_params.rs
  substrate/client/cli/src/runner.rs
  substrate/client/network/common/src/role.rs
  substrate/client/service/src/builder.rs
  substrate/client/service/src/config.rs
  substrate/client/service/src/lib.rs
  substrate/client/service/src/metrics.rs
  substrate/client/service/test/src/lib.rs
  templates/minimal/node/src/service.rs
  templates/parachain/node/src/command.rs
  templates/parachain/node/src/service.rs
  templates/solochain/node/src/service.rs
Labels: T0-node

#5538 collator-protocol: Handle unknown validator heads
  Cargo.lock
  Cargo.toml
  polkadot/node/network/collator-protocol/Cargo.toml
  polkadot/node/network/collator-protocol/src/collator_side/mod.rs
  polkadot/node/network/collator-protocol/src/collator_side/tests/mod.rs
  polkadot/node/network/collator-protocol/src/collator_side/tests/prospective_parachains.rs
  polkadot/node/subsystem-test-helpers/src/lib.rs
  prdoc/pr_5538.prdoc
Labels: T8-polkadot

#5322 Elastic scaling: introduce new candidate receipt primitive
  Cargo.lock
  cumulus/client/relay-chain-inprocess-interface/src/lib.rs
  polkadot/node/service/src/fake_runtime_api.rs
  polkadot/node/subsystem-types/src/runtime_client.rs
  polkadot/node/test/client/src/block_builder.rs
  polkadot/primitives/Cargo.toml
  polkadot/primitives/src/runtime_api.rs
  polkadot/primitives/src/v8/mod.rs
  polkadot/primitives/src/vstaging/async_backing.rs
  polkadot/primitives/src/vstaging/mod.rs
  polkadot/primitives/test-helpers/src/lib.rs
  polkadot/runtime/parachains/Cargo.toml
  polkadot/runtime/parachains/src/builder.rs
  polkadot/runtime/parachains/src/inclusion/benchmarking.rs
  polkadot/runtime/parachains/src/inclusion/migration.rs
  polkadot/runtime/parachains/src/inclusion/mod.rs
  polkadot/runtime/parachains/src/inclusion/tests.rs
  polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs
  polkadot/runtime/parachains/src/paras_inherent/mod.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
  polkadot/runtime/parachains/src/runtime_api_impl/v10.rs
  polkadot/runtime/parachains/src/runtime_api_impl/vstaging.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_5322.prdoc
Labels: T4-runtime_API, T8-polkadot

#5549 Update CODEOWNERS and review-bot for new contracts pallet
  .github/CODEOWNERS
  .github/review-bot.yml
Labels: R0-silent

#5548 [pallet-revive] Use address20 for contract's address
  Cargo.lock
  prdoc/pr_5548.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/fixtures/Cargo.toml
  substrate/frame/revive/fixtures/contracts/call.rs
  substrate/frame/revive/fixtures/contracts/call_return_code.rs
  substrate/frame/revive/fixtures/contracts/call_runtime_and_call.rs
  substrate/frame/revive/fixtures/contracts/call_with_flags_and_value.rs
  substrate/frame/revive/fixtures/contracts/call_with_limit.rs
  substrate/frame/revive/fixtures/contracts/caller_contract.rs
  substrate/frame/revive/fixtures/contracts/create_storage_and_call.rs
  substrate/frame/revive/fixtures/contracts/create_storage_and_instantiate.rs
  substrate/frame/revive/fixtures/contracts/create_transient_storage_and_call.rs
  substrate/frame/revive/fixtures/contracts/delegate_call_lib.rs
  substrate/frame/revive/fixtures/contracts/destroy_and_transfer.rs
  substrate/frame/revive/fixtures/contracts/locking_delegate_dependency.rs
  substrate/frame/revive/fixtures/contracts/read_only_call.rs
  substrate/frame/revive/fixtures/contracts/self_destruct.rs
  substrate/frame/revive/fixtures/src/lib.rs
  substrate/frame/revive/mock-network/src/parachain/contracts_config.rs
  substrate/frame/revive/src/address.rs
  substrate/frame/revive/src/benchmarking/call_builder.rs
  substrate/frame/revive/src/benchmarking/code.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/debug.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/primitives.rs
  substrate/frame/revive/src/storage.rs
  substrate/frame/revive/src/storage/meter.rs
  substrate/frame/revive/src/test_utils.rs
  substrate/frame/revive/src/test_utils/builder.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/tests/test_debug.rs
  substrate/frame/revive/src/wasm/mod.rs
  substrate/frame/revive/src/wasm/runtime.rs
Labels: T2-pallets

#5201 Snowbridge free consensus updates
  bridges/snowbridge/pallets/ethereum-client/src/lib.rs
  bridges/snowbridge/pallets/ethereum-client/src/mock.rs
  bridges/snowbridge/pallets/ethereum-client/src/tests.rs
  bridges/snowbridge/pallets/inbound-queue/src/mock.rs
  bridges/snowbridge/runtime/test-common/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_ethereum_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/bridge_to_ethereum_config.rs
  prdoc/pr_5201.prdoc
Labels: T15-bridges

#5198 [FRAME] MQ processor should be transactional
  prdoc/pr_5198.prdoc
  substrate/frame/message-queue/src/integration_test.rs
  substrate/frame/message-queue/src/lib.rs
  substrate/frame/message-queue/src/mock.rs
  substrate/frame/message-queue/src/tests.rs
Labels: T2-pallets

#5437 Remove noise from the template list
  docs/sdk/src/polkadot_sdk/templates.rs
  docs/sdk/src/reference_docs/cli.rs
Labels: R0-silent

#5560 [backport] Snowbridge free consensus updates (#5201)
  bridges/snowbridge/pallets/ethereum-client/src/lib.rs
  bridges/snowbridge/pallets/ethereum-client/src/mock.rs
  bridges/snowbridge/pallets/ethereum-client/src/tests.rs
  bridges/snowbridge/pallets/inbound-queue/src/mock.rs
  bridges/snowbridge/runtime/test-common/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_ethereum_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/bridge_to_ethereum_config.rs
  prdoc/1.16.0/pr_5201.prdoc
Labels: R0-silent

#5556 revive: Make `salt` salt optional to allow for CREATE1 semantics
  prdoc/pr_5556.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/revive/src/address.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/test_utils/builder.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/tests/test_debug.rs
  substrate/frame/revive/src/wasm/runtime.rs
Labels: R0-silent

#5561 [CI] Also backport to stable2409
  .github/workflows/command-backport.yml
Labels: R0-silent

#5346 GHA Migration - build misc
  .github/workflows/build-misc.yml
  .github/workflows/check-runtime-migration.yml
  .github/workflows/checks.yml
  .github/workflows/publish-subsystem-benchmarks.yml
  .github/workflows/subsystem-benchmarks.yml
  .gitlab/pipeline/build.yml
  .gitlab/pipeline/publish.yml
  .gitlab/pipeline/test.yml
Labels: R0-silent

#5527 chainHead/fix: Report bestBlock events only for newBlock reports
  prdoc/pr_5527.prdoc
  substrate/client/rpc-spec-v2/src/chain_head/chain_head_follow.rs
  substrate/client/rpc-spec-v2/src/chain_head/test_utils.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
Labels: I2-bug, T3-RPC_API, D0-easy

#5515 cumulus/client: added external rpc connection retry logic
  Cargo.lock
  cumulus/client/relay-chain-rpc-interface/Cargo.toml
  cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs
  prdoc/pr_5515.prdoc
Labels: T9-cumulus

#5582 [backport] chainHead/fix: Report bestBlock events only for newBlock reports (#5527)
  prdoc/pr_5527.prdoc
  substrate/client/rpc-spec-v2/src/chain_head/chain_head_follow.rs
  substrate/client/rpc-spec-v2/src/chain_head/test_utils.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
Labels: R0-silent

#4889 Add parachain related parameters to `chain-spec-builder`
  Cargo.lock
  docs/sdk/src/reference_docs/chain_spec_genesis.rs
  docs/sdk/src/reference_docs/chain_spec_runtime/tests/chain_spec_builder_tests.rs
  prdoc/pr_4889.prdoc
  substrate/bin/utils/chain-spec-builder/Cargo.toml
  substrate/bin/utils/chain-spec-builder/bin/main.rs
  substrate/bin/utils/chain-spec-builder/src/lib.rs
  substrate/bin/utils/chain-spec-builder/tests/expected/add_code_substitute.json
  substrate/bin/utils/chain-spec-builder/tests/expected/convert_to_raw.json
  substrate/bin/utils/chain-spec-builder/tests/expected/create_default.json
  substrate/bin/utils/chain-spec-builder/tests/expected/create_parachain.json
  substrate/bin/utils/chain-spec-builder/tests/expected/create_raw_storage.json
  substrate/bin/utils/chain-spec-builder/tests/expected/create_with_full.json
  substrate/bin/utils/chain-spec-builder/tests/expected/create_with_named_preset.json
  substrate/bin/utils/chain-spec-builder/tests/expected/create_with_params.json
  substrate/bin/utils/chain-spec-builder/tests/expected/create_with_patch.json
  substrate/bin/utils/chain-spec-builder/tests/expected/update_code.json
  substrate/bin/utils/chain-spec-builder/tests/expected/update_code_raw.json
  substrate/bin/utils/chain-spec-builder/tests/input/chain_spec_conversion_test.json
  substrate/bin/utils/chain-spec-builder/tests/input/chain_spec_plain.json
  substrate/bin/utils/chain-spec-builder/tests/input/chain_spec_raw.json
  substrate/bin/utils/chain-spec-builder/tests/input/code_040506.blob
  substrate/bin/utils/chain-spec-builder/tests/input/full.json
  substrate/bin/utils/chain-spec-builder/tests/input/patch.json
  substrate/bin/utils/chain-spec-builder/tests/test.rs
Labels: T11-documentation

#5540 Avoid updating the block gap when it's unchanged
  prdoc/pr_5540.prdoc
  substrate/client/db/src/lib.rs
Labels: T0-node

#5518 Add badges with the release info to the README.md
  README.md
Labels: R0-silent, T11-documentation, D0-easy

#3151 Collective: dynamic deposit based on number of proposals
  Cargo.lock
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_collective.rs
  prdoc/pr_3151.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/alliance/src/mock.rs
  substrate/frame/balances/src/tests/fungible_tests.rs
  substrate/frame/collective/Cargo.toml
  substrate/frame/collective/src/benchmarking.rs
  substrate/frame/collective/src/lib.rs
  substrate/frame/collective/src/tests.rs
  substrate/frame/collective/src/weights.rs
  substrate/frame/utility/src/tests.rs
Labels: T1-FRAME

#5526 try making bench numbers make sense
  polkadot/runtime/parachains/src/inclusion/benchmarking.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_parachains_inclusion.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_parachains_inclusion.rs
  prdoc/pr_5526.prdoc
Labels: R0-silent, T12-benchmarks

#5558 build and publish images migration
  .github/actions/build-push-image/action.yml
  .github/workflows/build-publish-images.yml
Labels: R0-silent, GHA-migration

#3881 Create a Basic Proving Trie for the Runtime
  Cargo.lock
  prdoc/pr_3881.prdoc
  substrate/primitives/runtime/Cargo.toml
  substrate/primitives/runtime/src/lib.rs
  substrate/primitives/runtime/src/proving_trie.rs
Labels: T4-runtime_API

#5590 fix link check
  .config/lychee.toml
Labels: R0-silent, T11-documentation

#5555 [pallet-revive] refactor uapi with better types
  prdoc/pr_5555.prdoc
  substrate/frame/revive/fixtures/build.rs
  substrate/frame/revive/fixtures/contracts/call.rs
  substrate/frame/revive/fixtures/contracts/call_return_code.rs
  substrate/frame/revive/fixtures/contracts/call_runtime_and_call.rs
  substrate/frame/revive/fixtures/contracts/call_with_flags_and_value.rs
  substrate/frame/revive/fixtures/contracts/call_with_limit.rs
  substrate/frame/revive/fixtures/contracts/caller_contract.rs
  substrate/frame/revive/fixtures/contracts/chain_extension_temp_storage.rs
  substrate/frame/revive/fixtures/contracts/common/src/lib.rs
  substrate/frame/revive/fixtures/contracts/create_storage_and_call.rs
  substrate/frame/revive/fixtures/contracts/create_storage_and_instantiate.rs
  substrate/frame/revive/fixtures/contracts/create_transient_storage_and_call.rs
  substrate/frame/revive/fixtures/contracts/delegate_call.rs
  substrate/frame/revive/fixtures/contracts/delegate_call_lib.rs
  substrate/frame/revive/fixtures/contracts/delegate_call_simple.rs
  substrate/frame/revive/fixtures/contracts/destroy_and_transfer.rs
  substrate/frame/revive/fixtures/contracts/drain.rs
  substrate/frame/revive/fixtures/contracts/instantiate_return_code.rs
  substrate/frame/revive/fixtures/contracts/locking_delegate_dependency.rs
  substrate/frame/revive/fixtures/contracts/read_only_call.rs
  substrate/frame/revive/fixtures/contracts/recurse.rs
  substrate/frame/revive/fixtures/contracts/self_destruct.rs
  substrate/frame/revive/fixtures/contracts/self_destructing_constructor.rs
  substrate/frame/revive/fixtures/contracts/set_code_hash.rs
  substrate/frame/revive/fixtures/contracts/transfer_return_code.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/debug.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/storage.rs
  substrate/frame/revive/src/tests/test_debug.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/src/weights.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv32.rs
Labels: T7-smart_contracts

#5446 Update and test the `getting-started` script
  .github/workflows/check-getting-started.yml
  scripts/getting-started.sh
Labels: R0-silent

#5571 [ci] Move test-linux-stable to GHA
  .github/workflows/tests-linux-stable.yml
  .gitlab-ci.yml
  .gitlab/pipeline/test.yml
Labels: R0-silent

#5581 Clear other messages before dry-run to get only the ones produced during
  bridges/modules/xcm-bridge-hub-router/src/lib.rs
  bridges/modules/xcm-bridge-hub-router/src/mock.rs
  bridges/modules/xcm-bridge-hub/src/mock.rs
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/xcmp-queue/src/lib.rs
  cumulus/primitives/utility/src/lib.rs
  polkadot/runtime/common/src/xcm_sender.rs
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/xcm-builder/src/routing.rs
  polkadot/xcm/xcm-builder/src/universal_exports.rs
  prdoc/pr_5581.prdoc
Labels: T6-XCM, A4-needs-backport

#5389 Make the docs logo readable on light backgrounds
  docs/sdk/assets/theme.css
  docs/sdk/src/lib.rs
Labels: R0-silent, T11-documentation

#5127 Add benchmark for the number of minimum cpu cores
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/command.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/common/spec.rs
  polkadot/cli/src/command.rs
  polkadot/node/service/src/lib.rs
  prdoc/pr_5127.prdoc
  substrate/bin/node/cli/src/service.rs
  substrate/client/sysinfo/src/lib.rs
  substrate/client/sysinfo/src/sysinfo.rs
  substrate/utils/frame/benchmarking-cli/src/machine/hardware.rs
  substrate/utils/frame/benchmarking-cli/src/machine/mod.rs
  substrate/utils/frame/benchmarking-cli/src/machine/reference_hardware.json
  templates/parachain/node/src/command.rs
  templates/parachain/node/src/service.rs
Labels: T0-node

#5385 GHA Migration - test-misc
  .github/scripts/check-each-crate.py
  .github/workflows/tests-misc.yml
  .github/workflows/tests.yml
  .gitlab-ci.yml
  .gitlab/pipeline/test.yml
Labels: R0-silent

#5148 Github actions coverage
  .github/codecov.yml
  .github/workflows/tests-linux-stable-coverage.yml
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/babe/src/mock.rs
  substrate/frame/grandpa/src/mock.rs
Labels: R0-silent, T10-tests, GHA-coverage

#5533 /cmd followups
  .github/scripts/cmd/cmd.py
  .github/scripts/cmd/test_cmd.py
  .github/workflows/cmd-tests.yml
  .github/workflows/cmd.yml
  .github/workflows/runtimes-matrix.json
  substrate/frame/balances/src/weights.rs
Labels: R0-silent

#5607 minor fixes pipeline
  .github/workflows/tests-misc.yml
  .gitlab-ci.yml
  .gitlab/pipeline/test.yml
Labels: R0-silent

#5592 Introduce `BlockGap`
  prdoc/pr_5592.prdoc
  substrate/client/consensus/babe/src/lib.rs
  substrate/client/db/src/lib.rs
  substrate/client/db/src/utils.rs
  substrate/client/network/sync/src/strategy/chain_sync.rs
  substrate/client/service/src/client/client.rs
  substrate/primitives/blockchain/src/backend.rs
Labels: T0-node

#5381 Update Templates Readme - Github Repo links
  templates/minimal/README.md
  templates/parachain/README.md
  templates/solochain/README.md
Labels: R0-silent

#5598 [CI/Release] Pipeline to create a stable release branch
  .github/scripts/common/lib.sh
  .github/scripts/release/release_lib.sh
  .github/workflows/release-branchoff-stable.yml
Labels: R0-silent

#5606 Fix PVF precompilation for Kusama
  polkadot/node/core/candidate-validation/src/lib.rs
  polkadot/node/core/candidate-validation/src/tests.rs
  prdoc/pr_5606.prdoc
Labels: T0-node, I5-enhancement, T8-polkadot

#5619 [ci] Fix final job for required workflows
  .github/workflows/build-misc.yml
  .github/workflows/check-cargo-check-runtimes.yml
  .github/workflows/check-runtime-migration.yml
  .github/workflows/checks.yml
  .github/workflows/tests-linux-stable.yml
  .github/workflows/tests-misc.yml
Labels: R0-silent

#5615 Update tests-misc.yml
  .github/workflows/tests-misc.yml
Labels: R0-silent

#5632 Fix occasional `alloc` not found error in `format_runtime_string!`
  prdoc/pr_5632.prdoc
  substrate/primitives/runtime/src/lib.rs
  substrate/primitives/runtime/src/runtime_string.rs
Labels: T1-FRAME, A4-needs-backport

#5594 Add debugging info for `StorageWeightReclaim`
  cumulus/primitives/storage-weight-reclaim/src/lib.rs
  prdoc/pr_5594.prdoc
Labels: T2-pallets

#5622 [pallet-revive] remove custom migration framework
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/build.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/migration.rs
  substrate/frame/revive/src/primitives.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/weights.rs
Labels: R0-silent

#5608 [pallet-revive] update generic runtime types
  prdoc/pr_5608.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/build.rs
  substrate/frame/revive/fixtures/contracts/balance.rs
  substrate/frame/revive/fixtures/contracts/call.rs
  substrate/frame/revive/fixtures/contracts/call_return_code.rs
  substrate/frame/revive/fixtures/contracts/call_runtime_and_call.rs
  substrate/frame/revive/fixtures/contracts/call_with_flags_and_value.rs
  substrate/frame/revive/fixtures/contracts/call_with_limit.rs
  substrate/frame/revive/fixtures/contracts/caller_contract.rs
  substrate/frame/revive/fixtures/contracts/chain_extension_temp_storage.rs
  substrate/frame/revive/fixtures/contracts/common/src/lib.rs
  substrate/frame/revive/fixtures/contracts/create_storage_and_call.rs
  substrate/frame/revive/fixtures/contracts/create_storage_and_instantiate.rs
  substrate/frame/revive/fixtures/contracts/create_transient_storage_and_call.rs
  substrate/frame/revive/fixtures/contracts/delegate_call_lib.rs
  substrate/frame/revive/fixtures/contracts/destroy_and_transfer.rs
  substrate/frame/revive/fixtures/contracts/drain.rs
  substrate/frame/revive/fixtures/contracts/event_and_return_on_deploy.rs
  substrate/frame/revive/fixtures/contracts/event_size.rs
  substrate/frame/revive/fixtures/contracts/instantiate_return_code.rs
  substrate/frame/revive/fixtures/contracts/read_only_call.rs
  substrate/frame/revive/fixtures/contracts/recurse.rs
  substrate/frame/revive/fixtures/contracts/self_destruct.rs
  substrate/frame/revive/fixtures/contracts/transfer_return_code.rs
  substrate/frame/revive/src/benchmarking/call_builder.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/migration.rs
  substrate/frame/revive/src/primitives.rs
  substrate/frame/revive/src/storage.rs
  substrate/frame/revive/src/storage/meter.rs
  substrate/frame/revive/src/test_utils/builder.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/mod.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/src/weights.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv32.rs
Labels: R0-silent

#5602 [CI] Remove duplicate jobs
  .github/workflows/checks-quick.yml
  .gitlab/pipeline/check.yml
Labels: R0-silent

#5038 Plumb RPC listener up to caller
  prdoc/pr_5038.prdoc
  substrate/client/rpc-servers/src/lib.rs
  substrate/client/service/src/builder.rs
  substrate/client/service/src/lib.rs
Labels: T0-node

#5613 [backport] Add benchmark for the number of minimum cpu cores (#5127)
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/command.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/common/spec.rs
  polkadot/cli/src/command.rs
  polkadot/node/service/src/lib.rs
  prdoc/pr_5127.prdoc
  substrate/bin/node/cli/src/service.rs
  substrate/client/sysinfo/src/lib.rs
  substrate/client/sysinfo/src/sysinfo.rs
  substrate/utils/frame/benchmarking-cli/src/machine/hardware.rs
  substrate/utils/frame/benchmarking-cli/src/machine/mod.rs
  substrate/utils/frame/benchmarking-cli/src/machine/reference_hardware.json
  templates/parachain/node/src/command.rs
  templates/parachain/node/src/service.rs
Labels: R0-silent

#5644 pallet-utility: Improve weight annotations
  prdoc/pr_5644.prdoc
  substrate/frame/utility/src/lib.rs
Labels: T2-pallets, A4-needs-backport

#5343 Allow to disable gap creation during block import
  prdoc/pr_5343.prdoc
  substrate/client/api/src/backend.rs
  substrate/client/api/src/in_mem.rs
  substrate/client/consensus/common/src/block_import.rs
  substrate/client/db/src/lib.rs
  substrate/client/service/src/client/client.rs
Labels: T0-node

#5648 [Bot] Revive prdoc bot
  .github/scripts/generate-prdoc.py
  .github/workflows/command-prdoc.yml
Labels: R0-silent

#5625 Install prdoc from Parity fork
  .github/workflows/check-prdoc.yml
  docs/contributor/prdoc.md
Labels: R0-silent

#5640 [pallet-revive] move event topics in event's body
  prdoc/pr_5640.prdoc
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/tests.rs
Labels: R0-silent, T7-smart_contracts

#5580 frame pallet macro: fix span for error on wrong returned type.
  prdoc/pr_5580.prdoc
  substrate/frame/support/procedural/src/pallet/expand/call.rs
  substrate/frame/support/procedural/src/pallet/parse/call.rs
  substrate/frame/support/procedural/src/pallet/parse/helper.rs
  substrate/frame/support/test/tests/pallet_ui/call_span_for_error.rs
  substrate/frame/support/test/tests/pallet_ui/call_span_for_error.stderr
Labels: T1-FRAME

#4257 Update `RuntimeVerison` type and use `system_version` to derive extrinsics root `StateVersion` instead of `V0`
  Cargo.lock
  cumulus/client/network/src/tests.rs
  cumulus/client/pov-recovery/src/tests.rs
  cumulus/pallets/parachain-system/src/mock.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/starters/seedling/src/lib.rs
  cumulus/parachains/runtimes/starters/shell/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  cumulus/test/runtime/src/lib.rs
  docs/sdk/src/reference_docs/chain_spec_runtime/src/runtime.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_4257.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/client/block-builder/src/lib.rs
  substrate/client/executor/src/wasm_runtime.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
  substrate/client/rpc/src/state/tests.rs
  substrate/frame/support/test/compile_pass/src/lib.rs
  substrate/frame/system/src/lib.rs
  substrate/frame/system/src/mock.rs
  substrate/frame/system/src/tests.rs
  substrate/primitives/api/src/lib.rs
  substrate/primitives/storage/src/lib.rs
  substrate/primitives/version/proc-macro/Cargo.toml
  substrate/primitives/version/proc-macro/src/decl_runtime_version.rs
  substrate/primitives/version/src/lib.rs
  substrate/test-utils/runtime/src/lib.rs
  templates/minimal/runtime/src/lib.rs
  templates/parachain/runtime/src/lib.rs
  templates/solochain/runtime/src/lib.rs
Labels: T1-FRAME

#5653 [WIP][ci] GHA improvements
  .github/workflows/check-cargo-check-runtimes.yml
  .github/workflows/check-frame-omni-bencher.yml
  .github/workflows/tests-misc.yml
Labels: R0-silent

#5654 [Bot] Use correct token in backport bot
  .github/workflows/command-backport.yml
Labels: R0-silent

#5601 Introduce `RpcParams` in sc-cli
  cumulus/client/cli/src/lib.rs
  prdoc/pr_5601.prdoc
  substrate/client/cli/src/commands/run_cmd.rs
  substrate/client/cli/src/params/rpc_params.rs
Labels: T0-node

#5609 litep2p: Update network backend to v0.7.0
  Cargo.lock
  Cargo.toml
  prdoc/pr_5609.prdoc
  substrate/client/network/src/litep2p/discovery.rs
  substrate/client/network/src/litep2p/mod.rs
  substrate/client/network/src/litep2p/service.rs
  substrate/client/network/src/litep2p/shim/request_response/mod.rs
  substrate/client/network/src/litep2p/shim/request_response/tests.rs
  substrate/client/tracing/src/logging/mod.rs
Labels: T0-node, I5-enhancement, D0-easy

#5661 Add prdoc command to /cmd
  .github/scripts/cmd/cmd.py
  .github/scripts/cmd/test_cmd.py
  .github/scripts/generate-prdoc.py
  .github/scripts/generate-prdoc.requirements.txt
  .github/workflows/check-cargo-check-runtimes.yml
  .github/workflows/check-features.yml
  .github/workflows/check-labels.yml
  .github/workflows/check-licenses.yml
  .github/workflows/check-links.yml
  .github/workflows/check-prdoc.yml
  .github/workflows/cmd-tests.yml
  .github/workflows/cmd.yml
  .github/workflows/publish-check-crates.yml
  docs/contributor/commands-readme.md
  docs/contributor/prdoc.md
Labels: R0-silent

#5664 Send balance when contract doesn't exist
  prdoc/pr_5664.prdoc
  substrate/frame/revive/fixtures/contracts/call_return_code.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/primitives.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/uapi/src/flags.rs
Labels: R0-silent

#5665 [pallet-contracts] Remove riscv support
  Cargo.lock
  prdoc/pr_5665.prdoc
  substrate/frame/contracts/fixtures/Cargo.toml
  substrate/frame/contracts/fixtures/build.rs
  substrate/frame/contracts/fixtures/contracts/common/src/lib.rs
  substrate/frame/contracts/fixtures/src/lib.rs
  substrate/frame/contracts/uapi/Cargo.toml
  substrate/frame/contracts/uapi/src/host.rs
  substrate/frame/contracts/uapi/src/host/riscv32.rs
  substrate/frame/contracts/uapi/src/lib.rs
Labels: T7-smart_contracts

#5670 [CI] Fix parity-publish
  .github/workflows/check-semver.yml
  .github/workflows/publish-check-crates.yml
  .github/workflows/publish-claim-crates.yml
Labels: A1-insubstantial, R0-silent

#5627 [Staking] Propagate actual system error while staking::bond
  substrate/frame/staking/src/pallet/mod.rs
Labels: R0-silent, T2-pallets

#4851 Deprecation info support in RuntimeMetadataIR
  prdoc/pr_4851.prdoc
  substrate/frame/support/procedural/examples/proc_main/inject_runtime_type.rs
  substrate/frame/support/procedural/examples/proc_main/runtime.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/metadata.rs
  substrate/frame/support/procedural/src/construct_runtime/parse.rs
  substrate/frame/support/procedural/src/deprecation.rs
  substrate/frame/support/procedural/src/lib.rs
  substrate/frame/support/procedural/src/pallet/expand/call.rs
  substrate/frame/support/procedural/src/pallet/expand/constants.rs
  substrate/frame/support/procedural/src/pallet/expand/error.rs
  substrate/frame/support/procedural/src/pallet/expand/event.rs
  substrate/frame/support/procedural/src/pallet/expand/pallet_struct.rs
  substrate/frame/support/procedural/src/pallet/expand/storage.rs
  substrate/frame/support/procedural/src/pallet/parse/call.rs
  substrate/frame/support/procedural/src/pallet/parse/config.rs
  substrate/frame/support/procedural/src/pallet/parse/error.rs
  substrate/frame/support/procedural/src/pallet/parse/event.rs
  substrate/frame/support/procedural/src/pallet/parse/extra_constants.rs
  substrate/frame/support/procedural/src/pallet/parse/mod.rs
  substrate/frame/support/procedural/src/pallet/parse/storage.rs
  substrate/frame/support/procedural/src/runtime/parse/mod.rs
  substrate/frame/support/procedural/src/runtime/parse/pallet.rs
  substrate/frame/support/src/lib.rs
  substrate/frame/support/src/storage/generator/map.rs
  substrate/frame/support/src/storage/types/counted_map.rs
  substrate/frame/support/src/storage/types/counted_nmap.rs
  substrate/frame/support/src/storage/types/double_map.rs
  substrate/frame/support/src/storage/types/map.rs
  substrate/frame/support/src/storage/types/mod.rs
  substrate/frame/support/src/storage/types/nmap.rs
  substrate/frame/support/src/storage/types/value.rs
  substrate/frame/support/src/tests/mod.rs
  substrate/frame/support/test/tests/construct_runtime_ui/undefined_event_part.stderr
  substrate/frame/support/test/tests/enum_deprecation.rs
  substrate/frame/support/test/tests/instance.rs
  substrate/frame/support/test/tests/pallet.rs
  substrate/frame/support/test/tests/runtime_metadata.rs
  substrate/primitives/api/proc-macro/src/impl_runtime_apis.rs
  substrate/primitives/api/proc-macro/src/runtime_metadata.rs
  substrate/primitives/api/proc-macro/src/utils.rs
  substrate/primitives/api/src/lib.rs
  substrate/primitives/api/test/tests/ui/deprecation_info.rs
  substrate/primitives/api/test/tests/ui/deprecation_info.stderr
  substrate/primitives/metadata-ir/src/types.rs
Labels: R0-silent, I5-enhancement, D1-medium

#4846 [4 / 5] Make approval-voting runnable on a worker thread
  polkadot/cli/src/command.rs
  polkadot/node/core/approval-voting/Cargo.toml
  polkadot/node/core/approval-voting/src/import.rs
  polkadot/node/core/approval-voting/src/lib.rs
  polkadot/node/core/approval-voting/src/tests.rs
  polkadot/node/service/src/lib.rs
  polkadot/node/service/src/overseer.rs
  polkadot/node/subsystem-bench/src/lib/approval/mod.rs
  prdoc/pr_4846.prdoc
Labels: T0-node, T8-polkadot

#5691 [stable2409] Backport #5678
  prdoc/pr_5678.prdoc
  substrate/client/rpc-servers/src/utils.rs
Labels: A3-backport

#5667 Fix subsystem bench publishing
  .github/workflows/subsystem-benchmarks.yml
Labels: R0-silent

#2704 Add emulated tests for the Coretime Interface calls to ensure sufficient weights
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/chains/parachains/coretime/coretime-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/parachains/coretime/coretime-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-rococo/src/tests/coretime_interface.rs
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-rococo/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-westend/src/tests/coretime_interface.rs
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-westend/src/tests/mod.rs
Labels: R0-silent, T10-tests, T14-system_parachains

#5509 Add `pallet_proxy` to People Chain and Coretime Chain testnet runtimes.
  Cargo.lock
  cumulus/parachains/runtimes/coretime/coretime-rococo/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_proxy.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/pallet_proxy.rs
  cumulus/parachains/runtimes/people/people-rococo/Cargo.toml
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/mod.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/pallet_proxy.rs
  cumulus/parachains/runtimes/people/people-westend/Cargo.toml
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/mod.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/pallet_proxy.rs
  prdoc/pr_5509.prdoc
Labels: T14-system_parachains

#5684 [pallet-revive] fix xcm tests
  Cargo.lock
  prdoc/pr_5684.prdoc
  substrate/frame/revive/fixtures/Cargo.toml
  substrate/frame/revive/fixtures/src/lib.rs
  substrate/frame/revive/mock-network/Cargo.toml
  substrate/frame/revive/mock-network/src/tests.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/uapi/src/host/riscv32.rs
  umbrella/Cargo.toml
Labels: R0-silent, T7-smart_contracts

#5675 [pallet-revive] Add balance_of syscyall for fetching foreign balances
  prdoc/pr_5675.prdoc
  substrate/frame/revive/fixtures/contracts/balance_of.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/src/weights.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv32.rs
Labels: R0-silent

#5696 revive: Get rid of no longer needed trait bound
  substrate/frame/revive/src/benchmarking/call_builder.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/storage.rs
  substrate/frame/revive/src/storage/meter.rs
  substrate/frame/revive/src/test_utils/builder.rs
  substrate/frame/revive/src/wasm/mod.rs
Labels: R0-silent

#5690 [ci] Move check each crate osx from gitlab to github
  .github/actions/set-up-mac/README.md
  .github/actions/set-up-mac/action.yml
  .github/workflows/tests-misc.yml
Labels: R0-silent

#5695 pallet-migrations: fix index access for singluar migrations
  prdoc/pr_5695.prdoc
  substrate/frame/migrations/src/lib.rs
  substrate/frame/migrations/src/tests.rs
  substrate/frame/support/src/migrations.rs
Labels: T1-FRAME

#5546 Transfer Polkadot-native assets to Ethereum
  Cargo.lock
  bridges/snowbridge/pallets/inbound-queue/src/lib.rs
  bridges/snowbridge/pallets/inbound-queue/src/mock.rs
  bridges/snowbridge/pallets/outbound-queue/src/mock.rs
  bridges/snowbridge/pallets/system/src/benchmarking.rs
  bridges/snowbridge/pallets/system/src/lib.rs
  bridges/snowbridge/pallets/system/src/mock.rs
  bridges/snowbridge/pallets/system/src/tests.rs
  bridges/snowbridge/pallets/system/src/weights.rs
  bridges/snowbridge/primitives/core/Cargo.toml
  bridges/snowbridge/primitives/core/src/lib.rs
  bridges/snowbridge/primitives/core/src/location.rs
  bridges/snowbridge/primitives/core/src/outbound.rs
  bridges/snowbridge/primitives/router/src/inbound/mod.rs
  bridges/snowbridge/primitives/router/src/inbound/tests.rs
  bridges/snowbridge/primitives/router/src/outbound/mod.rs
  bridges/snowbridge/primitives/router/src/outbound/tests.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-westend/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/common/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_ethereum_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/snowbridge_pallet_system.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/bridge_to_ethereum_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/snowbridge_pallet_system.rs
  cumulus/parachains/runtimes/constants/src/rococo.rs
  cumulus/parachains/runtimes/constants/src/westend.rs
  prdoc/pr_5546.prdoc
Labels: T15-bridges

#5681 [Bot] Fix backport bot
  .github/workflows/command-backport.yml
Labels: R0-silent

#3049 Fix treasury benchmarks when no SpendOrigin
  prdoc/pr_3049.prdoc
  substrate/frame/treasury/src/benchmarking.rs
  substrate/frame/treasury/src/tests.rs
Labels: T2-pallets, A4-needs-backport

#5682 Introduces `VerifyExistenceProof` trait
  Cargo.lock
  prdoc/pr_5682.prdoc
  substrate/frame/support/Cargo.toml
  substrate/frame/support/src/traits.rs
  substrate/frame/support/src/traits/proving.rs
  substrate/primitives/runtime/src/proving_trie.rs
  substrate/utils/binary-merkle-tree/Cargo.toml
  substrate/utils/binary-merkle-tree/src/lib.rs
Labels: T1-FRAME

#5687 Asset Hub: auto incremented asset id for trust backed assets
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_5687.prdoc
Labels: T4-runtime_API

#5688 fix rococo-dev bench
  polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs
  prdoc/pr_5688.prdoc
Labels: R0-silent

#5692 Preflight workflow
  .github/workflows/build-misc.yml
  .github/workflows/build-publish-images.yml
  .github/workflows/check-cargo-check-runtimes.yml
  .github/workflows/check-frame-omni-bencher.yml
  .github/workflows/check-runtime-migration.yml
  .github/workflows/checks-quick.yml
  .github/workflows/checks.yml
  .github/workflows/command-prdoc.yml
  .github/workflows/docs.yml
  .github/workflows/reusable-check-changed-files.yml
  .github/workflows/reusable-preflight.yml
  .github/workflows/subsystem-benchmarks.yml
  .github/workflows/tests-linux-stable-coverage.yml
  .github/workflows/tests-linux-stable.yml
  .github/workflows/tests-misc.yml
  .github/workflows/tests.yml
Labels: R0-silent

#5727 [stable2409]: Backport #5688
  polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs
  prdoc/pr_5688.prdoc
Labels: A3-backport

#5342 add zombienet-sdk test to parachain-template
  .gitlab/pipeline/build.yml
  .gitlab/pipeline/zombienet.yml
  .gitlab/pipeline/zombienet/parachain-template.yml
  Cargo.lock
  Cargo.toml
  templates/zombienet/Cargo.toml
  templates/zombienet/tests/smoke.rs
Labels: R0-silent, T10-tests

#5666 Syncing strategy refactoring (part 2)
  cumulus/client/service/src/lib.rs
  polkadot/node/service/src/lib.rs
  prdoc/pr_5666.prdoc
  substrate/bin/node/cli/src/service.rs
  substrate/client/network/sync/src/engine.rs
  substrate/client/network/sync/src/strategy.rs
  substrate/client/network/sync/src/strategy/chain_sync.rs
  substrate/client/network/sync/src/strategy/chain_sync/test.rs
  substrate/client/network/sync/src/strategy/state.rs
  substrate/client/network/sync/src/strategy/warp.rs
  substrate/client/network/test/src/lib.rs
  substrate/client/network/test/src/service.rs
  substrate/client/service/src/builder.rs
  substrate/client/service/src/lib.rs
  templates/minimal/node/src/service.rs
  templates/solochain/node/src/service.rs
Labels: T0-node

#5713 pallet-treasury: Improve `remove_approval` benchmark
  prdoc/pr_5713.prdoc
  substrate/frame/treasury/src/benchmarking.rs
Labels: T2-pallets, A4-needs-backport

#5584 Adds support for generics in`derive-impl`
  substrate/frame/support/procedural/src/derive_impl.rs
  substrate/frame/support/procedural/src/lib.rs
Labels: R0-silent

#4883 add `coretime` test using `zombienet-sdk`
  .cargo/config.toml
  .github/scripts/deny-git-deps.py
  .gitlab/pipeline/build.yml
  .gitlab/pipeline/zombienet.yml
  .gitlab/pipeline/zombienet/polkadot.yml
  Cargo.lock
  Cargo.toml
  polkadot/zombienet-sdk-tests/Cargo.toml
  polkadot/zombienet-sdk-tests/build.rs
  polkadot/zombienet-sdk-tests/metadata-files/.gitkeep
  polkadot/zombienet-sdk-tests/src/lib.rs
  polkadot/zombienet-sdk-tests/tests/lib.rs
  polkadot/zombienet-sdk-tests/tests/smoke/coretime_revenue.rs
  polkadot/zombienet-sdk-tests/tests/smoke/mod.rs
Labels: R0-silent, T10-tests

#5743 [pallet-revive] write sandbox output according to the provided output buffer length
  prdoc/pr_5743.prdoc
  substrate/frame/revive/fixtures/contracts/call_diverging_out_len.rs
  substrate/frame/revive/fixtures/contracts/create1_with_value.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/runtime.rs
Labels: R0-silent, T7-smart_contracts

#5752 [ci] Remove cargo check osx from gitlab
  .github/workflows/tests-misc.yml
  .gitlab-ci.yml
  .gitlab/pipeline/test.yml
Labels: R0-silent

#4974 Remove libp2p dependency from sc-network-sync
  Cargo.lock
  prdoc/pr_4974.prdoc
  substrate/client/network/src/request_responses.rs
  substrate/client/network/sync/Cargo.toml
  substrate/client/network/sync/src/engine.rs
Labels: T0-node

#5748 Add timeout for script/after_script and debug
  .gitlab/pipeline/zombienet/parachain-template.yml
Labels: R0-silent, T10-tests

#5726 revive: Limit the amount of static memory a contract can use
  Cargo.lock
  prdoc/pr_5726.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/fixtures/Cargo.toml
  substrate/frame/revive/fixtures/build/Cargo.toml
  substrate/frame/revive/fixtures/contracts/oom_ro.rs
  substrate/frame/revive/fixtures/contracts/oom_rw_included.rs
  substrate/frame/revive/fixtures/contracts/oom_rw_trailing.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/limits.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/mod.rs
  substrate/frame/revive/uapi/Cargo.toml
Labels: R0-silent

#5760 make update-ui-test executable
  scripts/update-ui-tests.sh
Labels: R0-silent

#5712 [xcm-emulator] Better logs for message execution and processing
  Cargo.lock
  cumulus/xcm/xcm-emulator/Cargo.toml
  cumulus/xcm/xcm-emulator/src/lib.rs
  prdoc/pr_5712.prdoc
Labels: T6-XCM, A4-needs-backport

#5762 chore: fast return for invalid request of node health
  prdoc/pr_5762.prdoc
  substrate/client/rpc-servers/src/middleware/node_health.rs
Labels: T0-node

#5753 Use maximum allowed response size for request/response protocols
  polkadot/node/network/protocol/src/request_response/mod.rs
  prdoc/pr_5753.prdoc
  substrate/client/network/light/src/light_client_requests.rs
  substrate/client/network/src/bitswap/mod.rs
  substrate/client/network/src/lib.rs
  substrate/client/network/src/protocol.rs
  substrate/client/network/sync/src/block_request_handler.rs
  substrate/client/network/sync/src/state_request_handler.rs
  substrate/client/network/sync/src/warp_request_handler.rs
  substrate/client/network/transactions/src/config.rs
Labels: I9-optimisation, T8-polkadot

#5572 cumulus/minimal-node: added prometheus metrics for the RPC client
  Cargo.lock
  cumulus/client/relay-chain-minimal-node/src/lib.rs
  cumulus/client/relay-chain-rpc-interface/Cargo.toml
  cumulus/client/relay-chain-rpc-interface/src/lib.rs
  cumulus/client/relay-chain-rpc-interface/src/metrics.rs
  cumulus/client/relay-chain-rpc-interface/src/rpc_client.rs
  cumulus/client/service/src/lib.rs
  cumulus/test/service/Cargo.toml
  cumulus/test/service/src/lib.rs
  cumulus/test/service/src/main.rs
  prdoc/pr_5572.prdoc
  substrate/utils/prometheus/src/lib.rs
Labels: T9-cumulus

#5747 Add Snowbridge initialize migration on Westend
  Cargo.lock
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  prdoc/pr_5747.prdoc
Labels: T15-bridges, A4-needs-backport

#5521 Allow to call arbitrary runtime apis using RelayChainInterface
  cumulus/client/consensus/common/src/tests.rs
  cumulus/client/network/src/tests.rs
  cumulus/client/pov-recovery/src/tests.rs
  cumulus/client/relay-chain-inprocess-interface/src/lib.rs
  cumulus/client/relay-chain-interface/src/lib.rs
  cumulus/client/relay-chain-rpc-interface/src/lib.rs
  cumulus/client/relay-chain-rpc-interface/src/rpc_client.rs
  prdoc/pr_5521.prdoc
Labels: T0-node

#5780 Update README.md
  README.md
Labels: R0-silent

#5796 Fix RPC relay chain interface
  cumulus/client/relay-chain-rpc-interface/src/rpc_client.rs
  prdoc/pr_5796.prdoc
Labels: R0-silent

#5655 [benchmarking] Reset to genesis storage after each run
  prdoc/pr_5655.prdoc
  substrate/bin/node/cli/tests/benchmark_pallet_works.rs
  substrate/frame/benchmarking/pov/src/benchmarking.rs
  substrate/utils/frame/benchmarking-cli/src/pallet/command.rs
  substrate/utils/frame/benchmarking-cli/src/pallet/mod.rs
  substrate/utils/frame/benchmarking-cli/src/pallet/types.rs
  substrate/utils/frame/benchmarking-cli/src/pallet/writer.rs
Labels: T1-FRAME, A4-needs-backport

#5372 elastic scaling: add core selector to cumulus
  Cargo.lock
  cumulus/client/consensus/aura/Cargo.toml
  cumulus/client/consensus/aura/src/collators/lookahead.rs
  cumulus/client/consensus/aura/src/collators/mod.rs
  cumulus/client/consensus/aura/src/collators/slot_based/block_builder_task.rs
  cumulus/client/consensus/aura/src/collators/slot_based/mod.rs
  cumulus/client/consensus/common/src/tests.rs
  cumulus/client/network/src/tests.rs
  cumulus/client/pov-recovery/src/tests.rs
  cumulus/client/relay-chain-inprocess-interface/src/lib.rs
  cumulus/client/relay-chain-interface/src/lib.rs
  cumulus/client/relay-chain-minimal-node/src/blockchain_rpc_client.rs
  cumulus/client/relay-chain-rpc-interface/src/lib.rs
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/parachain-system/src/mock.rs
  cumulus/pallets/xcmp-queue/src/mock.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/cumulus_pallet_parachain_system.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/starters/seedling/src/lib.rs
  cumulus/parachains/runtimes/starters/shell/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/common/mod.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/fake_runtime_api/utils.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/service.rs
  cumulus/primitives/core/src/lib.rs
  cumulus/test/runtime/src/lib.rs
  cumulus/test/service/src/lib.rs
  docs/sdk/src/polkadot_sdk/cumulus.rs
  prdoc/pr_5372.prdoc
  templates/parachain/runtime/src/configs/mod.rs
Labels: I5-enhancement, T9-cumulus

#5768 chore: export NodeHealthProxyLayer
  prdoc/pr_5768.prdoc
  substrate/client/rpc-servers/src/lib.rs
Labels: T0-node

#5807 [pallet-revive] Add chain ID to config an runtime API
  prdoc/pr_5807.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/revive/fixtures/contracts/chain_id.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv32.rs
Labels: R0-silent, T7-smart_contracts

#5745 Implement try_append for StorageNMap
  prdoc/pr_5745.prdoc
  substrate/frame/support/src/storage/mod.rs
  substrate/frame/support/src/storage/types/nmap.rs
Labels: T1-FRAME

#5772 update solochain to use #[runtime]
  prdoc/1.9.0/pr_1378.prdoc
  templates/parachain/pallets/template/src/mock.rs
  templates/parachain/pallets/template/src/tests.rs
  templates/parachain/pallets/template/src/weights.rs
  templates/solochain/README.md
  templates/solochain/pallets/template/src/mock.rs
  templates/solochain/pallets/template/src/tests.rs
  templates/solochain/pallets/template/src/weights.rs
  templates/solochain/runtime/src/benchmarks.rs
  templates/solochain/runtime/src/lib.rs
Labels: R0-silent, C1-mentor, I4-refactor

#5563 snowbridge: improve destination fee handling to avoid trapping fees dust
  bridges/snowbridge/pallets/inbound-queue/src/test.rs
  bridges/snowbridge/primitives/router/src/inbound/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  prdoc/pr_5563.prdoc
Labels: T15-bridges, A4-needs-backport

#5671 Fix border condition in Snowbridge free consensus Updates
  bridges/snowbridge/pallets/ethereum-client/src/lib.rs
  bridges/snowbridge/pallets/ethereum-client/src/mock.rs
  bridges/snowbridge/pallets/ethereum-client/src/tests.rs
  bridges/snowbridge/pallets/ethereum-client/tests/fixtures/initial-checkpoint.json
  bridges/snowbridge/pallets/ethereum-client/tests/fixtures/sync-committee-update-period-0-newer.json
  bridges/snowbridge/pallets/ethereum-client/tests/fixtures/sync-committee-update-period-0-older.json
  bridges/snowbridge/pallets/ethereum-client/tests/fixtures/sync-committee-update-period-0.json
  prdoc/pr_5671.prdoc
Labels: T15-bridges, A4-needs-backport

#5814 [stable2409] Backport 5509
  Cargo.lock
  cumulus/parachains/runtimes/coretime/coretime-rococo/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_proxy.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/pallet_proxy.rs
  cumulus/parachains/runtimes/people/people-rococo/Cargo.toml
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/mod.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/pallet_proxy.rs
  cumulus/parachains/runtimes/people/people-westend/Cargo.toml
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/mod.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/pallet_proxy.rs
  prdoc/pr_5509.prdoc
Labels: A3-backport

#5821 Fix parachain-template-test
  Cargo.lock
  Cargo.toml
  polkadot/zombienet-sdk-tests/Cargo.toml
  templates/zombienet/Cargo.toml
Labels: R0-silent, T10-tests

#4251 MBM `try-runtime` support
  .gitlab/pipeline/test.yml
  Cargo.lock
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  prdoc/pr_4251.prdoc
  substrate/frame/examples/multi-block-migrations/src/migrations/v1/mod.rs
  substrate/frame/migrations/Cargo.toml
  substrate/frame/migrations/src/lib.rs
  substrate/frame/migrations/src/mock_helpers.rs
  substrate/frame/migrations/src/tests.rs
  substrate/frame/support/src/migrations.rs
  substrate/frame/support/src/traits/try_runtime/mod.rs
Labels: T1-FRAME

#5660 xcm-executor: validate destinations for ReserveWithdraw and Teleport transfers
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/hybrid_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/xcm-builder/tests/scenarios.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  polkadot/xcm/xcm-simulator/example/src/relay_chain/xcm_config/mod.rs
  polkadot/xcm/xcm-simulator/example/src/relay_chain/xcm_config/teleporter.rs
  prdoc/pr_5660.prdoc
Labels: T6-XCM, A4-needs-backport

#5779 [pallet-revive] last call return data API
  prdoc/pr_5779.prdoc
  substrate/frame/revive/fixtures/contracts/return_data_api.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv32.rs
Labels: R0-silent, T7-smart_contracts

#5824 chore: bump runtime api version to v11
  polkadot/runtime/parachains/src/runtime_api_impl/mod.rs
  polkadot/runtime/parachains/src/runtime_api_impl/v11.rs
  polkadot/runtime/parachains/src/runtime_api_impl/vstaging.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_5824.prdoc
Labels: T8-polkadot

#5843 [ci] Disable cargo-hfuzz, disable cargo-doc
  .github/workflows/check-runtime-migration.yml
  .github/workflows/checks.yml
  .github/workflows/docs.yml
  .github/workflows/tests-linux-stable.yml
  .github/workflows/tests-misc.yml
  .github/workflows/tests.yml
  .gitlab/pipeline/test.yml
Labels: R0-silent

#5834 bump zombienet version `v1.3.110`
  .gitlab/pipeline/zombienet.yml
Labels: R0-silent, T10-tests

#5830 Remove jaeger from approval-voting and approval-distribution
  Cargo.lock
  polkadot/node/core/approval-voting/Cargo.toml
  polkadot/node/core/approval-voting/benches/approval-voting-regression-bench.rs
  polkadot/node/core/approval-voting/src/import.rs
  polkadot/node/core/approval-voting/src/lib.rs
  polkadot/node/core/approval-voting/src/tests.rs
  polkadot/node/network/approval-distribution/Cargo.toml
  polkadot/node/network/approval-distribution/src/lib.rs
  prdoc/pr_5830.prdoc
Labels: R0-silent

#5851 Disable flaky tests reported in 5848/5844
  .gitlab/pipeline/zombienet/polkadot.yml
Labels: R0-silent, T10-tests

#5853 make frame omni bencher to install from path
  .github/workflows/cmd.yml
  .github/workflows/runtimes-matrix.json
Labels: R0-silent

#5839 Remove fixed workaround in `impl_runtime_apis`
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/command.rs
  prdoc/pr_5839.prdoc
  substrate/frame/support/procedural/src/runtime/expand/mod.rs
  substrate/primitives/api/proc-macro/src/impl_runtime_apis.rs
  substrate/primitives/api/proc-macro/src/utils.rs
Labels: T1-FRAME

#5838 substrate/utils: enable wasm builder diagnostics propagation
  Cargo.lock
  Cargo.toml
  prdoc/pr_5838.prdoc
  substrate/utils/wasm-builder/Cargo.toml
  substrate/utils/wasm-builder/src/lib.rs
  substrate/utils/wasm-builder/src/wasm_project.rs
Labels: I5-enhancement

#5829 Update runtimes-matrix.json
  .github/workflows/runtimes-matrix.json
Labels: A1-insubstantial, R0-silent

#5811 Clarify firing of `import_notification_stream` in doc comment
  prdoc/pr_5811.prdoc
  substrate/client/api/src/client.rs
Labels: T11-documentation

#5756 Improve APIs for Tries in Runtime
  Cargo.lock
  prdoc/pr_5756.prdoc
  substrate/frame/support/src/traits/proving.rs
  substrate/primitives/runtime/Cargo.toml
  substrate/primitives/runtime/src/proving_trie.rs
  substrate/primitives/runtime/src/proving_trie/base16.rs
  substrate/primitives/runtime/src/proving_trie/base2.rs
  substrate/primitives/runtime/src/proving_trie/mod.rs
Labels: T1-FRAME

#5860 [ci] Run subsystem-benchmarks on large runners
  .github/workflows/subsystem-benchmarks.yml
Labels: R0-silent

#5716 Replace lazy_static with LazyLock
  Cargo.lock
  Cargo.toml
  cumulus/pallets/parachain-system/Cargo.toml
  cumulus/pallets/parachain-system/src/tests.rs
  cumulus/xcm/xcm-emulator/Cargo.toml
  cumulus/xcm/xcm-emulator/src/lib.rs
  polkadot/node/jaeger/Cargo.toml
  polkadot/node/jaeger/src/lib.rs
  polkadot/node/network/dispute-distribution/Cargo.toml
  polkadot/node/network/dispute-distribution/src/tests/mock.rs
  polkadot/node/network/gossip-support/Cargo.toml
  polkadot/node/network/gossip-support/src/tests.rs
  polkadot/node/primitives/src/lib.rs
  polkadot/node/subsystem-util/Cargo.toml
  polkadot/node/zombienet-backchannel/Cargo.toml
  polkadot/node/zombienet-backchannel/src/lib.rs
  prdoc/pr_5716.prdoc
  substrate/bin/node/bench/Cargo.toml
  substrate/bin/node/bench/src/trie.rs
  substrate/client/offchain/Cargo.toml
  substrate/client/offchain/src/api/http.rs
  substrate/client/tracing/Cargo.toml
  substrate/client/utils/Cargo.toml
  substrate/client/utils/src/metrics.rs
  substrate/primitives/consensus/beefy/Cargo.toml
  substrate/primitives/consensus/beefy/src/test_utils.rs
  substrate/primitives/core/Cargo.toml
  substrate/primitives/core/fuzz/Cargo.toml
  substrate/primitives/core/fuzz/fuzz_targets/fuzz_address_uri.rs
  substrate/primitives/core/src/address_uri.rs
  substrate/primitives/panic-handler/Cargo.toml
  substrate/primitives/panic-handler/src/lib.rs
  substrate/primitives/trie/Cargo.toml
  substrate/primitives/trie/src/cache/shared_cache.rs
  substrate/utils/frame/benchmarking-cli/Cargo.toml
  substrate/utils/frame/benchmarking-cli/src/machine/hardware.rs
Labels: T0-node
