Repository paritytech/polkadot-sdk, pull requests merged in 2024-06, with the labels that each got.

#4643 Better error for missing index in CRV2
  substrate/frame/support/procedural/src/runtime/parse/mod.rs
  substrate/frame/support/test/tests/runtime_ui/missing_pallet_index.rs
  substrate/frame/support/test/tests/runtime_ui/missing_pallet_index.stderr
Labels: R0-silent, T1-FRAME

#4537 [Pools] Refactors and runtime apis for DelegateStake
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_4537.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/delegated-staking/src/impls.rs
  substrate/frame/delegated-staking/src/lib.rs
  substrate/frame/delegated-staking/src/mock.rs
  substrate/frame/delegated-staking/src/tests.rs
  substrate/frame/delegated-staking/src/types.rs
  substrate/frame/nomination-pools/benchmarking/src/inner.rs
  substrate/frame/nomination-pools/runtime-api/src/lib.rs
  substrate/frame/nomination-pools/src/adapter.rs
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/nomination-pools/src/migration.rs
  substrate/frame/nomination-pools/src/tests.rs
  substrate/frame/nomination-pools/test-delegate-stake/src/lib.rs
  substrate/frame/nomination-pools/test-delegate-stake/src/mock.rs
  substrate/primitives/staking/src/lib.rs
Labels: T2-pallets, T4-runtime_API

#4645 make all storage items in parachain-system public
  cumulus/pallets/parachain-system/src/lib.rs
  prdoc/pr_4645.prdoc
Labels: T2-pallets

#4655 Add chain-spec-builder docker image
  .github/workflows/release-50_publish-docker.yml
  docker/dockerfiles/binary_injected.Dockerfile
  docker/scripts/chain-spec-builder/build-injected.sh
  docker/scripts/chain-spec-builder/test-build.sh
Labels: R0-silent

#4637 Add Dockerfiles to the templates
  templates/minimal/.dockerignore
  templates/minimal/Dockerfile
  templates/parachain/.dockerignore
  templates/parachain/Dockerfile
  templates/solochain/.dockerignore
  templates/solochain/Dockerfile
Labels: R0-silent

#4670 Fix umbrella CI check and fix the C&P message
  .github/workflows/checks-quick.yml
  Cargo.lock
  umbrella/Cargo.toml
  umbrella/src/lib.rs
Labels: R0-silent

#4676 [ci] Delete unused flow
  .github/workflows/release-build-and-attach-runtimes.yml
Labels: R0-silent

#4656 Backport broker new price adapter (#4521) without extra changes
  Cargo.lock
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/coretime.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/broker/Cargo.toml
  substrate/frame/broker/src/adapt_price.rs
  substrate/frame/broker/src/benchmarking.rs
  substrate/frame/broker/src/dispatchable_impls.rs
  substrate/frame/broker/src/lib.rs
  substrate/frame/broker/src/mock.rs
  substrate/frame/broker/src/tests.rs
  substrate/frame/broker/src/tick_impls.rs
  substrate/frame/broker/src/utility_impls.rs
  substrate/frame/broker/src/weights.rs
Labels: R0-silent, A3-backport, T2-pallets

#4679 Fix code broken by merge
  substrate/frame/broker/src/tests.rs
  substrate/frame/broker/src/tick_impls.rs
Labels: R0-silent, T2-pallets

#4688 Format the README.md files
  .github/workflows/checks-quick.yml
  templates/minimal/README.md
  templates/minimal/node/README.md
  templates/minimal/pallets/README.md
  templates/minimal/runtime/README.md
Labels: R0-silent

#4418 Add READ_ONLY flag to contract call function
  prdoc/pr_4418.prdoc
  substrate/frame/contracts/fixtures/contracts/call_with_flags_and_value.rs
  substrate/frame/contracts/fixtures/contracts/read_only_call.rs
  substrate/frame/contracts/proc-macro/src/lib.rs
  substrate/frame/contracts/src/chain_extension.rs
  substrate/frame/contracts/src/exec.rs
  substrate/frame/contracts/src/lib.rs
  substrate/frame/contracts/src/tests.rs
  substrate/frame/contracts/src/wasm/mod.rs
  substrate/frame/contracts/src/wasm/runtime.rs
  substrate/frame/contracts/src/weights.rs
  substrate/frame/contracts/uapi/src/flags.rs
Labels: T7-smart_contracts

#4683 Forward put_record requests to authorithy-discovery
  substrate/client/authority-discovery/src/error.rs
  substrate/client/authority-discovery/src/worker.rs
  substrate/client/authority-discovery/src/worker/tests.rs
  substrate/client/network/src/behaviour.rs
  substrate/client/network/src/discovery.rs
  substrate/client/network/src/event.rs
  substrate/client/network/src/litep2p/service.rs
  substrate/client/network/src/service.rs
  substrate/client/network/src/service/traits.rs
Labels: R0-silent

#4669 Add `codeSubstitutes` to rococo parachains
  cumulus/parachains/chain-specs/asset-hub-rococo.json
  cumulus/parachains/chain-specs/bridge-hub-rococo.json
  cumulus/parachains/chain-specs/contracts-rococo.json
  cumulus/parachains/chain-specs/coretime-rococo.json
  cumulus/parachains/chain-specs/people-rococo.json
Labels: R0-silent, T0-node, T14-system_parachains

#4672 Use `parachain_info` in cumulus-test-runtime
  Cargo.lock
  cumulus/test/runtime/Cargo.toml
  cumulus/test/runtime/src/lib.rs
  cumulus/test/runtime/src/test_pallet.rs
  cumulus/test/service/src/chain_spec.rs
Labels: R0-silent

#4682 Upgrade libp2p upgrade PR on latest master
  Cargo.lock
  polkadot/node/network/bridge/src/validator_discovery.rs
  substrate/client/authority-discovery/Cargo.toml
  substrate/client/authority-discovery/src/service.rs
  substrate/client/authority-discovery/src/tests.rs
  substrate/client/authority-discovery/src/worker.rs
  substrate/client/authority-discovery/src/worker/addr_cache.rs
  substrate/client/authority-discovery/src/worker/tests.rs
  substrate/client/mixnet/Cargo.toml
  substrate/client/mixnet/src/sync_with_runtime.rs
  substrate/client/network-gossip/Cargo.toml
  substrate/client/network-gossip/src/bridge.rs
  substrate/client/network-gossip/src/lib.rs
  substrate/client/network-gossip/src/state_machine.rs
  substrate/client/network/src/behaviour.rs
  substrate/client/network/src/config.rs
  substrate/client/network/src/discovery.rs
  substrate/client/network/src/litep2p/service.rs
  substrate/client/network/src/protocol/notifications/handler.rs
  substrate/client/network/src/protocol/notifications/upgrade.rs
  substrate/client/network/src/protocol/notifications/upgrade/notifications.rs
  substrate/client/network/src/service.rs
  substrate/client/network/statement/src/lib.rs
  substrate/client/network/transactions/src/lib.rs
  substrate/client/network/types/Cargo.toml
  substrate/client/network/types/src/multiaddr.rs
  substrate/client/network/types/src/multiaddr/protocol.rs
  substrate/client/network/types/src/multihash.rs
  substrate/client/service/src/lib.rs
Labels: R0-silent, T0-node

#4678 `chain-spec`/presets reference docs added
  Cargo.lock
  Cargo.toml
  docs/sdk/Cargo.toml
  docs/sdk/src/reference_docs/chain_spec_genesis.rs
  docs/sdk/src/reference_docs/chain_spec_runtime/Cargo.toml
  docs/sdk/src/reference_docs/chain_spec_runtime/build.rs
  docs/sdk/src/reference_docs/chain_spec_runtime/src/lib.rs
  docs/sdk/src/reference_docs/chain_spec_runtime/src/pallets.rs
  docs/sdk/src/reference_docs/chain_spec_runtime/src/presets.rs
  docs/sdk/src/reference_docs/chain_spec_runtime/src/runtime.rs
  docs/sdk/src/reference_docs/chain_spec_runtime/tests/chain_spec_builder_tests.rs
  docs/sdk/src/reference_docs/mod.rs
  substrate/bin/utils/chain-spec-builder/Cargo.toml
  substrate/bin/utils/chain-spec-builder/bin/main.rs
  substrate/client/chain-spec/src/lib.rs
Labels: R0-silent, T11-documentation

#4646 [Identity] Remove double encoding username signature payload
  Cargo.lock
  prdoc/pr_4646.prdoc
  substrate/frame/identity/Cargo.toml
  substrate/frame/identity/src/benchmarking.rs
  substrate/frame/identity/src/lib.rs
  substrate/frame/identity/src/tests.rs
Labels: T2-pallets

#4638 Update the `polkadot_builder` Dockerfile
  docker/dockerfiles/polkadot/polkadot_builder.Dockerfile
Labels: R0-silent

#4698 Upgrade libp2p to 0.52.4
  Cargo.lock
  substrate/client/authority-discovery/Cargo.toml
  substrate/client/network/Cargo.toml
  substrate/client/network/src/discovery.rs
  substrate/client/network/src/protocol/notifications/tests.rs
  substrate/client/network/src/service.rs
  substrate/client/network/src/transport.rs
  substrate/client/network/sync/Cargo.toml
  substrate/client/network/test/Cargo.toml
  substrate/client/network/types/Cargo.toml
  substrate/client/offchain/Cargo.toml
  substrate/client/telemetry/Cargo.toml
  substrate/client/telemetry/src/transport.rs
Labels: R0-silent, T0-node

#4444 Rococo AH: cleanup storage
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  prdoc/pr_4444.prdoc
Labels: T14-system_parachains

#4431 statement-distribution: prep for re-enabling
  polkadot/node/network/statement-distribution/src/v2/cluster.rs
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  polkadot/node/network/statement-distribution/src/v2/tests/mod.rs
  polkadot/node/network/statement-distribution/src/v2/tests/requests.rs
  polkadot/roadmap/implementers-guide/src/node/backing/statement-distribution.md
  prdoc/pr_4431.prdoc
Labels: T8-polkadot

#4709 fix build on MacOS: bump secp256k1 and secp256k1-sys to patched versions
  Cargo.lock
Labels: R0-silent

#4677 [CI] Delete cargo-deny config
  .gitlab/pipeline/check.yml
  substrate/scripts/ci/deny.toml
Labels: R0-silent

#4711 Update link to a latest polkadot release
  polkadot/README.md
Labels: R0-silent, T11-documentation

#4662 Cleanup PVF artifact by cache limit and stale time
  polkadot/node/core/pvf/common/src/prepare.rs
  polkadot/node/core/pvf/src/artifacts.rs
  polkadot/node/core/pvf/src/host.rs
  polkadot/node/core/pvf/src/prepare/worker_interface.rs
  polkadot/node/core/pvf/src/testing.rs
  prdoc/pr_4662.prdoc
Labels: T0-node, I9-optimisation, T8-polkadot

#4718 Update the README to include a link to the Polkadot SDK Version Manager
  README.md
Labels: R0-silent

#4727 statement-distribution: Fix false warning
  polkadot/node/network/statement-distribution/src/v2/cluster.rs
Labels: R0-silent

#4691 Fix occupied core handling
  polkadot/runtime/parachains/src/assigner_coretime/tests.rs
  polkadot/runtime/parachains/src/assigner_on_demand/tests.rs
  polkadot/runtime/parachains/src/assigner_parachains/tests.rs
  polkadot/runtime/parachains/src/builder.rs
  polkadot/runtime/parachains/src/configuration.rs
  polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs
  polkadot/runtime/parachains/src/paras_inherent/mod.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
  polkadot/runtime/parachains/src/runtime_api_impl/v10.rs
  polkadot/runtime/parachains/src/runtime_api_impl/vstaging.rs
  polkadot/runtime/parachains/src/scheduler.rs
  polkadot/runtime/parachains/src/scheduler/migration.rs
  polkadot/runtime/parachains/src/scheduler/tests.rs
  prdoc/pr_4691.prdoc
Labels: T8-polkadot

#4642 Frame Pallets: Clean a lot of test setups
  bridges/modules/beefy/src/mock.rs
  bridges/snowbridge/pallets/inbound-queue/src/mock.rs
  cumulus/pallets/collator-selection/src/mock.rs
  substrate/frame/conviction-voting/src/tests.rs
  substrate/frame/examples/multi-block-migrations/src/mock.rs
  substrate/frame/fast-unstake/src/mock.rs
  substrate/frame/im-online/src/mock.rs
  substrate/frame/indices/src/mock.rs
  substrate/frame/nomination-pools/benchmarking/src/mock.rs
  substrate/frame/nomination-pools/src/mock.rs
  substrate/frame/nomination-pools/test-delegate-stake/src/mock.rs
  substrate/frame/nomination-pools/test-transfer-stake/src/mock.rs
  substrate/frame/offences/benchmarking/src/mock.rs
  substrate/frame/offences/src/mock.rs
  substrate/frame/paged-list/src/mock.rs
  substrate/frame/session/benchmarking/src/mock.rs
  substrate/frame/sudo/src/mock.rs
  substrate/frame/system/benches/bench.rs
  substrate/frame/system/benchmarking/src/mock.rs
  substrate/frame/transaction-payment/asset-conversion-tx-payment/src/mock.rs
  substrate/frame/transaction-payment/asset-tx-payment/src/mock.rs
  substrate/frame/transaction-payment/src/mock.rs
  substrate/frame/tx-pause/src/mock.rs
  substrate/test-utils/runtime/src/lib.rs
  templates/parachain/pallets/template/src/mock.rs
  templates/solochain/pallets/template/src/mock.rs
Labels: R0-silent, T1-FRAME

#4654 New reference doc for Custom RPC V2
  Cargo.lock
  docs/sdk/src/reference_docs/custom_runtime_api_rpc.rs
  docs/sdk/src/reference_docs/mod.rs
  substrate/frame/system/rpc/runtime-api/Cargo.toml
  substrate/frame/system/rpc/runtime-api/src/lib.rs
  substrate/utils/frame/rpc/system/Cargo.toml
  substrate/utils/frame/rpc/system/src/lib.rs
  templates/minimal/node/Cargo.toml
  templates/minimal/node/src/rpc.rs
Labels: R0-silent, T11-documentation

#4732 Backport style changes from P<>K bridge to R<>W bridge
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
Labels: R0-silent, T15-bridges

#3679 Contracts: update wasmi to 0.32
  Cargo.lock
  prdoc/pr_3679.prdoc
  substrate/frame/contracts/Cargo.toml
  substrate/frame/contracts/proc-macro/src/lib.rs
  substrate/frame/contracts/src/benchmarking/mod.rs
  substrate/frame/contracts/src/benchmarking/sandbox.rs
  substrate/frame/contracts/src/gas.rs
  substrate/frame/contracts/src/schedule.rs
  substrate/frame/contracts/src/wasm/mod.rs
  substrate/frame/contracts/src/wasm/prepare.rs
  substrate/frame/contracts/src/wasm/runtime.rs
  substrate/frame/contracts/src/weights.rs
Labels: T7-smart_contracts

#4712 frame/proc-macro: Refactor code for better readability
  substrate/frame/support/procedural/src/pallet/expand/constants.rs
  substrate/frame/support/procedural/src/pallet/parse/config.rs
  substrate/frame/support/procedural/src/pallet/parse/helper.rs
Labels: A1-insubstantial, R0-silent, I4-refactor, D0-easy

#4734 Update README.md to move the PSVM link under a "Tooling" section under the "Releases" section
  README.md
Labels: R0-silent

#4713 Revamp the Readme of the parachain template
  templates/minimal/README.md
  templates/parachain/README.md
  templates/parachain/node/README.md
  templates/parachain/pallets/README.md
  templates/parachain/pallets/template/README.md
  templates/parachain/polkadot-launch/config.json
  templates/parachain/runtime/README.md
  templates/parachain/zombienet.toml
Labels: R0-silent, T11-documentation

#4726 approval-voting: Add no shows debug information
  polkadot/node/core/approval-voting/src/approval_checking.rs
  polkadot/node/core/approval-voting/src/import.rs
  polkadot/node/core/approval-voting/src/lib.rs
  polkadot/node/core/approval-voting/src/tests.rs
Labels: R0-silent

#4733 add pov-recovery unit tests and support for elastic scaling
  Cargo.lock
  cumulus/client/consensus/common/Cargo.toml
  cumulus/client/consensus/common/src/tests.rs
  cumulus/client/network/Cargo.toml
  cumulus/client/network/src/lib.rs
  cumulus/client/network/src/tests.rs
  cumulus/client/pov-recovery/Cargo.toml
  cumulus/client/pov-recovery/src/active_candidate_recovery.rs
  cumulus/client/pov-recovery/src/lib.rs
  cumulus/client/pov-recovery/src/tests.rs
  cumulus/client/relay-chain-inprocess-interface/src/lib.rs
  cumulus/client/relay-chain-interface/Cargo.toml
  cumulus/client/relay-chain-interface/src/lib.rs
  cumulus/client/relay-chain-rpc-interface/src/lib.rs
  prdoc/pr_4733.prdoc
  substrate/client/api/src/client.rs
  substrate/primitives/blockchain/src/backend.rs
  substrate/primitives/consensus/common/src/lib.rs
Labels: T9-cumulus

#4742 Remove unncessary call remove_from_peers_set
  polkadot/node/network/bridge/src/validator_discovery.rs
Labels: R0-silent

#4721 finalization: Skip tree route calculation if no forks present
  prdoc/pr_4721.prdoc
  substrate/client/db/src/lib.rs
  substrate/primitives/blockchain/src/backend.rs
  substrate/primitives/blockchain/src/header_metadata.rs
Labels: T0-node

#4760 [1.13.0 backport] finalization: Skip tree route calculation if no forks present
  prdoc/pr_4721.prdoc
  substrate/client/db/src/lib.rs
  substrate/primitives/blockchain/src/backend.rs
  substrate/primitives/blockchain/src/header_metadata.rs
Labels: T0-node

#4761 [1.12.0 backport] finalization: Skip tree route calculation if no forks present
  prdoc/pr_4721.prdoc
  substrate/client/db/src/lib.rs
  substrate/primitives/blockchain/src/backend.rs
  substrate/primitives/blockchain/src/header_metadata.rs
Labels: T0-node

#1223 Append overlay optimization.
  Cargo.lock
  polkadot/node/core/pvf/common/src/executor_interface.rs
  prdoc/pr_1223.prdoc
  substrate/client/executor/src/integration_tests/mod.rs
  substrate/primitives/externalities/src/lib.rs
  substrate/primitives/io/src/lib.rs
  substrate/primitives/state-machine/Cargo.toml
  substrate/primitives/state-machine/fuzz/Cargo.toml
  substrate/primitives/state-machine/fuzz/fuzz_targets/fuzz_append.rs
  substrate/primitives/state-machine/src/basic.rs
  substrate/primitives/state-machine/src/ext.rs
  substrate/primitives/state-machine/src/fuzzing.rs
  substrate/primitives/state-machine/src/in_memory_backend.rs
  substrate/primitives/state-machine/src/lib.rs
  substrate/primitives/state-machine/src/overlayed_changes/changeset.rs
  substrate/primitives/state-machine/src/overlayed_changes/mod.rs
  substrate/primitives/state-machine/src/overlayed_changes/offchain.rs
  substrate/primitives/state-machine/src/read_only.rs
  substrate/primitives/state-machine/src/testing.rs
  substrate/utils/frame/remote-externalities/src/lib.rs
Labels: A0-needs_burnin, T0-node, I2-bug

#4771 Backport Append optimization to 1.13.0
  Cargo.lock
  polkadot/node/core/pvf/common/src/executor_interface.rs
  prdoc/pr_1223.prdoc
  substrate/client/executor/src/integration_tests/mod.rs
  substrate/primitives/externalities/src/lib.rs
  substrate/primitives/io/src/lib.rs
  substrate/primitives/state-machine/Cargo.toml
  substrate/primitives/state-machine/fuzz/Cargo.toml
  substrate/primitives/state-machine/fuzz/fuzz_targets/fuzz_append.rs
  substrate/primitives/state-machine/src/basic.rs
  substrate/primitives/state-machine/src/ext.rs
  substrate/primitives/state-machine/src/fuzzing.rs
  substrate/primitives/state-machine/src/in_memory_backend.rs
  substrate/primitives/state-machine/src/lib.rs
  substrate/primitives/state-machine/src/overlayed_changes/changeset.rs
  substrate/primitives/state-machine/src/overlayed_changes/mod.rs
  substrate/primitives/state-machine/src/overlayed_changes/offchain.rs
  substrate/primitives/state-machine/src/read_only.rs
  substrate/primitives/state-machine/src/testing.rs
  substrate/utils/frame/remote-externalities/src/lib.rs
Labels: R0-silent

#4735 Update the pallet guide in `sdk-docs`
  Cargo.lock
  README.md
  docs/mermaid/IA.mmd
  docs/sdk/Cargo.toml
  docs/sdk/src/guides/mod.rs
  docs/sdk/src/guides/your_first_pallet/mod.rs
  docs/sdk/src/guides/your_first_runtime.rs
  docs/sdk/src/polkadot_sdk/templates.rs
  docs/sdk/src/reference_docs/blockchain_scalibility.rs
  docs/sdk/src/reference_docs/consensus_swapping.rs
  docs/sdk/src/reference_docs/custom_host_functions.rs
  docs/sdk/src/reference_docs/fee_less_runtime.rs
  docs/sdk/src/reference_docs/frame_offchain_workers.rs
  docs/sdk/src/reference_docs/frame_system_accounts.rs
  docs/sdk/src/reference_docs/light_nodes.rs
  docs/sdk/src/reference_docs/metadata.rs
  docs/sdk/src/reference_docs/mod.rs
  docs/sdk/src/reference_docs/wasm_memory.rs
  docs/sdk/src/reference_docs/wasm_meta_protocol.rs
  substrate/frame/support/src/traits/hooks.rs
  substrate/primitives/io/Cargo.toml
  substrate/primitives/io/src/lib.rs
  templates/minimal/node/src/service.rs
Labels: R0-silent, T11-documentation

#4752 Add `--version` to the `ChainSpecBuilder` command for `staging-chain-spec-builder`
  .github/workflows/release-30_publish_release_draft.yml
  substrate/bin/utils/chain-spec-builder/src/lib.rs
  substrate/utils/frame/omni-bencher/Cargo.toml
Labels: R0-silent

#4784 [Backport] Version bumps and prdoc reorg from 1.13.0
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot/node/primitives/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/1.13.0/pr_1223.prdoc
  prdoc/1.13.0/pr_1644.prdoc
  prdoc/1.13.0/pr_3393.prdoc
  prdoc/1.13.0/pr_3905.prdoc
  prdoc/1.13.0/pr_3935.prdoc
  prdoc/1.13.0/pr_3952.prdoc
  prdoc/1.13.0/pr_4131.prdoc
  prdoc/1.13.0/pr_4198.prdoc
  prdoc/1.13.0/pr_4233.prdoc
  prdoc/1.13.0/pr_4249.prdoc
  prdoc/1.13.0/pr_4274.prdoc
  prdoc/1.13.0/pr_4339.prdoc
  prdoc/1.13.0/pr_4380.prdoc
  prdoc/1.13.0/pr_4392.prdoc
  prdoc/1.13.0/pr_4410.prdoc
  prdoc/1.13.0/pr_4418.prdoc
  prdoc/1.13.0/pr_4431.prdoc
  prdoc/1.13.0/pr_4444.prdoc
  prdoc/1.13.0/pr_4465.prdoc
  prdoc/1.13.0/pr_4471.prdoc
  prdoc/1.13.0/pr_4472.prdoc
  prdoc/1.13.0/pr_4475.prdoc
  prdoc/1.13.0/pr_4478.prdoc
  prdoc/1.13.0/pr_4503.prdoc
  prdoc/1.13.0/pr_4510.prdoc
  prdoc/1.13.0/pr_4514.prdoc
  prdoc/1.13.0/pr_4521.prdoc
  prdoc/1.13.0/pr_4533.prdoc
  prdoc/1.13.0/pr_4534.prdoc
  prdoc/1.13.0/pr_4537.prdoc
  prdoc/1.13.0/pr_4541.prdoc
  prdoc/1.13.0/pr_4542.prdoc
  prdoc/1.13.0/pr_4555.prdoc
  prdoc/1.13.0/pr_4571.prdoc
  prdoc/1.13.0/pr_4595.prdoc
  prdoc/1.13.0/pr_4621.prdoc
  prdoc/1.13.0/pr_4633.prdoc
  prdoc/1.13.0/pr_4634.prdoc
  prdoc/1.13.0/pr_4645.prdoc
  prdoc/1.13.0/pr_4646.prdoc
  prdoc/1.13.0/pr_4721.prdoc
Labels: R0-silent

#4666 `polkadot-parachain-bin`: small cosmetics and improvements
  cumulus/polkadot-parachain/Cargo.toml
  cumulus/polkadot-parachain/src/cli.rs
  cumulus/polkadot-parachain/src/command.rs
  cumulus/polkadot-parachain/src/common/aura.rs
  cumulus/polkadot-parachain/src/common/mod.rs
  cumulus/polkadot-parachain/src/fake_runtime_api/asset_hub_polkadot_aura.rs
  cumulus/polkadot-parachain/src/fake_runtime_api/aura.rs
  cumulus/polkadot-parachain/src/main.rs
  cumulus/polkadot-parachain/src/service.rs
  substrate/client/service/src/config.rs
Labels: R0-silent, T0-node

#4494 Bridges - changes for Bridges V2 - relay client part
  Cargo.lock
  bridges/modules/relayers/src/lib.rs
  bridges/primitives/relayers/src/lib.rs
  bridges/primitives/runtime/src/lib.rs
  bridges/relays/client-substrate/Cargo.toml
  bridges/relays/client-substrate/src/chain.rs
  bridges/relays/client-substrate/src/client.rs
  bridges/relays/client-substrate/src/client/caching.rs
  bridges/relays/client-substrate/src/client/mod.rs
  bridges/relays/client-substrate/src/client/rpc.rs
  bridges/relays/client-substrate/src/client/rpc_api.rs
  bridges/relays/client-substrate/src/client/subscription.rs
  bridges/relays/client-substrate/src/client/traits.rs
  bridges/relays/client-substrate/src/error.rs
  bridges/relays/client-substrate/src/guard.rs
  bridges/relays/client-substrate/src/lib.rs
  bridges/relays/client-substrate/src/metrics/float_storage_value.rs
  bridges/relays/client-substrate/src/transaction_tracker.rs
  bridges/relays/lib-substrate-relay/src/cli/chain_schema.rs
  bridges/relays/lib-substrate-relay/src/cli/detect_equivocations.rs
  bridges/relays/lib-substrate-relay/src/cli/mod.rs
  bridges/relays/lib-substrate-relay/src/cli/relay_headers.rs
  bridges/relays/lib-substrate-relay/src/cli/relay_headers_and_messages/mod.rs
  bridges/relays/lib-substrate-relay/src/cli/relay_headers_and_messages/parachain_to_parachain.rs
  bridges/relays/lib-substrate-relay/src/cli/relay_headers_and_messages/relay_to_parachain.rs
  bridges/relays/lib-substrate-relay/src/cli/relay_headers_and_messages/relay_to_relay.rs
  bridges/relays/lib-substrate-relay/src/cli/relay_messages.rs
  bridges/relays/lib-substrate-relay/src/cli/relay_parachains.rs
  bridges/relays/lib-substrate-relay/src/equivocation/mod.rs
  bridges/relays/lib-substrate-relay/src/equivocation/source.rs
  bridges/relays/lib-substrate-relay/src/equivocation/target.rs
  bridges/relays/lib-substrate-relay/src/finality/initialize.rs
  bridges/relays/lib-substrate-relay/src/finality/mod.rs
  bridges/relays/lib-substrate-relay/src/finality/source.rs
  bridges/relays/lib-substrate-relay/src/finality/target.rs
  bridges/relays/lib-substrate-relay/src/finality_base/engine.rs
  bridges/relays/lib-substrate-relay/src/finality_base/mod.rs
  bridges/relays/lib-substrate-relay/src/messages_lane.rs
  bridges/relays/lib-substrate-relay/src/messages_metrics.rs
  bridges/relays/lib-substrate-relay/src/messages_source.rs
  bridges/relays/lib-substrate-relay/src/messages_target.rs
  bridges/relays/lib-substrate-relay/src/on_demand/headers.rs
  bridges/relays/lib-substrate-relay/src/on_demand/parachains.rs
  bridges/relays/lib-substrate-relay/src/parachains/source.rs
  bridges/relays/lib-substrate-relay/src/parachains/target.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_data/mod.rs
Labels: R0-silent, T15-bridges

#4765 CheckWeight: account for extrinsic len as proof size
  cumulus/primitives/storage-weight-reclaim/src/lib.rs
  prdoc/pr_4765.prdoc
  substrate/frame/executive/src/tests.rs
  substrate/frame/system/src/extensions/check_weight.rs
Labels: T1-FRAME

#4768 add ref doc for logging practices in FRAME
  Cargo.lock
  docs/sdk/Cargo.toml
  docs/sdk/src/reference_docs/frame_logging.rs
  docs/sdk/src/reference_docs/mod.rs
  docs/sdk/src/reference_docs/umbrella_crate.rs
  substrate/primitives/api/Cargo.toml
  substrate/primitives/api/src/lib.rs
Labels: R0-silent, T11-documentation

#4780 CI: Add stable clobber
  .github/workflows/release-clobber-stable.yml
  .github/workflows/release-srtool.yml
Labels: R0-silent

#4797 Impl and use default config for pallet-staking in tests
  substrate/frame/babe/src/mock.rs
  substrate/frame/beefy/src/mock.rs
  substrate/frame/delegated-staking/src/mock.rs
  substrate/frame/delegated-staking/src/tests.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
  substrate/frame/fast-unstake/src/mock.rs
  substrate/frame/grandpa/src/mock.rs
  substrate/frame/nomination-pools/benchmarking/src/mock.rs
  substrate/frame/nomination-pools/test-delegate-stake/src/mock.rs
  substrate/frame/nomination-pools/test-transfer-stake/src/mock.rs
  substrate/frame/offences/benchmarking/src/mock.rs
  substrate/frame/root-offences/src/mock.rs
  substrate/frame/session/benchmarking/src/mock.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/mod.rs
Labels: R0-silent, T10-tests

#4810 Improve pruning CLI documentation
  substrate/client/cli/src/params/pruning_params.rs
Labels: R0-silent, T0-node

#4741 Ibp bootnodes for Kusama People (#6)
  cumulus/parachains/chain-specs/collectives-polkadot.json
  cumulus/parachains/chain-specs/people-kusama.json
Labels: R0-silent

#4783 node-inspect: do not depend on rocksdb
  substrate/bin/node/inspect/Cargo.toml
Labels: R0-silent

#3374 remove pallet::getter usage from pallet-timestamp
  cumulus/test/runtime/src/lib.rs
  polkadot/runtime/test-runtime/src/lib.rs
  prdoc/pr_3374.prdoc
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/lib.rs
  substrate/frame/timestamp/src/benchmarking.rs
  substrate/frame/timestamp/src/lib.rs
  substrate/frame/timestamp/src/tests.rs
Labels: T1-FRAME

#4684 refactor: parachain template
  prdoc/pr_4684.prdoc
  templates/parachain/pallets/template/src/lib.rs
  templates/parachain/pallets/template/src/mock.rs
  templates/parachain/pallets/template/src/weights.rs
  templates/parachain/runtime/Cargo.toml
  templates/parachain/runtime/src/lib.rs
Labels: T11-documentation

#4728 glutton: also increase parachain block length
  Cargo.lock
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  prdoc/pr_4728.prdoc
  substrate/bin/node/bench/src/import.rs
  substrate/bin/node/cli/tests/res/default_genesis_config.json
  substrate/frame/glutton/Cargo.toml
  substrate/frame/glutton/README.md
  substrate/frame/glutton/src/lib.rs
  substrate/frame/glutton/src/mock.rs
  substrate/frame/glutton/src/tests.rs
Labels: T10-tests, T12-benchmarks

#3820 Remove deprecated treasury pallet calls
  cumulus/parachains/runtimes/collectives/collectives-westend/src/fellowship/mod.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_treasury.rs
  polkadot/runtime/common/src/impls.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/pallet_treasury.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/pallet_treasury.rs
  prdoc/pr_3820.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/bounties/src/tests.rs
  substrate/frame/child-bounties/src/tests.rs
  substrate/frame/tips/src/tests.rs
  substrate/frame/treasury/README.md
  substrate/frame/treasury/src/benchmarking.rs
  substrate/frame/treasury/src/lib.rs
  substrate/frame/treasury/src/tests.rs
  substrate/frame/treasury/src/weights.rs
Labels: T1-FRAME

#3843 Add set_partial_params dispatchable function
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_core_fellowship_ambassador_core.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_core_fellowship_fellowship_core.rs
  prdoc/pr_3843.prdoc
  substrate/frame/core-fellowship/src/benchmarking.rs
  substrate/frame/core-fellowship/src/lib.rs
  substrate/frame/core-fellowship/src/tests/unit.rs
  substrate/frame/core-fellowship/src/weights.rs
Labels: T2-pallets

#4618 Unify `code_at` logic between `CallExecutor` & `Client`
  cumulus/client/consensus/aura/src/collators/lookahead.rs
  cumulus/client/consensus/aura/src/collators/mod.rs
  prdoc/pr_4618.prdoc
  substrate/client/service/src/client/call_executor.rs
  substrate/client/service/src/client/client.rs
  substrate/client/service/src/client/code_provider.rs
  substrate/client/service/src/client/mod.rs
  substrate/client/service/src/client/wasm_substitutes.rs
  substrate/test-utils/client/src/client_ext.rs
Labels: T0-node, T9-cumulus

#4653 chore: remove redundant words.
  substrate/primitives/storage/src/lib.rs
Labels: R0-silent

#4701 Migrated commands to github actions
  .github/actions/set-up-gh/action.yml
  .github/command-screnshot.png
  .github/commands-readme.md
  .github/workflows/command-bench-all.yml
  .github/workflows/command-bench-overhead.yml
  .github/workflows/command-bench.yml
  .github/workflows/command-fmt.yml
  .github/workflows/command-inform.yml
  .github/workflows/command-update-ui.yml
  scripts/bench-all.sh
  scripts/bench.sh
  scripts/command-utils.sh
  scripts/lib/bench-all-cumulus.sh
  scripts/lib/bench-all-pallet.sh
  scripts/lib/bench-all-polkadot.sh
  scripts/lib/bench-all-substrate.sh
  scripts/lib/bench-overhead.sh
  scripts/lib/bench-pallet.sh
  scripts/sync.sh
Labels: R0-silent

#4821 Update bridges zombienet tests relay version
  docker/dockerfiles/bridges_zombienet_tests_injected.Dockerfile
Labels: R0-silent, T15-bridges

#4836 Fix CLI pruning params
  substrate/client/cli/src/params/pruning_params.rs
Labels: R0-silent

#4802 rpc server: add `health/readiness endpoint`
  Cargo.lock
  prdoc/pr_4802.prdoc
  substrate/client/rpc-servers/Cargo.toml
  substrate/client/rpc-servers/src/lib.rs
  substrate/client/rpc-servers/src/middleware/mod.rs
  substrate/client/rpc-servers/src/middleware/node_health.rs
Labels: T0-node

#4756 Do not make pallet-nfts benchmarks signature-dependent
  prdoc/pr_4756.prdoc
  substrate/frame/nfts/src/benchmarking.rs
  substrate/frame/nfts/src/lib.rs
Labels: T2-pallets

#4710 [HRMP] Dont partially modify pages
  cumulus/pallets/xcmp-queue/src/lib.rs
  cumulus/pallets/xcmp-queue/src/tests.rs
  prdoc/pr_4710.prdoc
Labels: T6-XCM

#3951 Implement `pallet-assets-freezer`
  Cargo.lock
  Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_3951.prdoc
  substrate/frame/assets-freezer/Cargo.toml
  substrate/frame/assets-freezer/src/impls.rs
  substrate/frame/assets-freezer/src/lib.rs
  substrate/frame/assets-freezer/src/mock.rs
  substrate/frame/assets-freezer/src/tests.rs
  substrate/frame/balances/src/lib.rs
  substrate/frame/balances/src/types.rs
  substrate/frame/support/src/traits/tokens.rs
  substrate/frame/support/src/traits/tokens/misc.rs
  umbrella/Cargo.toml
  umbrella/src/lib.rs
Labels: T2-pallets

#4855 sc-network-types: implement `From<IpAddr> for Multiaddr`
  substrate/client/network/types/src/multiaddr.rs
  substrate/client/network/types/src/multiaddr/protocol.rs
Labels: R0-silent, T0-node, D0-easy

#4862 Bump time to fix compilation on latest nightly
  Cargo.lock
Labels: R0-silent

#4596 Frame: `Consideration` trait generic over `Footprint` and indicates zero cost
  prdoc/pr_4596.prdoc
  substrate/frame/balances/src/tests/fungible_tests.rs
  substrate/frame/balances/src/tests/mod.rs
  substrate/frame/preimage/src/benchmarking.rs
  substrate/frame/preimage/src/lib.rs
  substrate/frame/support/src/traits/storage.rs
  substrate/frame/support/src/traits/tokens/fungible/mod.rs
Labels: T1-FRAME

#4513 Remove pallet::getter macro usage from pallet-elections-phragmen
  prdoc/pr_4513.prdoc
  substrate/frame/elections-phragmen/src/benchmarking.rs
  substrate/frame/elections-phragmen/src/lib.rs
  substrate/frame/elections-phragmen/src/migrations/v3.rs
Labels: T2-pallets

#4833 Reinitialize should allow to override existing config in collationGeneration
  polkadot/node/collation-generation/src/lib.rs
  prdoc/pr_4833.prdoc
Labels: T0-node

#4842 Block import cleanups
  Cargo.lock
  substrate/client/consensus/common/Cargo.toml
  substrate/client/consensus/common/src/import_queue.rs
  substrate/client/consensus/common/src/import_queue/basic_queue.rs
Labels: R0-silent

#4861 Dont publish example pallets
  substrate/frame/examples/basic/Cargo.toml
  substrate/frame/examples/default-config/Cargo.toml
  substrate/frame/examples/offchain-worker/Cargo.toml
  substrate/frame/examples/split/Cargo.toml
  substrate/frame/examples/tasks/Cargo.toml
Labels: R0-silent

#4865 pallet-membership should implement ContainsLengthBound
  prdoc/pr_4865.prdoc
  substrate/frame/membership/src/lib.rs
Labels: T1-FRAME

#4823 Ensure earliest allowed block is at minimum the next block
  prdoc/pr_4823.prdoc
  substrate/frame/referenda/src/lib.rs
  substrate/frame/referenda/src/mock.rs
  substrate/frame/referenda/src/tests.rs
Labels: T2-pallets

#4807 pallet ranked collective: max member count per rank
  cumulus/parachains/runtimes/collectives/collectives-westend/src/ambassador/mod.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/fellowship/mod.rs
  polkadot/runtime/rococo/src/governance/fellowship.rs
  prdoc/pr_4807.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/core-fellowship/src/tests/integration.rs
  substrate/frame/ranked-collective/src/lib.rs
  substrate/frame/ranked-collective/src/tests.rs
  substrate/frame/salary/src/tests/integration.rs
Labels: T1-FRAME

#4867 CI quick-checks: Pull Rust deps in advance
  .github/workflows/checks-quick.yml
Labels: R0-silent

#4831 treasury pallet: remove unused config parameters
  cumulus/parachains/runtimes/collectives/collectives-westend/src/fellowship/mod.rs
  polkadot/runtime/common/src/impls.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_4831.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/bounties/src/benchmarking.rs
  substrate/frame/bounties/src/lib.rs
  substrate/frame/bounties/src/tests.rs
  substrate/frame/child-bounties/src/tests.rs
  substrate/frame/tips/src/lib.rs
  substrate/frame/tips/src/tests.rs
  substrate/frame/treasury/src/lib.rs
  substrate/frame/treasury/src/tests.rs
Labels: T1-FRAME

#4869 chore: remove repeat words
  polkadot/runtime/common/src/traits.rs
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/src/v2/mod.rs
  polkadot/xcm/src/v3/junction.rs
  substrate/client/network/src/event.rs
  substrate/frame/staking/src/tests.rs
  substrate/test-utils/runtime/src/lib.rs
Labels: R0-silent

#4872 rpc2: Finalized event doesn't indicate that the best block changes
  substrate/client/rpc-spec-v2/src/chain_head/chain_head_follow.rs
Labels: R0-silent

#4772 [subsystem-bench] Trigger own assignments in approval-voting
  polkadot/node/subsystem-bench/src/lib/approval/mod.rs
  polkadot/node/subsystem-bench/src/lib/mock/runtime_api.rs
Labels: R0-silent, T12-benchmarks

#4685 chain-spec-builder: Add support for `codeSubstitutes`
  prdoc/pr_4685.prdoc
  substrate/bin/utils/chain-spec-builder/bin/main.rs
  substrate/bin/utils/chain-spec-builder/src/lib.rs
  substrate/client/chain-spec/src/chain_spec.rs
  substrate/client/chain-spec/src/lib.rs
Labels: T0-node

#1631 Upgrade libp2p to 0.52.4
  Cargo.lock
  Cargo.toml
  prdoc/pr_1631.prdoc
  substrate/client/authority-discovery/Cargo.toml
  substrate/client/authority-discovery/src/service.rs
  substrate/client/authority-discovery/src/worker.rs
  substrate/client/authority-discovery/src/worker/addr_cache.rs
  substrate/client/network-gossip/Cargo.toml
  substrate/client/network-gossip/src/bridge.rs
  substrate/client/network-gossip/src/lib.rs
  substrate/client/network-gossip/src/state_machine.rs
  substrate/client/network/src/behaviour.rs
  substrate/client/network/src/config.rs
  substrate/client/network/src/discovery.rs
  substrate/client/network/src/litep2p/service.rs
  substrate/client/network/src/peer_info.rs
  substrate/client/network/src/protocol.rs
  substrate/client/network/src/protocol/notifications/behaviour.rs
  substrate/client/network/src/protocol/notifications/handler.rs
  substrate/client/network/src/protocol/notifications/tests.rs
  substrate/client/network/src/protocol/notifications/upgrade.rs
  substrate/client/network/src/protocol/notifications/upgrade/collec.rs
  substrate/client/network/src/protocol/notifications/upgrade/notifications.rs
  substrate/client/network/src/request_responses.rs
  substrate/client/network/src/service.rs
  substrate/client/network/src/transport.rs
  substrate/client/network/src/types.rs
  substrate/client/network/statement/Cargo.toml
  substrate/client/network/transactions/Cargo.toml
  substrate/client/network/types/Cargo.toml
  substrate/client/network/types/src/multiaddr.rs
  substrate/client/network/types/src/multiaddr/protocol.rs
  substrate/client/network/types/src/multihash.rs
  substrate/client/offchain/Cargo.toml
  substrate/client/telemetry/src/transport.rs
Labels: T0-node

#4769 Use real rust type for pallet alias in `runtime` macro
  prdoc/pr_4769.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/support/procedural/Cargo.toml
  substrate/frame/support/procedural/src/lib.rs
  substrate/frame/support/procedural/src/runtime/expand/mod.rs
  substrate/frame/support/procedural/src/runtime/parse/mod.rs
  substrate/frame/support/procedural/src/runtime/parse/pallet.rs
  substrate/frame/support/procedural/src/runtime/parse/pallet_decl.rs
  substrate/frame/support/src/lib.rs
  substrate/frame/support/src/tests/mod.rs
  substrate/frame/support/src/tests/runtime.rs
  templates/minimal/runtime/src/lib.rs
Labels: T1-FRAME

#4844 Block import and verification refactoring
  Cargo.lock
  cumulus/client/consensus/aura/Cargo.toml
  cumulus/client/consensus/aura/src/equivocation_import_queue.rs
  cumulus/client/consensus/common/src/import_queue.rs
  cumulus/client/consensus/common/src/lib.rs
  cumulus/client/consensus/relay-chain/src/import_queue.rs
  cumulus/polkadot-parachain/src/service.rs
  prdoc/pr_4844.prdoc
  substrate/client/consensus/aura/src/import_queue.rs
  substrate/client/consensus/babe/src/lib.rs
  substrate/client/consensus/babe/src/tests.rs
  substrate/client/consensus/beefy/src/import.rs
  substrate/client/consensus/common/src/block_import.rs
  substrate/client/consensus/common/src/import_queue.rs
  substrate/client/consensus/common/src/import_queue/basic_queue.rs
  substrate/client/consensus/grandpa/src/import.rs
  substrate/client/consensus/manual-seal/src/consensus/babe.rs
  substrate/client/consensus/manual-seal/src/lib.rs
  substrate/client/consensus/pow/src/lib.rs
  substrate/client/network/test/src/lib.rs
  substrate/client/network/test/src/service.rs
  substrate/client/service/src/client/client.rs
Labels: T0-node

#3828 [FRAME] Remove storage migration type
  prdoc/pr_3828.prdoc
  substrate/frame/support/src/migrations.rs
Labels: T1-FRAME

#4730 rpc: upgrade jsonrpsee v0.23
  Cargo.lock
  Cargo.toml
  bridges/relays/client-substrate/Cargo.toml
  bridges/relays/client-substrate/src/client/subscription.rs
  cumulus/client/relay-chain-rpc-interface/src/light_client_worker.rs
  prdoc/pr_4730.prdoc
  substrate/client/rpc-servers/Cargo.toml
  substrate/client/rpc-servers/src/lib.rs
  substrate/client/rpc-servers/src/middleware/node_health.rs
  substrate/client/rpc-servers/src/utils.rs
  substrate/client/rpc-spec-v2/src/chain_head/api.rs
  substrate/client/rpc-spec-v2/src/chain_head/chain_head.rs
  substrate/client/rpc-spec-v2/src/chain_head/subscription/inner.rs
  substrate/client/rpc-spec-v2/src/common/connections.rs
  substrate/client/rpc-spec-v2/src/transaction/api.rs
  substrate/client/rpc-spec-v2/src/transaction/transaction_broadcast.rs
  substrate/client/rpc/src/utils.rs
  substrate/utils/frame/remote-externalities/src/lib.rs
Labels: T0-node

#4878 Update parity publish
  .github/workflows/check-semver.yml
  .github/workflows/publish-check-crates.yml
  .github/workflows/publish-claim-crates.yml
Labels: R0-silent

#4857 [xcm] runtime api for LocationToAccount conversions
  Cargo.lock
  Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/relays/westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/xcm_fee_estimation.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/Cargo.toml
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/Cargo.toml
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/Cargo.toml
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/Cargo.toml
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  cumulus/polkadot-parachain/Cargo.toml
  polkadot/node/service/Cargo.toml
  polkadot/node/service/src/fake_runtime_api.rs
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/Cargo.toml
  polkadot/runtime/westend/src/lib.rs
  polkadot/xcm/pallet-xcm/Cargo.toml
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/xcm-runtime-apis/Cargo.toml
  polkadot/xcm/xcm-runtime-apis/src/conversions.rs
  polkadot/xcm/xcm-runtime-apis/src/dry_run.rs
  polkadot/xcm/xcm-runtime-apis/src/fees.rs
  polkadot/xcm/xcm-runtime-apis/src/lib.rs
  polkadot/xcm/xcm-runtime-apis/tests/conversions.rs
  polkadot/xcm/xcm-runtime-apis/tests/fee_estimation.rs
  polkadot/xcm/xcm-runtime-apis/tests/mock.rs
  prdoc/pr_4857.prdoc
  umbrella/Cargo.toml
  umbrella/src/lib.rs
Labels: T6-XCM

#4877 Fellowship-core: add fast promote
  cumulus/parachains/runtimes/collectives/collectives-westend/src/ambassador/mod.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/fellowship/mod.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_core_fellowship_ambassador_core.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_core_fellowship_fellowship_core.rs
  prdoc/pr_4877.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/core-fellowship/src/benchmarking.rs
  substrate/frame/core-fellowship/src/lib.rs
  substrate/frame/core-fellowship/src/tests/integration.rs
  substrate/frame/core-fellowship/src/tests/unit.rs
  substrate/frame/core-fellowship/src/weights.rs
Labels: T2-pallets

#3940 Coretime: Add request revenue info
  Cargo.lock
  cumulus/parachains/runtimes/coretime/coretime-rococo/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/coretime.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_broker.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-westend/src/coretime.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/pallet_broker.rs
  cumulus/polkadot-parachain/Cargo.toml
  polkadot/runtime/parachains/src/assigner_coretime/tests.rs
  polkadot/runtime/parachains/src/assigner_on_demand/mod.rs
  polkadot/runtime/parachains/src/assigner_on_demand/tests.rs
  polkadot/runtime/parachains/src/assigner_on_demand/types.rs
  polkadot/runtime/parachains/src/coretime/benchmarking.rs
  polkadot/runtime/parachains/src/coretime/mod.rs
  polkadot/runtime/parachains/src/mock.rs
  polkadot/runtime/rococo/constants/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/runtime_parachains_assigner_on_demand.rs
  polkadot/runtime/rococo/src/weights/runtime_parachains_coretime.rs
  polkadot/runtime/westend/constants/Cargo.toml
  polkadot/runtime/westend/constants/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/runtime_parachains_assigner_on_demand.rs
  polkadot/runtime/westend/src/weights/runtime_parachains_coretime.rs
  prdoc/pr_3940.prdoc
  substrate/bin/node/cli/tests/res/default_genesis_config.json
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/broker/src/benchmarking.rs
  substrate/frame/broker/src/coretime_interface.rs
  substrate/frame/broker/src/dispatchable_impls.rs
  substrate/frame/broker/src/lib.rs
  substrate/frame/broker/src/migration.rs
  substrate/frame/broker/src/mock.rs
  substrate/frame/broker/src/tests.rs
  substrate/frame/broker/src/tick_impls.rs
  substrate/frame/broker/src/types.rs
  substrate/frame/broker/src/weights.rs
Labels: T14-system_parachains

#4757 pallet assets: optional auto-increment for the asset ID
  Cargo.lock
  polkadot/xcm/xcm-builder/src/tests/pay/mock.rs
  polkadot/xcm/xcm-runtime-apis/tests/mock.rs
  prdoc/pr_4757.prdoc
  substrate/bin/node/cli/tests/res/default_genesis_config.json
  substrate/frame/assets-freezer/src/mock.rs
  substrate/frame/assets/Cargo.toml
  substrate/frame/assets/src/functions.rs
  substrate/frame/assets/src/lib.rs
  substrate/frame/assets/src/migration.rs
  substrate/frame/assets/src/mock.rs
  substrate/frame/assets/src/tests.rs
  substrate/frame/contracts/mock-network/src/lib.rs
Labels: T1-FRAME

#4799 network: Upgrade `litep2p` to v0.6.2
  Cargo.lock
  Cargo.toml
  prdoc/pr_4799.prdoc
  substrate/client/authority-discovery/src/worker.rs
  substrate/client/network/src/litep2p/discovery.rs
  substrate/client/network/src/litep2p/mod.rs
  substrate/client/network/src/litep2p/service.rs
  substrate/client/network/types/src/ed25519.rs
Labels: A0-needs_burnin, T0-node

#4887 Mention the signed extensions in the reference docs
  Cargo.lock
  docs/sdk/Cargo.toml
  docs/sdk/src/reference_docs/signed_extensions.rs
  substrate/frame/system/src/extensions/check_mortality.rs
  substrate/frame/transaction-payment/skip-feeless-payment/src/lib.rs
Labels: R0-silent

#4699 Ensure key ownership proof is optimal
  bridges/bin/runtime-common/src/messages.rs
  bridges/primitives/runtime/src/storage_proof.rs
  substrate/frame/session/src/historical/mod.rs
  substrate/primitives/trie/src/accessed_nodes_tracker.rs
  substrate/primitives/trie/src/lib.rs
  substrate/primitives/trie/src/recorder.rs
  substrate/primitives/trie/src/recorder_ext.rs
  substrate/primitives/trie/src/storage_proof.rs
Labels: R0-silent, T15-bridges

#4895 Use newer nightly in check-semver
  .github/workflows/check-semver.yml
Labels: A1-insubstantial, R0-silent

#4891 BridgeHubs fresh weights for bridging pallets
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_grandpa.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_messages_rococo_to_rococo_bulletin.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_messages_rococo_to_westend.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_parachains.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_relayers.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_bridge_grandpa.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_bridge_messages.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_bridge_parachains.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_bridge_relayers.rs
Labels: R0-silent, T15-bridges

#4898 chore(deps): upgrade prometheous server to hyper v1
  Cargo.lock
  Cargo.toml
  polkadot/node/metrics/Cargo.toml
  polkadot/node/metrics/src/tests.rs
  substrate/client/offchain/Cargo.toml
  substrate/client/offchain/src/api/http.rs
  substrate/utils/prometheus/Cargo.toml
  substrate/utils/prometheus/src/lib.rs
Labels: R0-silent

#4805 Add `Runtime::OmniNode` variant to `polkadot-parachain`
  cumulus/polkadot-parachain/src/cli.rs
  cumulus/polkadot-parachain/src/command.rs
  cumulus/polkadot-parachain/src/main.rs
Labels: R0-silent, T0-node

#4363 Add Async Backing guide
  docs/sdk/src/guides/async_backing_guide.rs
  docs/sdk/src/guides/mod.rs
  templates/parachain/node/src/service.rs
  templates/parachain/runtime/src/apis.rs
  templates/parachain/runtime/src/configs/mod.rs
  templates/parachain/runtime/src/lib.rs
Labels: R0-silent, T11-documentation

#4888 [Rococo<>Westend bridge] Allow any asset over the lane between the two Asset Hubs
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-rococo/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/common/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/treasury.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/send_xcm.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/send_xcm.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/common/src/matching.rs
  prdoc/pr_4888.prdoc
Labels: T14-system_parachains, T15-bridges

#4738 Adds CheckMetadata SignedExtension to Coretime Parachains (Rococo and Westend)
  Cargo.lock
  cumulus/parachains/runtimes/coretime/coretime-rococo/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-rococo/build.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-westend/build.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  prdoc/pr_4738.prdoc
Labels: T14-system_parachains

#4906 network: Sync peerstore constants between libp2p and litep2p
  substrate/client/network/src/litep2p/peerstore.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement, D0-easy
