Repository paritytech/polkadot-sdk, pull requests merged in 2024-02, with the labels that each got.

#3074 [BEEFY] Avoid missing voting sessions during node restart
  substrate/client/consensus/beefy/src/aux_schema.rs
  substrate/client/consensus/beefy/src/communication/request_response/incoming_requests_handler.rs
  substrate/client/consensus/beefy/src/communication/request_response/outgoing_requests_engine.rs
  substrate/client/consensus/beefy/src/import.rs
  substrate/client/consensus/beefy/src/lib.rs
  substrate/client/consensus/beefy/src/metrics.rs
  substrate/client/consensus/beefy/src/tests.rs
  substrate/client/consensus/beefy/src/worker.rs
Labels: R0-silent, T15-bridges

#3093 Backport of fix Pools 6->7 migration (#2942)
  prdoc/pr_2942.prdoc
  substrate/frame/nomination-pools/src/migration.rs
Labels: R0-silent, T1-FRAME

#3170 Fixup backing group computation time
  .gitlab/pipeline/zombienet/polkadot.yml
  polkadot/runtime/parachains/src/runtime_api_impl/v7.rs
  polkadot/zombienet_tests/functional/0011-async-backing-6-seconds-rate.toml
  polkadot/zombienet_tests/functional/0011-async-backing-6-seconds-rate.zndsl
Labels: R0-silent

#3189 Fix `new_session` benchmark in `pallet_collator_selection`
  cumulus/pallets/collator-selection/src/benchmarking.rs
Labels: R0-silent, T12-benchmarks

#3175 [cumulus] Improved check for sane bridge fees calculations
  bridges/primitives/chain-bridge-hub-rococo/src/lib.rs
  bridges/primitives/chain-bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/from_grandpa_chain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/from_parachain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/mod.rs
Labels: R0-silent

#2949 Enable async backing on all testnet system chains
  Cargo.lock
  bridges/primitives/chain-bridge-hub-cumulus/src/lib.rs
  bridges/primitives/chain-bridge-hub-rococo/src/lib.rs
  bridges/primitives/chain-bridge-hub-westend/src/lib.rs
  cumulus/pallets/collator-selection/src/benchmarking.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_westend_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/bridge_to_rococo_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/Cargo.toml
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/constants/Cargo.toml
  cumulus/parachains/runtimes/constants/src/rococo.rs
  cumulus/parachains/runtimes/constants/src/westend.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/Cargo.toml
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/Cargo.toml
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/polkadot-parachain/src/command.rs
  cumulus/polkadot-parachain/src/service.rs
  polkadot/zombienet_tests/smoke/0004-configure-broker.js
  prdoc/pr_2949-async-backing-on-all-testnet-system-chains.prdoc
Labels: T14-system_parachains

#3188 Small fixes coretime related fixes
  polkadot/runtime/parachains/src/configuration/migration/v11.rs
  polkadot/runtime/parachains/src/configuration/tests.rs
  polkadot/runtime/parachains/src/coretime/migration.rs
  polkadot/runtime/parachains/src/scheduler.rs
Labels: A1-insubstantial, R0-silent, I3-annoyance, T8-polkadot

#3162 Enable async backing by default for Rococo/Westend
  polkadot/node/core/prospective-parachains/src/fragment_tree.rs
  polkadot/node/core/prospective-parachains/src/lib.rs
  polkadot/node/malus/src/variants/suggest_garbage_candidate.rs
  polkadot/node/service/src/chain_spec.rs
Labels: R0-silent

#3179 Initial support for building RISC-V runtimes targeting PolkaVM
  .gitlab/pipeline/build.yml
  Cargo.lock
  Cargo.toml
  substrate/primitives/api/Cargo.toml
  substrate/primitives/api/proc-macro/src/impl_runtime_apis.rs
  substrate/primitives/api/src/lib.rs
  substrate/primitives/io/src/lib.rs
  substrate/primitives/runtime-interface/Cargo.toml
  substrate/primitives/runtime-interface/proc-macro/src/runtime_interface/bare_function_interface.rs
  substrate/primitives/runtime-interface/proc-macro/src/runtime_interface/host_function_interface.rs
  substrate/primitives/runtime-interface/src/lib.rs
  substrate/primitives/runtime-interface/src/polkavm.rs
  substrate/utils/wasm-builder/Cargo.toml
  substrate/utils/wasm-builder/src/builder.rs
  substrate/utils/wasm-builder/src/lib.rs
  substrate/utils/wasm-builder/src/prerequisites.rs
  substrate/utils/wasm-builder/src/wasm_project.rs
Labels: R0-silent, I5-enhancement

#3154 Contracts: Stabilize `caller_is_root` API
  prdoc/pr_3154.prdoc
  substrate/frame/contracts/src/wasm/runtime.rs
  substrate/frame/contracts/uapi/src/host.rs
Labels: T7-smart_contracts

#3166 Expose internal functions used by `spawn_tasks`
  prdoc/pr_3166.prdoc
  substrate/client/service/src/builder.rs
  substrate/client/service/src/lib.rs
Labels: T0-node

#3183 Fixup backing group computation time (#3170)
  .gitlab/pipeline/zombienet/polkadot.yml
  polkadot/runtime/parachains/src/runtime_api_impl/v7.rs
  polkadot/zombienet_tests/functional/0011-async-backing-6-seconds-rate.toml
  polkadot/zombienet_tests/functional/0011-async-backing-6-seconds-rate.zndsl
Labels: R0-silent

#2621 Introduce approval-voting/distribution benchmark
  Cargo.lock
  polkadot/node/core/approval-voting/src/criteria.rs
  polkadot/node/core/approval-voting/src/lib.rs
  polkadot/node/core/approval-voting/src/tests.rs
  polkadot/node/core/approval-voting/src/time.rs
  polkadot/node/subsystem-bench/Cargo.toml
  polkadot/node/subsystem-bench/examples/approvals_no_shows.yaml
  polkadot/node/subsystem-bench/examples/approvals_throughput.yaml
  polkadot/node/subsystem-bench/examples/approvals_throughput_best_case.yaml
  polkadot/node/subsystem-bench/examples/approvals_throughput_no_optimisations_enabled.yaml
  polkadot/node/subsystem-bench/src/approval/helpers.rs
  polkadot/node/subsystem-bench/src/approval/message_generator.rs
  polkadot/node/subsystem-bench/src/approval/mock_chain_selection.rs
  polkadot/node/subsystem-bench/src/approval/mod.rs
  polkadot/node/subsystem-bench/src/approval/test_message.rs
  polkadot/node/subsystem-bench/src/availability/av_store_helpers.rs
  polkadot/node/subsystem-bench/src/availability/mod.rs
  polkadot/node/subsystem-bench/src/cli.rs
  polkadot/node/subsystem-bench/src/core/configuration.rs
  polkadot/node/subsystem-bench/src/core/display.rs
  polkadot/node/subsystem-bench/src/core/environment.rs
  polkadot/node/subsystem-bench/src/core/keyring.rs
  polkadot/node/subsystem-bench/src/core/mock/chain_api.rs
  polkadot/node/subsystem-bench/src/core/mock/mod.rs
  polkadot/node/subsystem-bench/src/core/mock/network_bridge.rs
  polkadot/node/subsystem-bench/src/core/mock/runtime_api.rs
  polkadot/node/subsystem-bench/src/core/mod.rs
  polkadot/node/subsystem-bench/src/core/network.rs
  polkadot/node/subsystem-bench/src/subsystem-bench.rs
Labels: R0-silent, T10-tests, T12-benchmarks

#3094 Backport of fix Pools 6->7 migration (#2942)
  .gitlab-ci.yml
  polkadot/node/core/prospective-parachains/src/tests.rs
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/pallet-xcm/src/tests/assets_transfer.rs
  prdoc/pr_2942.prdoc
  substrate/bin/node/cli/tests/websocket_server.rs
  substrate/client/consensus/babe/src/tests.rs
  substrate/frame/nomination-pools/src/migration.rs
  substrate/frame/sassafras/src/data/tickets-sort.md
  substrate/frame/support/test/tests/construct_runtime_ui/deprecated_where_block.stderr
  substrate/frame/support/test/tests/construct_runtime_ui/number_of_pallets_exceeds_tuple_size.stderr
  substrate/frame/support/test/tests/derive_impl_ui/inject_runtime_type_fails_when_type_not_in_scope.stderr
  substrate/frame/support/test/tests/pallet_ui/call_argument_invalid_bound.stderr
  substrate/frame/support/test/tests/pallet_ui/call_argument_invalid_bound_2.stderr
  substrate/frame/support/test/tests/pallet_ui/call_argument_invalid_bound_3.stderr
  substrate/frame/support/test/tests/pallet_ui/call_missing_index.stderr
  substrate/frame/support/test/tests/pallet_ui/call_weight_argument_has_suffix.stderr
  substrate/frame/support/test/tests/pallet_ui/call_weight_const_warning.stderr
  substrate/frame/support/test/tests/pallet_ui/call_weight_const_warning_twice.stderr
  substrate/frame/support/test/tests/pallet_ui/call_weight_inherited_invalid3.stderr
  substrate/frame/support/test/tests/pallet_ui/call_weight_unchecked_warning.stderr
  substrate/frame/support/test/tests/pallet_ui/deprecated_store_attr.stderr
  substrate/frame/support/test/tests/pallet_ui/dev_mode_without_arg_call_index.stderr
  substrate/frame/support/test/tests/pallet_ui/dev_mode_without_arg_max_encoded_len.stderr
  substrate/frame/support/test/tests/pallet_ui/error_does_not_derive_pallet_error.stderr
  substrate/frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr
  substrate/frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen_unnamed.stderr
  substrate/frame/support/test/tests/pallet_ui/storage_info_unsatisfied.stderr
  substrate/frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.stderr
  substrate/frame/support/test/tests/pallet_ui/store_trait_leak_private.stderr
  substrate/primitives/api/test/tests/ui/impl_incorrect_method_signature.stderr
  substrate/primitives/api/test/tests/ui/type_reference_in_impl_runtime_apis_call.stderr
Labels: R0-silent, T1-FRAME

#3160 prospective-parachains: respond with multiple backable candidates
  polkadot/node/core/prospective-parachains/src/fragment_tree.rs
  polkadot/node/core/prospective-parachains/src/lib.rs
  polkadot/node/core/prospective-parachains/src/tests.rs
  polkadot/node/core/provisioner/src/lib.rs
  polkadot/node/core/provisioner/src/tests.rs
  polkadot/node/subsystem-types/src/messages.rs
  polkadot/roadmap/implementers-guide/src/node/backing/prospective-parachains.md
  polkadot/roadmap/implementers-guide/src/node/utility/provisioner.md
  prdoc/pr_3160.prdoc
Labels: T0-node, I5-enhancement, T8-polkadot

#3212 Ranked collective `Add`+`Remove` origins
  cumulus/parachains/runtimes/collectives/collectives-westend/src/ambassador/mod.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/fellowship/mod.rs
  polkadot/runtime/rococo/src/governance/fellowship.rs
  prdoc/pr_3212.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/core-fellowship/src/tests/integration.rs
  substrate/frame/ranked-collective/src/benchmarking.rs
  substrate/frame/ranked-collective/src/lib.rs
  substrate/frame/ranked-collective/src/tests.rs
  substrate/frame/salary/src/tests/integration.rs
  substrate/primitives/runtime/src/traits.rs
Labels: T2-pallets

#3225 Introduce submit_finality_proof_ex call to bridges GRANDPA pallet
  bridges/bin/runtime-common/src/refund_relayer_extension.rs
  bridges/modules/grandpa/README.md
  bridges/modules/grandpa/src/benchmarking.rs
  bridges/modules/grandpa/src/call_ext.rs
  bridges/modules/grandpa/src/lib.rs
  bridges/modules/parachains/src/lib.rs
  bridges/primitives/header-chain/src/lib.rs
  bridges/zombienet/helpers/chains/rococo-at-westend.js
  bridges/zombienet/helpers/chains/westend-at-rococo.js
  prdoc/pr_3225.prdoc
Labels: T15-bridges

#3209 Build more runtimes targeting PolkaVM
  .gitlab/pipeline/build.yml
  Cargo.lock
  Cargo.toml
  substrate/primitives/consensus/beefy/Cargo.toml
  substrate/primitives/merkle-mountain-range/Cargo.toml
  substrate/utils/wasm-builder/src/wasm_project.rs
Labels: R0-silent

#3228 [pallet_xcm] Forgotten migration to XCMv4 + added `try-state` to the `pallet_xcm`
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/pallet-xcm/src/migration.rs
  polkadot/xcm/pallet-xcm/src/tests/mod.rs
  prdoc/pr_3228.prdoc
Labels: T6-XCM

#3158 subsystem-bench: Prepare CI output
  polkadot/node/subsystem-bench/src/approval/mod.rs
  polkadot/node/subsystem-bench/src/availability/mod.rs
  polkadot/node/subsystem-bench/src/cli.rs
  polkadot/node/subsystem-bench/src/core/environment.rs
  polkadot/node/subsystem-bench/src/subsystem-bench.rs
Labels: R0-silent, T12-benchmarks

#3213 [pallet_broker] Remove leases that have already expired in rotate_sale
  substrate/frame/broker/src/tests.rs
  substrate/frame/broker/src/tick_impls.rs
Labels: R0-silent, T2-pallets

#3222 Add try_state and integrity_test to XCM simulator fuzzer
  Cargo.lock
  polkadot/xcm/xcm-simulator/fuzzer/Cargo.toml
  polkadot/xcm/xcm-simulator/fuzzer/README.md
  polkadot/xcm/xcm-simulator/fuzzer/src/fuzz.rs
  polkadot/xcm/xcm-simulator/fuzzer/src/parachain.rs
  polkadot/xcm/xcm-simulator/fuzzer/src/relay_chain.rs
Labels: R0-silent, T10-tests

#3239 subsystem-bench: run cli benchmarks only using config files
  polkadot/node/subsystem-bench/src/approval/message_generator.rs
  polkadot/node/subsystem-bench/src/approval/mod.rs
  polkadot/node/subsystem-bench/src/availability/mod.rs
  polkadot/node/subsystem-bench/src/cli.rs
  polkadot/node/subsystem-bench/src/core/configuration.rs
  polkadot/node/subsystem-bench/src/subsystem-bench.rs
Labels: R0-silent, T12-benchmarks

#3007 Try State Hook for Ranked Collective
  prdoc/pr_3007.prdoc
  substrate/frame/ranked-collective/src/benchmarking.rs
  substrate/frame/ranked-collective/src/lib.rs
  substrate/frame/ranked-collective/src/tests.rs
Labels: T1-FRAME

#3185 contracts: Remove unused benchmarks
  substrate/frame/contracts/benchmarks/README.md
  substrate/frame/contracts/benchmarks/ink_erc20.json
  substrate/frame/contracts/benchmarks/ink_erc20.wasm
  substrate/frame/contracts/benchmarks/ink_erc20_test.wasm
  substrate/frame/contracts/benchmarks/solang_erc20.json
  substrate/frame/contracts/benchmarks/solang_erc20.wasm
  substrate/frame/contracts/src/benchmarking/code.rs
  substrate/frame/contracts/src/benchmarking/mod.rs
Labels: R0-silent

#3243 contracts: Don't fail fast if the `Weight` limit of a cross contract call is too big
  prdoc/pr_3243.prdoc
  substrate/frame/contracts/fixtures/contracts/call_with_limit.rs
  substrate/frame/contracts/src/exec.rs
  substrate/frame/contracts/src/gas.rs
  substrate/frame/contracts/src/tests.rs
Labels: T7-smart_contracts

#3184 contracts: Remove no longer enforced limits from the `Schedule`
  prdoc/pr_3184.prdoc
  substrate/frame/contracts/src/schedule.rs
  substrate/frame/contracts/src/wasm/prepare.rs
Labels: T7-smart_contracts

#3241 Contracts update doc.rs metadata
  substrate/frame/contracts/uapi/Cargo.toml
Labels: R0-silent

#2258 Make BEEFY client keystore generic over BEEFY `AuthorityId` type
  Cargo.lock
  substrate/client/consensus/beefy/Cargo.toml
  substrate/client/consensus/beefy/src/communication/gossip.rs
  substrate/client/consensus/beefy/src/justification.rs
  substrate/client/consensus/beefy/src/keystore.rs
  substrate/client/consensus/beefy/src/round.rs
  substrate/client/consensus/beefy/src/tests.rs
  substrate/client/consensus/beefy/src/worker.rs
  substrate/client/keystore/src/local.rs
  substrate/frame/beefy/src/tests.rs
  substrate/primitives/consensus/beefy/Cargo.toml
  substrate/primitives/consensus/beefy/src/commitment.rs
  substrate/primitives/consensus/beefy/src/lib.rs
  substrate/primitives/consensus/beefy/src/test_utils.rs
  substrate/primitives/core/src/bandersnatch.rs
  substrate/primitives/core/src/bls.rs
  substrate/primitives/core/src/ecdsa.rs
  substrate/primitives/core/src/ed25519.rs
  substrate/primitives/core/src/paired_crypto.rs
  substrate/primitives/core/src/sr25519.rs
  substrate/primitives/keystore/src/lib.rs
  substrate/primitives/keystore/src/testing.rs
Labels: R0-silent, T0-node

#3263 Update README.md - Runtimes on Fellowship Repo
  README.md
Labels: R0-silent

#3244 `bench pallet`: only require `Hash` instead of `Block`
  Cargo.lock
  cumulus/parachain-template/node/src/command.rs
  cumulus/polkadot-parachain/src/command.rs
  polkadot/cli/Cargo.toml
  polkadot/cli/src/command.rs
  prdoc/pr_3244.prdoc
  substrate/bin/node-template/node/src/command.rs
  substrate/bin/node/cli/src/command.rs
  substrate/client/db/src/bench.rs
  substrate/client/db/src/lib.rs
  substrate/utils/frame/benchmarking-cli/src/pallet/command.rs
  substrate/utils/frame/benchmarking-cli/src/storage/write.rs
Labels: T12-benchmarks

#3052 Fixes `TotalValueLocked` out of sync in nomination pools
  Cargo.lock
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_3052.prdoc
  substrate/frame/election-provider-multi-phase/test-staking-e2e/Cargo.toml
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/lib.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/nomination-pools/src/migration.rs
  substrate/frame/nomination-pools/src/mock.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/primitives/staking/src/lib.rs
Labels: T1-FRAME, T8-polkadot, T10-tests

#2061 [FRAME] Parameters pallet
  Cargo.lock
  Cargo.toml
  prdoc/pr_2061.prdoc
  substrate/bin/node/runtime/Cargo.toml
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/examples/kitchensink/Cargo.toml
  substrate/frame/parameters/Cargo.toml
  substrate/frame/parameters/src/benchmarking.rs
  substrate/frame/parameters/src/lib.rs
  substrate/frame/parameters/src/tests/mock.rs
  substrate/frame/parameters/src/tests/mod.rs
  substrate/frame/parameters/src/tests/test_renamed.rs
  substrate/frame/parameters/src/tests/unit.rs
  substrate/frame/parameters/src/weights.rs
  substrate/frame/support/procedural/Cargo.toml
  substrate/frame/support/procedural/src/dynamic_params.rs
  substrate/frame/support/procedural/src/lib.rs
  substrate/frame/support/src/lib.rs
  substrate/frame/support/src/traits.rs
  substrate/frame/support/src/traits/dynamic_params.rs
  substrate/frame/support/test/tests/derive_impl_ui/inject_runtime_type_invalid.stderr
Labels: T2-pallets

#3254 [Backport] Version bumps from 1.7.0 release
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot/node/primitives/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/1.7.0/pr_1222.prdoc
  prdoc/1.7.0/pr_1230.prdoc
  prdoc/1.7.0/pr_1296.prdoc
  prdoc/1.7.0/pr_1313.prdoc
  prdoc/1.7.0/pr_1845.prdoc
  prdoc/1.7.0/pr_1871.prdoc
  prdoc/1.7.0/pr_2125.prdoc
  prdoc/1.7.0/pr_2467.prdoc
  prdoc/1.7.0/pr_2477-use-clone-instead-of-fork-on-pvf.prdoc
  prdoc/1.7.0/pr_2587.prdoc
  prdoc/1.7.0/pr_2657.prdoc
  prdoc/1.7.0/pr_2796.prdoc
  prdoc/1.7.0/pr_2826.prdoc
  prdoc/1.7.0/pr_2889.prdoc
  prdoc/1.7.0/pr_2920.prdoc
  prdoc/1.7.0/pr_2924.prdoc
  prdoc/1.7.0/pr_2942.prdoc
  prdoc/1.7.0/pr_2970.prdoc
  prdoc/1.7.0/pr_3001.prdoc
  prdoc/1.7.0/pr_3009.prdoc
  prdoc/1.7.0/pr_3020.prdoc
  prdoc/1.7.0/pr_3029.prdoc
  prdoc/1.7.0/pr_3040.prdoc
  prdoc/1.7.0/pr_3057.prdoc
  prdoc/1.7.0/pr_3061.prdoc
  prdoc/1.7.0/pr_3077.prdoc
  prdoc/1.7.0/pr_3108.prdoc
  prdoc/1.7.0/pr_3110.prdoc
  prdoc/1.7.0/pr_3156.prdoc
  prdoc/1.7.0/pr_3228.prdoc
Labels: R0-silent, A3-backport, D0-easy

#3236 Add forklift to remaining jobs
  .gitlab-ci.yml
  .gitlab/check-each-crate.py
  .gitlab/pipeline/build.yml
  .gitlab/pipeline/test.yml
  polkadot/scripts/build-only-wasm.sh
Labels: A1-insubstantial, R0-silent

#3047 refactor pvf security module
  polkadot/node/core/pvf/README.md
  polkadot/node/core/pvf/common/Cargo.toml
  polkadot/node/core/pvf/common/src/lib.rs
  polkadot/node/core/pvf/src/host.rs
  polkadot/node/core/pvf/src/lib.rs
  polkadot/node/core/pvf/src/security.rs
Labels: R0-silent, T0-node

#3221 Backport of fix Pools 6->7 migration (#2942) (#3093)
  prdoc/pr_2942.prdoc
  substrate/frame/nomination-pools/src/migration.rs
  substrate/frame/sassafras/src/data/tickets-sort.md
Labels: R0-silent

#3262 subsystem-bench: polish imports
  polkadot/node/subsystem-bench/src/approval/helpers.rs
  polkadot/node/subsystem-bench/src/approval/message_generator.rs
  polkadot/node/subsystem-bench/src/approval/mock_chain_selection.rs
  polkadot/node/subsystem-bench/src/approval/mod.rs
  polkadot/node/subsystem-bench/src/approval/test_message.rs
  polkadot/node/subsystem-bench/src/availability/av_store_helpers.rs
  polkadot/node/subsystem-bench/src/availability/mod.rs
  polkadot/node/subsystem-bench/src/core/configuration.rs
  polkadot/node/subsystem-bench/src/core/display.rs
  polkadot/node/subsystem-bench/src/core/environment.rs
  polkadot/node/subsystem-bench/src/core/mock/av_store.rs
  polkadot/node/subsystem-bench/src/core/mock/chain_api.rs
  polkadot/node/subsystem-bench/src/core/mock/dummy.rs
  polkadot/node/subsystem-bench/src/core/mock/mod.rs
  polkadot/node/subsystem-bench/src/core/mock/network_bridge.rs
  polkadot/node/subsystem-bench/src/core/mock/runtime_api.rs
  polkadot/node/subsystem-bench/src/core/mod.rs
  polkadot/node/subsystem-bench/src/core/network.rs
  polkadot/node/subsystem-bench/src/subsystem-bench.rs
Labels: R0-silent, T12-benchmarks

#3215 transaction-pool: Improve transaction status documentation and add helpers
  substrate/client/transaction-pool/api/src/error.rs
  substrate/client/transaction-pool/api/src/lib.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement

#3260 Bridge zombienet tests refactoring
  bridges/zombienet/README.md
  bridges/zombienet/environments/rococo-westend/helper.sh
  bridges/zombienet/environments/rococo-westend/rococo-init.zndsl
  bridges/zombienet/environments/rococo-westend/rococo.zndsl
  bridges/zombienet/environments/rococo-westend/spawn.sh
  bridges/zombienet/environments/rococo-westend/westend-init.zndsl
  bridges/zombienet/environments/rococo-westend/westend.zndsl
  bridges/zombienet/helpers/best-finalized-header-at-bridged-chain.js
  bridges/zombienet/helpers/native-assets-balance-increased.js
  bridges/zombienet/helpers/relayer-rewards.js
  bridges/zombienet/helpers/wait-hrmp-channel-opened.js
  bridges/zombienet/helpers/wrapped-assets-balance.js
  bridges/zombienet/run-new-test.sh
  bridges/zombienet/run-tests.sh
  bridges/zombienet/scripts/invoke-script.sh
  bridges/zombienet/scripts/start-relayer.sh
  bridges/zombienet/tests/0001-asset-transfer/roc-reaches-westend.zndsl
  bridges/zombienet/tests/0001-asset-transfer/run.sh
  bridges/zombienet/tests/0001-asset-transfer/wnd-reaches-rococo.zndsl
  bridges/zombienet/tests/0001-asset-transfer/wroc-reaches-rococo.zndsl
  bridges/zombienet/tests/0001-asset-transfer/wwnd-reaches-westend.zndsl
  bridges/zombienet/utils/common.sh
  bridges/zombienet/utils/zombienet.sh
  cumulus/parachains/runtimes/bridge-hubs/README.md
  cumulus/scripts/bridges_common.sh
  cumulus/scripts/bridges_rococo_westend.sh
  cumulus/zombienet/bridge-hubs/bridge_hub_rococo_local_network.toml
  cumulus/zombienet/bridge-hubs/bridge_hub_westend_local_network.toml
Labels: R0-silent, T10-tests, T15-bridges

#3257 [ci] Don't run prdoc and lables GHA on master
  .github/workflows/check-labels.yml
  .github/workflows/check-prdoc.yml
Labels: R0-silent

#3223 statement-distribution: Fix CostMinor("Unexpected Statement")
  polkadot/node/network/statement-distribution/src/v2/grid.rs
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  polkadot/node/network/statement-distribution/src/v2/tests/cluster.rs
Labels: R0-silent

#3289 Bump coretime-rococo to get leases fix
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
Labels: R0-silent, T14-system_parachains

#3079 rpc-v2/tx: Implement `transaction_unstable_broadcast` and `transaction_unstable_stop`
  Cargo.lock
  prdoc/pr_3079.prdoc
  substrate/client/rpc-spec-v2/Cargo.toml
  substrate/client/rpc-spec-v2/src/chain_head/mod.rs
  substrate/client/rpc-spec-v2/src/transaction/api.rs
  substrate/client/rpc-spec-v2/src/transaction/error.rs
  substrate/client/rpc-spec-v2/src/transaction/mod.rs
  substrate/client/rpc-spec-v2/src/transaction/tests.rs
  substrate/client/rpc-spec-v2/src/transaction/transaction.rs
  substrate/client/rpc-spec-v2/src/transaction/transaction_broadcast.rs
Labels: I5-enhancement, T3-RPC_API, D1-medium

#3264 Add bridge zombienet test back to the CI
  .gitlab/pipeline/build.yml
  .gitlab/pipeline/publish.yml
  .gitlab/pipeline/zombienet.yml
  .gitlab/pipeline/zombienet/bridges.yml
  docker/dockerfiles/bridges_zombienet_tests_injected.Dockerfile
Labels: R0-silent, T10-tests, T15-bridges

#3280 AlreadyVoting Error - Remove ambiguity
  substrate/frame/conviction-voting/src/lib.rs
Labels: R0-silent, T11-documentation

#3299 Fix(zombienet): allow finality_lag be to be 1 or less and increase timeout
  polkadot/zombienet_tests/misc/0001-paritydb.zndsl
Labels: R0-silent, T10-tests

#3284 Use `TEST_WS` in all remote-externalities tests
  substrate/utils/frame/remote-externalities/src/lib.rs
Labels: R0-silent

#3297 [ci] Fix gitspiegel trigger
  .github/workflows/gitspiegel-trigger.yml
Labels: R0-silent

#3296 Fix compilation on latest nightly because of `stdsimd`
  Cargo.lock
  substrate/bin/node-template/env-setup/.envrc
  substrate/bin/node-template/env-setup/README.md
  substrate/bin/node-template/env-setup/flake.lock
  substrate/bin/node-template/env-setup/flake.nix
  substrate/bin/node-template/env-setup/rust-toolchain.toml
  substrate/scripts/ci/node-template-release/src/main.rs
Labels: R0-silent

#3211 Use dynamic aura slot duration in lookahead collator
  cumulus/client/consensus/aura/src/collators/lookahead.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/polkadot-parachain/src/service.rs
Labels: R0-silent, T14-system_parachains

#3287 [xcm-builder] Replaced deprecated CurrencyAdapter with FungibleAdapter
  bridges/snowbridge/runtime/test-common/src/lib.rs
  cumulus/pallets/xcmp-queue/src/mock.rs
  cumulus/parachain-template/runtime/src/xcm_config.rs
  cumulus/parachains/integration-tests/emulated/common/src/macros.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-rococo/src/tests/reap_identity.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-rococo/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/reap_identity.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/teleport.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/snowbridge.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/people/people-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/people/people-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot/runtime/rococo/src/xcm_config.rs
  polkadot/runtime/westend/src/xcm_config.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/fungible/benchmarking.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/fungible/mock.rs
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/xcm-builder/src/fungible_adapter.rs
  polkadot/xcm/xcm-builder/tests/mock/mod.rs
  polkadot/xcm/xcm-simulator/fuzzer/src/parachain.rs
  polkadot/xcm/xcm-simulator/fuzzer/src/relay_chain.rs
  substrate/frame/contracts/mock-network/src/parachain.rs
  substrate/frame/contracts/mock-network/src/relay_chain.rs
Labels: R0-silent, T6-XCM

#3224 Prepare syncing for parallel sync strategies
  substrate/client/network/sync/src/engine.rs
  substrate/client/network/sync/src/justification_requests.rs
  substrate/client/network/sync/src/lib.rs
  substrate/client/network/sync/src/pending_responses.rs
  substrate/client/network/sync/src/strategy.rs
  substrate/client/network/sync/src/strategy/chain_sync.rs
  substrate/client/network/sync/src/strategy/chain_sync/test.rs
  substrate/client/network/sync/src/strategy/state.rs
Labels: R0-silent, T0-node

#3308 Parachains-Aura: Only produce once per slot
  cumulus/client/consensus/aura/src/collator.rs
  cumulus/client/consensus/aura/src/collators/basic.rs
  cumulus/client/consensus/aura/src/lib.rs
  prdoc/pr_3308.prdoc
Labels: T0-node

#3310 Bridges: add test 0002 to CI
  .gitlab/pipeline/zombienet/bridges.yml
  bridges/zombienet/environments/rococo-westend/spawn.sh
  bridges/zombienet/environments/rococo-westend/start_relayer.sh
  bridges/zombienet/helpers/only-mandatory-headers-synced-when-idle.js
  bridges/zombienet/helpers/utils.js
  bridges/zombienet/run-new-test.sh
  bridges/zombienet/tests/0001-asset-transfer/run.sh
  bridges/zombienet/tests/0002-mandatory-headers-synced-while-idle/rococo-to-westend.zndsl
  bridges/zombienet/tests/0002-mandatory-headers-synced-while-idle/run.sh
  bridges/zombienet/tests/0002-mandatory-headers-synced-while-idle/westend-to-rococo.zndsl
Labels: R0-silent, T10-tests, T15-bridges

#2628 Add XCM documentation to the sdk docs
  Cargo.lock
  docs/sdk/Cargo.toml
  docs/sdk/src/polkadot_sdk/xcm.rs
Labels: R0-silent

#3313 chainHead: Error on duplicate unpin hashes
  substrate/client/rpc-spec-v2/src/chain_head/chain_head.rs
  substrate/client/rpc-spec-v2/src/chain_head/error.rs
  substrate/client/rpc-spec-v2/src/chain_head/subscription/error.rs
  substrate/client/rpc-spec-v2/src/chain_head/subscription/inner.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
Labels: A1-insubstantial, R0-silent, I2-bug, D0-easy

#3232 Validate code when scheduling uprades from registrar
  polkadot/primitives/src/lib.rs
  polkadot/primitives/src/v6/mod.rs
  polkadot/primitives/test-helpers/src/lib.rs
  polkadot/runtime/common/src/integration_tests.rs
  polkadot/runtime/common/src/paras_registrar/mod.rs
  polkadot/runtime/parachains/src/configuration.rs
  polkadot/runtime/parachains/src/inclusion/tests.rs
  polkadot/runtime/parachains/src/paras/benchmarking/pvf_check.rs
  polkadot/runtime/parachains/src/paras/mod.rs
  polkadot/runtime/parachains/src/paras/tests.rs
  prdoc/pr_3232.prdoc
Labels: T8-polkadot

#3230 rpc: bump jsonrpsee v0.22 and fix race in `rpc v2 chain_head`
  Cargo.lock
  cumulus/client/relay-chain-interface/Cargo.toml
  cumulus/client/relay-chain-interface/src/lib.rs
  cumulus/client/relay-chain-rpc-interface/Cargo.toml
  cumulus/client/relay-chain-rpc-interface/src/light_client_worker.rs
  cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs
  cumulus/client/relay-chain-rpc-interface/src/rpc_client.rs
  cumulus/parachain-template/node/Cargo.toml
  cumulus/polkadot-parachain/Cargo.toml
  cumulus/test/service/Cargo.toml
  polkadot/rpc/Cargo.toml
  prdoc/pr_3230.prdoc
  substrate/bin/minimal/node/Cargo.toml
  substrate/bin/node-template/node/Cargo.toml
  substrate/bin/node/cli/Cargo.toml
  substrate/bin/node/rpc/Cargo.toml
  substrate/client/consensus/babe/rpc/Cargo.toml
  substrate/client/consensus/babe/rpc/src/lib.rs
  substrate/client/consensus/beefy/rpc/Cargo.toml
  substrate/client/consensus/beefy/rpc/src/lib.rs
  substrate/client/consensus/grandpa/rpc/Cargo.toml
  substrate/client/consensus/grandpa/rpc/src/lib.rs
  substrate/client/consensus/manual-seal/Cargo.toml
  substrate/client/merkle-mountain-range/rpc/Cargo.toml
  substrate/client/rpc-api/Cargo.toml
  substrate/client/rpc-servers/Cargo.toml
  substrate/client/rpc-servers/src/lib.rs
  substrate/client/rpc-servers/src/middleware.rs
  substrate/client/rpc-servers/src/middleware/metrics.rs
  substrate/client/rpc-servers/src/middleware/mod.rs
  substrate/client/rpc-spec-v2/Cargo.toml
  substrate/client/rpc-spec-v2/src/archive/tests.rs
  substrate/client/rpc-spec-v2/src/chain_head/api.rs
  substrate/client/rpc-spec-v2/src/chain_head/chain_head.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
  substrate/client/rpc-spec-v2/src/transaction/tests.rs
  substrate/client/rpc/Cargo.toml
  substrate/client/rpc/src/author/tests.rs
  substrate/client/rpc/src/dev/tests.rs
  substrate/client/rpc/src/state/tests.rs
  substrate/client/rpc/src/system/tests.rs
  substrate/client/rpc/src/utils.rs
  substrate/client/service/Cargo.toml
  substrate/client/service/src/lib.rs
  substrate/client/sync-state-rpc/Cargo.toml
  substrate/frame/transaction-payment/rpc/Cargo.toml
  substrate/utils/frame/remote-externalities/Cargo.toml
  substrate/utils/frame/rpc/client/Cargo.toml
  substrate/utils/frame/rpc/client/src/lib.rs
  substrate/utils/frame/rpc/state-trie-migration-rpc/Cargo.toml
  substrate/utils/frame/rpc/support/Cargo.toml
  substrate/utils/frame/rpc/support/src/lib.rs
  substrate/utils/frame/rpc/system/Cargo.toml
Labels: T3-RPC_API

#3304 Use simple-mermaid from crates-io
  Cargo.lock
  docs/sdk/Cargo.toml
  substrate/frame/Cargo.toml
  substrate/primitives/runtime/Cargo.toml
Labels: R0-silent

#3334 sc-keystore: Improve docs
  substrate/client/keystore/src/local.rs
  substrate/primitives/core/src/crypto.rs
Labels: R0-silent

#3333 Bridge zombienet tests - move all test scripts to the same folder
  .config/taplo.toml
  .gitlab/pipeline/build.yml
  .gitlab/pipeline/zombienet/bridges.yml
  bridges/testing/README.md
  bridges/testing/environments/rococo-westend/bridge_hub_rococo_local_network.toml
  bridges/testing/environments/rococo-westend/bridge_hub_westend_local_network.toml
  bridges/testing/environments/rococo-westend/bridges_rococo_westend.sh
  bridges/testing/environments/rococo-westend/helper.sh
  bridges/testing/environments/rococo-westend/rococo-init.zndsl
  bridges/testing/environments/rococo-westend/rococo.zndsl
  bridges/testing/environments/rococo-westend/spawn.sh
  bridges/testing/environments/rococo-westend/start_relayer.sh
  bridges/testing/environments/rococo-westend/westend-init.zndsl
  bridges/testing/environments/rococo-westend/westend.zndsl
  bridges/testing/js-helpers/best-finalized-header-at-bridged-chain.js
  bridges/testing/js-helpers/chains/rococo-at-westend.js
  bridges/testing/js-helpers/chains/westend-at-rococo.js
  bridges/testing/js-helpers/native-assets-balance-increased.js
  bridges/testing/js-helpers/only-mandatory-headers-synced-when-idle.js
  bridges/testing/js-helpers/only-required-headers-synced-when-idle.js
  bridges/testing/js-helpers/relayer-rewards.js
  bridges/testing/js-helpers/utils.js
  bridges/testing/js-helpers/wait-hrmp-channel-opened.js
  bridges/testing/js-helpers/wrapped-assets-balance.js
  bridges/testing/run-new-test.sh
  bridges/testing/run-tests.sh
  bridges/testing/scripts/invoke-script.sh
  bridges/testing/scripts/start-relayer.sh
  bridges/testing/scripts/sync-exit.sh
  bridges/testing/tests/0001-asset-transfer/roc-reaches-westend.zndsl
  bridges/testing/tests/0001-asset-transfer/run.sh
  bridges/testing/tests/0001-asset-transfer/wnd-reaches-rococo.zndsl
  bridges/testing/tests/0001-asset-transfer/wroc-reaches-rococo.zndsl
  bridges/testing/tests/0001-asset-transfer/wwnd-reaches-westend.zndsl
  bridges/testing/tests/0002-mandatory-headers-synced-while-idle/rococo-to-westend.zndsl
  bridges/testing/tests/0002-mandatory-headers-synced-while-idle/run.sh
  bridges/testing/tests/0002-mandatory-headers-synced-while-idle/westend-to-rococo.zndsl
  bridges/testing/tests/0003-required-headers-synced-while-active-rococo-to-westend.zndsl
  bridges/testing/tests/0003-required-headers-synced-while-active-westend-to-rococo.zndsl
  bridges/testing/utils/bridges.sh
  bridges/testing/utils/common.sh
  bridges/testing/utils/generate_hex_encoded_call/index.js
  bridges/testing/utils/generate_hex_encoded_call/package-lock.json
  bridges/testing/utils/generate_hex_encoded_call/package.json
  bridges/testing/utils/zombienet.sh
  bridges/zombienet/environments/rococo-westend/helper.sh
  bridges/zombienet/environments/rococo-westend/rococo-init.zndsl
  bridges/zombienet/environments/rococo-westend/rococo.zndsl
  bridges/zombienet/environments/rococo-westend/westend-init.zndsl
  bridges/zombienet/environments/rococo-westend/westend.zndsl
  bridges/zombienet/tests/0001-asset-transfer-works-rococo-to-westend.zndsl
  bridges/zombienet/tests/0001-asset-transfer-works-westend-to-rococo.zndsl
  bridges/zombienet/tests/0001-asset-transfer/roc-reaches-westend.zndsl
  bridges/zombienet/tests/0001-asset-transfer/wnd-reaches-rococo.zndsl
  bridges/zombienet/tests/0002-mandatory-headers-synced-while-idle-rococo-to-westend.zndsl
  bridges/zombienet/tests/0002-mandatory-headers-synced-while-idle-westend-to-rococo.zndsl
  cumulus/parachains/runtimes/bridge-hubs/README.md
  docker/dockerfiles/bridges_zombienet_tests_injected.Dockerfile
Labels: R0-silent, T10-tests, T15-bridges

#2504 [WIP] PoV friendly, multi-block Election Provider Multi-Phase pallet
  Cargo.lock
  Cargo.toml
  substrate/frame/election-provider-multi-block/Cargo.toml
  substrate/frame/election-provider-multi-block/README.md
  substrate/frame/election-provider-multi-block/integration-tests/Cargo.toml
  substrate/frame/election-provider-multi-block/integration-tests/src/lib.rs
  substrate/frame/election-provider-multi-block/integration-tests/src/mock.rs
  substrate/frame/election-provider-multi-block/src/helpers.rs
  substrate/frame/election-provider-multi-block/src/lib.rs
  substrate/frame/election-provider-multi-block/src/mock/mod.rs
  substrate/frame/election-provider-multi-block/src/mock/staking.rs
  substrate/frame/election-provider-multi-block/src/signed/mod.rs
  substrate/frame/election-provider-multi-block/src/signed/tests.rs
  substrate/frame/election-provider-multi-block/src/types.rs
  substrate/frame/election-provider-multi-block/src/unsigned/miner.rs
  substrate/frame/election-provider-multi-block/src/unsigned/mod.rs
  substrate/frame/election-provider-multi-block/src/verifier/impls.rs
  substrate/frame/election-provider-multi-block/src/verifier/mod.rs
  substrate/frame/election-provider-multi-block/src/verifier/tests.rs
  substrate/frame/election-provider-multi-phase/src/lib.rs
  substrate/frame/election-provider-multi-phase/src/mock.rs
  substrate/frame/election-provider-multi-phase/src/signed.rs
  substrate/frame/election-provider-multi-phase/src/unsigned.rs
  substrate/frame/election-provider-support/solution-type/src/codec.rs
  substrate/frame/election-provider-support/solution-type/src/single_page.rs
  substrate/frame/election-provider-support/src/lib.rs
  substrate/frame/election-provider-support/src/onchain.rs
  substrate/frame/staking/src/lib.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/tests.rs
  substrate/primitives/npos-elections/src/lib.rs
  substrate/primitives/staking/src/lib.rs
Labels: T2-pallets, D2-substantial

#1660 Implements a % cap on staking rewards from era inflation
  polkadot/runtime/westend/src/weights/pallet_staking.rs
  prdoc/pr_1660.prdoc
  substrate/frame/nomination-pools/test-staking/src/mock.rs
  substrate/frame/staking/src/benchmarking.rs
  substrate/frame/staking/src/lib.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/tests.rs
  substrate/frame/staking/src/weights.rs
Labels: T2-pallets, T8-polkadot

#3354 [ci] allow fail build-runtimes-polkavm job
  .gitlab/pipeline/build.yml
Labels: R0-silent

#3357 Fix `runtime-benchmarks` feature propagation for cumulus test utils (backport for 1.5)
  Cargo.lock
  cumulus/parachains/runtimes/assets/test-utils/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/test-utils/Cargo.toml
  cumulus/parachains/runtimes/test-utils/Cargo.toml
Labels: R0-silent

#3356 Fix `runtime-benchmarks` feature propagation for cumulus test utils (backport for 1.6)
  Cargo.lock
  cumulus/parachains/runtimes/assets/test-utils/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/test-utils/Cargo.toml
  cumulus/parachains/runtimes/test-utils/Cargo.toml
Labels: R0-silent

#3060 Add retry mechanics to `pallet-scheduler`
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_scheduler.rs
  polkadot/runtime/rococo/src/weights/pallet_scheduler.rs
  polkadot/runtime/westend/src/weights/pallet_scheduler.rs
  prdoc/pr_3060.prdoc
  substrate/frame/scheduler/src/benchmarking.rs
  substrate/frame/scheduler/src/lib.rs
  substrate/frame/scheduler/src/mock.rs
  substrate/frame/scheduler/src/tests.rs
  substrate/frame/scheduler/src/weights.rs
Labels: A0-needs_burnin, I5-enhancement, T2-pallets

#3355 Update subkey README.md
  substrate/bin/utils/subkey/README.md
Labels: R0-silent, T11-documentation

#3348 remove recursion limit
  substrate/client/executor/src/lib.rs
  substrate/frame/collective/src/lib.rs
  substrate/frame/core-fellowship/src/lib.rs
  substrate/frame/ranked-collective/src/lib.rs
  substrate/frame/salary/src/lib.rs
  substrate/frame/support/procedural/tools/derive/src/lib.rs
Labels: R0-silent

#3337 fix(zombienet): docker `img` version to use in merge queues for bridges
  .gitlab/pipeline/zombienet/bridges.yml
Labels: R0-silent, T10-tests, T15-bridges

#3358 do not block finality for "disabled" disputes
  polkadot/node/core/dispute-coordinator/src/import.rs
  polkadot/node/core/dispute-coordinator/src/initialized.rs
  polkadot/node/core/dispute-coordinator/src/lib.rs
  polkadot/node/core/dispute-coordinator/src/tests.rs
  prdoc/pr_3358.prdoc
Labels: T0-node

#3301 rpc server: add rate limiting middleware
  Cargo.lock
  cumulus/test/service/src/lib.rs
  polkadot/node/test/service/src/lib.rs
  prdoc/pr_3301.prdoc
  substrate/bin/node/cli/benches/block_production.rs
  substrate/bin/node/cli/benches/transaction_pool.rs
  substrate/client/cli/src/commands/run_cmd.rs
  substrate/client/cli/src/config.rs
  substrate/client/cli/src/runner.rs
  substrate/client/rpc-servers/Cargo.toml
  substrate/client/rpc-servers/src/lib.rs
  substrate/client/rpc-servers/src/middleware/mod.rs
  substrate/client/rpc-servers/src/middleware/rate_limit.rs
  substrate/client/service/src/config.rs
  substrate/client/service/src/lib.rs
  substrate/client/service/test/src/lib.rs
Labels: T0-node

#3325 Ensure referenda `TracksInfo` is sorted
  prdoc/pr_3308.prdoc
  prdoc/pr_3325.prdoc
  substrate/frame/referenda/src/lib.rs
  substrate/frame/referenda/src/types.rs
Labels: T2-pallets

#3373 Remove unused `im-online` weights
  polkadot/runtime/rococo/src/weights/mod.rs
  polkadot/runtime/rococo/src/weights/pallet_im_online.rs
  polkadot/runtime/westend/src/weights/mod.rs
  polkadot/runtime/westend/src/weights/pallet_im_online.rs
Labels: R0-silent, T2-pallets

#3363 Make `sp-keystore` `no_std`-compatible and fix the `build-runtimes-polkavm` CI job
  .gitlab/pipeline/build.yml
  Cargo.lock
  substrate/primitives/externalities/src/extensions.rs
  substrate/primitives/keystore/Cargo.toml
  substrate/primitives/keystore/src/lib.rs
Labels: R0-silent

#3372 Fix documentation dead link
  substrate/client/cli/src/commands/run_cmd.rs
Labels: R0-silent, T11-documentation

#3380 Update coretime-westend bootnodes
  cumulus/parachains/chain-specs/coretime-westend.json
Labels: R0-silent

#3385 Do not block finality for "disabled" disputes (#3358)
  polkadot/node/core/dispute-coordinator/src/import.rs
  polkadot/node/core/dispute-coordinator/src/initialized.rs
  polkadot/node/core/dispute-coordinator/src/lib.rs
  polkadot/node/core/dispute-coordinator/src/tests.rs
  prdoc/pr_3385.prdoc
Labels: A3-backport

#3258 gossip-support: add unittests for update authorities
  Cargo.lock
  polkadot/node/network/gossip-support/Cargo.toml
  polkadot/node/network/gossip-support/src/lib.rs
  polkadot/node/network/gossip-support/src/tests.rs
Labels: R0-silent

#3370 removed `pallet::getter` from `pallet-sudo`
  substrate/frame/sudo/src/extension.rs
  substrate/frame/sudo/src/lib.rs
  substrate/frame/sudo/src/tests.rs
Labels: R0-silent, T13-deprecation

#3086 Contracts: xcm host fn fixes
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/pallet-xcm/src/tests/mod.rs
  polkadot/xcm/xcm-builder/src/controller.rs
  substrate/frame/contracts/fixtures/contracts/xcm_execute.rs
  substrate/frame/contracts/mock-network/src/lib.rs
  substrate/frame/contracts/mock-network/src/tests.rs
  substrate/frame/contracts/src/exec.rs
  substrate/frame/contracts/src/gas.rs
  substrate/frame/contracts/src/wasm/mod.rs
  substrate/frame/contracts/src/wasm/runtime.rs
  substrate/frame/contracts/uapi/src/host.rs
  substrate/frame/contracts/uapi/src/host/riscv32.rs
  substrate/frame/contracts/uapi/src/host/wasm32.rs
Labels: R0-silent

#2903 implement ConversionToAssetBalance in asset-rate
  prdoc/pr_2903.prdoc
  substrate/frame/asset-rate/src/lib.rs
  substrate/frame/asset-rate/src/tests.rs
Labels: T1-FRAME

#3405 Downgrade log message to `trace`
  polkadot/node/core/prospective-parachains/src/lib.rs
Labels: R0-silent

#3384 Contracts: Stabilize APIs
  prdoc/pr_3384.prdoc
  substrate/frame/contracts/fixtures/contracts/call.rs
  substrate/frame/contracts/fixtures/contracts/call_return_code.rs
  substrate/frame/contracts/fixtures/contracts/call_runtime_and_call.rs
  substrate/frame/contracts/fixtures/contracts/call_with_limit.rs
  substrate/frame/contracts/fixtures/contracts/caller_contract.rs
  substrate/frame/contracts/fixtures/contracts/chain_extension_temp_storage.rs
  substrate/frame/contracts/fixtures/contracts/create_storage_and_call.rs
  substrate/frame/contracts/fixtures/contracts/create_storage_and_instantiate.rs
  substrate/frame/contracts/fixtures/contracts/destroy_and_transfer.rs
  substrate/frame/contracts/fixtures/contracts/instantiate_return_code.rs
  substrate/frame/contracts/fixtures/contracts/locking_delegate_dependency.rs
  substrate/frame/contracts/fixtures/contracts/reentrance_count_call.rs
  substrate/frame/contracts/fixtures/contracts/self_destruct.rs
  substrate/frame/contracts/src/benchmarking/mod.rs
  substrate/frame/contracts/src/exec.rs
  substrate/frame/contracts/src/lib.rs
  substrate/frame/contracts/src/schedule.rs
  substrate/frame/contracts/src/storage.rs
  substrate/frame/contracts/src/tests.rs
  substrate/frame/contracts/src/wasm/mod.rs
  substrate/frame/contracts/src/wasm/runtime.rs
  substrate/frame/contracts/src/weights.rs
  substrate/frame/contracts/uapi/src/host.rs
  substrate/frame/contracts/uapi/src/host/riscv32.rs
  substrate/frame/contracts/uapi/src/host/wasm32.rs
Labels: T7-smart_contracts

#3409 Externalize received fees checks from `receive_reserve_asset_deposited_from_different_consensus_works`
  Cargo.lock
  cumulus/parachains/runtimes/assets/asset-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/assets/test-utils/Cargo.toml
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases_over_bridge.rs
Labels: R0-silent

#3364 rpc server: make possible to disable/enable batch requests
  .gitlab/pipeline/check.yml
  cumulus/client/cli/src/lib.rs
  cumulus/test/service/src/lib.rs
  polkadot/node/test/service/src/lib.rs
  prdoc/pr_3364.prdoc
  substrate/bin/node/cli/benches/block_production.rs
  substrate/bin/node/cli/benches/transaction_pool.rs
  substrate/client/cli/src/commands/run_cmd.rs
  substrate/client/cli/src/config.rs
  substrate/client/cli/src/runner.rs
  substrate/client/rpc-servers/src/lib.rs
  substrate/client/service/src/config.rs
  substrate/client/service/src/lib.rs
  substrate/client/service/test/src/lib.rs
Labels: T0-node

#3410 Nits found during the bumping fellows repo
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/common/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
  polkadot/runtime/common/src/impls.rs
  polkadot/xcm/src/lib.rs
  substrate/frame/asset-conversion/src/lib.rs
Labels: R0-silent

#3401 nit: add prdoc for 3370
  prdoc/pr_3370.prdoc
Labels: R0-silent

#3303 remove bound on accountID in AssetFeeAsExistentialDepositMultiplier
  cumulus/parachains/common/src/xcm_config.rs
Labels: R0-silent

#3418 sc-consensus-beefy: reduce log levels
  substrate/client/consensus/beefy/src/aux_schema.rs
  substrate/client/consensus/beefy/src/lib.rs
  substrate/client/consensus/beefy/src/worker.rs
Labels: R0-silent, T0-node

#3417 Backport patch for xcm fungible benchmarks required by new FungibleAdapter
  polkadot/xcm/pallet-xcm-benchmarks/src/fungible/benchmarking.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/fungible/mock.rs
Labels: R0-silent

#3422 Backport patch for xcm fungible benchmarks required by new FungibleAdapter for 1.6
  Cargo.lock
  polkadot/xcm/pallet-xcm-benchmarks/src/fungible/benchmarking.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/fungible/mock.rs
Labels: R0-silent

#3416 Fix failing release notifications GHA
  .github/workflows/release-99_notif-published.yml
Labels: R0-silent, D0-easy

#3395 benchmarking-cli: add --list-pallets and --all options
  prdoc/pr_3395.prdoc
  substrate/scripts/run_all_benchmarks.sh
  substrate/utils/frame/benchmarking-cli/src/pallet/command.rs
  substrate/utils/frame/benchmarking-cli/src/pallet/mod.rs
Labels: T12-benchmarks

#3321 rpc-v2/tx: Remove the broadcast event from `transaction_submitAndWatch`
  substrate/client/rpc-spec-v2/src/transaction/event.rs
  substrate/client/rpc-spec-v2/src/transaction/mod.rs
  substrate/client/rpc-spec-v2/src/transaction/transaction.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement, D0-easy

#3389 ProposerFactory impl Clone
  substrate/client/basic-authorship/src/basic_authorship.rs
Labels: R0-silent

#3371 removed `pallet::getter` from example pallets
  cumulus/parachain-template/pallets/template/src/lib.rs
  cumulus/parachain-template/pallets/template/src/tests.rs
  prdoc/pr_3371.prdoc
  substrate/bin/node-template/pallets/template/src/lib.rs
  substrate/bin/node-template/pallets/template/src/tests.rs
  substrate/frame/examples/basic/src/benchmarking.rs
  substrate/frame/examples/basic/src/lib.rs
  substrate/frame/examples/basic/src/tests.rs
  substrate/frame/examples/kitchensink/src/benchmarking.rs
  substrate/frame/examples/kitchensink/src/lib.rs
  substrate/frame/examples/offchain-worker/src/lib.rs
  substrate/frame/examples/split/src/lib.rs
Labels: T13-deprecation

#3430 Add matrix public channels for release announcements
  .github/workflows/release-99_notif-published.yml
Labels: R0-silent, D0-easy

#3439 Fix `wasm-builder` not exiting if compilation fails
  substrate/utils/wasm-builder/src/wasm_project.rs
Labels: R0-silent, I2-bug

#3435 sc-consensus-beefy: pump gossip engine while waiting for initialization conditions
  prdoc/pr_3435.prdoc
  substrate/client/consensus/beefy/src/communication/gossip.rs
  substrate/client/consensus/beefy/src/communication/mod.rs
  substrate/client/consensus/beefy/src/import.rs
  substrate/client/consensus/beefy/src/lib.rs
  substrate/client/consensus/beefy/src/tests.rs
  substrate/client/consensus/beefy/src/worker.rs
  substrate/primitives/consensus/beefy/src/commitment.rs
Labels: T0-node

#3340 Fix `DepositReserveAsset` fees payment
  Cargo.lock
  polkadot/node/test/service/src/chain_spec.rs
  polkadot/runtime/test-runtime/src/xcm_config.rs
  polkadot/xcm/xcm-executor/integration-tests/Cargo.toml
  polkadot/xcm/xcm-executor/integration-tests/src/lib.rs
  polkadot/xcm/xcm-executor/src/lib.rs
Labels: R0-silent, T6-XCM

#3459 prdoc: Print errors on CI
  .github/workflows/check-prdoc.yml
Labels: R0-silent

#3415 Contracts Add new version for marking new stable API
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/contracts.rs
  prdoc/pr_3415.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/contracts/mock-network/src/parachain/contracts_config.rs
  substrate/frame/contracts/src/lib.rs
  substrate/frame/contracts/src/tests.rs
Labels: T7-smart_contracts

#3324 pallet-membership weights
  prdoc/pr_3324.prdoc
  substrate/frame/membership/src/lib.rs
  substrate/frame/membership/src/weights.rs
Labels: T2-pallets

#3002 PoV Reclaim Runtime Side
  .gitlab/pipeline/check.yml
  Cargo.lock
  Cargo.toml
  cumulus/pallets/parachain-system/src/validate_block/implementation.rs
  cumulus/pallets/parachain-system/src/validate_block/tests.rs
  cumulus/pallets/parachain-system/src/validate_block/trie_recorder.rs
  cumulus/parachain-template/node/src/command.rs
  cumulus/parachain-template/node/src/service.rs
  cumulus/parachain-template/runtime/Cargo.toml
  cumulus/parachain-template/runtime/src/lib.rs
  cumulus/polkadot-parachain/src/command.rs
  cumulus/polkadot-parachain/src/service.rs
  cumulus/primitives/proof-size-hostfunction/src/lib.rs
  cumulus/primitives/storage-weight-reclaim/Cargo.toml
  cumulus/primitives/storage-weight-reclaim/src/lib.rs
  cumulus/test/client/Cargo.toml
  cumulus/test/client/src/lib.rs
  cumulus/test/runtime/Cargo.toml
  cumulus/test/runtime/src/lib.rs
  cumulus/test/service/Cargo.toml
  cumulus/test/service/src/lib.rs
  prdoc/pr_3002.prdoc
  substrate/frame/system/src/lib.rs
  substrate/primitives/weights/src/weight_meter.rs
  substrate/test-utils/client/src/lib.rs
Labels: T0-node, T1-FRAME, T5-host_functions, T9-cumulus

#3462 Bridge zombienet tests: move all "framework" files under one folder
  bridges/testing/environments/rococo-westend/bridges_rococo_westend.sh
  bridges/testing/environments/rococo-westend/helper.sh
  bridges/testing/environments/rococo-westend/rococo-init.zndsl
  bridges/testing/environments/rococo-westend/rococo.zndsl
  bridges/testing/environments/rococo-westend/spawn.sh
  bridges/testing/environments/rococo-westend/start_relayer.sh
  bridges/testing/environments/rococo-westend/westend-init.zndsl
  bridges/testing/environments/rococo-westend/westend.zndsl
  bridges/testing/framework/js-helpers/best-finalized-header-at-bridged-chain.js
  bridges/testing/framework/js-helpers/chains/rococo-at-westend.js
  bridges/testing/framework/js-helpers/chains/westend-at-rococo.js
  bridges/testing/framework/js-helpers/native-assets-balance-increased.js
  bridges/testing/framework/js-helpers/only-mandatory-headers-synced-when-idle.js
  bridges/testing/framework/js-helpers/only-required-headers-synced-when-idle.js
  bridges/testing/framework/js-helpers/relayer-rewards.js
  bridges/testing/framework/js-helpers/utils.js
  bridges/testing/framework/js-helpers/wait-hrmp-channel-opened.js
  bridges/testing/framework/js-helpers/wrapped-assets-balance.js
  bridges/testing/framework/utils/bridges.sh
  bridges/testing/framework/utils/common.sh
  bridges/testing/framework/utils/generate_hex_encoded_call/index.js
  bridges/testing/framework/utils/generate_hex_encoded_call/package-lock.json
  bridges/testing/framework/utils/generate_hex_encoded_call/package.json
  bridges/testing/framework/utils/zombienet.sh
  bridges/testing/run-new-test.sh
  bridges/testing/tests/0001-asset-transfer/roc-reaches-westend.zndsl
  bridges/testing/tests/0001-asset-transfer/run.sh
  bridges/testing/tests/0001-asset-transfer/wnd-reaches-rococo.zndsl
  bridges/testing/tests/0001-asset-transfer/wroc-reaches-rococo.zndsl
  bridges/testing/tests/0001-asset-transfer/wwnd-reaches-westend.zndsl
  bridges/testing/tests/0002-mandatory-headers-synced-while-idle/rococo-to-westend.zndsl
  bridges/testing/tests/0002-mandatory-headers-synced-while-idle/run.sh
  bridges/testing/tests/0002-mandatory-headers-synced-while-idle/westend-to-rococo.zndsl
  docker/dockerfiles/bridges_zombienet_tests_injected.Dockerfile
Labels: R0-silent, T10-tests, T15-bridges

#3231 Runtime: allow backing multiple candidates of same parachain on different cores
  .gitlab/pipeline/zombienet/polkadot.yml
  Cargo.lock
  polkadot/node/core/backing/Cargo.toml
  polkadot/node/core/backing/src/lib.rs
  polkadot/node/core/backing/src/tests/mod.rs
  polkadot/node/core/provisioner/src/lib.rs
  polkadot/node/core/provisioner/src/tests.rs
  polkadot/primitives/src/v6/mod.rs
  polkadot/runtime/parachains/Cargo.toml
  polkadot/runtime/parachains/src/builder.rs
  polkadot/runtime/parachains/src/inclusion/mod.rs
  polkadot/runtime/parachains/src/inclusion/tests.rs
  polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs
  polkadot/runtime/parachains/src/paras_inherent/mod.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
  polkadot/runtime/parachains/src/paras_inherent/weights.rs
  polkadot/zombienet_tests/functional/0012-elastic-scaling-mvp.toml
  polkadot/zombienet_tests/functional/0012-elastic-scaling-mvp.zndsl
  polkadot/zombienet_tests/functional/0012-enable-node-feature.js
  polkadot/zombienet_tests/functional/0012-register-para.js
  prdoc/pr_3231.prdoc
Labels: I5-enhancement, T8-polkadot

#3447 Use generic hash for runtime wasm in resolve_state_version_from_wasm
  prdoc/pr_3447.prdoc
  substrate/client/chain-spec/src/genesis_block.rs
  substrate/client/service/src/client/client.rs
Labels: T0-node

#3457 Remove redundant parachains assigner pallet.
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
Labels: R0-silent

#3465 [pallet-xcm] Adjust benchmarks (teleport_assets/reserve_transfer_assets) not relying on ED (patch for 1.7.0)
  Cargo.lock
  cumulus/pallets/parachain-system/Cargo.toml
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/primitives/utility/Cargo.toml
  cumulus/primitives/utility/src/lib.rs
  polkadot/runtime/common/Cargo.toml
  polkadot/runtime/common/src/xcm_sender.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/xcm_config.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/lib.rs
  polkadot/xcm/pallet-xcm/src/benchmarking.rs
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/xcm-builder/src/currency_adapter.rs
  polkadot/xcm/xcm-builder/src/fungible_adapter.rs
  polkadot/xcm/xcm-builder/src/fungibles_adapter.rs
  polkadot/xcm/xcm-builder/src/lib.rs
  polkadot/xcm/xcm-builder/src/routing.rs
Labels: R0-silent, T6-XCM

#3419 Add more debug logs to understand if statement-distribution misbehaving
  polkadot/node/network/statement-distribution/src/v2/cluster.rs
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  polkadot/node/network/statement-distribution/src/v2/requests.rs
Labels: R0-silent

#3464 [pallet-xcm] Adjust benchmarks (teleport_assets/reserve_transfer_assets) not relying on ED
  Cargo.lock
  cumulus/pallets/parachain-system/Cargo.toml
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/primitives/utility/Cargo.toml
  cumulus/primitives/utility/src/lib.rs
  polkadot/runtime/common/Cargo.toml
  polkadot/runtime/common/src/xcm_sender.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/xcm_config.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/lib.rs
  polkadot/xcm/pallet-xcm/src/benchmarking.rs
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/xcm-builder/src/currency_adapter.rs
  polkadot/xcm/xcm-builder/src/fungible_adapter.rs
  polkadot/xcm/xcm-builder/src/fungibles_adapter.rs
  polkadot/xcm/xcm-builder/src/lib.rs
  polkadot/xcm/xcm-builder/src/routing.rs
Labels: R0-silent, T6-XCM

#3411 add Encointer as trusted teleporter for Westend
  polkadot/runtime/westend/constants/src/lib.rs
  polkadot/runtime/westend/src/xcm_config.rs
  prdoc/pr_3411.prdoc
Labels: R0-silent

#3476 Add more debug logs to understand if statement-distribution misbehaving
  polkadot/node/network/statement-distribution/src/v2/cluster.rs
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  polkadot/node/network/statement-distribution/src/v2/requests.rs
Labels: R0-silent

#3469 Fix multiple cores assignments 1.7
  .gitlab/pipeline/zombienet/polkadot.yml
  Cargo.lock
  polkadot/node/core/backing/Cargo.toml
  polkadot/node/core/backing/src/error.rs
  polkadot/node/core/backing/src/lib.rs
  polkadot/node/core/backing/src/tests/mod.rs
  polkadot/node/core/backing/src/tests/prospective_parachains.rs
  polkadot/node/core/provisioner/src/lib.rs
  polkadot/node/core/provisioner/src/tests.rs
  polkadot/primitives/Cargo.toml
  polkadot/primitives/src/v6/mod.rs
  polkadot/primitives/src/vstaging/mod.rs
  polkadot/runtime/parachains/Cargo.toml
  polkadot/runtime/parachains/src/builder.rs
  polkadot/runtime/parachains/src/inclusion/mod.rs
  polkadot/runtime/parachains/src/inclusion/tests.rs
  polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs
  polkadot/runtime/parachains/src/paras_inherent/mod.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
  polkadot/runtime/parachains/src/paras_inherent/weights.rs
  polkadot/statement-table/Cargo.toml
  polkadot/statement-table/src/generic.rs
  polkadot/statement-table/src/lib.rs
  polkadot/zombienet_tests/functional/0012-elastic-scaling-mvp.toml
  polkadot/zombienet_tests/functional/0012-elastic-scaling-mvp.zndsl
  polkadot/zombienet_tests/functional/0012-enable-node-feature.js
  polkadot/zombienet_tests/functional/0012-register-para.js
  prdoc/pr_3469.prdoc
Labels: A3-backport

#3477 Fix multiple cores 1.8
  .gitlab/pipeline/zombienet/polkadot.yml
  Cargo.lock
  polkadot/node/core/backing/Cargo.toml
  polkadot/node/core/backing/src/error.rs
  polkadot/node/core/backing/src/lib.rs
  polkadot/node/core/backing/src/tests/mod.rs
  polkadot/node/core/backing/src/tests/prospective_parachains.rs
  polkadot/node/core/provisioner/src/lib.rs
  polkadot/node/core/provisioner/src/tests.rs
  polkadot/primitives/Cargo.toml
  polkadot/primitives/src/v6/mod.rs
  polkadot/primitives/src/vstaging/mod.rs
  polkadot/runtime/parachains/Cargo.toml
  polkadot/runtime/parachains/src/builder.rs
  polkadot/runtime/parachains/src/inclusion/mod.rs
  polkadot/runtime/parachains/src/inclusion/tests.rs
  polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs
  polkadot/runtime/parachains/src/paras_inherent/mod.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
  polkadot/runtime/parachains/src/paras_inherent/weights.rs
  polkadot/statement-table/Cargo.toml
  polkadot/statement-table/src/generic.rs
  polkadot/statement-table/src/lib.rs
  polkadot/zombienet_tests/functional/0012-elastic-scaling-mvp.toml
  polkadot/zombienet_tests/functional/0012-elastic-scaling-mvp.zndsl
  polkadot/zombienet_tests/functional/0012-enable-node-feature.js
  polkadot/zombienet_tests/functional/0012-register-para.js
  prdoc/prpr_3477.prdoc
Labels: A3-backport

#3478 frame-support: Improve error reporting when having too many pallets
  substrate/frame/support/procedural/src/construct_runtime/mod.rs
  substrate/frame/support/test/tests/construct_runtime_ui/number_of_pallets_exceeds_tuple_size.stderr
Labels: R0-silent

#2935 Introduce Notification block pinning limit
  Cargo.lock
  substrate/client/api/src/client.rs
  substrate/client/db/src/lib.rs
  substrate/client/db/src/pinned_blocks_cache.rs
  substrate/client/service/Cargo.toml
  substrate/client/service/src/client/client.rs
  substrate/client/service/src/client/mod.rs
  substrate/client/service/src/client/notification_pinning.rs
Labels: R0-silent, T0-node

#3446 Cleanup String::from_utf8
  substrate/utils/frame/benchmarking-cli/src/pallet/command.rs
  substrate/utils/frame/benchmarking-cli/src/pallet/writer.rs
Labels: R0-silent

#3376 fix(zombienet): increase timeout in download artifacts
  polkadot/zombienet_tests/misc/0002-upgrade-node.zndsl
Labels: R0-silent, T10-tests

#3424 Snowbridge benchmark tests fix
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
Labels: R0-silent

#3490 Bridge zombienet tests: Check amount received at destination
  bridges/testing/environments/rococo-westend/bridges_rococo_westend.sh
  bridges/testing/framework/js-helpers/native-assets-balance-increased.js
  bridges/testing/tests/0001-asset-transfer/roc-reaches-westend.zndsl
  bridges/testing/tests/0001-asset-transfer/wnd-reaches-rococo.zndsl
  bridges/testing/tests/0001-asset-transfer/wroc-reaches-rococo.zndsl
  bridges/testing/tests/0001-asset-transfer/wwnd-reaches-westend.zndsl
Labels: R0-silent, T10-tests, T15-bridges

#3362 Add documentation around FRAME Origin
  .gitlab/pipeline/build.yml
  Cargo.lock
  docs/mermaid/IA.mmd
  docs/mermaid/outer_runtime_types.mmd
  docs/sdk/Cargo.toml
  docs/sdk/headers/header.html
  docs/sdk/headers/theme.css
  docs/sdk/headers/toc.html
  docs/sdk/src/guides/your_first_pallet/mod.rs
  docs/sdk/src/lib.rs
  docs/sdk/src/meta_contributing.rs
  docs/sdk/src/reference_docs/extrinsic_encoding.rs
  docs/sdk/src/reference_docs/frame_composite_enums.rs
  docs/sdk/src/reference_docs/frame_origin.rs
  docs/sdk/src/reference_docs/frame_runtime_types.rs
  docs/sdk/src/reference_docs/mod.rs
  substrate/frame/src/lib.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/origin.rs
  substrate/frame/support/procedural/src/lib.rs
  substrate/frame/support/src/lib.rs
  substrate/frame/system/src/lib.rs
Labels: R0-silent, T11-documentation

#3497 Backport: Fix multiple cores assignments 1.7 (#3469)
  .gitlab/pipeline/zombienet/polkadot.yml
  Cargo.lock
  polkadot/node/core/backing/Cargo.toml
  polkadot/node/core/backing/src/error.rs
  polkadot/node/core/backing/src/lib.rs
  polkadot/node/core/backing/src/tests/mod.rs
  polkadot/node/core/backing/src/tests/prospective_parachains.rs
  polkadot/node/core/provisioner/src/lib.rs
  polkadot/node/core/provisioner/src/tests.rs
  polkadot/primitives/Cargo.toml
  polkadot/primitives/src/v6/mod.rs
  polkadot/primitives/src/vstaging/mod.rs
  polkadot/runtime/parachains/Cargo.toml
  polkadot/runtime/parachains/src/builder.rs
  polkadot/runtime/parachains/src/inclusion/mod.rs
  polkadot/runtime/parachains/src/inclusion/tests.rs
  polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs
  polkadot/runtime/parachains/src/paras_inherent/mod.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
  polkadot/runtime/parachains/src/paras_inherent/weights.rs
  polkadot/statement-table/Cargo.toml
  polkadot/statement-table/src/generic.rs
  polkadot/statement-table/src/lib.rs
  polkadot/zombienet_tests/functional/0012-elastic-scaling-mvp.toml
  polkadot/zombienet_tests/functional/0012-elastic-scaling-mvp.zndsl
  polkadot/zombienet_tests/functional/0012-enable-node-feature.js
  polkadot/zombienet_tests/functional/0012-register-para.js
  prdoc/pr_3469.prdoc
Labels: R0-silent

#3193 rpc-v2/tx/tests: Add transaction broadcast tests and check propagated tx status
  substrate/client/rpc-spec-v2/src/chain_head/test_utils.rs
  substrate/client/rpc-spec-v2/src/transaction/tests.rs
  substrate/client/rpc-spec-v2/src/transaction/tests/executor.rs
  substrate/client/rpc-spec-v2/src/transaction/tests/middleware_pool.rs
  substrate/client/rpc-spec-v2/src/transaction/tests/mod.rs
  substrate/client/rpc-spec-v2/src/transaction/tests/setup.rs
  substrate/client/rpc-spec-v2/src/transaction/tests/transaction_broadcast_tests.rs
  substrate/client/transaction-pool/src/lib.rs
  substrate/client/transaction-pool/tests/pool.rs
  substrate/test-utils/runtime/transaction-pool/src/lib.rs
Labels: A1-insubstantial, R0-silent, T3-RPC_API

#3441 [prdoc] Optional SemVer bumps and Docs
  docs/RELEASE.md
  prdoc/schema_user.json
Labels: R0-silent, T11-documentation

#3187 PVF: re-preparing artifact on failed runtime construction
  polkadot/node/core/candidate-validation/src/lib.rs
  polkadot/node/core/pvf/common/src/error.rs
  polkadot/node/core/pvf/common/src/execute.rs
  polkadot/node/core/pvf/common/src/executor_interface.rs
  polkadot/node/core/pvf/execute-worker/src/lib.rs
  polkadot/node/core/pvf/src/artifacts.rs
  polkadot/node/core/pvf/src/error.rs
  polkadot/node/core/pvf/src/execute/mod.rs
  polkadot/node/core/pvf/src/execute/queue.rs
  polkadot/node/core/pvf/src/execute/worker_interface.rs
  polkadot/node/core/pvf/src/host.rs
  polkadot/node/core/pvf/tests/it/main.rs
  polkadot/primitives/src/v6/executor_params.rs
  polkadot/roadmap/implementers-guide/src/node/utility/pvf-host-and-workers.md
  prdoc/pr_3187.prdoc
Labels: T0-node

#3501 Snowbridge - Extract Ethereum Chain ID
  Cargo.lock
  bridges/snowbridge/pallets/ethereum-client/Cargo.toml
  bridges/snowbridge/pallets/inbound-queue/Cargo.toml
  bridges/snowbridge/pallets/inbound-queue/fixtures/Cargo.toml
  bridges/snowbridge/pallets/outbound-queue/Cargo.toml
  bridges/snowbridge/pallets/outbound-queue/merkle-tree/Cargo.toml
  bridges/snowbridge/pallets/outbound-queue/runtime-api/Cargo.toml
  bridges/snowbridge/pallets/system/Cargo.toml
  bridges/snowbridge/pallets/system/runtime-api/Cargo.toml
  bridges/snowbridge/primitives/beacon/Cargo.toml
  bridges/snowbridge/primitives/core/Cargo.toml
  bridges/snowbridge/primitives/ethereum/Cargo.toml
  bridges/snowbridge/primitives/router/Cargo.toml
  bridges/snowbridge/runtime/runtime-common/Cargo.toml
  bridges/snowbridge/runtime/test-common/Cargo.toml
  bridges/snowbridge/runtime/test-common/src/lib.rs
  bridges/snowbridge/scripts/contribute-upstream.sh
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/snowbridge.rs
Labels: R0-silent

#3510 Fixup multi-collator parachain transition to async backing
  cumulus/client/consensus/aura/src/lib.rs
  cumulus/polkadot-parachain/src/service.rs
  prdoc/pr_3510.prdoc
  substrate/bin/node-template/node/src/service.rs
Labels: T9-cumulus

#3491 [Deprecation] Remove sp_weights::OldWeight
  prdoc/pr_3491.prdoc
  substrate/frame/contracts/src/wasm/mod.rs
  substrate/primitives/weights/src/lib.rs
  substrate/primitives/weights/src/weight_meter.rs
Labels: T1-FRAME

#3181 Remove `AssignmentProviderConfig` and use parameters from `HostConfiguration` instead
  cumulus/zombienet/tests/0002-pov_recovery.toml
  polkadot/node/service/src/chain_spec.rs
  polkadot/node/test/service/src/chain_spec.rs
  polkadot/primitives/src/vstaging/mod.rs
  polkadot/roadmap/implementers-guide/src/types/runtime.md
  polkadot/runtime/parachains/src/assigner_coretime/mock_helpers.rs
  polkadot/runtime/parachains/src/assigner_coretime/mod.rs
  polkadot/runtime/parachains/src/assigner_on_demand/benchmarking.rs
  polkadot/runtime/parachains/src/assigner_on_demand/mock_helpers.rs
  polkadot/runtime/parachains/src/assigner_on_demand/mod.rs
  polkadot/runtime/parachains/src/assigner_parachains.rs
  polkadot/runtime/parachains/src/assigner_parachains/mock_helpers.rs
  polkadot/runtime/parachains/src/builder.rs
  polkadot/runtime/parachains/src/configuration.rs
  polkadot/runtime/parachains/src/configuration/benchmarking.rs
  polkadot/runtime/parachains/src/configuration/migration.rs
  polkadot/runtime/parachains/src/configuration/migration/v11.rs
  polkadot/runtime/parachains/src/configuration/migration/v12.rs
  polkadot/runtime/parachains/src/configuration/tests.rs
  polkadot/runtime/parachains/src/coretime/migration.rs
  polkadot/runtime/parachains/src/coretime/mod.rs
  polkadot/runtime/parachains/src/inclusion/tests.rs
  polkadot/runtime/parachains/src/mock.rs
  polkadot/runtime/parachains/src/paras/tests.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
  polkadot/runtime/parachains/src/scheduler.rs
  polkadot/runtime/parachains/src/scheduler/common.rs
  polkadot/runtime/parachains/src/scheduler/tests.rs
  polkadot/runtime/parachains/src/session_info/tests.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/runtime_parachains_configuration.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/runtime_parachains_configuration.rs
  polkadot/zombienet_tests/functional/0002-parachains-disputes.toml
  polkadot/zombienet_tests/functional/0004-parachains-garbage-candidate.toml
  polkadot/zombienet_tests/functional/0005-parachains-disputes-past-session.toml
  polkadot/zombienet_tests/functional/0006-parachains-max-tranche0.toml
  polkadot/zombienet_tests/functional/0007-dispute-freshly-finalized.toml
  polkadot/zombienet_tests/functional/0008-dispute-old-finalized.toml
  polkadot/zombienet_tests/functional/0010-validator-disabling.toml
  polkadot/zombienet_tests/functional/0011-async-backing-6-seconds-rate.toml
  polkadot/zombienet_tests/functional/0012-elastic-scaling-mvp.toml
  polkadot/zombienet_tests/misc/0001-paritydb.toml
Labels: R0-silent, T8-polkadot

#3277 Fix accidental no-shows on node restart
  polkadot/node/core/approval-voting/src/lib.rs
  polkadot/node/core/approval-voting/src/persisted_entries.rs
  polkadot/node/core/approval-voting/src/tests.rs
Labels: R0-silent

#3506 update development setup in sdk-docs
  docs/sdk/src/reference_docs/development_environment_advice.rs
Labels: R0-silent, T11-documentation

#3513 Fix call enum's metadata regression
  docs/sdk/headers/header.html
  docs/sdk/headers/theme.css
  prdoc/pr_3513.prdoc
  substrate/frame/support/Cargo.toml
  substrate/frame/support/procedural/src/pallet/expand/call.rs
  substrate/frame/support/test/tests/pallet.rs
Labels: T1-FRAME, T2-pallets, T11-documentation
