Repository paritytech/polkadot-sdk, pull requests merged in 2024-10, with the labels that each got.

#5707 Remove ValidateFromChainState
  polkadot/node/core/candidate-validation/src/lib.rs
  polkadot/node/core/candidate-validation/src/metrics.rs
  polkadot/node/core/candidate-validation/src/tests.rs
  polkadot/node/malus/src/variants/back_garbage_candidate.rs
  polkadot/node/malus/src/variants/common.rs
  polkadot/node/malus/src/variants/dispute_valid_candidates.rs
  polkadot/node/malus/src/variants/suggest_garbage_candidate.rs
  polkadot/node/overseer/examples/minimal-example.rs
  polkadot/node/overseer/src/tests.rs
  polkadot/node/subsystem-types/src/messages.rs
  polkadot/roadmap/implementers-guide/src/types/overseer-protocol.md
  prdoc/pr_5707.prdoc
Labels: T0-node, T8-polkadot

#5857 Beefy equivocation: check all the MMR roots
  prdoc/pr_5857.prdoc
  substrate/frame/beefy-mmr/src/lib.rs
  substrate/frame/beefy-mmr/src/tests.rs
  substrate/primitives/consensus/beefy/src/payload.rs
Labels: T15-bridges

#5880 fix prospective parachains test to use shuffled candidate list
  polkadot/node/core/prospective-parachains/src/fragment_chain/tests.rs
  prdoc/pr_5880.prdoc
Labels: R0-silent, T8-polkadot, T10-tests

#5882 `zombienet`, retry only on 'runner_system_failure'
  .gitlab/pipeline/zombienet.yml
  .gitlab/pipeline/zombienet/cumulus.yml
  .gitlab/pipeline/zombienet/parachain-template.yml
  .gitlab/pipeline/zombienet/polkadot.yml
  .gitlab/pipeline/zombienet/substrate.yml
Labels: R0-silent, T10-tests

#5887 Do not enforce PoV size hard limit in config
  polkadot/runtime/parachains/src/configuration.rs
  polkadot/runtime/parachains/src/configuration/tests.rs
  prdoc/pr_5887.prdoc
Labels: T8-polkadot

#5907 [Backport] Fix parity-publish (#5670)
  .github/workflows/check-semver.yml
  .github/workflows/publish-check-crates.yml
  .github/workflows/publish-claim-crates.yml
  Cargo.lock
Labels: R0-silent, A3-backport, D0-easy

#5765 Added foreign locations to local accounts converter to all the parachains
  cumulus/parachains/runtimes/assets/asset-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/tests/tests.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/tests/tests.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/tests/tests.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/tests/tests.rs
  cumulus/parachains/runtimes/people/people-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/people/people-rococo/tests/tests.rs
  cumulus/parachains/runtimes/people/people-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/people/people-westend/tests/tests.rs
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
  polkadot/runtime/rococo/src/tests.rs
  polkadot/runtime/westend/src/tests.rs
  prdoc/pr_5765.prdoc
Labels: T6-XCM

#5586 `polkadot-parachain`: add manual seal support
  Cargo.lock
  cumulus/polkadot-parachain/polkadot-parachain-lib/Cargo.toml
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/cli.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/command.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/common/command.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/common/mod.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/common/spec.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/lib.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/nodes/aura.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/nodes/manual_seal.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/nodes/mod.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/nodes/shell.rs
  docs/sdk/src/guides/enable_elastic_scaling_mvp.rs
Labels: R0-silent, T0-node

#5909 Always amend to the same commit for gh-pages
  .gitlab/pipeline/publish.yml
Labels: R0-silent

#5916 bump zombienet version `v1.3.112`
  .gitlab/pipeline/zombienet.yml
Labels: R0-silent, T10-tests

#5741 rpc v2: backpressure chainHead_v1_storage
  Cargo.lock
  Cargo.toml
  prdoc/pr_5741.prdoc
  substrate/client/rpc-servers/src/lib.rs
  substrate/client/rpc-spec-v2/Cargo.toml
  substrate/client/rpc-spec-v2/src/archive/archive.rs
  substrate/client/rpc-spec-v2/src/chain_head/chain_head.rs
  substrate/client/rpc-spec-v2/src/chain_head/chain_head_storage.rs
  substrate/client/rpc-spec-v2/src/chain_head/mod.rs
  substrate/client/rpc-spec-v2/src/chain_head/subscription/inner.rs
  substrate/client/rpc-spec-v2/src/chain_head/subscription/mod.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
  substrate/client/rpc-spec-v2/src/common/storage.rs
Labels: T3-RPC_API

#5845 Re-establish pallet_revive weights baseline
  .github/workflows/cmd-tests.yml
  prdoc/pr_5845.prdoc
  substrate/frame/revive/fixtures/contracts/instr_benchmark.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/gas.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/src/weights.rs
Labels: R0-silent

#5912 Simplify bridges relayer cli configuration
  Cargo.lock
  bridges/relays/lib-substrate-relay/Cargo.toml
  bridges/relays/lib-substrate-relay/src/cli/bridge.rs
  bridges/relays/lib-substrate-relay/src/cli/relay_headers_and_messages/mod.rs
Labels: R0-silent, T15-bridges

#5911 polkadot-parachain: Remove shell node
  .github/workflows/check-cargo-check-runtimes.yml
  .gitlab/pipeline/build.yml
  Cargo.lock
  Cargo.toml
  cumulus/parachains/chain-specs/shell-head-data
  cumulus/parachains/chain-specs/shell.json
  cumulus/parachains/runtimes/starters/seedling/Cargo.toml
  cumulus/parachains/runtimes/starters/seedling/build.rs
  cumulus/parachains/runtimes/starters/seedling/src/lib.rs
  cumulus/parachains/runtimes/starters/shell/Cargo.toml
  cumulus/parachains/runtimes/starters/shell/build.rs
  cumulus/parachains/runtimes/starters/shell/src/lib.rs
  cumulus/parachains/runtimes/starters/shell/src/xcm_config.rs
  cumulus/polkadot-parachain/Cargo.toml
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/command.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/common/rpc.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/common/runtime.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/nodes/mod.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/nodes/shell.rs
  cumulus/polkadot-parachain/src/chain_spec/mod.rs
  cumulus/polkadot-parachain/src/chain_spec/seedling.rs
  cumulus/polkadot-parachain/src/chain_spec/shell.rs
  prdoc/pr_5911.prdoc
Labels: T0-node

#5896 Add stable-rc tags to the docker images
  .github/scripts/common/lib.sh
  .github/workflows/release-50_publish-docker.yml
  docker/dockerfiles/polkadot/polkadot_injected.Dockerfile
  docker/scripts/build-injected.sh
  docker/scripts/polkadot/build-injected.sh
Labels: R0-silent, A4-needs-backport

#5918 Update "@polkadot/api": "^14.0" for bridges zombienet tests
  bridges/testing/framework/utils/generate_hex_encoded_call/package-lock.json
  bridges/testing/framework/utils/generate_hex_encoded_call/package.json
Labels: R0-silent, T10-tests, T15-bridges

#5789 Prevents EthereumBlobExporter from consuming dest when returning NotApplicable
  bridges/snowbridge/primitives/router/src/outbound/mod.rs
  bridges/snowbridge/primitives/router/src/outbound/tests.rs
  prdoc/pr_5789.prdoc
Labels: T15-bridges

#5875 Remove jaeger everywhere
  Cargo.lock
  Cargo.toml
  cumulus/client/relay-chain-inprocess-interface/src/lib.rs
  polkadot/cli/src/cli.rs
  polkadot/cli/src/command.rs
  polkadot/node/collation-generation/src/tests.rs
  polkadot/node/core/approval-voting-parallel/Cargo.toml
  polkadot/node/core/av-store/Cargo.toml
  polkadot/node/core/av-store/src/lib.rs
  polkadot/node/core/bitfield-signing/src/lib.rs
  polkadot/node/core/bitfield-signing/src/tests.rs
  polkadot/node/core/candidate-validation/src/tests.rs
  polkadot/node/core/provisioner/src/lib.rs
  polkadot/node/jaeger/Cargo.toml
  polkadot/node/jaeger/src/config.rs
  polkadot/node/jaeger/src/errors.rs
  polkadot/node/jaeger/src/lib.rs
  polkadot/node/jaeger/src/spans.rs
  polkadot/node/network/availability-distribution/src/lib.rs
  polkadot/node/network/availability-distribution/src/pov_requester/mod.rs
  polkadot/node/network/availability-distribution/src/requester/fetch_task/mod.rs
  polkadot/node/network/availability-distribution/src/requester/fetch_task/tests.rs
  polkadot/node/network/availability-distribution/src/requester/mod.rs
  polkadot/node/network/availability-distribution/src/requester/tests.rs
  polkadot/node/network/availability-distribution/src/responder.rs
  polkadot/node/network/availability-recovery/src/lib.rs
  polkadot/node/network/bitfield-distribution/src/lib.rs
  polkadot/node/network/bitfield-distribution/src/tests.rs
  polkadot/node/network/bridge/src/rx/mod.rs
  polkadot/node/network/bridge/src/rx/tests.rs
  polkadot/node/network/collator-protocol/src/collator_side/mod.rs
  polkadot/node/network/collator-protocol/src/collator_side/tests/mod.rs
  polkadot/node/network/collator-protocol/src/collator_side/tests/prospective_parachains.rs
  polkadot/node/network/collator-protocol/src/validator_side/collation.rs
  polkadot/node/network/collator-protocol/src/validator_side/mod.rs
  polkadot/node/network/collator-protocol/src/validator_side/tests/prospective_parachains.rs
  polkadot/node/network/protocol/Cargo.toml
  polkadot/node/network/protocol/src/lib.rs
  polkadot/node/network/statement-distribution/src/legacy_v1/mod.rs
  polkadot/node/network/statement-distribution/src/legacy_v1/requester.rs
  polkadot/node/network/statement-distribution/src/legacy_v1/tests.rs
  polkadot/node/overseer/src/dummy.rs
  polkadot/node/overseer/src/lib.rs
  polkadot/node/service/src/lib.rs
  polkadot/node/service/src/overseer.rs
  polkadot/node/subsystem-bench/src/lib/availability/mod.rs
  polkadot/node/subsystem-bench/src/lib/mock/mod.rs
  polkadot/node/subsystem-test-helpers/src/mock.rs
  polkadot/node/subsystem-types/Cargo.toml
  polkadot/node/subsystem-types/src/errors.rs
  polkadot/node/subsystem-types/src/lib.rs
  polkadot/node/subsystem-util/Cargo.toml
  polkadot/node/subsystem/Cargo.toml
  polkadot/node/subsystem/src/lib.rs
  polkadot/node/test/service/src/lib.rs
  polkadot/parachain/test-parachains/adder/collator/src/main.rs
  polkadot/parachain/test-parachains/undying/collator/src/main.rs
  prdoc/pr_5875.prdoc
  umbrella/Cargo.toml
  umbrella/src/lib.rs
Labels: T8-polkadot

#5868 templates: add genesis config presets for minimal/solochain
  Cargo.lock
  templates/minimal/node/src/chain_spec.rs
  templates/minimal/node/src/command.rs
  templates/minimal/runtime/Cargo.toml
  templates/minimal/runtime/src/lib.rs
  templates/parachain/node/src/chain_spec.rs
  templates/parachain/node/src/command.rs
  templates/parachain/runtime/Cargo.toml
  templates/solochain/node/Cargo.toml
  templates/solochain/node/src/chain_spec.rs
  templates/solochain/node/src/command.rs
  templates/solochain/runtime/Cargo.toml
  templates/solochain/runtime/src/apis.rs
  templates/solochain/runtime/src/genesis_config_presets.rs
  templates/solochain/runtime/src/lib.rs
Labels: R0-silent, T17-Templates

#5917 XCM paid execution barrier supports more origin altering instructions
  polkadot/xcm/xcm-builder/src/barriers.rs
  polkadot/xcm/xcm-builder/src/tests/barriers.rs
  prdoc/pr_5917.prdoc
Labels: T6-XCM

#5921 Bridge relayer backwards compatibility for reading storage InboundLaneData/OutboundLaneData
  bridges/relays/lib-substrate-relay/src/messages/source.rs
  bridges/relays/lib-substrate-relay/src/messages/target.rs
Labels: R0-silent, T15-bridges

#5861 [pallet-revive] immutable data storage
  prdoc/pr_5861.prdoc
  substrate/frame/revive/fixtures/contracts/immutable_data.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/limits.rs
  substrate/frame/revive/src/storage.rs
  substrate/frame/revive/src/storage/meter.rs
  substrate/frame/revive/src/test_utils.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/src/weights.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv32.rs
Labels: R0-silent, T7-smart_contracts

#5938 update runners for cmd and docs
  .github/workflows/cmd.yml
  .github/workflows/docs.yml
Labels: R0-silent

#5935 bump zombienet version `v1.3.113`
  .gitlab/pipeline/zombienet.yml
Labels: R0-silent, T10-tests

#5901 fix `participation_with_onchain_disabling_confirmed` test
  polkadot/node/core/dispute-coordinator/src/tests.rs
  prdoc/pr_5901.prdoc
Labels: R0-silent, T10-tests

#5859 beefy/metrics: Add number of live peers available for requests
  prdoc/pr_5859.prdoc
  substrate/client/consensus/beefy/src/communication/request_response/outgoing_requests_engine.rs
  substrate/client/consensus/beefy/src/metrics.rs
Labels: A1-insubstantial, T0-node, I5-enhancement, D0-easy

#5893 Added people-polkadot Dwellir bootnodes
  cumulus/parachains/chain-specs/people-polkadot.json
Labels: R0-silent

#5423 Elastic scaling: runtime v2 descriptor support
  polkadot/primitives/src/vstaging/mod.rs
  polkadot/roadmap/implementers-guide/src/node/utility/candidate-validation.md
  polkadot/roadmap/implementers-guide/src/runtime/inclusion.md
  polkadot/runtime/parachains/src/builder.rs
  polkadot/runtime/parachains/src/inclusion/mod.rs
  polkadot/runtime/parachains/src/inclusion/tests.rs
  polkadot/runtime/parachains/src/paras_inherent/mod.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
  polkadot/runtime/parachains/src/runtime_api_impl/v11.rs
  polkadot/runtime/parachains/src/shared.rs
  polkadot/runtime/parachains/src/shared/migration.rs
  polkadot/runtime/parachains/src/shared/tests.rs
  polkadot/runtime/parachains/src/ump_tests.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_5423.prdoc
Labels: T8-polkadot

#5888 parachain-system: send core selector ump signal
  cumulus/client/consensus/aura/src/collators/lookahead.rs
  cumulus/pallets/parachain-system/Cargo.toml
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/primitives/core/src/lib.rs
  prdoc/pr_5888.prdoc
Labels: I5-enhancement, T9-cumulus

#5947 Update docker image for bridges substrate-relay
  docker/dockerfiles/bridges_zombienet_tests_injected.Dockerfile
Labels: R0-silent, T15-bridges

#5949 [ci] Use parity common runners in all workflows
  .github/workflows/build-publish-images.yml
  .github/workflows/check-getting-started.yml
  .github/workflows/tests-misc.yml
  docs/contributor/weight-generation.md
Labels: R0-silent

#5856 chainHead: Track reported blocks to capture notification gaps
  prdoc/pr_5856.prdoc
  substrate/client/rpc-spec-v2/src/chain_head/chain_head_follow.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
Labels: I2-bug, T3-RPC_API

#5890 [CI] Update try-runtime-cli
  .github/workflows/check-runtime-migration.yml
Labels: A1-insubstantial, R0-silent

#5946 [FRAME] fix: Do not emit `Issued { amount: 0 }` event
  prdoc/pr_5946.prdoc
  substrate/frame/balances/src/impl_fungible.rs
Labels: T2-pallets

#5952 Bridges - add version guarding for standalone relaying of parachains and messages
  bridges/relays/lib-substrate-relay/src/cli/mod.rs
  bridges/relays/lib-substrate-relay/src/cli/relay_headers.rs
  bridges/relays/lib-substrate-relay/src/cli/relay_messages.rs
  bridges/relays/lib-substrate-relay/src/cli/relay_parachains.rs
  bridges/relays/parachains/src/parachains_loop.rs
Labels: R0-silent, T15-bridges

#5630 Introduce and Implement `VestedTransfer` Trait
  prdoc/pr_5630.prdoc
  substrate/frame/support/src/traits.rs
  substrate/frame/support/src/traits/tokens/currency.rs
  substrate/frame/support/src/traits/tokens/currency/lockable.rs
  substrate/frame/vesting/src/benchmarking.rs
  substrate/frame/vesting/src/lib.rs
  substrate/frame/vesting/src/tests.rs
Labels: T1-FRAME, T2-pallets

#5955 fix auto-swap delivery fee when using PayFees
  polkadot/xcm/xcm-executor/src/lib.rs
Labels: R0-silent

#5939 revive: Bump PolkaVM and add static code validation
  Cargo.lock
  prdoc/pr_5939.prdoc
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/fixtures/Cargo.toml
  substrate/frame/revive/fixtures/build.rs
  substrate/frame/revive/fixtures/build/Cargo.toml
  substrate/frame/revive/fixtures/contracts/basic_block.rs
  substrate/frame/revive/fixtures/contracts/call_diverging_out_len.rs
  substrate/frame/revive/fixtures/contracts/call_return_code.rs
  substrate/frame/revive/fixtures/contracts/sbrk.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/limits.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/mod.rs
  substrate/frame/revive/src/weights.rs
  substrate/frame/revive/uapi/Cargo.toml
Labels: R0-silent

#5399 [Staking] Noop refactor to prep pallet for currency fungible migration
  substrate/frame/delegated-staking/src/impls.rs
  substrate/frame/delegated-staking/src/tests.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/lib.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
  substrate/frame/fast-unstake/src/tests.rs
  substrate/frame/nomination-pools/benchmarking/src/inner.rs
  substrate/frame/nomination-pools/src/adapter.rs
  substrate/frame/offences/benchmarking/src/inner.rs
  substrate/frame/root-offences/src/tests.rs
  substrate/frame/staking/src/asset.rs
  substrate/frame/staking/src/benchmarking.rs
  substrate/frame/staking/src/ledger.rs
  substrate/frame/staking/src/lib.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/slashing.rs
  substrate/frame/staking/src/testing_utils.rs
  substrate/frame/staking/src/tests.rs
  substrate/primitives/staking/src/lib.rs
Labels: R0-silent, T2-pallets

#5892 Add migration to clear unapproved proposals from treasury pallet
  Cargo.lock
  polkadot/runtime/rococo/src/lib.rs
  prdoc/pr_5892.prdoc
  substrate/frame/treasury/Cargo.toml
  substrate/frame/treasury/src/lib.rs
  substrate/frame/treasury/src/migration.rs
Labels: T1-FRAME

#5941 SolochainDefaultConfig: Use correct `AccountData`
  prdoc/pr_5941.prdoc
  substrate/frame/system/src/lib.rs
Labels: R0-silent

#5931 improve prdoc generation
  .github/scripts/cmd/cmd.py
  .github/scripts/generate-prdoc.py
  .github/workflows/cmd.yml
  .github/workflows/command-prdoc.yml
  docs/contributor/commands-readme.md
Labels: R0-silent

#5872 [omni-bencher] Make all runtimes work
  .github/scripts/cmd/cmd.py
  .github/scripts/cmd/test_cmd.py
  .github/workflows/check-frame-omni-bencher.yml
  .github/workflows/runtimes-matrix.json
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/contracts.rs
  prdoc/pr_5872.prdoc
  substrate/utils/frame/benchmarking-cli/src/pallet/command.rs
  substrate/utils/frame/benchmarking-cli/src/pallet/mod.rs
  substrate/utils/frame/benchmarking-cli/src/pallet/types.rs
  substrate/utils/frame/benchmarking-cli/src/pallet/writer.rs
Labels: T12-benchmarks

#5968 bump zombienet version and set request for k8s
  .gitlab/pipeline/zombienet.yml
Labels: R0-silent, T10-tests

#5886 Bump some dependencies
  Cargo.lock
  Cargo.toml
  bridges/primitives/polkadot-core/Cargo.toml
  bridges/primitives/polkadot-core/src/parachains.rs
  prdoc/pr_5886.prdoc
  substrate/client/consensus/babe/src/authorship.rs
  substrate/frame/babe/src/mock.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/sassafras/src/mock.rs
  substrate/primitives/runtime/src/testing.rs
Labels: T17-primitives

#5976 Disable flaky tests reported in 5972/5973/5974
  .gitlab/pipeline/zombienet/polkadot.yml
  .gitlab/pipeline/zombienet/substrate.yml
Labels: R0-silent, T10-tests

#5963 [Release/CI] Github flow to build `polkadot`/`polkadot-parachain` rc binaries and deb package
  .github/scripts/release/build-deb.sh
  .github/scripts/release/build-linux-release.sh
  .github/scripts/release/release_lib.sh
  .github/workflows/release-build-rc.yml
  .github/workflows/release-reusable-rc-buid.yml
  .github/workflows/release-reusable-s3-upload.yml
Labels: R0-silent

#5924 Bump PoV request timeout
  polkadot/node/network/protocol/src/request_response/mod.rs
  prdoc/pr_5924.prdoc
Labels: T0-node, T8-polkadot

#5979 [ci] Move test-linux-stable-no-try-runtime to GHA
  .github/actions/set-up-gh/action.yml
  .github/workflows/check-semver.yml
  .github/workflows/tests-linux-stable.yml
  .gitlab/pipeline/test.yml
Labels: R0-silent

#5994 Fix u256 conversion in BABE
  prdoc/pr_5994.prdoc
  substrate/client/consensus/babe/src/authorship.rs
Labels: R0-silent

#5902 Snowbridge V2 docs
  bridges/snowbridge/docs/v2.md
Labels: R0-silent, T11-documentation

#4837 Add PVF execution priority
  Cargo.lock
  polkadot/node/core/approval-voting/src/lib.rs
  polkadot/node/core/backing/Cargo.toml
  polkadot/node/core/backing/src/lib.rs
  polkadot/node/core/backing/src/tests/mod.rs
  polkadot/node/core/backing/src/tests/prospective_parachains.rs
  polkadot/node/core/candidate-validation/src/lib.rs
  polkadot/node/core/candidate-validation/src/tests.rs
  polkadot/node/core/dispute-coordinator/src/participation/mod.rs
  polkadot/node/core/dispute-coordinator/src/participation/tests.rs
  polkadot/node/core/pvf/Cargo.toml
  polkadot/node/core/pvf/src/execute/queue.rs
  polkadot/node/core/pvf/src/host.rs
  polkadot/node/core/pvf/src/metrics.rs
  polkadot/node/core/pvf/src/priority.rs
  polkadot/node/core/pvf/tests/it/main.rs
  polkadot/node/malus/src/variants/common.rs
  polkadot/node/overseer/examples/minimal-example.rs
  polkadot/node/overseer/src/tests.rs
  polkadot/node/subsystem-types/Cargo.toml
  polkadot/node/subsystem-types/src/messages.rs
  prdoc/pr_4837.prdoc
Labels: T0-node, T8-polkadot

#5967 Add RadiumBlock bootnodes to Coretime Polkadot Chain spec
  cumulus/parachains/chain-specs/coretime-polkadot.json
Labels: R0-silent

#5913 Remove redundant XCMs from dry run's forwarded xcms
  Cargo.lock
  bridges/modules/xcm-bridge-hub-router/src/lib.rs
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/parachains/integration-tests/emulated/common/src/macros.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  polkadot/xcm/xcm-builder/src/universal_exports.rs
  prdoc/pr_5913.prdoc
Labels: T6-XCM, A4-needs-backport

#6003 Fix `0003-beefy-and-mmr` test
  .gitlab/pipeline/zombienet/polkadot.yml
  polkadot/zombienet_tests/functional/0003-beefy-and-mmr.zndsl
Labels: R0-silent, T15-bridges

#6006 Set larger timeout for cmd.yml
  .github/workflows/cmd.yml
Labels: R0-silent

#6019 [stable2407] Backport Fix parity-publish (#5670)
  .github/workflows/check-semver.yml
  .github/workflows/publish-check-crates.yml
  .github/workflows/publish-claim-crates.yml
Labels: R0-silent, A3-backport

#6017 [stable2407] Backport docker fix to 2407
  .github/scripts/common/lib.sh
  .github/workflows/release-50_publish-docker.yml
  docker/dockerfiles/polkadot/polkadot_injected.Dockerfile
  docker/scripts/build-injected.sh
  docker/scripts/polkadot/build-injected.sh
Labels: R0-silent, A3-backport

#6021 [stable2409] Backport docker fix to 2409
  .github/scripts/common/lib.sh
  .github/workflows/release-50_publish-docker.yml
Labels: R0-silent, A3-backport

#6014 [ci] Remove quick-benchmarks-omni from GitLab
  .github/workflows/check-frame-omni-bencher.yml
  .gitlab/pipeline/test.yml
Labels: R0-silent

#6015 Rename QueueEvent::StartWork
  polkadot/node/core/pvf/src/execute/queue.rs
  prdoc/pr_6015.prdoc
Labels: T0-node, I4-refactor, T8-polkadot

#5925 `substrate-node`: removed excessive polkadot-sdk features
  substrate/bin/node/cli/Cargo.toml
Labels: R0-silent, T0-node

#6007 /cmd: Improved devx of benching many pallets simultaneously
  .github/scripts/cmd/cmd.py
  .github/scripts/cmd/test_cmd.py
  .github/workflows/cmd.yml
  README.md
  docs/contributor/commands-readme.md
  docs/contributor/weight-generation.md
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/examples/tasks/src/mock.rs
Labels: R0-silent

#6023 Fix storage expansion in pallet section
  prdoc/pr_6023.prdoc
  substrate/frame/support/procedural/src/pallet/expand/storage.rs
  substrate/frame/support/test/tests/split_ui/pass/split_storage.rs
  substrate/frame/support/test/tests/split_ui/pass/storage/mod.rs
Labels: T1-FRAME

#6038 update cmd timeout
  .github/workflows/cmd.yml
Labels: R0-silent

#5991 Use the umbrella crate for the parachain template
  Cargo.lock
  substrate/frame/support/src/lib.rs
  templates/parachain/node/Cargo.toml
  templates/parachain/node/build.rs
  templates/parachain/node/src/chain_spec.rs
  templates/parachain/node/src/cli.rs
  templates/parachain/node/src/command.rs
  templates/parachain/node/src/main.rs
  templates/parachain/node/src/rpc.rs
  templates/parachain/node/src/service.rs
  templates/parachain/pallets/template/Cargo.toml
  templates/parachain/pallets/template/src/benchmarking.rs
  templates/parachain/pallets/template/src/lib.rs
  templates/parachain/pallets/template/src/mock.rs
  templates/parachain/pallets/template/src/tests.rs
  templates/parachain/pallets/template/src/weights.rs
  templates/parachain/runtime/Cargo.toml
  templates/parachain/runtime/src/apis.rs
  templates/parachain/runtime/src/benchmarks.rs
  templates/parachain/runtime/src/configs/mod.rs
  templates/parachain/runtime/src/configs/xcm_config.rs
  templates/parachain/runtime/src/genesis_config_presets.rs
  templates/parachain/runtime/src/lib.rs
  templates/parachain/runtime/src/weights/block_weights.rs
  templates/parachain/runtime/src/weights/extrinsic_weights.rs
  templates/parachain/runtime/src/weights/paritydb_weights.rs
  templates/parachain/runtime/src/weights/rocksdb_weights.rs
Labels: R0-silent, T17-Templates

#5999 Westend: Constant yearly emission
  Cargo.lock
  Cargo.toml
  polkadot/runtime/westend/Cargo.toml
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/tests.rs
  prdoc/pr_5999.prdoc
Labels: A0-needs_burnin, T10-tests

#6032 Fix `feeless_if` in pallet section
  prdoc/pr_6032.prdoc
  substrate/frame/support/procedural/src/pallet/expand/call.rs
  substrate/frame/support/test/tests/split_ui/pass/call/mod.rs
  substrate/frame/support/test/tests/split_ui/pass/split_call.rs
Labels: T1-FRAME

#6061 Remove `check-migrations` for rococo chain
  .github/workflows/check-runtime-migration.yml
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  prdoc/pr_6061.prdoc
Labels: R0-silent

#4982 pallet-xcm: added useful error logs (#2408)
  Cargo.lock
  polkadot/xcm/pallet-xcm/Cargo.toml
  polkadot/xcm/pallet-xcm/src/benchmarking.rs
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/pallet-xcm/src/migration.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  prdoc/pr_4982.prdoc
Labels: T6-XCM

#5599 Add assets in pool with native to query_acceptable_payment_assets's return
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_5599.prdoc
Labels: T6-XCM, A4-needs-backport

#6065 Bump zombienet version `v1.3.115`
  .gitlab/pipeline/zombienet.yml
Labels: R0-silent, T10-tests

#6018 Upgrade Proxy and Multisig pallets to Benchmarking V2
  substrate/frame/multisig/src/benchmarking.rs
  substrate/frame/proxy/src/benchmarking.rs
Labels: T1-FRAME

#6047 [ci] Move build and publish rustdocs to GHA
  .github/workflows/docs.yml
  .gitlab/pipeline/build.yml
  .gitlab/pipeline/publish.yml
  .gitlab/pipeline/test.yml
Labels: R0-silent

#5846 Fix `solochain-template-runtime` freezes config
  templates/solochain/runtime/src/configs/mod.rs
Labels: R0-silent

#6027 remove pallet::getter from pallet-offences
  prdoc/pr_6027.prdoc
  substrate/frame/offences/src/lib.rs
  substrate/frame/offences/src/tests.rs
Labels: T2-pallets

#5998 litep2p/discovery: Fix memory leak in `litep2p.public_addresses()`
  prdoc/pr_5998.prdoc
  substrate/client/network/src/litep2p/discovery.rs
  substrate/client/network/src/litep2p/mod.rs
Labels: T0-node, I2-bug, A4-needs-backport

#6076 Stabilize elastic-pov-recovery zombienet test
  cumulus/zombienet/tests/0009-elastic_pov_recovery.toml
Labels: R0-silent, T10-tests

#5274 Metadata V16 (unstable): Enrich metadata with associated types of config traits
  prdoc/pr_5274.prdoc
  substrate/frame/support/procedural/src/construct_runtime/expand/metadata.rs
  substrate/frame/support/procedural/src/lib.rs
  substrate/frame/support/procedural/src/pallet/expand/config.rs
  substrate/frame/support/procedural/src/pallet/expand/mod.rs
  substrate/frame/support/procedural/src/pallet/parse/config.rs
  substrate/frame/support/procedural/src/pallet/parse/mod.rs
  substrate/frame/support/procedural/tools/src/lib.rs
  substrate/frame/support/src/lib.rs
  substrate/frame/support/test/tests/construct_runtime_ui/deprecated_where_block.stderr
  substrate/frame/support/test/tests/pallet_associated_types_metadata.rs
  substrate/frame/support/test/tests/pallet_ui/config_duplicate_attr.rs
  substrate/frame/support/test/tests/pallet_ui/config_duplicate_attr.stderr
  substrate/frame/support/test/tests/pallet_ui/config_metadata_non_type_info.rs
  substrate/frame/support/test/tests/pallet_ui/config_metadata_non_type_info.stderr
  substrate/frame/support/test/tests/pallet_ui/config_metadata_on_constants.rs
  substrate/frame/support/test/tests/pallet_ui/config_metadata_on_constants.stderr
  substrate/frame/support/test/tests/pallet_ui/config_metadata_on_events.rs
  substrate/frame/support/test/tests/pallet_ui/config_metadata_on_events.stderr
  substrate/frame/support/test/tests/pallet_ui/no_default_but_missing_with_default.stderr
  substrate/frame/support/test/tests/pallet_ui/pass/config_multiple_attr.rs
  substrate/frame/support/test/tests/pallet_ui/pass/config_without_metadata.rs
  substrate/primitives/metadata-ir/src/types.rs
Labels: I5-enhancement, T1-FRAME, T11-documentation, D1-medium

#6082 [stable2409] Backport #5887
  polkadot/runtime/parachains/Cargo.toml
  polkadot/runtime/parachains/src/configuration.rs
  polkadot/runtime/parachains/src/configuration/tests.rs
  prdoc/pr_6082.prdoc
Labels: A3-backport

#6045 [pallet-revive] ensure the return data is reset if no frame was instantiated
  prdoc/pr_6045.prdoc
  substrate/frame/revive/src/exec.rs
Labels: R0-silent, T7-smart_contracts

#6085 [ci] Small updates
  .github/workflows/check-cargo-check-runtimes.yml
  .github/workflows/check-labels.yml
  .github/workflows/check-links.yml
  .github/workflows/check-prdoc.yml
  .github/workflows/check-semver.yml
  .github/workflows/command-backport.yml
  .github/workflows/docs.yml
  .github/workflows/fork-sync-action.yml
  .github/workflows/tests-misc.yml
Labels: R0-silent

#4803 Fix for Issue 4762
  prdoc/pr_4803.prdoc
  substrate/frame/message-queue/src/lib.rs
  substrate/frame/message-queue/src/tests.rs
Labels: T2-pallets, A4-needs-backport

#6091 bump `zombienet` version and inc. memory request in k8s
  .gitlab/pipeline/zombienet.yml
Labels: R0-silent, T0-node

#6092 Use `Versioned*::from` instead of concrete `V*` when using `xcm::latest`
  bridges/modules/xcm-bridge-hub-router/src/lib.rs
  bridges/modules/xcm-bridge-hub-router/src/mock.rs
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/xcmp-queue/src/lib.rs
  cumulus/pallets/xcmp-queue/src/tests.rs
  cumulus/parachains/integration-tests/emulated/common/src/macros.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/treasury.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/xcm_fee_estimation.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/fellowship_treasury.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/treasury.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/xcm_fee_estimation.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge.rs
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/src/tests/fellowship_treasury.rs
  polkadot/runtime/common/src/impls.rs
  polkadot/runtime/common/src/xcm_sender.rs
  polkadot/runtime/rococo/src/impls.rs
  polkadot/runtime/westend/src/impls.rs
  polkadot/xcm/docs/src/cookbook/relay_token_transactor/tests.rs
  polkadot/xcm/pallet-xcm/src/benchmarking.rs
  polkadot/xcm/pallet-xcm/src/tests/mod.rs
  polkadot/xcm/xcm-builder/src/process_xcm_message.rs
  polkadot/xcm/xcm-executor/integration-tests/src/lib.rs
  polkadot/xcm/xcm-executor/src/lib.rs
Labels: R0-silent, T6-XCM

#5420 [XCMv5] Better fee mechanism
  bridges/modules/xcm-bridge-hub-router/src/lib.rs
  bridges/modules/xcm-bridge-hub-router/src/mock.rs
  bridges/snowbridge/pallets/system/src/benchmarking.rs
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/xcmp-queue/src/lib.rs
  cumulus/pallets/xcmp-queue/src/tests.rs
  cumulus/parachains/integration-tests/emulated/common/src/macros.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/treasury.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/xcm_fee_estimation.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/fellowship_treasury.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/treasury.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/xcm_fee_estimation.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge.rs
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/src/tests/fellowship_treasury.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/xcm/xcm-emulator/src/lib.rs
  polkadot/runtime/common/src/impls.rs
  polkadot/runtime/common/src/xcm_sender.rs
  polkadot/runtime/rococo/src/impls.rs
  polkadot/runtime/rococo/src/weights/xcm/mod.rs
  polkadot/runtime/rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  polkadot/runtime/westend/src/impls.rs
  polkadot/runtime/westend/src/weights/xcm/mod.rs
  polkadot/runtime/westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  polkadot/xcm/docs/src/cookbook/relay_token_transactor/tests.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  polkadot/xcm/pallet-xcm/src/benchmarking.rs
  polkadot/xcm/pallet-xcm/src/tests/mod.rs
  polkadot/xcm/procedural/src/builder_pattern.rs
  polkadot/xcm/src/v3/mod.rs
  polkadot/xcm/src/v4/mod.rs
  polkadot/xcm/src/v5/asset.rs
  polkadot/xcm/src/v5/mod.rs
  polkadot/xcm/src/v5/traits.rs
  polkadot/xcm/xcm-builder/src/barriers.rs
  polkadot/xcm/xcm-builder/src/process_xcm_message.rs
  polkadot/xcm/xcm-executor/integration-tests/src/lib.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  polkadot/xcm/xcm-executor/src/tests/mock.rs
  polkadot/xcm/xcm-executor/src/tests/mod.rs
  polkadot/xcm/xcm-executor/src/tests/pay_fees.rs
  prdoc/pr_5420.prdoc
Labels: T6-XCM

#5435 [AHs] Support registering assets on Asset Hubs over bridge
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/register_bridged_assets.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/register_bridged_assets.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/common/src/matching.rs
  prdoc/pr_5435.prdoc
Labels: T10-tests, T15-bridges

#6108 [Release/CI] Adjust release pipelines to support new tags and delete rococo from release
  .github/scripts/common/lib.sh
  .github/workflows/release-10_rc-automation.yml
  .github/workflows/release-30_publish_release_draft.yml
  .github/workflows/release-50_publish-docker.yml
  .github/workflows/release-branchoff-stable.yml
  .github/workflows/release-reusable-rc-buid.yml
  .github/workflows/release-srtool.yml
  scripts/release/build-changelogs.sh
  scripts/release/templates/changelog.md.tera
Labels: R0-silent

#6103 Fix generate-prdoc for single audiences
  .github/scripts/generate-prdoc.py
Labels: R0-silent

#6039 Added Trusted Query API calls
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/xcm-runtime-apis/src/lib.rs
  polkadot/xcm/xcm-runtime-apis/src/trusted_query.rs
  polkadot/xcm/xcm-runtime-apis/tests/mock.rs
  polkadot/xcm/xcm-runtime-apis/tests/trusted_query.rs
  polkadot/zombienet-sdk-tests/metadata-files/coretime-rococo-local.scale
  polkadot/zombienet-sdk-tests/metadata-files/rococo-local.scale
  prdoc/pr_6039.prdoc
Labels: T6-XCM

#6088 pallet-revive: EXTCODEHASH to match EIP-1052
  prdoc/pr_6088.prdoc
  substrate/frame/revive/fixtures/contracts/code_hash.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv32.rs
Labels: R0-silent, T7-smart_contracts

#6058 rpc v2: backpressure `chainhead_v1_follow`
  prdoc/pr_6058.prdoc
  substrate/client/rpc-spec-v2/src/chain_head/chain_head.rs
  substrate/client/rpc-spec-v2/src/chain_head/chain_head_follow.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
  substrate/client/rpc/src/utils.rs
Labels: T3-RPC_API, A4-needs-backport

#6120 [CI] Fix branch-off pipeline
  .github/workflows/release-branchoff-stable.yml
Labels: R0-silent, D0-easy

#6093 Adding migration instruction from benchmarking v1 to v2
  substrate/frame/benchmarking/src/lib.rs
Labels: R0-silent, T1-FRAME

#6124 Removed .scale files
  polkadot/zombienet-sdk-tests/metadata-files/coretime-rococo-local.scale
  polkadot/zombienet-sdk-tests/metadata-files/rococo-local.scale
Labels: A1-insubstantial, R0-silent

#6130 Added .scale metadata-files to gitignore
  .gitignore
Labels: R0-silent

#5686 sync: Remove checking of the extrinsics root
  prdoc/pr_5686.prdoc
  substrate/client/network/sync/src/strategy/chain_sync.rs
Labels: T0-node

#6141 Improve CheckMetadataHash: make it constant time and compile error on wrong env variable
  Cargo.lock
  Cargo.toml
  prdoc/pr_6141.prdoc
  substrate/frame/metadata-hash-extension/Cargo.toml
  substrate/frame/metadata-hash-extension/src/lib.rs
Labels: T1-FRAME

#6155 bump zombienet version `v1.3.116`
  .gitlab/pipeline/zombienet.yml
Labels: R0-silent, T10-tests

#6118 Fix a reference name in a reusable workflow invocation
  .github/workflows/fork-sync-action.yml
Labels: R0-silent

#6154 Fix and re-enable `zombienet-substrate-0002-validators-warp-sync`
  .gitlab/pipeline/zombienet/substrate.yml
  substrate/zombienet/0002-validators-warp-sync/test-validators-warp-sync.toml
  substrate/zombienet/0002-validators-warp-sync/test-validators-warp-sync.zndsl
Labels: R0-silent, T10-tests, T15-bridges

#5758 include more external links and resources
  README.md
  docs/mermaid/IA.mmd
  docs/sdk/src/external_resources.rs
  docs/sdk/src/lib.rs
  docs/sdk/src/polkadot_sdk/mod.rs
Labels: R0-silent

#5461 runtime: remove ttl
  .gitlab/pipeline/zombienet/polkadot.yml
  polkadot/primitives/src/v8/mod.rs
  polkadot/runtime/parachains/src/assigner_coretime/mod.rs
  polkadot/runtime/parachains/src/assigner_coretime/tests.rs
  polkadot/runtime/parachains/src/assigner_parachains.rs
  polkadot/runtime/parachains/src/assigner_parachains/tests.rs
  polkadot/runtime/parachains/src/builder.rs
  polkadot/runtime/parachains/src/configuration.rs
  polkadot/runtime/parachains/src/configuration/migration/v12.rs
  polkadot/runtime/parachains/src/configuration/tests.rs
  polkadot/runtime/parachains/src/coretime/migration.rs
  polkadot/runtime/parachains/src/disputes.rs
  polkadot/runtime/parachains/src/inclusion/mod.rs
  polkadot/runtime/parachains/src/inclusion/tests.rs
  polkadot/runtime/parachains/src/initializer.rs
  polkadot/runtime/parachains/src/mock.rs
  polkadot/runtime/parachains/src/on_demand/mod.rs
  polkadot/runtime/parachains/src/on_demand/tests.rs
  polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs
  polkadot/runtime/parachains/src/paras_inherent/mod.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
  polkadot/runtime/parachains/src/runtime_api_impl/v11.rs
  polkadot/runtime/parachains/src/scheduler.rs
  polkadot/runtime/parachains/src/scheduler/common.rs
  polkadot/runtime/parachains/src/scheduler/migration.rs
  polkadot/runtime/parachains/src/scheduler/tests.rs
  polkadot/runtime/parachains/src/session_info.rs
  polkadot/runtime/parachains/src/shared.rs
  polkadot/runtime/parachains/src/shared/tests.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_parachains_paras_inherent.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_parachains_paras_inherent.rs
  polkadot/zombienet_tests/functional/0015-coretime-shared-core.zndsl
  polkadot/zombienet_tests/functional/0017-sync-backing.toml
  polkadot/zombienet_tests/functional/0017-sync-backing.zndsl
  polkadot/zombienet_tests/functional/0018-shared-core-idle-parachain.toml
  polkadot/zombienet_tests/functional/0018-shared-core-idle-parachain.zndsl
  polkadot/zombienet_tests/functional/force-register-paras.js
  prdoc/pr_5461.prdoc
Labels: T8-polkadot

#6087 [pallet-nfts, pallet_uniques] - Expose private structs
  prdoc/pr_6087.prdoc
  substrate/frame/nfts/src/types.rs
  substrate/frame/uniques/src/lib.rs
  substrate/frame/uniques/src/types.rs
Labels: T2-pallets

#6170 Fix TrustedQueryApi Error
  .gitlab/pipeline/zombienet.yml
  polkadot/xcm/xcm-runtime-apis/src/trusted_query.rs
Labels: R0-silent, T6-XCM, I2-bug, T15-bridges

#5866 [pallet-revive] Eth RPC integration
  Cargo.lock
  prdoc/pr_5866.prdoc
  substrate/bin/node/cli/Cargo.toml
  substrate/bin/node/cli/benches/block_production.rs
  substrate/bin/node/cli/src/chain_spec.rs
  substrate/bin/node/cli/src/service.rs
  substrate/bin/node/cli/tests/basic.rs
  substrate/bin/node/cli/tests/fees.rs
  substrate/bin/node/cli/tests/submit_transaction.rs
  substrate/bin/node/runtime/Cargo.toml
  substrate/bin/node/runtime/src/lib.rs
  substrate/bin/node/testing/Cargo.toml
  substrate/bin/node/testing/src/bench.rs
  substrate/bin/node/testing/src/keyring.rs
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/fixtures/Cargo.toml
  substrate/frame/revive/fixtures/build.rs
  substrate/frame/revive/fixtures/build/Cargo.toml
  substrate/frame/revive/fixtures/src/lib.rs
  substrate/frame/revive/mock-network/Cargo.toml
  substrate/frame/revive/src/address.rs
  substrate/frame/revive/src/evm.rs
  substrate/frame/revive/src/evm/api.rs
  substrate/frame/revive/src/evm/api/account.rs
  substrate/frame/revive/src/evm/api/byte.rs
  substrate/frame/revive/src/evm/api/rlp_codec.rs
  substrate/frame/revive/src/evm/api/rpc_types.rs
  substrate/frame/revive/src/evm/api/rpc_types_gen.rs
  substrate/frame/revive/src/evm/api/signature.rs
  substrate/frame/revive/src/evm/api/type_id.rs
  substrate/frame/revive/src/evm/runtime.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/primitives.rs
  substrate/frame/revive/src/test_utils/builder.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/mod.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/uapi/Cargo.toml
  umbrella/Cargo.toml
Labels: R0-silent, T7-smart_contracts

#6104 `fatxpool`: `LocalTransactionPool` implemented
  prdoc/pr_6104.prdoc
  substrate/client/transaction-pool/benches/basics.rs
  substrate/client/transaction-pool/src/common/api.rs
  substrate/client/transaction-pool/src/common/tests.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/tx_mem_pool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/view.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs
  substrate/client/transaction-pool/src/graph/pool.rs
  substrate/test-utils/runtime/transaction-pool/src/lib.rs
Labels: R0-silent

#6156 Use bool::then instead of then_some with function calls
  cumulus/polkadot-omni-node/lib/src/command.rs
  polkadot/cli/src/command.rs
  polkadot/node/network/collator-protocol/src/collator_side/validators_buffer.rs
  prdoc/pr_6156.prdoc
  substrate/bin/node/cli/src/service.rs
  substrate/client/network/src/discovery.rs
  substrate/client/network/sync/src/strategy/state.rs
  substrate/client/network/sync/src/strategy/warp.rs
  substrate/frame/contracts/proc-macro/src/lib.rs
  substrate/frame/support/procedural/src/pallet/expand/pallet_struct.rs
  substrate/frame/support/src/migrations.rs
  templates/parachain/node/src/command.rs
Labels: T12-benchmarks

#6080 Assets in pool with native can be used in `query_weight_to_asset_fee`
  cumulus/parachains/integration-tests/emulated/common/src/macros.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/swap.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/swap.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/common/src/lib.rs
  prdoc/pr_6080.prdoc
Labels: T6-XCM, A4-needs-backport

#5502 [pallet-revive] Add pallet to AH westend
  Cargo.lock
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_5502.prdoc
Labels: T7-smart_contracts

#5876 [xcm-v5] implement RFC#100: add new InitiateTransfer instruction
  bridges/snowbridge/runtime/test-common/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-rococo/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-westend/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/common/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  polkadot/runtime/rococo/src/weights/xcm/mod.rs
  polkadot/runtime/rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  polkadot/runtime/westend/src/weights/xcm/mod.rs
  polkadot/runtime/westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/fungible/benchmarking.rs
  polkadot/xcm/src/lib.rs
  polkadot/xcm/src/v3/traits.rs
  polkadot/xcm/src/v4/mod.rs
  polkadot/xcm/src/v5/asset.rs
  polkadot/xcm/src/v5/mod.rs
  polkadot/xcm/src/v5/traits.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  polkadot/xcm/xcm-executor/src/traits/fee_manager.rs
  prdoc/pr_5876.prdoc
Labels: T6-XCM

#6094 Polkadot OmniNode Docs
  .gitignore
  Cargo.lock
  Cargo.toml
  cumulus/polkadot-omni-node/lib/src/cli.rs
  cumulus/polkadot-omni-node/lib/src/lib.rs
  cumulus/polkadot-omni-node/lib/src/nodes/manual_seal.rs
  cumulus/polkadot-omni-node/src/main.rs
  docs/mermaid/IA.mmd
  docs/sdk/Cargo.toml
  docs/sdk/assets/theme.css
  docs/sdk/packages/guides/first-pallet/Cargo.toml
  docs/sdk/packages/guides/first-pallet/src/lib.rs
  docs/sdk/packages/guides/first-runtime/Cargo.toml
  docs/sdk/packages/guides/first-runtime/build.rs
  docs/sdk/packages/guides/first-runtime/src/lib.rs
  docs/sdk/src/guides/enable_elastic_scaling_mvp.rs
  docs/sdk/src/guides/mod.rs
  docs/sdk/src/guides/your_first_node.rs
  docs/sdk/src/guides/your_first_pallet/mod.rs
  docs/sdk/src/guides/your_first_pallet/with_event.rs
  docs/sdk/src/guides/your_first_runtime.rs
  docs/sdk/src/lib.rs
  docs/sdk/src/meta_contributing.rs
  docs/sdk/src/polkadot_sdk/mod.rs
  docs/sdk/src/polkadot_sdk/substrate.rs
  docs/sdk/src/reference_docs/chain_spec_genesis.rs
  docs/sdk/src/reference_docs/frame_benchmarking_weight.rs
  docs/sdk/src/reference_docs/mod.rs
  docs/sdk/src/reference_docs/omni_node.rs
  docs/sdk/src/reference_docs/umbrella_crate.rs
  prdoc/pr_6094.prdoc
  substrate/bin/node/cli/src/cli.rs
  substrate/frame/Cargo.toml
  substrate/frame/aura/src/lib.rs
  substrate/frame/src/lib.rs
  substrate/primitives/genesis-builder/src/lib.rs
  templates/minimal/runtime/src/lib.rs
  templates/parachain/runtime/src/genesis_config_presets.rs
Labels: R0-silent, T11-documentation

#6175 Fix `zombienet-bridges-0001-asset-transfer-works`
  .gitlab/pipeline/zombienet/bridges.yml
  bridges/testing/environments/rococo-westend/rococo-bridge.zndsl
  bridges/testing/environments/rococo-westend/rococo-start.zndsl
  bridges/testing/environments/rococo-westend/spawn.sh
  bridges/testing/environments/rococo-westend/start_relayer.sh
  bridges/testing/environments/rococo-westend/westend-bridge.zndsl
  bridges/testing/environments/rococo-westend/westend-start.zndsl
Labels: R0-silent, I2-bug, T15-bridges

#6192 [pallet-revive] fix hardcoded gas in tests
  prdoc/pr_6192.prdoc
  substrate/frame/revive/src/evm/runtime.rs
  substrate/frame/revive/src/lib.rs
Labels: R0-silent, T7-smart_contracts

#6216 Snowbridge: PNA Audit Better Documentation and minor Refactorings
  bridges/snowbridge/primitives/router/src/inbound/mod.rs
  bridges/snowbridge/primitives/router/src/outbound/mod.rs
Labels: R0-silent, T11-documentation, T15-bridges

#6218 Enable approval-voting-parallel by default on kusama
  polkadot/node/service/src/lib.rs
  prdoc/pr_6218.prdoc
Labels: T8-polkadot

#6064 Disable tests reported in #6062
  .gitlab/pipeline/zombienet/polkadot.yml
Labels: R0-silent, T10-tests

#6229 Fix a tiny typo
  templates/solochain/runtime/src/lib.rs
Labels: R0-silent

#6205 pallet-message-queue: Fix max message size calculation
  prdoc/pr_6205.prdoc
  substrate/frame/message-queue/src/lib.rs
  substrate/frame/message-queue/src/mock.rs
  substrate/frame/message-queue/src/tests.rs
Labels: T2-pallets

#5813 `RuntimeGenesiConfig`: json macro added
  Cargo.lock
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/genesis_config_presets.rs
  docs/sdk/src/reference_docs/chain_spec_genesis.rs
  docs/sdk/src/reference_docs/chain_spec_runtime/Cargo.toml
  docs/sdk/src/reference_docs/chain_spec_runtime/src/pallets.rs
  docs/sdk/src/reference_docs/chain_spec_runtime/src/presets.rs
  docs/sdk/src/reference_docs/chain_spec_runtime/tests/chain_spec_builder_tests.rs
  polkadot/runtime/westend/src/genesis_config_presets.rs
  prdoc/pr_5813.prdoc
  substrate/frame/support/Cargo.toml
  substrate/frame/support/src/generate_genesis_config.rs
  substrate/frame/support/src/lib.rs
Labels: R0-silent, T1-FRAME

#5919 substrate-offchain: upgrade hyper to v1
  Cargo.lock
  Cargo.toml
  polkadot/node/service/src/lib.rs
  prdoc/pr_5919.prdoc
  substrate/bin/node/cli/src/service.rs
  substrate/client/offchain/Cargo.toml
  substrate/client/offchain/src/api.rs
  substrate/client/offchain/src/api/http.rs
  substrate/client/offchain/src/lib.rs
  templates/minimal/node/src/service.rs
  templates/parachain/node/src/service.rs
  templates/solochain/node/src/service.rs
Labels: T17-primitives

#6222 asset-hubs: simplify xcm-config
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
Labels: R0-silent

#6236 Fix a flaky zombienet test - 0004-coretime-smoke-test
  polkadot/zombienet_tests/smoke/0004-coretime-smoke-test.zndsl
Labels: R0-silent, T10-tests

#6214 fix experimental-ump-signals tests
  cumulus/pallets/parachain-system/src/tests.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/Cargo.toml
  prdoc/pr_6214.prdoc
Labels: R0-silent, T9-cumulus, T10-tests

#6171 remove parachains_assigner code
  polkadot/runtime/parachains/src/assigner_parachains.rs
  polkadot/runtime/parachains/src/assigner_parachains/mock_helpers.rs
  polkadot/runtime/parachains/src/assigner_parachains/tests.rs
  polkadot/runtime/parachains/src/lib.rs
  polkadot/runtime/parachains/src/mock.rs
  prdoc/pr_6171.prdoc
Labels: T8-polkadot

#6263 [pallet-revive] Update typeInfo
  prdoc/pr_6263.prdoc
  substrate/frame/revive/src/evm/runtime.rs
Labels: R0-silent, T7-smart_contracts

#6264 pallet-revive: Trade code size for call stack depth
  prdoc/pr_6264.prdoc
  substrate/frame/revive/fixtures/contracts/oom_rw_trailing.rs
  substrate/frame/revive/src/limits.rs
Labels: R0-silent

#6105 [pallet-revive] implement tx origin API
  prdoc/pr_6105.prdoc
  substrate/frame/revive/fixtures/contracts/origin.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/src/weights.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv32.rs
Labels: R0-silent, T7-smart_contracts

#6228 Transact without specifying weight
  Cargo.lock
  bridges/snowbridge/primitives/router/src/inbound/mod.rs
  cumulus/parachains/integration-tests/emulated/common/src/macros.rs
  cumulus/parachains/integration-tests/emulated/common/src/xcm_helpers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/send.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/set_xcm_versions.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/src/tests/fellowship.rs
  cumulus/parachains/pallets/ping/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/coretime.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/coretime.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/test-utils/src/lib.rs
  cumulus/parachains/runtimes/test-utils/src/test_cases.rs
  polkadot/runtime/parachains/src/coretime/migration.rs
  polkadot/runtime/parachains/src/coretime/mod.rs
  polkadot/runtime/parachains/src/mock.rs
  polkadot/runtime/rococo/src/impls.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/xcm/mod.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/impls.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/xcm/mod.rs
  polkadot/xcm/Cargo.toml
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/src/lib.rs
  polkadot/xcm/src/v4/mod.rs
  polkadot/xcm/src/v5/mod.rs
  polkadot/xcm/src/v5/traits.rs
  polkadot/xcm/xcm-builder/src/process_xcm_message.rs
  polkadot/xcm/xcm-builder/src/tests/transacting.rs
  polkadot/xcm/xcm-builder/src/weight.rs
  polkadot/xcm/xcm-executor/integration-tests/src/lib.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  polkadot/xcm/xcm-executor/src/tests/mock.rs
  polkadot/xcm/xcm-executor/src/traits/weight.rs
  polkadot/xcm/xcm-simulator/example/src/tests.rs
  prdoc/pr_6228.prdoc
  substrate/frame/system/src/lib.rs
Labels: T6-XCM

#5995 Use frame umbrella crate in `pallet-proxy` and `pallet-multisig`
  .github/scripts/cmd/cmd.py
  Cargo.lock
  prdoc/pr_5995.prdoc
  substrate/.maintain/frame-umbrella-weight-template.hbs
  substrate/frame/migrations/src/benchmarking.rs
  substrate/frame/multisig/Cargo.toml
  substrate/frame/multisig/src/benchmarking.rs
  substrate/frame/multisig/src/lib.rs
  substrate/frame/multisig/src/migrations.rs
  substrate/frame/multisig/src/tests.rs
  substrate/frame/multisig/src/weights.rs
  substrate/frame/proxy/Cargo.toml
  substrate/frame/proxy/src/benchmarking.rs
  substrate/frame/proxy/src/lib.rs
  substrate/frame/proxy/src/tests.rs
  substrate/frame/proxy/src/weights.rs
  substrate/frame/src/lib.rs
  substrate/scripts/run_all_benchmarks.sh
  templates/minimal/pallets/template/src/lib.rs
  templates/minimal/runtime/Cargo.toml
  templates/minimal/runtime/src/lib.rs
Labels: T1-FRAME

#5971 [xcm-v5] implement RFC#122: InitiateTransfer can alias XCM original origin on destination
  Cargo.lock
  bridges/snowbridge/primitives/router/src/inbound/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/transact.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/transact.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/testing/penpal/Cargo.toml
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
  polkadot/runtime/rococo/src/weights/xcm/mod.rs
  polkadot/runtime/westend/src/weights/xcm/mod.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/fungible/benchmarking.rs
  polkadot/xcm/src/v5/mod.rs
  polkadot/xcm/xcm-builder/src/lib.rs
  polkadot/xcm/xcm-builder/src/origin_aliases.rs
  polkadot/xcm/xcm-builder/src/tests/aliases.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  polkadot/xcm/xcm-executor/src/tests/initiate_transfer.rs
  polkadot/xcm/xcm-executor/src/tests/mod.rs
  prdoc/pr_5971.prdoc
Labels: T6-XCM

#6254 Migrate pallet-vesting benchmark to v2
  substrate/frame/vesting/src/benchmarking.rs
  substrate/primitives/panic-handler/src/lib.rs
Labels: R0-silent, T2-pallets, T12-benchmarks

#5554 [Identity] Decouple usernames from identities
  Cargo.lock
  cumulus/parachains/runtimes/people/people-rococo/Cargo.toml
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/people.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/mod.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/pallet_identity.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/pallet_migrations.rs
  cumulus/parachains/runtimes/people/people-westend/Cargo.toml
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/people.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/mod.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/pallet_identity.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/pallet_migrations.rs
  polkadot/runtime/common/src/integration_tests.rs
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/mod.rs
  polkadot/runtime/rococo/src/weights/pallet_identity.rs
  polkadot/runtime/rococo/src/weights/pallet_migrations.rs
  polkadot/runtime/westend/Cargo.toml
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/mod.rs
  polkadot/runtime/westend/src/weights/pallet_identity.rs
  polkadot/runtime/westend/src/weights/pallet_migrations.rs
  prdoc/pr_5554.prdoc
  substrate/bin/node/runtime/src/impls.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/alliance/src/mock.rs
  substrate/frame/identity/README.md
  substrate/frame/identity/src/benchmarking.rs
  substrate/frame/identity/src/lib.rs
  substrate/frame/identity/src/migration.rs
  substrate/frame/identity/src/tests.rs
  substrate/frame/identity/src/types.rs
  substrate/frame/identity/src/weights.rs
Labels: T2-pallets

#6266 pallet-revive: Use custom target to build test fixtures
  Cargo.lock
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/fixtures/Cargo.toml
  substrate/frame/revive/fixtures/build.rs
  substrate/frame/revive/fixtures/build/Cargo.toml
  substrate/frame/revive/fixtures/contracts/oom_rw_included.rs
  substrate/frame/revive/fixtures/contracts/oom_rw_trailing.rs
  substrate/frame/revive/fixtures/riscv32emac-unknown-none-polkavm.json
  substrate/frame/revive/src/limits.rs
  substrate/frame/revive/uapi/Cargo.toml
Labels: R0-silent

#6275 Fix review in #6258
  substrate/frame/timestamp/src/benchmarking.rs
Labels: R0-silent, T2-pallets

#6073 Refactor `pallet-grandpa` to use `v2` benchmarks
  prdoc/pr_6073.prdoc
  substrate/frame/grandpa/src/benchmarking.rs
Labels: I4-refactor, T2-pallets, T12-benchmarks, T14-system_parachains

#6278 [pallet-revive] rpc server add docker file
  prdoc/pr_6278.prdoc
  substrate/frame/revive/rpc/.dockerignore
  substrate/frame/revive/rpc/Dockerfile
Labels: R0-silent, T7-smart_contracts

#6286 [ci] Add publish docker for eth-rpc
  .github/workflows/build-publish-eth-rpc.yml
Labels: R0-silent

#5891 Add overhead benchmark to frame-omni-bencher
  Cargo.lock
  cumulus/client/parachain-inherent/src/mock.rs
  cumulus/polkadot-omni-node/lib/src/command.rs
  cumulus/polkadot-omni-node/src/main.rs
  cumulus/polkadot-parachain/src/main.rs
  cumulus/test/client/src/lib.rs
  cumulus/test/runtime/Cargo.toml
  cumulus/test/runtime/src/genesis_config_presets.rs
  cumulus/test/runtime/src/lib.rs
  cumulus/test/service/Cargo.toml
  cumulus/test/service/benches/transaction_throughput.rs
  cumulus/test/service/benches/validate_block.rs
  cumulus/test/service/src/bench_utils.rs
  cumulus/test/service/src/chain_spec.rs
  cumulus/test/service/src/lib.rs
  cumulus/zombienet/examples/small_network.toml
  polkadot/cli/src/command.rs
  polkadot/node/service/src/benchmarking.rs
  polkadot/tests/benchmark_overhead.rs
  prdoc/pr_5891.prdoc
  substrate/bin/node/cli/src/command.rs
  substrate/client/chain-spec/src/genesis_block.rs
  substrate/utils/frame/benchmarking-cli/Cargo.toml
  substrate/utils/frame/benchmarking-cli/src/extrinsic/bench.rs
  substrate/utils/frame/benchmarking-cli/src/extrinsic/cmd.rs
  substrate/utils/frame/benchmarking-cli/src/lib.rs
  substrate/utils/frame/benchmarking-cli/src/overhead/cmd.rs
  substrate/utils/frame/benchmarking-cli/src/overhead/command.rs
  substrate/utils/frame/benchmarking-cli/src/overhead/fake_runtime_api.rs
  substrate/utils/frame/benchmarking-cli/src/overhead/mod.rs
  substrate/utils/frame/benchmarking-cli/src/overhead/remark_builder.rs
  substrate/utils/frame/benchmarking-cli/src/overhead/runtime_utilities.rs
  substrate/utils/frame/benchmarking-cli/src/overhead/template.rs
  substrate/utils/frame/benchmarking-cli/src/overhead/weights.hbs
  substrate/utils/frame/benchmarking-cli/src/pallet/command.rs
  substrate/utils/frame/benchmarking-cli/src/pallet/mod.rs
  substrate/utils/frame/benchmarking-cli/src/pallet/types.rs
  substrate/utils/frame/benchmarking-cli/src/shared/genesis_state.rs
  substrate/utils/frame/benchmarking-cli/src/shared/mod.rs
  substrate/utils/frame/omni-bencher/Cargo.toml
  substrate/utils/frame/omni-bencher/src/command.rs
  substrate/utils/frame/omni-bencher/src/main.rs
  substrate/utils/frame/omni-bencher/tests/benchmark_works.rs
  templates/solochain/node/src/command.rs
Labels: T0-node, T12-benchmarks

#6260 [pallet-revive] code size API
  prdoc/pr_6260.prdoc
  substrate/frame/revive/fixtures/contracts/extcodesize.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/mod.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/src/weights.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv32.rs
Labels: R0-silent, T7-smart_contracts

#6057 Publish `polkadot-omni-node` binary
  .github/workflows/release-30_publish_release_draft.yml
  .github/workflows/release-50_publish-docker.yml
  docker/scripts/polkadot-omni-node/build-injected.sh
Labels: R0-silent, T0-node

#6246 [pallet-revive] implement the block hash API
  prdoc/pr_6246.prdoc
  substrate/frame/revive/fixtures/contracts/block_hash.rs
  substrate/frame/revive/src/benchmarking/call_builder.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/evm/runtime.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/mod.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/src/weights.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv32.rs
Labels: R0-silent, T7-smart_contracts

#6288 [pallet-revive] Add metrics to eth-rpc
  Cargo.lock
  prdoc/pr_6288.prdoc
  substrate/client/cli/src/signals.rs
  substrate/frame/revive/rpc/Cargo.toml
  substrate/frame/revive/rpc/Dockerfile
  substrate/frame/revive/rpc/examples/js/src/script.ts
  substrate/frame/revive/rpc/src/cli.rs
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/rpc/src/main.rs
  substrate/frame/revive/rpc/src/tests.rs
Labels: R0-silent, T7-smart_contracts

#6305 Remove `riscv` feature flag
  .config/zepter.yaml
  .github/scripts/cmd/test_cmd.py
  .github/workflows/runtimes-matrix.json
  .github/workflows/tests-linux-stable-coverage.yml
  .github/workflows/tests-linux-stable.yml
  prdoc/pr_6305.prdoc
  scripts/generate-umbrella.py
  substrate/bin/node/cli/Cargo.toml
  substrate/bin/node/runtime/Cargo.toml
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/fixtures/Cargo.toml
  substrate/frame/revive/fixtures/build.rs
  substrate/frame/revive/fixtures/src/lib.rs
  substrate/frame/revive/mock-network/Cargo.toml
  substrate/frame/revive/mock-network/src/lib.rs
  substrate/frame/revive/rpc/Cargo.toml
  substrate/frame/revive/rpc/Dockerfile
  substrate/frame/revive/rpc/examples/README.md
  substrate/frame/revive/rpc/src/tests.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/benchmarking_dummy.rs
  substrate/frame/revive/src/evm/runtime.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/storage.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/tests/test_debug.rs
  substrate/frame/revive/src/wasm/mod.rs
  umbrella/Cargo.toml
Labels: T7-smart_contracts, T10-tests

#5847 `candidate-validation`: RFC103 implementation
  Cargo.lock
  polkadot/node/core/candidate-validation/Cargo.toml
  polkadot/node/core/candidate-validation/src/lib.rs
  polkadot/node/core/candidate-validation/src/tests.rs
  polkadot/node/primitives/src/lib.rs
  polkadot/primitives/src/vstaging/mod.rs
  prdoc/pr_5847.prdoc
Labels: T0-node, T8-polkadot
