Repository paritytech/polkadot-sdk, pull requests merged in 2024-08, with the labels that each got.

#5182 Adjust sync templates flow to use new release branch
  .github/workflows/misc-sync-templates.yml
Labels: R0-silent

#5168 Adds target approvals buffering below a threshold
  Cargo.lock
  polkadot/runtime/westend/src/lib.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/delegated-staking/src/mock.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
  substrate/frame/nomination-pools/src/mock.rs
  substrate/frame/nomination-pools/test-delegate-stake/src/mock.rs
  substrate/frame/nomination-pools/test-transfer-stake/src/mock.rs
  substrate/frame/staking/src/benchmarking.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/tests.rs
  substrate/frame/staking/stake-tracker/Cargo.toml
  substrate/frame/staking/stake-tracker/src/benchmarking.rs
  substrate/frame/staking/stake-tracker/src/lib.rs
  substrate/frame/staking/stake-tracker/src/mock.rs
  substrate/frame/staking/stake-tracker/src/tests.rs
  substrate/frame/staking/stake-tracker/src/weights.rs
  substrate/primitives/staking/src/lib.rs
Labels: R0-silent

#4948 Add deprecation for Calls,Events,Errors,Pallet
  prdoc/pr_4851.prdoc
  substrate/frame/support/procedural/src/construct_runtime/expand/metadata.rs
  substrate/frame/support/procedural/src/construct_runtime/parse.rs
  substrate/frame/support/procedural/src/deprecation.rs
  substrate/frame/support/procedural/src/pallet/expand/call.rs
  substrate/frame/support/procedural/src/pallet/expand/error.rs
  substrate/frame/support/procedural/src/pallet/expand/event.rs
  substrate/frame/support/procedural/src/pallet/expand/pallet_struct.rs
  substrate/frame/support/procedural/src/pallet/parse/call.rs
  substrate/frame/support/procedural/src/pallet/parse/error.rs
  substrate/frame/support/procedural/src/pallet/parse/event.rs
  substrate/frame/support/procedural/src/runtime/parse/pallet.rs
  substrate/frame/support/src/storage/types/counted_map.rs
  substrate/frame/support/src/storage/types/counted_nmap.rs
  substrate/frame/support/src/storage/types/double_map.rs
  substrate/frame/support/src/storage/types/map.rs
  substrate/frame/support/src/storage/types/mod.rs
  substrate/frame/support/src/storage/types/nmap.rs
  substrate/frame/support/src/storage/types/value.rs
  substrate/frame/support/src/tests/mod.rs
  substrate/frame/support/src/tests/runtime.rs
  substrate/frame/support/test/tests/construct_runtime_ui/undefined_event_part.stderr
  substrate/frame/support/test/tests/enum_deprecation.rs
  substrate/frame/support/test/tests/instance.rs
  substrate/frame/support/test/tests/pallet.rs
  substrate/frame/support/test/tests/runtime_metadata.rs
  substrate/primitives/api/proc-macro/src/utils.rs
  substrate/primitives/api/test/tests/ui/deprecation_info.stderr
  substrate/primitives/api/test/tests/ui/impl_incorrect_method_signature.stderr
  substrate/primitives/metadata-ir/src/types.rs
Labels: R0-silent, I5-enhancement, D1-medium

#5065 Replace env_logger with sp_tracing
  Cargo.lock
  Cargo.toml
  bridges/relays/utils/Cargo.toml
  bridges/relays/utils/src/initialize.rs
  bridges/snowbridge/pallets/outbound-queue/merkle-tree/Cargo.toml
  bridges/snowbridge/pallets/outbound-queue/merkle-tree/src/lib.rs
  polkadot/node/core/approval-voting/Cargo.toml
  polkadot/node/core/approval-voting/src/tests.rs
  polkadot/node/core/av-store/Cargo.toml
  polkadot/node/core/av-store/src/tests.rs
  polkadot/node/network/approval-distribution/Cargo.toml
  polkadot/node/network/approval-distribution/src/tests.rs
  polkadot/node/network/bitfield-distribution/Cargo.toml
  polkadot/node/network/bitfield-distribution/src/tests.rs
  polkadot/node/network/collator-protocol/Cargo.toml
  polkadot/node/network/collator-protocol/src/collator_side/tests/mod.rs
  polkadot/node/network/collator-protocol/src/validator_side/tests/mod.rs
  polkadot/node/service/Cargo.toml
  polkadot/node/service/src/tests.rs
  polkadot/node/subsystem-bench/Cargo.toml
  polkadot/node/subsystem-bench/src/cli/subsystem-bench.rs
  polkadot/node/subsystem-util/Cargo.toml
  polkadot/xcm/xcm-runtime-apis/Cargo.toml
  polkadot/xcm/xcm-runtime-apis/tests/fee_estimation.rs
  prdoc/pr_5065.prdoc
  substrate/client/executor/Cargo.toml
  substrate/client/executor/benches/bench.rs
  substrate/client/rpc/Cargo.toml
  substrate/client/rpc/src/author/tests.rs
  substrate/client/statement-store/Cargo.toml
  substrate/client/statement-store/src/lib.rs
  substrate/frame/contracts/Cargo.toml
  substrate/frame/contracts/src/tests.rs
  substrate/frame/merkle-mountain-range/Cargo.toml
  substrate/frame/merkle-mountain-range/src/tests.rs
  substrate/frame/sassafras/src/tests.rs
  substrate/primitives/tracing/Cargo.toml
  substrate/primitives/tracing/src/lib.rs
  substrate/utils/binary-merkle-tree/Cargo.toml
  substrate/utils/binary-merkle-tree/src/lib.rs
  substrate/utils/frame/omni-bencher/Cargo.toml
  substrate/utils/frame/omni-bencher/src/main.rs
Labels: T0-node, T10-tests, T15-bridges

#5130 Add an adapter for configuring AssetExchanger
  Cargo.lock
  cumulus/primitives/utility/src/lib.rs
  polkadot/xcm/xcm-builder/Cargo.toml
  polkadot/xcm/xcm-builder/src/asset_exchange/mod.rs
  polkadot/xcm/xcm-builder/src/asset_exchange/single_asset_adapter/adapter.rs
  polkadot/xcm/xcm-builder/src/asset_exchange/single_asset_adapter/mock.rs
  polkadot/xcm/xcm-builder/src/asset_exchange/single_asset_adapter/mod.rs
  polkadot/xcm/xcm-builder/src/asset_exchange/single_asset_adapter/tests.rs
  polkadot/xcm/xcm-builder/src/lib.rs
  polkadot/xcm/xcm-builder/src/test_utils.rs
  polkadot/xcm/xcm-builder/src/tests/mock.rs
  polkadot/xcm/xcm-executor/src/traits/asset_exchange.rs
  prdoc/pr_5130.prdoc
  substrate/frame/asset-conversion/src/lib.rs
Labels: T6-XCM

#5205 rpc: Enable ChainSpec for polkadot-parachain
  Cargo.lock
  polkadot/rpc/src/lib.rs
  prdoc/pr_5205.prdoc
  substrate/bin/node/rpc/Cargo.toml
  substrate/bin/node/rpc/src/lib.rs
  substrate/client/service/src/builder.rs
Labels: I5-enhancement, T3-RPC_API, T9-cumulus, D0-easy

#5197 beefy: Tolerate pruned state on runtime API call
  prdoc/pr_5197.prdoc
  substrate/client/consensus/beefy/src/lib.rs
  substrate/client/consensus/beefy/src/worker.rs
Labels: T0-node

#5222 Fix frame crate usage doc
  substrate/frame/src/lib.rs
Labels: R0-silent

#5029 network/strategy: Backoff and ban overloaded peers to avoid submitting the same request multiple times
  prdoc/pr_5029.prdoc
  substrate/client/network/sync/src/engine.rs
  substrate/client/network/sync/src/strategy.rs
  substrate/client/network/sync/src/strategy/chain_sync.rs
  substrate/client/network/sync/src/strategy/disconnected_peers.rs
  substrate/client/network/sync/src/strategy/state.rs
  substrate/client/network/sync/src/strategy/warp.rs
Labels: A1-insubstantial, T0-node, I5-enhancement, D1-medium

#4424 Coretime auto-renew
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/coretime.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_broker.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/coretime.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/pallet_broker.rs
  prdoc/pr_4424.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/broker/src/benchmarking.rs
  substrate/frame/broker/src/dispatchable_impls.rs
  substrate/frame/broker/src/lib.rs
  substrate/frame/broker/src/mock.rs
  substrate/frame/broker/src/tests.rs
  substrate/frame/broker/src/tick_impls.rs
  substrate/frame/broker/src/types.rs
  substrate/frame/broker/src/utility_impls.rs
  substrate/frame/broker/src/weights.rs
Labels: T2-pallets

#5237 Remove unused feature gated code from the minimal template
  templates/minimal/node/src/command.rs
  templates/minimal/node/src/service.rs
Labels: R0-silent

#5248 Backport #4812 and #5189 into stable
  .github/workflows/check-semver.yml
  .github/workflows/publish-check-crates.yml
  .github/workflows/publish-claim-crates.yml
Labels: R0-silent

#4973 [pallet_contracts] Increase the weight of the deposit_event host function to limit the memory used by events.
  prdoc/pr_4973.prdoc
  substrate/frame/contracts/src/lib.rs
  substrate/frame/contracts/src/schedule.rs
  substrate/frame/contracts/src/wasm/runtime.rs
Labels: T7-smart_contracts

#5264 Improve Pallet UI doc test
  substrate/frame/support/test/example-pallet-doc.md
  substrate/frame/support/test/example-readme.md
  substrate/frame/support/test/tests/pallet.rs
Labels: R0-silent

#4527 [Assets] Call implementation for `transfer_all`
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_assets_foreign.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_assets_local.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_assets_pool.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_assets_foreign.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_assets_local.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_assets_pool.rs
  prdoc/pr_4527.prdoc
  substrate/frame/assets/src/benchmarking.rs
  substrate/frame/assets/src/lib.rs
  substrate/frame/assets/src/tests.rs
  substrate/frame/assets/src/weights.rs
Labels: T1-FRAME

#5257 Add `ProofSizeExt` to benchmarks
  prdoc/pr_5257.prdoc
  substrate/client/db/src/bench.rs
  substrate/utils/frame/benchmarking-cli/src/pallet/command.rs
  substrate/utils/frame/benchmarking-cli/src/pallet/mod.rs
Labels: T12-benchmarks

#5240 cli/net_params: Warn on empty public-addr when starting a validator node
  prdoc/pr_5240.prdoc
  substrate/client/cli/src/config.rs
Labels: T0-node

#5256 Update the wishlist leaderboard script to handle PRs
  .github/scripts/update-wishlist-leaderboard.py
Labels: R0-silent

#5250 Export more from sc-service
  prdoc/pr_5250.prdoc
  substrate/client/service/src/builder.rs
  substrate/client/service/src/lib.rs
Labels: T0-node

#5189 Run semver check even when no prdoc
  .github/workflows/check-semver.yml
  .github/workflows/publish-check-crates.yml
  .github/workflows/publish-claim-crates.yml
Labels: A1-insubstantial, R0-silent

#5173 Umbrella crate: exclude chain-specific crates
  Cargo.lock
  bridges/chains/chain-asset-hub-rococo/Cargo.toml
  bridges/chains/chain-asset-hub-westend/Cargo.toml
  bridges/chains/chain-bridge-hub-cumulus/Cargo.toml
  bridges/chains/chain-bridge-hub-kusama/Cargo.toml
  bridges/chains/chain-bridge-hub-polkadot/Cargo.toml
  bridges/chains/chain-bridge-hub-rococo/Cargo.toml
  bridges/chains/chain-bridge-hub-westend/Cargo.toml
  bridges/chains/chain-kusama/Cargo.toml
  bridges/chains/chain-polkadot-bulletin/Cargo.toml
  bridges/chains/chain-rococo/Cargo.toml
  bridges/chains/chain-westend/Cargo.toml
  docs/contributor/CONTRIBUTING.md
  polkadot/runtime/rococo/constants/Cargo.toml
  polkadot/runtime/westend/constants/Cargo.toml
  prdoc/pr_5173.prdoc
  scripts/generate-umbrella.py
  umbrella/Cargo.toml
  umbrella/src/lib.rs
Labels: T8-polkadot

#5268 frame-omni-bencher short checks
  .github/workflows/check-changed-files.yml
  .github/workflows/check-frame-omni-bencher.yml
  .github/workflows/reusable-check-changed-files.yml
  .github/workflows/tests-linux-stable.yml
  .github/workflows/tests.yml
Labels: R0-silent

#5275 Fix Weight Annotation
  substrate/frame/assets/src/lib.rs
Labels: A1-insubstantial, R0-silent

#4897 [ci] Add test-linux-stable jobs GHA
  .github/workflows/tests-linux-stable.yml
  .gitlab/pipeline/test.yml
Labels: R0-silent

#5247 Backport #4791
  .gitlab/pipeline/zombienet/polkadot.yml
  Cargo.lock
  polkadot/node/core/candidate-validation/Cargo.toml
  polkadot/node/core/candidate-validation/src/lib.rs
  polkadot/node/core/candidate-validation/src/tests.rs
  polkadot/node/service/src/overseer.rs
  polkadot/zombienet_tests/smoke/0005-precompile-pvf-smoke.js
  polkadot/zombienet_tests/smoke/0005-precompile-pvf-smoke.toml
  polkadot/zombienet_tests/smoke/0005-precompile-pvf-smoke.zndsl
  polkadot/zombienet_tests/smoke/0005-register-deregister-validator.js
  polkadot/zombienet_tests/smoke/0005-register-para.js
  prdoc/pr_5247.prdoc
Labels: T0-node, A3-backport, T8-polkadot

#5291 Synchronize templates through PRs, instead of pushes
  .github/workflows/misc-sync-templates.yml
Labels: R0-silent

#5300 Update BHR and BHW runtime versions
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
Labels: R0-silent

#5301 [tests] make emulated setup closer to ecosystem reality
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-rococo/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-westend/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/testing/penpal/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/treasury.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/fellowship_treasury.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/treasury.rs
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
Labels: R0-silent, T10-tests

#5289 [ci] Move checks to GHA
  .github/workflows/checks.yml
Labels: R0-silent

#5273 StorageWeightReclaim: Fix issue when underestimating refund.
  cumulus/primitives/storage-weight-reclaim/src/lib.rs
  prdoc/pr_5273.prdoc
Labels: T1-FRAME

#5306 Fix bridge zombienet tests
  docker/dockerfiles/bridges_zombienet_tests_injected.Dockerfile
Labels: R0-silent

#5142 Move PVF code and PoV decompression to PVF host workers
  Cargo.lock
  polkadot/node/core/candidate-validation/Cargo.toml
  polkadot/node/core/candidate-validation/src/lib.rs
  polkadot/node/core/candidate-validation/src/metrics.rs
  polkadot/node/core/candidate-validation/src/tests.rs
  polkadot/node/core/pvf/benches/host_prepare_rococo_runtime.rs
  polkadot/node/core/pvf/common/src/error.rs
  polkadot/node/core/pvf/common/src/execute.rs
  polkadot/node/core/pvf/common/src/prepare.rs
  polkadot/node/core/pvf/common/src/pvf.rs
  polkadot/node/core/pvf/execute-worker/Cargo.toml
  polkadot/node/core/pvf/execute-worker/src/lib.rs
  polkadot/node/core/pvf/prepare-worker/Cargo.toml
  polkadot/node/core/pvf/prepare-worker/benches/prepare_rococo_runtime.rs
  polkadot/node/core/pvf/prepare-worker/src/lib.rs
  polkadot/node/core/pvf/src/error.rs
  polkadot/node/core/pvf/src/execute/queue.rs
  polkadot/node/core/pvf/src/execute/worker_interface.rs
  polkadot/node/core/pvf/src/host.rs
  polkadot/node/core/pvf/src/metrics.rs
  polkadot/node/core/pvf/src/prepare/worker_interface.rs
  polkadot/node/core/pvf/tests/it/adder.rs
  polkadot/node/core/pvf/tests/it/main.rs
  polkadot/node/core/pvf/tests/it/process.rs
  polkadot/node/overseer/src/lib.rs
  prdoc/pr_5142.prdoc
Labels: T0-node

#5294 Add missing features in templates' node packages
  templates/minimal/README.md
  templates/minimal/node/Cargo.toml
  templates/parachain/README.md
  templates/parachain/node/Cargo.toml
  templates/solochain/README.md
  templates/solochain/node/Cargo.toml
Labels: R0-silent

#4937 prospective-parachains rework: take II
  Cargo.lock
  polkadot/node/core/prospective-parachains/Cargo.toml
  polkadot/node/core/prospective-parachains/src/error.rs
  polkadot/node/core/prospective-parachains/src/fragment_chain/mod.rs
  polkadot/node/core/prospective-parachains/src/fragment_chain/tests.rs
  polkadot/node/core/prospective-parachains/src/lib.rs
  polkadot/node/core/prospective-parachains/src/metrics.rs
  polkadot/node/core/prospective-parachains/src/tests.rs
  polkadot/node/core/provisioner/src/lib.rs
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  polkadot/node/subsystem-types/src/messages.rs
  polkadot/node/subsystem-util/src/backing_implicit_view.rs
  polkadot/node/subsystem-util/src/inclusion_emulator/mod.rs
  prdoc/pr_4937.prdoc
Labels: T8-polkadot

#4460 xcm-executor: allow deposit of multiple assets if at least one of them satisfies ED
  cumulus/parachains/integration-tests/emulated/common/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-rococo/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/teleport.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  polkadot/runtime/rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  polkadot/runtime/westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  prdoc/pr_4460.prdoc
Labels: T6-XCM

#5319 Fix favicon link to fix CI
  docs/sdk/src/lib.rs
Labels: R0-silent, T11-documentation

#5321 fix av-distribution Jaeger spans mem leak
  polkadot/node/network/availability-distribution/src/lib.rs
  polkadot/node/network/availability-distribution/src/requester/mod.rs
  polkadot/node/network/availability-distribution/src/requester/tests.rs
  prdoc/pr_5321.prdoc
Labels: I2-bug, T8-polkadot

#5324 chain-spec: minor clarification on the genesis config patch
  substrate/client/chain-spec/src/lib.rs
Labels: R0-silent

#5318 Remove unnecessary mut
  substrate/client/consensus/common/src/import_queue.rs
  substrate/client/consensus/common/src/import_queue/basic_queue.rs
  substrate/client/network/test/src/block_import.rs
Labels: R0-silent

#5287 ci: Paused `cmd-action` commenter
  .github/workflows/command-inform.yml
Labels: R0-silent

#5310 `polkadot-node-core-pvf-common`: Fix test compilation error
  polkadot/node/core/pvf/common/Cargo.toml
Labels: R0-silent

#5206 Fix spelling issues
  docs/contributor/CONTRIBUTING.md
  docs/contributor/DOCUMENTATION_GUIDELINES.md
  docs/contributor/PULL_REQUEST_TEMPLATE.md
  substrate/docs/SECURITY.md
Labels: R0-silent

#5195 Bump authoring duration for async backing to 2s.
  cumulus/polkadot-parachain/src/service.rs
  docs/sdk/src/guides/async_backing_guide.rs
  prdoc/pr_5195.prdoc
Labels: T9-cumulus

#5325 Create subsystem-benchmarks.yml
  .github/workflows/subsystem-benchmarks.yml
Labels: R0-silent

#5332 [stable2407] Backport #5321
  polkadot/node/network/availability-distribution/src/lib.rs
  polkadot/node/network/availability-distribution/src/requester/mod.rs
  polkadot/node/network/availability-distribution/src/requester/tests.rs
  prdoc/pr_5332.prdoc
Labels: A3-backport, I2-bug, T8-polkadot

#5331 [Bot] Add prdoc generation
  .github/commands-readme.md
  .github/scripts/generate-prdoc.py
  .github/workflows/command-prdoc.yml
Labels: R0-silent

#5337 [stable2407] backport #4937
  Cargo.lock
  polkadot/node/core/prospective-parachains/Cargo.toml
  polkadot/node/core/prospective-parachains/src/error.rs
  polkadot/node/core/prospective-parachains/src/fragment_chain/mod.rs
  polkadot/node/core/prospective-parachains/src/fragment_chain/tests.rs
  polkadot/node/core/prospective-parachains/src/lib.rs
  polkadot/node/core/prospective-parachains/src/metrics.rs
  polkadot/node/core/prospective-parachains/src/tests.rs
  polkadot/node/core/provisioner/src/lib.rs
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  polkadot/node/subsystem-types/src/messages.rs
  polkadot/node/subsystem-util/src/backing_implicit_view.rs
  polkadot/node/subsystem-util/src/inclusion_emulator/mod.rs
  prdoc/pr_4937.prdoc
Labels: A3-backport, T8-polkadot

#5281 StorageWeightReclaim: set to node pov size if higher
  cumulus/primitives/storage-weight-reclaim/src/lib.rs
  prdoc/pr_5281.prdoc
  substrate/frame/system/src/lib.rs
Labels: T1-FRAME

#4998 [Pools] Ensure members can always exit the pool gracefully
  prdoc/pr_4998.prdoc
  substrate/frame/delegated-staking/src/impls.rs
  substrate/frame/delegated-staking/src/lib.rs
  substrate/frame/delegated-staking/src/tests.rs
  substrate/frame/delegated-staking/src/types.rs
  substrate/frame/nomination-pools/src/adapter.rs
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/nomination-pools/src/tests.rs
  substrate/frame/nomination-pools/test-delegate-stake/src/lib.rs
  substrate/frame/nomination-pools/test-delegate-stake/src/mock.rs
  substrate/frame/nomination-pools/test-transfer-stake/src/lib.rs
  substrate/primitives/staking/src/lib.rs
Labels: T2-pallets

#5284 Minor clean up
  prdoc/pr_5284.prdoc
  substrate/primitives/runtime/src/lib.rs
Labels: R0-silent

#4129 Migrate foreign assets v3::Location to v4::Location
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/common/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/send.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/swap.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/send.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/swap.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/send_xcm.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/tests/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases.rs
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases_over_bridge.rs
  prdoc/pr_4129.prdoc
  substrate/frame/assets/Cargo.toml
Labels: T6-XCM

#5297 Stop running the wishlist workflow on forks
  .github/workflows/misc-update-wishlist-leaderboard.yml
Labels: R0-silent

#5338 [tests] dedup test code, add more tests, improve naming and docs
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/chains/parachains/people/people-rococo/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/people/people-westend/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/common/src/macros.rs
  cumulus/parachains/integration-tests/emulated/common/src/xcm_helpers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/send.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/send.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/src/tests/fellowship.rs
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/src/tests/fellowship_salary.rs
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-rococo/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-rococo/src/tests/reap_identity.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-rococo/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/reap_identity.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/teleport.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/xcm_config.rs
Labels: R0-silent, T10-tests

#5359 Make ticket non-optional and add ensure_successful method to Consideration trait
  prdoc/pr_5359.prdoc
  substrate/frame/balances/src/tests/fungible_tests.rs
  substrate/frame/preimage/src/benchmarking.rs
  substrate/frame/preimage/src/lib.rs
  substrate/frame/support/src/traits/storage.rs
  substrate/frame/support/src/traits/tokens/fungible/mod.rs
Labels: T1-FRAME

#5356 Fix OurViewChange small race
  polkadot/node/network/bridge/src/rx/mod.rs
  prdoc/pr_5356.prdoc
Labels: T0-node, T8-polkadot

#5188 Beefy: add benchmarks for `report_fork_voting()`
  Cargo.lock
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/mod.rs
  polkadot/runtime/rococo/src/weights/pallet_beefy_mmr.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/mod.rs
  polkadot/runtime/westend/src/weights/pallet_beefy_mmr.rs
  prdoc/pr_5188.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/beefy-mmr/Cargo.toml
  substrate/frame/beefy-mmr/src/benchmarking.rs
  substrate/frame/beefy-mmr/src/lib.rs
  substrate/frame/beefy-mmr/src/mock.rs
  substrate/frame/beefy-mmr/src/tests.rs
  substrate/frame/beefy-mmr/src/weights.rs
  substrate/frame/beefy/src/default_weights.rs
  substrate/frame/beefy/src/lib.rs
  substrate/frame/beefy/src/mock.rs
  substrate/frame/beefy/src/tests.rs
  substrate/frame/merkle-mountain-range/src/lib.rs
  substrate/frame/merkle-mountain-range/src/mmr/mmr.rs
  substrate/frame/merkle-mountain-range/src/mmr/storage.rs
  substrate/primitives/consensus/beefy/Cargo.toml
  substrate/primitives/consensus/beefy/src/lib.rs
  substrate/primitives/merkle-mountain-range/src/utils.rs
Labels: T15-bridges

#5358 [CI] Fix prdoc command
  .github/workflows/check-runtime-migration.yml
  .github/workflows/command-prdoc.yml
Labels: R0-silent

#5360 Unify `no_genesis` check
  prdoc/pr_5360.prdoc
  substrate/client/service/src/builder.rs
Labels: R0-silent

#4822 [Pools] Fix issues with member migration to `DelegateStake`
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/tests.rs
  prdoc/pr_4822.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/delegated-staking/src/impls.rs
  substrate/frame/delegated-staking/src/lib.rs
  substrate/frame/delegated-staking/src/tests.rs
  substrate/frame/delegated-staking/src/types.rs
  substrate/frame/nomination-pools/runtime-api/src/lib.rs
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/nomination-pools/test-delegate-stake/src/lib.rs
Labels: T2-pallets

#5365 Upgrade accidentally downgraded deps
  Cargo.lock
Labels: R0-silent

#4999 [Pools] fix derivation of pool account
  Cargo.lock
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_4999.prdoc
  substrate/frame/delegated-staking/Cargo.toml
  substrate/frame/delegated-staking/src/lib.rs
  substrate/frame/delegated-staking/src/migration.rs
Labels: R0-silent, T2-pallets

#5367 [Backport] Bump serde_json from 1.0.120 to 1.0.121 in the known_good_semver group (#5169)
  Cargo.lock
  Cargo.toml
  cumulus/primitives/timestamp/Cargo.toml
  prdoc/pr_5367.prdoc
Labels: A1-insubstantial, R0-silent, A3-backport

#5369 [Coretime] Always include UnpaidExecution, not just when revenue is > 0
  polkadot/runtime/parachains/src/coretime/mod.rs
  prdoc/pr_5369.prdoc
Labels: T8-polkadot

#5183 Update Identity pallet README.md
  substrate/frame/identity/README.md
Labels: R0-silent, T2-pallets, T11-documentation

#5352 Aura: Ensure we are building on each relay chain fork
  cumulus/client/consensus/aura/src/collators/basic.rs
  prdoc/pr_5352.prdoc
Labels: T0-node

#5262 Correct some typos in crates' descriptions
  cumulus/client/pov-recovery/Cargo.toml
  cumulus/pallets/aura-ext/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  prdoc/pr_5262.prdoc
  substrate/frame/try-runtime/Cargo.toml
  substrate/frame/whitelist/Cargo.toml
  umbrella/src/lib.rs
Labels: T1-FRAME, T9-cumulus

#3634 fix visibility for `pallet_nfts` types used as call arguments
  substrate/frame/nfts/src/types.rs
Labels: R0-silent

#5370 Backport #5369 to v1.14: Always include UnpaidExecution, not just when revenue is nonzero
  polkadot/runtime/parachains/src/coretime/mod.rs
  prdoc/pr_5370.prdoc
Labels: A3-backport, T8-polkadot

#5202 Backport pallet info pub to SDK 1.14.0
  Cargo.lock
  polkadot/xcm/Cargo.toml
  polkadot/xcm/src/v4/mod.rs
  prdoc/pr_5202.prdoc
Labels: T6-XCM

#5340 Moving cargo check for runtimes to GHA
  .github/actions/cargo-check-runtimes/action.yml
  .github/workflows/check-cargo-check-runtimes.yml
Labels: R0-silent

#5348 allow for `u8` to be used as hold/freeze reason
  prdoc/pr_5348.prdoc
  substrate/frame/support/src/traits/misc.rs
Labels: T1-FRAME

#5326 Update Readme of the `polkadot` crate
  polkadot/README.md
  prdoc/pr_5326.prdoc
Labels: T8-polkadot, T11-documentation

#5373 Fix zombienet bridges test
  bridges/testing/environments/rococo-westend/bridges_rococo_westend.sh
  bridges/testing/framework/js-helpers/wrapped-assets-balance.js
Labels: R0-silent, T6-XCM

#5252 More logs in `is_potential_spam` from `dispute-coordinator`
  polkadot/node/core/dispute-coordinator/src/initialized.rs
  polkadot/node/core/dispute-coordinator/src/lib.rs
  prdoc/pr_5252.prdoc
Labels: R0-silent, I3-annoyance

#5330 Remove redundant minimal template workspace
  Cargo.lock
  Cargo.toml
  templates/minimal/Cargo.toml
  templates/minimal/src/lib.rs
Labels: R0-silent

#5204 Fix doc: start_destroy doesn't need asset to be frozen
  prdoc/pr_5204.prdoc
  substrate/frame/assets/src/lib.rs
  substrate/frame/support/src/traits/tokens/misc.rs
Labels: T2-pallets

#5339 Replace unnecessary `&mut self` with `&self` in `BlockImport::import_block()`
  cumulus/client/consensus/common/src/lib.rs
  cumulus/client/consensus/common/src/parachain_consensus.rs
  cumulus/client/consensus/common/src/tests.rs
  cumulus/client/network/src/tests.rs
  cumulus/client/relay-chain-inprocess-interface/src/lib.rs
  cumulus/pallets/parachain-system/src/validate_block/tests.rs
  cumulus/test/service/benches/validate_block_glutton.rs
  cumulus/test/service/src/bench_utils.rs
  polkadot/node/test/client/src/lib.rs
  polkadot/xcm/xcm-executor/integration-tests/src/lib.rs
  prdoc/pr_5339.prdoc
  substrate/bin/node/cli/benches/block_production.rs
  substrate/bin/node/cli/tests/basic.rs
  substrate/client/basic-authorship/src/basic_authorship.rs
  substrate/client/consensus/babe/src/lib.rs
  substrate/client/consensus/babe/src/tests.rs
  substrate/client/consensus/beefy/src/import.rs
  substrate/client/consensus/beefy/src/tests.rs
  substrate/client/consensus/common/src/block_import.rs
  substrate/client/consensus/common/src/import_queue/basic_queue.rs
  substrate/client/consensus/grandpa/src/finality_proof.rs
  substrate/client/consensus/grandpa/src/import.rs
  substrate/client/consensus/grandpa/src/tests.rs
  substrate/client/consensus/grandpa/src/voting_rule.rs
  substrate/client/consensus/grandpa/src/warp_proof.rs
  substrate/client/consensus/pow/src/lib.rs
  substrate/client/consensus/pow/src/worker.rs
  substrate/client/merkle-mountain-range/src/test_utils.rs
  substrate/client/network/src/bitswap/mod.rs
  substrate/client/network/sync/src/strategy.rs
  substrate/client/network/sync/src/strategy/chain_sync/test.rs
  substrate/client/network/test/src/block_import.rs
  substrate/client/network/test/src/lib.rs
  substrate/client/offchain/src/lib.rs
  substrate/client/rpc-spec-v2/src/archive/tests.rs
  substrate/client/rpc-spec-v2/src/chain_head/subscription/inner.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
  substrate/client/rpc/src/chain/tests.rs
  substrate/client/rpc/src/dev/tests.rs
  substrate/client/rpc/src/state/tests.rs
  substrate/client/service/src/client/client.rs
  substrate/client/service/test/src/client/mod.rs
  substrate/client/transaction-pool/tests/pool.rs
  substrate/test-utils/client/src/client_ext.rs
  substrate/test-utils/runtime/client/src/trait_tests.rs
  substrate/test-utils/runtime/src/lib.rs
Labels: T0-node

#5376 binary-merkle-tree: Do not spam test output
  prdoc/pr_5376.prdoc
  substrate/utils/binary-merkle-tree/src/lib.rs
Labels: R0-silent

#5387 Fix publishing of the`chain-spec-builder` image
  .github/workflows/release-50_publish-docker.yml
Labels: R0-silent

#5380 Fix leases with gaps and time slice calculation in `MigrateToCoretime`
  polkadot/runtime/parachains/src/coretime/migration.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_5380.prdoc
Labels: T8-polkadot

#5411 approval-distribution: Fix preallocation of ApprovalEntries
  polkadot/node/network/approval-distribution/src/lib.rs
  prdoc/pr_5411.prdoc
Labels: R0-silent

#5417 Fix mmr zombienet test
  polkadot/zombienet_tests/functional/0003-mmr-generate-and-verify-proof.js
Labels: R0-silent

#5345 Migrated `docs` scripts to GitHub actions
  .github/workflows/docs.yml
Labels: R0-silent

#5288 polkadot-parachain: compile separate lib and bin
  Cargo.lock
  Cargo.toml
  cumulus/polkadot-parachain/Cargo.toml
  cumulus/polkadot-parachain/polkadot-parachain-lib/Cargo.toml
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/cli.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/command.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/common/aura.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/common/chain_spec.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/common/mod.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/common/runtime.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/fake_runtime_api/asset_hub_polkadot_aura.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/fake_runtime_api/aura.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/fake_runtime_api/mod.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/lib.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/rpc.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/service.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/tests/benchmark_storage_works.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/tests/common.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/tests/polkadot_argument_parsing.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/tests/polkadot_mdns_issue.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/tests/purge_chain_works.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/tests/running_the_node_and_interrupt.rs
  cumulus/polkadot-parachain/src/chain_spec/asset_hubs.rs
  cumulus/polkadot-parachain/src/chain_spec/bridge_hubs.rs
  cumulus/polkadot-parachain/src/chain_spec/collectives.rs
  cumulus/polkadot-parachain/src/chain_spec/contracts.rs
  cumulus/polkadot-parachain/src/chain_spec/coretime.rs
  cumulus/polkadot-parachain/src/chain_spec/glutton.rs
  cumulus/polkadot-parachain/src/chain_spec/mod.rs
  cumulus/polkadot-parachain/src/chain_spec/penpal.rs
  cumulus/polkadot-parachain/src/chain_spec/people.rs
  cumulus/polkadot-parachain/src/chain_spec/rococo_parachain.rs
  cumulus/polkadot-parachain/src/chain_spec/seedling.rs
  cumulus/polkadot-parachain/src/chain_spec/shell.rs
  cumulus/polkadot-parachain/src/cli.rs
  cumulus/polkadot-parachain/src/command.rs
  cumulus/polkadot-parachain/src/main.rs
  docs/sdk/src/guides/enable_elastic_scaling_mvp.rs
  prdoc/pr_5288.prdoc
  umbrella/Cargo.toml
  umbrella/src/lib.rs
Labels: T0-node

#5428 docs: Fix beefy primitives link in beefy README
  substrate/client/consensus/beefy/README.md
Labels: R0-silent

#5407 peerstore: Clarify peer report warnings
  prdoc/pr_5407.prdoc
  substrate/client/network/src/litep2p/peerstore.rs
  substrate/client/network/src/peer_store.rs
Labels: T0-node, I5-enhancement, D0-easy

#5436 Add the Polkadot Coretime chain-spec
  cumulus/parachains/chain-specs/coretime-polkadot.json
  cumulus/polkadot-parachain/chain-specs/coretime-polkadot.json
  cumulus/polkadot-parachain/src/chain_spec/coretime.rs
  prdoc/pr_5436.prdoc
Labels: T14-system_parachains

#5374 [Backport] Version bumps and prdoc reorgs from stable2407-1
  polkadot/node/primitives/src/lib.rs
  prdoc/1.15.1/pr_4791.prdoc
  prdoc/1.15.1/pr_4937.prdoc
  prdoc/1.15.1/pr_5273.prdoc
  prdoc/1.15.1/pr_5281.prdoc
  prdoc/1.15.1/pr_5321.prdoc
Labels: R0-silent, A3-backport, D0-easy

#5392 Don't disconnect on invalid imports.
  polkadot/node/network/dispute-distribution/src/receiver/mod.rs
  prdoc/pr_5392.prdoc
Labels: T0-node

#5431 Remove the need to wait for target block header in warp sync implementation
  cumulus/client/service/src/lib.rs
  polkadot/node/service/src/lib.rs
  prdoc/pr_5431.prdoc
  substrate/bin/node/cli/src/service.rs
  substrate/client/informant/src/display.rs
  substrate/client/network/sync/src/engine.rs
  substrate/client/network/sync/src/lib.rs
  substrate/client/network/sync/src/strategy.rs
  substrate/client/network/sync/src/strategy/warp.rs
  substrate/client/network/test/src/lib.rs
  substrate/client/network/test/src/sync.rs
  substrate/client/service/src/builder.rs
  substrate/client/service/src/lib.rs
  templates/minimal/node/src/service.rs
  templates/solochain/node/src/service.rs
Labels: T0-node

#5398 Update OpenZeppelin template documentation
  docs/sdk/src/polkadot_sdk/templates.rs
Labels: R0-silent

#5279 Change the chain to Rococo in the parachain template Zombienet config
  templates/parachain/README.md
  templates/parachain/zombienet.toml
Labels: R0-silent

#5243 Improve the appearance of crates on `crates.io`
  .github/scripts/generate-readmes.py
  docs/images/Polkadot_Logo_Horizontal_Pink_BlackOnWhite.png
  docs/images/Polkadot_Logo_Horizontal_Pink_WhiteOnBlack.png
Labels: R0-silent, T11-documentation

#5006 [bridges] Prune messages from confirmation tx body, not from the on_idle
  bridges/modules/messages/src/lib.rs
  bridges/modules/messages/src/outbound_lane.rs
  bridges/modules/messages/src/tests/pallet_tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_messages_rococo_to_rococo_bulletin.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_messages_rococo_to_westend.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_bridge_messages.rs
Labels: R0-silent, T15-bridges

#5410 Reactive syncing metrics
  prdoc/pr_5410.prdoc
  substrate/client/network/sync/src/engine.rs
  substrate/client/network/sync/src/justification_requests.rs
  substrate/client/network/sync/src/strategy.rs
  substrate/client/network/sync/src/strategy/chain_sync.rs
Labels: T0-node

#5427 Remove unnecessary panic
  polkadot/statement-table/src/generic.rs
Labels: R0-silent, T0-node

#5377 Moving `Find FAIL-CI` check to GHA
  .github/workflows/checks-quick.yml
  .gitlab/pipeline/check.yml
Labels: R0-silent

#5442 Derive `Clone` on `EncodableOpaqueLeaf`
  prdoc/pr_5442.prdoc
  substrate/primitives/merkle-mountain-range/src/lib.rs
Labels: T2-pallets

#5430 pallet-collator-selection: correctly register weight in `new_session`
  cumulus/pallets/collator-selection/src/lib.rs
  prdoc/pr_5430.prdoc
Labels: T2-pallets

#5344 Skip slot before creating inherent data providers during major sync
  prdoc/pr_5344.prdoc
  substrate/client/consensus/slots/src/lib.rs
  substrate/client/consensus/slots/src/slots.rs
Labels: T0-node

#5384 `MaybeConsideration` extension trait for `Consideration`
  prdoc/pr_5384.prdoc
  substrate/frame/balances/src/tests/fungible_tests.rs
  substrate/frame/support/src/traits.rs
  substrate/frame/support/src/traits/storage.rs
  substrate/frame/support/src/traits/tokens/fungible/mod.rs
Labels: T1-FRAME

#5450 Sync status refactoring
  prdoc/pr_5450.prdoc
  substrate/client/informant/src/display.rs
  substrate/client/informant/src/lib.rs
  substrate/client/network/sync/src/engine.rs
  substrate/client/network/sync/src/service/syncing_service.rs
  substrate/client/network/sync/src/strategy/chain_sync.rs
  substrate/client/network/sync/src/strategy/state.rs
  substrate/client/network/sync/src/strategy/warp.rs
  substrate/client/network/sync/src/types.rs
  substrate/client/network/test/src/lib.rs
  substrate/client/network/test/src/sync.rs
  substrate/client/service/src/lib.rs
Labels: T0-node

#5361 [CI] Fix SemVer check base commit
  .github/scripts/generate-prdoc.py
  .github/workflows/check-semver.yml
Labels: R0-silent

#5424 Only log the propagating transactions when they are not empty
  prdoc/pr_5424.prdoc
  substrate/client/network/transactions/src/lib.rs
Labels: T0-node, I5-enhancement, D0-easy

#5459 Backport timestamp logging fix
  prdoc/pr_5055.prdoc
  substrate/frame/timestamp/src/lib.rs
Labels: A3-backport

#5462 Make the PR template a default for new PRs
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
  docs/contributor/PULL_REQUEST_TEMPLATE.md
Labels: R0-silent

#5456 Backport #5392
  polkadot/node/network/dispute-distribution/src/receiver/mod.rs
  prdoc/pr_5392.prdoc
Labels: A3-backport

#5439 Remove deprecated calls in cumulus-parachain-system
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/parachain-system/src/mock.rs
  cumulus/pallets/parachain-system/src/tests.rs
  cumulus/pallets/xcmp-queue/src/mock.rs
  prdoc/pr_5439.prdoc
Labels: T2-pallets

#5466 frame-omni-bencher maintenance
  Cargo.lock
  prdoc/pr_5466.prdoc
  substrate/utils/frame/benchmarking-cli/src/pallet/command.rs
  substrate/utils/frame/omni-bencher/Cargo.toml
  substrate/utils/frame/omni-bencher/README.md
  substrate/utils/frame/omni-bencher/src/command.rs
  substrate/utils/frame/omni-bencher/src/main.rs
Labels: T1-FRAME, A4-needs-backport

#5467 Make `PendingConfigs` storage item public
  polkadot/runtime/parachains/src/configuration.rs
  prdoc/pr_5467.prdoc
Labels: T8-polkadot

#5393 Add feature to allow Aura collator to use full PoV size
  cumulus/client/consensus/aura/Cargo.toml
  cumulus/client/consensus/aura/src/collators/basic.rs
  cumulus/client/consensus/aura/src/collators/lookahead.rs
  cumulus/client/consensus/aura/src/collators/slot_based/block_builder_task.rs
  prdoc/pr_5393.prdoc
Labels: T9-cumulus

#5471 polkadot-parachain-bin: Remove contracts parachain
  cumulus/polkadot-parachain/chain-specs/contracts-rococo.json
  cumulus/polkadot-parachain/src/chain_spec/contracts.rs
  cumulus/polkadot-parachain/src/chain_spec/mod.rs
Labels: R0-silent, T0-node

#5443 change try-runtime rpc domains
  .config/lychee.toml
  .github/workflows/check-runtime-migration.yml
  .gitlab/pipeline/check.yml
  prdoc/pr_5443.prdoc
  substrate/utils/frame/remote-externalities/src/lib.rs
Labels: R0-silent

#5504 Update approval-voting-regression-bench
  polkadot/node/core/approval-voting/benches/approval-voting-regression-bench.rs
Labels: R0-silent

#5155 Use umbrella crate for minimal template
  Cargo.lock
  Cargo.toml
  bridges/relays/utils/Cargo.toml
  cumulus/client/consensus/proposer/Cargo.toml
  docs/sdk/Cargo.toml
  docs/sdk/src/reference_docs/chain_spec_runtime/src/runtime.rs
  prdoc/pr_5155.prdoc
  scripts/generate-umbrella.py
  substrate/bin/node/runtime/Cargo.toml
  substrate/frame/contracts/fixtures/Cargo.toml
  substrate/frame/revive/fixtures/Cargo.toml
  substrate/frame/src/lib.rs
  substrate/frame/support/test/tests/pallet_outer_enums_explicit.rs
  substrate/frame/support/test/tests/pallet_outer_enums_implicit.rs
  substrate/primitives/wasm-interface/Cargo.toml
  templates/minimal/node/Cargo.toml
  templates/minimal/node/build.rs
  templates/minimal/node/src/chain_spec.rs
  templates/minimal/node/src/cli.rs
  templates/minimal/node/src/command.rs
  templates/minimal/node/src/main.rs
  templates/minimal/node/src/rpc.rs
  templates/minimal/node/src/service.rs
  templates/minimal/pallets/template/Cargo.toml
  templates/minimal/pallets/template/src/lib.rs
  templates/minimal/runtime/Cargo.toml
  templates/minimal/runtime/build.rs
  templates/minimal/runtime/src/lib.rs
  umbrella/Cargo.toml
Labels: R0-silent, T1-FRAME, T17-Templates

#5507 [Backport] Add feature to allow Aura collator to use full PoV size (#5393)
  cumulus/client/consensus/aura/Cargo.toml
  cumulus/client/consensus/aura/src/collators/basic.rs
  cumulus/client/consensus/aura/src/collators/lookahead.rs
  cumulus/client/consensus/aura/src/collators/slot_based/block_builder_task.rs
  prdoc/pr_5507.prdoc
Labels: A3-backport

#5510 [Backport] Always include UnpaidExecution, not just when revenue is nonzero
  polkadot/runtime/parachains/src/coretime/mod.rs
  prdoc/pr_5510.prdoc
Labels: A3-backport, T8-polkadot

#5269 polkadot-parachain: Add omni-node variant with u64 block number
  Cargo.lock
  cumulus/polkadot-parachain/polkadot-parachain-lib/Cargo.toml
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/cli.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/command.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/common/command.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/common/mod.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/common/rpc.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/common/runtime.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/common/spec.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/common/types.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/fake_runtime_api/asset_hub_polkadot_aura.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/fake_runtime_api/aura.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/fake_runtime_api/mod.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/fake_runtime_api/utils.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/lib.rs
  cumulus/polkadot-parachain/polkadot-parachain-lib/src/service.rs
  cumulus/polkadot-parachain/src/chain_spec/mod.rs
  prdoc/pr_5269.prdoc
Labels: T0-node

#5434 Bridge zombienet tests: remove old command
  .gitlab/pipeline/zombienet/bridges.yml
  bridges/testing/README.md
  bridges/testing/framework/js-helpers/only-required-headers-synced-when-active.js
  bridges/testing/run-test.sh
  bridges/testing/run-tests.sh
  bridges/testing/tests/0003-required-headers-synced-while-active-rococo-to-westend.zndsl
  bridges/testing/tests/0003-required-headers-synced-while-active-westend-to-rococo.zndsl
  bridges/testing/tests/0003-required-headers-synced-while-active/rococo-to-westend.zndsl
  bridges/testing/tests/0003-required-headers-synced-while-active/run.sh
Labels: R0-silent, T10-tests, T15-bridges

#4962 Remove pallet::getter usage from treasury
  prdoc/pr_4962.prdoc
  substrate/frame/treasury/src/benchmarking.rs
  substrate/frame/treasury/src/lib.rs
  substrate/frame/treasury/src/tests.rs
Labels: T2-pallets

#5354 Fix benchmark failures when using `insecure_zero_ed` flag
  prdoc/pr_5354.prdoc
  substrate/frame/balances/src/benchmarking.rs
Labels: T2-pallets

#5457 Command bot GHA v2 - /cmd <cmd>
  .github/command-screnshot.png
  .github/commands-readme.md
  .github/scripts/cmd/_help.py
  .github/scripts/cmd/cmd.py
  .github/workflows/cmd.yml
  .github/workflows/command-bench-all.yml
  .github/workflows/command-bench-overhead.yml
  .github/workflows/command-bench.yml
  .github/workflows/command-fmt.yml
  .github/workflows/command-inform.yml
  .github/workflows/command-prdoc.yml
  .github/workflows/command-sync.yml
  .github/workflows/command-update-ui.yml
  .github/workflows/review-bot.yml
  .github/workflows/runtimes-matrix.json
  .gitignore
  docs/contributor/CONTRIBUTING.md
  docs/contributor/commands-readme.md
  docs/contributor/weight-generation.md
  scripts/bench-all.sh
  scripts/bench.sh
  scripts/command-utils.sh
  scripts/lib/bench-all-cumulus.sh
  scripts/lib/bench-all-pallet.sh
  scripts/lib/bench-all-polkadot.sh
  scripts/lib/bench-all-substrate.sh
  scripts/lib/bench-overhead.sh
  scripts/lib/bench-pallet.sh
  scripts/sync.sh
  scripts/update-ui-tests.sh
Labels: R0-silent

#4795 CI: Add backporting bot
  .github/workflows/check-semver.yml
  .github/workflows/command-backport.yml
  docs/BACKPORT.md
  docs/RELEASE.md
  docs/images/backport-ex2.png
Labels: R0-silent

#5082 short-term fix for para inherent weight overestimation
  polkadot/runtime/parachains/src/builder.rs
  polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs
  polkadot/runtime/parachains/src/paras_inherent/weights.rs
  polkadot/runtime/rococo/src/impls.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/mod.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_common_assigned_slots.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_common_auctions.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_common_claims.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_common_crowdloan.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_common_identity_migrator.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_common_paras_registrar.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_common_slots.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_parachains_configuration.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_parachains_coretime.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_parachains_disputes.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_parachains_hrmp.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_parachains_inclusion.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_parachains_initializer.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_parachains_on_demand.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_parachains_paras.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_parachains_paras_inherent.rs
  polkadot/runtime/westend/src/impls.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/mod.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_common_assigned_slots.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_common_auctions.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_common_crowdloan.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_common_identity_migrator.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_common_paras_registrar.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_common_slots.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_parachains_configuration.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_parachains_coretime.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_parachains_disputes.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_parachains_disputes_slashing.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_parachains_hrmp.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_parachains_inclusion.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_parachains_initializer.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_parachains_on_demand.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_parachains_paras.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_parachains_paras_inherent.rs
  prdoc/pr_5082.prdoc
Labels: T2-pallets, T8-polkadot, T12-benchmarks

#5511 [ci] Migrate checks to GHA
  .github/workflows/checks.yml
  .github/workflows/tests.yml
  .gitlab-ci.yml
  .gitlab/pipeline/check.yml
  .gitlab/pipeline/test.yml
Labels: R0-silent

#5316 Add an utility function to get the first timestamp of a slot
  prdoc/pr_5316.prdoc
  substrate/primitives/consensus/slots/src/lib.rs
Labels: T0-node

#5517 [CI] Fixup backport bot
  .github/workflows/command-backport.yml
Labels: R0-silent

#5270 inclusion: bench `enact_candidate` weight
  polkadot/node/core/pvf/common/Cargo.toml
  polkadot/runtime/parachains/src/builder.rs
  polkadot/runtime/parachains/src/dmp.rs
  polkadot/runtime/parachains/src/hrmp.rs
  polkadot/runtime/parachains/src/inclusion/benchmarking.rs
  polkadot/runtime/parachains/src/inclusion/mod.rs
  polkadot/runtime/parachains/src/inclusion/tests.rs
  polkadot/runtime/parachains/src/mock.rs
  polkadot/runtime/parachains/src/paras/mod.rs
  polkadot/runtime/parachains/src/paras_inherent/mod.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
  polkadot/runtime/parachains/src/paras_inherent/weights.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_parachains_inclusion.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_parachains_inclusion.rs
  prdoc/pr_5270.prdoc
Labels: T8-polkadot, T12-benchmarks

#5519 [ci] Move check-runtime-migration to GHA
  .github/workflows/check-runtime-migration.yml
  .gitlab-ci.yml
  .gitlab/pipeline/check.yml
Labels: R0-silent

#5522 Add support for memory-profiling on subsystem-bench
  Cargo.lock
  Cargo.toml
  polkadot/node/subsystem-bench/Cargo.toml
  polkadot/node/subsystem-bench/README.md
  polkadot/node/subsystem-bench/src/cli/subsystem-bench.rs
Labels: R0-silent

#5396 Simplify `SyncingEngine::new()` a bit
  prdoc/pr_5396.prdoc
  substrate/client/network/sync/src/engine.rs
Labels: T0-node

#5528 Added `mac-setup` script
  .github/actions/set-up-mac/README.md
  .github/actions/set-up-mac/action.yml
Labels: R0-silent

#5525 Polkadot Primitives v8
  polkadot/node/collation-generation/src/lib.rs
  polkadot/node/core/backing/src/lib.rs
  polkadot/node/core/prospective-parachains/src/lib.rs
  polkadot/node/network/collator-protocol/src/collator_side/mod.rs
  polkadot/node/network/collator-protocol/src/validator_side/mod.rs
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  polkadot/node/network/statement-distribution/src/v2/statement_store.rs
  polkadot/node/service/src/chain_spec.rs
  polkadot/node/subsystem-util/src/lib.rs
  polkadot/node/subsystem-util/src/runtime/mod.rs
  polkadot/node/subsystem-util/src/vstaging.rs
  polkadot/node/test/service/src/chain_spec.rs
  polkadot/primitives/src/lib.rs
  polkadot/primitives/src/v8/async_backing.rs
  polkadot/primitives/src/v8/executor_params.rs
  polkadot/primitives/src/v8/metrics.rs
  polkadot/primitives/src/v8/mod.rs
  polkadot/primitives/src/v8/signed.rs
  polkadot/primitives/src/v8/slashing.rs
  polkadot/primitives/src/vstaging/mod.rs
  polkadot/runtime/parachains/src/configuration.rs
  polkadot/runtime/parachains/src/configuration/migration/v12.rs
  polkadot/runtime/parachains/src/paras/tests.rs
  polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
  polkadot/runtime/parachains/src/scheduler/tests.rs
  polkadot/runtime/parachains/src/session_info/tests.rs
  polkadot/runtime/rococo/src/genesis_config_presets.rs
Labels: R0-silent

#5513 Add more logs for AcceptanceCheckErr
  polkadot/runtime/parachains/src/inclusion/mod.rs
  prdoc/pr_5513.prdoc
Labels: T2-pallets

#5531 fix cmd bot PR context
  .github/workflows/cmd.yml
  .github/workflows/command-inform.yml
  scripts/update-ui-tests.sh
Labels: R0-silent

#3996 asset-hub-rococo: genesis config presets added
  Cargo.lock
  cumulus/parachains/common/src/genesis_config_helpers.rs
  cumulus/parachains/common/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/genesis_config_presets.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/constants/src/rococo.rs
  cumulus/polkadot-parachain/src/chain_spec/asset_hubs.rs
  prdoc/pr_3996.prdoc
Labels: R0-silent, T14-system_parachains

#4739 parachain-template: genesis config presets added
  Cargo.lock
  prdoc/pr_4739.prdoc
  substrate/primitives/genesis-builder/src/lib.rs
  templates/parachain/node/src/chain_spec.rs
  templates/parachain/runtime/Cargo.toml
  templates/parachain/runtime/src/apis.rs
  templates/parachain/runtime/src/genesis_config_presets.rs
  templates/parachain/runtime/src/lib.rs
Labels: R0-silent, T11-documentation, T17-Templates

#5535 'remainder' instead of reminder && explicit instruction to clone
  docs/sdk/src/guides/your_first_pallet/mod.rs
  docs/sdk/src/guides/your_first_pallet/with_event.rs
Labels: R0-silent, T11-documentation

#5537 Update CODEOWNERS for contracts
  .github/CODEOWNERS
Labels: R0-silent

#5536 Update cmd.yml
  .github/workflows/cmd.yml
Labels: R0-silent
