Repository paritytech/polkadot-sdk, pull requests merged in 2024-11, with the labels that each got.

#3970 Update Treasury to Support Relay Chain Block Number Provider
  cumulus/parachains/runtimes/collectives/collectives-westend/src/fellowship/mod.rs
  polkadot/runtime/common/src/impls.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_3970.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/bounties/src/benchmarking.rs
  substrate/frame/bounties/src/lib.rs
  substrate/frame/bounties/src/tests.rs
  substrate/frame/child-bounties/src/benchmarking.rs
  substrate/frame/child-bounties/src/lib.rs
  substrate/frame/child-bounties/src/tests.rs
  substrate/frame/tips/src/tests.rs
  substrate/frame/treasury/src/lib.rs
  substrate/frame/treasury/src/tests.rs
Labels: T1-FRAME

#5908 collation-generation: use v2 receipts
  Cargo.lock
  polkadot/node/collation-generation/Cargo.toml
  polkadot/node/collation-generation/src/error.rs
  polkadot/node/collation-generation/src/lib.rs
  polkadot/node/collation-generation/src/metrics.rs
  polkadot/node/collation-generation/src/tests.rs
  polkadot/primitives/Cargo.toml
  polkadot/primitives/src/vstaging/mod.rs
  prdoc/pr_5908.prdoc
Labels: T8-polkadot

#6317 [eth-rpc] Fixes
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_6317.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/client/service/src/lib.rs
  substrate/frame/revive/rpc/Cargo.toml
  substrate/frame/revive/rpc/examples/rust/transfer.rs
  substrate/frame/revive/rpc/revive_chain.metadata
  substrate/frame/revive/rpc/src/cli.rs
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/rpc/src/tests.rs
  substrate/frame/revive/src/evm/runtime.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
Labels: R0-silent, T7-smart_contracts

#6318 Refactor pallet `claims`
  polkadot/runtime/common/src/claims.rs
  prdoc/pr_6318.prdoc
Labels: T2-pallets, T12-benchmarks

#6296 Migrate pallet-glutton benchmark to v2
  prdoc/pr_6296.prdoc
  substrate/frame/glutton/src/benchmarking.rs
Labels: T2-pallets, T12-benchmarks

#6316 Migrate pallet-election-provider-multi-phase benchmark to v2 and improve doc
  prdoc/pr_6316.prdoc
  substrate/frame/election-provider-multi-phase/src/benchmarking.rs
Labels: T2-pallets, T12-benchmarks

#6257 fix claim queue size
  polkadot/runtime/parachains/src/scheduler.rs
  polkadot/runtime/parachains/src/scheduler/tests.rs
  prdoc/pr_6257.prdoc
Labels: I2-bug, T8-polkadot

#6178 inclusion emulator: correctly handle UMP signals
  polkadot/node/subsystem-util/src/inclusion_emulator/mod.rs
  polkadot/primitives/test-helpers/Cargo.toml
Labels: R0-silent, T8-polkadot

#6346 Disable flaky tests reported in #6343 / #6345
  .gitlab/pipeline/zombienet/polkadot.yml
Labels: R0-silent, T10-tests

#6351 Silent annoying log
  cumulus/primitives/storage-weight-reclaim/src/lib.rs
Labels: R0-silent, T0-node

#5961 Bounty Pallet: add `approve_bounty_with_curator` call to `bounties` pallet
  polkadot/runtime/rococo/src/weights/pallet_bounties.rs
  prdoc/pr_5961.prdoc
  substrate/frame/bounties/src/benchmarking.rs
  substrate/frame/bounties/src/lib.rs
  substrate/frame/bounties/src/tests.rs
  substrate/frame/bounties/src/weights.rs
Labels: T1-FRAME

#6298 authority-discovery: Populate DHT records with public listen addresses
  prdoc/pr_6298.prdoc
  substrate/client/authority-discovery/src/worker.rs
  substrate/client/authority-discovery/src/worker/tests.rs
  substrate/client/cli/src/commands/run_cmd.rs
Labels: T0-node, I5-enhancement, D1-medium, A4-needs-backport

#6221 snowbridge: allow account conversion for Ethereum accounts
  bridges/snowbridge/primitives/router/src/inbound/mod.rs
  bridges/snowbridge/primitives/router/src/inbound/tests.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  prdoc/pr_6221.prdoc
Labels: T15-bridges

#6361 Remove leftover references of Wococo
  bridges/primitives/messages/src/lane.rs
  cumulus/parachains/runtimes/assets/common/src/matching.rs
  polkadot/cli/src/cli.rs
Labels: R0-silent

#6291 migrate pallet-remarks to v2 bench syntax
  prdoc/pr_6291.prdoc
  substrate/frame/remark/src/benchmarking.rs
Labels: T2-pallets, T12-benchmarks

#5985 [pallet-staking] Additional check for virtual stakers
  substrate/frame/staking/src/pallet/impls.rs
  substrate/primitives/panic-handler/src/lib.rs
Labels: R0-silent, T2-pallets

#6353 litep2p: Update litep2p to v0.8.0
  Cargo.lock
  Cargo.toml
  prdoc/pr_6353.prdoc
  substrate/client/network/src/litep2p/discovery.rs
Labels: T0-node, I5-enhancement

#6217 refactor and harden check_core_index
  cumulus/client/consensus/aura/src/collators/lookahead.rs
  cumulus/client/consensus/aura/src/collators/slot_based/block_builder_task.rs
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/primitives/core/src/lib.rs
  polkadot/node/collation-generation/src/error.rs
  polkadot/node/collation-generation/src/lib.rs
  polkadot/node/subsystem-util/src/inclusion_emulator/mod.rs
  polkadot/primitives/src/vstaging/mod.rs
  polkadot/runtime/parachains/src/inclusion/mod.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
  prdoc/pr_6217.prdoc
Labels: T8-polkadot

#6169 [Deprecation] deprecate treasury `spend_local` call and related items
  prdoc/pr_6169.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/bounties/src/lib.rs
  substrate/frame/bounties/src/tests.rs
  substrate/frame/child-bounties/src/tests.rs
  substrate/frame/tips/src/tests.rs
  substrate/frame/treasury/src/benchmarking.rs
  substrate/frame/treasury/src/lib.rs
  substrate/frame/treasury/src/migration.rs
  substrate/frame/treasury/src/tests.rs
Labels: T1-FRAME

#6287 Run check semver in MQ
  .github/workflows/check-semver.yml
Labels: R0-silent

#6366 [Release|CI/CD] adjust release pipelines
  .github/scripts/common/lib.sh
  .github/workflows/release-10_rc-automation.yml
  .github/workflows/release-branchoff-stable.yml
  .github/workflows/release-build-rc.yml
  .github/workflows/release-reusable-rc-buid.yml
Labels: R0-silent

#6360 [eth-rpc] proxy /health
  Cargo.lock
  prdoc/pr_6360.prdoc
  substrate/frame/revive/rpc/Cargo.toml
  substrate/frame/revive/rpc/src/cli.rs
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/rpc/src/lib.rs
  substrate/frame/revive/rpc/src/rpc_health.rs
Labels: R0-silent, T7-smart_contracts

#6365 pallet-revive: Use `RUSTUP_TOOLCHAIN` if set
  prdoc/pr_6365.prdoc
  substrate/frame/revive/fixtures/build.rs
Labels: R0-silent

#6295 Migrate pallet-im-online benchmark to v2
  prdoc/pr_6295.prdoc
  substrate/frame/im-online/src/benchmarking.rs
Labels: T2-pallets, T12-benchmarks

#5693 Remove `sp_runtime::RuntimeString` and replace with `Cow<'static, str>` or `String` depending on use case
  cumulus/client/network/src/tests.rs
  cumulus/client/pov-recovery/src/tests.rs
  cumulus/pallets/parachain-system/src/mock.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/genesis_config_presets.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/genesis_config_presets.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/genesis_config_presets.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/genesis_config_presets.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/genesis_config_presets.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  cumulus/polkadot-omni-node/lib/src/fake_runtime_api/utils.rs
  cumulus/test/runtime/src/genesis_config_presets.rs
  cumulus/test/runtime/src/lib.rs
  docs/sdk/packages/guides/first-runtime/src/lib.rs
  docs/sdk/src/reference_docs/chain_spec_runtime/src/presets.rs
  docs/sdk/src/reference_docs/chain_spec_runtime/src/runtime.rs
  polkadot/runtime/rococo/src/genesis_config_presets.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/genesis_config_presets.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_5693.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/bin/utils/chain-spec-builder/src/lib.rs
  substrate/client/consensus/pow/src/lib.rs
  substrate/client/executor/src/wasm_runtime.rs
  substrate/frame/benchmarking/src/utils.rs
  substrate/frame/benchmarking/src/v1.rs
  substrate/frame/revive/src/evm/runtime.rs
  substrate/frame/src/lib.rs
  substrate/frame/support/src/genesis_builder_helper.rs
  substrate/frame/support/test/compile_pass/src/lib.rs
  substrate/frame/system/src/lib.rs
  substrate/frame/system/src/mock.rs
  substrate/primitives/api/src/lib.rs
  substrate/primitives/genesis-builder/src/lib.rs
  substrate/primitives/runtime/src/lib.rs
  substrate/primitives/runtime/src/runtime_string.rs
  substrate/primitives/version/proc-macro/src/decl_runtime_version.rs
  substrate/primitives/version/src/lib.rs
  substrate/test-utils/runtime/src/lib.rs
  templates/minimal/runtime/src/lib.rs
  templates/parachain/runtime/src/apis.rs
  templates/parachain/runtime/src/genesis_config_presets.rs
  templates/parachain/runtime/src/lib.rs
  templates/solochain/runtime/src/apis.rs
  templates/solochain/runtime/src/genesis_config_presets.rs
  templates/solochain/runtime/src/lib.rs
Labels: T17-primitives

#6373 `chain-spec-builder`: info about patch/full files added
  prdoc/pr_6373.prdoc
  substrate/bin/utils/chain-spec-builder/README.docify.md
  substrate/bin/utils/chain-spec-builder/README.md
Labels: R0-silent, T11-documentation

#6255 pallet-child-bounties index child bounty by parent bounty
  polkadot/runtime/rococo/src/lib.rs
  prdoc/pr_6255.prdoc
  substrate/frame/bounties/src/lib.rs
  substrate/frame/child-bounties/src/benchmarking.rs
  substrate/frame/child-bounties/src/lib.rs
  substrate/frame/child-bounties/src/migration.rs
  substrate/frame/child-bounties/src/tests.rs
  substrate/primitives/core/src/crypto.rs
Labels: T1-FRAME

#6016 litep2p/peerset: Do not disconnect all peers on `SetReservedPeers` command
  prdoc/pr_6016.prdoc
  substrate/client/network/src/litep2p/shim/notification/peerset.rs
  substrate/client/network/src/litep2p/shim/notification/tests/peerset.rs
Labels: T0-node, I5-enhancement

#6383 Small nits for XCMv5
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_bulletin_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_westend_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/bridge_to_rococo_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/common/src/message_queue.rs
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
  polkadot/runtime/parachains/src/coretime/migration.rs
  polkadot/xcm/docs/src/cookbook/relay_token_transactor/parachain/xcm_config.rs
  polkadot/xcm/docs/src/cookbook/relay_token_transactor/relay_chain/mod.rs
  polkadot/xcm/docs/src/cookbook/relay_token_transactor/relay_chain/xcm_config.rs
  polkadot/xcm/src/v4/mod.rs
  polkadot/xcm/src/v5/mod.rs
Labels: R0-silent

#6376 polkadot-service: Fix flaky tests
  Cargo.lock
  Cargo.toml
  polkadot/node/service/Cargo.toml
  polkadot/node/service/src/workers.rs
Labels: R0-silent

#6337 Don't expose metadata for Runtime APIs that haven't been implemented
  prdoc/pr_6337.prdoc
  substrate/frame/support/test/tests/runtime_metadata.rs
  substrate/primitives/api/proc-macro/src/decl_runtime_apis.rs
  substrate/primitives/api/proc-macro/src/impl_runtime_apis.rs
  substrate/primitives/api/proc-macro/src/runtime_metadata.rs
  substrate/primitives/api/proc-macro/src/utils.rs
  substrate/primitives/api/test/tests/decl_and_impl.rs
  substrate/primitives/consensus/babe/src/lib.rs
Labels: I2-bug, T4-runtime_API

#6011 collator protocol: validate descriptor version on the validator side
  polkadot/node/network/collator-protocol/src/error.rs
  polkadot/node/network/collator-protocol/src/validator_side/collation.rs
  polkadot/node/network/collator-protocol/src/validator_side/mod.rs
  polkadot/node/network/collator-protocol/src/validator_side/tests/mod.rs
  polkadot/node/network/collator-protocol/src/validator_side/tests/prospective_parachains.rs
  prdoc/pr_6011.prdoc
Labels: T8-polkadot

#4012 sp-api: `impl_runtime_apis!` replace the use of `Self` as a type argument
  prdoc/pr_4012.prdoc
  substrate/primitives/api/proc-macro/Cargo.toml
  substrate/primitives/api/proc-macro/src/impl_runtime_apis.rs
Labels: R0-silent, D1-medium

#6384 Fix #6102
  polkadot/runtime/parachains/src/assigner_coretime/mod.rs
  polkadot/runtime/parachains/src/assigner_coretime/tests.rs
  prdoc/pr_6384.prdoc
Labels: T2-pallets, T8-polkadot

#6391 Xcm v5 migration for bhw
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/bridge_to_ethereum_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/bridge_to_rococo_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
Labels: R0-silent, T6-XCM

#6357 [Pools] New runtime api that returns the pot accounts associated with the pool
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_6357.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/nomination-pools/runtime-api/src/lib.rs
  substrate/frame/nomination-pools/src/lib.rs
Labels: T2-pallets, T4-runtime_API

#6315 Migrate pallet-election-provider-support-benchmarking benchmark to v2
  prdoc/pr_6315.prdoc
  substrate/frame/election-provider-support/benchmarking/src/inner.rs
Labels: T2-pallets, T12-benchmarks

#6387 fix shared-core-idle-parachain flaky test
  .gitlab/pipeline/zombienet/polkadot.yml
  polkadot/zombienet_tests/functional/0018-shared-core-idle-parachain.zndsl
Labels: R0-silent, T10-tests

#6379 substrate/zombienet: Fix 0002-validators-warp-sync
  substrate/zombienet/0002-validators-warp-sync/test-validators-warp-sync.zndsl
Labels: R0-silent, I2-bug, D0-easy

#5737 Syncing strategy refactoring (part 3)
  .gitignore
  cumulus/client/service/src/lib.rs
  cumulus/polkadot-omni-node/lib/src/nodes/manual_seal.rs
  polkadot/node/service/src/lib.rs
  prdoc/pr_5737.prdoc
  substrate/bin/node/cli/src/service.rs
  substrate/client/consensus/common/src/import_queue.rs
  substrate/client/consensus/common/src/import_queue/basic_queue.rs
  substrate/client/consensus/common/src/import_queue/buffered_link.rs
  substrate/client/consensus/common/src/import_queue/mock.rs
  substrate/client/network/sync/src/block_relay_protocol.rs
  substrate/client/network/sync/src/block_request_handler.rs
  substrate/client/network/sync/src/engine.rs
  substrate/client/network/sync/src/mock.rs
  substrate/client/network/sync/src/pending_responses.rs
  substrate/client/network/sync/src/service/mock.rs
  substrate/client/network/sync/src/service/network.rs
  substrate/client/network/sync/src/service/syncing_service.rs
  substrate/client/network/sync/src/strategy.rs
  substrate/client/network/sync/src/strategy/chain_sync.rs
  substrate/client/network/sync/src/strategy/chain_sync/test.rs
  substrate/client/network/sync/src/strategy/polkadot.rs
  substrate/client/network/sync/src/strategy/state.rs
  substrate/client/network/sync/src/strategy/warp.rs
  substrate/client/network/sync/src/types.rs
  substrate/client/network/test/src/lib.rs
  substrate/client/network/test/src/service.rs
  substrate/client/service/src/builder.rs
  substrate/client/service/src/chain_ops/import_blocks.rs
  substrate/client/service/src/lib.rs
  templates/minimal/node/src/service.rs
  templates/solochain/node/Cargo.toml
  templates/solochain/node/src/service.rs
Labels: T0-node

#5984 [pallet-staking] Add page info to `PayoutStarted` event
  prdoc/pr_5984.prdoc
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/tests.rs
Labels: T2-pallets

#6380 net/discovery: Do not propagate external addr with different peerIDs
  prdoc/pr_6380.prdoc
  substrate/client/network/src/discovery.rs
  substrate/client/network/src/litep2p/discovery.rs
  substrate/client/network/src/litep2p/mod.rs
Labels: T0-node, I5-enhancement

#5616 PVF: drop backing jobs if it is too late
  Cargo.lock
  polkadot/node/core/backing/src/lib.rs
  polkadot/node/core/backing/src/tests/mod.rs
  polkadot/node/core/backing/src/tests/prospective_parachains.rs
  polkadot/node/core/candidate-validation/src/lib.rs
  polkadot/node/core/candidate-validation/src/tests.rs
  polkadot/node/core/pvf/Cargo.toml
  polkadot/node/core/pvf/src/error.rs
  polkadot/node/core/pvf/src/execute/queue.rs
  polkadot/node/core/pvf/src/host.rs
  polkadot/node/core/pvf/src/priority.rs
  polkadot/node/core/pvf/tests/it/adder.rs
  polkadot/node/core/pvf/tests/it/main.rs
  polkadot/node/core/pvf/tests/it/process.rs
  polkadot/node/overseer/examples/minimal-example.rs
  polkadot/node/overseer/src/lib.rs
  polkadot/node/overseer/src/tests.rs
  polkadot/node/subsystem-types/Cargo.toml
  polkadot/node/subsystem-types/src/messages.rs
  prdoc/pr_5616.prdoc
Labels: T0-node, I5-enhancement, T8-polkadot

#6399 [Release|CI/CD] Add node version to deb package version
  .github/scripts/release/build-deb.sh
  .github/workflows/release-reusable-rc-buid.yml
Labels: R0-silent

#6382 gensis-config: patching default `RuntimeGenesisConfig` fixed
  prdoc/pr_6382.prdoc
  substrate/bin/utils/chain-spec-builder/src/lib.rs
  substrate/client/chain-spec/src/genesis_config_builder.rs
  substrate/client/chain-spec/src/json_patch.rs
Labels: T0-node

#6261 Add missing events to identity pallet
  prdoc/pr_6261.prdoc
  substrate/frame/identity/src/lib.rs
  substrate/frame/identity/src/tests.rs
Labels: T2-pallets, T14-system_parachains, D0-easy

#6077 Add networking benchmarks for libp2p
  Cargo.lock
  prdoc/pr_6077.prdoc
  substrate/client/network/Cargo.toml
  substrate/client/network/benches/notifications_protocol.rs
  substrate/client/network/benches/request_response_protocol.rs
Labels: R0-silent, T12-benchmarks

#6406 make prospective-parachains debug logs less spammy
  polkadot/node/core/prospective-parachains/src/lib.rs
  prdoc/pr_6406.prdoc
Labels: I3-annoyance, T8-polkadot

#6314 Migrate pallet-elections-phragmen benchmark to v2 and improve doc
  prdoc/pr_6314.prdoc
  substrate/frame/elections-phragmen/src/benchmarking.rs
Labels: T2-pallets, T12-benchmarks

#6163 Expose more syncing types to enable custom syncing strategy
  prdoc/pr_6163.prdoc
  substrate/client/network/sync/src/lib.rs
  substrate/client/network/sync/src/strategy.rs
  substrate/client/network/sync/src/strategy/state.rs
Labels: T0-node

#6349 runtimes: presets are provided as config patches
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/genesis_config_presets.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/genesis_config_presets.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/genesis_config_presets.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/genesis_config_presets.rs
  docs/sdk/packages/guides/first-runtime/src/lib.rs
  polkadot/runtime/rococo/src/genesis_config_presets.rs
  polkadot/runtime/westend/src/genesis_config_presets.rs
  prdoc/pr_6349.prdoc
  substrate/frame/support/src/generate_genesis_config.rs
  templates/minimal/runtime/src/lib.rs
  templates/parachain/runtime/src/genesis_config_presets.rs
  templates/solochain/runtime/src/genesis_config_presets.rs
Labels: R0-silent, T1-FRAME

#6290 Migrate pallet-transaction-storage and pallet-indices to benchmark v2
  prdoc/pr_6290.prdoc
  substrate/frame/indices/src/benchmarking.rs
  substrate/frame/transaction-storage/src/benchmarking.rs
Labels: R0-silent

#6417 fix prospective-parachains best backable chain reversion bug
  polkadot/node/core/prospective-parachains/src/fragment_chain/mod.rs
  polkadot/node/core/prospective-parachains/src/fragment_chain/tests.rs
  prdoc/pr_6417.prdoc
Labels: I2-bug, T8-polkadot, A4-needs-backport

#6400 Remove network starter that is no longer needed
  cumulus/client/relay-chain-minimal-node/src/lib.rs
  cumulus/client/relay-chain-minimal-node/src/network.rs
  cumulus/client/service/src/lib.rs
  cumulus/polkadot-omni-node/lib/src/common/spec.rs
  cumulus/polkadot-omni-node/lib/src/nodes/manual_seal.rs
  cumulus/test/service/src/lib.rs
  polkadot/node/service/src/lib.rs
  prdoc/pr_6400.prdoc
  substrate/bin/node/cli/src/service.rs
  substrate/client/service/src/builder.rs
  substrate/client/service/src/lib.rs
  templates/minimal/node/src/service.rs
  templates/parachain/node/src/service.rs
  templates/solochain/node/src/service.rs
Labels: T0-node

#6262 `fatxpool`: size limits implemented
  prdoc/pr_6262.prdoc
  substrate/client/transaction-pool/src/fork_aware_txpool/dropped_watcher.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/tx_mem_pool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs
  substrate/client/transaction-pool/src/graph/mod.rs
  substrate/client/transaction-pool/src/graph/tracked_map.rs
  substrate/client/transaction-pool/tests/fatp_common/mod.rs
  substrate/client/transaction-pool/tests/fatp_limits.rs
Labels: R0-silent, T0-node

#6439 pallet-membership: Do not verify the `MembershipChanged` in bechmarks
  prdoc/pr_6439.prdoc
  substrate/frame/membership/src/benchmarking.rs
Labels: T2-pallets

#5363 add FeeManager to pallet xcm
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  prdoc/pr_5363.prdoc
Labels: T6-XCM

#5656 Use relay chain block number in the broker pallet instead of block number
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  prdoc/pr_5656.prdoc
  substrate/frame/broker/src/benchmarking.rs
  substrate/frame/broker/src/dispatchable_impls.rs
  substrate/frame/broker/src/lib.rs
  substrate/frame/broker/src/migration.rs
  substrate/frame/broker/src/tick_impls.rs
  substrate/frame/broker/src/types.rs
  substrate/frame/broker/src/utility_impls.rs
Labels: T2-pallets

#6301 migrate pallet-nft-fractionalization to benchmarking v2 syntax
  prdoc/pr_6301.prdoc
  substrate/frame/nft-fractionalization/src/benchmarking.rs
Labels: T2-pallets

#6393 [pallet-revive] adjust fee dry-run calculation
  Cargo.lock
  Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_6393.prdoc
  substrate/bin/node/cli/src/chain_spec.rs
  substrate/frame/revive/fixtures/build.rs
  substrate/frame/revive/fixtures/contracts/rpc_demo.rs
  substrate/frame/revive/rpc/Cargo.toml
  substrate/frame/revive/rpc/examples/README.md
  substrate/frame/revive/rpc/examples/bun.lockb
  substrate/frame/revive/rpc/examples/js/.prettierrc.json
  substrate/frame/revive/rpc/examples/js/contracts/Event.sol
  substrate/frame/revive/rpc/examples/js/contracts/Revert.sol
  substrate/frame/revive/rpc/examples/js/evm-contracts.json
  substrate/frame/revive/rpc/examples/js/index.html
  substrate/frame/revive/rpc/examples/js/package-lock.json
  substrate/frame/revive/rpc/examples/js/package.json
  substrate/frame/revive/rpc/examples/js/pvm-contracts.json
  substrate/frame/revive/rpc/examples/js/src/build-contracts.ts
  substrate/frame/revive/rpc/examples/js/src/event.ts
  substrate/frame/revive/rpc/examples/js/src/lib.ts
  substrate/frame/revive/rpc/examples/js/src/main.ts
  substrate/frame/revive/rpc/examples/js/src/revert.ts
  substrate/frame/revive/rpc/examples/js/src/script.ts
  substrate/frame/revive/rpc/examples/js/src/solc.d.ts
  substrate/frame/revive/rpc/examples/js/src/web.ts
  substrate/frame/revive/rpc/examples/package.json
  substrate/frame/revive/rpc/examples/rust/deploy.rs
  substrate/frame/revive/rpc/examples/rust/transfer.rs
  substrate/frame/revive/rpc/revive_chain.metadata
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/rpc/src/example.rs
  substrate/frame/revive/rpc/src/lib.rs
  substrate/frame/revive/rpc/src/subxt_client.rs
  substrate/frame/revive/rpc/src/tests.rs
  substrate/frame/revive/src/evm/api/account.rs
  substrate/frame/revive/src/evm/api/rpc_types.rs
  substrate/frame/revive/src/evm/runtime.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/primitives.rs
Labels: R0-silent, T7-smart_contracts

#6310 Migrate pallet-child-bounties benchmark to v2
  prdoc/pr_6310.prdoc
  substrate/frame/child-bounties/src/benchmarking.rs
Labels: T2-pallets, T12-benchmarks

#6425 Introduce `ConstUint` to make dependent types in `DefaultConfig` more adaptable
  Cargo.lock
  Cargo.toml
  prdoc/pr_6425.prdoc
  substrate/frame/assets/src/lib.rs
  substrate/frame/balances/src/lib.rs
  substrate/frame/support/src/lib.rs
  substrate/frame/support/src/traits.rs
  substrate/frame/support/src/traits/misc.rs
  substrate/frame/system/src/lib.rs
  substrate/frame/timestamp/src/lib.rs
  substrate/primitives/core/src/lib.rs
  substrate/primitives/runtime/src/traits/mod.rs
Labels: T17-primitives

#6431 Use type alias for transactions
  substrate/client/network/transactions/src/lib.rs
Labels: R0-silent

#6444 [Release|CI/CD] Fix audiences changelog template
  .github/workflows/release-30_publish_release_draft.yml
  scripts/release/templates/audience.md.tera
Labels: R0-silent, A4-needs-backport

#6454 rpc server: fix host filter for localhost on ipv6
  prdoc/pr_6454.prdoc
  substrate/client/rpc-servers/src/utils.rs
Labels: T0-node, A4-needs-backport

#6453 [pallet-revive] eth-rpc fixes
  .config/nextest.toml
  Cargo.lock
  prdoc/pr_6453.prdoc
  substrate/frame/revive/rpc/Cargo.toml
  substrate/frame/revive/rpc/examples/js/src/lib.ts
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/rpc/src/lib.rs
  substrate/frame/revive/rpc/src/tests.rs
Labels: R0-silent, T7-smart_contracts

#6440 Remove debug message about pruning active leaves
  polkadot/node/core/pvf/src/execute/queue.rs
  prdoc/pr_6440.prdoc
Labels: R0-silent, T8-polkadot

#6184 remove pallet::getter from pallet-staking
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_6184.prdoc
  substrate/frame/babe/src/mock.rs
  substrate/frame/babe/src/tests.rs
  substrate/frame/beefy/src/mock.rs
  substrate/frame/beefy/src/tests.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/lib.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
  substrate/frame/grandpa/src/mock.rs
  substrate/frame/grandpa/src/tests.rs
  substrate/frame/nomination-pools/test-delegate-stake/src/lib.rs
  substrate/frame/nomination-pools/test-transfer-stake/src/lib.rs
  substrate/frame/root-offences/src/lib.rs
  substrate/frame/root-offences/src/mock.rs
  substrate/frame/staking/src/benchmarking.rs
  substrate/frame/staking/src/lib.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/testing_utils.rs
  substrate/frame/staking/src/tests.rs
Labels: T2-pallets

#6367 Refactor pallet `society`
  prdoc/pr_6367.prdoc
  substrate/frame/society/src/benchmarking.rs
  substrate/frame/society/src/lib.rs
Labels: T2-pallets, T12-benchmarks

#6284 backing: improve session buffering for runtime information
  polkadot/node/core/backing/src/error.rs
  polkadot/node/core/backing/src/lib.rs
  polkadot/node/core/backing/src/tests/mod.rs
  polkadot/node/core/backing/src/tests/prospective_parachains.rs
  prdoc/pr_6284.prdoc
Labels: T0-node, I9-optimisation, T4-runtime_API, T8-polkadot, C2-good-first-issue

#6465 Fixed bridges zombienet tests because of removed NetworkId::Rococo/Westend from xcm::v5
  bridges/testing/environments/rococo-westend/bridges_rococo_westend.sh
  bridges/testing/framework/js-helpers/wrapped-assets-balance.js
  bridges/testing/framework/utils/bridges.sh
  bridges/testing/tests/0001-asset-transfer/roc-reaches-westend.zndsl
  bridges/testing/tests/0001-asset-transfer/wnd-reaches-rococo.zndsl
Labels: R0-silent, T15-bridges

#6463 Fix staking benchmark
  prdoc/pr_6463.prdoc
  substrate/frame/staking/src/benchmarking.rs
Labels: T2-pallets, T12-benchmarks

#6359 feat: add workflow to test readme generation
  .github/scripts/check-missing-readme-generation.sh
  .github/workflows/checks-quick.yml
Labels: R0-silent

#6460 [pallet-revive] set logs_bloom
  prdoc/pr_6460.prdoc
  substrate/frame/revive/rpc/examples/js/src/lib.ts
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/src/evm/api.rs
  substrate/frame/revive/src/evm/api/rpc_types.rs
  substrate/frame/revive/src/evm/api/rpc_types_gen.rs
Labels: R0-silent, T7-smart_contracts

#6411 Support more types in TypeWithDefault
  prdoc/pr_6411.prdoc
  substrate/primitives/runtime/src/type_with_default.rs
Labels: T17-primitives

#6484 network/litep2p: Update litep2p network backend to version 0.8.1
  Cargo.lock
  Cargo.toml
  prdoc/pr_6484.prdoc
  substrate/client/network/src/litep2p/mod.rs
Labels: T0-node, I5-enhancement, A4-needs-backport

#6486 sp-trie: minor fix to avoid possible panic during node decoding
  prdoc/pr_6486.prdoc
  substrate/primitives/trie/src/node_codec.rs
Labels: T17-primitives

#6302 migrate pallet-nomination-pool-benchmarking to benchmarking syntax v2
  prdoc/pr_6302.prdoc
  substrate/frame/nomination-pools/benchmarking/src/inner.rs
Labels: T2-pallets, T12-benchmarks

#6490 Mention that account might still be required in doc for feeless if.
  substrate/frame/support/src/lib.rs
Labels: R0-silent

#4551 [WIP][ci] Add worfklow stopper
  .github/actions/workflow-stopper/action.yml
  .github/workflows/build-misc.yml
  .github/workflows/check-frame-omni-bencher.yml
  .github/workflows/check-runtime-migration.yml
  .github/workflows/checks-quick.yml
  .github/workflows/checks.yml
  .github/workflows/docs.yml
  .github/workflows/tests-linux-stable.yml
Labels: R0-silent

#6215 Remove `ProspectiveParachainsMode` usage in backing subsystem
  polkadot/node/core/backing/src/lib.rs
  polkadot/node/core/backing/src/tests/mod.rs
  polkadot/node/core/backing/src/tests/prospective_parachains.rs
  polkadot/node/subsystem-util/src/backing_implicit_view.rs
  polkadot/roadmap/implementers-guide/src/node/utility/provisioner.md
  polkadot/roadmap/implementers-guide/src/types/overseer-protocol.md
  polkadot/statement-table/src/generic.rs
  polkadot/statement-table/src/lib.rs
  prdoc/pr_6215.prdoc
Labels: T8-polkadot

#6526 sp-runtime: Be a little bit more functional :D
  prdoc/pr_6526.prdoc
  substrate/primitives/runtime/src/generic/digest.rs
Labels: A4-needs-backport, T17-primitives

#6470 Backport #6304 to stable2412
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/claim_assets.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  polkadot/runtime/rococo/src/weights/pallet_xcm_benchmarks_generic.rs
  polkadot/runtime/rococo/src/weights/xcm/mod.rs
  polkadot/runtime/rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  polkadot/runtime/westend/src/weights/xcm/mod.rs
  polkadot/runtime/westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  polkadot/xcm/src/v4/mod.rs
  polkadot/xcm/src/v5/mod.rs
  polkadot/xcm/xcm-builder/src/weight.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  polkadot/xcm/xcm-executor/src/tests/execute_with_origin.rs
  polkadot/xcm/xcm-executor/src/tests/mod.rs
  prdoc/pr_6470.prdoc
Labels: T6-XCM

#6473 backport #6323 to stable2412: add transaction source in transaction extension API.
  bridges/bin/runtime-common/src/extensions.rs
  bridges/modules/relayers/src/extension/mod.rs
  polkadot/runtime/common/src/claims.rs
  prdoc/pr_6473.prdoc
  substrate/frame/examples/authorization-tx-extension/src/extensions.rs
  substrate/frame/examples/basic/src/lib.rs
  substrate/frame/examples/basic/src/tests.rs
  substrate/frame/sudo/src/extension.rs
  substrate/frame/system/src/extensions/check_mortality.rs
  substrate/frame/system/src/extensions/check_non_zero_sender.rs
  substrate/frame/system/src/extensions/check_nonce.rs
  substrate/frame/system/src/extensions/check_weight.rs
  substrate/frame/transaction-payment/asset-conversion-tx-payment/src/lib.rs
  substrate/frame/transaction-payment/asset-tx-payment/src/lib.rs
  substrate/frame/transaction-payment/skip-feeless-payment/src/lib.rs
  substrate/frame/transaction-payment/skip-feeless-payment/src/mock.rs
  substrate/frame/transaction-payment/skip-feeless-payment/src/tests.rs
  substrate/frame/transaction-payment/src/lib.rs
  substrate/frame/transaction-payment/src/tests.rs
  substrate/frame/verify-signature/src/benchmarking.rs
  substrate/frame/verify-signature/src/extension.rs
  substrate/frame/verify-signature/src/tests.rs
  substrate/primitives/runtime/src/generic/checked_extrinsic.rs
  substrate/primitives/runtime/src/traits/transaction_extension/as_transaction_extension.rs
  substrate/primitives/runtime/src/traits/transaction_extension/dispatch_transaction.rs
  substrate/primitives/runtime/src/traits/transaction_extension/mod.rs
  substrate/test-utils/runtime/src/lib.rs
Labels: A3-backport

#6527 backport: Update litep2p network backend to version 0.8.1 for stable2412
  Cargo.lock
  Cargo.toml
  prdoc/pr_6527.prdoc
  substrate/client/network/src/litep2p/mod.rs
Labels: A3-backport

#6528 `TransactionPool` API uses `async_trait`
  Cargo.lock
  prdoc/pr_6528.prdoc
  substrate/bin/node/bench/Cargo.toml
  substrate/bin/node/bench/src/construct.rs
  substrate/client/rpc-spec-v2/Cargo.toml
  substrate/client/rpc-spec-v2/src/transaction/tests/middleware_pool.rs
  substrate/client/rpc/src/author/mod.rs
  substrate/client/service/src/lib.rs
  substrate/client/transaction-pool/api/src/lib.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/mod.rs
  substrate/client/transaction-pool/src/lib.rs
  substrate/client/transaction-pool/src/single_state_txpool/single_state_txpool.rs
  substrate/client/transaction-pool/src/transaction_pool_wrapper.rs
Labels: R0-silent, T0-node

#6502 sp-trie: correctly avoid panicking when decoding bad compact proofs
  prdoc/pr_6502.prdoc
  substrate/primitives/trie/src/node_codec.rs
  substrate/primitives/trie/src/storage_proof.rs
Labels: T17-primitives

#6220 Fix metrics not shutting down if there are open connections
  prdoc/pr_6220.prdoc
  substrate/utils/prometheus/Cargo.toml
  substrate/utils/prometheus/src/lib.rs
Labels: T0-node

#6509 Migrate pallet-democracy benchmarks to benchmark v2 syntax
  prdoc/pr_6509.prdoc
  substrate/frame/democracy/src/benchmarking.rs
  substrate/frame/democracy/src/weights.rs
Labels: T1-FRAME

#6534 Forward logging directives to Polkadot workers
  Cargo.lock
  polkadot/node/core/pvf/Cargo.toml
  polkadot/node/core/pvf/src/worker_interface.rs
  prdoc/pr_6534.prdoc
  substrate/client/tracing/src/logging/directives.rs
Labels: T8-polkadot

#5703 Support block gap created by fast sync
  prdoc/pr_5703.prdoc
  substrate/client/db/src/lib.rs
Labels: T0-node

#6521 Pure state sync refactoring (part-2)
  prdoc/pr_6521.prdoc
  substrate/client/network/sync/src/strategy/state_sync.rs
Labels: T0-node

#6544 Add and test events in `pallet-conviction-voting`
  prdoc/pr_6544.prdoc
  substrate/frame/conviction-voting/src/lib.rs
  substrate/frame/conviction-voting/src/tests.rs
  substrate/frame/conviction-voting/src/types.rs
Labels: I4-refactor, T2-pallets, T10-tests, T14-system_parachains

#6546 Increase default trie cache size to 1GiB
  prdoc/pr_6546.prdoc
  substrate/client/cli/src/params/import_params.rs
Labels: T0-node

#6536 Bridges testing improvements
  bridges/bin/runtime-common/src/integrity.rs
  bridges/bin/runtime-common/src/mock.rs
  bridges/modules/relayers/src/lib.rs
  bridges/modules/relayers/src/mock.rs
  bridges/modules/relayers/src/payment_adapter.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_bulletin_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_westend_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/bridge_to_rococo_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/helpers.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/mod.rs
  cumulus/parachains/runtimes/test-utils/src/lib.rs
  prdoc/pr_6536.prdoc
Labels: T15-bridges, A4-needs-backport

#6292 Migrate pallet-scheduler benchmark to v2
  substrate/frame/scheduler/src/benchmarking.rs
Labels: R0-silent, T2-pallets

#6522 Removes constraint in `BlockNumberProvider` from treasury
  prdoc/pr_6522.prdoc
  substrate/frame/bounties/src/benchmarking.rs
  substrate/frame/bounties/src/lib.rs
  substrate/frame/child-bounties/src/benchmarking.rs
  substrate/frame/child-bounties/src/lib.rs
  substrate/frame/treasury/src/benchmarking.rs
  substrate/frame/treasury/src/lib.rs
  substrate/primitives/runtime/src/traits/mod.rs
Labels: T2-pallets

#6567 revive: Bump connect timeout to fix flaky tests
  .config/nextest.toml
  substrate/.config/nextest.toml
  substrate/frame/revive/rpc/src/tests.rs
Labels: R0-silent

#6553 network-gossip: Ensure sync event is processed on unknown peer roles
  prdoc/pr_6553.prdoc
  substrate/client/network-gossip/src/bridge.rs
  substrate/client/network/sync/src/engine.rs
Labels: T0-node, I2-bug

#6561 slot-based-collator: Move spawning of the futures
  cumulus/client/consensus/aura/src/collators/slot_based/mod.rs
  cumulus/polkadot-omni-node/lib/src/nodes/aura.rs
  cumulus/test/service/src/lib.rs
  prdoc/pr_6561.prdoc
Labels: T9-cumulus

#6540 [Fix|NominationPools] Only allow apply slash to be executed if the slash amount is atleast ED
  prdoc/pr_6540.prdoc
  substrate/frame/nomination-pools/runtime-api/src/lib.rs
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/nomination-pools/test-delegate-stake/Cargo.toml
  substrate/frame/nomination-pools/test-delegate-stake/src/lib.rs
Labels: T2-pallets, A4-needs-backport

#6560 parachain-template-node: add properties for dev chain-spec
  templates/parachain/node/src/chain_spec.rs
Labels: R0-silent

#6554 Only mess with coretime if we are registering an actual parachain.
  polkadot/runtime/common/src/paras_sudo_wrapper.rs
Labels: R0-silent, T2-pallets

#6605 Notify telemetry only every second about the tx pool status
  Cargo.lock
  cumulus/client/service/Cargo.toml
  prdoc/pr_6605.prdoc
  substrate/client/service/src/builder.rs
Labels: T0-node

#6410 Fixes cfg attributes in runtime macro
  substrate/frame/support/procedural/src/runtime/parse/pallet.rs
  substrate/frame/support/test/tests/pallet.rs
Labels: R0-silent, T1-FRAME

#6579 Error logging for send xcm to pallet-xcm
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/xcm-builder/src/process_xcm_message.rs
Labels: R0-silent, T6-XCM, A4-needs-backport

#6632 ci: improve workflow-stopper ux
  .github/workflows/build-misc.yml
  .github/workflows/check-frame-omni-bencher.yml
  .github/workflows/checks-quick.yml
  .github/workflows/checks.yml
  .github/workflows/docs.yml
  .github/workflows/tests-linux-stable.yml
Labels: R0-silent

#6628 remove ReportCollator message
  polkadot/node/network/collator-protocol/src/collator_side/mod.rs
  polkadot/node/network/collator-protocol/src/validator_side/mod.rs
  polkadot/node/network/collator-protocol/src/validator_side/tests/mod.rs
  polkadot/node/subsystem-types/src/messages.rs
  polkadot/roadmap/implementers-guide/src/node/collators/collator-protocol.md
  polkadot/roadmap/implementers-guide/src/node/subsystems-and-jobs.md
  polkadot/roadmap/implementers-guide/src/types/overseer-protocol.md
  prdoc/pr_6628.prdoc
Labels: T8-polkadot

#6588 rpc server: fix subscription id_provider being reset to default one.
  prdoc/pr_6588.prdoc
  substrate/client/rpc-servers/src/lib.rs
Labels: T0-node, A3-backport

#6633 bump zombienet-sdk version `v0.2.16`
  Cargo.lock
  Cargo.toml
Labels: R0-silent, T10-tests

#6535 ci/check-semver: Fix semver failed step
  .github/workflows/check-semver.yml
Labels: R0-silent, D0-easy

#6645 xcm: fix local/remote exports when inner routers return `NotApplicable`
  polkadot/grafana/README.md
  polkadot/grafana/parachains/status.json
  polkadot/xcm/src/v3/traits.rs
  polkadot/xcm/src/v4/traits.rs
  polkadot/xcm/src/v5/traits.rs
  polkadot/xcm/xcm-builder/src/universal_exports.rs
  polkadot/xcm/xcm-executor/src/traits/export.rs
  prdoc/pr_6645.prdoc
  substrate/frame/examples/default-config/src/lib.rs
Labels: R0-silent, T6-XCM, T15-bridges, A4-needs-backport

#6506 Zero refund check for FungibleAdapter
  prdoc/pr_6506.prdoc
  substrate/frame/transaction-payment/src/payment.rs
  substrate/frame/transaction-payment/src/tests.rs
Labels: T2-pallets, A4-needs-backport

#6562 Hide nonce implementation details in metadata
  prdoc/pr_6562.prdoc
  substrate/primitives/runtime/src/type_with_default.rs
Labels: T1-FRAME

#6459 Fix `XcmPaymentApi::query_weight_to_asset_fee` version conversion
  Cargo.lock
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/assets/common/src/lib.rs
  cumulus/parachains/runtimes/assets/test-utils/Cargo.toml
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/Cargo.toml
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/tests/tests.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/tests/tests.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/tests/tests.rs
  cumulus/parachains/runtimes/people/people-rococo/Cargo.toml
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/tests/tests.rs
  cumulus/parachains/runtimes/people/people-westend/Cargo.toml
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/tests/tests.rs
  cumulus/parachains/runtimes/test-utils/Cargo.toml
  cumulus/parachains/runtimes/test-utils/src/test_cases.rs
  polkadot/xcm/xcm-runtime-apis/tests/fee_estimation.rs
  polkadot/xcm/xcm-runtime-apis/tests/mock.rs
  prdoc/pr_6459.prdoc
Labels: T6-XCM, T9-cumulus, A4-needs-backport

#6649 [stable2412] Backport #6465 #6536 #6579
  bridges/bin/runtime-common/src/integrity.rs
  bridges/bin/runtime-common/src/mock.rs
  bridges/modules/relayers/src/lib.rs
  bridges/modules/relayers/src/mock.rs
  bridges/modules/relayers/src/payment_adapter.rs
  bridges/testing/environments/rococo-westend/bridges_rococo_westend.sh
  bridges/testing/framework/js-helpers/wrapped-assets-balance.js
  bridges/testing/framework/utils/bridges.sh
  bridges/testing/tests/0001-asset-transfer/roc-reaches-westend.zndsl
  bridges/testing/tests/0001-asset-transfer/wnd-reaches-rococo.zndsl
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_bulletin_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_westend_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/bridge_to_rococo_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/helpers.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/mod.rs
  cumulus/parachains/runtimes/test-utils/src/lib.rs
  polkadot/grafana/README.md
  polkadot/grafana/parachains/status.json
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/src/v3/traits.rs
  polkadot/xcm/src/v4/traits.rs
  polkadot/xcm/src/v5/traits.rs
  polkadot/xcm/xcm-builder/src/process_xcm_message.rs
  polkadot/xcm/xcm-builder/src/universal_exports.rs
  polkadot/xcm/xcm-executor/src/traits/export.rs
  prdoc/pr_6536.prdoc
  prdoc/pr_6645.prdoc
  substrate/frame/examples/default-config/src/lib.rs
Labels: T6-XCM, T15-bridges

#6666 Add stable2412 to target_branches for command-backport.yml
  .github/workflows/command-backport.yml
Labels: R0-silent

#6603 litep2p/req-resp: Always provide main protocol name in responses
  prdoc/pr_6603.prdoc
  substrate/client/network/src/litep2p/shim/request_response/mod.rs
Labels: T0-node, A4-needs-backport

#5732 v16: Expose the unstable metadata v16
  Cargo.lock
  Cargo.toml
  prdoc/pr_5732.prdoc
  substrate/frame/metadata-hash-extension/Cargo.toml
  substrate/frame/revive/src/evm/runtime.rs
  substrate/frame/support/Cargo.toml
  substrate/frame/support/procedural/src/construct_runtime/expand/metadata.rs
  substrate/frame/support/test/Cargo.toml
  substrate/frame/support/test/tests/pallet.rs
  substrate/primitives/metadata-ir/Cargo.toml
  substrate/primitives/metadata-ir/src/lib.rs
  substrate/primitives/metadata-ir/src/types.rs
  substrate/primitives/metadata-ir/src/unstable.rs
  substrate/primitives/metadata-ir/src/v14.rs
  substrate/primitives/metadata-ir/src/v15.rs
  substrate/primitives/runtime/src/generic/unchecked_extrinsic.rs
  substrate/primitives/runtime/src/traits/mod.rs
  substrate/utils/frame/benchmarking-cli/src/overhead/remark_builder.rs
  substrate/utils/frame/benchmarking-cli/src/overhead/runtime_utilities.rs
  substrate/utils/wasm-builder/Cargo.toml
Labels: I5-enhancement, T1-FRAME

#6676 Backport/2412: Expose the unstable metadata v16
  Cargo.lock
  Cargo.toml
  prdoc/pr_5732.prdoc
  prdoc/pr_6676.prdoc
  substrate/frame/metadata-hash-extension/Cargo.toml
  substrate/frame/revive/src/evm/runtime.rs
  substrate/frame/support/Cargo.toml
  substrate/frame/support/procedural/src/construct_runtime/expand/metadata.rs
  substrate/frame/support/test/Cargo.toml
  substrate/frame/support/test/tests/pallet.rs
  substrate/primitives/metadata-ir/Cargo.toml
  substrate/primitives/metadata-ir/src/lib.rs
  substrate/primitives/metadata-ir/src/types.rs
  substrate/primitives/metadata-ir/src/unstable.rs
  substrate/primitives/metadata-ir/src/v14.rs
  substrate/primitives/metadata-ir/src/v15.rs
  substrate/primitives/runtime/src/generic/unchecked_extrinsic.rs
  substrate/primitives/runtime/src/traits/mod.rs
  substrate/utils/frame/benchmarking-cli/src/overhead/remark_builder.rs
  substrate/utils/frame/benchmarking-cli/src/overhead/runtime_utilities.rs
  substrate/utils/wasm-builder/Cargo.toml
Labels: A3-backport

#5997 rpc-v2: Implement `archive_unstable_storageDiff`
  Cargo.lock
  prdoc/pr_5997.prdoc
  substrate/client/rpc-spec-v2/Cargo.toml
  substrate/client/rpc-spec-v2/src/archive/api.rs
  substrate/client/rpc-spec-v2/src/archive/archive.rs
  substrate/client/rpc-spec-v2/src/archive/archive_storage.rs
  substrate/client/rpc-spec-v2/src/archive/tests.rs
  substrate/client/rpc-spec-v2/src/common/events.rs
  substrate/client/rpc-spec-v2/src/common/storage.rs
  substrate/client/service/src/builder.rs
Labels: I5-enhancement, T3-RPC_API, D1-medium

#6677 chore: Update litep2p to v0.8.2
  Cargo.lock
  Cargo.toml
  prdoc/pr_6677.prdoc
  substrate/client/network/src/litep2p/mod.rs
Labels: T0-node, I9-optimisation, I5-enhancement, A4-needs-backport

#6684 Multiple instances for pallet-bridge-relayers fix
  bridges/modules/relayers/src/extension/mod.rs
Labels: R0-silent, T15-bridges, A4-needs-backport

#6617 Migrating pallet-state-trie-migration to benchmarking V2
  substrate/frame/state-trie-migration/src/lib.rs
Labels: R0-silent, T2-pallets, T12-benchmarks

#6695 [pallet-revive] bugfix decoding 64bit args in the decoder
  prdoc/pr_6695.prdoc
  substrate/frame/revive/proc-macro/src/lib.rs
Labels: R0-silent, T7-smart_contracts

#5855 Expose types from `sc-service`
  prdoc/pr_5855.prdoc
  substrate/bin/node/testing/Cargo.toml
  substrate/client/network/test/Cargo.toml
  substrate/client/rpc-spec-v2/Cargo.toml
  substrate/client/rpc-spec-v2/src/chain_head/subscription/inner.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
  substrate/client/service/Cargo.toml
  substrate/client/service/src/client/client.rs
  substrate/client/service/src/client/mod.rs
  substrate/client/service/src/lib.rs
  substrate/client/service/test/Cargo.toml
  substrate/client/service/test/src/client/mod.rs
  substrate/test-utils/client/Cargo.toml
  substrate/test-utils/runtime/Cargo.toml
Labels: T0-node

#6691 ci: update nightly in ci-unified to 2024-11-19
  .github/env
  .gitlab-ci.yml
  docs/contributor/container.md
Labels: R0-silent

#6277 Migrate pallet-preimage to benchmark v2
  substrate/frame/preimage/src/benchmarking.rs
  substrate/frame/preimage/src/weights.rs
Labels: R0-silent, T2-pallets, T12-benchmarks

#6565 pallet_revive: Switch to 64bit RISC-V
  .github/workflows/checks-quick.yml
  Cargo.lock
  prdoc/pr_6565.prdoc
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/fixtures/Cargo.toml
  substrate/frame/revive/fixtures/build.rs
  substrate/frame/revive/fixtures/build/_Cargo.toml
  substrate/frame/revive/fixtures/build/_rust-toolchain.toml
  substrate/frame/revive/fixtures/riscv32emac-unknown-none-polkavm.json
  substrate/frame/revive/fixtures/src/lib.rs
  substrate/frame/revive/proc-macro/src/lib.rs
  substrate/frame/revive/rpc/src/tests.rs
  substrate/frame/revive/src/chain_extension.rs
  substrate/frame/revive/src/limits.rs
  substrate/frame/revive/src/wasm/mod.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/uapi/Cargo.toml
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv64.rs
  substrate/frame/revive/uapi/src/lib.rs
Labels: T2-pallets

#6665 Fix runtime api impl detection by construct runtime
  Cargo.lock
  prdoc/pr_6665.prdoc
  substrate/frame/support/procedural/src/construct_runtime/expand/metadata.rs
  substrate/frame/support/procedural/src/construct_runtime/mod.rs
  substrate/frame/support/test/tests/runtime_metadata.rs
  substrate/primitives/api/proc-macro/src/runtime_metadata.rs
  substrate/primitives/api/test/Cargo.toml
  substrate/primitives/api/test/tests/decl_and_impl.rs
  substrate/primitives/metadata-ir/src/lib.rs
Labels: T1-FRAME

#6483 archive: Refactor `archive_storage` method into subscription
  substrate/client/rpc-spec-v2/src/archive/api.rs
  substrate/client/rpc-spec-v2/src/archive/archive.rs
  substrate/client/rpc-spec-v2/src/archive/archive_storage.rs
  substrate/client/rpc-spec-v2/src/archive/mod.rs
  substrate/client/rpc-spec-v2/src/archive/tests.rs
  substrate/client/rpc-spec-v2/src/chain_head/event.rs
  substrate/client/rpc-spec-v2/src/common/events.rs
  substrate/client/rpc-spec-v2/src/common/storage.rs
  substrate/client/service/src/builder.rs
Labels: R0-silent, I4-refactor, I5-enhancement

#6681 Update scale-info to 2.11.6
  Cargo.lock
  Cargo.toml
  prdoc/pr_6681.prdoc
Labels: R0-silent

#6377 People chain integration tests
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/governance.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/mod.rs
Labels: R0-silent, T10-tests, T14-system_parachains

#6703 network/libp2p-backend: Suppress warning adding already reserved node as reserved
  prdoc/pr_6703.prdoc
  substrate/client/network/src/protocol_controller.rs
Labels: R0-silent, T0-node, D0-easy

#6662 Let's be a bit less strict here.
  polkadot/node/network/collator-protocol/src/error.rs
Labels: R0-silent, T0-node
