Repository paritytech/polkadot-sdk, pull requests merged in 2024-07, with the labels that each got.

#4840 Remove getters from pallet-membership
  prdoc/pr_4840.prdoc
  substrate/frame/membership/src/lib.rs
Labels: T2-pallets

#4918 prdoc upgrade
  .github/workflows/check-prdoc.yml
Labels: R0-silent

#4806 Pallet Name Customisation
  templates/minimal/README.md
Labels: R0-silent

#4908 Update `PULL_REQUEST_TEMPLATE` and `CONTRIBUTING` docs.
  docs/contributor/CONTRIBUTING.md
  docs/contributor/PULL_REQUEST_TEMPLATE.md
  templates/minimal/README.md
Labels: R0-silent

#4870 bridge tests: send bridged assets from random parachain to bridged asset hub
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/people/people-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/people/people-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/testing/penpal/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/relays/rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/relays/westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/hybrid_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/swap.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/treasury.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/fellowship_treasury.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/swap.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/treasury.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/src/tests/fellowship_treasury.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/people/people-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-rococo/src/tests/reap_identity.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-rococo/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/reap_identity.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/teleport.rs
Labels: R0-silent

#4929 litep2p: Increment random walk metrics
  substrate/client/network/src/litep2p/discovery.rs
  substrate/client/network/src/litep2p/mod.rs
Labels: A1-insubstantial, R0-silent, D0-easy

#4932 `polkadot-parachain`: Unify asset-hub authoring codepath with general AURA
  cumulus/polkadot-parachain/src/command.rs
  cumulus/polkadot-parachain/src/service.rs
  prdoc/pr_4932.prdoc
Labels: T0-node

#3899 approval-voting: Make tests deterministic
  polkadot/node/subsystem-bench/examples/approvals_no_shows.yaml
  polkadot/node/subsystem-bench/examples/approvals_throughput.yaml
  polkadot/node/subsystem-bench/examples/approvals_throughput_best_case.yaml
  polkadot/node/subsystem-bench/examples/approvals_throughput_no_optimisations_enabled.yaml
  polkadot/node/subsystem-bench/src/lib/approval/mod.rs
Labels: R0-silent

#4522 [BEEFY] Add runtime support for reporting fork voting
  polkadot/node/service/src/fake_runtime_api.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_4522.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/client/consensus/beefy/src/fisherman.rs
  substrate/client/consensus/beefy/src/tests.rs
  substrate/client/consensus/beefy/src/worker.rs
  substrate/frame/beefy-mmr/src/lib.rs
  substrate/frame/beefy-mmr/src/mock.rs
  substrate/frame/beefy-mmr/src/tests.rs
  substrate/frame/beefy/src/default_weights.rs
  substrate/frame/beefy/src/equivocation.rs
  substrate/frame/beefy/src/lib.rs
  substrate/frame/beefy/src/mock.rs
  substrate/frame/beefy/src/tests.rs
  substrate/frame/merkle-mountain-range/src/lib.rs
  substrate/frame/merkle-mountain-range/src/mmr/mmr.rs
  substrate/frame/merkle-mountain-range/src/mmr/mod.rs
  substrate/frame/merkle-mountain-range/src/mmr/storage.rs
  substrate/frame/merkle-mountain-range/src/tests.rs
  substrate/primitives/consensus/beefy/src/lib.rs
  substrate/primitives/consensus/beefy/src/payload.rs
  substrate/primitives/consensus/beefy/src/test_utils.rs
Labels: T15-bridges

#4904 [Staking] Delegators can stake but stakers can't delegate
  substrate/frame/delegated-staking/src/lib.rs
  substrate/frame/delegated-staking/src/tests.rs
Labels: R0-silent, T2-pallets

#4871 Remove pallet::getter usage from all pallet-tips
  prdoc/pr_4871.prdoc
  substrate/frame/tips/src/lib.rs
Labels: R0-silent

#4921 rename the candidate backing message from `GetBackedCandidates` to `GetBackableCandidates`
  polkadot/node/core/backing/src/lib.rs
  polkadot/node/core/backing/src/tests/mod.rs
  polkadot/node/core/provisioner/src/lib.rs
  polkadot/node/core/provisioner/src/tests.rs
  polkadot/node/overseer/src/tests.rs
  polkadot/node/subsystem-types/src/messages.rs
Labels: R0-silent

#4839 Remove getter macro from pallet-insecure-randomness-collective-flip
  prdoc/pr_4839.prdoc
  substrate/frame/insecure-randomness-collective-flip/README.md
  substrate/frame/insecure-randomness-collective-flip/src/lib.rs
Labels: T2-pallets

#4097 Introduce basic slot-based collator
  .gitlab/pipeline/zombienet/cumulus.yml
  Cargo.lock
  cumulus/client/consensus/aura/Cargo.toml
  cumulus/client/consensus/aura/src/collator.rs
  cumulus/client/consensus/aura/src/collators/basic.rs
  cumulus/client/consensus/aura/src/collators/lookahead.rs
  cumulus/client/consensus/aura/src/collators/mod.rs
  cumulus/client/consensus/aura/src/collators/slot_based/block_builder_task.rs
  cumulus/client/consensus/aura/src/collators/slot_based/collation_task.rs
  cumulus/client/consensus/aura/src/collators/slot_based/mod.rs
  cumulus/client/consensus/common/src/lib.rs
  cumulus/client/consensus/common/src/parachain_consensus.rs
  cumulus/client/consensus/common/src/parent_search.rs
  cumulus/client/consensus/common/src/tests.rs
  cumulus/client/network/src/tests.rs
  cumulus/client/parachain-inherent/Cargo.toml
  cumulus/client/pov-recovery/src/tests.rs
  cumulus/client/relay-chain-inprocess-interface/src/lib.rs
  cumulus/client/relay-chain-interface/src/lib.rs
  cumulus/client/relay-chain-minimal-node/Cargo.toml
  cumulus/client/relay-chain-rpc-interface/src/lib.rs
  cumulus/pallets/aura-ext/src/consensus_hook.rs
  cumulus/pallets/aura-ext/src/lib.rs
  cumulus/polkadot-parachain/Cargo.toml
  cumulus/polkadot-parachain/src/cli.rs
  cumulus/polkadot-parachain/src/command.rs
  cumulus/polkadot-parachain/src/service.rs
  cumulus/test/client/src/lib.rs
  cumulus/test/runtime/Cargo.toml
  cumulus/test/runtime/build.rs
  cumulus/test/runtime/src/lib.rs
  cumulus/test/service/Cargo.toml
  cumulus/test/service/src/chain_spec.rs
  cumulus/test/service/src/cli.rs
  cumulus/test/service/src/lib.rs
  cumulus/test/service/src/main.rs
  cumulus/zombienet/tests/0003-full_node_catching_up.zndsl
  cumulus/zombienet/tests/0006-rpc_collator_builds_blocks.zndsl
  cumulus/zombienet/tests/0008-elastic_authoring.toml
  cumulus/zombienet/tests/0008-elastic_authoring.zndsl
  cumulus/zombienet/tests/0009-elastic_pov_recovery.toml
  cumulus/zombienet/tests/0009-elastic_pov_recovery.zndsl
  cumulus/zombienet/tests/assign-core.js
  polkadot/zombienet_tests/elastic_scaling/0001-basic-3cores-6s-blocks.toml
  prdoc/pr_4097.prdoc
  substrate/client/basic-authorship/src/basic_authorship.rs
  substrate/client/consensus/aura/src/standalone.rs
  substrate/client/consensus/slots/src/lib.rs
  templates/parachain/node/src/service.rs
Labels: T0-node, T9-cumulus

#4950 [ci] Increase timeout for ci jobs
  .github/workflows/checks-quick.yml
  .github/workflows/command-bench-all.yml
  .github/workflows/command-bench-overhead.yml
  .github/workflows/command-bench.yml
  .github/workflows/command-fmt.yml
  .github/workflows/command-update-ui.yml
  .github/workflows/tests-linux-stable.yml
  .github/workflows/tests.yml
Labels: R0-silent

#4958 Stabilize elastic-scaling pov-recovery test
  cumulus/zombienet/tests/0002-pov_recovery.zndsl
  cumulus/zombienet/tests/0009-elastic_pov_recovery.toml
  cumulus/zombienet/tests/0009-elastic_pov_recovery.zndsl
Labels: R0-silent, T10-tests

#4902 remove getter from vesting pallet
  prdoc/pr_4902.prdoc
  substrate/frame/vesting/src/benchmarking.rs
  substrate/frame/vesting/src/lib.rs
  substrate/frame/vesting/src/tests.rs
Labels: T2-pallets

#4922 Optimize finalization performance
  Cargo.lock
  prdoc/pr_4922.prdoc
  substrate/client/api/src/backend.rs
  substrate/client/api/src/leaves.rs
  substrate/client/db/src/lib.rs
  substrate/primitives/blockchain/Cargo.toml
  substrate/primitives/blockchain/src/backend.rs
  substrate/primitives/blockchain/src/header_metadata.rs
Labels: T0-node

#4945 upgrade to macro_magic 0.5.1
  Cargo.lock
  Cargo.toml
Labels: R0-silent

#4943 Fix small typo in fungible token freeze docs
  prdoc/pr_4943.prdoc
  substrate/frame/support/src/traits/tokens/fungible/mod.rs
Labels: A1-insubstantial, T1-FRAME, T11-documentation

#4885 remove getter from transaction storage pallet
  prdoc/pr_4885.prdoc
  substrate/frame/transaction-storage/src/lib.rs
  substrate/frame/transaction-storage/src/tests.rs
Labels: T2-pallets

#4912 remove getter from babe pallet
  prdoc/pr_4912.prdoc
  substrate/frame/babe/src/lib.rs
  substrate/frame/babe/src/mock.rs
  substrate/frame/babe/src/tests.rs
Labels: T2-pallets

#3286 Assets: can_decrease/increase for destroying asset is not successful
  prdoc/pr_3286.prdoc
  substrate/frame/assets/src/functions.rs
  substrate/frame/assets/src/tests.rs
Labels: T2-pallets

#4955 [Backport] Version bumps and prdocs reordering from 1.14.0
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot/node/primitives/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/1.14.0/pr_1631.prdoc
  prdoc/1.14.0/pr_3374.prdoc
  prdoc/1.14.0/pr_3679.prdoc
  prdoc/1.14.0/pr_3820.prdoc
  prdoc/1.14.0/pr_3828.prdoc
  prdoc/1.14.0/pr_3843.prdoc
  prdoc/1.14.0/pr_3940.prdoc
  prdoc/1.14.0/pr_3951.prdoc
  prdoc/1.14.0/pr_4513.prdoc
  prdoc/1.14.0/pr_4596.prdoc
  prdoc/1.14.0/pr_4618.prdoc
  prdoc/1.14.0/pr_4662.prdoc
  prdoc/1.14.0/pr_4684.prdoc
  prdoc/1.14.0/pr_4685.prdoc
  prdoc/1.14.0/pr_4691.prdoc
  prdoc/1.14.0/pr_4710.prdoc
  prdoc/1.14.0/pr_4724.prdoc
  prdoc/1.14.0/pr_4728.prdoc
  prdoc/1.14.0/pr_4730.prdoc
  prdoc/1.14.0/pr_4733.prdoc
  prdoc/1.14.0/pr_4756.prdoc
  prdoc/1.14.0/pr_4757.prdoc
  prdoc/1.14.0/pr_4765.prdoc
  prdoc/1.14.0/pr_4769.prdoc
  prdoc/1.14.0/pr_4799.prdoc
  prdoc/1.14.0/pr_4802.prdoc
  prdoc/1.14.0/pr_4807.prdoc
  prdoc/1.14.0/pr_4823.prdoc
  prdoc/1.14.0/pr_4831.prdoc
  prdoc/1.14.0/pr_4833.prdoc
  prdoc/1.14.0/pr_4844.prdoc
  prdoc/1.14.0/pr_4857.prdoc
  prdoc/1.14.0/pr_4865.prdoc
  prdoc/1.14.0/pr_4877.prdoc
Labels: R0-silent, A3-backport, D0-easy

#4968 sp-core: Improve docs generated by `generate_feature_enabled_macro`
  substrate/primitives/core/src/lib.rs
Labels: R0-silent

#4863 Make `tracing::log` work in the runtime
  Cargo.lock
  prdoc/pr_4863.prdoc
  substrate/primitives/runtime/Cargo.toml
  substrate/primitives/runtime/src/runtime_logger.rs
  substrate/test-utils/runtime/Cargo.toml
  substrate/test-utils/runtime/src/lib.rs
Labels: T1-FRAME

#4971 litep2p/peerstore: Fix bump last updated time
  substrate/client/network/src/litep2p/peerstore.rs
Labels: A1-insubstantial, R0-silent, I2-bug, D0-easy

#4777 allow clear_origin in safe xcm builder
  polkadot/xcm/procedural/src/builder_pattern.rs
  polkadot/xcm/procedural/tests/builder_pattern.rs
  prdoc/pr_4777.prdoc
Labels: T6-XCM

#4980 Update Templates README docs
  templates/minimal/README.md
  templates/parachain/README.md
  templates/parachain/node/README.md
  templates/solochain/README.md
Labels: R0-silent

#4916 `polkadot-parachain` simplifications and deduplications
  cumulus/polkadot-parachain/src/cli.rs
  cumulus/polkadot-parachain/src/command.rs
  cumulus/polkadot-parachain/src/common/mod.rs
  cumulus/polkadot-parachain/src/rpc.rs
  cumulus/polkadot-parachain/src/service.rs
  polkadot/cli/src/command.rs
  substrate/client/cli/src/lib.rs
  substrate/client/service/src/lib.rs
Labels: R0-silent, T0-node

#4983 add notices to the implementer's guide docs that changed for elastic scaling
  polkadot/roadmap/implementers-guide/src/node/backing/candidate-backing.md
  polkadot/roadmap/implementers-guide/src/node/backing/prospective-parachains.md
  polkadot/roadmap/implementers-guide/src/node/collators/collator-protocol.md
  polkadot/roadmap/implementers-guide/src/node/utility/provisioner.md
  polkadot/roadmap/implementers-guide/src/runtime/inclusion.md
  polkadot/roadmap/implementers-guide/src/runtime/parainherent.md
Labels: R0-silent, T11-documentation

#4978 Add `MAX_INSTRUCTIONS_TO_DECODE` to XCMv2
  polkadot/xcm/src/v2/mod.rs
  prdoc/pr_4978.prdoc
Labels: T6-XCM

#4944 [bridges] Prune messages from confirmation tx body, not from the on_idle
  bridges/modules/messages/src/lib.rs
  bridges/modules/messages/src/outbound_lane.rs
  bridges/modules/messages/src/tests/pallet_tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_messages_rococo_to_rococo_bulletin.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_messages_rococo_to_westend.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_bridge_messages.rs
Labels: R0-silent, T15-bridges

#4886 Expose metadata-hash feature from polkadot crate
  Cargo.lock
  polkadot/Cargo.toml
  polkadot/cli/Cargo.toml
  polkadot/node/service/Cargo.toml
Labels: R0-silent

#4941 Explain usage of `<T: Config>` in FRAME storage + Update parachain pallet template
  Cargo.lock
  docs/sdk/src/polkadot_sdk/frame_runtime.rs
  docs/sdk/src/reference_docs/frame_storage_derives.rs
  docs/sdk/src/reference_docs/mod.rs
  substrate/frame/bags-list/src/list/tests.rs
  substrate/frame/nis/src/lib.rs
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/src/lib.rs
  substrate/frame/state-trie-migration/src/lib.rs
  substrate/frame/support/src/lib.rs
  templates/minimal/README.md
  templates/minimal/pallets/template/src/lib.rs
  templates/parachain/pallets/template/Cargo.toml
  templates/parachain/pallets/template/src/benchmarking.rs
  templates/parachain/pallets/template/src/lib.rs
  templates/parachain/pallets/template/src/tests.rs
Labels: R0-silent, T11-documentation

#5000 fixed cmd bot commenting not working
  .github/workflows/command-inform.yml
Labels: R0-silent

#5001 Remove usage of `sp-std` on templates
  Cargo.lock
  templates/parachain/pallets/template/Cargo.toml
  templates/parachain/runtime/Cargo.toml
  templates/parachain/runtime/src/apis.rs
  templates/parachain/runtime/src/lib.rs
  templates/solochain/runtime/Cargo.toml
  templates/solochain/runtime/src/lib.rs
Labels: R0-silent

#4996 xcm-executor: Improve logging
  Cargo.lock
  polkadot/xcm/xcm-executor/Cargo.toml
  polkadot/xcm/xcm-executor/src/lib.rs
  polkadot/xcm/xcm-executor/src/traits/conversion.rs
  polkadot/xcm/xcm-executor/src/traits/should_execute.rs
  polkadot/xcm/xcm-executor/src/traits/token_matching.rs
  polkadot/xcm/xcm-executor/src/traits/transact_asset.rs
  polkadot/xcm/xcm-executor/src/traits/weight.rs
  substrate/frame/support/src/traits/messages.rs
Labels: R0-silent

#4554 [statement-distribution] Add metrics for distributed statements in V2
  polkadot/node/network/statement-distribution/src/lib.rs
  polkadot/node/network/statement-distribution/src/metrics.rs
  polkadot/node/network/statement-distribution/src/v2/mod.rs
Labels: R0-silent, T0-node, T8-polkadot

#4563 Try State Hook for Bounties
  prdoc/pr_4563.prdoc
  substrate/frame/bounties/src/benchmarking.rs
  substrate/frame/bounties/src/lib.rs
  substrate/frame/bounties/src/tests.rs
Labels: R0-silent

#5002 network/tx: Ban peers with tx that fail to decode
  substrate/client/network/transactions/src/lib.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement, D0-easy

#5011 Use sp_runtime::traits::BadOrigin
  cumulus/parachains/pallets/collective-content/src/tests.rs
  polkadot/runtime/common/src/paras_registrar/mod.rs
  polkadot/runtime/parachains/src/assigner_on_demand/tests.rs
  polkadot/runtime/parachains/src/hrmp/tests.rs
  prdoc/pr_5011.prdoc
  substrate/frame/alliance/src/tests.rs
  substrate/frame/contracts/src/lib.rs
  substrate/frame/democracy/src/lib.rs
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/ranked-collective/src/tests.rs
  substrate/frame/utility/src/tests.rs
Labels: T2-pallets

#5017 Updated substrate-relay version for tests
  docker/dockerfiles/bridges_zombienet_tests_injected.Dockerfile
Labels: R0-silent, T15-bridges

#4952 rpc: add back rpc logger
  substrate/client/rpc-servers/src/lib.rs
Labels: A1-insubstantial, R0-silent

#5018 net/litep2p: Propagate ValuePut events to the network backend
  substrate/client/network/src/litep2p/mod.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement, D0-easy

#5016 command-action: added scoped permissions to the github tokens
  .github/workflows/command-bench-all.yml
  .github/workflows/command-bench-overhead.yml
  .github/workflows/command-bench.yml
  .github/workflows/command-fmt.yml
  .github/workflows/command-sync.yml
  .github/workflows/command-update-ui.yml
Labels: R0-silent

#4972 Remove `pallet-getter` usage from pallet-session
  prdoc/pr_4972.prdoc
  substrate/frame/session/README.md
  substrate/frame/session/benchmarking/src/inner.rs
  substrate/frame/session/src/lib.rs
  substrate/frame/session/src/tests.rs
Labels: T2-pallets

#4848 [1 / 5] Optimize logic for gossiping assignments
  polkadot/node/network/approval-distribution/src/lib.rs
  polkadot/node/network/approval-distribution/src/tests.rs
  polkadot/node/network/protocol/src/grid_topology.rs
  prdoc/pr_4848.prdoc
Labels: T0-node

#4566 [pallet_contracts] Add support for transient storage in contracts host functions
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/contracts.rs
  prdoc/pr_4566.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/contracts/fixtures/contracts/create_transient_storage_and_call.rs
  substrate/frame/contracts/fixtures/contracts/set_transient_storage.rs
  substrate/frame/contracts/fixtures/contracts/transient_storage.rs
  substrate/frame/contracts/src/benchmarking/call_builder.rs
  substrate/frame/contracts/src/benchmarking/mod.rs
  substrate/frame/contracts/src/exec.rs
  substrate/frame/contracts/src/lib.rs
  substrate/frame/contracts/src/storage.rs
  substrate/frame/contracts/src/tests.rs
  substrate/frame/contracts/src/transient_storage.rs
  substrate/frame/contracts/src/wasm/mod.rs
  substrate/frame/contracts/src/wasm/runtime.rs
  substrate/frame/contracts/src/weights.rs
  substrate/frame/contracts/uapi/src/host.rs
  substrate/frame/contracts/uapi/src/host/riscv32.rs
  substrate/frame/contracts/uapi/src/host/wasm32.rs
Labels: T7-smart_contracts

#5028 Adjust base value for statement-distribution regression tests
  polkadot/node/network/statement-distribution/benches/statement-distribution-regression-bench.rs
Labels: R0-silent, T12-benchmarks

#5032 [ci] Update forklift in CI image
  .github/env
Labels: R0-silent

#4755 Send PeerViewChange with high priority
  Cargo.lock
  Cargo.toml
  polkadot/node/malus/src/interceptor.rs
  polkadot/node/network/availability-distribution/src/tests/state.rs
  polkadot/node/network/bridge/src/rx/mod.rs
  polkadot/node/network/bridge/src/rx/tests.rs
  polkadot/node/overseer/src/lib.rs
  polkadot/node/subsystem-test-helpers/src/lib.rs
  prdoc/pr_4755.prdoc
Labels: T0-node, T8-polkadot

#4663 add elastic scaling MVP guide
  Cargo.lock
  cumulus/polkadot-parachain/Cargo.toml
  cumulus/polkadot-parachain/src/service.rs
  docs/sdk/src/guides/enable_elastic_scaling_mvp.rs
  docs/sdk/src/guides/mod.rs
  prdoc/pr_4663.prdoc
Labels: T11-documentation

#5015 Adjust release flows to use those with the new branch model
  .github/scripts/common/lib.sh
  .github/workflows/release-10_rc-automation.yml
  .github/workflows/release-50_publish-docker.yml
  .github/workflows/release-srtool.yml
Labels: R0-silent

#4997 Do not crash on block gap in `displaced_leaves_after_finalizing`
  Cargo.lock
  prdoc/pr_4997.prdoc
  substrate/client/db/src/lib.rs
  substrate/primitives/blockchain/Cargo.toml
  substrate/primitives/blockchain/src/backend.rs
  substrate/primitives/blockchain/src/lib.rs
Labels: T0-node

#5040 fix: Update libp2p-websocket to v0.42.2 to fix panics
  Cargo.lock
  prdoc/pr_5040.prdoc
Labels: A1-insubstantial, T0-node, I2-bug, D0-easy

#5037 Fix landlock presence test
  polkadot/node/core/pvf/tests/it/main.rs
Labels: R0-silent, T10-tests

#5052 Remove accidentally added files
  .gitignore
  master.wasm
  modified.wasm
  substrate/kitchensink_runtime.wasm
Labels: R0-silent

#4992 Add 'missing_docs' attribute to dummy package
  substrate/utils/wasm-builder/src/prerequisites.rs
Labels: R0-silent

#5054 Update command-fmt.yml
  .github/workflows/command-fmt.yml
Labels: R0-silent

#5056 upgrade `wasm-bindgen` to 0.2.92
  Cargo.lock
Labels: R0-silent

#5022 Update the template synchronization script
  .github/workflows/misc-sync-templates.yml
Labels: R0-silent

#3777 wasm-builder: Also set `mcpu` for c deps
  substrate/utils/wasm-builder/src/wasm_project.rs
Labels: R0-silent

#5063 Use `Mutex` in `HeaderMetadataCache`
  substrate/primitives/blockchain/src/header_metadata.rs
Labels: R0-silent

#4976 Add `pub` to xcm::v4::PalletInfo
  polkadot/xcm/src/v4/mod.rs
  prdoc/pr_4976.prdoc
Labels: T6-XCM

#4959 relax `XcmFeeToAccount` trait bound on `AccountId`
  Cargo.lock
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/people/people-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/people/people-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
  polkadot/runtime/rococo/src/xcm_config.rs
  polkadot/runtime/westend/src/xcm_config.rs
  polkadot/xcm/Cargo.toml
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/src/v4/location.rs
  polkadot/xcm/xcm-builder/src/fee_handling.rs
  polkadot/xcm/xcm-builder/src/lib.rs
  prdoc/pr_4959.prdoc
Labels: T6-XCM

#5073 prdoc: Require `bump` field
  prdoc/pr_3286.prdoc
  prdoc/schema_user.json
Labels: R0-silent

#4751 beefy: put not only lease parachain heads into mmr
  Cargo.lock
  polkadot/runtime/parachains/Cargo.toml
  polkadot/runtime/parachains/src/paras/benchmarking.rs
  polkadot/runtime/parachains/src/paras/benchmarking/mmr_setup.rs
  polkadot/runtime/parachains/src/paras/mod.rs
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/mod.rs
  polkadot/runtime/rococo/src/weights/pallet_mmr.rs
  polkadot/runtime/westend/Cargo.toml
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/mod.rs
  polkadot/runtime/westend/src/weights/pallet_mmr.rs
  prdoc/pr_4751.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/beefy-mmr/Cargo.toml
  substrate/frame/beefy-mmr/src/mock.rs
  substrate/frame/merkle-mountain-range/src/benchmarking.rs
  substrate/frame/merkle-mountain-range/src/default_weights.rs
  substrate/frame/merkle-mountain-range/src/lib.rs
  substrate/frame/merkle-mountain-range/src/mock.rs
  umbrella/Cargo.toml
Labels: T8-polkadot

#4981 [NPoS] Some simple refactors to Delegate Staking
  substrate/frame/delegated-staking/src/lib.rs
  substrate/frame/delegated-staking/src/tests.rs
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/nomination-pools/src/mock.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/tests.rs
  substrate/primitives/staking/src/lib.rs
Labels: R0-silent, T2-pallets

#4640 Implements `PoV` export and local validation
  Cargo.lock
  Cargo.toml
  cumulus/bin/pov-validator/Cargo.toml
  cumulus/bin/pov-validator/src/main.rs
  cumulus/client/consensus/aura/src/collators/lookahead.rs
  cumulus/polkadot-parachain/src/cli.rs
  cumulus/polkadot-parachain/src/command.rs
  cumulus/polkadot-parachain/src/common/mod.rs
  cumulus/polkadot-parachain/src/service.rs
  prdoc/pr_4640.prdoc
Labels: T9-cumulus

#4936 Balances Pallet: Emit events when TI is updated in currency impl
  Cargo.lock
  prdoc/pr_4936.prdoc
  substrate/bin/node/bench/src/import.rs
  substrate/bin/node/cli/Cargo.toml
  substrate/bin/node/cli/tests/basic.rs
  substrate/frame/balances/src/impl_currency.rs
  substrate/frame/balances/src/lib.rs
  substrate/frame/balances/src/tests/currency_tests.rs
  substrate/frame/balances/src/tests/reentrancy_tests.rs
Labels: T2-pallets

#5020 command action: documented use of gh cli
  .github/commands-readme.md
Labels: R0-silent

#5075 beefy: Increment metric and add extra log details
  substrate/client/consensus/beefy/src/communication/peers.rs
  substrate/client/consensus/beefy/src/communication/request_response/outgoing_requests_engine.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement, D0-easy

#5077 litep2p: Improve metric reasons for RequestResponse errors
  substrate/client/network/src/litep2p/shim/request_response/mod.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement, D0-easy

#5072 backport v1.14: fix: Update libp2p-websocket to v0.42.2 to fix panics (#5040)
  Cargo.lock
  prdoc/1.14.0/pr_5040.prdoc
Labels: A1-insubstantial, R0-silent, I0-panic, D0-easy

#4706 Rename `assigner_on_demand` to `on_demand`
  Cargo.lock
  polkadot/runtime/parachains/src/assigner_coretime/mod.rs
  polkadot/runtime/parachains/src/assigner_coretime/tests.rs
  polkadot/runtime/parachains/src/coretime/benchmarking.rs
  polkadot/runtime/parachains/src/coretime/mod.rs
  polkadot/runtime/parachains/src/lib.rs
  polkadot/runtime/parachains/src/mock.rs
  polkadot/runtime/parachains/src/on_demand/benchmarking.rs
  polkadot/runtime/parachains/src/on_demand/migration.rs
  polkadot/runtime/parachains/src/on_demand/mock_helpers.rs
  polkadot/runtime/parachains/src/on_demand/mod.rs
  polkadot/runtime/parachains/src/on_demand/tests.rs
  polkadot/runtime/parachains/src/on_demand/types.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/mod.rs
  polkadot/runtime/rococo/src/weights/runtime_parachains_on_demand.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/mod.rs
  polkadot/runtime/westend/src/weights/runtime_parachains_on_demand.rs
  prdoc/pr_4706.prdoc
Labels: T2-pallets

#5105 Update parity publish
  .github/workflows/check-semver.yml
  .github/workflows/publish-check-crates.yml
  .github/workflows/publish-claim-crates.yml
Labels: A1-insubstantial, R0-silent

#4791 Prepare PVFs if node is a validator in the next session
  .gitlab/pipeline/zombienet/polkadot.yml
  Cargo.lock
  polkadot/node/core/candidate-validation/Cargo.toml
  polkadot/node/core/candidate-validation/src/lib.rs
  polkadot/node/core/candidate-validation/src/tests.rs
  polkadot/node/service/src/overseer.rs
  polkadot/zombienet_tests/smoke/0005-precompile-pvf-smoke.js
  polkadot/zombienet_tests/smoke/0005-precompile-pvf-smoke.toml
  polkadot/zombienet_tests/smoke/0005-precompile-pvf-smoke.zndsl
  polkadot/zombienet_tests/smoke/0005-register-deregister-validator.js
  polkadot/zombienet_tests/smoke/0005-register-para.js
  prdoc/pr_4791.prdoc
Labels: T0-node, T8-polkadot

#4938 feat: introduce pallet-parameters to Westend to parameterize inflation
  Cargo.lock
  polkadot/runtime/common/src/impls.rs
  polkadot/runtime/westend/Cargo.toml
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/mod.rs
  polkadot/runtime/westend/src/weights/pallet_parameters.rs
  prdoc/pr_4938.prdoc
  prdoc/pr_4943.prdoc
Labels: T8-polkadot

#5115 [subsystem-bench] Adjust approval-voting-regression-bench
  polkadot/node/core/approval-voting/benches/approval-voting-regression-bench.rs
Labels: R0-silent, T12-benchmarks

#4994 Frame Metadata Deprecation: Refactor enum a bit
  prdoc/pr_4851.prdoc
  substrate/frame/support/procedural/src/deprecation.rs
  substrate/frame/support/procedural/src/pallet/expand/call.rs
  substrate/frame/support/procedural/src/pallet/expand/error.rs
  substrate/frame/support/procedural/src/pallet/expand/event.rs
  substrate/frame/support/procedural/src/pallet/expand/pallet_struct.rs
  substrate/frame/support/src/storage/types/counted_map.rs
  substrate/frame/support/src/storage/types/counted_nmap.rs
  substrate/frame/support/src/storage/types/double_map.rs
  substrate/frame/support/src/storage/types/map.rs
  substrate/frame/support/src/storage/types/mod.rs
  substrate/frame/support/src/storage/types/nmap.rs
  substrate/frame/support/src/storage/types/value.rs
  substrate/frame/support/src/tests/mod.rs
  substrate/frame/support/test/tests/instance.rs
  substrate/frame/support/test/tests/pallet.rs
  substrate/frame/support/test/tests/runtime_metadata.rs
  substrate/primitives/api/proc-macro/src/utils.rs
  substrate/primitives/metadata-ir/src/types.rs
Labels: R0-silent, I5-enhancement, D1-medium

#4564 Make `on_unbalanceds` work with `fungibles` `imbalances`
  cumulus/parachains/common/src/impls.rs
  polkadot/runtime/common/src/impls.rs
  prdoc/pr_4564.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/balances/src/impl_currency.rs
  substrate/frame/support/src/traits/tokens/fungible/imbalance.rs
  substrate/frame/support/src/traits/tokens/fungibles/imbalance.rs
  substrate/frame/support/src/traits/tokens/imbalance.rs
  substrate/frame/support/src/traits/tokens/imbalance/on_unbalanced.rs
  substrate/frame/transaction-payment/asset-conversion-tx-payment/src/mock.rs
  substrate/frame/transaction-payment/src/mock.rs
Labels: T1-FRAME

#4993 Beefy equivocation: add runtime API methods
  polkadot/node/service/src/fake_runtime_api.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_4993.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/beefy-mmr/src/lib.rs
  substrate/frame/beefy/src/lib.rs
  substrate/frame/beefy/src/mock.rs
  substrate/primitives/consensus/beefy/src/lib.rs
Labels: T15-bridges

#2923 Replace all ansi_term crates
  Cargo.lock
  Cargo.toml
  bridges/relays/utils/Cargo.toml
  bridges/relays/utils/src/initialize.rs
  cumulus/test/service/src/lib.rs
  polkadot/node/test/service/src/lib.rs
  prdoc/pr_2923.prdoc
  substrate/bin/node/cli/benches/block_production.rs
  substrate/bin/node/cli/benches/transaction_pool.rs
  substrate/client/cli/src/config.rs
  substrate/client/cli/src/runner.rs
  substrate/client/informant/Cargo.toml
  substrate/client/informant/src/display.rs
  substrate/client/informant/src/lib.rs
  substrate/client/service/src/builder.rs
  substrate/client/service/src/config.rs
  substrate/client/service/test/src/lib.rs
  substrate/client/tracing/Cargo.toml
  substrate/client/tracing/src/logging/event_format.rs
  substrate/client/tracing/src/logging/mod.rs
Labels: T0-node

#4586 Remove pallet::getter macro from pallet-identity
  cumulus/parachains/integration-tests/emulated/tests/people/people-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-rococo/src/tests/reap_identity.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/reap_identity.rs
  prdoc/pr_4586.prdoc
  substrate/bin/node/runtime/src/impls.rs
  substrate/frame/alliance/src/mock.rs
  substrate/frame/identity/src/legacy.rs
  substrate/frame/identity/src/lib.rs
  substrate/frame/identity/src/tests.rs
Labels: T1-FRAME

#4977 network/metrics: Expose number of banned peers from peerstore and enable litep2p metrics
  cumulus/client/relay-chain-minimal-node/src/lib.rs
  cumulus/polkadot-parachain/src/service.rs
  cumulus/test/service/src/lib.rs
  polkadot/node/service/src/lib.rs
  substrate/bin/node/cli/src/service.rs
  substrate/client/network/src/config.rs
  substrate/client/network/src/litep2p/mod.rs
  substrate/client/network/src/litep2p/peerstore.rs
  substrate/client/network/src/litep2p/shim/notification/tests/fuzz.rs
  substrate/client/network/src/mock.rs
  substrate/client/network/src/peer_store.rs
  substrate/client/network/src/protocol/notifications/tests.rs
  substrate/client/network/src/protocol_controller.rs
  substrate/client/network/src/service.rs
  substrate/client/network/src/service/metrics.rs
  substrate/client/network/src/service/traits.rs
  substrate/client/network/test/src/fuzz.rs
  substrate/client/network/test/src/lib.rs
  substrate/client/network/test/src/service.rs
  templates/minimal/node/src/service.rs
  templates/parachain/node/src/service.rs
  templates/solochain/node/src/service.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement, D0-easy

#5103 hotfix: blockchain/backend: Skip genesis leaf to unblock syncing
  prdoc/pr_5103.prdoc
  substrate/client/db/src/lib.rs
  substrate/primitives/blockchain/src/backend.rs
  substrate/zombienet/0001-basic-warp-sync/test-warp-sync.toml
  substrate/zombienet/0001-basic-warp-sync/test-warp-sync.zndsl
Labels: A1-insubstantial, T0-node, I2-bug, I5-enhancement, D1-medium

#5114 Remove not-audited warning
  prdoc/pr_5114.prdoc
  substrate/frame/safe-mode/src/lib.rs
  substrate/frame/tx-pause/src/lib.rs
Labels: T2-pallets

#4613 include events for voting
  prdoc/pr_4613.prdoc
  substrate/frame/conviction-voting/src/lib.rs
Labels: T2-pallets

#5042 [subsystem-bench] Add mocks for own assignments triggering
  polkadot/node/subsystem-bench/src/lib/approval/mod.rs
  polkadot/node/subsystem-bench/src/lib/mock/availability_recovery.rs
  polkadot/node/subsystem-bench/src/lib/mock/candidate_validation.rs
  polkadot/node/subsystem-bench/src/lib/mock/mod.rs
  polkadot/node/subsystem-bench/src/lib/mock/runtime_api.rs
Labels: R0-silent

#4946 Use jobserver in wasm-builder to limit concurrency of spawned cargo processes
  Cargo.lock
  Cargo.toml
  substrate/utils/wasm-builder/Cargo.toml
  substrate/utils/wasm-builder/src/builder.rs
  substrate/utils/wasm-builder/src/wasm_project.rs
Labels: R0-silent

#4931 Migrate BEEFY BLS crypto to bls12-381 curve
  substrate/client/consensus/beefy/src/keystore.rs
  substrate/client/keystore/src/local.rs
  substrate/primitives/application-crypto/src/bls377.rs
  substrate/primitives/application-crypto/src/bls381.rs
  substrate/primitives/application-crypto/src/ecdsa_bls381.rs
  substrate/primitives/application-crypto/src/lib.rs
  substrate/primitives/consensus/beefy/src/commitment.rs
  substrate/primitives/consensus/beefy/src/lib.rs
  substrate/primitives/consensus/beefy/src/witness.rs
  substrate/primitives/core/src/bls.rs
  substrate/primitives/core/src/lib.rs
  substrate/primitives/core/src/paired_crypto.rs
  substrate/primitives/core/src/testing.rs
  substrate/primitives/io/src/lib.rs
  substrate/primitives/keystore/src/lib.rs
  substrate/primitives/keystore/src/testing.rs
Labels: R0-silent, I5-enhancement

#4345 fix(chain-spec): ChainSpecBuilder with object as default genesis
  substrate/client/chain-spec/src/chain_spec.rs
Labels: T0-node

#5099 pallet macro: do not generate try-runtime related code when frame-support doesn't have try-runtime.
  substrate/frame/support/procedural/src/pallet/expand/hooks.rs
  substrate/frame/support/procedural/src/pallet/expand/storage.rs
  substrate/frame/support/src/lib.rs
  substrate/frame/support/test/tests/pallet_ui/pass/simple_storage.rs
Labels: R0-silent, T1-FRAME

#5123 Backport #5103
  prdoc/1.15.0/pr_5103.prdoc
  substrate/client/db/src/lib.rs
  substrate/primitives/blockchain/src/backend.rs
  substrate/zombienet/0001-basic-warp-sync/test-warp-sync.toml
  substrate/zombienet/0001-basic-warp-sync/test-warp-sync.zndsl
Labels: R0-silent, A3-backport

#4970 Remove `pallet-getter` usage from pallet-transaction-payment
  prdoc/pr_4970.prdoc
  substrate/frame/transaction-payment/src/lib.rs
  substrate/frame/transaction-payment/src/tests.rs
Labels: T2-pallets

#4488 Tx Payment: drop ED requirements for tx payments with exchangeable asset
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_4488.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/asset-conversion/src/swap.rs
  substrate/frame/transaction-payment/asset-conversion-tx-payment/src/lib.rs
  substrate/frame/transaction-payment/asset-conversion-tx-payment/src/mock.rs
  substrate/frame/transaction-payment/asset-conversion-tx-payment/src/payment.rs
  substrate/frame/transaction-payment/asset-conversion-tx-payment/src/tests.rs
  substrate/frame/transaction-payment/src/lib.rs
Labels: T1-FRAME

#5126 Fix after ring-proof api change
  Cargo.lock
  substrate/primitives/core/Cargo.toml
Labels: A1-insubstantial, R0-silent

#4536 membership: Restructure pallet into separate files
  substrate/frame/membership/src/benchmarking.rs
  substrate/frame/membership/src/lib.rs
  substrate/frame/membership/src/mock.rs
  substrate/frame/membership/src/tests.rs
Labels: R0-silent

#5085 Introduce a workflow updating the wishlist leaderboards
  .github/scripts/update-wishlist-leaderboard.py
  .github/workflows/misc-update-wishlist-leaderboard.yml
Labels: R0-silent

#3095 Fix misleading comment about RewardHandler in epm config
  polkadot/runtime/westend/src/lib.rs
  substrate/bin/node/runtime/src/lib.rs
Labels: R0-silent

#5128 Bridges improved tests and nits
  Cargo.lock
  bridges/bin/runtime-common/src/integrity.rs
  bridges/modules/messages/src/proofs.rs
  bridges/modules/messages/src/tests/mock.rs
  bridges/modules/xcm-bridge-hub/Cargo.toml
  bridges/modules/xcm-bridge-hub/src/exporter.rs
  bridges/modules/xcm-bridge-hub/src/mock.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_bulletin_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_westend_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/bridge_to_rococo_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/from_grandpa_chain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/from_parachain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/helpers.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_data/from_grandpa_chain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_data/from_parachain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_data/mod.rs
Labels: R0-silent, T15-bridges

#4665 CandidateDescriptor: disable collator signature and collator id usage
  polkadot/node/core/prospective-parachains/src/fragment_chain/mod.rs
  polkadot/node/subsystem-util/src/inclusion_emulator/mod.rs
  polkadot/primitives/src/v7/mod.rs
  polkadot/runtime/parachains/src/builder.rs
  polkadot/runtime/parachains/src/inclusion/mod.rs
  polkadot/runtime/parachains/src/inclusion/tests.rs
  prdoc/pr_4665.prdoc
Labels: T8-polkadot

#5124 Add people polkadot genesis chainspec
  cumulus/parachains/chain-specs/people-polkadot.json
  cumulus/polkadot-parachain/chain-specs/people-polkadot.json
  cumulus/polkadot-parachain/src/chain_spec/people.rs
  prdoc/pr_5124.prdoc
Labels: A1-insubstantial, T14-system_parachains

#4879 Getting Started Script
  README.md
  scripts/getting-started.sh
Labels: R0-silent

#5145 Dependabot: Group all CI dependencies
  .github/dependabot.yml
Labels: R0-silent

#3786 authorithy-discovery: Make changing of peer-id while active a bit more robust
  polkadot/node/network/bridge/src/network.rs
  polkadot/node/network/bridge/src/rx/tests.rs
  polkadot/node/network/bridge/src/tx/mod.rs
  polkadot/node/network/bridge/src/tx/tests.rs
  polkadot/node/network/bridge/src/validator_discovery.rs
  polkadot/node/network/gossip-support/src/lib.rs
  polkadot/node/network/gossip-support/src/tests.rs
  polkadot/node/subsystem-types/src/messages.rs
  prdoc/pr_3786.prdoc
  substrate/client/authority-discovery/build.rs
  substrate/client/authority-discovery/src/worker.rs
  substrate/client/authority-discovery/src/worker/schema/dht-v3.proto
  substrate/client/authority-discovery/src/worker/schema/tests.rs
  substrate/client/authority-discovery/src/worker/tests.rs
  substrate/client/network/src/behaviour.rs
  substrate/client/network/src/discovery.rs
  substrate/client/network/src/event.rs
  substrate/client/network/src/litep2p/discovery.rs
  substrate/client/network/src/litep2p/mod.rs
  substrate/client/network/src/litep2p/service.rs
  substrate/client/network/src/service.rs
  substrate/client/network/src/service/traits.rs
Labels: T0-node, T8-polkadot

#5143 enhancing solochain template
  Cargo.lock
  templates/parachain/runtime/src/configs/mod.rs
  templates/parachain/runtime/src/lib.rs
  templates/solochain/node/Cargo.toml
  templates/solochain/node/src/benchmarking.rs
  templates/solochain/node/src/service.rs
  templates/solochain/runtime/Cargo.toml
  templates/solochain/runtime/build.rs
  templates/solochain/runtime/src/apis.rs
  templates/solochain/runtime/src/benchmarks.rs
  templates/solochain/runtime/src/configs/mod.rs
  templates/solochain/runtime/src/lib.rs
Labels: R0-silent

#5132 Add `from_mel` for `Footprint` with a Test
  prdoc/pr_5132.prdoc
  substrate/frame/support/src/traits/storage.rs
Labels: T1-FRAME

#4812 CI: Prevent breaking backports
  .github/workflows/check-semver.yml
Labels: R0-silent

#5149 Upgrade time crate, fix compilation on Rust 1.80
  Cargo.lock
Labels: R0-silent

#5151 Umbrella crate: Add polkadot-sdk-frame/?runtime
  .config/zepter.yaml
  scripts/generate-umbrella.py
  umbrella/Cargo.toml
Labels: R0-silent, T1-FRAME

#5129 BEEFY: Disarm finality notifications to prevent pinning
  prdoc/pr_5129.prdoc
  substrate/client/consensus/beefy/src/lib.rs
  substrate/client/consensus/beefy/src/tests.rs
  substrate/client/consensus/beefy/src/worker.rs
Labels: T0-node

#5156 [v.1.14 backport]: runtime: make the candidate relay parent progression check more strict
  polkadot/runtime/parachains/src/inclusion/mod.rs
  polkadot/runtime/parachains/src/paras_inherent/mod.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
  prdoc/1.14.0/pr_5113.prdoc
Labels: A3-backport, I2-bug, T8-polkadot

#5152 Update README.md
  README.md
Labels: R0-silent

#5150 Fix warnings for rust 1.80
  Cargo.toml
  substrate/frame/support/src/lib.rs
  substrate/frame/support/src/storage/generator/map.rs
  substrate/primitives/runtime-interface/src/lib.rs
  substrate/primitives/weights/src/weight_v2.rs
Labels: R0-silent

#5067 Fix region nonfungible implementation
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  prdoc/pr_5067.prdoc
  substrate/frame/broker/src/dispatchable_impls.rs
  substrate/frame/broker/src/nonfungible_impl.rs
  substrate/frame/broker/src/tests.rs
  substrate/frame/broker/src/utility_impls.rs
Labels: T2-pallets

#5157 [stable2407 backport] runtime: make the candidate relay parent progression check more stric…
  polkadot/runtime/parachains/src/inclusion/mod.rs
  polkadot/runtime/parachains/src/paras_inherent/mod.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
  prdoc/1.15.0/pr_5113.prdoc
Labels: A3-backport, T8-polkadot

#5161 Re: fix warnings with latest rust
  Cargo.toml
Labels: R0-silent

#5153 grandpa: handle error from SelectChain::finality_target
  prdoc/pr_5153.prdoc
  substrate/client/consensus/grandpa/src/environment.rs
  substrate/client/consensus/grandpa/src/tests.rs
Labels: T0-node

#5036 [pallet_contracts] Modify the storage host function benchmarks to run on an unbalanced storage trie.
  prdoc/pr_5036.prdoc
  substrate/frame/contracts/src/benchmarking/mod.rs
  substrate/frame/contracts/src/storage.rs
  substrate/frame/contracts/src/wasm/runtime.rs
  substrate/frame/contracts/src/weights.rs
Labels: T7-smart_contracts

#4845 [2 / 5] Make approval-distribution logic runnable on a separate thread
  polkadot/node/network/approval-distribution/src/lib.rs
  prdoc/pr_4845.prdoc
Labels: T0-node, T8-polkadot

#4901 rpc v2: `submitAndWatch` replace old messages if it's lagging
  substrate/client/consensus/beefy/rpc/src/lib.rs
  substrate/client/consensus/grandpa/rpc/src/lib.rs
  substrate/client/rpc-spec-v2/src/chain_head/chain_head.rs
  substrate/client/rpc-spec-v2/src/chain_head/chain_head_follow.rs
  substrate/client/rpc-spec-v2/src/transaction/tests/transaction_tests.rs
  substrate/client/rpc-spec-v2/src/transaction/transaction.rs
  substrate/client/rpc/src/author/mod.rs
  substrate/client/rpc/src/chain/chain_full.rs
  substrate/client/rpc/src/state/state_full.rs
  substrate/client/rpc/src/utils.rs
Labels: R0-silent

#5154 Various corrections in the documentation
  Cargo.lock
  docs/contributor/DOCUMENTATION_GUIDELINES.md
  docs/sdk/Cargo.toml
  docs/sdk/src/guides/async_backing_guide.rs
  docs/sdk/src/guides/enable_elastic_scaling_mvp.rs
  docs/sdk/src/guides/enable_metadata_hash.rs
  docs/sdk/src/guides/enable_pov_reclaim.rs
  docs/sdk/src/guides/mod.rs
  docs/sdk/src/guides/your_first_pallet/mod.rs
  docs/sdk/src/lib.rs
  docs/sdk/src/meta_contributing.rs
  docs/sdk/src/polkadot_sdk/frame_runtime.rs
  docs/sdk/src/polkadot_sdk/mod.rs
  docs/sdk/src/polkadot_sdk/polkadot.rs
  docs/sdk/src/polkadot_sdk/substrate.rs
  docs/sdk/src/polkadot_sdk/xcm.rs
  docs/sdk/src/reference_docs/cli.rs
  docs/sdk/src/reference_docs/custom_runtime_api_rpc.rs
  docs/sdk/src/reference_docs/defensive_programming.rs
  docs/sdk/src/reference_docs/development_environment_advice.rs
  docs/sdk/src/reference_docs/frame_benchmarking_weight.rs
  docs/sdk/src/reference_docs/frame_logging.rs
  docs/sdk/src/reference_docs/frame_offchain_workers.rs
  docs/sdk/src/reference_docs/frame_pallet_coupling.rs
  docs/sdk/src/reference_docs/frame_runtime_types.rs
  docs/sdk/src/reference_docs/frame_runtime_upgrades_and_migrations.rs
  docs/sdk/src/reference_docs/frame_storage_derives.rs
  docs/sdk/src/reference_docs/frame_system_accounts.rs
  docs/sdk/src/reference_docs/frame_tokens.rs
  docs/sdk/src/reference_docs/metadata.rs
  docs/sdk/src/reference_docs/mod.rs
  docs/sdk/src/reference_docs/runtime_vs_smart_contract.rs
  docs/sdk/src/reference_docs/trait_based_programming.rs
  docs/sdk/src/reference_docs/umbrella_crate.rs
  docs/sdk/src/reference_docs/wasm_meta_protocol.rs
  substrate/frame/support/src/lib.rs
Labels: R0-silent, T11-documentation

#5174 Wasm-builder: Set the resolver version
  prdoc/pr_5174.prdoc
  substrate/utils/wasm-builder/src/wasm_project.rs
Labels: T0-node

#5078 add possibility to inject non-authorities session-keys in genesis
  cumulus/pallets/collator-selection/src/mock.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-rococo/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-westend/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-rococo/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-westend/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/collectives/collectives-westend/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/coretime/coretime-rococo/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/coretime/coretime-westend/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/people/people-rococo/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/people/people-westend/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/testing/penpal/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/relays/rococo/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/relays/westend/src/genesis.rs
  cumulus/parachains/runtimes/test-utils/src/lib.rs
  cumulus/polkadot-parachain/src/chain_spec/asset_hubs.rs
  prdoc/pr_5078.prdoc
  substrate/bin/node/cli/tests/res/default_genesis_config.json
  substrate/bin/node/testing/src/genesis.rs
  substrate/frame/babe/src/mock.rs
  substrate/frame/beefy-mmr/src/mock.rs
  substrate/frame/beefy/src/mock.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
  substrate/frame/grandpa/src/mock.rs
  substrate/frame/root-offences/src/mock.rs
  substrate/frame/session/src/historical/mod.rs
  substrate/frame/session/src/historical/offchain.rs
  substrate/frame/session/src/lib.rs
  substrate/frame/session/src/mock.rs
  substrate/frame/staking/src/mock.rs
Labels: T2-pallets

#5177 Review-bot@2.6.0
  .github/workflows/review-bot.yml
Labels: R0-silent

#4487 Remove pallet::getter macro usage from pallet-election-provider-multi-phase
  prdoc/pr_4487.prdoc
  substrate/frame/election-provider-multi-phase/src/benchmarking.rs
  substrate/frame/election-provider-multi-phase/src/helpers.rs
  substrate/frame/election-provider-multi-phase/src/lib.rs
  substrate/frame/election-provider-multi-phase/src/mock.rs
  substrate/frame/election-provider-multi-phase/src/signed.rs
  substrate/frame/election-provider-multi-phase/src/unsigned.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/lib.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
Labels: T1-FRAME

#4963 Remove pallet::getter usage from proxy
  prdoc/pr_4963.prdoc
  substrate/frame/proxy/src/lib.rs
Labels: T2-pallets

#5180 [subsystem-benchmark] Update availability-distribution-regression-bench baseline after recent subsystem changes
  polkadot/node/network/availability-distribution/benches/availability-distribution-regression-bench.rs
Labels: R0-silent, T12-benchmarks

#5178 [Backport] version bumps and the prdocs reordering from stable2407
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  polkadot/node/primitives/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/1.15.0/pr_3286.prdoc
  prdoc/1.15.0/pr_4097.prdoc
  prdoc/1.15.0/pr_4522.prdoc
  prdoc/1.15.0/pr_4563.prdoc
  prdoc/1.15.0/pr_4566.prdoc
  prdoc/1.15.0/pr_4663.prdoc
  prdoc/1.15.0/pr_4738.prdoc
  prdoc/1.15.0/pr_4755.prdoc
  prdoc/1.15.0/pr_4777.prdoc
  prdoc/1.15.0/pr_4839.prdoc
  prdoc/1.15.0/pr_4840.prdoc
  prdoc/1.15.0/pr_4848.prdoc
  prdoc/1.15.0/pr_4863.prdoc
  prdoc/1.15.0/pr_4871.prdoc
  prdoc/1.15.0/pr_4885.prdoc
  prdoc/1.15.0/pr_4888.prdoc
  prdoc/1.15.0/pr_4902.prdoc
  prdoc/1.15.0/pr_4912.prdoc
  prdoc/1.15.0/pr_4922.prdoc
  prdoc/1.15.0/pr_4932.prdoc
  prdoc/1.15.0/pr_4935.prdoc
  prdoc/1.15.0/pr_4943.prdoc
  prdoc/1.15.0/pr_4972.prdoc
  prdoc/1.15.0/pr_4978.prdoc
  prdoc/1.15.0/pr_4997.prdoc
  prdoc/1.15.0/pr_5011.prdoc
  prdoc/1.15.0/pr_5040.prdoc
  prdoc/1.15.0/pr_5103.prdoc
  prdoc/1.15.0/pr_5153.prdoc
Labels: R0-silent, A3-backport, D0-easy

#5179 [CI] Cache try-runtime check
  .github/workflows/check-runtime-migration.yml
Labels: R0-silent

#5055 pallet-timestamp: `UnixTime::now` implementation logs error only if called at genesis
  prdoc/pr_5055.prdoc
  substrate/frame/timestamp/src/lib.rs
Labels: T2-pallets

#4967 Remove `pallet::getter` usage from the pallet-balances
  prdoc/pr_4967.prdoc
  substrate/frame/balances/src/benchmarking.rs
  substrate/frame/balances/src/lib.rs
  substrate/frame/balances/src/tests/currency_tests.rs
  substrate/frame/balances/src/tests/dispatchable_tests.rs
  substrate/frame/bounties/src/tests.rs
  substrate/frame/conviction-voting/src/tests.rs
  substrate/frame/democracy/src/tests.rs
  substrate/frame/democracy/src/tests/lock_voting.rs
  substrate/frame/democracy/src/tests/voting.rs
  substrate/frame/elections-phragmen/src/lib.rs
  substrate/frame/referenda/src/tests.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/tests.rs
  substrate/frame/treasury/src/tests.rs
Labels: T2-pallets

#5167 Run UI tests in CI for some other crates
  .gitlab/pipeline/test.yml
  Cargo.toml
  polkadot/xcm/procedural/Cargo.toml
  scripts/update-ui-tests.sh
  substrate/frame/election-provider-support/solution-type/Cargo.toml
Labels: R0-silent

#5176 litep2p/discovery: Publish authority records with external addresses only
  substrate/client/authority-discovery/src/worker.rs
  substrate/client/network/src/litep2p/discovery.rs
  substrate/client/network/src/litep2p/mod.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement, D0-easy
