Repository paritytech/polkadot-sdk, pull requests merged in 2024-04, with the labels that each got.

#3738 Removed `pallet::getter` usage from `pallet-alliance`
  prdoc/pr_3738.prdoc
  substrate/frame/alliance/src/benchmarking.rs
  substrate/frame/alliance/src/lib.rs
  substrate/frame/alliance/src/migration.rs
  substrate/frame/alliance/src/tests.rs
Labels: T1-FRAME

#3711 network:bridge: fix peer_count metric
  polkadot/node/network/bridge/src/lib.rs
  polkadot/node/network/bridge/src/rx/mod.rs
Labels: R0-silent, T0-node

#3809 [parachain-template] pallet configurations into `mod configs`
  templates/parachain/runtime/src/apis.rs
  templates/parachain/runtime/src/configs/mod.rs
  templates/parachain/runtime/src/configs/xcm_config.rs
  templates/parachain/runtime/src/lib.rs
Labels: R0-silent

#3897 Improve `HostConfiguration` consistency check
  polkadot/runtime/parachains/src/configuration.rs
Labels: A1-insubstantial, R0-silent

#3438 Pools: Make `PermissionlessWithdraw` the default claim permission
  prdoc/pr_3438.prdoc
  substrate/frame/nomination-pools/benchmarking/src/lib.rs
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/nomination-pools/src/tests.rs
Labels: I5-enhancement, T2-pallets

#3893 Fix 0007-dispute-freshly-finalized.zndsl failing
  polkadot/zombienet_tests/functional/0007-dispute-freshly-finalized.zndsl
Labels: R0-silent

#3925 primitives: Move out of staging released APIs
  cumulus/client/relay-chain-minimal-node/src/blockchain_rpc_client.rs
  cumulus/client/relay-chain-rpc-interface/src/rpc_client.rs
  polkadot/node/core/approval-voting/src/import.rs
  polkadot/node/core/approval-voting/src/lib.rs
  polkadot/node/core/approval-voting/src/tests.rs
  polkadot/node/core/backing/src/lib.rs
  polkadot/node/core/backing/src/tests/mod.rs
  polkadot/node/core/dispute-coordinator/src/tests.rs
  polkadot/node/core/provisioner/src/lib.rs
  polkadot/node/core/runtime-api/src/cache.rs
  polkadot/node/core/runtime-api/src/tests.rs
  polkadot/node/network/availability-distribution/src/pov_requester/mod.rs
  polkadot/node/network/availability-distribution/src/requester/tests.rs
  polkadot/node/network/availability-distribution/src/tests/state.rs
  polkadot/node/network/collator-protocol/src/collator_side/tests/mod.rs
  polkadot/node/network/dispute-distribution/src/tests/mod.rs
  polkadot/node/network/statement-distribution/src/legacy_v1/tests.rs
  polkadot/node/network/statement-distribution/src/v2/statement_store.rs
  polkadot/node/service/src/chain_spec.rs
  polkadot/node/subsystem-bench/src/lib/approval/message_generator.rs
  polkadot/node/subsystem-bench/src/lib/mock/runtime_api.rs
  polkadot/node/subsystem-types/src/messages.rs
  polkadot/node/subsystem-types/src/runtime_client.rs
  polkadot/node/subsystem-util/src/runtime/mod.rs
  polkadot/primitives/src/lib.rs
  polkadot/primitives/src/runtime_api.rs
  polkadot/primitives/src/v7/async_backing.rs
  polkadot/primitives/src/v7/executor_params.rs
  polkadot/primitives/src/v7/metrics.rs
  polkadot/primitives/src/v7/mod.rs
  polkadot/primitives/src/v7/signed.rs
  polkadot/primitives/src/v7/slashing.rs
  polkadot/primitives/src/vstaging/mod.rs
  polkadot/runtime/parachains/src/builder.rs
  polkadot/runtime/parachains/src/configuration.rs
  polkadot/runtime/parachains/src/configuration/migration/v10.rs
  polkadot/runtime/parachains/src/configuration/migration/v11.rs
  polkadot/runtime/parachains/src/disputes.rs
  polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs
  polkadot/runtime/parachains/src/paras_inherent/mod.rs
  polkadot/runtime/parachains/src/runtime_api_impl/mod.rs
  polkadot/runtime/parachains/src/runtime_api_impl/v10.rs
  polkadot/runtime/parachains/src/runtime_api_impl/vstaging.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
Labels: R0-silent

#3928 Fix links
  .github/workflows/check-links.yml
  docs/sdk/src/polkadot_sdk/substrate.rs
  docs/sdk/src/polkadot_sdk/templates.rs
  docs/sdk/src/reference_docs/runtime_vs_smart_contract.rs
Labels: R0-silent, T11-documentation

#3923 pallet-scheduler: fix test
  substrate/frame/scheduler/src/tests.rs
Labels: R0-silent, T10-tests

#3902 `im-online` removal final cleanup
  Cargo.lock
  cumulus/test/service/Cargo.toml
  polkadot/node/service/Cargo.toml
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/Cargo.toml
  polkadot/runtime/westend/src/lib.rs
Labels: R0-silent, T2-pallets

#3920 Update derive syn parse 0.2.0 (+ docify)
  Cargo.lock
  cumulus/primitives/storage-weight-reclaim/Cargo.toml
  docs/sdk/Cargo.toml
  substrate/client/chain-spec/Cargo.toml
  substrate/frame/Cargo.toml
  substrate/frame/bags-list/Cargo.toml
  substrate/frame/balances/Cargo.toml
  substrate/frame/examples/single-block-migrations/Cargo.toml
  substrate/frame/fast-unstake/Cargo.toml
  substrate/frame/migrations/Cargo.toml
  substrate/frame/migrations/src/lib.rs
  substrate/frame/paged-list/Cargo.toml
  substrate/frame/parameters/Cargo.toml
  substrate/frame/safe-mode/Cargo.toml
  substrate/frame/scheduler/Cargo.toml
  substrate/frame/sudo/Cargo.toml
  substrate/frame/support/Cargo.toml
  substrate/frame/support/procedural/Cargo.toml
  substrate/frame/system/Cargo.toml
  substrate/frame/timestamp/Cargo.toml
  substrate/frame/treasury/Cargo.toml
  substrate/frame/tx-pause/Cargo.toml
  substrate/primitives/arithmetic/Cargo.toml
  substrate/primitives/runtime/Cargo.toml
Labels: R0-silent

#3927 pallet-xcm: fix weights for all XTs and deprecate unlimited weight ones
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/test-utils/src/lib.rs
  polkadot/runtime/westend/src/tests.rs
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/pallet-xcm/src/tests/assets_transfer.rs
  polkadot/xcm/xcm-simulator/example/src/lib.rs
  prdoc/pr_3927.prdoc
Labels: T2-pallets

#3341 Fix parachain upgrade scheduling when done by the owner/root
  polkadot/runtime/common/src/paras_registrar/mod.rs
  polkadot/runtime/parachains/src/inclusion/mod.rs
  polkadot/runtime/parachains/src/inclusion/tests.rs
  polkadot/runtime/parachains/src/lib.rs
  polkadot/runtime/parachains/src/paras/benchmarking.rs
  polkadot/runtime/parachains/src/paras/benchmarking/pvf_check.rs
  polkadot/runtime/parachains/src/paras/mod.rs
  polkadot/runtime/parachains/src/paras/tests.rs
  prdoc/pr_3341.prdoc
Labels: T8-polkadot

#3933 chore(zombienet): bump version
  .gitlab/pipeline/zombienet.yml
Labels: R0-silent, T10-tests

#3938 Update bridges subtree
  Cargo.lock
  bridges/README.md
  bridges/bin/runtime-common/Cargo.toml
  bridges/chains/chain-asset-hub-rococo/Cargo.toml
  bridges/chains/chain-asset-hub-westend/Cargo.toml
  bridges/chains/chain-bridge-hub-cumulus/Cargo.toml
  bridges/chains/chain-bridge-hub-kusama/Cargo.toml
  bridges/chains/chain-bridge-hub-polkadot/Cargo.toml
  bridges/chains/chain-bridge-hub-rococo/Cargo.toml
  bridges/chains/chain-bridge-hub-westend/Cargo.toml
  bridges/chains/chain-kusama/Cargo.toml
  bridges/chains/chain-polkadot-bulletin/Cargo.toml
  bridges/chains/chain-polkadot/Cargo.toml
  bridges/chains/chain-rococo/Cargo.toml
  bridges/chains/chain-westend/Cargo.toml
  bridges/modules/grandpa/Cargo.toml
  bridges/modules/messages/Cargo.toml
  bridges/modules/parachains/Cargo.toml
  bridges/modules/relayers/Cargo.toml
  bridges/modules/xcm-bridge-hub-router/Cargo.toml
  bridges/modules/xcm-bridge-hub/Cargo.toml
  bridges/primitives/header-chain/Cargo.toml
  bridges/primitives/messages/Cargo.toml
  bridges/primitives/parachains/Cargo.toml
  bridges/primitives/polkadot-core/Cargo.toml
  bridges/primitives/relayers/Cargo.toml
  bridges/primitives/runtime/Cargo.toml
  bridges/primitives/test-utils/Cargo.toml
  bridges/primitives/xcm-bridge-hub-router/Cargo.toml
  bridges/primitives/xcm-bridge-hub/Cargo.toml
Labels: R0-silent, T15-bridges

#3939 beefy: error logs for validators with dummy keys
  polkadot/node/service/src/lib.rs
  substrate/bin/node/cli/src/service.rs
  substrate/client/consensus/beefy/src/lib.rs
  substrate/client/consensus/beefy/src/tests.rs
  substrate/client/consensus/beefy/src/worker.rs
Labels: R0-silent

#3481 chainHead: Allow methods to be called from within a single connection context and limit connections
  Cargo.lock
  substrate/client/rpc-spec-v2/Cargo.toml
  substrate/client/rpc-spec-v2/src/chain_head/api.rs
  substrate/client/rpc-spec-v2/src/chain_head/chain_head.rs
  substrate/client/rpc-spec-v2/src/chain_head/chain_head_follow.rs
  substrate/client/rpc-spec-v2/src/chain_head/error.rs
  substrate/client/rpc-spec-v2/src/chain_head/subscription/inner.rs
  substrate/client/rpc-spec-v2/src/chain_head/subscription/mod.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
  substrate/client/rpc-spec-v2/src/common/connections.rs
  substrate/client/rpc-spec-v2/src/common/mod.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement, D0-easy

#3835 migrations: prevent accidentally using unversioned migrations instead of `VersionedMigration`
  cumulus/pallets/xcmp-queue/src/migration.rs
  polkadot/runtime/common/src/assigned_slots/migration.rs
  polkadot/runtime/common/src/paras_registrar/migration.rs
  polkadot/runtime/parachains/src/assigner_on_demand/migration.rs
  polkadot/runtime/parachains/src/configuration/migration/v10.rs
  polkadot/runtime/parachains/src/configuration/migration/v11.rs
  polkadot/runtime/parachains/src/configuration/migration/v12.rs
  polkadot/runtime/parachains/src/inclusion/migration.rs
  polkadot/runtime/parachains/src/scheduler/migration.rs
  polkadot/xcm/pallet-xcm/src/migration.rs
  prdoc/pr_3835.prdoc
  substrate/frame/examples/single-block-migrations/src/lib.rs
  substrate/frame/examples/single-block-migrations/src/migrations/v1.rs
  substrate/frame/grandpa/src/migrations/v5.rs
  substrate/frame/identity/src/migration.rs
  substrate/frame/nomination-pools/src/migration.rs
  substrate/frame/society/src/migrations.rs
  substrate/frame/support/src/migrations.rs
  substrate/frame/support/src/traits.rs
  substrate/frame/support/src/traits/hooks.rs
  substrate/frame/support/test/tests/versioned_migration.rs
  substrate/frame/uniques/src/migration.rs
Labels: T1-FRAME

#3761 Snowbridge: Synchronize from Snowfork repository
  bridges/snowbridge/pallets/ethereum-client/fixtures/src/lib.rs
  bridges/snowbridge/pallets/ethereum-client/src/benchmarking/mod.rs
  bridges/snowbridge/pallets/ethereum-client/src/impls.rs
  bridges/snowbridge/pallets/ethereum-client/src/lib.rs
  bridges/snowbridge/pallets/ethereum-client/src/mock.rs
  bridges/snowbridge/pallets/ethereum-client/src/tests.rs
  bridges/snowbridge/pallets/ethereum-client/src/types.rs
  bridges/snowbridge/pallets/ethereum-client/src/weights.rs
  bridges/snowbridge/pallets/ethereum-client/tests/fixtures/execution-header-update.json
  bridges/snowbridge/pallets/ethereum-client/tests/fixtures/execution-proof.json
  bridges/snowbridge/pallets/ethereum-client/tests/fixtures/finalized-header-update.json
  bridges/snowbridge/pallets/ethereum-client/tests/fixtures/inbound-message.json
  bridges/snowbridge/pallets/ethereum-client/tests/fixtures/initial-checkpoint.json
  bridges/snowbridge/pallets/ethereum-client/tests/fixtures/sync-committee-update.json
  bridges/snowbridge/pallets/inbound-queue/fixtures/src/lib.rs
  bridges/snowbridge/pallets/inbound-queue/fixtures/src/register_token.rs
  bridges/snowbridge/pallets/inbound-queue/fixtures/src/register_token_with_insufficient_fee.rs
  bridges/snowbridge/pallets/inbound-queue/fixtures/src/send_token.rs
  bridges/snowbridge/pallets/inbound-queue/fixtures/src/send_token_to_penpal.rs
  bridges/snowbridge/pallets/inbound-queue/src/benchmarking/mod.rs
  bridges/snowbridge/pallets/inbound-queue/src/lib.rs
  bridges/snowbridge/pallets/inbound-queue/src/mock.rs
  bridges/snowbridge/pallets/inbound-queue/src/test.rs
  bridges/snowbridge/primitives/beacon/src/lib.rs
  bridges/snowbridge/primitives/beacon/src/types.rs
  bridges/snowbridge/primitives/beacon/src/updates.rs
  bridges/snowbridge/primitives/core/src/inbound.rs
  bridges/snowbridge/runtime/test-common/src/lib.rs
  bridges/snowbridge/scripts/contribute-upstream.sh
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/snowbridge_pallet_ethereum_client.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/snowbridge_pallet_inbound_queue.rs
  prdoc/pr_3761.prdoc
Labels: T15-bridges

#3942 sp_runtime: TryFrom<RuntimeString> for &str
  substrate/primitives/runtime/src/runtime_string.rs
Labels: R0-silent

#3729 SortedMembers::add for pallet-membership benchmarks
  substrate/frame/membership/src/lib.rs
Labels: R0-silent

#3885 Remove nextest filtration
  .gitlab/pipeline/test.yml
  substrate/frame/core-fellowship/src/benchmarking.rs
  substrate/frame/core-fellowship/src/lib.rs
  substrate/frame/scheduler/src/tests.rs
Labels: R0-silent, T10-tests

#3879 statement-distribution: fix filtering of statements for elastic parachains
  polkadot/node/collation-generation/src/error.rs
  polkadot/node/collation-generation/src/lib.rs
  polkadot/node/collation-generation/src/tests.rs
  polkadot/node/network/statement-distribution/src/error.rs
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  polkadot/node/network/statement-distribution/src/v2/tests/cluster.rs
  polkadot/node/network/statement-distribution/src/v2/tests/grid.rs
  polkadot/node/network/statement-distribution/src/v2/tests/mod.rs
  polkadot/node/subsystem-util/src/vstaging.rs
Labels: R0-silent

#3954 sp-wasm-interface: `wasmtime` should not be enabled by `std`
  substrate/primitives/wasm-interface/Cargo.toml
Labels: R0-silent

#3955 Added tests for XCM barriers: `AllowSubscriptions`, `WithUniqueTopic` and `TrailingSetTopicAsId`
  polkadot/xcm/xcm-builder/src/tests/barriers.rs
  polkadot/xcm/xcm-builder/src/tests/mod.rs
  polkadot/xcm/xcm-builder/src/tests/routing.rs
  polkadot/xcm/xcm-builder/src/tests/version_subscriptions.rs
  polkadot/xcm/xcm-executor/src/traits/should_execute.rs
Labels: R0-silent, T6-XCM

#3858 Enable pov-reclaim on rococo and westend parachains
  Cargo.lock
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/snowbridge.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/Cargo.toml
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/Cargo.toml
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/Cargo.toml
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
Labels: R0-silent, T14-system_parachains

#3950 Add ClaimQueue wrapper
  polkadot/node/collation-generation/src/lib.rs
  polkadot/node/collation-generation/src/tests.rs
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  polkadot/node/subsystem-util/src/vstaging.rs
  prdoc/pr_3950.prdoc
Labels: T0-node

#3813 Renames `frame` crate to `polkadot-sdk-frame`
  Cargo.lock
  docs/sdk/Cargo.toml
  prdoc/pr_3813.prdoc
  substrate/client/chain-spec/src/lib.rs
  substrate/frame/Cargo.toml
  substrate/frame/examples/frame-crate/Cargo.toml
  substrate/frame/src/lib.rs
  substrate/frame/support/procedural/src/lib.rs
  substrate/frame/support/procedural/src/pallet/parse/config.rs
  substrate/frame/support/procedural/tools/src/lib.rs
  substrate/frame/support/test/stg_frame_crate/Cargo.toml
  substrate/frame/support/test/tests/pallet_ui/event_type_invalid_bound_no_frame_crate.rs
  substrate/frame/support/test/tests/pallet_ui/event_type_invalid_bound_no_frame_crate.stderr
  substrate/primitives/api/proc-macro/src/utils.rs
  substrate/utils/frame/benchmarking-cli/src/pallet/command.rs
  substrate/utils/frame/rpc/support/src/lib.rs
  templates/minimal/node/Cargo.toml
  templates/minimal/pallets/template/Cargo.toml
  templates/minimal/runtime/Cargo.toml
Labels: T1-FRAME

#3971 Convince GitLab not to crop collapsed multiline strings
  .gitlab-ci.yml
  .gitlab/pipeline/build.yml
  .gitlab/pipeline/check.yml
  .gitlab/pipeline/publish.yml
  .gitlab/pipeline/test.yml
Labels: R0-silent

#3941 Use 0.1.0 as minimum version for crates
  Cargo.lock
  cumulus/parachains/runtimes/bridge-hubs/common/Cargo.toml
  substrate/frame/parameters/Cargo.toml
  substrate/primitives/crypto/hashing/Cargo.toml
  substrate/primitives/crypto/hashing/proc-macro/Cargo.toml
Labels: A1-insubstantial, R0-silent

#3875 Fix Mermaid diagram rendering
  .gitlab/pipeline/build.yml
  cumulus/test/service/src/chain_spec.rs
  docs/sdk/assets/after-content.html
  docs/sdk/assets/header.html
  docs/sdk/assets/theme.css
  prdoc/pr_3875.prdoc
  substrate/frame/assets/src/lib.rs
Labels: R0-silent, T11-documentation

#2119 [doc] Example MBM pallet
  Cargo.lock
  Cargo.toml
  prdoc/pr_2119.prdoc
  substrate/bin/node/runtime/Cargo.toml
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/examples/multi-block-migrations/Cargo.toml
  substrate/frame/examples/multi-block-migrations/src/lib.rs
  substrate/frame/examples/multi-block-migrations/src/migrations/mod.rs
  substrate/frame/examples/multi-block-migrations/src/migrations/v1/benchmarks.rs
  substrate/frame/examples/multi-block-migrations/src/migrations/v1/mod.rs
  substrate/frame/examples/multi-block-migrations/src/migrations/v1/tests.rs
  substrate/frame/examples/multi-block-migrations/src/migrations/v1/weights.rs
  substrate/frame/examples/multi-block-migrations/src/mock.rs
  substrate/frame/migrations/src/lib.rs
  substrate/frame/migrations/src/mock.rs
  substrate/frame/migrations/src/mock_helpers.rs
  substrate/frame/support/src/migrations.rs
Labels: T1-FRAME

#3708 XCM builder pattern improvement - Accept `impl Into<T>` instead of just `T`
  polkadot/xcm/pallet-xcm/src/tests/mod.rs
  polkadot/xcm/procedural/src/builder_pattern.rs
  polkadot/xcm/procedural/tests/builder_pattern.rs
  polkadot/xcm/src/v4/location.rs
  prdoc/pr_3708.prdoc
Labels: T6-XCM

#3961 Added support for coretime-kusama/polkadot and people-kusama/polkadot
  cumulus/parachains/chain-specs/coretime-kusama.json
  cumulus/parachains/chain-specs/people-kusama.json
  cumulus/polkadot-parachain/chain-specs/coretime-kusama.json
  cumulus/polkadot-parachain/chain-specs/people-kusama.json
  cumulus/polkadot-parachain/src/chain_spec/coretime.rs
  cumulus/polkadot-parachain/src/chain_spec/people.rs
  cumulus/polkadot-parachain/src/command.rs
  prdoc/pr_3961.prdoc
Labels: T9-cumulus

#3974 Make `BlockNumberProvider::set_block_number` available in tests / std
  substrate/primitives/runtime/src/traits.rs
Labels: R0-silent

#2714 `GenesisConfig` presets for runtime
  Cargo.lock
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/starters/seedling/src/lib.rs
  cumulus/parachains/runtimes/starters/shell/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  cumulus/polkadot-parachain/src/fake_runtime_api/asset_hub_polkadot_aura.rs
  cumulus/polkadot-parachain/src/fake_runtime_api/aura.rs
  cumulus/test/runtime/src/lib.rs
  polkadot/node/service/src/chain_spec.rs
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/rococo/src/genesis_config_presets.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_2714.prdoc
  substrate/bin/node/cli/Cargo.toml
  substrate/bin/node/cli/tests/basic.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/bin/utils/chain-spec-builder/Cargo.toml
  substrate/bin/utils/chain-spec-builder/bin/main.rs
  substrate/bin/utils/chain-spec-builder/src/lib.rs
  substrate/client/chain-spec/Cargo.toml
  substrate/client/chain-spec/res/chain_spec_as_json_fails_with_invalid_config.err
  substrate/client/chain-spec/res/substrate_test_runtime_from_named_preset.json
  substrate/client/chain-spec/src/chain_spec.rs
  substrate/client/chain-spec/src/genesis_config_builder.rs
  substrate/client/chain-spec/src/lib.rs
  substrate/frame/support/src/genesis_builder_helper.rs
  substrate/primitives/genesis-builder/Cargo.toml
  substrate/primitives/genesis-builder/src/lib.rs
  substrate/test-utils/runtime/Cargo.toml
  substrate/test-utils/runtime/src/lib.rs
  templates/minimal/runtime/Cargo.toml
  templates/minimal/runtime/src/lib.rs
  templates/parachain/runtime/src/apis.rs
  templates/solochain/runtime/src/lib.rs
Labels: T0-node, T4-runtime_API

#3922 Add Helikon boot nodes for Coretime Westend and People Westend.
  cumulus/parachains/chain-specs/coretime-westend.json
  cumulus/parachains/chain-specs/people-westend.json
Labels: R0-silent

#3988 Update pr_3844.prdoc
  prdoc/pr_3844.prdoc
Labels: R0-silent

#3929 Elastic scaling: add e2e test
  .gitlab/pipeline/zombienet/polkadot.yml
  polkadot/zombienet_tests/elastic_scaling/0001-basic-3cores-6s-blocks.toml
  polkadot/zombienet_tests/elastic_scaling/0001-basic-3cores-6s-blocks.zndsl
  polkadot/zombienet_tests/elastic_scaling/0002-elastic-scaling-doesnt-break-parachains.toml
  polkadot/zombienet_tests/elastic_scaling/0002-elastic-scaling-doesnt-break-parachains.zndsl
  polkadot/zombienet_tests/elastic_scaling/assign-core.js
Labels: R0-silent, T10-tests

#3987 Revert "[prdoc] Require SemVer bump level"
  prdoc/schema_user.json
Labels: R0-silent

#3985 Update pr_3302.prdoc
  prdoc/pr_3302.prdoc
Labels: R0-silent

#3997 [pallet-broker] Fix claim revenue behaviour for zero timeslices
  prdoc/pr_3997.prdoc
  substrate/frame/broker/src/dispatchable_impls.rs
  substrate/frame/broker/src/lib.rs
  substrate/frame/broker/src/tests.rs
Labels: T2-pallets

#3818 [parachain-template] benchmarks into `mod benchmarks`
  templates/parachain/runtime/src/benchmarks.rs
  templates/parachain/runtime/src/lib.rs
Labels: R0-silent

#4005 Rococo/Westend: publish `claim_queue` Runtime API
  cumulus/parachains/integration-tests/emulated/chains/relays/rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/relays/westend/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
Labels: A1-insubstantial, R0-silent

#4004 chore: fix some comments
  polkadot/node/core/approval-voting/src/lib.rs
  substrate/frame/glutton/src/benchmarking.rs
  substrate/frame/nomination-pools/test-staking/src/lib.rs
  substrate/frame/society/src/tests.rs
  substrate/primitives/npos-elections/src/reduce.rs
Labels: R0-silent

#3485 Broker: sale price runtime api
  Cargo.lock
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  prdoc/pr_3485.prdoc
  substrate/frame/broker/Cargo.toml
  substrate/frame/broker/src/dispatchable_impls.rs
  substrate/frame/broker/src/lib.rs
  substrate/frame/broker/src/runtime_api.rs
Labels: T2-pallets

#3976 `pallet-uniques`: decrement `total_deposit` when clearing collection metadata
  prdoc/pr_3976.prdoc
  substrate/frame/nfts/src/features/metadata.rs
  substrate/frame/nfts/src/tests.rs
  substrate/frame/uniques/src/lib.rs
  substrate/frame/uniques/src/tests.rs
Labels: T1-FRAME

#4007 Improve frame umbrella crate doc experience
  substrate/frame/src/lib.rs
  substrate/frame/support/procedural/src/lib.rs
Labels: R0-silent, T11-documentation

#3891 Major bump of tracing-subscriber version
  Cargo.lock
  Cargo.toml
  substrate/client/executor/Cargo.toml
  substrate/client/tracing/Cargo.toml
  substrate/client/tracing/benches/bench.rs
  substrate/client/tracing/src/lib.rs
  substrate/client/tracing/src/logging/event_format.rs
  substrate/client/tracing/src/logging/fast_local_time.rs
  substrate/client/tracing/src/logging/layers/prefix_layer.rs
  substrate/client/tracing/src/logging/mod.rs
  substrate/client/tracing/src/logging/stderr_writer.rs
  substrate/primitives/tracing/Cargo.toml
Labels: R0-silent

#4018 Fix some typos
  cumulus/pallets/collator-selection/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/README.md
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  docs/sdk/src/reference_docs/frame_tokens.rs
  polkadot/node/core/approval-voting/src/approval_checking.rs
  substrate/frame/support/src/traits/tokens/fungible/mod.rs
  substrate/frame/treasury/src/lib.rs
Labels: R0-silent

#3979 Deprecate `para_id()` from `CoreState` in polkadot primitives
  cumulus/client/consensus/aura/src/collators/lookahead.rs
  polkadot/node/core/prospective-parachains/src/tests.rs
  polkadot/node/core/provisioner/src/tests.rs
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  polkadot/primitives/src/v7/mod.rs
  prdoc/pr_3979.prdoc
Labels: T8-polkadot

#4015 sc-beefy-consensus: Remove unneeded stream.
  prdoc/pr_4015.prdoc
  substrate/client/consensus/beefy/src/communication/gossip.rs
  substrate/client/consensus/beefy/src/lib.rs
  substrate/client/consensus/beefy/src/tests.rs
  substrate/client/consensus/beefy/src/worker.rs
Labels: T0-node

#4016 adder-collator: add velocity measurement and make elastic scaling test more robust
  polkadot/parachain/test-parachains/adder/collator/src/lib.rs
  polkadot/zombienet_tests/elastic_scaling/0001-basic-3cores-6s-blocks.zndsl
Labels: R0-silent, T10-tests

#3953 Adapt `RemoteExternalities` and its related types to be used with generic hash parameters
  prdoc/pr_3953.prdoc
  substrate/frame/state-trie-migration/src/lib.rs
  substrate/utils/frame/remote-externalities/src/lib.rs
  substrate/utils/frame/try-runtime/cli/src/lib.rs
Labels: T1-FRAME

#3993 Fixes validation for `SkipCheckIfFeeless` extension
  substrate/frame/transaction-payment/skip-feeless-payment/src/lib.rs
  substrate/frame/transaction-payment/skip-feeless-payment/src/mock.rs
  substrate/frame/transaction-payment/skip-feeless-payment/src/tests.rs
Labels: R0-silent, T1-FRAME

#4029 Removed unused deps from Snowbridge deps
  Cargo.lock
  bridges/snowbridge/pallets/ethereum-client/Cargo.toml
  bridges/snowbridge/pallets/ethereum-client/fixtures/Cargo.toml
  bridges/snowbridge/pallets/inbound-queue/Cargo.toml
  bridges/snowbridge/pallets/inbound-queue/fixtures/Cargo.toml
  bridges/snowbridge/pallets/outbound-queue/Cargo.toml
  bridges/snowbridge/pallets/outbound-queue/runtime-api/Cargo.toml
  bridges/snowbridge/pallets/system/Cargo.toml
  bridges/snowbridge/pallets/system/runtime-api/Cargo.toml
  bridges/snowbridge/primitives/beacon/Cargo.toml
  bridges/snowbridge/primitives/ethereum/Cargo.toml
  bridges/snowbridge/primitives/router/Cargo.toml
  bridges/snowbridge/runtime/runtime-common/Cargo.toml
  bridges/snowbridge/runtime/test-common/Cargo.toml
  bridges/snowbridge/runtime/test-common/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/Cargo.toml
Labels: R0-silent

#3959 Nomination pool configurations can be managed by custom origin
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_3959.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
  substrate/frame/nomination-pools/benchmarking/src/mock.rs
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/nomination-pools/src/mock.rs
  substrate/frame/nomination-pools/src/tests.rs
  substrate/frame/nomination-pools/test-staking/src/mock.rs
Labels: T1-FRAME, T2-pallets, D0-easy

#2943 Contracts: Refactor API to use WeightMeter
  substrate/frame/contracts/src/benchmarking/mod.rs
  substrate/frame/contracts/src/lib.rs
  substrate/frame/contracts/src/migration.rs
  substrate/frame/contracts/src/migration/v09.rs
  substrate/frame/contracts/src/migration/v10.rs
  substrate/frame/contracts/src/migration/v11.rs
  substrate/frame/contracts/src/migration/v12.rs
  substrate/frame/contracts/src/migration/v13.rs
  substrate/frame/contracts/src/migration/v14.rs
  substrate/frame/contracts/src/migration/v15.rs
  substrate/frame/contracts/src/storage.rs
  substrate/frame/contracts/src/tests.rs
Labels: R0-silent

#3982 Upgrade `trie-db` from `0.28.0` to `0.29.0`
  Cargo.lock
  bridges/primitives/runtime/Cargo.toml
  cumulus/pallets/parachain-system/Cargo.toml
  substrate/primitives/state-machine/Cargo.toml
  substrate/primitives/trie/Cargo.toml
  substrate/primitives/trie/src/lib.rs
  substrate/test-utils/runtime/Cargo.toml
  substrate/utils/frame/rpc/state-trie-migration-rpc/Cargo.toml
Labels: R0-silent, T0-node

#4031 peer_store: Increase peer ban time until escapes banned threshold
  substrate/client/network/src/peer_store.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement, D0-easy

#3930 test runtimes: allow local origins to execute arbitrary XCMs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/people/people-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/people/people-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
  polkadot/runtime/westend/src/xcm_config.rs
  prdoc/pr_3930.prdoc
Labels: T6-XCM, T14-system_parachains

#4048 Update subsystem regression benchmarks charts
  bench/availability-distribution-regression-bench/index.html
  bench/availability-recovery-regression-bench/index.html
Labels: R0-silent, T12-benchmarks

#3784 rpc-v2/transaction: Generate `Invalid` events and add tests
  substrate/client/rpc-spec-v2/src/chain_head/test_utils.rs
  substrate/client/rpc-spec-v2/src/transaction/tests/mod.rs
  substrate/client/rpc-spec-v2/src/transaction/tests/setup.rs
  substrate/client/rpc-spec-v2/src/transaction/tests/transaction_tests.rs
  substrate/client/rpc-spec-v2/src/transaction/transaction.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement, T10-tests, D0-easy

#3994 Contracts: Fix legacy uapi
  substrate/frame/contracts/fixtures/contracts/common/src/lib.rs
  substrate/frame/contracts/fixtures/contracts/storage.rs
  substrate/frame/contracts/src/tests.rs
  substrate/frame/contracts/src/wasm/mod.rs
  substrate/frame/contracts/uapi/src/host/wasm32.rs
Labels: R0-silent

#4052 [Backport] Version bumps and prdoc reorg from 1.10.0
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot/node/primitives/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/1.10.0/pr_3190.prdoc
  prdoc/1.10.0/pr_3246.prdoc
  prdoc/1.10.0/pr_3302.prdoc
  prdoc/1.10.0/pr_3341.prdoc
  prdoc/1.10.0/pr_3350.prdoc
  prdoc/1.10.0/pr_3438.prdoc
  prdoc/1.10.0/pr_3471.prdoc
  prdoc/1.10.0/pr_3479.prdoc
  prdoc/1.10.0/pr_3521.prdoc
  prdoc/1.10.0/pr_3580.prdoc
  prdoc/1.10.0/pr_3607.prdoc
  prdoc/1.10.0/pr_3616.prdoc
  prdoc/1.10.0/pr_3654.prdoc
  prdoc/1.10.0/pr_3696.prdoc
  prdoc/1.10.0/pr_3706.prdoc
  prdoc/1.10.0/pr_3714.prdoc
  prdoc/1.10.0/pr_3718.prdoc
  prdoc/1.10.0/pr_3722.prdoc
  prdoc/1.10.0/pr_3738.prdoc
  prdoc/1.10.0/pr_3740.prdoc
  prdoc/1.10.0/pr_3749.prdoc
  prdoc/1.10.0/pr_3754.prdoc
  prdoc/1.10.0/pr_3761.prdoc
  prdoc/1.10.0/pr_3792.prdoc
  prdoc/1.10.0/pr_3795.prdoc
  prdoc/1.10.0/pr_3808.prdoc
  prdoc/1.10.0/pr_3817.prdoc
  prdoc/1.10.0/pr_3835.prdoc
  prdoc/1.10.0/pr_3844.prdoc
  prdoc/1.10.0/pr_3849.prdoc
  prdoc/1.10.0/pr_3850.prdoc
  prdoc/1.10.0/pr_3854.prdoc
  prdoc/1.10.0/pr_3927.prdoc
  prdoc/1.10.0/pr_3950.prdoc
  prdoc/1.10.0/pr_3961.prdoc
Labels: R0-silent, A3-backport, D0-easy

#4057 Convert chainspec to raw
  cumulus/parachains/chain-specs/coretime-kusama-genesis.json
  cumulus/parachains/chain-specs/coretime-kusama.json
  cumulus/parachains/chain-specs/people-kusama-genesis.json
  cumulus/parachains/chain-specs/people-kusama.json
Labels: R0-silent

#3660 Removed `pallet::getter` usage from Polkadot Runtime pallets
  polkadot/roadmap/implementers-guide/src/runtime/disputes.md
  polkadot/roadmap/implementers-guide/src/runtime/scheduler.md
  polkadot/roadmap/implementers-guide/src/runtime/session_info.md
  polkadot/runtime/common/src/assigned_slots/migration.rs
  polkadot/runtime/common/src/assigned_slots/mod.rs
  polkadot/runtime/common/src/auctions.rs
  polkadot/runtime/common/src/claims.rs
  polkadot/runtime/common/src/crowdloan/mod.rs
  polkadot/runtime/common/src/integration_tests.rs
  polkadot/runtime/common/src/paras_registrar/mod.rs
  polkadot/runtime/common/src/paras_sudo_wrapper.rs
  polkadot/runtime/common/src/slots/mod.rs
  polkadot/runtime/common/src/xcm_sender.rs
  polkadot/runtime/parachains/src/assigner_coretime/mod.rs
  polkadot/runtime/parachains/src/assigner_on_demand/migration.rs
  polkadot/runtime/parachains/src/assigner_on_demand/mod.rs
  polkadot/runtime/parachains/src/assigner_parachains.rs
  polkadot/runtime/parachains/src/builder.rs
  polkadot/runtime/parachains/src/configuration.rs
  polkadot/runtime/parachains/src/configuration/tests.rs
  polkadot/runtime/parachains/src/coretime/migration.rs
  polkadot/runtime/parachains/src/disputes.rs
  polkadot/runtime/parachains/src/disputes/slashing.rs
  polkadot/runtime/parachains/src/disputes/slashing/benchmarking.rs
  polkadot/runtime/parachains/src/disputes/tests.rs
  polkadot/runtime/parachains/src/dmp.rs
  polkadot/runtime/parachains/src/dmp/tests.rs
  polkadot/runtime/parachains/src/hrmp.rs
  polkadot/runtime/parachains/src/hrmp/benchmarking.rs
  polkadot/runtime/parachains/src/hrmp/tests.rs
  polkadot/runtime/parachains/src/inclusion/mod.rs
  polkadot/runtime/parachains/src/inclusion/tests.rs
  polkadot/runtime/parachains/src/initializer.rs
  polkadot/runtime/parachains/src/initializer/benchmarking.rs
  polkadot/runtime/parachains/src/initializer/tests.rs
  polkadot/runtime/parachains/src/lib.rs
  polkadot/runtime/parachains/src/paras/benchmarking.rs
  polkadot/runtime/parachains/src/paras/benchmarking/pvf_check.rs
  polkadot/runtime/parachains/src/paras/mod.rs
  polkadot/runtime/parachains/src/paras/tests.rs
  polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs
  polkadot/runtime/parachains/src/paras_inherent/mod.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
  polkadot/runtime/parachains/src/reward_points.rs
  polkadot/runtime/parachains/src/runtime_api_impl/v10.rs
  polkadot/runtime/parachains/src/runtime_api_impl/vstaging.rs
  polkadot/runtime/parachains/src/scheduler.rs
  polkadot/runtime/parachains/src/scheduler/migration.rs
  polkadot/runtime/parachains/src/scheduler/tests.rs
  polkadot/runtime/parachains/src/session_info.rs
  polkadot/runtime/parachains/src/session_info/tests.rs
  polkadot/runtime/parachains/src/shared.rs
  polkadot/runtime/parachains/src/shared/tests.rs
  polkadot/runtime/parachains/src/ump_tests.rs
  polkadot/runtime/parachains/src/util.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_3660.prdoc
Labels: T2-pallets

#3915 Contracts: Only exec parsed code in benchmarks
  prdoc/pr_3915.prdoc
  substrate/frame/contracts/fixtures/contracts/return_with_data.rs
  substrate/frame/contracts/src/benchmarking/call_builder.rs
  substrate/frame/contracts/src/benchmarking/mod.rs
  substrate/frame/contracts/src/exec.rs
  substrate/frame/contracts/src/wasm/mod.rs
  substrate/frame/contracts/src/weights.rs
Labels: T7-smart_contracts

#4051 net/strategy: Log bad peerId from on_validated_block_announce
  polkadot/node/network/statement-distribution/src/v2/cluster.rs
  substrate/client/network/sync/src/strategy/chain_sync.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement, D0-easy

#3789 Contracts: Reuse module when validating
  prdoc/pr_3789.prdoc
  substrate/frame/contracts/src/benchmarking/sandbox.rs
  substrate/frame/contracts/src/tests.rs
  substrate/frame/contracts/src/wasm/mod.rs
  substrate/frame/contracts/src/wasm/prepare.rs
  substrate/frame/contracts/src/weights.rs
Labels: T7-smart_contracts

#4072 Amend chainspecs for `people-westend` and add IBP bootnodes
  cumulus/parachains/chain-specs/people-westend.json
  prdoc/pr_4072.prdoc
Labels: T0-node

#3536 Contracts: Remove ED from base deposit
  substrate/frame/contracts/src/benchmarking/mod.rs
  substrate/frame/contracts/src/lib.rs
  substrate/frame/contracts/src/migration.rs
  substrate/frame/contracts/src/migration/v16.rs
  substrate/frame/contracts/src/storage.rs
  substrate/frame/contracts/src/storage/meter.rs
  substrate/frame/contracts/src/tests.rs
  substrate/frame/contracts/src/weights.rs
Labels: R0-silent

#4065 Fix ClaimQueue case of nothing scheduled on session boundary
  polkadot/runtime/parachains/src/runtime_api_impl/vstaging.rs
Labels: R0-silent, T4-runtime_API

#4070 collation-generation: Avoid using `para_backing_state` if runtime is ancient
  polkadot/node/collation-generation/src/lib.rs
  polkadot/node/collation-generation/src/tests.rs
  prdoc/pr_4070.prdoc
Labels: T9-cumulus

#4074 Fix link check
  .config/lychee.toml
  substrate/client/network/types/src/peer_id.rs
Labels: R0-silent

#3630 Enable mainnet system parachains to use async backing-enabled collator
  cumulus/client/consensus/aura/src/collators/lookahead.rs
  cumulus/polkadot-parachain/src/command.rs
  cumulus/polkadot-parachain/src/service.rs
  prdoc/pr_3630.prdoc
Labels: T14-system_parachains

#4076 [ci] Divide subsystem-regression-tests into 2 jobs
  .gitlab/pipeline/publish.yml
  .gitlab/pipeline/test.yml
Labels: R0-silent

#4017 Remove deprecated `TryRuntime` subcommand
  Cargo.lock
  Cargo.toml
  cumulus/polkadot-parachain/src/cli.rs
  cumulus/polkadot-parachain/src/command.rs
  polkadot/cli/Cargo.toml
  polkadot/cli/src/cli.rs
  polkadot/cli/src/command.rs
  prdoc/pr_4017.prdoc
  substrate/bin/node/cli/Cargo.toml
  substrate/bin/node/cli/src/cli.rs
  substrate/bin/node/cli/src/command.rs
  substrate/utils/frame/try-runtime/cli/Cargo.toml
  substrate/utils/frame/try-runtime/cli/src/block_building_info.rs
  substrate/utils/frame/try-runtime/cli/src/commands/create_snapshot.rs
  substrate/utils/frame/try-runtime/cli/src/commands/execute_block.rs
  substrate/utils/frame/try-runtime/cli/src/commands/fast_forward.rs
  substrate/utils/frame/try-runtime/cli/src/commands/follow_chain.rs
  substrate/utils/frame/try-runtime/cli/src/commands/mod.rs
  substrate/utils/frame/try-runtime/cli/src/commands/offchain_worker.rs
  substrate/utils/frame/try-runtime/cli/src/commands/on_runtime_upgrade.rs
  substrate/utils/frame/try-runtime/cli/src/lib.rs
  substrate/utils/frame/try-runtime/cli/src/parse.rs
  templates/parachain/node/src/cli.rs
  templates/parachain/node/src/command.rs
  templates/solochain/node/Cargo.toml
  templates/solochain/node/src/cli.rs
  templates/solochain/node/src/command.rs
Labels: T0-node

#1817 Use defaultConfig for pallet_contracts
  substrate/frame/contracts/mock-network/src/parachain/contracts_config.rs
  substrate/frame/contracts/src/lib.rs
  substrate/frame/contracts/src/tests.rs
Labels: R0-silent, T1-FRAME

#3721 establish_channel_with_system
  polkadot/runtime/parachains/src/hrmp.rs
  polkadot/runtime/parachains/src/hrmp/benchmarking.rs
  polkadot/runtime/parachains/src/hrmp/tests.rs
  polkadot/runtime/parachains/src/mock.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/runtime_parachains_hrmp.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/runtime_parachains_hrmp.rs
  prdoc/pr_3721.prdoc
Labels: T6-XCM, T14-system_parachains

#4032 Adjust zombienet test resources and logic
  .gitlab/pipeline/zombienet/polkadot.yml
  polkadot/zombienet_tests/elastic_scaling/0001-basic-3cores-6s-blocks.toml
  polkadot/zombienet_tests/elastic_scaling/0001-basic-3cores-6s-blocks.zndsl
  polkadot/zombienet_tests/elastic_scaling/assign-core.js
Labels: R0-silent, T10-tests

#3980 Improve docs of broker pallet
  substrate/frame/broker/src/dispatchable_impls.rs
  substrate/frame/broker/src/lib.rs
Labels: A1-insubstantial, R0-silent

#4027 Runtime API: introduce `candidates_pending_availability`
  cumulus/client/relay-chain-minimal-node/src/blockchain_rpc_client.rs
  cumulus/client/relay-chain-rpc-interface/src/rpc_client.rs
  polkadot/node/core/runtime-api/src/cache.rs
  polkadot/node/core/runtime-api/src/lib.rs
  polkadot/node/core/runtime-api/src/tests.rs
  polkadot/node/subsystem-types/src/messages.rs
  polkadot/node/subsystem-types/src/runtime_client.rs
  polkadot/node/subsystem-util/src/lib.rs
  polkadot/primitives/src/runtime_api.rs
  polkadot/roadmap/implementers-guide/src/runtime-api/candidate-pending-availability.md
  polkadot/roadmap/implementers-guide/src/runtime/inclusion.md
  polkadot/runtime/parachains/src/inclusion/mod.rs
  polkadot/runtime/parachains/src/runtime_api_impl/v10.rs
  polkadot/runtime/parachains/src/runtime_api_impl/vstaging.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_4027.prdoc
Labels: T4-runtime_API, T8-polkadot

#4083 Fix storage migration of `OffendingValidators`
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_2226.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/babe/src/mock.rs
  substrate/frame/beefy/src/mock.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/lib.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
  substrate/frame/fast-unstake/src/mock.rs
  substrate/frame/grandpa/src/mock.rs
  substrate/frame/nomination-pools/benchmarking/src/mock.rs
  substrate/frame/nomination-pools/test-staking/src/mock.rs
  substrate/frame/offences/benchmarking/src/mock.rs
  substrate/frame/root-offences/src/mock.rs
  substrate/frame/session/benchmarking/src/mock.rs
  substrate/frame/staking/CHANGELOG.md
  substrate/frame/staking/src/lib.rs
  substrate/frame/staking/src/migrations.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/tests.rs
Labels: R0-silent

#4095 chore: fix some typos
  bridges/relays/messages/src/message_race_delivery.rs
  bridges/relays/messages/src/message_race_strategy.rs
  bridges/relays/parachains/README.md
Labels: R0-silent

#4040 Synchronize templates
  .github/workflows/sync-templates.yml
Labels: R0-silent, T11-documentation

#4059 Remove redundent logging code
  prdoc/pr_4059.prdoc
  substrate/client/tracing/src/logging/event_format.rs
Labels: T0-node

#4037 Remove `xcm::v3` from `assets-common` nits
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/testing/penpal/src/genesis.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/testing/penpal/src/lib.rs
  cumulus/parachains/integration-tests/emulated/common/src/impls.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/foreign_assets_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/swap.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/foreign_assets_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/swap.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/assets/common/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot/xcm/xcm-builder/src/asset_conversion.rs
  polkadot/xcm/xcm-builder/src/lib.rs
  polkadot/xcm/xcm-builder/src/matches_location.rs
  prdoc/pr_4037.prdoc
Labels: T6-XCM, T9-cumulus

#4080 define block hash provider and default impl using frame_system
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/beefy-mmr/src/mock.rs
  substrate/frame/merkle-mountain-range/src/lib.rs
  substrate/frame/merkle-mountain-range/src/mmr/storage.rs
  substrate/frame/merkle-mountain-range/src/mock.rs
Labels: R0-silent, T15-bridges

#4069 Fix zombienet-bridges-0001-asset-transfer-works
  bridges/testing/environments/rococo-westend/bridges_rococo_westend.sh
  bridges/testing/framework/utils/bridges.sh
  bridges/testing/tests/0002-mandatory-headers-synced-while-idle/run.sh
  docker/dockerfiles/bridges_zombienet_tests_injected.Dockerfile
Labels: R0-silent, T10-tests, T15-bridges

#4111 sc_network_test: Announce only the highest block
  substrate/client/network/test/src/lib.rs
Labels: R0-silent

#3694 Use Github Issue Sync to automate issues in Parachain board
  .github/workflows/auto-add-parachain-issues.yml
Labels: R0-silent

#4006 Deploy `pallet-parameters` to rococo and fix dynamic_params name expand
  Cargo.lock
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/mod.rs
  polkadot/runtime/rococo/src/weights/pallet_parameters.rs
  prdoc/pr_4006.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/parameters/src/tests/mock.rs
  substrate/frame/support/procedural/src/dynamic_params.rs
Labels: T1-FRAME

#4066 Adding Dwellir bootnodes for Coretime Westend, People Westend and Paseo
  cumulus/parachains/chain-specs/coretime-westend.json
  cumulus/parachains/chain-specs/people-westend.json
  polkadot/node/service/chain-specs/paseo.json
Labels: R0-silent

#4112 rococo_contracts: Adds missing migration
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/contracts.rs
Labels: R0-silent

#3852 Prevent accidental change of network-key for active authorities
  polkadot/tests/benchmark_block.rs
  prdoc/pr_3852.prdoc
  substrate/bin/utils/subkey/src/lib.rs
  substrate/client/cli/src/commands/generate_node_key.rs
  substrate/client/cli/src/commands/inspect_node_key.rs
  substrate/client/cli/src/commands/key.rs
  substrate/client/cli/src/commands/mod.rs
  substrate/client/cli/src/config.rs
  substrate/client/cli/src/error.rs
  substrate/client/cli/src/params/node_key_params.rs
Labels: T0-node

#4106 Bridge: slash destination may be an explicit account
  bridges/bin/runtime-common/src/extensions/refund_relayer_extension.rs
  bridges/modules/relayers/src/benchmarking.rs
  bridges/modules/relayers/src/lib.rs
  bridges/modules/relayers/src/stake_adapter.rs
  bridges/primitives/relayers/src/lib.rs
  bridges/primitives/relayers/src/registration.rs
Labels: R0-silent, T15-bridges

#4117 sp-api: Use macro to detect if `frame-metadata` is enabled
  substrate/primitives/api/Cargo.toml
  substrate/primitives/api/proc-macro/Cargo.toml
  substrate/primitives/api/proc-macro/src/decl_runtime_apis.rs
  substrate/primitives/api/proc-macro/src/impl_runtime_apis.rs
  substrate/primitives/api/proc-macro/src/lib.rs
  substrate/primitives/api/proc-macro/src/runtime_metadata.rs
  substrate/primitives/api/proc-macro/src/utils.rs
  substrate/primitives/api/src/lib.rs
Labels: R0-silent

#4089 pallet_broker: Support renewing leases expired in a previous period
  Cargo.lock
  prdoc/pr_4089.prdoc
  substrate/frame/broker/Cargo.toml
  substrate/frame/broker/src/mock.rs
  substrate/frame/broker/src/tests.rs
  substrate/frame/broker/src/tick_impls.rs
Labels: T2-pallets

#3431 added script to require a review post push
  .github/workflows/review-trigger.yml
Labels: R0-silent

#4124 logging(fix): Use the proper log target for logging
  substrate/client/tracing/src/logging/event_format.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement, D0-easy

#4099 [pallet-broker] add tests for renewing leases
  substrate/frame/broker/src/tests.rs
Labels: R0-silent, T2-pallets

#4118 pallet assets: Fix errors
  Cargo.lock
  prdoc/pr_4118.prdoc
  substrate/frame/assets/Cargo.toml
  substrate/frame/assets/src/functions.rs
  substrate/frame/assets/src/lib.rs
Labels: T2-pallets

#4148 move fragment_tree module to its own folder
  polkadot/node/core/prospective-parachains/src/fragment_tree/mod.rs
  polkadot/node/core/prospective-parachains/src/fragment_tree/tests.rs
Labels: R0-silent, T8-polkadot

#4152 added check to ensure there are approvals
  .github/workflows/review-trigger.yml
Labels: R0-silent

#4137 Update review-trigger.yml
  .github/workflows/review-trigger.yml
Labels: R0-silent

#3998 [prdoc] Update docs
  docs/contributor/prdoc.md
  prdoc/schema_user.json
Labels: R0-silent

#4135 grandpa: Send neighbor packet to lightclients with every finalized head
  substrate/client/consensus/grandpa/src/communication/gossip.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement, D0-easy

#4162 Adjust `xcm-bridge-hub-router`'s `SendXcm::validate` behavior for `NotApplicable`
  bridges/modules/xcm-bridge-hub-router/src/lib.rs
  bridges/modules/xcm-bridge-hub-router/src/mock.rs
Labels: R0-silent, T6-XCM, T15-bridges

#3455 XCM coretime region transfers
  Cargo.lock
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/xcm_config.rs
  polkadot/xcm/pallet-xcm/src/benchmarking.rs
  prdoc/pr_3455.prdoc
  substrate/frame/broker/Cargo.toml
  substrate/frame/broker/src/benchmarking.rs
  substrate/frame/broker/src/dispatchable_impls.rs
  substrate/frame/broker/src/lib.rs
  substrate/frame/broker/src/migration.rs
  substrate/frame/broker/src/nonfungible_impl.rs
  substrate/frame/broker/src/tests.rs
  substrate/frame/broker/src/types.rs
  substrate/frame/broker/src/utility_impls.rs
Labels: T6-XCM, T2-pallets

#3667 chainHead: Report unique hashes for pruned blocks
  Cargo.lock
  substrate/client/rpc-spec-v2/Cargo.toml
  substrate/client/rpc-spec-v2/src/chain_head/chain_head.rs
  substrate/client/rpc-spec-v2/src/chain_head/chain_head_follow.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
Labels: A1-insubstantial, R0-silent, I2-bug, D1-medium

#4146 Improve doc for pallet macro and config macro
  substrate/frame/support/src/lib.rs
Labels: R0-silent

#3251 Asset Conversion: Pool Touch Call
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_asset_conversion.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_asset_conversion.rs
  prdoc/pr_3251.prdoc
  substrate/frame/asset-conversion/src/benchmarking.rs
  substrate/frame/asset-conversion/src/lib.rs
  substrate/frame/asset-conversion/src/weights.rs
  substrate/frame/assets/src/lib.rs
Labels: T2-pallets

#4060 Fix nostd build of several crates
  cumulus/pallets/session-benchmarking/src/inner.rs
  cumulus/pallets/session-benchmarking/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/Cargo.toml
  cumulus/primitives/parachain-inherent/Cargo.toml
  polkadot/primitives/Cargo.toml
  polkadot/runtime/parachains/Cargo.toml
  polkadot/xcm/xcm-executor/integration-tests/src/lib.rs
  prdoc/pr_4060.prdoc
  substrate/frame/Cargo.toml
  substrate/frame/atomic-swap/src/lib.rs
  substrate/frame/election-provider-support/benchmarking/src/inner.rs
  substrate/frame/election-provider-support/benchmarking/src/lib.rs
  substrate/frame/examples/dev-mode/src/lib.rs
  substrate/frame/examples/offchain-worker/Cargo.toml
  substrate/frame/indices/Cargo.toml
  substrate/frame/nomination-pools/Cargo.toml
  substrate/frame/nomination-pools/benchmarking/src/inner.rs
  substrate/frame/nomination-pools/benchmarking/src/lib.rs
  substrate/frame/offences/benchmarking/src/inner.rs
  substrate/frame/offences/benchmarking/src/lib.rs
  substrate/frame/offences/benchmarking/src/mock.rs
  substrate/frame/root-offences/Cargo.toml
  substrate/frame/root-offences/src/lib.rs
  substrate/frame/session/benchmarking/src/inner.rs
  substrate/frame/session/benchmarking/src/lib.rs
  substrate/frame/src/lib.rs
  substrate/frame/system/benchmarking/src/inner.rs
  substrate/frame/system/benchmarking/src/lib.rs
  substrate/frame/try-runtime/src/inner.rs
  substrate/frame/try-runtime/src/lib.rs
  substrate/primitives/consensus/babe/Cargo.toml
  substrate/primitives/core/Cargo.toml
  substrate/primitives/session/Cargo.toml
  substrate/primitives/transaction-storage-proof/Cargo.toml
Labels: T2-pallets

#4158 Contracts: Refactor test builder
  substrate/frame/contracts/mock-network/src/lib.rs
  substrate/frame/contracts/mock-network/src/tests.rs
  substrate/frame/contracts/src/lib.rs
  substrate/frame/contracts/src/test_utils.rs
  substrate/frame/contracts/src/test_utils/builder.rs
  substrate/frame/contracts/src/tests.rs
  substrate/frame/contracts/src/tests/builder.rs
Labels: R0-silent, T7-smart_contracts

#3867 Remove NotConcrete error
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/xcm-executor/src/traits/asset_transfer.rs
Labels: R0-silent

#4178 [ci] Run `test-linux-stable-int` on self-hosted GitHub Runners
  .github/workflows/test-github-actions.yml
Labels: R0-silent

#4142 Release crates io v1.8.0 staking backport
  Cargo.lock
  prdoc/pr_3639.prdoc
  substrate/frame/staking/src/ledger.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/tests.rs
Labels: R0-silent, A3-backport

#4077 [ci] Update ci image with rust 1.77 and 2024-04-10
  .github/workflows/fmt-check.yml
  .github/workflows/test-github-actions.yml
  .gitlab-ci.yml
  docs/contributor/container.md
  docs/sdk/src/reference_docs/development_environment_advice.rs
  polkadot/node/core/runtime-api/src/cache.rs
  polkadot/node/core/runtime-api/src/lib.rs
  polkadot/node/network/approval-distribution/src/lib.rs
  polkadot/node/network/collator-protocol/src/validator_side/mod.rs
  polkadot/node/network/dispute-distribution/src/sender/send_task.rs
  polkadot/runtime/parachains/src/inclusion/mod.rs
  substrate/client/consensus/aura/src/lib.rs
  substrate/client/consensus/grandpa/src/communication/tests.rs
  substrate/frame/contracts/fixtures/build.rs
  substrate/frame/support/test/tests/benchmark_ui/invalid_origin.stderr
  substrate/frame/support/test/tests/construct_runtime_ui/deprecated_where_block.stderr
  substrate/frame/support/test/tests/construct_runtime_ui/number_of_pallets_exceeds_tuple_size.stderr
  substrate/frame/support/test/tests/construct_runtime_ui/pallet_error_too_large.stderr
  substrate/frame/support/test/tests/construct_runtime_ui/undefined_call_part.stderr
  substrate/frame/support/test/tests/construct_runtime_ui/undefined_validate_unsigned_part.stderr
  substrate/frame/support/test/tests/derive_no_bound.rs
  substrate/frame/support/test/tests/pallet_ui/call_argument_invalid_bound.stderr
  substrate/frame/support/test/tests/pallet_ui/call_argument_invalid_bound_2.stderr
  substrate/frame/support/test/tests/pallet_ui/call_argument_invalid_bound_3.stderr
  substrate/frame/support/test/tests/pallet_ui/dev_mode_without_arg_max_encoded_len.stderr
  substrate/frame/support/test/tests/pallet_ui/event_field_not_member.stderr
  substrate/frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr
  substrate/frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen_unnamed.stderr
  substrate/frame/support/test/tests/pallet_ui/storage_info_unsatisfied.stderr
  substrate/frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.stderr
  substrate/primitives/api/test/tests/ui/impl_incorrect_method_signature.stderr
  substrate/primitives/api/test/tests/ui/type_reference_in_impl_runtime_apis_call.stderr
Labels: R0-silent

#4179 Improve changelog in the release notes
  .github/workflows/release-30_publish_release_draft.yml
  scripts/release/build-changelogs.sh
  scripts/release/templates/audience.md.tera
Labels: R0-silent

#4196 [ci] Use ci-unified reference
  .gitlab-ci.yml
Labels: R0-silent

#4103 chain-selection: allow reverting current block
  polkadot/node/core/chain-selection/src/lib.rs
  polkadot/node/core/chain-selection/src/tests.rs
  polkadot/node/core/chain-selection/src/tree.rs
Labels: R0-silent, T8-polkadot

#4200 [ci] Use native git cli in cargo
  .github/workflows/test-github-actions.yml
Labels: R0-silent

#4192 Fix next_retry busy waiting on first retry
  polkadot/node/network/statement-distribution/src/v2/requests.rs
  polkadot/node/network/statement-distribution/src/v2/tests/requests.rs
Labels: R0-silent, T0-node

#4050 tx: Remove tx_broadcast transaction from the pool
  substrate/client/rpc-spec-v2/src/transaction/tests/transaction_broadcast_tests.rs
  substrate/client/rpc-spec-v2/src/transaction/transaction_broadcast.rs
Labels: A0-needs_burnin, R0-silent, I5-enhancement, D0-easy

#4168 chainHead: Stabilize chainHead to version 1
  prdoc/pr_4168.prdoc
  substrate/client/rpc-spec-v2/src/chain_head/api.rs
  substrate/client/rpc-spec-v2/src/chain_head/subscription/inner.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
Labels: A1-insubstantial, I5-enhancement, T3-RPC_API, D0-easy

#3772 rpc-v2: Limit transactionBroadcast calls to 16
  substrate/client/rpc-spec-v2/src/transaction/api.rs
  substrate/client/rpc-spec-v2/src/transaction/tests/setup.rs
  substrate/client/rpc-spec-v2/src/transaction/tests/transaction_broadcast_tests.rs
  substrate/client/rpc-spec-v2/src/transaction/transaction.rs
  substrate/client/rpc-spec-v2/src/transaction/transaction_broadcast.rs
  substrate/client/service/src/builder.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement, D0-easy

#4172 Use higher priority for PVF preparation in dispute/approval context
  polkadot/node/core/candidate-validation/src/lib.rs
  polkadot/node/core/candidate-validation/src/tests.rs
  polkadot/node/core/pvf/src/host.rs
  polkadot/node/core/pvf/src/priority.rs
Labels: R0-silent, I9-optimisation

#4208 Fixed GrandpaConsensusLogReader::find_scheduled_change
  bridges/primitives/header-chain/src/lib.rs
Labels: R0-silent, T15-bridges

#4209 fixed GrandpaConsensusLogReader::find_scheduled_change
  Cargo.lock
  bridges/primitives/header-chain/src/lib.rs
  prdoc/pr_4209.prdoc
Labels: T15-bridges

#4071 Pvf refactor execute worker errors follow up
  Cargo.lock
  polkadot/node/core/pvf/Cargo.toml
  polkadot/node/core/pvf/common/Cargo.toml
  polkadot/node/core/pvf/common/src/error.rs
  polkadot/node/core/pvf/common/src/execute.rs
  polkadot/node/core/pvf/common/src/lib.rs
  polkadot/node/core/pvf/common/src/pvf.rs
  polkadot/node/core/pvf/common/src/worker/mod.rs
  polkadot/node/core/pvf/execute-worker/src/lib.rs
  polkadot/node/core/pvf/prepare-worker/src/lib.rs
  polkadot/node/core/pvf/src/execute/queue.rs
  polkadot/node/core/pvf/src/execute/worker_interface.rs
  polkadot/node/core/pvf/src/host.rs
Labels: R0-silent, T0-node

#3889 Allow privileged virtual bond in Staking pallet
  prdoc/pr_3889.prdoc
  substrate/frame/nomination-pools/src/mock.rs
  substrate/frame/staking/src/ledger.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/slashing.rs
  substrate/frame/staking/src/tests.rs
  substrate/primitives/staking/src/lib.rs
Labels: T1-FRAME, T2-pallets

#4223 Fix case in type in macro generation
  substrate/frame/support/procedural/src/runtime/expand/mod.rs
Labels: R0-silent

#4205 ci: disallow westend migration failure
  .gitlab/pipeline/check.yml
  polkadot/runtime/westend/src/lib.rs
Labels: R0-silent

#4143 Release crates io v1.6.0 staking backport
  Cargo.lock
  prdoc/pr_3639.prdoc
  substrate/frame/staking/src/ledger.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/tests.rs
Labels: R0-silent, A3-backport

#4144 Release crates io v1.5.0 staking backport
  Cargo.lock
  prdoc/pr_3639.prdoc
  substrate/frame/staking/src/ledger.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/tests.rs
Labels: R0-silent, A3-backport

#4145 Release crates io v1.4.0 staking backport
  prdoc/pr_3639.prdoc
  substrate/frame/staking/src/ledger.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/tests.rs
Labels: R0-silent, A3-backport

#4235 [xcm] Assets: sort after `prepend_with`
  polkadot/xcm/src/v3/multiasset.rs
  polkadot/xcm/src/v4/asset.rs
Labels: R0-silent, T6-XCM

#4238 Sanitize `UniversalLocation` witth `GlobalConsensus` + XCM small nits and improvements
  Cargo.lock
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/starters/shell/src/xcm_config.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot/xcm/pallet-xcm-benchmarks/Cargo.toml
  polkadot/xcm/pallet-xcm-benchmarks/src/fungible/mock.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/mock.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/mock.rs
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/xcm-builder/src/universal_exports.rs
  polkadot/xcm/xcm-builder/tests/mock/mod.rs
  polkadot/xcm/xcm-simulator/example/src/parachain.rs
  polkadot/xcm/xcm-simulator/example/src/relay_chain.rs
  polkadot/xcm/xcm-simulator/fuzzer/src/parachain.rs
  polkadot/xcm/xcm-simulator/fuzzer/src/relay_chain.rs
  substrate/frame/contracts/mock-network/src/parachain.rs
  substrate/frame/contracts/mock-network/src/relay_chain.rs
  templates/parachain/runtime/src/configs/xcm_config.rs
Labels: R0-silent, T6-XCM

#4239 Added prdoc for 4208
  prdoc/pr_4208.prdoc
Labels: R0-silent, T15-bridges

#4243 [subsystem-benchmark] Fix results filename for approval-voting benches
  polkadot/node/core/approval-voting/benches/approval-voting-regression-bench.rs
Labels: R0-silent, T12-benchmarks

#4240 Use default branch of `psvm` when synchronizing templates
  .github/workflows/sync-templates.yml
Labels: R0-silent, T11-documentation

#4177 wasm-builder: Make it easier to build a WASM binary
  cumulus/parachains/runtimes/assets/asset-hub-rococo/build.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/build.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/build.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/build.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/build.rs
  cumulus/parachains/runtimes/testing/penpal/build.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/build.rs
  cumulus/test/runtime/build.rs
  polkadot/runtime/rococo/build.rs
  polkadot/runtime/test-runtime/build.rs
  polkadot/runtime/westend/build.rs
  prdoc/pr_4177.prdoc
  substrate/utils/wasm-builder/src/builder.rs
  substrate/utils/wasm-builder/src/lib.rs
  templates/minimal/runtime/build.rs
  templates/parachain/runtime/build.rs
  templates/solochain/runtime/build.rs
Labels: T0-node

#4199 [testnets] remove XCM SafeCallFilter for chains using Weights::v3
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/people/people-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/people/people-westend/src/xcm_config.rs
  prdoc/pr_4199.prdoc
Labels: T6-XCM

#4250 Add metric for time spent waiting in the execution queue
  polkadot/node/core/pvf/src/execute/queue.rs
  polkadot/node/core/pvf/src/metrics.rs
Labels: R0-silent

#4236 Add `validate_xcm_nesting` to the `ParentAsUmp` and `ChildParachainRouter`
  cumulus/pallets/xcmp-queue/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/primitives/utility/src/lib.rs
  polkadot/runtime/common/src/integration_tests.rs
  polkadot/runtime/common/src/xcm_sender.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/fungible/benchmarking.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/fungible/mock.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/mock.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/lib.rs
  polkadot/xcm/src/lib.rs
Labels: R0-silent, T6-XCM

#4189 parachains_coretime: Expose `MaxXCMTransactWeight`
  polkadot/runtime/parachains/src/coretime/migration.rs
  polkadot/runtime/parachains/src/coretime/mod.rs
  polkadot/runtime/parachains/src/mock.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_4189.prdoc
Labels: T8-polkadot

#4253 chore: fix some typos
  polkadot/runtime/common/src/crowdloan/mod.rs
  polkadot/runtime/common/src/paras_registrar/mod.rs
  polkadot/runtime/parachains/src/inclusion/mod.rs
  polkadot/runtime/parachains/src/paras/mod.rs
  polkadot/runtime/parachains/src/paras_inherent/mod.rs
Labels: R0-silent

#4186 Ensure outbound XCMs are decodable with limits + add `EnsureDecodableXcm` router (for testing purposes)
  Cargo.lock
  polkadot/runtime/test-runtime/Cargo.toml
  polkadot/runtime/test-runtime/constants/Cargo.toml
  polkadot/xcm/pallet-xcm-benchmarks/src/fungible/mock.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/mock.rs
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/xcm-builder/src/lib.rs
  polkadot/xcm/xcm-builder/src/routing.rs
  polkadot/xcm/xcm-builder/src/tests/mock.rs
  polkadot/xcm/xcm-builder/tests/mock/mod.rs
  polkadot/xcm/xcm-simulator/example/src/parachain.rs
  polkadot/xcm/xcm-simulator/example/src/relay_chain.rs
Labels: R0-silent, T6-XCM

#4229 Fix Stuck Collator Funds
  cumulus/pallets/collator-selection/Cargo.toml
  cumulus/pallets/collator-selection/src/lib.rs
  cumulus/pallets/collator-selection/src/migration.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  prdoc/pr_4229.prdoc
Labels: I2-bug, T2-pallets, T14-system_parachains
