Repository paritytech/polkadot-sdk, pull requests merged in 2024-12, with the labels that each got.

#6608 [pallet-revive] eth-prc fix geth diff
  Cargo.lock
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_6608.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/mock-network/src/tests.rs
  substrate/frame/revive/rpc/Cargo.toml
  substrate/frame/revive/rpc/examples/js/abi/errorTester.ts
  substrate/frame/revive/rpc/examples/js/abi/event.json
  substrate/frame/revive/rpc/examples/js/abi/event.ts
  substrate/frame/revive/rpc/examples/js/abi/piggyBank.json
  substrate/frame/revive/rpc/examples/js/abi/piggyBank.ts
  substrate/frame/revive/rpc/examples/js/abi/revert.json
  substrate/frame/revive/rpc/examples/js/bun.lockb
  substrate/frame/revive/rpc/examples/js/contracts/.solhint.json
  substrate/frame/revive/rpc/examples/js/contracts/ErrorTester.sol
  substrate/frame/revive/rpc/examples/js/contracts/PiggyBank.sol
  substrate/frame/revive/rpc/examples/js/package.json
  substrate/frame/revive/rpc/examples/js/pvm/errorTester.polkavm
  substrate/frame/revive/rpc/examples/js/src/balance.ts
  substrate/frame/revive/rpc/examples/js/src/build-contracts.ts
  substrate/frame/revive/rpc/examples/js/src/event.ts
  substrate/frame/revive/rpc/examples/js/src/geth-diff-setup.ts
  substrate/frame/revive/rpc/examples/js/src/geth-diff.test.ts
  substrate/frame/revive/rpc/examples/js/src/lib.ts
  substrate/frame/revive/rpc/examples/js/src/piggy-bank.ts
  substrate/frame/revive/rpc/examples/js/src/revert.ts
  substrate/frame/revive/rpc/examples/js/src/transfer.ts
  substrate/frame/revive/rpc/examples/js/types/ethers-contracts/Event.ts
  substrate/frame/revive/rpc/examples/js/types/ethers-contracts/PiggyBank.ts
  substrate/frame/revive/rpc/examples/js/types/ethers-contracts/Revert.ts
  substrate/frame/revive/rpc/examples/js/types/ethers-contracts/common.ts
  substrate/frame/revive/rpc/examples/js/types/ethers-contracts/factories/Event__factory.ts
  substrate/frame/revive/rpc/examples/js/types/ethers-contracts/factories/Revert__factory.ts
  substrate/frame/revive/rpc/examples/js/types/ethers-contracts/factories/index.ts
  substrate/frame/revive/rpc/examples/js/types/ethers-contracts/index.ts
  substrate/frame/revive/rpc/revive_chain.metadata
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/rpc/src/lib.rs
  substrate/frame/revive/rpc/src/rpc_methods_gen.rs
  substrate/frame/revive/rpc/src/subxt_client.rs
  substrate/frame/revive/rpc/src/tests.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/evm/api/rlp_codec.rs
  substrate/frame/revive/src/evm/api/rpc_types.rs
  substrate/frame/revive/src/evm/api/rpc_types_gen.rs
  substrate/frame/revive/src/evm/runtime.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/primitives.rs
  substrate/frame/revive/src/storage/meter.rs
  substrate/frame/revive/src/test_utils/builder.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/tests/test_debug.rs
  substrate/frame/revive/src/wasm/mod.rs
Labels: R0-silent, T7-smart_contracts

#6294 migrate pallet-session-benchmarking to bench V2 syntax
  substrate/frame/session/benchmarking/src/inner.rs
  substrate/frame/session/benchmarking/src/mock.rs
Labels: R0-silent, T2-pallets, T12-benchmarks

#6300 migrate pallet-offences-benchmarking to benchmark v2 syntax
  substrate/frame/offences/benchmarking/src/inner.rs
  substrate/frame/offences/benchmarking/src/mock.rs
Labels: R0-silent, T2-pallets, T12-benchmarks

#6674 Backport #5887 to `stable2407`
  polkadot/runtime/parachains/Cargo.toml
  polkadot/runtime/parachains/src/configuration.rs
  polkadot/runtime/parachains/src/configuration/tests.rs
  prdoc/pr_6674.prdoc
Labels: A3-backport

#6653 [stable2412] Backport #6454
  prdoc/pr_6588.prdoc
  substrate/client/rpc-servers/src/lib.rs
Labels: A3-backport

#6709 backport/rpc-v2: Implement `archive_unstable_storageDiff` (stable2412)
  Cargo.lock
  prdoc/pr_5997.prdoc
  substrate/client/rpc-spec-v2/Cargo.toml
  substrate/client/rpc-spec-v2/src/archive/api.rs
  substrate/client/rpc-spec-v2/src/archive/archive.rs
  substrate/client/rpc-spec-v2/src/archive/archive_storage.rs
  substrate/client/rpc-spec-v2/src/archive/tests.rs
  substrate/client/rpc-spec-v2/src/common/events.rs
  substrate/client/rpc-spec-v2/src/common/storage.rs
  substrate/client/service/src/builder.rs
Labels: A3-backport

#6708 Rococo People <> Bulletin bridge fixes
  bridges/chains/chain-polkadot-bulletin/src/lib.rs
  bridges/relays/utils/src/initialize.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_bulletin_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/genesis_config_presets.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
Labels: R0-silent, T15-bridges

#6734 [Release/CICD] Re-worked Create Release Draft flow
  .github/scripts/common/lib.sh
  .github/scripts/release/release_lib.sh
  .github/workflows/release-10_branchoff-stable.yml
  .github/workflows/release-11_rc-automation.yml
  .github/workflows/release-20_build-rc.yml
  .github/workflows/release-30_publish_release_draft.yml
  .github/workflows/release-50_publish-docker.yml
  .github/workflows/release-reusable-rc-buid.yml
  .github/workflows/release-srtool.yml
Labels: R0-silent, A4-needs-backport

#6735 pallet-revive-fixtures: Try not to re-create fixture dir
  substrate/frame/revive/fixtures/build.rs
Labels: R0-silent

#6583 Bump Westend AH
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_6583.prdoc
Labels: R0-silent, T7-smart_contracts

#6556 Add publish-check-compile workflow
  .github/workflows/publish-check-compile.yml
Labels: A1-insubstantial, R0-silent

#6405 `fatxpool`: handling limits and priorities improvements
  prdoc/pr_6405.prdoc
  substrate/client/transaction-pool/benches/basics.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/dropped_watcher.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/import_notification_sink.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/multi_view_listener.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/revalidation_worker.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/tx_mem_pool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/view.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs
  substrate/client/transaction-pool/src/graph/base_pool.rs
  substrate/client/transaction-pool/src/graph/listener.rs
  substrate/client/transaction-pool/src/graph/pool.rs
  substrate/client/transaction-pool/src/graph/ready.rs
  substrate/client/transaction-pool/src/graph/rotator.rs
  substrate/client/transaction-pool/src/graph/validated_pool.rs
  substrate/client/transaction-pool/src/graph/watcher.rs
  substrate/client/transaction-pool/src/lib.rs
  substrate/client/transaction-pool/src/single_state_txpool/revalidation.rs
  substrate/client/transaction-pool/src/single_state_txpool/single_state_txpool.rs
  substrate/client/transaction-pool/tests/fatp.rs
  substrate/client/transaction-pool/tests/fatp_common/mod.rs
  substrate/client/transaction-pool/tests/fatp_limits.rs
  substrate/client/transaction-pool/tests/fatp_prios.rs
  substrate/client/transaction-pool/tests/pool.rs
Labels: R0-silent, T0-node

#6743 umbrella: Remove `pallet-revive-fixtures`
  Cargo.lock
  prdoc/pr_6743.prdoc
  substrate/frame/revive/fixtures/Cargo.toml
  umbrella/Cargo.toml
  umbrella/src/lib.rs
Labels: R0-silent

#6748 [Release|CI/CD] Add pipeline to promote release candidate from rcX to final in S3
  .github/scripts/common/lib.sh
  .github/scripts/release/release_lib.sh
  .github/workflows/release-31_promote-rc-to-final.yml
  .github/workflows/release-reusable-promote-to-final.yml
  .github/workflows/release-reusable-rc-buid.yml
  .github/workflows/release-reusable-s3-upload.yml
Labels: R0-silent, A4-needs-backport

#6753 [stable2412] Backport backport #6748
  .github/scripts/common/lib.sh
  .github/scripts/release/release_lib.sh
  .github/workflows/release-31_promote-rc-to-final.yml
  .github/workflows/release-reusable-promote-to-final.yml
  .github/workflows/release-reusable-rc-buid.yml
  .github/workflows/release-reusable-s3-upload.yml
Labels: R0-silent, A3-backport

#6749 Disable flaky tests reported in #6574/#6644
  .gitlab/pipeline/zombienet/polkadot.yml
Labels: R0-silent, T10-tests

#6742 chore: Update litep2p to v0.8.3
  Cargo.lock
  Cargo.toml
  prdoc/pr_6742.prdoc
  substrate/client/network/src/litep2p/mod.rs
Labels: T0-node, I5-enhancement

#6754 [CI/CD] Fix permissions issue in the backport to stable flow
  .github/workflows/command-backport.yml
Labels: R0-silent, A4-needs-backport

#6419 wasm-builder: Use riscv32emac-unknown-none-polkavm.json target
  Cargo.lock
  Cargo.toml
  prdoc/pr_6419.prdoc
  substrate/utils/wasm-builder/src/builder.rs
  substrate/utils/wasm-builder/src/lib.rs
  substrate/utils/wasm-builder/src/prerequisites.rs
  substrate/utils/wasm-builder/src/wasm_project.rs
Labels: T0-node

#6762 ci: skip check-semver in master and merge queue
  .github/workflows/check-semver.yml
Labels: R0-silent

#6636 Optimize initialization of networking protocol benchmarks
  prdoc/pr_6636.prdoc
  substrate/client/network/benches/notifications_protocol.rs
  substrate/client/network/benches/request_response_protocol.rs
Labels: R0-silent, T12-benchmarks

#6760 chainHead: Always report discarded items for storage operations
  prdoc/pr_6760.prdoc
  substrate/client/rpc-spec-v2/src/chain_head/chain_head.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
Labels: I5-enhancement, T3-RPC_API, A4-needs-backport

#6090 bump zombienet and re-enable test
  .gitlab/pipeline/zombienet/parachain-template.yml
Labels: R0-silent, T10-tests

#6765 [CI/CD] Add release environment to the backport job
  .github/workflows/command-backport.yml
Labels: R0-silent

#6643 Added fallback_max_weight to Transact for sending messages to V4 chains
  bridges/snowbridge/pallets/inbound-queue/src/test.rs
  bridges/snowbridge/primitives/router/src/inbound/mod.rs
  cumulus/parachains/integration-tests/emulated/common/src/xcm_helpers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/transact.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/transact.rs
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/src/tests/fellowship.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/governance.rs
  cumulus/parachains/pallets/ping/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/coretime.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/coretime.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/test-utils/src/lib.rs
  polkadot/runtime/parachains/src/coretime/mod.rs
  polkadot/runtime/parachains/src/mock.rs
  polkadot/runtime/rococo/src/impls.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/xcm/mod.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/impls.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/xcm/mod.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  polkadot/xcm/src/v4/mod.rs
  polkadot/xcm/src/v5/mod.rs
  polkadot/xcm/src/v5/traits.rs
  polkadot/xcm/xcm-builder/src/tests/transacting.rs
  polkadot/xcm/xcm-executor/integration-tests/src/lib.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  polkadot/xcm/xcm-simulator/example/src/tests.rs
  prdoc/pr_6643.prdoc
Labels: T6-XCM, A4-needs-backport

#6768 `basic-authorship`: debug level is now less spammy
  prdoc/pr_6768.prdoc
  substrate/client/basic-authorship/src/basic_authorship.rs
  substrate/client/proposer-metrics/src/lib.rs
Labels: R0-silent, T0-node

#6777 Update weights for westend pallet balances
  polkadot/runtime/westend/src/weights/pallet_balances.rs
Labels: R0-silent

#6566 XCM V5 - SetHints instruction
  Cargo.lock
  bridges/snowbridge/pallets/inbound-queue/src/test.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/set_asset_claimer.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  polkadot/runtime/rococo/src/weights/xcm/mod.rs
  polkadot/runtime/rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  polkadot/runtime/westend/src/weights/xcm/mod.rs
  polkadot/runtime/westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  polkadot/xcm/procedural/Cargo.toml
  polkadot/xcm/procedural/src/builder_pattern.rs
  polkadot/xcm/procedural/src/enum_variants.rs
  polkadot/xcm/procedural/src/lib.rs
  polkadot/xcm/procedural/tests/builder_pattern.rs
  polkadot/xcm/procedural/tests/enum_variants.rs
  polkadot/xcm/procedural/tests/ui/builder_pattern/loads_holding_no_operands.stderr
  polkadot/xcm/procedural/tests/ui/builder_pattern/unexpected_attribute.stderr
  polkadot/xcm/procedural/tests/ui/builder_pattern/unpaid_execution_named_fields.stderr
  polkadot/xcm/src/v4/mod.rs
  polkadot/xcm/src/v5/mod.rs
  polkadot/xcm/xcm-builder/src/barriers.rs
  polkadot/xcm/xcm-builder/src/tests/barriers.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  polkadot/xcm/xcm-executor/src/tests/set_asset_claimer.rs
  prdoc/pr_6566.prdoc
Labels: T6-XCM

#6794 [CI/CD]Revert the token changes in backport flow
  .github/workflows/command-backport.yml
Labels: R0-silent

#6690 Fix `Possible bug: Vote import failed` after aggression is enabled
  polkadot/node/network/approval-distribution/src/lib.rs
  polkadot/node/network/protocol/src/grid_topology.rs
  prdoc/pr_6690.prdoc
Labels: T8-polkadot, A4-needs-backport

#6796 pallet-revive: Remove unused dependencies
  Cargo.lock
  prdoc/pr_6796.prdoc
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/src/benchmarking/call_builder.rs
  substrate/frame/revive/src/benchmarking/mod.rs
Labels: R0-silent

#6778 Added fallback_max_weight to Transact for sending messages to V4 chai…
  bridges/snowbridge/pallets/inbound-queue/src/test.rs
  bridges/snowbridge/primitives/router/src/inbound/mod.rs
  cumulus/parachains/integration-tests/emulated/common/src/xcm_helpers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/transact.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/transact.rs
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/src/tests/fellowship.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/governance.rs
  cumulus/parachains/pallets/ping/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/coretime.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/coretime.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/test-utils/src/lib.rs
  polkadot/runtime/parachains/src/coretime/mod.rs
  polkadot/runtime/parachains/src/mock.rs
  polkadot/runtime/rococo/src/impls.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/xcm/mod.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/impls.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/xcm/mod.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  polkadot/xcm/src/v4/mod.rs
  polkadot/xcm/src/v5/mod.rs
  polkadot/xcm/src/v5/traits.rs
  polkadot/xcm/xcm-builder/src/tests/transacting.rs
  polkadot/xcm/xcm-executor/integration-tests/src/lib.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  polkadot/xcm/xcm-simulator/example/src/tests.rs
  prdoc/6778.prdoc
Labels: T6-XCM

#4834 xcm-executor: take transport fee from transferred assets if necessary
  bridges/snowbridge/primitives/router/src/inbound/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/transact.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/register_bridged_assets.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/send_xcm.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/register_bridged_assets.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/send_xcm.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/transact.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  prdoc/pr_4834.prdoc
Labels: T6-XCM, A4-needs-backport

#6792 Add fallback_max_weight to snowbridge Transact
  bridges/snowbridge/pallets/inbound-queue/src/test.rs
  bridges/snowbridge/primitives/router/src/inbound/mod.rs
  prdoc/pr_6792.prdoc
Labels: T6-XCM

#6782 Add fallback_weight to the log
  polkadot/xcm/src/v4/mod.rs
Labels: R0-silent, T6-XCM

#6781 Bridges - revert-back congestion mechanism
  Cargo.lock
  bridges/chains/chain-asset-hub-rococo/Cargo.toml
  bridges/chains/chain-asset-hub-rococo/src/lib.rs
  bridges/chains/chain-asset-hub-westend/Cargo.toml
  bridges/chains/chain-asset-hub-westend/src/lib.rs
  bridges/modules/xcm-bridge-hub-router/src/benchmarking.rs
  bridges/modules/xcm-bridge-hub-router/src/lib.rs
  bridges/modules/xcm-bridge-hub-router/src/mock.rs
  bridges/modules/xcm-bridge-hub-router/src/weights.rs
  bridges/modules/xcm-bridge-hub/Cargo.toml
  bridges/modules/xcm-bridge-hub/src/exporter.rs
  bridges/modules/xcm-bridge-hub/src/lib.rs
  bridges/modules/xcm-bridge-hub/src/mock.rs
  bridges/primitives/xcm-bridge-hub/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_xcm_bridge_hub_router.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_xcm_bridge_hub_router.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases_over_bridge.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_westend_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/bridge_to_rococo_config.rs
  prdoc/pr_6781.prdoc
Labels: T15-bridges, A4-needs-backport

#5899 Remove AccountKeyring everywhere
  Cargo.lock
  bridges/snowbridge/pallets/inbound-queue/src/test.rs
  bridges/snowbridge/runtime/test-common/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/snowbridge.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/snowbridge.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/from_grandpa_chain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/from_parachain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/helpers.rs
  cumulus/test/client/src/lib.rs
  docs/sdk/packages/guides/first-runtime/src/lib.rs
  docs/sdk/src/reference_docs/chain_spec_runtime/src/presets.rs
  polkadot/node/metrics/src/tests.rs
  polkadot/node/test/service/src/lib.rs
  polkadot/parachain/test-parachains/adder/collator/tests/integration.rs
  polkadot/parachain/test-parachains/undying/collator/tests/integration.rs
  polkadot/runtime/rococo/src/tests.rs
  polkadot/runtime/westend/src/tests.rs
  prdoc/pr_5899.prdoc
  substrate/bin/node/cli/src/service.rs
  substrate/client/basic-authorship/src/basic_authorship.rs
  substrate/client/basic-authorship/src/lib.rs
  substrate/client/chain-spec/src/chain_spec.rs
  substrate/client/consensus/manual-seal/src/lib.rs
  substrate/client/network/test/src/lib.rs
  substrate/client/rpc-spec-v2/src/archive/tests.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
  substrate/client/rpc-spec-v2/src/transaction/tests/transaction_broadcast_tests.rs
  substrate/client/rpc-spec-v2/src/transaction/tests/transaction_tests.rs
  substrate/client/rpc/src/author/tests.rs
  substrate/client/rpc/src/state/tests.rs
  substrate/client/service/src/lib.rs
  substrate/client/service/test/src/client/mod.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/revalidation_worker.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/tx_mem_pool.rs
  substrate/client/transaction-pool/src/graph/pool.rs
  substrate/client/transaction-pool/src/single_state_txpool/revalidation.rs
  substrate/client/transaction-pool/tests/fatp.rs
  substrate/client/transaction-pool/tests/fatp_common/mod.rs
  substrate/client/transaction-pool/tests/fatp_limits.rs
  substrate/client/transaction-pool/tests/fatp_prios.rs
  substrate/client/transaction-pool/tests/pool.rs
  substrate/docs/Upgrading-2.0-to-3.0.md
  substrate/frame/examples/authorization-tx-extension/src/tests.rs
  substrate/frame/src/lib.rs
  substrate/frame/support/Cargo.toml
  substrate/primitives/api/test/tests/runtime_calls.rs
  substrate/primitives/keyring/src/lib.rs
  substrate/test-utils/client/src/lib.rs
  substrate/test-utils/runtime/client/src/lib.rs
  substrate/test-utils/runtime/client/src/trait_tests.rs
  substrate/test-utils/runtime/src/extrinsic.rs
  substrate/test-utils/runtime/src/genesismap.rs
  substrate/test-utils/runtime/src/lib.rs
  substrate/test-utils/runtime/transaction-pool/src/lib.rs
  substrate/utils/frame/rpc/system/src/lib.rs
  templates/minimal/runtime/src/lib.rs
  templates/solochain/runtime/src/genesis_config_presets.rs
Labels: T17-primitives

#6624 polkadot-sdk-docs: Use command_macro!
  Cargo.lock
  docs/sdk/Cargo.toml
  docs/sdk/src/guides/your_first_node.rs
  docs/sdk/src/reference_docs/chain_spec_genesis.rs
  docs/sdk/src/reference_docs/chain_spec_runtime/Cargo.toml
  docs/sdk/src/reference_docs/chain_spec_runtime/tests/chain_spec_builder_tests.rs
  prdoc/pr_6624.prdoc
Labels: R0-silent, T11-documentation

#6729 Fix order of resending messages after restart
  polkadot/node/core/approval-voting/src/lib.rs
  polkadot/node/core/approval-voting/src/tests.rs
  prdoc/pr_6729.prdoc
Labels: T8-polkadot, A4-needs-backport

#6503 XCMv5: Fix for compatibility with V4
  bridges/snowbridge/pallets/inbound-queue/src/mock.rs
  bridges/snowbridge/pallets/inbound-queue/src/test.rs
  polkadot/xcm/src/v5/junction.rs
  prdoc/pr_6503.prdoc
Labels: T6-XCM

#6646 omni-node: --dev sets manual seal and allows --chain to be set
  cumulus/polkadot-omni-node/README.md
  cumulus/polkadot-omni-node/lib/src/cli.rs
  cumulus/polkadot-omni-node/lib/src/command.rs
  prdoc/pr_6646.prdoc
  substrate/client/cli/src/params/shared_params.rs
  templates/minimal/README.md
  templates/minimal/zombienet-omni-node.toml
  templates/parachain/README.md
Labels: T9-cumulus, T17-Templates

#6613 Migration of polkadot-runtime-common auctions benchmarking to v2
  polkadot/runtime/common/src/auctions.rs
Labels: R0-silent, T2-pallets, T12-benchmarks

#6696 Make approval-distribution aggression a bit more robust and less spammy
  polkadot/node/network/approval-distribution/src/lib.rs
  polkadot/node/network/approval-distribution/src/tests.rs
  prdoc/pr_6696.prdoc
Labels: T8-polkadot, A4-needs-backport

#6808 snowbridge: Update alloy-core
  Cargo.lock
  Cargo.toml
  bridges/snowbridge/pallets/inbound-queue/Cargo.toml
  bridges/snowbridge/pallets/inbound-queue/src/envelope.rs
Labels: R0-silent

#6842 backport/stable2412: chainHead: Always report discarded items for storage operations
  prdoc/pr_6760.prdoc
  substrate/client/rpc-spec-v2/src/chain_head/chain_head.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
Labels: A3-backport

#6814 Add aliasers to westend chains
  cumulus/parachains/runtimes/collectives/collectives-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/people/people-westend/src/xcm_config.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/xcm/mod.rs
  polkadot/runtime/westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  polkadot/runtime/westend/src/xcm_config.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  prdoc/pr_6814.prdoc
Labels: T6-XCM

#6759 pallet-revive: Statically verify imports on code deployment
  prdoc/pr_6759.prdoc
  substrate/frame/revive/README.md
  substrate/frame/revive/fixtures/contracts/unknown_syscall.rs
  substrate/frame/revive/fixtures/contracts/unstable_interface.rs
  substrate/frame/revive/proc-macro/src/lib.rs
  substrate/frame/revive/src/benchmarking/call_builder.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/limits.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/mod.rs
  substrate/frame/revive/src/wasm/runtime.rs
Labels: R0-silent

#6849 Backport aliasers to westend to stable2412
  Cargo.lock
  bridges/snowbridge/pallets/inbound-queue/src/test.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/people/people-westend/src/xcm_config.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/xcm/mod.rs
  polkadot/runtime/westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  polkadot/runtime/westend/src/xcm_config.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  prdoc/pr_6849.prdoc
Labels: T6-XCM

#6854 Update parity-publish to 0.10.3
  .github/workflows/check-semver.yml
  .github/workflows/publish-check-compile.yml
  .github/workflows/publish-check-crates.yml
  .github/workflows/publish-claim-crates.yml
Labels: R0-silent

#6450 omni-node: add metadata checks for runtime/parachain compatibility
  Cargo.lock
  Cargo.toml
  cumulus/polkadot-omni-node/lib/Cargo.toml
  cumulus/polkadot-omni-node/lib/src/common/runtime.rs
  cumulus/polkadot-omni-node/lib/src/common/spec.rs
  docs/sdk/src/reference_docs/omni_node.rs
  prdoc/pr_6450.prdoc
  substrate/client/runtime-utilities/Cargo.toml
  substrate/client/runtime-utilities/src/error.rs
  substrate/client/runtime-utilities/src/lib.rs
  substrate/utils/frame/benchmarking-cli/Cargo.toml
  substrate/utils/frame/benchmarking-cli/src/lib.rs
  substrate/utils/frame/benchmarking-cli/src/overhead/command.rs
  substrate/utils/frame/benchmarking-cli/src/overhead/mod.rs
  umbrella/Cargo.toml
  umbrella/src/lib.rs
Labels: T9-cumulus

#6844 pallet-revive: disable host functions not in revive recompiler
  prdoc/pr_6844.prdoc
  substrate/frame/revive/src/wasm/runtime.rs
Labels: T7-smart_contracts

#6860 chore: Update litep2p to version 0.8.4
  Cargo.lock
  Cargo.toml
  prdoc/pr_6860.prdoc
Labels: T0-node

#6505 [pallet-broker] Fix auto renew benchmarks
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_broker.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/pallet_broker.rs
  prdoc/pr_6505.prdoc
  substrate/frame/broker/src/benchmarking.rs
  substrate/frame/broker/src/weights.rs
Labels: T2-pallets, T12-benchmarks

#6576 [polkadot-runtime-parachains] migrate paras module to benchmarking v2 syntax
  polkadot/runtime/parachains/src/paras/benchmarking.rs
Labels: R0-silent, T2-pallets

#6865 Rename PanicInfo to PanicHookInfo
  prdoc/pr_6865.prdoc
  substrate/primitives/panic-handler/src/lib.rs
Labels: R0-silent

#6862 backport/stable2412: Update litep2p to version 0.8.4
  Cargo.lock
  Cargo.toml
  prdoc/pr_6860.prdoc
Labels: A3-backport

#6857 [pallet-revive] implement the call data size API
  prdoc/pr_6857.prdoc
  substrate/frame/revive/fixtures/contracts/call_data_size.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/src/weights.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv64.rs
Labels: R0-silent, T7-smart_contracts

#6652 rpc: re-use server builder per rpc interface
  prdoc/pr_6652.prdoc
  substrate/client/rpc-servers/src/lib.rs
  substrate/client/rpc-servers/src/utils.rs
Labels: T0-node, A4-needs-backport

#6711 Expose DHT content providers API from `sc-network`
  prdoc/pr_6711.prdoc
  substrate/client/authority-discovery/src/worker.rs
  substrate/client/authority-discovery/src/worker/tests.rs
  substrate/client/network/src/behaviour.rs
  substrate/client/network/src/discovery.rs
  substrate/client/network/src/event.rs
  substrate/client/network/src/litep2p/discovery.rs
  substrate/client/network/src/litep2p/mod.rs
  substrate/client/network/src/litep2p/service.rs
  substrate/client/network/src/service.rs
  substrate/client/network/src/service/traits.rs
Labels: T0-node

#6481 slot-based-collator: Implement dedicated block import
  Cargo.lock
  cumulus/client/consensus/aura/Cargo.toml
  cumulus/client/consensus/aura/src/collators/slot_based/block_import.rs
  cumulus/client/consensus/aura/src/collators/slot_based/collation_task.rs
  cumulus/client/consensus/aura/src/collators/slot_based/mod.rs
  cumulus/polkadot-omni-node/lib/Cargo.toml
  cumulus/polkadot-omni-node/lib/src/common/spec.rs
  cumulus/polkadot-omni-node/lib/src/common/types.rs
  cumulus/polkadot-omni-node/lib/src/nodes/aura.rs
  cumulus/polkadot-omni-node/lib/src/nodes/manual_seal.rs
  cumulus/test/service/src/lib.rs
  prdoc/pr_6481.prdoc
Labels: T0-node

#6863 Update merkleized-metadata to 0.2.0
  Cargo.lock
  Cargo.toml
  prdoc/pr_6863.prdoc
Labels: R0-silent

#6744 Only one ParaId variable in the Parachain Template
  templates/parachain/node/src/chain_spec.rs
  templates/parachain/runtime/src/genesis_config_presets.rs
  templates/parachain/runtime/src/lib.rs
Labels: R0-silent

#6866 Add `unstable-api` feature flag to `pallet-revive`
  prdoc/pr_6866.prdoc
  substrate/frame/revive/fixtures/build/_Cargo.toml
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/uapi/Cargo.toml
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv64.rs
Labels: T7-smart_contracts

#6533 sc-executor-polkavm: Migrate into PolkaVM 0.18.0
  Cargo.lock
  Cargo.toml
  polkadot/runtime/rococo/src/lib.rs
  prdoc/pr_6533.prdoc
  substrate/client/executor/common/src/error.rs
  substrate/client/executor/common/src/runtime_blob/runtime_blob.rs
  substrate/client/executor/polkavm/src/lib.rs
Labels: T0-node

#6893 Fix flaky `build-runtimes-polkavm` CI job
  .github/workflows/build-misc.yml
Labels: R0-silent

#6248 Upgrade libp2p from 0.52.4 to 0.54.1
  Cargo.lock
  Cargo.toml
  prdoc/pr_6248.prdoc
  substrate/client/network/src/behaviour.rs
  substrate/client/network/src/discovery.rs
  substrate/client/network/src/network_state.rs
  substrate/client/network/src/peer_info.rs
  substrate/client/network/src/protocol.rs
  substrate/client/network/src/protocol/notifications.rs
  substrate/client/network/src/protocol/notifications/behaviour.rs
  substrate/client/network/src/protocol/notifications/handler.rs
  substrate/client/network/src/protocol/notifications/tests.rs
  substrate/client/network/src/protocol/notifications/upgrade/notifications.rs
  substrate/client/network/src/request_responses.rs
  substrate/client/network/src/service.rs
  substrate/client/network/src/transport.rs
  substrate/client/network/sync/src/engine.rs
  substrate/client/network/types/Cargo.toml
  substrate/client/telemetry/Cargo.toml
  substrate/client/telemetry/src/node.rs
Labels: T0-node

#6889 polkadot-omni-node-lib: remove unused dep
  Cargo.lock
  cumulus/polkadot-omni-node/lib/Cargo.toml
  prdoc/pr_6889.prdoc
Labels: T9-cumulus

#6898 Upgrade nix and reqwest
  Cargo.lock
  Cargo.toml
Labels: R0-silent

#6917 Remove unused dependencies from pallet_revive
  Cargo.lock
  prdoc/pr_6917.prdoc
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/fixtures/Cargo.toml
  substrate/frame/revive/fixtures/src/lib.rs
  substrate/frame/revive/mock-network/Cargo.toml
  substrate/frame/revive/rpc/Cargo.toml
Labels: R0-silent

#6923 omni-node: Tolerate failing metadata check
  Cargo.lock
  cumulus/polkadot-omni-node/lib/Cargo.toml
  cumulus/polkadot-omni-node/lib/src/common/runtime.rs
  prdoc/pr_6923.prdoc
Labels: T9-cumulus, A4-needs-backport

#6912 adding stkd bootnodes
  cumulus/parachains/chain-specs/asset-hub-kusama.json
  cumulus/parachains/chain-specs/asset-hub-polkadot.json
  cumulus/parachains/chain-specs/asset-hub-westend.json
  cumulus/parachains/chain-specs/bridge-hub-kusama.json
  cumulus/parachains/chain-specs/bridge-hub-polkadot.json
  cumulus/parachains/chain-specs/bridge-hub-westend.json
  cumulus/parachains/chain-specs/collectives-polkadot.json
  cumulus/parachains/chain-specs/collectives-westend.json
  cumulus/parachains/chain-specs/coretime-kusama.json
  cumulus/parachains/chain-specs/coretime-polkadot.json
  cumulus/parachains/chain-specs/coretime-westend.json
  cumulus/parachains/chain-specs/people-kusama.json
  cumulus/parachains/chain-specs/people-polkadot.json
  cumulus/parachains/chain-specs/people-westend.json
Labels: R0-silent

#6880 [pallet-revive] implement the call data copy API
  prdoc/pr_6880.prdoc
  substrate/frame/revive/fixtures/contracts/call_data_copy.rs
  substrate/frame/revive/fixtures/contracts/common/src/lib.rs
  substrate/frame/revive/rpc/examples/js/pvm/ErrorTester.polkavm
  substrate/frame/revive/rpc/examples/js/pvm/EventExample.polkavm
  substrate/frame/revive/rpc/examples/js/pvm/Flipper.polkavm
  substrate/frame/revive/rpc/examples/js/pvm/FlipperCaller.polkavm
  substrate/frame/revive/rpc/examples/js/pvm/PiggyBank.polkavm
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/src/weights.rs
  substrate/frame/revive/uapi/src/flags.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv64.rs
Labels: R0-silent, T7-smart_contracts

#6452 elastic scaling RFC 103 end-to-end test
  .gitlab/pipeline/zombienet/polkadot.yml
  Cargo.lock
  Cargo.toml
  cumulus/parachains/runtimes/testing/rococo-parachain/Cargo.toml
  cumulus/test/runtime/Cargo.toml
  cumulus/test/runtime/build.rs
  cumulus/test/runtime/src/lib.rs
  cumulus/test/service/src/chain_spec.rs
  cumulus/test/service/src/cli.rs
  polkadot/runtime/rococo/src/genesis_config_presets.rs
  polkadot/runtime/westend/src/genesis_config_presets.rs
  polkadot/zombienet-sdk-tests/build.rs
  polkadot/zombienet-sdk-tests/tests/elastic_scaling/helpers.rs
  polkadot/zombienet-sdk-tests/tests/elastic_scaling/mod.rs
  polkadot/zombienet-sdk-tests/tests/elastic_scaling/slot_based_3cores.rs
  polkadot/zombienet-sdk-tests/tests/lib.rs
  polkadot/zombienet-sdk-tests/tests/smoke/coretime_revenue.rs
  polkadot/zombienet-sdk-tests/tests/smoke/mod.rs
  prdoc/pr_6452.prdoc
Labels: T8-polkadot, T10-tests

#6501 Migrate pallet-xcm benchmarks to benchmark v2 syntax
  polkadot/xcm/pallet-xcm/src/benchmarking.rs
Labels: R0-silent, T2-pallets, T12-benchmarks

#6779 Improve pallet claims file structure
  polkadot/runtime/common/src/claims.rs
  polkadot/runtime/common/src/claims/benchmarking.rs
  polkadot/runtime/common/src/claims/mock.rs
  polkadot/runtime/common/src/claims/mod.rs
  polkadot/runtime/common/src/claims/tests.rs
Labels: R0-silent

#6919 `pallet_xcm::execute` weights
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/pallet_xcm.rs
  polkadot/runtime/rococo/src/weights/pallet_xcm.rs
  polkadot/runtime/westend/src/weights/pallet_xcm.rs
Labels: R0-silent, T6-XCM, T12-benchmarks, A4-needs-backport

#6908 [pallet-revive] implement the ref_time_left API
  prdoc/pr_6908.prdoc
  substrate/frame/revive/fixtures/contracts/ref_time_left.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/src/weights.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv64.rs
Labels: R0-silent, T7-smart_contracts

#6938 [CI/CD] Fixes fro the docker images publishing pipeline
  .github/scripts/common/lib.sh
  .github/workflows/release-50_publish-docker.yml
Labels: R0-silent

#6935 slot-based-collator: Refactor some internals
  cumulus/client/consensus/aura/src/collators/slot_based/block_builder_task.rs
  cumulus/client/consensus/aura/src/collators/slot_based/mod.rs
  cumulus/client/consensus/aura/src/collators/slot_based/relay_chain_data_cache.rs
Labels: R0-silent

#6920 [pallet-revive] change some getter APIs to return value in register
  prdoc/pr_6920.prdoc
  substrate/frame/revive/fixtures/contracts/call_data_size.rs
  substrate/frame/revive/fixtures/contracts/common/src/lib.rs
  substrate/frame/revive/fixtures/contracts/extcodesize.rs
  substrate/frame/revive/fixtures/contracts/return_data_api.rs
  substrate/frame/revive/rpc/examples/js/pvm/ErrorTester.polkavm
  substrate/frame/revive/rpc/examples/js/pvm/EventExample.polkavm
  substrate/frame/revive/rpc/examples/js/pvm/Flipper.polkavm
  substrate/frame/revive/rpc/examples/js/pvm/FlipperCaller.polkavm
  substrate/frame/revive/rpc/examples/js/pvm/PiggyBank.polkavm
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/mod.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/src/weights.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv64.rs
Labels: R0-silent, T7-smart_contracts

#6958 fixed token
  .github/workflows/cmd.yml
Labels: R0-silent

#6937 [pallet-revive] bump polkavm to 0.18
  Cargo.lock
  prdoc/pr_6937.prdoc
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/fixtures/Cargo.toml
  substrate/frame/revive/fixtures/build/_Cargo.toml
  substrate/frame/revive/rpc/examples/js/pvm/ErrorTester.polkavm
  substrate/frame/revive/rpc/examples/js/pvm/EventExample.polkavm
  substrate/frame/revive/rpc/examples/js/pvm/Flipper.polkavm
  substrate/frame/revive/rpc/examples/js/pvm/FlipperCaller.polkavm
  substrate/frame/revive/rpc/examples/js/pvm/PiggyBank.polkavm
  substrate/frame/revive/uapi/Cargo.toml
Labels: R0-silent, T7-smart_contracts

#6896 pallet-revive: Fix docs.rs
  Cargo.lock
  prdoc/pr_6896.prdoc
  substrate/frame/contracts/uapi/Cargo.toml
  substrate/frame/revive/fixtures/build/_Cargo.toml
  substrate/frame/revive/proc-macro/src/lib.rs
  substrate/frame/revive/uapi/Cargo.toml
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv64.rs
  substrate/frame/revive/uapi/src/lib.rs
Labels: R0-silent

#6780 Improve pallet purchase file structure
  polkadot/runtime/common/src/purchase.rs
  polkadot/runtime/common/src/purchase/mock.rs
  polkadot/runtime/common/src/purchase/mod.rs
  polkadot/runtime/common/src/purchase/tests.rs
Labels: R0-silent

#6746 Pallet:Auction move tests and benchmark to seperate files
  polkadot/runtime/common/src/auctions.rs
  polkadot/runtime/common/src/auctions/benchmarking.rs
  polkadot/runtime/common/src/auctions/mock.rs
  polkadot/runtime/common/src/auctions/mod.rs
  polkadot/runtime/common/src/auctions/tests.rs
Labels: R0-silent

#6783 Improve pallet paras_registrar file structure
  polkadot/runtime/common/src/paras_registrar/benchmarking.rs
  polkadot/runtime/common/src/paras_registrar/mock.rs
  polkadot/runtime/common/src/paras_registrar/mod.rs
  polkadot/runtime/common/src/paras_registrar/tests.rs
Labels: R0-silent

#6577 [polkadot-runtime-parachains] migrate disputes and disputes/slashing to benchmarking to bench v2 syntax
  polkadot/runtime/parachains/src/disputes/benchmarking.rs
  polkadot/runtime/parachains/src/disputes/slashing.rs
  polkadot/runtime/parachains/src/disputes/slashing/benchmarking.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_parachains_disputes_slashing.rs
Labels: R0-silent, T2-pallets

#6964 [pallet-revive] implement the base fee API
  prdoc/pr_6964.prdoc
  substrate/frame/revive/fixtures/contracts/base_fee.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/src/weights.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv64.rs
Labels: R0-silent, T7-smart_contracts

#6601 Migrate `pallet-atomic-swap` to umbrella crate
  Cargo.lock
  substrate/frame/atomic-swap/Cargo.toml
  substrate/frame/atomic-swap/src/lib.rs
  substrate/frame/atomic-swap/src/tests.rs
Labels: R0-silent, T1-FRAME

#6961 fix: typos in documentation files
  cumulus/README.md
Labels: R0-silent

#6963 grandpa: Ensure `WarpProof` stays in its limits
  prdoc/pr_6963.prdoc
  substrate/client/consensus/grandpa/src/warp_proof.rs
Labels: T0-node

#4273 [pallet-broker] add extrinsic to reserve a system core without having to wait two sale boundaries
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_broker.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/pallet_broker.rs
  prdoc/pr_4273.prdoc
  substrate/frame/broker/src/benchmarking.rs
  substrate/frame/broker/src/dispatchable_impls.rs
  substrate/frame/broker/src/lib.rs
  substrate/frame/broker/src/tests.rs
  substrate/frame/broker/src/weights.rs
Labels: T2-pallets

#6446 Make pallet-recovery supports `BlockNumberProvider`
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_6446.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/recovery/src/lib.rs
  substrate/frame/recovery/src/mock.rs
Labels: T2-pallets

#6979 Update prometheus binding failure logging format
  prdoc/pr_6979.prdoc
  substrate/utils/prometheus/src/lib.rs
Labels: T0-node

#6989 paras-registrar: Improve error reporting
  polkadot/runtime/common/src/paras_registrar/mod.rs
  polkadot/runtime/common/src/paras_registrar/tests.rs
  prdoc/pr_6989.prdoc
Labels: T8-polkadot

#6368 Migrate inclusion benchmark to v2
  polkadot/runtime/parachains/src/inclusion/benchmarking.rs
  prdoc/pr_6368.prdoc
Labels: R0-silent, T2-pallets, T12-benchmarks

#7005 Log peerset set ID -> protocol name mapping
  prdoc/pr_7005.prdoc
  substrate/client/network/src/protocol.rs
Labels: A1-insubstantial, R0-silent, T0-node

#7013 pallet-bounties: Fix benchmarks for 0 ED
  prdoc/pr_7013.prdoc
  substrate/frame/bounties/src/benchmarking.rs
  substrate/frame/bounties/src/lib.rs
Labels: T1-FRAME, A4-needs-backport

#6524 Excluding chainlink domain for link checker CI
  .config/lychee.toml
Labels: A1-insubstantial, R0-silent, T10-tests

#7011 sync: Send already connected peers to new subscribers
  prdoc/pr_7011.prdoc
  substrate/client/network-gossip/src/bridge.rs
  substrate/client/network-gossip/src/lib.rs
  substrate/client/network/statement/src/lib.rs
  substrate/client/network/sync/src/engine.rs
  substrate/client/network/sync/src/types.rs
  substrate/client/network/transactions/src/lib.rs
Labels: T0-node

#7001 correct path in cumulus README
  cumulus/README.md
Labels: R0-silent
