Repository paritytech/polkadot-sdk, pull requests merged in 2024-05, with the labels that each got.

#3444 Statement Distribution Per Peer Rate Limit
  .gitlab/pipeline/zombienet/polkadot.yml
  Cargo.lock
  polkadot/node/malus/Cargo.toml
  polkadot/node/malus/src/malus.rs
  polkadot/node/malus/src/variants/mod.rs
  polkadot/node/malus/src/variants/spam_statement_requests.rs
  polkadot/node/network/statement-distribution/src/lib.rs
  polkadot/node/network/statement-distribution/src/metrics.rs
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  polkadot/node/network/statement-distribution/src/v2/requests.rs
  polkadot/node/network/statement-distribution/src/v2/tests/requests.rs
  polkadot/zombienet_tests/functional/0012-spam-statement-distribution-requests.toml
  polkadot/zombienet_tests/functional/0012-spam-statement-distribution-requests.zndsl
  prdoc/pr_3444.prdoc
Labels: T0-node, I1-security, T8-polkadot

#4332 HRMP - set `DefaultChannelSizeAndCapacityWithSystem` with dynamic values according to the `ActiveConfig`
  polkadot/runtime/parachains/src/configuration.rs
  polkadot/runtime/parachains/src/configuration/tests.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/runtime_parachains_hrmp.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/runtime_parachains_hrmp.rs
Labels: R0-silent, T8-polkadot

#4295 Make parachain template great again (and async backing ready)
  Cargo.lock
  prdoc/pr_4295.prdoc
  templates/parachain/node/src/service.rs
  templates/parachain/runtime/Cargo.toml
  templates/parachain/runtime/src/apis.rs
  templates/parachain/runtime/src/configs/mod.rs
  templates/parachain/runtime/src/lib.rs
Labels: T9-cumulus

#4350 Bridge: ignore client errors when calling recently added `*_free_headers_interval` methods
  bridges/relays/lib-substrate-relay/src/finality/target.rs
  bridges/relays/lib-substrate-relay/src/parachains/target.rs
Labels: R0-silent, T15-bridges

#4344 cargo: Update experimental litep2p to latest version
  Cargo.lock
  substrate/client/network/Cargo.toml
  substrate/client/network/src/litep2p/discovery.rs
  substrate/client/network/types/Cargo.toml
Labels: A1-insubstantial, R0-silent, I5-enhancement, D0-easy

#4244 Add PoV-reclaim enablement guide to polkadot-sdk-docs
  Cargo.lock
  docs/sdk/Cargo.toml
  docs/sdk/src/guides/enable_pov_reclaim.rs
  docs/sdk/src/guides/mod.rs
  docs/sdk/src/meta_contributing.rs
  templates/parachain/node/Cargo.toml
  templates/parachain/node/src/service.rs
  templates/parachain/runtime/Cargo.toml
  templates/parachain/runtime/src/lib.rs
Labels: R0-silent, T11-documentation

#4330 deps: update jsonrpsee to v0.22.5
  Cargo.lock
  substrate/client/consensus/babe/rpc/Cargo.toml
  substrate/client/consensus/beefy/rpc/Cargo.toml
  substrate/client/consensus/grandpa/rpc/Cargo.toml
  substrate/client/consensus/manual-seal/Cargo.toml
  substrate/client/merkle-mountain-range/rpc/Cargo.toml
  substrate/client/rpc-api/Cargo.toml
  substrate/client/rpc-spec-v2/Cargo.toml
  substrate/client/sync-state-rpc/Cargo.toml
  substrate/frame/transaction-payment/rpc/Cargo.toml
  substrate/utils/frame/rpc/state-trie-migration-rpc/Cargo.toml
  substrate/utils/frame/rpc/system/Cargo.toml
Labels: R0-silent, T0-node

#4357 sc-tracing: enable env-filter feature
  substrate/client/tracing/Cargo.toml
Labels: A1-insubstantial, R0-silent

#4355 More `xcm::v4` cleanup and `xcm_fee_payment_runtime_api::XcmPaymentApi` nits
  Cargo.lock
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  polkadot/runtime/parachains/src/coretime/migration.rs
  polkadot/runtime/parachains/src/coretime/mod.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/xcm/xcm-fee-payment-runtime-api/src/lib.rs
Labels: R0-silent, T6-XCM

#4329 Deprecate `NativeElseWasmExecutor`
  cumulus/test/client/src/lib.rs
  prdoc/pr_4329.prdoc
  substrate/client/executor/src/executor.rs
  substrate/client/executor/src/lib.rs
  substrate/client/rpc-spec-v2/src/chain_head/subscription/inner.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
  substrate/client/service/src/builder.rs
  substrate/client/service/src/client/call_executor.rs
  substrate/client/service/src/client/wasm_override.rs
  substrate/client/service/src/lib.rs
  substrate/client/service/test/src/client/mod.rs
  substrate/frame/system/src/tests.rs
  substrate/primitives/api/test/tests/runtime_calls.rs
  substrate/test-utils/client/src/lib.rs
  substrate/test-utils/runtime/client/src/lib.rs
Labels: T0-node

#4346 Allow for 0 existential deposit in benchmarks for `pallet_staking`, `pallet_session`, and `pallet_balances`
  prdoc/pr_4346.prdoc
  substrate/frame/balances/src/benchmarking.rs
  substrate/frame/staking/src/testing_utils.rs
Labels: T1-FRAME

#4270 [WIP][CI] Add more GHA jobs
  .github/env
  .github/workflows/quick-checks.yml
  .github/workflows/test-github-actions.yml
Labels: R0-silent

#4367 Bridge: fix zombienet tests
  bridges/testing/environments/rococo-westend/bridges_rococo_westend.sh
Labels: R0-silent, T15-bridges

#4365 Bridge: added subcommand to relay single parachain header
  bridges/relays/lib-substrate-relay/src/cli/relay_parachains.rs
  bridges/relays/parachains/src/parachains_loop.rs
Labels: R0-silent, T15-bridges

#4364 Fix: dust unbonded for zero existential deposit
  prdoc/pr_4364.prdoc
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/tests.rs
Labels: T1-FRAME, T2-pallets

#4185 State trie migration on asset-hub westend and collectives westend
  Cargo.lock
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/Cargo.toml
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  prdoc/pr_4185.prdoc
Labels: T14-system_parachains, R1-breaking_change

#4368 Add validate field to prdoc
  prdoc/schema_user.json
Labels: A1-insubstantial, R0-silent

#4370 Publish `polkadot-sdk-frame` crate
  substrate/frame/Cargo.toml
Labels: R0-silent, T1-FRAME

#4034 Introduces `TypeWithDefault<T, D: Get<T>>`
  Cargo.lock
  prdoc/pr_4034.prdoc
  substrate/frame/system/src/extensions/check_nonce.rs
  substrate/frame/system/src/mock.rs
  substrate/frame/system/src/tests.rs
  substrate/primitives/runtime/Cargo.toml
  substrate/primitives/runtime/src/lib.rs
  substrate/primitives/runtime/src/type_with_default.rs
Labels: T1-FRAME

#4371 Improve Create release draft workflow + templates for the free notes and docker images sections in the notes
  .github/workflows/release-30_publish_release_draft.yml
  .github/workflows/release-99_notif-published.yml
  scripts/release/build-changelogs.sh
  scripts/release/templates/_free_notes.md.tera
  scripts/release/templates/docker_image.md.tera
  scripts/release/templates/template.md.tera
Labels: R0-silent, I5-enhancement

#4281 Add support for versioned notification for HRMP pallet
  polkadot/runtime/parachains/src/hrmp.rs
  polkadot/runtime/parachains/src/hrmp/tests.rs
  polkadot/runtime/parachains/src/mock.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/runtime_parachains_hrmp.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/runtime_parachains_hrmp.rs
  polkadot/xcm/xcm-simulator/example/src/relay_chain/mod.rs
  polkadot/xcm/xcm-simulator/fuzzer/src/relay_chain.rs
  prdoc/pr_4281.prdoc
Labels: T6-XCM

#4395 chore: fix typos
  polkadot/node/service/src/lib.rs
  polkadot/node/subsystem-bench/src/lib/approval/message_generator.rs
  polkadot/node/subsystem-bench/src/lib/approval/mod.rs
  polkadot/runtime/parachains/src/assigner_on_demand/mod.rs
Labels: R0-silent

#4394 Add Kusama People Chain genesis chainspec
  cumulus/parachains/chain-specs/people-kusama.json
  cumulus/polkadot-parachain/src/chain_spec/people.rs
  prdoc/pr_4394.prdoc
Labels: T14-system_parachains

#4387 Code coverage preparations
  .github/codecov.yml
  .gitlab/pipeline/test.yml
Labels: R0-silent

#4401 Update prdoc for 2226
  prdoc/pr_2226.prdoc
Labels: R0-silent

#4396 Generate XCM weights for coretimes
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
Labels: R0-silent

#3964 [pallet-balances] `burn_allow_death` extrinsic
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_balances.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_balances.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_balances.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_balances.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_balances.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_balances.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/pallet_balances.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/pallet_balances.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/pallet_balances.rs
  polkadot/runtime/rococo/src/weights/pallet_balances_balances.rs
  polkadot/runtime/rococo/src/weights/pallet_balances_nis_counterpart_balances.rs
  polkadot/runtime/westend/src/weights/pallet_balances.rs
  polkadot/xcm/xcm-builder/src/fungible_adapter.rs
  polkadot/xcm/xcm-builder/src/fungibles_adapter.rs
  prdoc/pr_3964.prdoc
  substrate/frame/asset-conversion/ops/src/lib.rs
  substrate/frame/asset-conversion/src/lib.rs
  substrate/frame/balances/src/benchmarking.rs
  substrate/frame/balances/src/lib.rs
  substrate/frame/balances/src/tests/currency_tests.rs
  substrate/frame/balances/src/tests/dispatchable_tests.rs
  substrate/frame/balances/src/weights.rs
  substrate/frame/nft-fractionalization/src/lib.rs
  substrate/frame/nis/src/lib.rs
  substrate/frame/nis/src/tests.rs
  substrate/frame/support/src/traits/tokens/fungible/conformance_tests/inspect_mutate.rs
  substrate/frame/support/src/traits/tokens/fungible/conformance_tests/regular/mutate.rs
  substrate/frame/support/src/traits/tokens/fungible/item_of.rs
  substrate/frame/support/src/traits/tokens/fungible/regular.rs
  substrate/frame/support/src/traits/tokens/fungible/union_of.rs
  substrate/frame/support/src/traits/tokens/fungibles/regular.rs
  substrate/frame/support/src/traits/tokens/fungibles/union_of.rs
Labels: T1-FRAME

#4385 Bridge: check bridge GRANDPA pallet call limits from signed extension
  bridges/modules/grandpa/src/call_ext.rs
  bridges/modules/grandpa/src/lib.rs
Labels: R0-silent, T15-bridges

#4406 Adds benchmarking and try-runtime support in frame crate
  Cargo.lock
  prdoc/pr_4406.prdoc
  substrate/frame/Cargo.toml
  substrate/frame/src/lib.rs
Labels: T1-FRAME

#4279 Add semver CI check
  .github/workflows/check-publish.yml
  .github/workflows/check-semver.yml
  .github/workflows/claim-crates.yml
  Cargo.lock
  substrate/client/network/types/Cargo.toml
Labels: A1-insubstantial, R0-silent

#3701 rpc: add option to `whitelist ips` in rate limiting
  Cargo.lock
  cumulus/test/service/src/lib.rs
  polkadot/node/test/service/src/lib.rs
  prdoc/pr_3701.prdoc
  substrate/bin/node/cli/benches/block_production.rs
  substrate/bin/node/cli/benches/transaction_pool.rs
  substrate/client/cli/src/commands/run_cmd.rs
  substrate/client/cli/src/config.rs
  substrate/client/cli/src/runner.rs
  substrate/client/rpc-servers/Cargo.toml
  substrate/client/rpc-servers/src/lib.rs
  substrate/client/rpc-servers/src/utils.rs
  substrate/client/service/src/config.rs
  substrate/client/service/src/lib.rs
  substrate/client/service/test/src/lib.rs
Labels: T0-node

#4425 Fixes `frame-support` reference in `try_decode_entire_state`
  substrate/frame/support/procedural/src/pallet/expand/storage.rs
Labels: R0-silent, T1-FRAME

#4411 `stake-tracker` feedback PR
  polkadot/runtime/westend/src/bag_thresholds.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/pallet_staking.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/staking/src/benchmarking.rs
  substrate/frame/staking/src/migrations/v13_stake_tracker/tests.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/tests.rs
  substrate/frame/staking/src/weights.rs
  substrate/frame/staking/stake-tracker/src/lib.rs
  substrate/frame/staking/stake-tracker/src/mock.rs
  substrate/frame/staking/stake-tracker/src/tests.rs
  substrate/primitives/staking/src/lib.rs
Labels: R0-silent

#4426 rustls: Disable logging
  prdoc/pr_4426.prdoc
  substrate/client/tracing/src/logging/mod.rs
Labels: T0-node

#2955 Disabling Strategy Implementers Guide
  polkadot/roadmap/implementers-guide/src/SUMMARY.md
  polkadot/roadmap/implementers-guide/src/protocol-disputes.md
  polkadot/roadmap/implementers-guide/src/protocol-validator-disabling.md
Labels: R0-silent, T11-documentation

#4423 Add docs to request_core_count
  polkadot/runtime/parachains/src/coretime/mod.rs
Labels: R0-silent, T8-polkadot

#4417 Remove pallet::getter usage from pallet-contracts-mock-network
  prdoc/pr_4417.prdoc
  substrate/frame/contracts/mock-network/src/mocks/msg_queue.rs
Labels: R0-silent

#4091 Remove `pallet::getter` usage from authority-discovery pallet
  prdoc/pr_4091.prdoc
  substrate/frame/authority-discovery/src/lib.rs
Labels: T2-pallets

#4434 xcm-emlator: Use `BlockNumberFor` instead of `parachains_common::BlockNumber=u32`
  cumulus/xcm/xcm-emulator/src/lib.rs
Labels: R0-silent, T10-tests

#4349 `remote-externalities`: store block header in snapshot
  .config/lychee.toml
  prdoc/pr_4349.prdoc
  substrate/utils/frame/remote-externalities/src/lib.rs
  substrate/utils/frame/remote-externalities/test_data/proxy_test
  substrate/utils/frame/remote-externalities/test_data/test.snap
Labels: T1-FRAME

#4302 migrations: `take()`should consume read and write operation weight
  prdoc/pr_4302.prdoc
  substrate/frame/balances/src/migration.rs
  substrate/frame/democracy/src/migrations/v1.rs
  substrate/frame/examples/single-block-migrations/src/migrations/v1.rs
  substrate/frame/staking/src/migrations.rs
Labels: T2-pallets

#4403 Remove `substrate-frame-cli`
  Cargo.lock
  Cargo.toml
  substrate/bin/node/cli/Cargo.toml
  substrate/utils/frame/frame-utilities-cli/Cargo.toml
  substrate/utils/frame/frame-utilities-cli/README.md
  substrate/utils/frame/frame-utilities-cli/src/lib.rs
  substrate/utils/frame/frame-utilities-cli/src/pallet_id.rs
Labels: R0-silent

#4414 Rococo AH: undeploy trie migration
  Cargo.lock
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  prdoc/pr_4414.prdoc
Labels: T14-system_parachains

#4430 Add generate and verify logic for `AncestryProof`
  Cargo.lock
  bridges/primitives/beefy/src/lib.rs
  polkadot/node/service/src/fake_runtime_api.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/client/merkle-mountain-range/rpc/src/lib.rs
  substrate/client/merkle-mountain-range/src/test_utils.rs
  substrate/frame/merkle-mountain-range/src/lib.rs
  substrate/frame/merkle-mountain-range/src/mmr/mmr.rs
  substrate/frame/merkle-mountain-range/src/mmr/storage.rs
  substrate/frame/merkle-mountain-range/src/tests.rs
  substrate/primitives/merkle-mountain-range/Cargo.toml
  substrate/primitives/merkle-mountain-range/src/lib.rs
Labels: R0-silent, T15-bridges

#4326 `CheckWeight` SE: Check for extrinsic length + proof size combined
  prdoc/pr_4326.prdoc
  substrate/frame/system/src/extensions/check_weight.rs
Labels: T1-FRAME

#4372 [ci] Add forklift to GHA ARC
  .forklift/config.toml
  .github/workflows/quick-checks.yml
  .github/workflows/test-github-actions.yml
  .gitlab-ci.yml
Labels: R0-silent

#4035 prospective-parachains rework
  Cargo.lock
  polkadot/node/core/backing/src/lib.rs
  polkadot/node/core/backing/src/tests/prospective_parachains.rs
  polkadot/node/core/prospective-parachains/Cargo.toml
  polkadot/node/core/prospective-parachains/src/fragment_chain/mod.rs
  polkadot/node/core/prospective-parachains/src/fragment_chain/tests.rs
  polkadot/node/core/prospective-parachains/src/lib.rs
  polkadot/node/core/prospective-parachains/src/metrics.rs
  polkadot/node/core/prospective-parachains/src/tests.rs
  polkadot/node/core/provisioner/src/lib.rs
  polkadot/node/network/collator-protocol/Cargo.toml
  polkadot/node/network/collator-protocol/src/collator_side/mod.rs
  polkadot/node/network/collator-protocol/src/validator_side/collation.rs
  polkadot/node/network/collator-protocol/src/validator_side/mod.rs
  polkadot/node/network/collator-protocol/src/validator_side/tests/prospective_parachains.rs
  polkadot/node/network/statement-distribution/src/v2/candidates.rs
  polkadot/node/network/statement-distribution/src/v2/grid.rs
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  polkadot/node/network/statement-distribution/src/v2/tests/cluster.rs
  polkadot/node/network/statement-distribution/src/v2/tests/grid.rs
  polkadot/node/network/statement-distribution/src/v2/tests/mod.rs
  polkadot/node/network/statement-distribution/src/v2/tests/requests.rs
  polkadot/node/subsystem-types/src/messages.rs
  polkadot/node/subsystem-util/src/inclusion_emulator/mod.rs
  polkadot/roadmap/implementers-guide/src/node/backing/prospective-parachains.md
  polkadot/roadmap/implementers-guide/src/node/backing/statement-distribution.md
  prdoc/pr_4035.prdoc
Labels: T8-polkadot

#4441 [ci] Run check-runtime-migration in GHA
  .github/workflows/check-runtime-migration.yml
  .github/workflows/tests.yml
  .gitlab/pipeline/check.yml
  .gitlab/pipeline/test.yml
Labels: R0-silent

#4442 improve MockValidationDataInherentDataProvider to support async backing
  cumulus/client/parachain-inherent/src/mock.rs
  prdoc/pr_4442.prdoc
Labels: T0-node

#4451 Bridge: use *-uri CLI arguments when starting relayer
  bridges/testing/environments/rococo-westend/bridges_rococo_westend.sh
Labels: R0-silent, T15-bridges

#4383 Bridge: add subcommand to relay messages range
  bridges/relays/lib-substrate-relay/src/cli/relay_messages.rs
  bridges/relays/lib-substrate-relay/src/messages_lane.rs
  bridges/relays/messages/src/lib.rs
  bridges/relays/messages/src/message_race_delivery.rs
Labels: R0-silent, T15-bridges

#4452 make polkadot-parachain chain-spec extension more relaxed
  cumulus/polkadot-parachain/src/chain_spec/mod.rs
  templates/parachain/node/src/chain_spec.rs
Labels: R0-silent

#4462 backport pallet-xcm::transfer_assets_using_type_and_then() (#3695)
  polkadot/xcm/pallet-xcm/Cargo.toml
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/xcm-executor/Cargo.toml
  polkadot/xcm/xcm-executor/src/traits/asset_transfer.rs
Labels: R0-silent

#3962 Change forks pruning algorithm.
  prdoc/pr_3962.prdoc
  substrate/client/api/src/in_mem.rs
  substrate/client/api/src/leaves.rs
  substrate/client/consensus/babe/src/lib.rs
  substrate/client/consensus/babe/src/tests.rs
  substrate/client/db/src/lib.rs
  substrate/client/merkle-mountain-range/src/offchain_mmr.rs
  substrate/client/rpc-spec-v2/src/chain_head/tests.rs
  substrate/client/service/src/client/client.rs
  substrate/client/service/test/src/client/mod.rs
  substrate/primitives/blockchain/src/backend.rs
  substrate/primitives/blockchain/src/header_metadata.rs
Labels: T0-node

#3936 Please consider adding RadiumBlock bootnodes for Westend People and Westend Coretime
  cumulus/parachains/chain-specs/coretime-westend.json
Labels: R0-silent

#4463 chore: update zombienet version
  .gitlab/pipeline/zombienet.yml
  .gitlab/pipeline/zombienet/cumulus.yml
  .gitlab/pipeline/zombienet/polkadot.yml
  .gitlab/pipeline/zombienet/substrate.yml
Labels: R0-silent, T10-tests

#4464 Bump fatality crate to 0.1.1
  Cargo.lock
  polkadot/node/core/backing/Cargo.toml
  polkadot/node/core/dispute-coordinator/Cargo.toml
  polkadot/node/core/prospective-parachains/Cargo.toml
  polkadot/node/core/provisioner/Cargo.toml
  polkadot/node/network/availability-distribution/Cargo.toml
  polkadot/node/network/availability-recovery/Cargo.toml
  polkadot/node/network/bridge/Cargo.toml
  polkadot/node/network/collator-protocol/Cargo.toml
  polkadot/node/network/dispute-distribution/Cargo.toml
  polkadot/node/network/protocol/Cargo.toml
  polkadot/node/network/statement-distribution/Cargo.toml
  polkadot/node/subsystem-util/Cargo.toml
Labels: R0-silent

#4138 Update BABE README.md
  .config/lychee.toml
  polkadot/runtime/rococo/constants/src/lib.rs
  polkadot/runtime/test-runtime/constants/src/lib.rs
  polkadot/runtime/westend/constants/src/lib.rs
  substrate/bin/node/runtime/src/constants.rs
  substrate/client/consensus/babe/README.md
  substrate/client/consensus/babe/src/lib.rs
Labels: R0-silent

#3904 Introduces: Delegated Staking Pallet
  Cargo.lock
  Cargo.toml
  prdoc/pr_3904.prdoc
  substrate/frame/delegated-staking/Cargo.toml
  substrate/frame/delegated-staking/src/impls.rs
  substrate/frame/delegated-staking/src/lib.rs
  substrate/frame/delegated-staking/src/mock.rs
  substrate/frame/delegated-staking/src/tests.rs
  substrate/frame/delegated-staking/src/types.rs
  substrate/frame/staking/src/lib.rs
  substrate/primitives/staking/src/lib.rs
Labels: T1-FRAME, T2-pallets

#4458 Add OnFinality kusama bootnode
  polkadot/node/service/chain-specs/kusama.json
Labels: R0-silent

#4461 Fix extrinsics count logging in frame-system
  prdoc/pr_4461.prdoc
  substrate/frame/system/src/lib.rs
Labels: T1-FRAME

#4457 Export all public functions of `sc-service`
  prdoc/pr_4457.prdoc
  substrate/client/service/src/lib.rs
Labels: T0-node

#4479 [ci] Fix publish-subsystem-benchmarks
  .gitlab/pipeline/publish.yml
Labels: R0-silent

#4475 Deprecate `dmp-queue` pallet
  cumulus/pallets/dmp-queue/src/lib.rs
  prdoc/pr_4475.prdoc
Labels: T1-FRAME

#4392 Remove pallet::getter usage from the bounties and child-bounties pallets
  prdoc/pr_4392.prdoc
  substrate/frame/bounties/src/lib.rs
  substrate/frame/bounties/src/tests.rs
  substrate/frame/child-bounties/src/benchmarking.rs
  substrate/frame/child-bounties/src/lib.rs
  substrate/frame/child-bounties/src/tests.rs
Labels: T1-FRAME

#3952 [Runtime] Bound XCMP queue
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/parachain-system/src/mock.rs
  cumulus/pallets/xcmp-queue/src/lib.rs
  cumulus/pallets/xcmp-queue/src/migration.rs
  cumulus/pallets/xcmp-queue/src/migration/v5.rs
  cumulus/pallets/xcmp-queue/src/mock.rs
  cumulus/pallets/xcmp-queue/src/tests.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/starters/shell/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  cumulus/primitives/core/src/lib.rs
  polkadot/parachain/src/primitives.rs
  prdoc/pr_3952.prdoc
  templates/parachain/runtime/src/configs/mod.rs
Labels: T14-system_parachains

#3833 network/discovery: Add to DHT only peers that support genesis-based protocol
  substrate/client/network/src/discovery.rs
  substrate/client/network/src/litep2p/discovery.rs
Labels: A0-needs_burnin, R0-silent, I5-enhancement, D0-easy

#4481 Bridge: drop subscriptions when they are no longer required
  bridges/relays/client-substrate/src/client.rs
  bridges/relays/client-substrate/src/transaction_tracker.rs
Labels: R0-silent, T15-bridges

#4480 Demote per-peer validation slots warning to debug
  substrate/client/network/sync/src/block_announce_validator.rs
Labels: R0-silent, T0-node

#4472 Remove pallet::getter usage from the democracy pallet
  prdoc/pr_4472.prdoc
  substrate/frame/democracy/src/benchmarking.rs
  substrate/frame/democracy/src/lib.rs
  substrate/frame/democracy/src/tests.rs
  substrate/frame/democracy/src/tests/cancellation.rs
  substrate/frame/democracy/src/tests/external_proposing.rs
  substrate/frame/democracy/src/tests/fast_tracking.rs
  substrate/frame/democracy/src/tests/metadata.rs
  substrate/frame/democracy/src/tests/public_proposals.rs
  substrate/frame/democracy/src/tests/scheduling.rs
  substrate/frame/democracy/src/tests/voting.rs
Labels: T1-FRAME

#4478 Snowbridge - Ethereum Client - Reject finalized updates without a sync committee in next store period
  bridges/snowbridge/pallets/ethereum-client/src/lib.rs
  bridges/snowbridge/pallets/ethereum-client/src/tests.rs
  prdoc/pr_4478.prdoc
Labels: T15-bridges

#3393 Adds `MaxRank` Config in `pallet-core-fellowship`
  cumulus/parachains/runtimes/collectives/collectives-westend/src/ambassador/mod.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/fellowship/mod.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  prdoc/pr_3393.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/core-fellowship/src/benchmarking.rs
  substrate/frame/core-fellowship/src/lib.rs
  substrate/frame/core-fellowship/src/migration.rs
  substrate/frame/core-fellowship/src/tests/integration.rs
  substrate/frame/core-fellowship/src/tests/unit.rs
  substrate/frame/core-fellowship/src/weights.rs
Labels: T1-FRAME

#4489 Contracts: remove kitchensink dynamic parameters
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/contracts/src/weights.rs
Labels: R0-silent, T7-smart_contracts

#4492 Bridge: fixed relayer version metric value
  Cargo.lock
  bridges/relays/lib-substrate-relay/src/cli/mod.rs
  bridges/relays/utils/Cargo.toml
  bridges/relays/utils/src/initialize.rs
Labels: R0-silent, T15-bridges

#4485 Snowbridge - Ethereum Client - Reject finalized updates without a sync committee in next store period
  bridges/snowbridge/pallets/ethereum-client/src/lib.rs
  bridges/snowbridge/pallets/ethereum-client/src/tests.rs
  prdoc/pr_4478.prdoc
Labels: R0-silent, T15-bridges

#4483 Snowbridge - Ethereum Client - Reject finalized updates without a sync committee in next store period
  bridges/snowbridge/pallets/ethereum-client/src/lib.rs
  bridges/snowbridge/pallets/ethereum-client/src/tests.rs
  prdoc/pr_4478.prdoc
Labels: R0-silent, T15-bridges

#4484 Snowbridge - Ethereum Client - Reject finalized updates without a sync committee in next store period
  bridges/snowbridge/pallets/ethereum-client/src/lib.rs
  bridges/snowbridge/pallets/ethereum-client/src/tests.rs
  prdoc/pr_4478.prdoc
Labels: R0-silent, T15-bridges

#4486 Snowbridge - Ethereum Client - Reject finalized updates without a sync committee in next store period
  bridges/snowbridge/pallets/ethereum-client/src/lib.rs
  bridges/snowbridge/pallets/ethereum-client/src/tests.rs
  prdoc/pr_4478.prdoc
Labels: R0-silent, T15-bridges

#4505 Snowbridge - Ethereum Client - Public storage items
  bridges/snowbridge/pallets/ethereum-client/src/lib.rs
  bridges/snowbridge/pallets/ethereum-client/src/types.rs
Labels: R0-silent, T15-bridges

#4506 Snowbridge - Ethereum Client - Public storage items
  bridges/snowbridge/pallets/ethereum-client/src/lib.rs
  bridges/snowbridge/pallets/ethereum-client/src/types.rs
Labels: R0-silent, T15-bridges

#4507 Snowbridge - Ethereum Client - Public storage items
  bridges/snowbridge/pallets/ethereum-client/src/lib.rs
  bridges/snowbridge/pallets/ethereum-client/src/types.rs
Labels: R0-silent, T15-bridges

#4508 Snowbridge - Ethereum Client - Public storage items
  bridges/snowbridge/pallets/ethereum-client/src/lib.rs
  bridges/snowbridge/pallets/ethereum-client/src/types.rs
Labels: R0-silent, T15-bridges

#4496 xcm-emlator: Use `BlockNumberFor` instead of `parachains_common::BlockNumber=u32` (#4434)
  cumulus/xcm/xcm-emulator/src/lib.rs
Labels: R0-silent, T6-XCM

#4497 xcm-emlator: Use `BlockNumberFor` instead of `parachains_common::BlockNumber=u32` (#4434)
  cumulus/xcm/xcm-emulator/src/lib.rs
Labels: R0-silent, T6-XCM

#4498 xcm-emlator: Use `BlockNumberFor` instead of `parachains_common::BlockNumber=u32` (#4434)
  cumulus/xcm/xcm-emulator/src/lib.rs
Labels: R0-silent, T6-XCM

#4499 xcm-emlator: Use `BlockNumberFor` instead of `parachains_common::BlockNumber=u32` (#4434)
  cumulus/xcm/xcm-emulator/src/lib.rs
Labels: R0-silent, T6-XCM

#4500 xcm-emlator: Use `BlockNumberFor` instead of `parachains_common::BlockNumber=u32` (#4434)
  cumulus/xcm/xcm-emulator/src/lib.rs
Labels: R0-silent, T6-XCM

#4504 Snowbridge - Ethereum Client - Public storage items
  bridges/snowbridge/parachain/pallets/ethereum-client/src/lib.rs
  bridges/snowbridge/parachain/pallets/ethereum-client/src/types.rs
Labels: R0-silent, T15-bridges

#4490 pallet_balances: Add `try_state` for checking `Holds` and `Freezes`
  substrate/frame/balances/src/lib.rs
  substrate/frame/balances/src/tests/general_tests.rs
Labels: R0-silent, T1-FRAME

#4501 Snowbridge - Ethereum Client - Public storage items
  bridges/snowbridge/pallets/ethereum-client/src/lib.rs
  bridges/snowbridge/pallets/ethereum-client/src/types.rs
Labels: R0-silent, T15-bridges

#4503 Allow pool to be destroyed with an extra (erroneous) consumer reference on the pool account
  prdoc/pr_4503.prdoc
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/nomination-pools/src/mock.rs
  substrate/frame/nomination-pools/src/tests.rs
  substrate/frame/nomination-pools/test-staking/src/lib.rs
Labels: I2-bug

#4510 Contracts: Remove topics for internal events
  prdoc/pr_4510.prdoc
  substrate/frame/contracts/src/exec.rs
  substrate/frame/contracts/src/lib.rs
  substrate/frame/contracts/src/storage/meter.rs
  substrate/frame/contracts/src/tests.rs
  substrate/frame/contracts/src/wasm/mod.rs
Labels: T7-smart_contracts

#4515 chore: fix typos
  polkadot/node/core/approval-voting/src/persisted_entries.rs
  polkadot/node/gum/src/lib.rs
  polkadot/node/network/bridge/src/network.rs
  polkadot/node/network/dispute-distribution/src/receiver/mod.rs
Labels: R0-silent

#4512 `remote-externalities`: `rpc_child_get_keys` to use paged scraping
  substrate/utils/frame/remote-externalities/src/lib.rs
Labels: R0-silent, I5-enhancement

#4514 Remove usage of the pallet::getter macro from pallet-fast-unstake
  prdoc/pr_4514.prdoc
  substrate/frame/fast-unstake/src/lib.rs
Labels: T1-FRAME

#4524 [nomination-pools] Backport of #4503. Fix pools with extra consumer ref to be destroyed.
  prdoc/pr_4503.prdoc
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/nomination-pools/src/mock.rs
  substrate/frame/nomination-pools/src/tests.rs
  substrate/frame/nomination-pools/test-staking/src/lib.rs
Labels: A3-backport, I2-bug

#4528 [xcm]: Use latest `Versioned*` instead of `V4` + bridges doc nits
  bridges/bin/runtime-common/src/messages_benchmarking.rs
  bridges/modules/beefy/src/lib.rs
  bridges/modules/grandpa/src/lib.rs
  bridges/modules/messages/README.md
  bridges/modules/messages/src/lib.rs
  bridges/modules/parachains/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/xcm/xcm-fee-payment-runtime-api/tests/fee_estimation.rs
  polkadot/xcm/xcm-fee-payment-runtime-api/tests/mock.rs
Labels: R0-silent, T6-XCM, T15-bridges

#4533 Fixed RPC subscriptions leak when subscription stream is finished
  prdoc/pr_4533.prdoc
  substrate/client/rpc/src/utils.rs
Labels: T0-node

#4465 Bridge: added force_set_pallet_state call to pallet-bridge-grandpa
  bridges/modules/grandpa/src/benchmarking.rs
  bridges/modules/grandpa/src/lib.rs
  bridges/modules/grandpa/src/weights.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_grandpa.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_bridge_grandpa.rs
  prdoc/pr_4465.prdoc
Labels: T15-bridges

#4198 Replace `Multiaddr` & related types with substrate-specific types
  Cargo.lock
  prdoc/pr_4198.prdoc
  substrate/client/authority-discovery/src/error.rs
  substrate/client/authority-discovery/src/worker.rs
  substrate/client/authority-discovery/src/worker/addr_cache.rs
  substrate/client/authority-discovery/src/worker/tests.rs
  substrate/client/cli/src/params/node_key_params.rs
  substrate/client/mixnet/src/sync_with_runtime.rs
  substrate/client/network/src/config.rs
  substrate/client/network/src/error.rs
  substrate/client/network/src/lib.rs
  substrate/client/network/src/litep2p/discovery.rs
  substrate/client/network/src/litep2p/mod.rs
  substrate/client/network/src/litep2p/service.rs
  substrate/client/network/src/peer_store.rs
  substrate/client/network/src/protocol/notifications/service/mod.rs
  substrate/client/network/src/protocol/notifications/service/tests.rs
  substrate/client/network/src/protocol_controller.rs
  substrate/client/network/src/service.rs
  substrate/client/network/src/service/traits.rs
  substrate/client/network/sync/src/service/mock.rs
  substrate/client/network/test/src/fuzz.rs
  substrate/client/network/test/src/lib.rs
  substrate/client/network/types/Cargo.toml
  substrate/client/network/types/src/ed25519.rs
  substrate/client/network/types/src/lib.rs
  substrate/client/network/types/src/multiaddr.rs
  substrate/client/network/types/src/multiaddr/protocol.rs
  substrate/client/network/types/src/multihash.rs
  substrate/client/network/types/src/peer_id.rs
  substrate/client/telemetry/src/endpoints.rs
  substrate/client/telemetry/src/lib.rs
  substrate/client/telemetry/src/node.rs
Labels: T0-node

#4535 chore: bump zombienet version
  .gitlab/pipeline/zombienet.yml
Labels: R0-silent, T10-tests

#4532 Update subsystem benchmark baselines
  polkadot/node/core/approval-voting/benches/approval-voting-regression-bench.rs
  polkadot/node/network/availability-distribution/benches/availability-distribution-regression-bench.rs
  polkadot/node/network/availability-recovery/benches/availability-recovery-regression-bench.rs
Labels: R0-silent, T12-benchmarks

#4534 Add Extra Check in Primary Username Setter
  prdoc/pr_4534.prdoc
  substrate/frame/identity/src/lib.rs
  substrate/frame/identity/src/tests.rs
Labels: T2-pallets

#4380 Remove `parameterized-consensus-hook` feature
  bridges/snowbridge/runtime/test-common/Cargo.toml
  cumulus/pallets/parachain-system/Cargo.toml
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/xcmp-queue/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/test-utils/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/test-utils/Cargo.toml
  cumulus/parachains/runtimes/collectives/collectives-westend/Cargo.toml
  cumulus/parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-rococo/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-westend/Cargo.toml
  cumulus/parachains/runtimes/glutton/glutton-westend/Cargo.toml
  cumulus/parachains/runtimes/people/people-rococo/Cargo.toml
  cumulus/parachains/runtimes/people/people-westend/Cargo.toml
  cumulus/parachains/runtimes/starters/seedling/Cargo.toml
  cumulus/parachains/runtimes/starters/shell/Cargo.toml
  cumulus/parachains/runtimes/test-utils/Cargo.toml
  cumulus/parachains/runtimes/testing/penpal/Cargo.toml
  cumulus/parachains/runtimes/testing/rococo-parachain/Cargo.toml
  cumulus/test/runtime/Cargo.toml
  cumulus/test/service/Cargo.toml
  docs/sdk/Cargo.toml
  prdoc/pr_4380.prdoc
  templates/parachain/runtime/Cargo.toml
Labels: T9-cumulus

#4538 [Backport] Version bumps and prdocs reordering from 1.12.0
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot/node/primitives/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/1.12.0/pr_2226.prdoc
  prdoc/1.12.0/pr_3444.prdoc
  prdoc/1.12.0/pr_3701.prdoc
  prdoc/1.12.0/pr_3865.prdoc
  prdoc/1.12.0/pr_3872.prdoc
  prdoc/1.12.0/pr_3904.prdoc
  prdoc/1.12.0/pr_3962.prdoc
  prdoc/1.12.0/pr_3964.prdoc
  prdoc/1.12.0/pr_4034.prdoc
  prdoc/1.12.0/pr_4035.prdoc
  prdoc/1.12.0/pr_4091.prdoc
  prdoc/1.12.0/pr_4102.prdoc
  prdoc/1.12.0/pr_4157.prdoc
  prdoc/1.12.0/pr_4175.prdoc
  prdoc/1.12.0/pr_4185.prdoc
  prdoc/1.12.0/pr_4202.prdoc
  prdoc/1.12.0/pr_4211.prdoc
  prdoc/1.12.0/pr_4213.prdoc
  prdoc/1.12.0/pr_4220.prdoc
  prdoc/1.12.0/pr_4281.prdoc
  prdoc/1.12.0/pr_4295.prdoc
  prdoc/1.12.0/pr_4301.prdoc
  prdoc/1.12.0/pr_4302.prdoc
  prdoc/1.12.0/pr_4311.prdoc
  prdoc/1.12.0/pr_4312.prdoc
  prdoc/1.12.0/pr_4326.prdoc
  prdoc/1.12.0/pr_4329.prdoc
  prdoc/1.12.0/pr_4346.prdoc
  prdoc/1.12.0/pr_4349.prdoc
  prdoc/1.12.0/pr_4364.prdoc
  prdoc/1.12.0/pr_4394.prdoc
  prdoc/1.12.0/pr_4406.prdoc
  prdoc/1.12.0/pr_4414.prdoc
  prdoc/1.12.0/pr_4417.prdoc
  prdoc/1.12.0/pr_4426.prdoc
  prdoc/1.12.0/pr_4442.prdoc
  prdoc/1.12.0/pr_4457.prdoc
  prdoc/1.12.0/pr_4461.prdoc
Labels: R0-silent, A3-backport, D0-easy

#4539 fixed link
  bridges/modules/grandpa/README.md
Labels: R0-silent, T11-documentation

#4541 rustls: Disable logging again
  prdoc/pr_4541.prdoc
  substrate/client/tracing/src/logging/mod.rs
Labels: T0-node

#3905 Refactor Nomination Pool to support multiple staking strategies
  Cargo.lock
  Cargo.toml
  polkadot/runtime/westend/Cargo.toml
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/pallet_nomination_pools.rs
  prdoc/pr_3905.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/delegated-staking/Cargo.toml
  substrate/frame/delegated-staking/src/impls.rs
  substrate/frame/delegated-staking/src/lib.rs
  substrate/frame/delegated-staking/src/mock.rs
  substrate/frame/delegated-staking/src/tests.rs
  substrate/frame/delegated-staking/src/types.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/lib.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
  substrate/frame/nomination-pools/benchmarking/Cargo.toml
  substrate/frame/nomination-pools/benchmarking/src/inner.rs
  substrate/frame/nomination-pools/benchmarking/src/lib.rs
  substrate/frame/nomination-pools/benchmarking/src/mock.rs
  substrate/frame/nomination-pools/fuzzer/src/call.rs
  substrate/frame/nomination-pools/src/adapter.rs
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/nomination-pools/src/migration.rs
  substrate/frame/nomination-pools/src/mock.rs
  substrate/frame/nomination-pools/src/tests.rs
  substrate/frame/nomination-pools/src/weights.rs
  substrate/frame/nomination-pools/test-delegate-stake/Cargo.toml
  substrate/frame/nomination-pools/test-delegate-stake/src/lib.rs
  substrate/frame/nomination-pools/test-delegate-stake/src/mock.rs
  substrate/frame/nomination-pools/test-transfer-stake/Cargo.toml
  substrate/frame/nomination-pools/test-transfer-stake/src/lib.rs
  substrate/frame/nomination-pools/test-transfer-stake/src/mock.rs
  substrate/frame/staking/src/ledger.rs
  substrate/frame/staking/src/lib.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/slashing.rs
  substrate/primitives/staking/src/lib.rs
Labels: T1-FRAME, T2-pallets

#4546 Fix README.md Logo URL
  README.md
Labels: R0-silent

#4548 Fix bridges grandpa benchmarks (#2577)
  bridges/modules/grandpa/src/benchmarking.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_grandpa.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_bridge_grandpa.rs
Labels: R0-silent, T15-bridges

#4233 Contracts: Rework host fn benchmarks
  prdoc/pr_4233.prdoc
  substrate/frame/contracts/README.md
  substrate/frame/contracts/proc-macro/src/lib.rs
  substrate/frame/contracts/src/benchmarking/call_builder.rs
  substrate/frame/contracts/src/benchmarking/code.rs
  substrate/frame/contracts/src/benchmarking/mod.rs
  substrate/frame/contracts/src/exec.rs
  substrate/frame/contracts/src/lib.rs
  substrate/frame/contracts/src/schedule.rs
  substrate/frame/contracts/src/tests.rs
  substrate/frame/contracts/src/wasm/mod.rs
  substrate/frame/contracts/src/wasm/runtime.rs
  substrate/frame/contracts/src/weights.rs
Labels: T7-smart_contracts

#4550 Define `OpaqueValue`
  substrate/primitives/consensus/beefy/src/lib.rs
  substrate/primitives/consensus/grandpa/src/lib.rs
  substrate/primitives/runtime/src/lib.rs
Labels: R0-silent, T15-bridges

#4558 Mention new XCM docs in sdk docs
  Cargo.lock
  docs/sdk/Cargo.toml
  docs/sdk/src/polkadot_sdk/xcm.rs
Labels: R0-silent, T6-XCM

#4562 Use polkadot-ckb-merkle-mountain-range dependency
  Cargo.lock
  substrate/primitives/merkle-mountain-range/Cargo.toml
Labels: R0-silent, T15-bridges

#4543 Attempt to avoid specifying `BlockHashCount` for different `mocking::{MockBlock, MockBlockU32, MockBlockU128}`
  bridges/bin/runtime-common/src/mock.rs
  bridges/snowbridge/pallets/inbound-queue/src/mock.rs
  bridges/snowbridge/pallets/outbound-queue/src/mock.rs
  bridges/snowbridge/pallets/system/src/mock.rs
  cumulus/pallets/collator-selection/src/mock.rs
  cumulus/pallets/parachain-system/src/mock.rs
  cumulus/pallets/xcmp-queue/src/mock.rs
  cumulus/parachains/common/src/impls.rs
  cumulus/parachains/pallets/collective-content/src/mock.rs
  polkadot/runtime/common/src/assigned_slots/mod.rs
  polkadot/runtime/common/src/auctions.rs
  polkadot/runtime/common/src/crowdloan/mod.rs
  polkadot/runtime/common/src/impls.rs
  polkadot/runtime/common/src/integration_tests.rs
  polkadot/runtime/common/src/paras_registrar/mod.rs
  polkadot/runtime/common/src/purchase.rs
  polkadot/runtime/common/src/slots/mod.rs
  polkadot/runtime/parachains/src/mock.rs
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/xcm-builder/src/tests/pay/mock.rs
  polkadot/xcm/xcm-builder/tests/mock/mod.rs
  substrate/frame/alliance/src/mock.rs
  substrate/frame/contracts/mock-network/src/parachain.rs
  substrate/frame/contracts/mock-network/src/relay_chain.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
  substrate/frame/examples/basic/src/tests.rs
  substrate/frame/examples/dev-mode/src/tests.rs
  substrate/frame/examples/offchain-worker/src/tests.rs
  substrate/frame/im-online/src/mock.rs
  substrate/frame/indices/src/mock.rs
  substrate/frame/multisig/src/tests.rs
  substrate/frame/offences/src/mock.rs
  substrate/frame/paged-list/src/mock.rs
  substrate/frame/safe-mode/src/mock.rs
  substrate/frame/state-trie-migration/src/lib.rs
  substrate/frame/support/test/tests/final_keys.rs
  substrate/frame/support/test/tests/genesisconfig.rs
  substrate/frame/support/test/tests/instance.rs
  substrate/frame/support/test/tests/issue2219.rs
  substrate/frame/support/test/tests/origin.rs
  substrate/frame/support/test/tests/pallet.rs
  substrate/frame/support/test/tests/pallet_instance.rs
  substrate/frame/support/test/tests/pallet_outer_enums_explicit.rs
  substrate/frame/support/test/tests/pallet_outer_enums_implicit.rs
  substrate/frame/support/test/tests/pallet_ui/pass/dev_mode_valid.rs
  substrate/frame/support/test/tests/runtime.rs
  substrate/frame/support/test/tests/runtime_legacy_ordering.rs
  substrate/frame/support/test/tests/runtime_metadata.rs
  substrate/frame/support/test/tests/storage_layers.rs
  substrate/frame/support/test/tests/storage_transaction.rs
  substrate/frame/support/test/tests/versioned_migration.rs
  substrate/frame/system/benches/bench.rs
  substrate/frame/system/src/lib.rs
  substrate/frame/transaction-payment/asset-conversion-tx-payment/src/mock.rs
  substrate/frame/transaction-payment/asset-tx-payment/src/mock.rs
  substrate/frame/transaction-payment/src/mock.rs
  substrate/frame/transaction-storage/src/mock.rs
  substrate/frame/tx-pause/src/mock.rs
  templates/parachain/pallets/template/src/mock.rs
  templates/solochain/pallets/template/src/mock.rs
Labels: R0-silent

#4560 Remove litep2p git dependency
  Cargo.lock
  substrate/client/network/Cargo.toml
  substrate/client/network/types/Cargo.toml
Labels: R0-silent

#3935 Polkadot-SDK Umbrella Crate
  .config/lychee.toml
  .config/zepter.yaml
  .github/workflows/check-features.yml
  .github/workflows/checks-quick.yml
  Cargo.lock
  Cargo.toml
  cumulus/pallets/parachain-system/src/validate_block/implementation.rs
  docs/sdk/Cargo.toml
  docs/sdk/src/reference_docs/mod.rs
  docs/sdk/src/reference_docs/umbrella_crate.rs
  polkadot/runtime/parachains/src/inclusion/mod.rs
  prdoc/pr_3935.prdoc
  scripts/generate-umbrella.py
  substrate/bin/node/cli/Cargo.toml
  substrate/bin/node/cli/benches/block_production.rs
  substrate/bin/node/cli/benches/executor.rs
  substrate/bin/node/cli/benches/transaction_pool.rs
  substrate/bin/node/cli/bin/main.rs
  substrate/bin/node/cli/build.rs
  substrate/bin/node/cli/src/benchmarking.rs
  substrate/bin/node/cli/src/chain_spec.rs
  substrate/bin/node/cli/src/cli.rs
  substrate/bin/node/cli/src/command.rs
  substrate/bin/node/cli/src/service.rs
  substrate/bin/node/cli/tests/basic.rs
  substrate/bin/node/cli/tests/common.rs
  substrate/bin/node/cli/tests/fees.rs
  substrate/bin/node/cli/tests/submit_transaction.rs
  substrate/bin/node/runtime/Cargo.toml
  substrate/bin/node/runtime/src/assets_api.rs
  substrate/bin/node/runtime/src/impls.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/client/chain-spec/derive/src/impls.rs
  substrate/frame/election-provider-support/solution-type/src/lib.rs
  substrate/frame/staking/reward-curve/src/lib.rs
  substrate/frame/support/procedural/tools/src/lib.rs
  substrate/primitives/api/proc-macro/src/utils.rs
  umbrella/Cargo.toml
  umbrella/src/lib.rs
Labels: T8-polkadot

#4399 availability-recovery: bump chunk fetch threshold to 1MB for Polkadot and 4MB for Kusama + testnets
  polkadot/node/network/availability-recovery/src/lib.rs
  polkadot/node/network/availability-recovery/src/tests.rs
  polkadot/node/service/src/lib.rs
  polkadot/node/service/src/overseer.rs
Labels: R0-silent, T0-node

#4567 Avoid using `xcm::v4` and use latest instead for AssetHub benchmarks
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
Labels: R0-silent, T6-XCM

#4549 Bridge: check submit_finality_proof limits before submission
  bridges/modules/grandpa/src/call_ext.rs
  bridges/primitives/header-chain/src/lib.rs
  bridges/relays/client-substrate/src/error.rs
  bridges/relays/lib-substrate-relay/src/finality/target.rs
  bridges/relays/lib-substrate-relay/src/finality_base/engine.rs
  bridges/relays/lib-substrate-relay/src/on_demand/headers.rs
Labels: R0-silent, T15-bridges

#4453 Bridge: add subcommand to relay messages delivery confirmation
  bridges/relays/lib-substrate-relay/src/cli/relay_messages.rs
  bridges/relays/lib-substrate-relay/src/messages_lane.rs
  bridges/relays/lib-substrate-relay/src/messages_target.rs
  bridges/relays/messages/src/lib.rs
  bridges/relays/messages/src/message_race_receiving.rs
Labels: R0-silent, T15-bridges

#4353 Add release version to commits and branch names of template synchronization job
  .github/workflows/misc-sync-templates.yml
Labels: R0-silent, T11-documentation

#4592 Backport 1.12.0: check-weight: Disable total pov size check for mandatory extrinsics
  prdoc/1.12.0/pr_4571.prdoc
  substrate/frame/system/src/extensions/check_weight.rs
Labels: R0-silent

#4593 Make markdown lint CI job pass
  README.md
Labels: R0-silent

#4576 `CheckMetadataHash` extension backport to 1.3.0
  .gitlab/pipeline/test.yml
  Cargo.lock
  Cargo.toml
  cumulus/parachain-template/runtime/Cargo.toml
  cumulus/parachain-template/runtime/build.rs
  cumulus/parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/xcm_fee_estimation.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/build.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/build.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-kusama/build.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/build.rs
  cumulus/parachains/runtimes/glutton/glutton-kusama/build.rs
  cumulus/parachains/runtimes/testing/penpal/build.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/build.rs
  cumulus/test/runtime/build.rs
  polkadot/node/service/Cargo.toml
  polkadot/node/service/src/benchmarking.rs
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/rococo/build.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/build.rs
  polkadot/runtime/westend/Cargo.toml
  polkadot/runtime/westend/build.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_4177.prdoc
  prdoc/pr_4274.prdoc
  substrate/bin/node-template/runtime/build.rs
  substrate/bin/node/cli/Cargo.toml
  substrate/bin/node/cli/src/service.rs
  substrate/bin/node/executor/benches/bench.rs
  substrate/bin/node/executor/tests/common.rs
  substrate/bin/node/runtime/Cargo.toml
  substrate/bin/node/runtime/build.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/bin/node/testing/Cargo.toml
  substrate/bin/node/testing/src/bench.rs
  substrate/bin/node/testing/src/keyring.rs
  substrate/client/executor/wasmtime/src/lib.rs
  substrate/frame/metadata-hash-extension/Cargo.toml
  substrate/frame/metadata-hash-extension/src/lib.rs
  substrate/frame/metadata-hash-extension/src/tests.rs
  substrate/test-utils/runtime/Cargo.toml
  substrate/test-utils/runtime/build.rs
  substrate/test-utils/runtime/src/extrinsic.rs
  substrate/test-utils/runtime/src/lib.rs
  substrate/utils/wasm-builder/Cargo.toml
  substrate/utils/wasm-builder/src/builder.rs
  substrate/utils/wasm-builder/src/lib.rs
  substrate/utils/wasm-builder/src/metadata_hash.rs
  substrate/utils/wasm-builder/src/wasm_project.rs
  templates/parachain/runtime/src/lib.rs
Labels: R0-silent

#4577 `CheckMetadataHash` extension backport to 1.4.0
  .gitlab/pipeline/test.yml
  Cargo.lock
  Cargo.toml
  cumulus/parachain-template/runtime/Cargo.toml
  cumulus/parachain-template/runtime/build.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/xcm_fee_estimation.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/build.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/build.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/build.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/build.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/build.rs
  cumulus/parachains/runtimes/testing/penpal/build.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/build.rs
  cumulus/test/runtime/build.rs
  polkadot/node/service/Cargo.toml
  polkadot/node/service/src/benchmarking.rs
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/rococo/build.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/build.rs
  polkadot/runtime/westend/Cargo.toml
  polkadot/runtime/westend/build.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_4177.prdoc
  prdoc/pr_4274.prdoc
  substrate/bin/minimal/runtime/build.rs
  substrate/bin/node-template/runtime/build.rs
  substrate/bin/node/cli/Cargo.toml
  substrate/bin/node/cli/src/service.rs
  substrate/bin/node/executor/benches/bench.rs
  substrate/bin/node/executor/tests/common.rs
  substrate/bin/node/runtime/Cargo.toml
  substrate/bin/node/runtime/build.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/bin/node/testing/Cargo.toml
  substrate/bin/node/testing/src/bench.rs
  substrate/bin/node/testing/src/keyring.rs
  substrate/client/executor/wasmtime/src/lib.rs
  substrate/frame/metadata-hash-extension/Cargo.toml
  substrate/frame/metadata-hash-extension/src/lib.rs
  substrate/frame/metadata-hash-extension/src/tests.rs
  substrate/test-utils/runtime/Cargo.toml
  substrate/test-utils/runtime/build.rs
  substrate/test-utils/runtime/src/extrinsic.rs
  substrate/test-utils/runtime/src/lib.rs
  substrate/utils/wasm-builder/Cargo.toml
  substrate/utils/wasm-builder/src/builder.rs
  substrate/utils/wasm-builder/src/lib.rs
  substrate/utils/wasm-builder/src/metadata_hash.rs
  substrate/utils/wasm-builder/src/wasm_project.rs
  templates/parachain/runtime/src/lib.rs
Labels: R0-silent

#4570 network: Update litep2p to v0.5.0
  Cargo.lock
  substrate/client/network/Cargo.toml
  substrate/client/network/src/litep2p/discovery.rs
  substrate/client/network/src/litep2p/mod.rs
  substrate/client/network/types/Cargo.toml
Labels: A1-insubstantial, R0-silent, I5-enhancement, D0-easy

#4597 chain-spec-builder: help updated
  substrate/bin/utils/chain-spec-builder/src/lib.rs
Labels: R0-silent

#4571 check-weight: Disable total pov size check for mandatory extrinsics
  prdoc/pr_4571.prdoc
  substrate/frame/system/src/extensions/check_weight.rs
Labels: T1-FRAME

#4578 `CheckMetadataHash` extension backport to 1.5.0
  .gitlab/pipeline/test.yml
  Cargo.lock
  Cargo.toml
  cumulus/parachain-template/runtime/Cargo.toml
  cumulus/parachain-template/runtime/build.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/xcm_fee_estimation.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/build.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/build.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/build.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/build.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/build.rs
  cumulus/parachains/runtimes/testing/penpal/build.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/build.rs
  cumulus/test/runtime/build.rs
  polkadot/node/service/Cargo.toml
  polkadot/node/service/src/benchmarking.rs
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/rococo/build.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/build.rs
  polkadot/runtime/westend/Cargo.toml
  polkadot/runtime/westend/build.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_4177.prdoc
  prdoc/pr_4274.prdoc
  substrate/bin/minimal/runtime/build.rs
  substrate/bin/node-template/runtime/build.rs
  substrate/bin/node/cli/Cargo.toml
  substrate/bin/node/cli/benches/executor.rs
  substrate/bin/node/cli/src/service.rs
  substrate/bin/node/cli/tests/common.rs
  substrate/bin/node/runtime/Cargo.toml
  substrate/bin/node/runtime/build.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/bin/node/testing/Cargo.toml
  substrate/bin/node/testing/src/bench.rs
  substrate/bin/node/testing/src/keyring.rs
  substrate/client/executor/wasmtime/src/lib.rs
  substrate/frame/metadata-hash-extension/Cargo.toml
  substrate/frame/metadata-hash-extension/src/lib.rs
  substrate/frame/metadata-hash-extension/src/tests.rs
  substrate/primitives/api/Cargo.toml
  substrate/primitives/api/src/lib.rs
  substrate/test-utils/runtime/Cargo.toml
  substrate/test-utils/runtime/build.rs
  substrate/test-utils/runtime/src/extrinsic.rs
  substrate/test-utils/runtime/src/lib.rs
  substrate/utils/wasm-builder/Cargo.toml
  substrate/utils/wasm-builder/src/builder.rs
  substrate/utils/wasm-builder/src/lib.rs
  substrate/utils/wasm-builder/src/metadata_hash.rs
  substrate/utils/wasm-builder/src/wasm_project.rs
  templates/parachain/runtime/src/lib.rs
Labels: R0-silent

#3863 [subsystem-benchmarks] Add statement-distribution benchmarks
  .gitlab/pipeline/publish.yml
  .gitlab/pipeline/test.yml
  Cargo.lock
  polkadot/node/network/statement-distribution/Cargo.toml
  polkadot/node/network/statement-distribution/benches/statement-distribution-regression-bench.rs
  polkadot/node/network/statement-distribution/src/lib.rs
  polkadot/node/subsystem-bench/Cargo.toml
  polkadot/node/subsystem-bench/examples/statement_distribution.yaml
  polkadot/node/subsystem-bench/src/cli/subsystem-bench.rs
  polkadot/node/subsystem-bench/src/lib/approval/mod.rs
  polkadot/node/subsystem-bench/src/lib/availability/mod.rs
  polkadot/node/subsystem-bench/src/lib/configuration.rs
  polkadot/node/subsystem-bench/src/lib/lib.rs
  polkadot/node/subsystem-bench/src/lib/mock/av_store.rs
  polkadot/node/subsystem-bench/src/lib/mock/candidate_backing.rs
  polkadot/node/subsystem-bench/src/lib/mock/mod.rs
  polkadot/node/subsystem-bench/src/lib/mock/network_bridge.rs
  polkadot/node/subsystem-bench/src/lib/mock/prospective_parachains.rs
  polkadot/node/subsystem-bench/src/lib/mock/runtime_api.rs
  polkadot/node/subsystem-bench/src/lib/network.rs
  polkadot/node/subsystem-bench/src/lib/statement/mod.rs
  polkadot/node/subsystem-bench/src/lib/statement/test_state.rs
Labels: R0-silent, T12-benchmarks

#4581 `CheckMetadataHash` extension backport to 1.6.0
  .gitlab/pipeline/test.yml
  Cargo.lock
  Cargo.toml
  cumulus/parachain-template/runtime/Cargo.toml
  cumulus/parachain-template/runtime/build.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/xcm_fee_estimation.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/build.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/build.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/build.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/build.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/build.rs
  cumulus/parachains/runtimes/testing/penpal/build.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/build.rs
  cumulus/test/runtime/build.rs
  polkadot/node/service/Cargo.toml
  polkadot/node/service/src/benchmarking.rs
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/rococo/build.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/build.rs
  polkadot/runtime/westend/Cargo.toml
  polkadot/runtime/westend/build.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_4177.prdoc
  prdoc/pr_4274.prdoc
  substrate/bin/minimal/runtime/build.rs
  substrate/bin/node-template/runtime/build.rs
  substrate/bin/node/cli/Cargo.toml
  substrate/bin/node/cli/benches/executor.rs
  substrate/bin/node/cli/src/service.rs
  substrate/bin/node/cli/tests/common.rs
  substrate/bin/node/runtime/Cargo.toml
  substrate/bin/node/runtime/build.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/bin/node/testing/Cargo.toml
  substrate/bin/node/testing/src/bench.rs
  substrate/bin/node/testing/src/keyring.rs
  substrate/client/executor/wasmtime/src/lib.rs
  substrate/frame/metadata-hash-extension/Cargo.toml
  substrate/frame/metadata-hash-extension/src/lib.rs
  substrate/frame/metadata-hash-extension/src/tests.rs
  substrate/test-utils/runtime/Cargo.toml
  substrate/test-utils/runtime/build.rs
  substrate/test-utils/runtime/src/extrinsic.rs
  substrate/test-utils/runtime/src/lib.rs
  substrate/utils/wasm-builder/Cargo.toml
  substrate/utils/wasm-builder/src/builder.rs
  substrate/utils/wasm-builder/src/lib.rs
  substrate/utils/wasm-builder/src/metadata_hash.rs
  substrate/utils/wasm-builder/src/wasm_project.rs
  templates/parachain/runtime/src/lib.rs
Labels: R0-silent

#4410 `sc-chain-spec`: deprecated code removed
  Cargo.lock
  cumulus/polkadot-parachain/src/chain_spec/mod.rs
  cumulus/polkadot-parachain/src/command.rs
  cumulus/test/service/src/chain_spec.rs
  polkadot/node/service/src/chain_spec.rs
  polkadot/node/service/src/lib.rs
  polkadot/node/test/service/src/chain_spec.rs
  prdoc/pr_4410.prdoc
  substrate/bin/node/cli/src/chain_spec.rs
  substrate/client/chain-spec/Cargo.toml
  substrate/client/chain-spec/res/chain_spec_as_json_fails_with_invalid_config.err
  substrate/client/chain-spec/src/chain_spec.rs
  substrate/client/chain-spec/src/lib.rs
  substrate/client/cli/src/commands/insert_key.rs
  substrate/client/cli/src/runner.rs
  substrate/client/consensus/grandpa/src/communication/tests.rs
  substrate/client/service/src/lib.rs
  substrate/client/service/test/src/lib.rs
  templates/minimal/node/src/chain_spec.rs
  templates/parachain/node/src/chain_spec.rs
  templates/solochain/node/src/chain_spec.rs
Labels: T0-node

#4598 Remove workspace lints from templates
  .github/workflows/misc-sync-templates.yml
  templates/minimal/Cargo.toml
  templates/minimal/node/Cargo.toml
  templates/minimal/node/src/cli.rs
  templates/minimal/node/src/service.rs
  templates/minimal/pallets/template/Cargo.toml
  templates/minimal/runtime/Cargo.toml
  templates/parachain/node/Cargo.toml
  templates/parachain/node/src/cli.rs
  templates/parachain/node/src/command.rs
  templates/parachain/node/src/service.rs
  templates/parachain/pallets/template/Cargo.toml
  templates/parachain/pallets/template/src/benchmarking.rs
  templates/parachain/runtime/Cargo.toml
  templates/solochain/node/Cargo.toml
  templates/solochain/node/src/command.rs
  templates/solochain/pallets/template/Cargo.toml
  templates/solochain/pallets/template/src/benchmarking.rs
  templates/solochain/runtime/Cargo.toml
Labels: R0-silent

#4579 `CheckMetadataHash` extension backport to 1.7.0
  .gitlab/pipeline/test.yml
  Cargo.lock
  Cargo.toml
  cumulus/parachain-template/runtime/Cargo.toml
  cumulus/parachain-template/runtime/build.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/xcm_fee_estimation.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/build.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/build.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/build.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/build.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/build.rs
  cumulus/parachains/runtimes/testing/penpal/build.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/build.rs
  cumulus/test/runtime/build.rs
  polkadot/node/service/Cargo.toml
  polkadot/node/service/src/benchmarking.rs
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/rococo/build.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/build.rs
  polkadot/runtime/westend/Cargo.toml
  polkadot/runtime/westend/build.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_4177.prdoc
  prdoc/pr_4274.prdoc
  substrate/bin/minimal/runtime/build.rs
  substrate/bin/node-template/runtime/build.rs
  substrate/bin/node/cli/Cargo.toml
  substrate/bin/node/cli/benches/executor.rs
  substrate/bin/node/cli/src/service.rs
  substrate/bin/node/cli/tests/common.rs
  substrate/bin/node/runtime/Cargo.toml
  substrate/bin/node/runtime/build.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/bin/node/testing/Cargo.toml
  substrate/bin/node/testing/src/bench.rs
  substrate/bin/node/testing/src/keyring.rs
  substrate/client/executor/wasmtime/src/lib.rs
  substrate/frame/metadata-hash-extension/Cargo.toml
  substrate/frame/metadata-hash-extension/src/lib.rs
  substrate/frame/metadata-hash-extension/src/tests.rs
  substrate/test-utils/runtime/Cargo.toml
  substrate/test-utils/runtime/build.rs
  substrate/test-utils/runtime/src/extrinsic.rs
  substrate/test-utils/runtime/src/lib.rs
  substrate/utils/wasm-builder/Cargo.toml
  substrate/utils/wasm-builder/src/builder.rs
  substrate/utils/wasm-builder/src/lib.rs
  substrate/utils/wasm-builder/src/metadata_hash.rs
  substrate/utils/wasm-builder/src/wasm_project.rs
  templates/parachain/runtime/src/lib.rs
Labels: R0-silent

#4540 [subsytem-bench] Remove redundant banchmark_name param
  polkadot/node/core/approval-voting/benches/approval-voting-regression-bench.rs
  polkadot/node/network/availability-distribution/benches/availability-distribution-regression-bench.rs
  polkadot/node/network/availability-recovery/benches/availability-recovery-regression-bench.rs
  polkadot/node/network/statement-distribution/benches/statement-distribution-regression-bench.rs
  polkadot/node/subsystem-bench/src/cli/subsystem-bench.rs
  polkadot/node/subsystem-bench/src/lib/approval/mod.rs
  polkadot/node/subsystem-bench/src/lib/availability/mod.rs
  polkadot/node/subsystem-bench/src/lib/environment.rs
  polkadot/node/subsystem-bench/src/lib/statement/mod.rs
  polkadot/node/subsystem-bench/src/lib/usage.rs
Labels: R0-silent, T12-benchmarks

#4580 `CheckMetadataHash` extension backport to 1.8.0
  .github/workflows/check-semver.yml
  .gitlab/pipeline/test.yml
  Cargo.lock
  Cargo.toml
  cumulus/parachain-template/runtime/Cargo.toml
  cumulus/parachain-template/runtime/build.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/xcm_fee_estimation.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/build.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/build.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/build.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/build.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/build.rs
  cumulus/parachains/runtimes/testing/penpal/build.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/build.rs
  cumulus/test/runtime/build.rs
  polkadot/node/service/Cargo.toml
  polkadot/node/service/src/benchmarking.rs
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/rococo/build.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/build.rs
  polkadot/runtime/westend/Cargo.toml
  polkadot/runtime/westend/build.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_4177.prdoc
  prdoc/pr_4274.prdoc
  substrate/bin/minimal/runtime/build.rs
  substrate/bin/node-template/runtime/build.rs
  substrate/bin/node/cli/Cargo.toml
  substrate/bin/node/cli/benches/executor.rs
  substrate/bin/node/cli/src/service.rs
  substrate/bin/node/cli/tests/common.rs
  substrate/bin/node/runtime/Cargo.toml
  substrate/bin/node/runtime/build.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/bin/node/testing/Cargo.toml
  substrate/bin/node/testing/src/bench.rs
  substrate/bin/node/testing/src/keyring.rs
  substrate/client/executor/wasmtime/src/lib.rs
  substrate/frame/metadata-hash-extension/Cargo.toml
  substrate/frame/metadata-hash-extension/src/lib.rs
  substrate/frame/metadata-hash-extension/src/tests.rs
  substrate/test-utils/runtime/Cargo.toml
  substrate/test-utils/runtime/build.rs
  substrate/test-utils/runtime/src/extrinsic.rs
  substrate/test-utils/runtime/src/lib.rs
  substrate/utils/wasm-builder/Cargo.toml
  substrate/utils/wasm-builder/src/builder.rs
  substrate/utils/wasm-builder/src/lib.rs
  substrate/utils/wasm-builder/src/metadata_hash.rs
  substrate/utils/wasm-builder/src/wasm_project.rs
  templates/parachain/runtime/src/lib.rs
Labels: R0-silent

#4582 `CheckMetadataHash` extension backport to 1.9.0
  .github/workflows/check-semver.yml
  .gitlab/pipeline/test.yml
  Cargo.lock
  Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/xcm_fee_estimation.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/build.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/build.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/build.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/build.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/build.rs
  cumulus/parachains/runtimes/testing/penpal/build.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/build.rs
  cumulus/test/runtime/build.rs
  docs/sdk/Cargo.toml
  polkadot/node/service/Cargo.toml
  polkadot/node/service/src/benchmarking.rs
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/rococo/build.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/build.rs
  polkadot/runtime/westend/Cargo.toml
  polkadot/runtime/westend/build.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_4177.prdoc
  prdoc/pr_4274.prdoc
  substrate/bin/node/cli/Cargo.toml
  substrate/bin/node/cli/benches/executor.rs
  substrate/bin/node/cli/src/service.rs
  substrate/bin/node/cli/tests/common.rs
  substrate/bin/node/runtime/Cargo.toml
  substrate/bin/node/runtime/build.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/bin/node/testing/Cargo.toml
  substrate/bin/node/testing/src/bench.rs
  substrate/bin/node/testing/src/keyring.rs
  substrate/client/executor/wasmtime/src/lib.rs
  substrate/frame/metadata-hash-extension/Cargo.toml
  substrate/frame/metadata-hash-extension/src/lib.rs
  substrate/frame/metadata-hash-extension/src/tests.rs
  substrate/test-utils/runtime/Cargo.toml
  substrate/test-utils/runtime/build.rs
  substrate/test-utils/runtime/src/extrinsic.rs
  substrate/test-utils/runtime/src/lib.rs
  substrate/utils/wasm-builder/Cargo.toml
  substrate/utils/wasm-builder/src/builder.rs
  substrate/utils/wasm-builder/src/lib.rs
  substrate/utils/wasm-builder/src/metadata_hash.rs
  substrate/utils/wasm-builder/src/wasm_project.rs
  templates/minimal/runtime/build.rs
  templates/parachain/runtime/Cargo.toml
  templates/parachain/runtime/build.rs
  templates/parachain/runtime/src/lib.rs
  templates/solochain/runtime/build.rs
Labels: R0-silent

#4572 [CI] Deny adding git deps
  .github/scripts/deny-git-deps.py
  .github/workflows/checks-quick.yml
Labels: R0-silent

#4587 Add metric to measure the time it takes to gather enough assignments
  polkadot/node/core/approval-voting/src/import.rs
  polkadot/node/core/approval-voting/src/lib.rs
  polkadot/node/core/approval-voting/src/tests.rs
Labels: R0-silent, T0-node

#4555 parachain-inherent: Make `para_id` more prominent
  cumulus/client/parachain-inherent/src/mock.rs
  prdoc/pr_4555.prdoc
Labels: T9-cumulus

#4599 Filter workspace dependencies in the templates
  .github/workflows/misc-sync-templates.yml
Labels: R0-silent

#4249 Moves runtime macro out of experimental flag
  prdoc/pr_4249.prdoc
  substrate/frame/support/procedural/src/lib.rs
  substrate/frame/support/procedural/src/runtime/mod.rs
  substrate/frame/support/src/lib.rs
Labels: T1-FRAME

#4557 Add omni bencher & chain-spec-builder bins to release
  .github/workflows/release-30_publish_release_draft.yml
Labels: R0-silent

#4518 Publish `chain-spec-builder`
  Cargo.lock
  substrate/bin/utils/chain-spec-builder/Cargo.toml
Labels: R0-silent

#4623 Update README.md
  README.md
Labels: R0-silent, T11-documentation

#4621 Change `XcmDryRunApi::dry_run_extrinsic` to take a call instead
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/xcm_fee_estimation.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  cumulus/xcm/xcm-emulator/src/lib.rs
  polkadot/node/service/src/fake_runtime_api.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/xcm-fee-payment-runtime-api/src/dry_run.rs
  polkadot/xcm/xcm-fee-payment-runtime-api/tests/fee_estimation.rs
  polkadot/xcm/xcm-fee-payment-runtime-api/tests/mock.rs
  prdoc/pr_4621.prdoc
Labels: T6-XCM

#4521 Broker new price adapter
  Cargo.lock
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/coretime.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_broker.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/coretime.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/pallet_broker.rs
  prdoc/pr_4521.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/broker/Cargo.toml
  substrate/frame/broker/src/adapt_price.rs
  substrate/frame/broker/src/benchmarking.rs
  substrate/frame/broker/src/dispatchable_impls.rs
  substrate/frame/broker/src/lib.rs
  substrate/frame/broker/src/migration.rs
  substrate/frame/broker/src/mock.rs
  substrate/frame/broker/src/tests.rs
  substrate/frame/broker/src/tick_impls.rs
  substrate/frame/broker/src/types.rs
  substrate/frame/broker/src/utility_impls.rs
  substrate/frame/broker/src/weights.rs
Labels: T2-pallets, R1-breaking_change

#1816 Beefy client generic on aduthority Id
  Cargo.lock
  polkadot/node/service/src/lib.rs
  polkadot/rpc/Cargo.toml
  polkadot/rpc/src/lib.rs
  substrate/bin/node/cli/src/service.rs
  substrate/bin/node/rpc/Cargo.toml
  substrate/bin/node/rpc/src/lib.rs
  substrate/client/consensus/beefy/Cargo.toml
  substrate/client/consensus/beefy/rpc/Cargo.toml
  substrate/client/consensus/beefy/rpc/src/lib.rs
  substrate/client/consensus/beefy/rpc/src/notification.rs
  substrate/client/consensus/beefy/src/aux_schema.rs
  substrate/client/consensus/beefy/src/communication/gossip.rs
  substrate/client/consensus/beefy/src/communication/notification.rs
  substrate/client/consensus/beefy/src/communication/request_response/incoming_requests_handler.rs
  substrate/client/consensus/beefy/src/communication/request_response/outgoing_requests_engine.rs
  substrate/client/consensus/beefy/src/error.rs
  substrate/client/consensus/beefy/src/fisherman.rs
  substrate/client/consensus/beefy/src/import.rs
  substrate/client/consensus/beefy/src/justification.rs
  substrate/client/consensus/beefy/src/keystore.rs
  substrate/client/consensus/beefy/src/lib.rs
  substrate/client/consensus/beefy/src/round.rs
  substrate/client/consensus/beefy/src/tests.rs
  substrate/client/consensus/beefy/src/worker.rs
  substrate/primitives/consensus/beefy/src/lib.rs
  substrate/primitives/keystore/src/testing.rs
Labels: R0-silent

#4636 Fix broken windows build
  substrate/primitives/runtime/src/generic/unchecked_extrinsic.rs
Labels: R0-silent
