Repository paritytech/polkadot-sdk, pull requests merged in 2024-01, with the labels that each got.

#2767 Extract PartialComponents into a type alias
  cumulus/parachain-template/node/src/service.rs
  cumulus/polkadot-parachain/src/service.rs
  cumulus/test/service/src/lib.rs
  prdoc/pr_2767.prdoc
  substrate/bin/minimal/node/src/service.rs
  substrate/bin/node-template/node/src/service.rs
Labels: R0-silent

#2804 malus: use spawn_blocking
  polkadot/node/malus/src/variants/common.rs
  polkadot/node/malus/src/variants/dispute_finalized_candidates.rs
  polkadot/node/malus/src/variants/suggest_garbage_candidate.rs
  prdoc/pr_2804.prdoc
Labels: A1-insubstantial, T0-node

#2813 Implement only sending one notification at a time as per RFC 56
  prdoc/pr_2813.prdoc
  substrate/client/network/transactions/src/lib.rs
Labels: T0-node

#2798 Finish up polkadot doc
  docs/sdk/src/polkadot_sdk/polkadot.rs
Labels: R0-silent, T11-documentation

#2821 Upgrade @polkadot/api and @polkadot/util package version to latest
  cumulus/scripts/generate_hex_encoded_call/package-lock.json
  cumulus/scripts/generate_hex_encoded_call/package.json
Labels: A1-insubstantial, R0-silent, T15-bridges

#2758 Fix vote weights of ranked members in the Society pallet
  prdoc/pr_2758.prdoc
  substrate/frame/society/src/lib.rs
  substrate/frame/society/src/tests.rs
Labels: T1-FRAME

#2848 Remove `dotgraph` feature
  Cargo.lock
  polkadot/node/overseer/Cargo.toml
Labels: R0-silent

#2835 malus: add new variant SupportDisabled
  polkadot/node/malus/src/malus.rs
  polkadot/node/malus/src/variants/mod.rs
  polkadot/node/malus/src/variants/support_disabled.rs
  prdoc/pr_2835.prdoc
Labels: T0-node

#2666 Remove kusama and polkadot SP constants from parachains-common
  cumulus/parachains/common/src/kusama.rs
  cumulus/parachains/common/src/lib.rs
  cumulus/parachains/common/src/polkadot.rs
  cumulus/parachains/runtimes/people/people-rococo/src/people.rs
  cumulus/parachains/runtimes/people/people-westend/src/people.rs
  prdoc/pr_2666.prdoc
Labels: T14-system_parachains

#2554 Contracts build risc-v fixtures
  Cargo.lock
  Cargo.toml
  substrate/frame/contracts/fixtures/Cargo.toml
  substrate/frame/contracts/fixtures/build.rs
  substrate/frame/contracts/fixtures/build/Cargo.toml
  substrate/frame/contracts/fixtures/build/riscv_memory_layout.ld
  substrate/frame/contracts/fixtures/contracts/call.rs
  substrate/frame/contracts/fixtures/contracts/common/Cargo.toml
  substrate/frame/contracts/fixtures/contracts/dummy.rs
  substrate/frame/contracts/uapi/Cargo.toml
  substrate/frame/contracts/uapi/src/host.rs
  substrate/frame/contracts/uapi/src/host/riscv32.rs
  substrate/frame/contracts/uapi/src/host/wasm32.rs
  substrate/frame/contracts/uapi/src/lib.rs
Labels: R0-silent

#2853 Update missing worker binaries error
  .github/workflows/check-markdown.yml
  polkadot/README.md
  polkadot/node/service/src/lib.rs
Labels: R0-silent, T0-node

#2834 proposer: return optional block
  cumulus/client/consensus/aura/src/collator.rs
  cumulus/client/consensus/aura/src/collators/basic.rs
  cumulus/client/consensus/aura/src/collators/lookahead.rs
  cumulus/client/consensus/proposer/src/lib.rs
  prdoc/pr_2834.prdoc
Labels: T0-node, R1-breaking_change

#2823 `fungible::Unbalanced::decrease_balance`: Handle `precision` properly
  prdoc/pr_2823.prdoc
  substrate/frame/balances/src/tests/fungible_tests.rs
  substrate/frame/support/src/traits/tokens/fungible/regular.rs
Labels: T1-FRAME

#2861 Fix clippy warnings
  bridges/snowbridge/parachain/pallets/outbound-queue/src/test.rs
  bridges/snowbridge/parachain/pallets/system/src/lib.rs
  bridges/snowbridge/parachain/runtime/tests/src/test_cases.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-rococo/src/tests/reap_identity.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/reap_identity.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/mod.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/mod.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/mod.rs
  polkadot/node/subsystem-bench/src/core/keyring.rs
  polkadot/node/subsystem-bench/src/core/mock/mod.rs
Labels: R0-silent

#2803 `cumulus-primitives-parachain-inherent`: Split into two crates
  Cargo.lock
  Cargo.toml
  cumulus/client/consensus/aura/Cargo.toml
  cumulus/client/consensus/aura/src/collator.rs
  cumulus/client/parachain-inherent/Cargo.toml
  cumulus/client/parachain-inherent/src/lib.rs
  cumulus/client/parachain-inherent/src/mock.rs
  cumulus/polkadot-parachain/Cargo.toml
  cumulus/polkadot-parachain/src/service.rs
  cumulus/primitives/parachain-inherent/Cargo.toml
  cumulus/primitives/parachain-inherent/src/lib.rs
  cumulus/test/service/Cargo.toml
  cumulus/test/service/src/bench_utils.rs
  cumulus/test/service/src/lib.rs
  prdoc/pr_2803.prdoc
Labels: T9-cumulus

#2856 Kitchensink chain: Add BEEFY support
  Cargo.lock
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  substrate/bin/node/cli/Cargo.toml
  substrate/bin/node/cli/src/chain_spec.rs
  substrate/bin/node/cli/src/service.rs
  substrate/bin/node/cli/tests/res/default_genesis_config.json
  substrate/bin/node/rpc/Cargo.toml
  substrate/bin/node/rpc/src/lib.rs
  substrate/bin/node/runtime/Cargo.toml
  substrate/bin/node/runtime/src/lib.rs
  substrate/bin/node/testing/src/genesis.rs
  substrate/bin/node/testing/src/keyring.rs
  substrate/primitives/consensus/beefy/src/mmr.rs
Labels: R0-silent, T10-tests

#2870 pallet-contracts-fixtures: Only build RISCV when the feature is enabled
  substrate/frame/contracts/fixtures/Cargo.toml
  substrate/frame/contracts/fixtures/build.rs
Labels: R0-silent

#2864 Parametrize SlotDurations for system parachain tests (because of `mock_open_hrmp_channel`)
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases.rs
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases_over_bridge.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/from_grandpa_chain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/from_parachain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/helpers.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/mod.rs
  cumulus/parachains/runtimes/test-utils/src/lib.rs
Labels: R0-silent

#2859 rpc: add `rpc v2 chainSpec` to polkadot
  Cargo.lock
  docs/sdk/src/reference_docs/runtime_vs_smart_contract.rs
  polkadot/node/core/candidate-validation/src/lib.rs
  polkadot/node/core/candidate-validation/src/tests.rs
  polkadot/rpc/Cargo.toml
  polkadot/rpc/src/lib.rs
  substrate/bin/node-template/node/src/rpc.rs
  substrate/client/consensus/beefy/src/import.rs
  substrate/client/consensus/beefy/src/lib.rs
  substrate/client/network/src/protocol/notifications/behaviour.rs
  substrate/frame/contracts/fixtures/build.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/task.rs
  substrate/frame/system/src/tests.rs
  substrate/primitives/core/src/address_uri.rs
  substrate/primitives/core/src/crypto.rs
  substrate/utils/wasm-builder/src/wasm_project.rs
Labels: R0-silent, T3-RPC_API

#2862 Return latest known relay chain block number in `on_initialize` etc
  cumulus/pallets/parachain-system/src/lib.rs
  prdoc/pr_2862.prdoc
Labels: T9-cumulus

#2879 Contracts rename riscv-experimental and enable ci tests
  .gitlab/pipeline/test.yml
  substrate/frame/contracts/fixtures/Cargo.toml
  substrate/frame/contracts/fixtures/build.rs
Labels: R0-silent

#2878 Make `simple-mermaid` optional
  substrate/frame/Cargo.toml
  substrate/primitives/runtime/Cargo.toml
  substrate/primitives/runtime/src/generic/unchecked_extrinsic.rs
Labels: R0-silent

#2867 Coretime Zombienet test
  .gitlab/pipeline/zombienet/polkadot.yml
  cumulus/parachains/runtimes/coretime/coretime-rococo/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-rococo/build.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/coretime.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/polkadot-parachain/src/chain_spec/coretime.rs
  polkadot/runtime/parachains/src/coretime/mod.rs
  polkadot/zombienet_tests/smoke/0004-configure-broker.js
  polkadot/zombienet_tests/smoke/0004-configure-relay.js
  polkadot/zombienet_tests/smoke/0004-coretime-smoke-test.toml
  polkadot/zombienet_tests/smoke/0004-coretime-smoke-test.zndsl
Labels: R0-silent

#2764 backport to master: Handling of disabled validators in backing subsystem (#1259)
  polkadot/node/core/backing/src/lib.rs
  polkadot/node/core/backing/src/tests/mod.rs
  polkadot/node/core/backing/src/tests/prospective_parachains.rs
  polkadot/node/core/provisioner/src/lib.rs
  polkadot/node/subsystem-util/src/lib.rs
  polkadot/node/subsystem-util/src/vstaging.rs
  prdoc/pr_2764.prdoc
Labels: T8-polkadot

#2637 dispute-coordinator: disabling in participation
  polkadot/node/core/backing/src/lib.rs
  polkadot/node/core/dispute-coordinator/src/import.rs
  polkadot/node/core/dispute-coordinator/src/initialized.rs
  polkadot/node/core/dispute-coordinator/src/lib.rs
  polkadot/node/core/dispute-coordinator/src/participation/tests.rs
  polkadot/node/core/dispute-coordinator/src/tests.rs
  polkadot/node/subsystem-util/src/lib.rs
  polkadot/node/subsystem-util/src/runtime/mod.rs
  polkadot/node/subsystem-util/src/vstaging.rs
  polkadot/primitives/src/v6/mod.rs
  polkadot/roadmap/implementers-guide/src/node/disputes/dispute-coordinator.md
  prdoc/pr_2637.prdoc
Labels: T8-polkadot

#2883 pallet-core-fellowship: import an unimported member on approve
  prdoc/pr_2883.prdoc
  substrate/frame/core-fellowship/src/lib.rs
  substrate/frame/core-fellowship/src/tests.rs
Labels: T1-FRAME

#2884 Contracts: Bump polkavm
  .gitlab-ci.yml
  Cargo.lock
  substrate/frame/contracts/fixtures/Cargo.toml
  substrate/frame/contracts/fixtures/build/Cargo.toml
  substrate/frame/contracts/uapi/Cargo.toml
Labels: R0-silent

#2792 Snowbridge Rococo deployment updates
  bridges/snowbridge/parachain/README.md
  bridges/snowbridge/parachain/pallets/ethereum-beacon-client/Cargo.toml
  bridges/snowbridge/parachain/pallets/ethereum-beacon-client/src/benchmarking/fixtures.rs
  bridges/snowbridge/parachain/pallets/ethereum-beacon-client/src/benchmarking/fixtures_mainnet.rs
  bridges/snowbridge/parachain/pallets/ethereum-beacon-client/src/benchmarking/fixtures_minimal.rs
  bridges/snowbridge/parachain/pallets/ethereum-beacon-client/src/benchmarking/mod.rs
  bridges/snowbridge/parachain/pallets/ethereum-beacon-client/src/config/mod.rs
  bridges/snowbridge/parachain/pallets/ethereum-beacon-client/src/lib.rs
  bridges/snowbridge/parachain/pallets/ethereum-beacon-client/src/mock.rs
  bridges/snowbridge/parachain/pallets/ethereum-beacon-client/src/tests.rs
  bridges/snowbridge/parachain/pallets/ethereum-beacon-client/tests/fixtures/execution-header-update.mainnet.json
  bridges/snowbridge/parachain/pallets/ethereum-beacon-client/tests/fixtures/finalized-header-update.mainnet.json
  bridges/snowbridge/parachain/pallets/ethereum-beacon-client/tests/fixtures/initial-checkpoint.mainnet.json
  bridges/snowbridge/parachain/pallets/ethereum-beacon-client/tests/fixtures/next-finalized-header-update.mainnet.json
  bridges/snowbridge/parachain/pallets/ethereum-beacon-client/tests/fixtures/next-sync-committee-update.mainnet.json
  bridges/snowbridge/parachain/pallets/ethereum-beacon-client/tests/fixtures/sync-committee-update.mainnet.json
  bridges/snowbridge/parachain/pallets/outbound-queue/src/lib.rs
  bridges/snowbridge/parachain/pallets/outbound-queue/src/types.rs
  bridges/snowbridge/parachain/runtime/tests/Cargo.toml
  bridges/snowbridge/parachain/scripts/verify-pallets-build.sh
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_ethereum_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  cumulus/polkadot-parachain/Cargo.toml
Labels: R0-silent, T15-bridges

#2886 Remove bounds from `PrevalidateAttests` struct definition
  polkadot/runtime/common/src/claims.rs
  prdoc/pr_2886.prdoc
Labels: R0-silent, T8-polkadot

#2896 Fix deps for local docs build for Rust `1.75.0`
  Cargo.lock
  docs/mermaid/polkadot_sdk_parachain.mmd
  docs/sdk/src/guides/your_first_pallet/mod.rs
  docs/sdk/src/meta_contributing.rs
Labels: A1-insubstantial, R0-silent, T11-documentation

#1841 statement-distribution: validator disabling
  .gitlab/pipeline/zombienet/polkadot.yml
  polkadot/node/network/statement-distribution/src/error.rs
  polkadot/node/network/statement-distribution/src/v2/grid.rs
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  polkadot/node/network/statement-distribution/src/v2/requests.rs
  polkadot/node/network/statement-distribution/src/v2/statement_store.rs
  polkadot/node/network/statement-distribution/src/v2/tests/cluster.rs
  polkadot/node/network/statement-distribution/src/v2/tests/grid.rs
  polkadot/node/network/statement-distribution/src/v2/tests/mod.rs
  polkadot/node/network/statement-distribution/src/v2/tests/requests.rs
  polkadot/roadmap/implementers-guide/src/node/backing/statement-distribution.md
  polkadot/zombienet_tests/functional/0010-validator-disabling.toml
  polkadot/zombienet_tests/functional/0010-validator-disabling.zndsl
  prdoc/pr_1841.prdoc
Labels: T0-node

#2651 Unique Usernames in Identity Pallet
  Cargo.lock
  cumulus/parachains/runtimes/people/people-rococo/src/people.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/pallet_identity.rs
  cumulus/parachains/runtimes/people/people-westend/src/people.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/pallet_identity.rs
  polkadot/runtime/common/src/integration_tests.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/pallet_identity.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/pallet_identity.rs
  prdoc/pr_2651.prdoc
  substrate/bin/node/runtime/src/impls.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/alliance/src/mock.rs
  substrate/frame/identity/Cargo.toml
  substrate/frame/identity/src/benchmarking.rs
  substrate/frame/identity/src/legacy.rs
  substrate/frame/identity/src/lib.rs
  substrate/frame/identity/src/migration.rs
  substrate/frame/identity/src/tests.rs
  substrate/frame/identity/src/types.rs
  substrate/frame/identity/src/weights.rs
Labels: T2-pallets

#2899 Improve storage monitor API
  Cargo.lock
  polkadot/cli/src/command.rs
  prdoc/pr_2899.prdoc
  substrate/bin/node/cli/src/service.rs
  substrate/client/storage-monitor/Cargo.toml
  substrate/client/storage-monitor/src/lib.rs
Labels: T0-node

#2771 add fallback request for req-response protocols
  polkadot/node/network/availability-distribution/src/pov_requester/mod.rs
  polkadot/node/network/availability-distribution/src/requester/fetch_task/tests.rs
  polkadot/node/network/availability-distribution/src/tests/state.rs
  polkadot/node/network/availability-recovery/src/tests.rs
  polkadot/node/network/bridge/src/network.rs
  polkadot/node/network/collator-protocol/src/validator_side/tests/mod.rs
  polkadot/node/network/collator-protocol/src/validator_side/tests/prospective_parachains.rs
  polkadot/node/network/dispute-distribution/src/tests/mod.rs
  polkadot/node/network/protocol/src/request_response/mod.rs
  polkadot/node/network/protocol/src/request_response/outgoing.rs
  polkadot/node/network/statement-distribution/src/legacy_v1/tests.rs
  polkadot/node/network/statement-distribution/src/v2/tests/mod.rs
  polkadot/node/network/statement-distribution/src/v2/tests/requests.rs
  polkadot/node/subsystem-bench/src/availability/mod.rs
  polkadot/node/subsystem-bench/src/core/mock/network_bridge.rs
  polkadot/node/subsystem-bench/src/core/network.rs
  prdoc/pr_2771.prdoc
  substrate/client/consensus/beefy/src/communication/request_response/outgoing_requests_engine.rs
  substrate/client/network/src/behaviour.rs
  substrate/client/network/src/request_responses.rs
  substrate/client/network/src/service.rs
  substrate/client/network/src/service/traits.rs
  substrate/client/network/sync/src/block_relay_protocol.rs
  substrate/client/network/sync/src/block_request_handler.rs
  substrate/client/network/sync/src/engine.rs
  substrate/client/network/sync/src/mock.rs
  substrate/client/network/sync/src/pending_responses.rs
  substrate/client/network/sync/src/service/mock.rs
  substrate/client/network/sync/src/service/network.rs
Labels: T0-node, I5-enhancement

#2895 PVF: Remove artifact persistence across restarts
  Cargo.lock
  polkadot/node/core/pvf/Cargo.toml
  polkadot/node/core/pvf/common/Cargo.toml
  polkadot/node/core/pvf/common/build.rs
  polkadot/node/core/pvf/common/src/lib.rs
  polkadot/node/core/pvf/src/artifacts.rs
  polkadot/node/core/pvf/src/host.rs
  polkadot/node/core/pvf/src/prepare/worker_interface.rs
  polkadot/node/core/pvf/src/worker_interface.rs
  polkadot/node/core/pvf/tests/it/main.rs
  substrate/utils/build-script-utils/src/version.rs
Labels: R0-silent, T0-node

#2907 frame-support: sp-runtime dependency updated (serde)
  substrate/frame/support/Cargo.toml
Labels: R0-silent

#2905 Fix coretime migration
  polkadot/runtime/parachains/src/coretime/migration.rs
  polkadot/runtime/parachains/src/coretime/mod.rs
Labels: R0-silent

#2898 Move Cors data structure into reachable place
  substrate/client/cli/src/arg_enums.rs
  substrate/client/cli/src/commands/run_cmd.rs
Labels: R0-silent

#2887 Cumulus test service cleanup
  cumulus/client/cli/src/lib.rs
  cumulus/polkadot-parachain/src/command.rs
  cumulus/test/service/benches/transaction_throughput.rs
  cumulus/test/service/src/cli.rs
  cumulus/test/service/src/genesis.rs
  cumulus/test/service/src/lib.rs
  cumulus/test/service/src/main.rs
  substrate/bin/node/cli/benches/transaction_pool.rs
Labels: R0-silent, T0-node

#2915 Add More HRMP Channel Opening Tests
  polkadot/runtime/parachains/src/hrmp/tests.rs
Labels: R0-silent, T10-tests, T14-system_parachains

#2919 Kitchensink: Fix pallet_mmr config
  substrate/bin/node/cli/tests/basic.rs
  substrate/bin/node/runtime/src/lib.rs
Labels: R0-silent, T10-tests

#2439 Run bridges zombienet tests on CI
  .gitlab/pipeline/build.yml
  .gitlab/pipeline/publish.yml
  .gitlab/pipeline/zombienet.yml
  .gitlab/pipeline/zombienet/bridges.yml
  bridges/zombienet/run-tests.sh
  cumulus/scripts/bridges_common.sh
  cumulus/scripts/bridges_rococo_westend.sh
  docker/dockerfiles/bridges_zombienet_tests_injected.Dockerfile
Labels: R0-silent, T15-bridges

#2467 Extract warp sync strategy from `ChainSync`
  polkadot/node/service/src/lib.rs
  prdoc/pr_2467.prdoc
  substrate/bin/node/cli/src/service.rs
  substrate/client/consensus/grandpa/src/warp_proof.rs
  substrate/client/informant/src/display.rs
  substrate/client/network/sync/Cargo.toml
  substrate/client/network/sync/src/block_announce_validator.rs
  substrate/client/network/sync/src/block_request_handler.rs
  substrate/client/network/sync/src/blocks.rs
  substrate/client/network/sync/src/engine.rs
  substrate/client/network/sync/src/extra_requests.rs
  substrate/client/network/sync/src/lib.rs
  substrate/client/network/sync/src/pending_responses.rs
  substrate/client/network/sync/src/state_request_handler.rs
  substrate/client/network/sync/src/strategy.rs
  substrate/client/network/sync/src/strategy/chain_sync.rs
  substrate/client/network/sync/src/strategy/chain_sync/test.rs
  substrate/client/network/sync/src/strategy/state.rs
  substrate/client/network/sync/src/strategy/state_sync.rs
  substrate/client/network/sync/src/strategy/warp.rs
  substrate/client/network/sync/src/types.rs
  substrate/client/network/sync/src/warp.rs
  substrate/client/network/sync/src/warp_request_handler.rs
  substrate/client/network/test/src/lib.rs
  substrate/client/network/test/src/sync.rs
  substrate/client/service/src/builder.rs
  substrate/client/service/src/lib.rs
  substrate/zombienet/0001-basic-warp-sync/test-warp-sync.zndsl
  substrate/zombienet/0002-validators-warp-sync/test-validators-warp-sync.zndsl
  substrate/zombienet/0003-block-building-warp-sync/test-block-building-warp-sync.zndsl
Labels: T0-node

#2912 Bump zombienet version `v1.3.91`
  .gitlab/pipeline/zombienet.yml
  polkadot/zombienet_tests/functional/0002-parachains-disputes.toml
Labels: A1-insubstantial, R0-silent, T10-tests

#2921 Upgrade aquamarine to v0.5.0, v0.4.0 has yanked
  Cargo.lock
  substrate/frame/bags-list/Cargo.toml
  substrate/frame/support/Cargo.toml
Labels: R0-silent

#2914 wasm-builder: bump toml from 0.8.2 to 0.8.8; replace ansi_term
  Cargo.lock
  substrate/utils/wasm-builder/Cargo.toml
  substrate/utils/wasm-builder/src/prerequisites.rs
  substrate/utils/wasm-builder/src/wasm_project.rs
Labels: R0-silent

#2928 Warp sync zombienet tests: update DB snapshot
  .gitlab/pipeline/zombienet/substrate.yml
  substrate/zombienet/0001-basic-warp-sync/chain-spec.json
  substrate/zombienet/0002-validators-warp-sync/test-validators-warp-sync.zndsl
Labels: R0-silent, T10-tests

#2932 Add missing crates to the workspace
  .github/scripts/check-workspace.py
  .github/workflows/check-workspace.yml
  Cargo.toml
Labels: R0-silent

#2920 Contracts: stabilize sr25519
  prdoc/pr_2920.prdoc
  substrate/frame/contracts/src/wasm/runtime.rs
Labels: T7-smart_contracts

#2936 Some random fixes
  cumulus/parachains/integration-tests/emulated/common/Cargo.toml
  substrate/frame/contracts/fixtures/src/lib.rs
Labels: R0-silent

#1845 XCM WeightTrader: Swap Fee Asset for Native Asset
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/send.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/swap.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/send.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/swap.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/assets/common/src/lib.rs
  cumulus/parachains/runtimes/assets/test-utils/Cargo.toml
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases_over_bridge.rs
  cumulus/primitives/utility/Cargo.toml
  cumulus/primitives/utility/src/lib.rs
  cumulus/primitives/utility/src/tests/mod.rs
  cumulus/primitives/utility/src/tests/swap_first.rs
  prdoc/pr_1845.prdoc
Labels: T6-XCM, T9-cumulus

#2913 Bump rococo relay and coretime-rococo to 1.6
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/cumulus_pallet_parachain_system.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/frame_system.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_balances.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_broker.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_collator_selection.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_message_queue.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_multisig.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_session.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_timestamp.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_utility.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  polkadot/runtime/rococo/src/lib.rs
Labels: A1-insubstantial, R0-silent

#1708 CI check features
  .github/workflows/check-features.yml
  substrate/frame/support/procedural/Cargo.toml
  substrate/primitives/api/Cargo.toml
Labels: R0-silent

#2893 subsystem-bench: cache misses profiling
  polkadot/node/subsystem-bench/README.md
  polkadot/node/subsystem-bench/src/subsystem-bench.rs
  polkadot/node/subsystem-bench/src/valgrind.rs
Labels: R0-silent, T10-tests, T12-benchmarks

#2956 Revert "pallet-core-fellowship: import an unimported member on approve"
  prdoc/pr_2883.prdoc
  substrate/frame/core-fellowship/src/lib.rs
  substrate/frame/core-fellowship/src/tests.rs
Labels: R0-silent, T2-pallets

#2959 Add `Storage` to `PolkadotXcm` for People Chains
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
Labels: R0-silent, T14-system_parachains, D0-easy

#2945 contracts: Update to Polkavm 0.5
  Cargo.lock
  substrate/frame/contracts/fixtures/Cargo.toml
  substrate/frame/contracts/fixtures/build.rs
  substrate/frame/contracts/fixtures/build/Cargo.toml
  substrate/frame/contracts/fixtures/build/riscv_memory_layout.ld
Labels: R0-silent

#2965 [Backport] Version bumps from 1.6.0 release
  Cargo.lock
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  cumulus/polkadot-parachain/Cargo.toml
  polkadot/Cargo.toml
  polkadot/node/primitives/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/1.6.0/pr_1191.prdoc
  prdoc/1.6.0/pr_1226.prdoc
  prdoc/1.6.0/pr_1289.prdoc
  prdoc/1.6.0/pr_1343.prdoc
  prdoc/1.6.0/pr_1454.prdoc
  prdoc/1.6.0/pr_1479.prdoc
  prdoc/1.6.0/pr_1677.prdoc
  prdoc/1.6.0/pr_1694.prdoc
  prdoc/1.6.0/pr_1841.prdoc
  prdoc/1.6.0/pr_2031.prdoc
  prdoc/1.6.0/pr_2033.prdoc
  prdoc/1.6.0/pr_2281.prdoc
  prdoc/1.6.0/pr_2331.prdoc
  prdoc/1.6.0/pr_2403.prdoc
  prdoc/1.6.0/pr_2481.prdoc
  prdoc/1.6.0/pr_2522.prdoc
  prdoc/1.6.0/pr_2532.prdoc
  prdoc/1.6.0/pr_2597.prdoc
  prdoc/1.6.0/pr_2637.prdoc
  prdoc/1.6.0/pr_2651.prdoc
  prdoc/1.6.0/pr_2656.prdoc
  prdoc/1.6.0/pr_2663-fix-could-not-create-temporary-drectory.prdoc
  prdoc/1.6.0/pr_2666.prdoc
  prdoc/1.6.0/pr_2682.prdoc
  prdoc/1.6.0/pr_2684.prdoc
  prdoc/1.6.0/pr_2687.prdoc
  prdoc/1.6.0/pr_2689.prdoc
  prdoc/1.6.0/pr_2694.prdoc
  prdoc/1.6.0/pr_2758.prdoc
  prdoc/1.6.0/pr_2764.prdoc
  prdoc/1.6.0/pr_2767.prdoc
  prdoc/1.6.0/pr_2771.prdoc
  prdoc/1.6.0/pr_2783.prdoc
  prdoc/1.6.0/pr_2799.prdoc
  prdoc/1.6.0/pr_2803.prdoc
  prdoc/1.6.0/pr_2804.prdoc
  prdoc/1.6.0/pr_2811.prdoc
  prdoc/1.6.0/pr_2813.prdoc
  prdoc/1.6.0/pr_2823.prdoc
  prdoc/1.6.0/pr_2834.prdoc
  prdoc/1.6.0/pr_2835.prdoc
  prdoc/1.6.0/pr_2862.prdoc
  prdoc/1.6.0/pr_2886.prdoc
  prdoc/1.6.0/pr_2899.prdoc
Labels: R0-silent, A3-backport, D0-easy

#2946 Rococo Identity Migration Part 2 + Bug Fix
  cumulus/parachains/integration-tests/emulated/tests/people/people-rococo/src/tests/reap_identity.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/people/people-westend/src/xcm_config.rs
  polkadot/runtime/rococo/src/lib.rs
  substrate/frame/identity/src/lib.rs
  substrate/frame/identity/src/tests.rs
Labels: R0-silent, T14-system_parachains

#2889 Filter votes from disabled validators in `BackedCandidates` in process_inherent_data
  polkadot/roadmap/implementers-guide/src/runtime/parainherent.md
  polkadot/runtime/common/src/assigned_slots/mod.rs
  polkadot/runtime/common/src/integration_tests.rs
  polkadot/runtime/common/src/paras_registrar/mod.rs
  polkadot/runtime/parachains/src/mock.rs
  polkadot/runtime/parachains/src/paras_inherent/mod.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
  polkadot/runtime/parachains/src/runtime_api_impl/vstaging.rs
  polkadot/runtime/parachains/src/scheduler.rs
  polkadot/runtime/parachains/src/shared.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/xcm/xcm-builder/tests/mock/mod.rs
  polkadot/xcm/xcm-simulator/example/src/relay_chain.rs
  polkadot/xcm/xcm-simulator/fuzzer/src/relay_chain.rs
  prdoc/pr_2889.prdoc
  substrate/frame/aura/src/mock.rs
  substrate/frame/contracts/mock-network/src/relay_chain.rs
  substrate/frame/session/src/lib.rs
  substrate/frame/support/src/traits/validation.rs
Labels: T2-pallets, T8-polkadot

#2971 Fix typo in traits.rs
  substrate/primitives/runtime/src/traits.rs
Labels: R0-silent

#2980 Downgrade logging to `debug`
  polkadot/node/core/approval-voting/src/lib.rs
Labels: R0-silent

#2966 Introduce `BlockWeightsForAsyncBacking` and `MAXIMUM_BLOCK_WEIGHT_FOR_ASYNC_BACKING` to bridges primitives
  bridges/primitives/chain-bridge-hub-cumulus/src/lib.rs
  bridges/primitives/chain-bridge-hub-rococo/src/lib.rs
  bridges/primitives/chain-bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_westend_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/bridge_to_rococo_config.rs
Labels: R0-silent, T15-bridges

#2983 Fix typos
  bridges/modules/parachains/src/lib.rs
  docs/contributor/STYLE_GUIDE.md
  docs/sdk/src/meta_contributing.rs
  docs/sdk/src/reference_docs/extrinsic_encoding.rs
Labels: R0-silent

#2978 Westend/Rococo Asset Hub: pay xcm fees with sufficient assets
  bridges/zombienet/tests/0001-asset-transfer-works-rococo-to-westend.zndsl
  bridges/zombienet/tests/0001-asset-transfer-works-westend-to-rococo.zndsl
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/send.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/send.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
Labels: R0-silent, T9-cumulus

#2986 pallet-contracts: Fix compilation on latest nightly
  substrate/frame/contracts/src/lib.rs
Labels: R0-silent

#2989 approval-distribution: downgrade errors to debug
  polkadot/node/network/approval-distribution/src/lib.rs
Labels: R0-silent, T0-node, T8-polkadot

#2969 contracts: Update weights
  substrate/frame/contracts/src/weights.rs
Labels: R0-silent

#2927 Fix contracts compilation with `CARGO_TARGET_DIR` set
  substrate/frame/contracts/fixtures/build.rs
Labels: R0-silent, T7-smart_contracts

#2987 `GenesisBuilder`: `arbitrary_precision` feature enabled for `serde_json`
  substrate/primitives/genesis-builder/Cargo.toml
Labels: R0-silent

#2599 More tests and checks confirming that `ledger.controller` is always correct.
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/tests.rs
Labels: R0-silent, T2-pallets, T10-tests

#2985 Update `translate` to use `defensive!`
  substrate/frame/support/src/storage/generator/map.rs
  substrate/frame/support/src/storage/types/map.rs
Labels: T0-node

#2958 Pvf thiserror
  polkadot/node/core/pvf/common/src/error.rs
  polkadot/node/core/pvf/execute-worker/src/lib.rs
  polkadot/node/core/pvf/src/error.rs
  polkadot/node/core/pvf/src/execute/queue.rs
  polkadot/node/core/pvf/src/host.rs
  polkadot/node/core/pvf/src/prepare/queue.rs
  polkadot/node/core/pvf/src/prepare/worker_interface.rs
Labels: R0-silent, T0-node, I4-refactor, T11-documentation

#2796 Enable cross-chain NFT transfers on asset-hub
  cumulus/parachains/common/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/common/src/lib.rs
  prdoc/pr_2796.prdoc
Labels: T6-XCM

#3000 Contract fixtures tests: fixe nightly version
  substrate/frame/contracts/fixtures/build.rs
Labels: R0-silent

#2996 Update bridges subtree
  bridges/bin/runtime-common/src/lib.rs
  bridges/bin/runtime-common/src/messages.rs
  bridges/bin/runtime-common/src/messages_call_ext.rs
  bridges/bin/runtime-common/src/messages_xcm_extension.rs
  bridges/bin/runtime-common/src/mock.rs
  bridges/bin/runtime-common/src/parachains_benchmarking.rs
  bridges/bin/runtime-common/src/refund_relayer_extension.rs
  bridges/modules/grandpa/src/lib.rs
  bridges/modules/grandpa/src/mock.rs
  bridges/modules/messages/README.md
  bridges/modules/messages/src/benchmarking.rs
  bridges/modules/messages/src/lib.rs
  bridges/modules/messages/src/mock.rs
  bridges/modules/messages/src/outbound_lane.rs
  bridges/modules/parachains/src/call_ext.rs
  bridges/modules/parachains/src/lib.rs
  bridges/modules/parachains/src/mock.rs
  bridges/modules/xcm-bridge-hub/src/exporter.rs
  bridges/modules/xcm-bridge-hub/src/mock.rs
  bridges/primitives/chain-bridge-hub-cumulus/src/lib.rs
  bridges/primitives/chain-bridge-hub-kusama/src/lib.rs
  bridges/primitives/chain-bridge-hub-polkadot/src/lib.rs
  bridges/primitives/chain-bridge-hub-rococo/src/lib.rs
  bridges/primitives/chain-bridge-hub-westend/Cargo.toml
  bridges/primitives/chain-bridge-hub-westend/src/lib.rs
  bridges/primitives/chain-kusama/src/lib.rs
  bridges/primitives/chain-polkadot-bulletin/src/lib.rs
  bridges/primitives/chain-polkadot/src/lib.rs
  bridges/primitives/chain-rococo/src/lib.rs
  bridges/primitives/chain-westend/src/lib.rs
  bridges/primitives/header-chain/src/lib.rs
  bridges/primitives/messages/src/lib.rs
  bridges/primitives/messages/src/source_chain.rs
  bridges/primitives/parachains/src/lib.rs
  bridges/primitives/polkadot-core/src/lib.rs
  bridges/primitives/polkadot-core/src/parachains.rs
  bridges/primitives/runtime/src/chain.rs
  bridges/primitives/runtime/src/extensions.rs
  bridges/primitives/runtime/src/lib.rs
  bridges/primitives/test-utils/src/keyring.rs
  bridges/primitives/test-utils/src/lib.rs
  bridges/snowbridge/parachain/pallets/ethereum-client/Cargo.toml
  bridges/snowbridge/parachain/pallets/inbound-queue/Cargo.toml
  bridges/snowbridge/parachain/pallets/outbound-queue/Cargo.toml
  bridges/snowbridge/parachain/primitives/beacon/Cargo.toml
  bridges/snowbridge/parachain/primitives/core/Cargo.toml
  bridges/snowbridge/parachain/primitives/router/Cargo.toml
  bridges/snowbridge/parachain/runtime/test-common/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_bulletin_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_westend_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/bridge_to_rococo_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
Labels: R0-silent, T15-bridges

#2957 Update Wasm benchmarks
  substrate/frame/contracts/src/benchmarking/code.rs
  substrate/frame/contracts/src/benchmarking/mod.rs
  substrate/frame/contracts/src/schedule.rs
  substrate/frame/contracts/src/weights.rs
Labels: R0-silent

#2999 Make `Slot` and `SlotDuration` transparent
  substrate/primitives/consensus/slots/src/lib.rs
Labels: R0-silent

#2990 better debugging for accountid32 in debug build
  substrate/primitives/core/src/crypto.rs
Labels: R0-silent

#1871 Adding `try_state` hook for Tips pallet
  prdoc/pr_1871.prdoc
  substrate/frame/tips/src/lib.rs
  substrate/frame/tips/src/tests.rs
Labels: T2-pallets

#2370 Adder Parachain: Accept output file argument to `export-genesis-*` subcommands
  polkadot/parachain/test-parachains/adder/collator/src/cli.rs
  polkadot/parachain/test-parachains/adder/collator/src/main.rs
  polkadot/parachain/test-parachains/undying/collator/src/main.rs
Labels: R0-silent

#2477 Use clone instead of fork on pvf
  Cargo.lock
  polkadot/node/core/pvf/common/Cargo.toml
  polkadot/node/core/pvf/common/src/execute.rs
  polkadot/node/core/pvf/common/src/executor_interface.rs
  polkadot/node/core/pvf/common/src/lib.rs
  polkadot/node/core/pvf/common/src/worker/mod.rs
  polkadot/node/core/pvf/common/src/worker/security/change_root.rs
  polkadot/node/core/pvf/common/src/worker/security/clone.rs
  polkadot/node/core/pvf/common/src/worker/security/landlock.rs
  polkadot/node/core/pvf/common/src/worker/security/mod.rs
  polkadot/node/core/pvf/common/src/worker/security/seccomp.rs
  polkadot/node/core/pvf/execute-worker/Cargo.toml
  polkadot/node/core/pvf/execute-worker/src/lib.rs
  polkadot/node/core/pvf/prepare-worker/Cargo.toml
  polkadot/node/core/pvf/prepare-worker/src/lib.rs
  polkadot/node/core/pvf/src/host.rs
  polkadot/node/core/pvf/src/security.rs
  polkadot/node/core/pvf/tests/it/main.rs
  polkadot/node/core/pvf/tests/it/process.rs
  prdoc/pr_2477-use-clone-instead-of-fork-on-pvf.prdoc
Labels: T0-node

#2125 Make candidate validation bounded again
  Cargo.lock
  cumulus/client/relay-chain-inprocess-interface/Cargo.toml
  polkadot/node/core/candidate-validation/src/lib.rs
  polkadot/node/core/pvf/src/host.rs
  polkadot/node/core/pvf/src/lib.rs
  polkadot/node/malus/src/interceptor.rs
  polkadot/node/metrics/Cargo.toml
  polkadot/node/overseer/Cargo.toml
  polkadot/node/subsystem-bench/Cargo.toml
  polkadot/node/subsystem-test-helpers/src/lib.rs
  polkadot/node/subsystem-types/Cargo.toml
  polkadot/node/subsystem-util/Cargo.toml
  prdoc/pr_2125.prdoc
Labels: T0-node

#3010 Review: Remove audit rules
  .github/review-bot.yml
Labels: R0-silent

#2826 Enable async backing on asset-hub-rococo
  Cargo.lock
  cumulus/client/collator/src/lib.rs
  cumulus/client/consensus/aura/src/collators/lookahead.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases.rs
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases_over_bridge.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/from_grandpa_chain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/from_parachain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/helpers.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/mod.rs
  cumulus/parachains/runtimes/test-utils/src/lib.rs
  cumulus/polkadot-parachain/src/command.rs
  cumulus/polkadot-parachain/src/service.rs
  polkadot/node/collation-generation/src/lib.rs
  polkadot/node/subsystem-types/src/messages.rs
  prdoc/pr_2826.prdoc
Labels: T14-system_parachains

#3009 sc-informant: Respect `--disable-log-color`
  prdoc/pr_3009.prdoc
  substrate/client/cli/src/config.rs
  substrate/client/informant/src/display.rs
  substrate/client/informant/src/lib.rs
  substrate/client/service/src/config.rs
Labels: T0-node

#3015 Adds missing feature flags in UI Test update script
  scripts/update-ui-tests.sh
Labels: R0-silent

#1633 Implement wrapping of EPM types
  substrate/frame/election-provider-multi-phase/src/lib.rs
Labels: R0-silent, T1-FRAME

#3019 approval-voting: Move verbose log from debug to tracing
  polkadot/node/core/approval-voting/src/lib.rs
Labels: A1-insubstantial, R0-silent, T0-node

#3022 Add unit impl for XcmAssetTransfers trait
  polkadot/xcm/xcm-executor/src/traits/asset_transfer.rs
Labels: R0-silent, T6-XCM

#3026 Update Westend / People Runtimes for Post-Migration
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/reap_identity.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
Labels: R0-silent, T14-system_parachains

#3017 rpc-v2: Enable the `archive` class of methods
  substrate/client/db/src/lib.rs
  substrate/client/rpc-spec-v2/src/archive/archive.rs
  substrate/client/rpc-spec-v2/src/archive/archive_storage.rs
  substrate/client/rpc-spec-v2/src/archive/mod.rs
  substrate/client/rpc-spec-v2/src/archive/tests.rs
  substrate/client/service/src/builder.rs
Labels: A1-insubstantial, R0-silent, I5-enhancement, D1-medium

#3006 Upgrade aquamarine to v0.5.0, v0.4.0 has yanked (#2921)
  Cargo.lock
  substrate/frame/bags-list/Cargo.toml
  substrate/frame/support/Cargo.toml
Labels: A1-insubstantial, R0-silent

#3024 Various nits and alignments for testnet runtimes
  Cargo.lock
  bridges/snowbridge/parachain/runtime/test-common/Cargo.toml
  cumulus/parachain-template/runtime/Cargo.toml
  cumulus/parachains/chain-specs/asset-hub-wococo.json
  cumulus/parachains/chain-specs/bridge-hub-wococo.json
  cumulus/parachains/common/Cargo.toml
  cumulus/parachains/common/src/lib.rs
  cumulus/parachains/common/src/wococo.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/parachains/collectives/collectives-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/parachains/people/people-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/parachains/people/people-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/parachains/testing/penpal/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/relays/rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/relays/westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/common/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/people/people-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/common/Cargo.toml
  cumulus/parachains/runtimes/assets/test-utils/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/Cargo.toml
  cumulus/parachains/runtimes/collectives/collectives-westend/Cargo.toml
  cumulus/parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-rococo/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/coretime.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/Cargo.toml
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/Cargo.toml
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/Cargo.toml
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/test-utils/Cargo.toml
  cumulus/parachains/runtimes/testing/penpal/Cargo.toml
  cumulus/parachains/runtimes/testing/rococo-parachain/Cargo.toml
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/westend/Cargo.toml
  substrate/bin/node-template/runtime/src/lib.rs
Labels: R0-silent

#3020 Registrar: Deposit covering max code size
  polkadot/runtime/common/src/integration_tests.rs
  polkadot/runtime/common/src/paras_registrar/mod.rs
  prdoc/pr_3020.prdoc
Labels: T8-polkadot

#3042 statement-distribution: Ensure we deactivate leaves before activating
  polkadot/node/network/statement-distribution/src/lib.rs
Labels: R0-silent

#1801 Refactor `pallet-state-trie-migration` to `fungible::*` traits
  Cargo.lock
  Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/alliance/src/mock.rs
  substrate/frame/nicks/Cargo.toml
  substrate/frame/nicks/README.md
  substrate/frame/nicks/src/lib.rs
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/safe-mode/src/benchmarking.rs
  substrate/frame/safe-mode/src/lib.rs
  substrate/frame/society/src/mock.rs
  substrate/frame/state-trie-migration/src/lib.rs
  substrate/frame/state-trie-migration/src/weights.rs
  substrate/frame/transaction-storage/src/lib.rs
  substrate/frame/transaction-storage/src/mock.rs
Labels: R0-silent, T1-FRAME

#3041 [cumulus] Feature gates for rococo/westend related stuff in the `parachains-common`
  cumulus/parachains/common/Cargo.toml
  cumulus/parachains/common/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/collectives/collectives-westend/Cargo.toml
  cumulus/parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-rococo/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-westend/Cargo.toml
  cumulus/parachains/runtimes/glutton/glutton-westend/Cargo.toml
  cumulus/parachains/runtimes/people/people-rococo/Cargo.toml
  cumulus/parachains/runtimes/people/people-westend/Cargo.toml
  cumulus/parachains/runtimes/testing/penpal/Cargo.toml
  cumulus/parachains/runtimes/testing/rococo-parachain/Cargo.toml
Labels: R0-silent, T9-cumulus

#3048 statement-dist: activate leaves before unconditional deactivate
  polkadot/node/network/statement-distribution/src/lib.rs
Labels: R0-silent

#2981 approval-distribution: Update topology if authorities are discovered later
  polkadot/node/network/approval-distribution/src/lib.rs
  polkadot/node/network/approval-distribution/src/tests.rs
  polkadot/node/network/bitfield-distribution/src/lib.rs
  polkadot/node/network/gossip-support/src/lib.rs
  polkadot/node/network/protocol/src/grid_topology.rs
  polkadot/node/network/statement-distribution/src/legacy_v1/mod.rs
Labels: R0-silent, T8-polkadot

#3044 Add RadiumBlock collectives-westend bootnode
  cumulus/parachains/chain-specs/collectives-westend.json
Labels: R0-silent

#3062 test-runtime: json_patch dep removed
  Cargo.lock
  substrate/client/chain-spec/src/lib.rs
  substrate/test-utils/runtime/Cargo.toml
  substrate/test-utils/runtime/src/lib.rs
Labels: R0-silent

#3065 bump reed-solomon-novelpoly version
  Cargo.lock
  polkadot/erasure-coding/Cargo.toml
  polkadot/erasure-coding/src/lib.rs
Labels: R0-silent, T0-node, T8-polkadot

#3073 Remove duplicate `subsystem-bench` from Cargo.toml
  Cargo.toml
  polkadot/node/subsystem-bench/Cargo.toml
Labels: R0-silent

#2942 Fix Pools 6->7 migration
  prdoc/pr_2796.prdoc
  prdoc/pr_2920.prdoc
  prdoc/pr_2942.prdoc
  substrate/frame/nomination-pools/src/migration.rs
Labels: T2-pallets

#2490 Release Process
  README.md
  docs/AUDIT.md
  docs/RELEASE.md
Labels: R0-silent, T11-documentation

#3021 contracts: Fix printing the `Schedule`
  substrate/frame/contracts/Cargo.toml
  substrate/frame/contracts/README.md
  substrate/frame/contracts/mock-network/Cargo.toml
  substrate/frame/contracts/proc-macro/Cargo.toml
  substrate/frame/contracts/proc-macro/src/lib.rs
  substrate/frame/contracts/src/benchmarking/mod.rs
  substrate/frame/contracts/src/schedule.rs
Labels: R0-silent

#3077 Enable cross-chain Coretime region transfers
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/xcm_config.rs
  prdoc/pr_3077.prdoc
  substrate/frame/broker/src/nonfungible_impl.rs
  substrate/frame/broker/src/tests.rs
Labels: T14-system_parachains

#2402 Removes the `Default` implementation for `RewardDestination`
  substrate/frame/nomination-pools/test-staking/src/lib.rs
  substrate/frame/staking/src/benchmarking.rs
  substrate/frame/staking/src/ledger.rs
  substrate/frame/staking/src/lib.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/tests.rs
Labels: R0-silent, T1-FRAME, T2-pallets, D0-easy

#3057 Serialize/Deserialize trait implemented in no-std for XCM assets
  polkadot/xcm/src/v3/multiasset.rs
  polkadot/xcm/src/v4/asset.rs
  prdoc/pr_3057.prdoc
Labels: T6-XCM

#3063 statement-distribution: fix parachains stalling on async_backing enablement
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  polkadot/node/network/statement-distribution/src/v2/tests/grid.rs
  polkadot/node/network/statement-distribution/src/v2/tests/mod.rs
Labels: R0-silent, T8-polkadot

#3061 Do not run unneeded subsystems on collator and its alongside node
  cumulus/client/relay-chain-inprocess-interface/src/lib.rs
  cumulus/test/service/src/lib.rs
  polkadot/cli/src/command.rs
  polkadot/cli/src/lib.rs
  polkadot/node/core/pvf-checker/src/lib.rs
  polkadot/node/malus/src/variants/back_garbage_candidate.rs
  polkadot/node/malus/src/variants/dispute_finalized_candidates.rs
  polkadot/node/malus/src/variants/dispute_valid_candidates.rs
  polkadot/node/malus/src/variants/suggest_garbage_candidate.rs
  polkadot/node/malus/src/variants/support_disabled.rs
  polkadot/node/service/src/lib.rs
  polkadot/node/service/src/overseer.rs
  polkadot/node/test/service/src/lib.rs
  polkadot/parachain/test-parachains/adder/collator/src/main.rs
  polkadot/parachain/test-parachains/undying/collator/src/main.rs
  prdoc/pr_3061.prdoc
Labels: T0-node

#3104 Fix markdown lint error
  substrate/frame/sassafras/src/data/tickets-sort.md
Labels: R0-silent

#3085 Fix delivery fees issue
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/assets/asset-hub-rococo/src/tests/reserve_transfer.rs
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
  polkadot/xcm/xcm-executor/Cargo.toml
  polkadot/xcm/xcm-executor/src/lib.rs
Labels: R0-silent

#3072 Add two new zombienet tests for bridges (manual run)
  bridges/zombienet/helpers/chains/rococo-at-westend.js
  bridges/zombienet/helpers/chains/westend-at-rococo.js
  bridges/zombienet/helpers/only-mandatory-headers-synced-when-idle.js
  bridges/zombienet/helpers/only-required-headers-synced-when-idle.js
  bridges/zombienet/helpers/utils.js
  bridges/zombienet/run-tests.sh
  bridges/zombienet/scripts/invoke-script.sh
  bridges/zombienet/scripts/start-relayer.sh
  bridges/zombienet/tests/0001-asset-transfer-works-rococo-to-westend.zndsl
  bridges/zombienet/tests/0001-asset-transfer-works-westend-to-rococo.zndsl
  bridges/zombienet/tests/0001-start-relay.sh
  bridges/zombienet/tests/0002-mandatory-headers-synced-while-idle-rococo-to-westend.zndsl
  bridges/zombienet/tests/0002-mandatory-headers-synced-while-idle-westend-to-rococo.zndsl
  bridges/zombienet/tests/0003-required-headers-synced-while-active-rococo-to-westend.zndsl
  bridges/zombienet/tests/0003-required-headers-synced-while-active-westend-to-rococo.zndsl
  cumulus/scripts/bridges_common.sh
Labels: R0-silent

#3087 Link mermaid docs to crate that uses them
  substrate/primitives/runtime/docs
  substrate/primitives/runtime/src/generic/unchecked_extrinsic.rs
Labels: A1-insubstantial, R0-silent

#3082 Error on duplicated crates
  .github/scripts/check-workspace.py
  Cargo.toml
Labels: R0-silent

#3105 Fix recv_signal in orchestra
  Cargo.lock
  polkadot/node/overseer/Cargo.toml
  polkadot/node/subsystem-bench/Cargo.toml
  polkadot/node/subsystem-types/Cargo.toml
Labels: R0-silent, T0-node, I2-bug, T8-polkadot

#3111 backporting gitspiegel-trigger.yml from master
  .github/workflows/.github/workflows/gitspiegel-trigger.yml
Labels: R0-silent

#2302 [Runtime] Bound XCMP queue
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/xcmp-queue/src/lib.rs
  cumulus/pallets/xcmp-queue/src/migration.rs
  cumulus/pallets/xcmp-queue/src/migration/v5.rs
  cumulus/pallets/xcmp-queue/src/mock.rs
  cumulus/pallets/xcmp-queue/src/tests.rs
  cumulus/parachain-template/runtime/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  cumulus/primitives/core/src/lib.rs
  polkadot/parachain/src/primitives.rs
  prdoc/pr_2302.prdoc
Labels: T2-pallets

#3122 Move candidate-validation on blocking tasks
  polkadot/node/overseer/src/lib.rs
Labels: R0-silent, T8-polkadot

#3125 Remove `forklift clean` call from CI
  .gitlab-ci.yml
Labels: R0-silent

#3124 Remove symlinks of non existing files
  cumulus/polkadot-parachain/chain-specs/asset-hub-wococo.json
  cumulus/polkadot-parachain/chain-specs/bridge-hub-wococo.json
Labels: R0-silent

#3117 Revert "[Runtime] Bound XCMP queue"
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/xcmp-queue/src/lib.rs
  cumulus/pallets/xcmp-queue/src/migration.rs
  cumulus/pallets/xcmp-queue/src/migration/v5.rs
  cumulus/pallets/xcmp-queue/src/mock.rs
  cumulus/pallets/xcmp-queue/src/tests.rs
  cumulus/parachain-template/runtime/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  cumulus/primitives/core/src/lib.rs
  polkadot/parachain/src/primitives.rs
  prdoc/pr_2302.prdoc
Labels: R0-silent

#3135 Bump Bridge Hub Rococo spec version
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
Labels: R0-silent

#3110 Nomination pools: Fix payout destination in permissionless unbond
  prdoc/pr_3110.prdoc
  substrate/frame/nomination-pools/Cargo.toml
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/nomination-pools/src/tests.rs
Labels: T2-pallets

#3112 (backport) Nomination pools: Fix payout destination in permissionless unbond
  Cargo.lock
  substrate/frame/nomination-pools/Cargo.toml
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/nomination-pools/src/tests.rs
Labels: T2-pallets

#3108 revert paritytech/polkadot#6577 & related changes
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_3108.prdoc
  substrate/bin/node/runtime/src/lib.rs
Labels: T15-bridges

#3126 Chore: link code TODO for removing redundant message information
  polkadot/node/network/protocol/src/lib.rs
Labels: A1-insubstantial, R0-silent, T8-polkadot

#3016 [ci] Update rust in ci image (1.75 and 2024-01-22)
  .github/workflows/fmt-check.yml
  .gitlab-ci.yml
  bridges/snowbridge/parachain/pallets/system/src/lib.rs
  docs/sdk/src/reference_docs/development_environment_advice.rs
  polkadot/node/subsystem-bench/src/availability/mod.rs
  polkadot/node/subsystem-bench/src/core/keyring.rs
  polkadot/node/subsystem-bench/src/core/mock/mod.rs
  substrate/frame/alliance/src/mock.rs
  substrate/frame/contracts/fixtures/build.rs
  substrate/frame/support/procedural/src/pallet/expand/call.rs
  substrate/frame/support/test/tests/construct_runtime_ui/deprecated_where_block.stderr
  substrate/frame/support/test/tests/pallet_ui/default_config_with_no_default_in_system.stderr
  substrate/frame/support/test/tests/pallet_ui/error_does_not_derive_pallet_error.rs
  substrate/frame/support/test/tests/pallet_ui/error_does_not_derive_pallet_error.stderr
  substrate/frame/support/test/tests/pallet_ui/event_field_not_member.rs
  substrate/frame/support/test/tests/pallet_ui/event_field_not_member.stderr
  substrate/frame/support/test/tests/pallet_ui/pass/error_nested_types.rs
  substrate/frame/support/test/tests/pallet_ui/pass/event_type_bound_system_config_assoc_type.rs
  substrate/frame/support/test/tests/pallet_ui/storage_result_query_missing_generics.rs
  substrate/frame/support/test/tests/pallet_ui/storage_result_query_missing_generics.stderr
  substrate/primitives/api/test/tests/ui/impl_two_traits_with_same_name.rs
  substrate/primitives/api/test/tests/ui/impl_two_traits_with_same_name.stderr
Labels: A1-insubstantial, R0-silent

#3114 Add limits to XCMv4
  polkadot/xcm/src/lib.rs
  polkadot/xcm/src/v3/mod.rs
  polkadot/xcm/src/v4/asset.rs
  polkadot/xcm/src/v4/mod.rs
Labels: R0-silent, T6-XCM

#3146 Fix for `poeple-*` benchmarks command + added them to CI
  .gitlab/pipeline/short-benchmarks.yml
  cumulus/polkadot-parachain/src/chain_spec/people.rs
Labels: R0-silent, T12-benchmarks

#3142 xcm-executor: DepositReserveAsset charges delivery fees from inner assets
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/reserve_transfer.rs
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
  polkadot/xcm/xcm-executor/src/lib.rs
Labels: R0-silent, T6-XCM

#3152 Fail early at obviously invalid approvals
  polkadot/node/network/approval-distribution/src/lib.rs
  polkadot/node/network/approval-distribution/src/tests.rs
Labels: R0-silent

#3150 Addressing Liam's comments from https://github.com/paritytech/polkadot-sdk/pull/2657
  substrate/frame/support/procedural/src/construct_runtime/expand/composite_helper.rs
  substrate/frame/support/procedural/src/lib.rs
  substrate/frame/support/procedural/src/pallet/expand/composite.rs
  substrate/frame/support/procedural/src/pallet/parse/composite.rs
Labels: R0-silent

#3157 [xcm] Fix `SovereignPaidRemoteExporter` and `DepositAsset` handling
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases_over_bridge.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/mod.rs
  polkadot/xcm/xcm-builder/src/tests/bridging/mod.rs
  polkadot/xcm/xcm-builder/src/tests/bridging/paid_remote_relay_relay.rs
  polkadot/xcm/xcm-builder/src/tests/bridging/universal_exports.rs
  polkadot/xcm/xcm-builder/src/universal_exports.rs
Labels: R0-silent, T6-XCM, T15-bridges

#3156 [FRAME] Make `core-fellowship` ans `salary` work for swapped members
  Cargo.lock
  cumulus/parachains/runtimes/collectives/collectives-westend/src/ambassador/mod.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/fellowship/mod.rs
  polkadot/runtime/rococo/src/governance/fellowship.rs
  prdoc/pr_3156.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/core-fellowship/Cargo.toml
  substrate/frame/core-fellowship/src/benchmarking.rs
  substrate/frame/core-fellowship/src/lib.rs
  substrate/frame/core-fellowship/src/tests/integration.rs
  substrate/frame/core-fellowship/src/tests/mod.rs
  substrate/frame/core-fellowship/src/tests/unit.rs
  substrate/frame/ranked-collective/Cargo.toml
  substrate/frame/ranked-collective/src/benchmarking.rs
  substrate/frame/ranked-collective/src/lib.rs
  substrate/frame/ranked-collective/src/tests.rs
  substrate/frame/salary/Cargo.toml
  substrate/frame/salary/src/benchmarking.rs
  substrate/frame/salary/src/lib.rs
  substrate/frame/salary/src/tests/integration.rs
  substrate/frame/salary/src/tests/mod.rs
  substrate/frame/salary/src/tests/unit.rs
  substrate/frame/support/src/traits.rs
  substrate/frame/support/src/traits/dispatch.rs
  substrate/frame/support/src/traits/members.rs
Labels: T2-pallets

#3140 [Documentation] Add description for VoteTally's methods
  substrate/frame/support/src/traits/voting.rs
Labels: R0-silent
