Repository paritytech/polkadot-sdk, pull requests merged in 2025-07, with the labels that each got.

#8860 XCMP and DMP improvements
  cumulus/pallets/parachain-system/src/benchmarking.rs
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/parachain-system/src/mock.rs
  cumulus/pallets/parachain-system/src/parachain_inherent.rs
  cumulus/pallets/parachain-system/src/tests.rs
  cumulus/pallets/parachain-system/src/unincluded_segment.rs
  cumulus/pallets/parachain-system/src/validate_block/implementation.rs
  cumulus/parachains/runtimes/test-utils/src/lib.rs
  cumulus/primitives/parachain-inherent/src/lib.rs
  cumulus/test/service/src/bench_utils.rs
  cumulus/xcm/xcm-emulator/src/lib.rs
  polkadot/node/subsystem-util/src/inclusion_emulator/mod.rs
  polkadot/runtime/parachains/src/hrmp.rs
  polkadot/runtime/parachains/src/hrmp/tests.rs
  prdoc/pr_8860.prdoc
Labels: T9-cumulus, T18-zombienet_tests

#8937 [Staking] [AHM] Fixes insufficient slashing of nominators (and some other small issues).
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/staking.rs
  prdoc/pr_8937.prdoc
  substrate/frame/staking-async/ahm-test/src/ah/mock.rs
  substrate/frame/staking-async/runtimes/parachain/src/staking.rs
  substrate/frame/staking-async/src/mock.rs
  substrate/frame/staking-async/src/pallet/mod.rs
  substrate/frame/staking-async/src/slashing.rs
  substrate/frame/staking-async/src/tests/bonding.rs
  substrate/frame/staking-async/src/tests/slashing.rs
Labels: T2-pallets

#8974 Fix flaxy 0003-block-building-warp-sync test - one more approach
  .github/zombienet-flaky-tests
  prdoc/pr_8974.prdoc
  substrate/zombienet/0003-block-building-warp-sync/test-block-building-warp-sync.zndsl
Labels: R0-no-crate-publish-required, T0-node, T18-zombienet_tests

#8896 Cleanup and improvements for `ControlledValidatorIndices`
  Cargo.lock
  polkadot/node/core/dispute-coordinator/src/import.rs
  polkadot/node/subsystem-util/Cargo.toml
  polkadot/node/subsystem-util/src/controlled_validator_indices.rs
  prdoc/pr_8896.prdoc
Labels: T0-node, T8-polkadot

#9057 Align parameters for `EventEmitter::emit_sent_event`
  polkadot/xcm/xcm-executor/src/traits/event_emitter.rs
  prdoc/pr_9057.prdoc
Labels: R0-no-crate-publish-required, T6-XCM

#9050 dispute-coordinator: handle race with offchain disabling
  polkadot/node/core/dispute-coordinator/src/initialized.rs
  polkadot/node/core/dispute-coordinator/src/metrics.rs
  polkadot/node/core/dispute-coordinator/src/tests.rs
  prdoc/pr_9050.prdoc
Labels: T0-node, T8-polkadot, A4-backport-stable2503, A4-backport-stable2506

#8839 net/discovery: File persistence for `AddrCache`
  Cargo.lock
  Cargo.toml
  cumulus/client/relay-chain-minimal-node/src/lib.rs
  polkadot/node/service/src/builder/mod.rs
  prdoc/pr_8839.prdoc
  substrate/bin/node/cli/src/service.rs
  substrate/client/authority-discovery/Cargo.toml
  substrate/client/authority-discovery/src/error.rs
  substrate/client/authority-discovery/src/lib.rs
  substrate/client/authority-discovery/src/tests.rs
  substrate/client/authority-discovery/src/worker.rs
  substrate/client/authority-discovery/src/worker/addr_cache.rs
  substrate/client/authority-discovery/src/worker/tests.rs
  substrate/client/network/types/Cargo.toml
  substrate/client/network/types/src/multiaddr.rs
  substrate/client/network/types/src/peer_id.rs
Labels: T0-node, T8-polkadot, A4-backport-stable2412, A4-backport-stable2503, A4-backport-stable2506

#9034 add try-state check for staking roles -- staker cannot be nominator a…
  substrate/frame/staking-async/src/pallet/impls.rs
Labels: R0-no-crate-publish-required

#9063 `sp-tracing`: Remove `test-utils` feature
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/Cargo.toml
  polkadot/xcm/pallet-xcm/Cargo.toml
  polkadot/xcm/xcm-builder/Cargo.toml
  polkadot/xcm/xcm-simulator/example/Cargo.toml
  prdoc/pr_9063.prdoc
  substrate/primitives/tracing/Cargo.toml
  substrate/primitives/tracing/src/lib.rs
Labels: T17-primitives

#9047 Add extra information to the harmless error logs during validate_transaction
  prdoc/pr_9047.prdoc
  substrate/primitives/api/proc-macro/src/impl_runtime_apis.rs
Labels: A4-backport-stable2506

#9084 Fix `MaxEncodedLen` implementation for `Error` enum
  polkadot/xcm/src/v3/traits.rs
  polkadot/xcm/src/v5/traits.rs
  prdoc/pr_9084.prdoc
Labels: T6-XCM

#9092 [Release|CI/CD] Fix syncing in the release flow
  .github/workflows/release-30_publish_release_draft.yml
  .github/workflows/release-31_promote-rc-to-final.yml
  .github/workflows/release-40_publish-deb-package.yml
  .github/workflows/release-50_publish-docker.yml
Labels: R0-no-crate-publish-required, A4-backport-stable2412, A4-backport-stable2503, A4-backport-stable2506

#9049 Optimize buffered offence storage and prevent unbounded growth in staking-async ah-client pallet
  Cargo.lock
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/pallet_staking_async_ah_client.rs
  prdoc/pr_9049.prdoc
  substrate/frame/staking-async/ah-client/Cargo.toml
  substrate/frame/staking-async/ah-client/src/benchmarking.rs
  substrate/frame/staking-async/ah-client/src/lib.rs
  substrate/frame/staking-async/ah-client/src/mock.rs
  substrate/frame/staking-async/ah-client/src/weights.rs
  substrate/frame/staking-async/ahm-test/src/lib.rs
  substrate/frame/staking-async/ahm-test/src/rc/mock.rs
  substrate/frame/staking-async/runtimes/rc/src/lib.rs
Labels: T2-pallets

#9102 `polkadot-omni-node`: pass timestamp inherent data for block import
  cumulus/polkadot-omni-node/lib/src/nodes/aura.rs
  prdoc/pr_9102.prdoc
Labels: T0-node, I5-enhancement

#9130 [stable2503] Backport #9130
  polkadot/runtime/common/src/xcm_sender.rs
  prdoc/pr_9130.prdoc
Labels: T12-benchmarks

#9129 ci: disable test-linux-stable-runtime-benchmarks
  .github/workflows/tests-linux-stable.yml
Labels: R0-no-crate-publish-required

#9074 make 0002-parachains-disputes a bit more robust
  .github/workflows/zombienet_polkadot.yml
  .github/zombienet-flaky-tests
  polkadot/zombienet_tests/functional/0002-parachains-disputes.zndsl
Labels: R0-no-crate-publish-required

#9112 Fix seal_call benchmark
  prdoc/pr_9112.prdoc
  substrate/frame/revive/src/benchmarking.rs
  substrate/frame/revive/src/weights.rs
Labels: T7-smart_contracts

#9135 XCM precompile: small cleanup
  polkadot/xcm/pallet-xcm/src/precompiles.rs
Labels: R0-no-crate-publish-required, T6-XCM, T7-smart_contracts

#9118 [Release|CI/CD] Move runtimes build to a separate pipeline and let it trigger the next flow
  .github/workflows/release-21_build-runtimes.yml
  .github/workflows/release-30_publish_release_draft.yml
  .github/workflows/release-srtool.yml
Labels: R0-no-crate-publish-required

#9131 Enable parachain-templates zombienet tests
  .github/workflows/zombienet_parachain-template.yml
Labels: R0-no-crate-publish-required, T10-tests

#9136 Fix `set_max_upward_queue_size`
  polkadot/runtime/parachains/src/configuration.rs
  polkadot/runtime/parachains/src/configuration/tests.rs
  prdoc/pr_9136.prdoc
Labels: T8-polkadot

#8732 Replace `log` with `tracing` on XCM-related modules
  Cargo.lock
  bridges/modules/xcm-bridge-hub-router/Cargo.toml
  bridges/modules/xcm-bridge-hub-router/src/lib.rs
  bridges/modules/xcm-bridge-hub/Cargo.toml
  bridges/modules/xcm-bridge-hub/src/dispatcher.rs
  bridges/modules/xcm-bridge-hub/src/exporter.rs
  bridges/modules/xcm-bridge-hub/src/lib.rs
  bridges/modules/xcm-bridge-hub/src/migration.rs
  cumulus/pallets/xcmp-queue/Cargo.toml
  cumulus/pallets/xcmp-queue/src/lib.rs
  cumulus/pallets/xcmp-queue/src/migration.rs
  cumulus/pallets/xcmp-queue/src/migration/v5.rs
  cumulus/parachains/common/Cargo.toml
  cumulus/parachains/common/src/impls.rs
  cumulus/parachains/common/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/staking.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_data/mod.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-rococo/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/coretime.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-westend/src/coretime.rs
  cumulus/parachains/runtimes/people/people-rococo/Cargo.toml
  cumulus/parachains/runtimes/people/people-westend/Cargo.toml
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/Cargo.toml
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
  polkadot/xcm/Cargo.toml
  polkadot/xcm/src/lib.rs
  polkadot/xcm/src/v3/traits.rs
  polkadot/xcm/src/v4/mod.rs
  polkadot/xcm/xcm-runtime-apis/Cargo.toml
  polkadot/xcm/xcm-runtime-apis/tests/mock.rs
  polkadot/xcm/xcm-simulator/example/Cargo.toml
  polkadot/xcm/xcm-simulator/example/src/tests.rs
  prdoc/pr_8732.prdoc
Labels: T6-XCM

#9159 `fatxpool`: debug levels adjusted
  prdoc/pr_9159.prdoc
  substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs
Labels: T0-node

#9107 Add BlockNumberProvider to PureCreated Event
  prdoc/pr_9107.prdoc
  substrate/frame/proxy/src/benchmarking.rs
  substrate/frame/proxy/src/lib.rs
  substrate/frame/proxy/src/tests.rs
Labels: T2-pallets

#9152 use correct era planning config in westend-asset-hub
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/staking.rs
Labels: R0-no-crate-publish-required

#9166 pallet-bags-list: Emit `ScoreUpdated` event only if it has changed
  prdoc/pr_9166.prdoc
  substrate/bin/node/bench/src/import.rs
  substrate/frame/bags-list/src/lib.rs
Labels: T2-pallets

#7250 Add Missing Events for Balances Pallet
  prdoc/pr_7250.prdoc
  substrate/frame/balances/src/impl_currency.rs
  substrate/frame/balances/src/impl_fungible.rs
  substrate/frame/balances/src/lib.rs
  substrate/frame/balances/src/tests/currency_tests.rs
  substrate/frame/balances/src/tests/fungible_tests.rs
  substrate/frame/balances/src/tests/reentrancy_tests.rs
  substrate/frame/collective/src/tests.rs
  substrate/frame/contracts/src/tests.rs
  substrate/frame/offences/benchmarking/src/inner.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/support/src/traits/tokens/fungible/hold.rs
Labels: T2-pallets

#9175 Deduplicate client-side inherents checking logic
  cumulus/client/consensus/aura/src/equivocation_import_queue.rs
  cumulus/client/consensus/relay-chain/src/import_queue.rs
  prdoc/pr_9175.prdoc
  substrate/client/consensus/aura/src/import_queue.rs
  substrate/client/consensus/aura/src/lib.rs
  substrate/client/consensus/babe/src/lib.rs
  substrate/client/consensus/pow/src/lib.rs
  substrate/primitives/block-builder/src/client_side.rs
  substrate/primitives/block-builder/src/lib.rs
  substrate/primitives/inherents/src/lib.rs
Labels: T0-node

#9141 Asset Hub Westend: nfts block provider is RC
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/governance/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_9141.prdoc
Labels: T14-system_parachains

#9191 Fixed westend asset hub ID
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_9191.prdoc
Labels: I2-bug, T4-runtime_API, T14-system_parachains

#9243 Don't use labels for branch names creation in the backport bot
  .github/workflows/command-backport.yml
Labels: R0-no-crate-publish-required

#9252 Remove `subwasmlib`
  Cargo.lock
  polkadot/zombienet-sdk-tests/Cargo.toml
  polkadot/zombienet-sdk-tests/build.rs
Labels: R0-no-crate-publish-required

#9262 feat(cumulus): Adds support for additional relay state keys in parachain validation data inherent
  cumulus/client/consensus/aura/src/collator.rs
  cumulus/client/parachain-inherent/src/lib.rs
  prdoc/pr_9262.prdoc
Labels: T9-cumulus

#9255 Fix CandidateDescriptor debug logs
  polkadot/primitives/src/vstaging/mod.rs
  prdoc/pr_9255.prdoc
Labels: T0-node, T8-polkadot

#9264 gossip-support: make low connectivity message an error
  polkadot/node/network/gossip-support/src/lib.rs
  prdoc/pr_9264.prdoc
Labels: A4-backport-stable2503, A4-backport-stable2506

#9257 Rewrite old disputes test with zombienet-sdk
  .github/workflows/zombienet_polkadot.yml
  polkadot/zombienet-sdk-tests/tests/functional/dispute_old_finalized.rs
  polkadot/zombienet-sdk-tests/tests/functional/mod.rs
  polkadot/zombienet_tests/functional/0008-dispute-old-finalized.toml
  polkadot/zombienet_tests/functional/0008-dispute-old-finalized.zndsl
Labels: R0-no-crate-publish-required, T0-node, T8-polkadot, T18-zombienet_tests

#9015 consensus/grandpa: Fix high number of peer disconnects with invalid justification
  bridges/primitives/header-chain/src/justification/verification/mod.rs
  prdoc/pr_9015.prdoc
  substrate/client/consensus/common/src/import_queue.rs
  substrate/client/consensus/common/src/import_queue/basic_queue.rs
  substrate/client/consensus/common/src/import_queue/buffered_link.rs
  substrate/client/consensus/common/src/lib.rs
  substrate/client/consensus/grandpa/src/communication/gossip.rs
  substrate/client/consensus/grandpa/src/communication/mod.rs
  substrate/client/consensus/grandpa/src/import.rs
  substrate/client/consensus/grandpa/src/justification.rs
  substrate/client/network/sync/src/engine.rs
  substrate/client/network/sync/src/service/mock.rs
  substrate/client/network/sync/src/service/syncing_service.rs
  substrate/primitives/blockchain/src/error.rs
  substrate/primitives/consensus/common/src/error.rs
  substrate/primitives/consensus/grandpa/src/lib.rs
Labels: T0-node

#9233 Dedup dependencies between dependencies and dev-dependencies
  bridges/modules/relayers/Cargo.toml
  bridges/modules/xcm-bridge-hub/Cargo.toml
  bridges/primitives/messages/Cargo.toml
  cumulus/client/network/Cargo.toml
  cumulus/client/pov-recovery/Cargo.toml
  cumulus/client/relay-chain-inprocess-interface/Cargo.toml
  cumulus/test/service/Cargo.toml
  polkadot/node/core/approval-voting-parallel/Cargo.toml
  polkadot/node/core/approval-voting/Cargo.toml
  polkadot/node/core/av-store/Cargo.toml
  polkadot/node/core/pvf/prepare-worker/Cargo.toml
  polkadot/node/malus/Cargo.toml
  polkadot/node/network/availability-distribution/Cargo.toml
  polkadot/node/network/availability-recovery/Cargo.toml
  polkadot/node/network/dispute-distribution/Cargo.toml
  polkadot/node/network/statement-distribution/Cargo.toml
  polkadot/parachain/test-parachains/adder/collator/Cargo.toml
  polkadot/parachain/test-parachains/undying/collator/Cargo.toml
  polkadot/xcm/xcm-runtime-apis/Cargo.toml
  substrate/bin/node/cli/Cargo.toml
  substrate/client/consensus/grandpa/Cargo.toml
  substrate/client/consensus/grandpa/rpc/Cargo.toml
  substrate/client/network/Cargo.toml
  substrate/client/network/sync/Cargo.toml
  substrate/client/offchain/Cargo.toml
  substrate/client/rpc/Cargo.toml
  substrate/client/transaction-pool/Cargo.toml
  substrate/frame/election-provider-multi-block/Cargo.toml
  substrate/frame/election-provider-multi-phase/Cargo.toml
  substrate/frame/revive/rpc/Cargo.toml
  substrate/frame/staking-async/ah-client/Cargo.toml
  substrate/frame/staking-async/ah-client/src/mock.rs
  substrate/test-utils/runtime/Cargo.toml
Labels: R0-no-crate-publish-required

#9294 Replace `log` with `tracing` on `pallet-bridge-grandpa`
  Cargo.lock
  bridges/modules/grandpa/Cargo.toml
  bridges/modules/grandpa/src/call_ext.rs
  bridges/modules/grandpa/src/lib.rs
  prdoc/pr_9294.prdoc
Labels: T15-bridges

#9179 Fix subsume_assets incorrectly merging two AssetsInHolding
  polkadot/xcm/xcm-executor/src/assets.rs
  prdoc/pr_9179.prdoc
Labels: T6-XCM, A4-backport-stable2409, A4-backport-stable2412, A4-backport-stable2503, A4-backport-stable2506, A4-backport-unstable2507

#9321 network/litep2p: Switch to system DNS resolver
  prdoc/pr_9321.prdoc
  substrate/client/network/src/litep2p/mod.rs
Labels: T0-node

#9281 litep2p/discovery: Ensure non-global addresses are not reported as external
  prdoc/pr_9281.prdoc
  substrate/client/network/src/litep2p/discovery.rs
Labels: T0-node, A4-backport-stable2503, A4-backport-stable2506, A4-backport-unstable2507

#9189 `fatxpool`: avoid premature revalidation of transactions
  prdoc/pr_9189.prdoc
  substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/tx_mem_pool.rs
  substrate/client/transaction-pool/tests/fatp.rs
Labels: T0-node

#9338 fatxpool: instant seal support
  prdoc/pr_9338.prdoc
  substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs
  substrate/client/transaction-pool/tests/fatp.rs
  substrate/client/transaction-pool/tests/fatp_common/mod.rs
  substrate/client/transaction-pool/tests/fatp_invalid.rs
Labels: T0-node

#9288 Replace `log` with `tracing` on `bridge-runtime-common`
  Cargo.lock
  bridges/bin/runtime-common/Cargo.toml
  bridges/bin/runtime-common/src/messages_benchmarking.rs
  prdoc/pr_9288.prdoc
Labels: T15-bridges

#9079 Ensure withdrawals don’t bypass slashing
  prdoc/pr_9079.prdoc
  substrate/frame/staking-async/ahm-test/src/ah/mock.rs
  substrate/frame/staking-async/ahm-test/src/ah/test.rs
  substrate/frame/staking-async/src/benchmarking.rs
  substrate/frame/staking-async/src/lib.rs
  substrate/frame/staking-async/src/mock.rs
  substrate/frame/staking-async/src/pallet/impls.rs
  substrate/frame/staking-async/src/pallet/mod.rs
  substrate/frame/staking-async/src/testing_utils.rs
  substrate/frame/staking-async/src/tests/bonding.rs
  substrate/frame/staking-async/src/tests/slashing.rs
Labels: T2-pallets, R1-breaking_change

#8840 include poll_index in voted and vote removed event
  prdoc/pr_8840.prdoc
  substrate/frame/conviction-voting/src/lib.rs
  substrate/frame/conviction-voting/src/tests.rs
Labels: T2-pallets

#9348 [Release|CI/CD] Add node version to the release announcement
  .github/workflows/release-99_notif-published.yml
Labels: R0-no-crate-publish-required, A4-backport-stable2506

#9326 [HRMP] Check messages order before enqueing them
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/parachain-system/src/parachain_inherent.rs
  cumulus/pallets/parachain-system/src/tests.rs
  polkadot/primitives/src/v8/mod.rs
  prdoc/pr_9326.prdoc
Labels: T9-cumulus, A4-backport-unstable2507

#9318 Replace `log` with `tracing` on `pallet-bridge-parachains`
  Cargo.lock
  bridges/modules/parachains/Cargo.toml
  bridges/modules/parachains/src/benchmarking.rs
  bridges/modules/parachains/src/call_ext.rs
  bridges/modules/parachains/src/lib.rs
  prdoc/pr_9318.prdoc
Labels: T15-bridges

#9310 update the builder dockerfile
  docker/dockerfiles/polkadot/polkadot_builder.Dockerfile
Labels: R0-no-crate-publish-required

#9355 substrate-prometheus-endpoint: directly require the feature "tokio/net"
  prdoc/pr_9355.prdoc
  substrate/utils/prometheus/Cargo.toml
Labels: T17-primitives

#9353 Maintenance of bootnodes for `westend` and related chains
  cumulus/parachains/chain-specs/asset-hub-westend.json
  cumulus/parachains/chain-specs/bridge-hub-westend.json
  cumulus/parachains/chain-specs/collectives-westend.json
  cumulus/parachains/chain-specs/coretime-westend.json
  cumulus/parachains/chain-specs/people-westend.json
  polkadot/node/service/chain-specs/westend.json
Labels: R0-no-crate-publish-required

#9362 cumulus zombienet: Send transactions as immortal
  cumulus/zombienet/zombienet-sdk-helpers/src/lib.rs
  cumulus/zombienet/zombienet-sdk/tests/zombie_ci/parachain_extrinsic_get_finalized.rs
Labels: R0-no-crate-publish-required

#9354 Remove whitespaces added by macros due to token re-parsing
  prdoc/pr_9354.prdoc
  substrate/frame/benchmarking/src/v1.rs
Labels: T12-benchmarks, A4-backport-stable2409, A4-backport-stable2412, A4-backport-stable2503, A4-backport-stable2506, A4-backport-unstable2507

#9347 Fix definition of held balance
  substrate/frame/staking/src/lib.rs
  substrate/frame/support/src/traits/tokens/fungible/mod.rs
Labels: R0-no-crate-publish-required

#9382 [stable2506] Fix `pallet-xcm` tests with `test_log_capture`
  polkadot/xcm/pallet-xcm/Cargo.toml
Labels: R0-no-crate-publish-required, T6-XCM, T10-tests

#8857 [FRAME] Custom log level for the runtime benchmarks
  Cargo.lock
  Cargo.toml
  prdoc/pr_8857.prdoc
  substrate/utils/frame/benchmarking-cli/Cargo.toml
  substrate/utils/frame/benchmarking-cli/src/pallet/command.rs
  substrate/utils/frame/benchmarking-cli/src/pallet/logging.rs
  substrate/utils/frame/benchmarking-cli/src/pallet/mod.rs
  substrate/utils/frame/benchmarking-cli/src/pallet/writer.rs
Labels: T12-benchmarks, A4-backport-stable2503, A4-backport-stable2506, A4-backport-unstable2507

#8172 Ignore trie nodes while recording a proof
  Cargo.lock
  cumulus/client/consensus/proposer/Cargo.toml
  cumulus/client/consensus/proposer/src/lib.rs
  cumulus/pallets/parachain-system/Cargo.toml
  cumulus/pallets/parachain-system/src/validate_block/implementation.rs
  cumulus/pallets/parachain-system/src/validate_block/tests.rs
  cumulus/pallets/parachain-system/src/validate_block/trie_cache.rs
  cumulus/pallets/parachain-system/src/validate_block/trie_recorder.rs
  cumulus/polkadot-omni-node/lib/src/nodes/aura.rs
  cumulus/test/client/src/block_builder.rs
  cumulus/test/client/src/lib.rs
  cumulus/test/runtime/src/lib.rs
  cumulus/test/runtime/src/test_pallet.rs
  cumulus/test/service/benches/validate_block.rs
  cumulus/test/service/benches/validate_block_glutton.rs
  cumulus/test/service/src/chain_spec.rs
  cumulus/test/service/src/lib.rs
  cumulus/zombienet/zombienet-sdk/tests/zombie_ci/elastic_scaling/slot_based_authoring.rs
  polkadot/primitives/src/vstaging/mod.rs
  prdoc/pr_8172.prdoc
  substrate/bin/node/bench/src/construct.rs
  substrate/bin/node/cli/src/service.rs
  substrate/client/basic-authorship/Cargo.toml
  substrate/client/basic-authorship/src/basic_authorship.rs
  substrate/client/basic-authorship/src/lib.rs
  substrate/client/block-builder/src/lib.rs
  substrate/client/consensus/common/src/block_import.rs
  substrate/primitives/api/proc-macro/src/impl_runtime_apis.rs
  substrate/primitives/api/proc-macro/src/mock_impl_runtime_apis.rs
  substrate/primitives/api/src/lib.rs
  substrate/primitives/trie/src/recorder.rs
  substrate/primitives/trie/src/trie_codec.rs
  templates/parachain/node/src/service.rs
Labels: T0-node, T18-zombienet_tests

#7321 Update XCM benchmarks delivery to sibling parachains not parent/relay chain
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/bridge-primitives/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/constants/src/rococo.rs
  cumulus/parachains/runtimes/constants/src/westend.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/people/people-westend/src/xcm_config.rs
  polkadot/runtime/rococo/constants/src/lib.rs
  polkadot/runtime/westend/constants/src/lib.rs
  prdoc/pr_7321.prdoc
Labels: T6-XCM, T12-benchmarks

#9378 Replace `log` with `tracing` on `pallet-bridge-beefy`
  Cargo.lock
  bridges/modules/beefy/Cargo.toml
  bridges/modules/beefy/src/lib.rs
  bridges/modules/beefy/src/utils.rs
  prdoc/pr_9378.prdoc
Labels: T15-bridges

#9384 [AHM] Make stuff public and derive
  polkadot/parachain/src/primitives.rs
  polkadot/runtime/common/src/claims/mod.rs
  polkadot/runtime/common/src/paras_registrar/mod.rs
  polkadot/runtime/parachains/src/inclusion/mod.rs
  prdoc/pr_9384.prdoc
  substrate/frame/bags-list/src/lib.rs
  substrate/frame/bounties/src/lib.rs
  substrate/frame/delegated-staking/src/lib.rs
  substrate/frame/multisig/src/lib.rs
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/preimage/src/lib.rs
  substrate/frame/referenda/src/migration.rs
  substrate/frame/scheduler/src/lib.rs
  substrate/frame/staking-async/src/lib.rs
Labels: T1-FRAME, T2-pallets, A4-backport-unstable2507

#9408 [stable2503] Post crates release updates
  .github/workflows/release-srtool.yml
  Cargo.lock
  Plan.toml
  cumulus/parachains/common/Cargo.toml
  cumulus/parachains/integration-tests/emulated/common/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/collectives/collectives-westend/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-rococo/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-westend/Cargo.toml
  cumulus/parachains/runtimes/glutton/glutton-westend/Cargo.toml
  cumulus/parachains/runtimes/people/people-rococo/Cargo.toml
  cumulus/parachains/runtimes/people/people-westend/Cargo.toml
  cumulus/parachains/runtimes/testing/penpal/Cargo.toml
  cumulus/polkadot-omni-node/lib/Cargo.toml
  cumulus/polkadot-omni-node/lib/src/nodes/mod.rs
  polkadot/node/network/bitfield-distribution/Cargo.toml
  polkadot/node/network/gossip-support/Cargo.toml
  polkadot/node/network/protocol/Cargo.toml
  polkadot/node/primitives/src/lib.rs
  polkadot/xcm/pallet-xcm/Cargo.toml
  polkadot/xcm/xcm-executor/Cargo.toml
  prdoc/stable2503-8/pr_9094.prdoc
  prdoc/stable2503-8/pr_9137.prdoc
  prdoc/stable2503-8/pr_9139.prdoc
  prdoc/stable2503-8/pr_9179.prdoc
  prdoc/stable2503-8/pr_9195.prdoc
  prdoc/stable2503-8/pr_9264.prdoc
  prdoc/stable2503-8/pr_9281.prdoc
  prdoc/stable2503-8/pr_9325.prdoc
  prdoc/stable2503-8/pr_9354.prdoc
  prdoc/stable2503-8/pr_9355.prdoc
  substrate/client/network/Cargo.toml
  substrate/frame/benchmarking/Cargo.toml
  substrate/frame/im-online/Cargo.toml
  substrate/frame/revive/Cargo.toml
  substrate/utils/prometheus/Cargo.toml
  umbrella/Cargo.toml
Labels: R0-no-crate-publish-required
