Repository paritytech/polkadot-sdk, pull requests merged in 2025-08, with the labels that each got.

#9423 Revert "fix(minimal): pre-seal a first block to trigger maintain (#92…
  templates/minimal/node/src/command.rs
  templates/minimal/node/src/service.rs
Labels: R0-no-crate-publish-required

#9024 Westend Secretary Program
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/src/tests/collectives_salary.rs
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/src/tests/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/secretary/mod.rs
  prdoc/pr_9024.prdoc
Labels: R0-no-crate-publish-required

#9416 pallet_revive: Enforce storage deposit limit on plain transfer
  prdoc/pr_9416.prdoc
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/primitives.rs
  substrate/frame/revive/src/storage/meter.rs
  substrate/frame/revive/src/tests.rs
Labels: T7-smart_contracts

#9409 Replace `log` with `tracing` on `xcm-emulator`
  Cargo.lock
  cumulus/xcm/xcm-emulator/Cargo.toml
  cumulus/xcm/xcm-emulator/src/lib.rs
  prdoc/pr_9409.prdoc
Labels: T6-XCM, C2-good-first-issue

#9401 Replace `log` with `tracing` on `bp-runtime`
  Cargo.lock
  bridges/primitives/runtime/Cargo.toml
  bridges/primitives/runtime/src/lib.rs
  bridges/primitives/runtime/src/storage_proof.rs
  prdoc/pr_9401.prdoc
Labels: T15-bridges, C2-good-first-issue

#9393 Added `substrate-node` and `eth-rpc` binaries into release workflow
  .github/scripts/release/release_lib.sh
  .github/workflows/release-20_build-rc.yml
  .github/workflows/release-reusable-rc-build.yml
Labels: R0-no-crate-publish-required

#9411 staking-async/papi-tests: fix justfile to run in CI
  prdoc/pr_9411.prdoc
  substrate/frame/staking-async/runtimes/papi-tests/justfile
Labels: R0-no-crate-publish-required, T10-tests

#9427 do not trigger zombienet workflows on 'labeled'
  .github/workflows/zombienet_cumulus.yml
  .github/workflows/zombienet_parachain-template.yml
  .github/workflows/zombienet_polkadot.yml
  .github/workflows/zombienet_substrate.yml
Labels: R0-no-crate-publish-required, T10-tests, T18-zombienet_tests

#9435 pallet-timestamp is dev dependency of pallet-xcm
  polkadot/xcm/pallet-xcm/Cargo.toml
Labels: R0-no-crate-publish-required, T6-XCM

#9432 CumulusDigestItem: Add function to fetch the relay block identifier
  cumulus/client/consensus/aura/src/equivocation_import_queue.rs
  cumulus/primitives/core/src/lib.rs
  prdoc/pr_9432.prdoc
Labels: T17-primitives

#9441 [pallet-revive] Implement basic `System` pre-compile, move `seal_hash_blake2_256` into it
  prdoc/pr_9441.prdoc
  substrate/frame/revive/fixtures/contracts/crypto_hashes.rs
  substrate/frame/revive/src/benchmarking.rs
  substrate/frame/revive/src/precompiles.rs
  substrate/frame/revive/src/precompiles/builtin.rs
  substrate/frame/revive/src/precompiles/builtin/system.rs
  substrate/frame/revive/src/precompiles/builtin/testdata/900-blake2_256.json
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/vm/runtime.rs
  substrate/frame/revive/src/weights.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv64.rs
Labels: T7-smart_contracts

#9445 pallet-xcm: fix authorized_alias benchmarks
  polkadot/xcm/pallet-xcm/src/benchmarking.rs
  prdoc/pr_9445.prdoc
Labels: T6-XCM, T12-benchmarks, A4-backport-stable2503, A4-backport-stable2506, A4-backport-unstable2507

#9415 Cleanup staking try states + fix min bonds
  prdoc/pr_9415.prdoc
  substrate/frame/nomination-pools/benchmarking/src/inner.rs
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/nomination-pools/src/migration.rs
  substrate/frame/staking-async/src/pallet/impls.rs
  substrate/frame/staking-async/src/pallet/mod.rs
  substrate/frame/staking-async/src/tests/bonding.rs
Labels: T2-pallets, A4-backport-unstable2507

#9459 [CI] add timeout to allow alloy to process the logs
  .github/scripts/process-logs-zombienet-sdk.sh
Labels: R0-no-crate-publish-required, T10-tests, T18-zombienet_tests

#9463 Minor Snowbridge test fixes
  bridges/snowbridge/runtime/test-common/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/bridge_to_ethereum_config.rs
  prdoc/pr_9463.prdoc
Labels: T10-tests, A4-backport-unstable2507

#9475 [unstable2507] Backport #9137
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/common/src/macros.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/transfer_assets_validation.rs
  polkadot/xcm/docs/src/cookbook/relay_token_transactor/tests.rs
  polkadot/xcm/pallet-xcm/Cargo.toml
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/pallet-xcm/src/transfer_assets_validation.rs
  prdoc/pr_9137.prdoc
Labels: A3-backport

#9476 [unstable2507] Post crates release changes
  Cargo.lock
  Plan.toml
  polkadot/xcm/pallet-xcm/Cargo.toml
  prdoc/unstable2507/pr_9137.prdoc
  prdoc/unstable2507/pr_9445.prdoc
Labels: R0-no-crate-publish-required

#9473 check-semver: enable the support for edition 2024
  .github/workflows/check-semver.yml
Labels: R0-no-crate-publish-required

#9489 Remove free balance check in `prepare_unlock`
  polkadot/xcm/pallet-xcm/src/lib.rs
  prdoc/pr_9489.prdoc
Labels: T6-XCM, A4-backport-stable2506, A4-backport-unstable2507

#9495 `fatxpool`: buckets for event-timings metrics adjusted
  prdoc/pr_9495.prdoc
  substrate/client/transaction-pool/src/fork_aware_txpool/metrics.rs
Labels: T0-node

#9516 Fix for `promote_fast` benchmark
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_core_fellowship_ambassador_core.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_core_fellowship_fellowship_core.rs
  prdoc/pr_9516.prdoc
  substrate/frame/core-fellowship/src/benchmarking.rs
  substrate/frame/core-fellowship/src/lib.rs
  substrate/frame/core-fellowship/src/weights.rs
Labels: T12-benchmarks, A4-backport-stable2506, A4-backport-unstable2507

#9316 Enable `TopicIdTracker` to support multiple flows
  cumulus/parachains/integration-tests/emulated/common/src/xcm_helpers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  polkadot/xcm/xcm-simulator/src/lib.rs
  prdoc/pr_9316.prdoc
Labels: T6-XCM, T10-tests

#9526 [CI/CD] Fix build binary flow
  .github/workflows/release-build-binary.yml
Labels: R0-no-crate-publish-required

#9466 Added `subkey` to CI release process
  .github/scripts/release/release_lib.sh
  .github/workflows/release-20_build-rc.yml
  .github/workflows/release-22_combined-rc-runtime-builds-release-draft.yml
  .github/workflows/release-reusable-rc-build.yml
  .github/workflows/release-reusable-s3-upload.yml
Labels: R0-no-crate-publish-required

#9511 EPMB/Signed: Make invulnerables non-eject-able
  prdoc/pr_9511.prdoc
  substrate/frame/election-provider-multi-block/src/signed/mod.rs
  substrate/frame/election-provider-multi-block/src/signed/tests.rs
  substrate/frame/staking-async/runtimes/parachain/src/staking.rs
  substrate/frame/staking-async/src/pallet/impls.rs
Labels: T2-pallets, A4-backport-unstable2507

#9381 Replace `log` with `tracing` on `pallet-bridge-relayers`
  Cargo.lock
  bridges/modules/relayers/Cargo.toml
  bridges/modules/relayers/src/extension/grandpa_adapter.rs
  bridges/modules/relayers/src/extension/mod.rs
  bridges/modules/relayers/src/extension/parachain_adapter.rs
  bridges/modules/relayers/src/lib.rs
  bridges/modules/relayers/src/migration.rs
  prdoc/pr_9381.prdoc
Labels: T15-bridges, C2-good-first-issue

#9177 align eth-rpc response with geth
  prdoc/pr_9177.prdoc
  substrate/frame/revive/rpc/revive_chain.metadata
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/rpc/src/client/storage_api.rs
  substrate/frame/revive/rpc/src/example.rs
  substrate/frame/revive/rpc/src/fee_history_provider.rs
  substrate/frame/revive/rpc/src/receipt_provider.rs
  substrate/frame/revive/src/evm/api/debug_rpc_types.rs
  substrate/frame/revive/src/evm/api/rlp_codec.rs
  substrate/frame/revive/src/evm/api/rpc_types.rs
  substrate/frame/revive/src/evm/api/rpc_types_gen.rs
  substrate/frame/revive/src/evm/api/signature.rs
  substrate/frame/revive/src/evm/api/type_id.rs
  substrate/frame/revive/src/evm/runtime.rs
Labels: T7-smart_contracts

#9539 [XCMP] `take_first_concatenated_xcm()` improvements
  cumulus/pallets/xcmp-queue/src/benchmarking.rs
  cumulus/pallets/xcmp-queue/src/lib.rs
  cumulus/pallets/xcmp-queue/src/tests.rs
  cumulus/pallets/xcmp-queue/src/weights.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/cumulus_pallet_xcmp_queue.rs
  prdoc/pr_9539.prdoc
  substrate/frame/staking-async/runtimes/parachain/src/weights/cumulus_pallet_xcmp_queue.rs
Labels: I9-optimisation, T1-FRAME

#9497 Society pallet supports non-consecutive block provider
  prdoc/pr_9497.prdoc
  substrate/frame/society/src/lib.rs
  substrate/frame/society/src/mock.rs
  substrate/frame/society/src/tests.rs
Labels: T1-FRAME

#9568 [stable2412] Post crates release changes
  Cargo.lock
  Cargo.toml
  Plan.toml
  cumulus/polkadot-omni-node/lib/src/nodes/mod.rs
  polkadot/node/primitives/src/lib.rs
  polkadot/xcm/xcm-executor/Cargo.toml
  prdoc/stable2412-9/pr_9195.prdoc
  prdoc/stable2412-9/pr_9354.prdoc
  prdoc/stable2412-9/pr_9355.prdoc
  substrate/bin/utils/chain-spec-builder/README.md
  substrate/frame/benchmarking/Cargo.toml
  substrate/utils/prometheus/Cargo.toml
  umbrella/Cargo.toml
Labels: R0-no-crate-publish-required

#9593 [stable2503] post crates changes
  Cargo.lock
  Plan.toml
  cumulus/polkadot-omni-node/lib/src/nodes/mod.rs
  polkadot/node/primitives/src/lib.rs
  polkadot/runtime/parachains/Cargo.toml
  polkadot/xcm/pallet-xcm/Cargo.toml
  prdoc/stable2503-9/pr_9445.prdoc
  prdoc/stable2503-9/pr_9564.prdoc
  scripts/release/delete-versions-if-paths-is-present.sh
Labels: R0-no-crate-publish-required

#9544 Disable reserve_asset_transfer for DOT
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/send_xcm.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/send_xcm.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases.rs
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases_over_bridge.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/pallet_xcm.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/pallet_xcm.rs
  polkadot/xcm/docs/src/cookbook/relay_token_transactor/tests.rs
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/pallet-xcm/src/transfer_assets_validation.rs
  prdoc/pr_9544.prdoc
Labels: T6-XCM, A4-backport-stable2409, A4-backport-stable2412, A4-backport-stable2503, A4-backport-stable2506, A4-backport-unstable2507

#9547 Snowbridge Westend runtime config cleanup
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge_v2_rewards.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/bridge_to_ethereum_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/bridge_common_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/bridge_to_ethereum_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/tests.rs
Labels: R0-no-crate-publish-required
