Repository paritytech/polkadot-sdk, pull requests merged in 2025-01, with the labels that each got.

#6285 [CI] Skip SemVer on R0-silent and update docs
  .github/scripts/generate-prdoc.py
  .github/workflows/check-semver.yml
  .github/workflows/command-prdoc.yml
  docs/contributor/prdoc.md
Labels: R0-silent

#7029 Add workflow for networking benchmarks
  .github/workflows/networking-benchmarks.yml
Labels: R0-silent, T12-benchmarks

#6981 [pallet-revive] fix file case
  prdoc/pr_6981.prdoc
  substrate/frame/revive/rpc/examples/js/abi/Errors.json
  substrate/frame/revive/rpc/examples/js/abi/Errors.ts
  substrate/frame/revive/rpc/examples/js/abi/errorTester.ts
  substrate/frame/revive/rpc/examples/js/contracts/Errors.sol
  substrate/frame/revive/rpc/examples/js/pvm/Errors.polkavm
  substrate/frame/revive/rpc/examples/js/src/geth-diff.test.ts
  substrate/frame/revive/rpc/src/tests.rs
Labels: R0-silent, T7-smart_contracts

#7020 Remove warning log from frame-omni-bencher CLI
  prdoc/pr_7020.prdoc
  substrate/utils/frame/omni-bencher/src/main.rs
Labels: R0-silent

#7022 Fix polkadot sdk doc.
  docs/sdk/src/polkadot_sdk/frame_runtime.rs
Labels: R0-silent

#6986 migrate pallet-mixnet to umbrella crate
  Cargo.lock
  prdoc/pr_6986.prdoc
  substrate/frame/mixnet/Cargo.toml
  substrate/frame/mixnet/src/lib.rs
  substrate/frame/src/lib.rs
  umbrella/Cargo.toml
Labels: R0-silent, T2-pallets

#7032 [docs] Fix release naming
  README.md
  cumulus/docs/release.md
  docs/RELEASE.md
Labels: R0-silent

#7036 [WIP] Fix networking-benchmarks
  .github/workflows/benchmarks-networking.yml
  .github/workflows/benchmarks-subsystem.yml
Labels: R0-silent

#7024 Replace duplicated whitelist with whitelisted_storage_keys
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
Labels: R0-silent

#7028 Make `TransactionExtension` tuple of tuple transparent for implication
  prdoc/pr_7028.prdoc
  substrate/frame/system/src/extensions/check_non_zero_sender.rs
  substrate/frame/system/src/extensions/check_nonce.rs
  substrate/frame/transaction-payment/skip-feeless-payment/src/lib.rs
  substrate/primitives/runtime/src/traits/mod.rs
  substrate/primitives/runtime/src/traits/transaction_extension/dispatch_transaction.rs
  substrate/primitives/runtime/src/traits/transaction_extension/mod.rs
Labels: T17-primitives

#7041 Print taplo version in CI
  .github/workflows/reusable-preflight.yml
Labels: R0-silent

#7034 chore: delete repeat words
  polkadot/primitives/src/v8/mod.rs
  polkadot/roadmap/implementers-guide/src/architecture.md
  polkadot/roadmap/implementers-guide/src/protocol-approval.md
  polkadot/roadmap/implementers-guide/src/protocol-validator-disabling.md
  polkadot/roadmap/implementers-guide/src/runtime/session_info.md
  substrate/client/network/README.md
  substrate/frame/democracy/README.md
  substrate/frame/democracy/src/lib.rs
  substrate/frame/recovery/README.md
  substrate/frame/recovery/src/lib.rs
Labels: R0-silent, T11-documentation

#7050 Avoid incomplete block import pipeline with full verifying import queue
  cumulus/client/consensus/aura/src/equivocation_import_queue.rs
  prdoc/pr_7050.prdoc
Labels: T0-node, A4-needs-backport

#7030 [core-fellowship] Add permissionless import_member
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_core_fellowship_ambassador_core.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_core_fellowship_fellowship_core.rs
  prdoc/pr_7030.prdoc
  substrate/frame/core-fellowship/src/benchmarking.rs
  substrate/frame/core-fellowship/src/lib.rs
  substrate/frame/core-fellowship/src/tests/integration.rs
  substrate/frame/core-fellowship/src/tests/unit.rs
  substrate/frame/core-fellowship/src/weights.rs
Labels: T1-FRAME, T2-pallets

#7027 Fix typos
  bridges/SECURITY.md
  bridges/modules/messages/README.md
  cumulus/docs/overview.md
  substrate/client/network/README.md
  substrate/frame/bounties/README.md
  substrate/frame/bounties/src/lib.rs
Labels: R0-silent

#7043 Remove usage of `sp-std` from Substrate
  Cargo.lock
  prdoc/pr_7043.prdoc
  substrate/client/sysinfo/Cargo.toml
  substrate/frame/bags-list/remote-tests/Cargo.toml
  substrate/frame/contracts/Cargo.toml
  substrate/frame/contracts/proc-macro/src/lib.rs
  substrate/frame/contracts/src/transient_storage.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/Cargo.toml
  substrate/frame/nft-fractionalization/Cargo.toml
  substrate/frame/nomination-pools/test-delegate-stake/Cargo.toml
  substrate/frame/nomination-pools/test-transfer-stake/Cargo.toml
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/proc-macro/src/lib.rs
  substrate/frame/revive/src/transient_storage.rs
  substrate/frame/root-offences/Cargo.toml
  substrate/frame/support/procedural/src/pallet/expand/config.rs
  substrate/frame/support/src/lib.rs
  substrate/frame/system/Cargo.toml
  substrate/frame/system/src/lib.rs
  substrate/frame/uniques/Cargo.toml
  substrate/primitives/runtime/src/generic/unchecked_extrinsic.rs
  substrate/primitives/runtime/src/proving_trie/base16.rs
  substrate/primitives/runtime/src/proving_trie/base2.rs
  substrate/primitives/runtime/src/proving_trie/mod.rs
  substrate/primitives/runtime/src/runtime_logger.rs
  substrate/primitives/runtime/src/traits/mod.rs
  substrate/primitives/runtime/src/traits/transaction_extension/mod.rs
Labels: T17-primitives

#7057 workflows: add debug input for sync templates act
  .github/workflows/misc-sync-templates.yml
Labels: R0-silent

#7073 Implement NetworkRequest for litep2p
  prdoc/pr_7073.prdoc
  substrate/client/network/src/litep2p/service.rs
Labels: T12-benchmarks

#7069 Fix defensive! macro to be used in umbrella crates
  prdoc/pr_7069.prdoc
  substrate/frame/support/src/traits/misc.rs
Labels: T1-FRAME

#7068 fix typos
  docs/sdk/src/reference_docs/frame_benchmarking_weight.rs
  substrate/frame/balances/src/impl_currency.rs
  substrate/frame/benchmarking/src/v1.rs
  substrate/frame/elections-phragmen/src/lib.rs
  substrate/frame/recovery/src/lib.rs
  substrate/frame/support/src/storage/child.rs
  substrate/frame/support/src/storage/unhashed.rs
  substrate/frame/support/src/traits/preimages.rs
Labels: R0-silent, T11-documentation

#7074 release: unset SKIP_WASM_BUILD
  .github/workflows/release-reusable-rc-buid.yml
  prdoc/pr_7074.prdoc
Labels: I2-bug

#7046 adding warning when using default substrateWeight in production
  prdoc/pr_7046.prdoc
  templates/parachain/pallets/template/src/weights.rs
Labels: T1-FRAME

#6855 Snowbridge: Support bridging native ETH
  bridges/snowbridge/pallets/inbound-queue/fixtures/src/lib.rs
  bridges/snowbridge/pallets/inbound-queue/fixtures/src/send_native_eth.rs
  bridges/snowbridge/primitives/router/src/inbound/mock.rs
  bridges/snowbridge/primitives/router/src/inbound/mod.rs
  bridges/snowbridge/primitives/router/src/inbound/tests.rs
  bridges/snowbridge/primitives/router/src/outbound/mod.rs
  bridges/snowbridge/primitives/router/src/outbound/tests.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  prdoc/pr_6855.prdoc
Labels: T15-bridges

#6672 Backport #5887 to v1.14 crates release
  polkadot/runtime/parachains/Cargo.toml
  polkadot/runtime/parachains/src/configuration.rs
  polkadot/runtime/parachains/src/configuration/tests.rs
  prdoc/pr_6672.prdoc
Labels: A3-backport

#7085 Backport 7074 to stable2412
  .github/workflows/release-reusable-rc-buid.yml
  prdoc/pr_7074.prdoc
Labels: R0-silent, A3-backport

#7097 eth-rpc 1017003 runtime upgrade fix
  .github/workflows/build-publish-eth-rpc.yml
  prdoc/pr_7097.prdoc
  substrate/frame/revive/rpc/revive_chain.metadata
Labels: R0-silent

#7048 Migrating salary pallet to use umbrella crate
  Cargo.lock
  prdoc/pr_7048.prdoc
  substrate/frame/salary/Cargo.toml
  substrate/frame/salary/src/benchmarking.rs
  substrate/frame/salary/src/lib.rs
  substrate/frame/salary/src/tests/integration.rs
  substrate/frame/salary/src/tests/unit.rs
  substrate/frame/salary/src/weights.rs
  substrate/frame/src/lib.rs
Labels: T2-pallets

#7056 networking-bench: Update benchmarks payload
  .github/workflows/benchmarks-networking.yml
  substrate/client/network/benches/notifications_protocol.rs
  substrate/client/network/benches/request_response_protocol.rs
Labels: R0-silent, T12-benchmarks

#6820 Add XCM benchmarks to collectives-westend
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/mod.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/xcm_config.rs
  prdoc/pr_6820.prdoc
Labels: T6-XCM

#7113 Switch to parity-large runners to be able to run on the github
  .github/workflows/check-runtime-migration.yml
  .github/workflows/command-update-ui.yml
  .github/workflows/tests-linux-stable.yml
  .github/workflows/tests.yml
Labels: R0-silent

#7118 Fix incorrected deprecated message
  substrate/frame/src/lib.rs
Labels: R0-silent

#7037 reference-docs: Start `state` and mention well known keys
  Cargo.lock
  docs/sdk/Cargo.toml
  docs/sdk/src/reference_docs/mod.rs
  docs/sdk/src/reference_docs/state.rs
  substrate/primitives/storage/src/lib.rs
Labels: R0-silent

#7126 xcm: Fixes for `UnpaidLocalExporter`
  polkadot/xcm/xcm-builder/src/lib.rs
  polkadot/xcm/xcm-builder/src/tests/bridging/local_para_para.rs
  polkadot/xcm/xcm-builder/src/tests/bridging/local_relay_relay.rs
  polkadot/xcm/xcm-builder/src/tests/bridging/mod.rs
  polkadot/xcm/xcm-builder/src/universal_exports.rs
  prdoc/pr_7126.prdoc
Labels: T6-XCM

#6689 [pallet-revive] Update gas encoding
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_6689.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/revive/rpc/examples/js/bun.lockb
  substrate/frame/revive/rpc/examples/js/package.json
  substrate/frame/revive/rpc/examples/js/src/geth-diff.test.ts
  substrate/frame/revive/rpc/examples/js/src/piggy-bank.ts
  substrate/frame/revive/rpc/revive_chain.metadata
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/rpc/src/lib.rs
  substrate/frame/revive/src/evm.rs
  substrate/frame/revive/src/evm/api/byte.rs
  substrate/frame/revive/src/evm/gas_encoder.rs
  substrate/frame/revive/src/evm/runtime.rs
  substrate/frame/revive/src/lib.rs
Labels: R0-silent, T7-smart_contracts

#7130 Switch to parity-large runners to be able to run on the github
  .github/workflows/check-cargo-check-runtimes.yml
  .github/workflows/check-frame-omni-bencher.yml
  .github/workflows/check-runtime-migration.yml
  .github/workflows/checks.yml
  .github/workflows/cmd.yml
  .github/workflows/docs.yml
  .github/workflows/tests-linux-stable.yml
  .github/workflows/tests.yml
Labels: R0-silent

#7116 Increase the number of pvf execute workers
  polkadot/node/service/src/lib.rs
  prdoc/pr_7116.prdoc
Labels: A4-needs-backport

#7102 `fatxpool`: rotator cache size now depends on pool's limits
  prdoc/pr_7102.prdoc
  substrate/client/transaction-pool/benches/basics.rs
  substrate/client/transaction-pool/src/common/tests.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/dropped_watcher.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs
  substrate/client/transaction-pool/src/graph/pool.rs
  substrate/client/transaction-pool/src/graph/rotator.rs
  substrate/client/transaction-pool/src/graph/validated_pool.rs
  substrate/client/transaction-pool/src/single_state_txpool/revalidation.rs
  substrate/client/transaction-pool/src/single_state_txpool/single_state_txpool.rs
  substrate/client/transaction-pool/tests/fatp.rs
  substrate/client/transaction-pool/tests/pool.rs
Labels: R0-silent, T0-node

#4529 Remove usage of the pallet::getter macro from pallet-grandpa
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_4529.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/grandpa/src/benchmarking.rs
  substrate/frame/grandpa/src/equivocation.rs
  substrate/frame/grandpa/src/lib.rs
  substrate/frame/grandpa/src/tests.rs
Labels: T2-pallets

#6475 Backport fix staking benchmark (#6463) to stable 2412 and disable flaky tests
  .gitlab/pipeline/zombienet/polkadot.yml
  prdoc/pr_6475.prdoc
  substrate/frame/staking/src/benchmarking.rs
Labels: A3-backport

#6647 `fatxpool`: proper handling of priorities when mempool is full
  prdoc/pr_6647.prdoc
  substrate/client/transaction-pool/src/fork_aware_txpool/dropped_watcher.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/tx_mem_pool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/view.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs
  substrate/client/transaction-pool/src/graph/base_pool.rs
  substrate/client/transaction-pool/src/graph/listener.rs
  substrate/client/transaction-pool/src/graph/mod.rs
  substrate/client/transaction-pool/src/graph/pool.rs
  substrate/client/transaction-pool/src/graph/ready.rs
  substrate/client/transaction-pool/src/graph/tracked_map.rs
  substrate/client/transaction-pool/src/graph/validated_pool.rs
  substrate/client/transaction-pool/src/single_state_txpool/revalidation.rs
  substrate/client/transaction-pool/src/single_state_txpool/single_state_txpool.rs
  substrate/client/transaction-pool/tests/fatp_common/mod.rs
  substrate/client/transaction-pool/tests/fatp_prios.rs
  substrate/client/transaction-pool/tests/pool.rs
  substrate/test-utils/runtime/transaction-pool/src/lib.rs
Labels: R0-silent, T0-node

#7133 litep2p: Sufix litep2p to the identify agent version for visibility
  prdoc/pr_7133.prdoc
  substrate/client/network/src/litep2p/discovery.rs
Labels: T0-node, I5-enhancement, A4-needs-backport

#6836 [pallet-revive-eth-rpc] persist eth transaction hash
  .cargo/config.toml
  .github/workflows/build-publish-eth-rpc.yml
  Cargo.lock
  prdoc/pr_6836.prdoc
  substrate/frame/revive/rpc/.sqlx/query-027a434a38822c2ba4439e8f9f9c1135227c1150f2c5083d1c7c6086b717ada0.json
  substrate/frame/revive/rpc/.sqlx/query-2348bd412ca114197996e4395fd68c427245f94b80d37ec3aef04cd96fb36298.json
  substrate/frame/revive/rpc/.sqlx/query-29af64347f700919dc2ee12463f332be50096d4e37be04ed8b6f46ac5c242043.json
  substrate/frame/revive/rpc/Cargo.toml
  substrate/frame/revive/rpc/dockerfiles/eth-indexer/Dockerfile
  substrate/frame/revive/rpc/dockerfiles/eth-rpc/Dockerfile
  substrate/frame/revive/rpc/examples/js/bun.lockb
  substrate/frame/revive/rpc/examples/js/package.json
  substrate/frame/revive/rpc/examples/js/src/build-contracts.ts
  substrate/frame/revive/rpc/examples/js/src/geth-diff.test.ts
  substrate/frame/revive/rpc/examples/js/src/lib.ts
  substrate/frame/revive/rpc/examples/js/src/piggy-bank.ts
  substrate/frame/revive/rpc/examples/js/src/spammer.ts
  substrate/frame/revive/rpc/examples/js/src/util.ts
  substrate/frame/revive/rpc/examples/westend_local_network.toml
  substrate/frame/revive/rpc/migrations/20241205165418_create_transaction_hashes.sql
  substrate/frame/revive/rpc/src/block_info_provider.rs
  substrate/frame/revive/rpc/src/cli.rs
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/rpc/src/eth-indexer.rs
  substrate/frame/revive/rpc/src/lib.rs
  substrate/frame/revive/rpc/src/receipt_provider.rs
  substrate/frame/revive/rpc/src/receipt_provider/cache.rs
  substrate/frame/revive/rpc/src/receipt_provider/db.rs
  substrate/frame/revive/rpc/src/rpc_health.rs
  substrate/frame/revive/rpc/src/rpc_methods_gen.rs
  substrate/frame/revive/src/evm/api/rpc_types.rs
  substrate/frame/revive/src/evm/api/rpc_types_gen.rs
  substrate/frame/revive/src/wasm/mod.rs
Labels: R0-silent, T7-smart_contracts

#6807 Retry approval on availability failure if the check is still needed
  polkadot/node/core/approval-voting/src/lib.rs
  polkadot/node/core/approval-voting/src/tests.rs
  polkadot/node/subsystem-bench/src/lib/approval/mod.rs
  prdoc/pr_6807.prdoc
Labels: A4-needs-backport

#6973 approval-voting: Fix sending of assignments after restart
  polkadot/node/core/approval-voting/src/lib.rs
  polkadot/node/core/approval-voting/src/tests.rs
  prdoc/pr_6973.prdoc
Labels: A4-needs-backport

#7139 CI: Only format umbrella crate during umbrella check
  .github/workflows/checks-quick.yml
Labels: R0-silent

#7134 xcm: convert properly assets in xcmpayment apis
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_7134.prdoc
Labels: T6-XCM

#7117 PRDOC: Document `validate: false`
  docs/contributor/prdoc.md
Labels: R0-silent

#6825 Parachains: Use relay chain slot for velocity measurement
  Cargo.lock
  cumulus/client/consensus/aura/src/collators/lookahead.rs
  cumulus/client/consensus/aura/src/collators/mod.rs
  cumulus/client/consensus/aura/src/collators/slot_based/block_builder_task.rs
  cumulus/client/parachain-inherent/src/mock.rs
  cumulus/pallets/aura-ext/Cargo.toml
  cumulus/pallets/aura-ext/src/consensus_hook.rs
  cumulus/pallets/aura-ext/src/lib.rs
  cumulus/pallets/aura-ext/src/migration.rs
  cumulus/pallets/aura-ext/src/test.rs
  cumulus/pallets/parachain-system/src/consensus_hook.rs
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/primitives/aura/src/lib.rs
  cumulus/xcm/xcm-emulator/src/lib.rs
  prdoc/pr_6825.prdoc
Labels: T9-cumulus

#6971 approval-voting: Make importing of duplicate assignment idempotent
  polkadot/node/core/approval-voting/src/approval_checking.rs
  polkadot/node/core/approval-voting/src/lib.rs
  polkadot/node/core/approval-voting/src/persisted_entries.rs
  prdoc/pr_6971.prdoc
Labels: A4-needs-backport

#7170 Fix reversed error message in DispatchInfo
  prdoc/pr_7170.prdoc
  substrate/frame/support/src/dispatch.rs
Labels: T1-FRAME

#7109 Add "run to block" tools
  cumulus/pallets/dmp-queue/src/tests.rs
  polkadot/runtime/common/src/assigned_slots/mod.rs
  polkadot/runtime/common/src/auctions/mock.rs
  polkadot/runtime/common/src/auctions/tests.rs
  polkadot/runtime/common/src/crowdloan/mod.rs
  polkadot/runtime/common/src/integration_tests.rs
  polkadot/runtime/common/src/paras_registrar/mock.rs
  polkadot/runtime/common/src/slots/mod.rs
  prdoc/pr_7109.prdoc
  substrate/frame/examples/multi-block-migrations/src/mock.rs
  substrate/frame/fast-unstake/src/mock.rs
  substrate/frame/identity/src/tests.rs
  substrate/frame/lottery/src/mock.rs
  substrate/frame/lottery/src/tests.rs
  substrate/frame/migrations/src/mock.rs
  substrate/frame/nis/src/mock.rs
  substrate/frame/nis/src/tests.rs
  substrate/frame/nomination-pools/src/mock.rs
  substrate/frame/recovery/src/mock.rs
  substrate/frame/recovery/src/tests.rs
  substrate/frame/root-offences/src/mock.rs
  substrate/frame/scheduler/src/mock.rs
  substrate/frame/scheduler/src/tests.rs
  substrate/frame/society/src/mock.rs
  substrate/frame/society/src/tests.rs
  substrate/frame/src/lib.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/state-trie-migration/src/lib.rs
  substrate/frame/system/src/lib.rs
  substrate/frame/transaction-storage/src/mock.rs
Labels: T1-FRAME

#7158 req-resp/litep2p: Reject inbound requests from banned peers
  prdoc/pr_7158.prdoc
  substrate/client/network/src/litep2p/shim/request_response/mod.rs
Labels: T0-node, I5-enhancement, A4-needs-backport

#6890 Remove 0 as a special case in gas/storage meters
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/governance.rs
  prdoc/pr_6890.prdoc
  substrate/frame/revive/fixtures/contracts/call.rs
  substrate/frame/revive/fixtures/contracts/call_diverging_out_len.rs
  substrate/frame/revive/fixtures/contracts/call_return_code.rs
  substrate/frame/revive/fixtures/contracts/call_runtime_and_call.rs
  substrate/frame/revive/fixtures/contracts/call_with_flags_and_value.rs
  substrate/frame/revive/fixtures/contracts/call_with_limit.rs
  substrate/frame/revive/fixtures/contracts/caller_contract.rs
  substrate/frame/revive/fixtures/contracts/chain_extension_temp_storage.rs
  substrate/frame/revive/fixtures/contracts/create1_with_value.rs
  substrate/frame/revive/fixtures/contracts/create_storage_and_call.rs
  substrate/frame/revive/fixtures/contracts/create_storage_and_instantiate.rs
  substrate/frame/revive/fixtures/contracts/create_transient_storage_and_call.rs
  substrate/frame/revive/fixtures/contracts/delegate_call.rs
  substrate/frame/revive/fixtures/contracts/delegate_call_deposit_limit.rs
  substrate/frame/revive/fixtures/contracts/delegate_call_simple.rs
  substrate/frame/revive/fixtures/contracts/destroy_and_transfer.rs
  substrate/frame/revive/fixtures/contracts/drain.rs
  substrate/frame/revive/fixtures/contracts/instantiate_return_code.rs
  substrate/frame/revive/fixtures/contracts/locking_delegate_dependency.rs
  substrate/frame/revive/fixtures/contracts/origin.rs
  substrate/frame/revive/fixtures/contracts/read_only_call.rs
  substrate/frame/revive/fixtures/contracts/recurse.rs
  substrate/frame/revive/fixtures/contracts/return_data_api.rs
  substrate/frame/revive/fixtures/contracts/self_destruct.rs
  substrate/frame/revive/fixtures/contracts/transfer_return_code.rs
  substrate/frame/revive/fixtures/src/lib.rs
  substrate/frame/revive/rpc/examples/js/pvm/FlipperCaller.polkavm
  substrate/frame/revive/rpc/examples/js/pvm/PiggyBank.polkavm
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/gas.rs
  substrate/frame/revive/src/primitives.rs
  substrate/frame/revive/src/storage/meter.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv64.rs
Labels: T2-pallets, T7-smart_contracts, T10-tests

#7176 [pallet-revive] Bump asset-hub westend spec version
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_7176.prdoc
  substrate/frame/revive/rpc/revive_chain.metadata
Labels: R0-silent, T7-smart_contracts

#7099 litep2p: Provide partial results to speedup GetRecord queries
  Cargo.lock
  Cargo.toml
  prdoc/pr_7099.prdoc
  substrate/client/network/src/litep2p/discovery.rs
  substrate/client/network/src/litep2p/mod.rs
Labels: T0-node, I5-enhancement, A4-needs-backport

#7163 [pallet-revive] Remove debug buffer
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_7163.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/revive/README.md
  substrate/frame/revive/fixtures/contracts/debug_message_invalid_utf8.rs
  substrate/frame/revive/fixtures/contracts/debug_message_logging_disabled.rs
  substrate/frame/revive/fixtures/contracts/debug_message_works.rs
  substrate/frame/revive/proc-macro/src/lib.rs
  substrate/frame/revive/src/benchmarking/call_builder.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/limits.rs
  substrate/frame/revive/src/primitives.rs
  substrate/frame/revive/src/test_utils/builder.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/tests/test_debug.rs
  substrate/frame/revive/src/wasm/mod.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/src/weights.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv64.rs
  substrate/frame/revive/uapi/src/lib.rs
Labels: R0-silent, T7-smart_contracts

#7164 [pallet-revive] Remove revive events
  prdoc/pr_7164.prdoc
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/storage/meter.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/mod.rs
Labels: R0-silent, T7-smart_contracts

#7091 [pallet-revive] Add host function `to_account_id`
  prdoc/pr_7091.prdoc
  substrate/frame/revive/fixtures/contracts/to_account_id.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/src/weights.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv64.rs
Labels: T7-smart_contracts

#3926 Implement `pallet-asset-rewards`
  Cargo.lock
  Cargo.toml
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/common/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/reward_pool.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/reward_pool.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_asset_rewards.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_asset_rewards.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/common/src/lib.rs
  polkadot/runtime/rococo/src/xcm_config.rs
  polkadot/runtime/westend/src/xcm_config.rs
  prdoc/pr_3926.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/asset-rewards/Cargo.toml
  substrate/frame/asset-rewards/src/benchmarking.rs
  substrate/frame/asset-rewards/src/lib.rs
  substrate/frame/asset-rewards/src/mock.rs
  substrate/frame/asset-rewards/src/tests.rs
  substrate/frame/asset-rewards/src/weights.rs
  substrate/frame/support/src/traits.rs
  substrate/frame/support/src/traits/storage.rs
  umbrella/Cargo.toml
  umbrella/src/lib.rs
Labels: T2-pallets

#7193 Update `parity-publish` to v0.10.4
  .github/workflows/check-semver.yml
  .github/workflows/publish-check-compile.yml
  .github/workflows/publish-check-crates.yml
  .github/workflows/publish-claim-crates.yml
Labels: R0-silent

#7178 Migrate substrate zombienet test poc
  .github/workflows/build-publish-images.yml
  .github/workflows/zombienet-reusable-preflight.yml
  .github/workflows/zombienet_substrate.yml
  .github/zombienet-env
Labels: R0-silent, T10-tests, GHA-migration

#6999 chore: fix typos
  bridges/relays/lib-substrate-relay/src/error.rs
  bridges/relays/messages/src/message_lane_loop.rs
  bridges/snowbridge/primitives/core/src/location.rs
Labels: R0-silent

#7187 [stable2412] Fix feature bandersnatch-experimental
  .github/scripts/check-workspace.py
  .github/workflows/checks-quick.yml
  substrate/client/keystore/src/local.rs
  substrate/client/statement-store/README.md
  substrate/primitives/application-crypto/check-features-variants.sh
  substrate/primitives/application-crypto/src/lib.rs
  substrate/primitives/consensus/sassafras/Cargo.toml
  substrate/primitives/core/check-features-variants.sh
  substrate/primitives/core/src/lib.rs
  substrate/primitives/io/src/lib.rs
  substrate/primitives/keyring/check-features-variants.sh
  substrate/primitives/keyring/src/lib.rs
  substrate/primitives/keystore/src/lib.rs
  substrate/primitives/keystore/src/testing.rs
Labels: R0-silent

#7177 Make frame crate not use the feature experimental
  docs/sdk/packages/guides/first-pallet/Cargo.toml
  docs/sdk/packages/guides/first-runtime/Cargo.toml
  polkadot/xcm/docs/Cargo.toml
  prdoc/pr_7177.prdoc
  substrate/frame/atomic-swap/Cargo.toml
  substrate/frame/examples/frame-crate/Cargo.toml
  substrate/frame/mixnet/Cargo.toml
  substrate/frame/multisig/Cargo.toml
  substrate/frame/node-authorization/Cargo.toml
  substrate/frame/proxy/Cargo.toml
  substrate/frame/salary/Cargo.toml
  substrate/frame/src/lib.rs
  substrate/frame/support/test/stg_frame_crate/Cargo.toml
Labels: T1-FRAME

#7203 pallet_revive: Bump PolkaVM
  Cargo.lock
  prdoc/pr_7203.prdoc
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/fixtures/Cargo.toml
  substrate/frame/revive/fixtures/build/_Cargo.toml
  substrate/frame/revive/rpc/examples/js/pvm/Errors.polkavm
  substrate/frame/revive/rpc/examples/js/pvm/EventExample.polkavm
  substrate/frame/revive/rpc/examples/js/pvm/Flipper.polkavm
  substrate/frame/revive/rpc/examples/js/pvm/FlipperCaller.polkavm
  substrate/frame/revive/rpc/examples/js/pvm/PiggyBank.polkavm
  substrate/frame/revive/uapi/Cargo.toml
Labels: T7-smart_contracts

#7214 review-bot upgrade
  .github/workflows/review-bot.yml
Labels: R0-silent

#6995 added new proxy ParaRegistration to Westend
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_6995.prdoc
Labels: T8-polkadot

#7221 enable-deprecation-warning for old command bot
  .github/workflows/command-inform.yml
Labels: R0-silent

#7166 [pallet-revive] Add tracing support (1/3)
  Cargo.lock
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/fixtures/build/_Cargo.toml
  substrate/frame/revive/fixtures/contracts/tracing.rs
  substrate/frame/revive/fixtures/contracts/tracing_callee.rs
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/debug.rs
  substrate/frame/revive/src/evm.rs
  substrate/frame/revive/src/evm/api.rs
  substrate/frame/revive/src/evm/api/byte.rs
  substrate/frame/revive/src/evm/api/debug_rpc_types.rs
  substrate/frame/revive/src/evm/api/hex_serde.rs
  substrate/frame/revive/src/evm/runtime.rs
  substrate/frame/revive/src/evm/tracing.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/tests/test_debug.rs
  substrate/frame/revive/src/tracing.rs
Labels: R0-silent, T7-smart_contracts

#7205 Collator: Fix `can_build_upon` by always allowing to build on included block
  Cargo.lock
  cumulus/client/consensus/aura/Cargo.toml
  cumulus/client/consensus/aura/src/collators/mod.rs
  prdoc/pr_7205.prdoc
Labels: T0-node

#7253 Stabilize `ensure_execute_processes_have_correct_num_threads` test
  polkadot/node/core/pvf/tests/it/process.rs
Labels: R0-silent, T10-tests

#7251 [pallet-revive] eth-rpc error logging
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_7251.prdoc
  substrate/frame/revive/rpc/src/client.rs
Labels: R0-silent, T7-smart_contracts

#7098 Apply a few minor fixes found while addressing the fellows PR for weights.
  bridges/bin/runtime-common/src/integrity.rs
  bridges/modules/messages/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
Labels: R0-silent, T15-bridges

#7081 Migrate pallet-mmr to umbrella crate
  Cargo.lock
  prdoc/pr_7081.prdoc
  substrate/frame/merkle-mountain-range/Cargo.toml
  substrate/frame/merkle-mountain-range/src/benchmarking.rs
  substrate/frame/merkle-mountain-range/src/default_weights.rs
  substrate/frame/merkle-mountain-range/src/lib.rs
  substrate/frame/merkle-mountain-range/src/mmr/mmr.rs
  substrate/frame/merkle-mountain-range/src/mmr/mod.rs
  substrate/frame/merkle-mountain-range/src/mmr/storage.rs
  substrate/frame/merkle-mountain-range/src/mock.rs
  substrate/frame/merkle-mountain-range/src/tests.rs
Labels: R0-silent, T2-pallets

#6599 Migrate `pallet-assets-freezer` to umbrella crate
  Cargo.lock
  substrate/frame/assets-freezer/Cargo.toml
  substrate/frame/assets-freezer/src/impls.rs
  substrate/frame/assets-freezer/src/lib.rs
  substrate/frame/assets-freezer/src/mock.rs
  substrate/frame/assets-freezer/src/tests.rs
  substrate/frame/src/lib.rs
Labels: R0-silent, T1-FRAME

#7263 Fix `frame-benchmarking-cli` not buildable without rocksdb
  polkadot/node/metrics/Cargo.toml
  prdoc/pr_7263.prdoc
  substrate/utils/frame/benchmarking-cli/src/overhead/command.rs
Labels: T0-node

#7260 [eth-indexer] subscribe to finalize blocks instead of best blocks
  prdoc/pr_7260.prdoc
  substrate/frame/revive/rpc/src/client.rs
Labels: R0-silent, T7-smart_contracts

#7206 Add an extra_constant to pallet-collator-selection
  cumulus/pallets/collator-selection/src/lib.rs
  prdoc/pr_7206.prdoc
Labels: T2-pallets

#7108 Snowbridge - Copy Rococo integration tests to Westend
  cumulus/parachains/integration-tests/emulated/chains/parachains/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge.rs
Labels: R0-silent, T10-tests, T15-bridges

#7261 Fix link-checker job
  polkadot/node/gum/proc-macro/src/lib.rs
  substrate/frame/contracts/src/schedule.rs
Labels: R0-silent

#6930 Migrate pallet-paged-list-fuzzer to umbrella crate
  Cargo.lock
  substrate/frame/paged-list/fuzzer/Cargo.toml
  substrate/frame/paged-list/fuzzer/src/paged_list.rs
Labels: R0-silent

#7283 Bump zombienet version to `v1.3.119`
  .gitlab/pipeline/zombienet.yml
Labels: R0-silent, T10-tests

#6856 Enable BEEFY `report_fork_voting()`
  Cargo.lock
  polkadot/runtime/rococo/src/weights/pallet_beefy_mmr.rs
  polkadot/runtime/westend/src/weights/pallet_beefy_mmr.rs
  prdoc/pr_6856.prdoc
  substrate/frame/beefy-mmr/src/benchmarking.rs
  substrate/frame/beefy-mmr/src/lib.rs
  substrate/frame/beefy-mmr/src/weights.rs
  substrate/frame/beefy/src/equivocation.rs
  substrate/frame/beefy/src/lib.rs
  substrate/frame/beefy/src/mock.rs
  substrate/frame/beefy/src/tests.rs
  substrate/frame/merkle-mountain-range/src/lib.rs
  substrate/frame/merkle-mountain-range/src/mmr/mmr.rs
  substrate/frame/merkle-mountain-range/src/mmr/mod.rs
  substrate/frame/merkle-mountain-range/src/tests.rs
  substrate/primitives/consensus/beefy/src/lib.rs
  substrate/primitives/merkle-mountain-range/Cargo.toml
Labels: T15-bridges

#7104 collation-generation: resolve mismatch between descriptor and commitments core index
  polkadot/node/collation-generation/src/lib.rs
  polkadot/node/collation-generation/src/tests.rs
  prdoc/pr_7104.prdoc
Labels: I2-bug, I10-unconfirmed

#7292 Fix bridge tests image
  docker/dockerfiles/bridges_zombienet_tests_injected.Dockerfile
Labels: R0-silent, T10-tests, T15-bridges

#7195 Unify Import verifier usage across parachain template and omninode
  cumulus/client/consensus/aura/src/equivocation_import_queue.rs
  cumulus/polkadot-omni-node/lib/src/nodes/aura.rs
  prdoc/pr_7195.prdoc
Labels: T0-node

#6738 Migrate `pallet-insecure-randomness-collective-flip` to umbrella crate
  Cargo.lock
  substrate/frame/insecure-randomness-collective-flip/Cargo.toml
  substrate/frame/insecure-randomness-collective-flip/src/lib.rs
Labels: R0-silent, T1-FRAME

#7281 [pallet-revive] fee estimation fixes
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_7281.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/revive/rpc/examples/js/src/build-contracts.ts
  substrate/frame/revive/rpc/examples/js/src/geth-diff.test.ts
  substrate/frame/revive/rpc/examples/js/src/util.ts
  substrate/frame/revive/rpc/revive_chain.metadata
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/evm/gas_encoder.rs
  substrate/frame/revive/src/evm/runtime.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/primitives.rs
Labels: R0-silent, T7-smart_contracts

#7252 bump lookahead to 3 for testnet genesis
  polkadot/runtime/rococo/src/genesis_config_presets.rs
  polkadot/runtime/westend/src/genesis_config_presets.rs
  polkadot/zombienet-sdk-tests/tests/elastic_scaling/doesnt_break_parachains.rs
Labels: R0-silent, T10-tests

#7231 Refactor command bot and drop rejecting non paritytech members
  .github/workflows/cmd.yml
Labels: R0-silent

#7315 Fix setting the image properly
  .github/workflows/cmd.yml
Labels: R0-silent

#7201 xcm: avoid subtracting delivery fees twice
  polkadot/xcm/xcm-executor/src/lib.rs
  prdoc/pr_7201.prdoc
Labels: T6-XCM

#6789 bench all weekly - and fix for pallet_multisig lib
  .github/workflows/bench-all-runtimes.yml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_multisig.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_multisig.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_multisig.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_multisig.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_multisig.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_multisig.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/pallet_multisig.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/pallet_multisig.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/pallet_multisig.rs
  polkadot/runtime/rococo/src/weights/pallet_multisig.rs
  polkadot/runtime/westend/src/weights/pallet_multisig.rs
  substrate/.maintain/frame-weight-template.hbs
  substrate/frame/multisig/src/benchmarking.rs
  substrate/frame/multisig/src/weights.rs
Labels: R0-silent

#7298 [stable2412] Partial backport of #6825 and #7205
  Cargo.lock
  cumulus/client/consensus/aura/Cargo.toml
  cumulus/client/consensus/aura/src/collators/lookahead.rs
  cumulus/client/consensus/aura/src/collators/mod.rs
  cumulus/client/consensus/aura/src/collators/slot_based/block_builder_task.rs
  cumulus/client/parachain-inherent/src/mock.rs
  cumulus/xcm/xcm-emulator/src/lib.rs
  prdoc/pr_6825.prdoc
  prdoc/pr_7205.prdoc
Labels: T0-node

#7215 Nits for collectives-westend XCM benchmarks setup
  Cargo.lock
  cumulus/parachains/runtimes/collectives/collectives-westend/Cargo.toml
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
Labels: R0-silent, T6-XCM, T12-benchmarks

#7299 fix(cmd bench-omni): build omni-bencher with production profile
  .github/workflows/cmd.yml
Labels: R0-silent

#7227 sync-templates: enable syncing from stable release patches
  .github/workflows/misc-sync-templates.yml
Labels: R0-silent

#7325 [pallet-revive] eth-rpc minor fixes
  Cargo.lock
  prdoc/pr_7325.prdoc
  substrate/frame/revive/rpc/Cargo.toml
  substrate/frame/revive/rpc/examples/README.md
  substrate/frame/revive/rpc/src/cli.rs
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/rpc/src/eth-indexer.rs
  substrate/frame/revive/rpc/src/eth-rpc-tester.rs
  substrate/frame/revive/rpc/src/example.rs
  substrate/frame/revive/rpc/src/lib.rs
Labels: R0-silent, T7-smart_contracts

#7318 revive: Fix compilation of `uapi` crate when `unstable-hostfn` is not set
  .github/workflows/build-misc.yml
  prdoc/pr_7318.prdoc
  substrate/frame/revive/uapi/src/host.rs
Labels: T7-smart_contracts

#7330 Fix the link to the chain snapshots
  substrate/utils/frame/benchmarking-cli/src/storage/README.md
Labels: R0-silent

#7327 `set_validation_data` register weight manually, do not use refund when the pre dispatch is zero.
  cumulus/pallets/parachain-system/src/lib.rs
  prdoc/pr_7327.prdoc
Labels: T2-pallets

#7142 Improve debugging by using `#[track_caller]` in system `assert_last_event` and `assert_has_event`
  substrate/frame/system/src/lib.rs
Labels: R0-silent, T1-FRAME

#7329 Removed unused dependencies (partial progress)
  Cargo.lock
  Cargo.toml
  bridges/relays/utils/Cargo.toml
  bridges/snowbridge/pallets/ethereum-client/Cargo.toml
  bridges/snowbridge/pallets/outbound-queue/Cargo.toml
  bridges/snowbridge/pallets/system/Cargo.toml
  bridges/snowbridge/primitives/ethereum/Cargo.toml
  cumulus/client/network/Cargo.toml
  cumulus/client/pov-recovery/Cargo.toml
  cumulus/client/relay-chain-inprocess-interface/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/test-utils/Cargo.toml
  cumulus/polkadot-parachain/Cargo.toml
  cumulus/test/runtime/Cargo.toml
  cumulus/test/service/Cargo.toml
  cumulus/xcm/xcm-emulator/Cargo.toml
  polkadot/node/metrics/Cargo.toml
  polkadot/node/test/service/Cargo.toml
  polkadot/parachain/test-parachains/adder/collator/Cargo.toml
  polkadot/parachain/test-parachains/undying/collator/Cargo.toml
  polkadot/runtime/parachains/Cargo.toml
  polkadot/runtime/rococo/Cargo.toml
  polkadot/runtime/test-runtime/Cargo.toml
  polkadot/runtime/westend/Cargo.toml
  polkadot/xcm/xcm-builder/Cargo.toml
  substrate/bin/node/cli/Cargo.toml
  substrate/client/api/Cargo.toml
  substrate/client/db/Cargo.toml
  substrate/client/network/common/Cargo.toml
  substrate/client/telemetry/Cargo.toml
  substrate/frame/contracts/Cargo.toml
  substrate/frame/contracts/mock-network/Cargo.toml
  substrate/frame/conviction-voting/Cargo.toml
  substrate/frame/delegated-staking/Cargo.toml
  substrate/frame/fast-unstake/Cargo.toml
  substrate/frame/glutton/Cargo.toml
  substrate/frame/indices/Cargo.toml
  substrate/frame/nfts/runtime-api/Cargo.toml
  substrate/frame/offences/Cargo.toml
  substrate/frame/paged-list/Cargo.toml
  substrate/frame/verify-signature/Cargo.toml
  substrate/test-utils/Cargo.toml
  substrate/test-utils/client/Cargo.toml
Labels: R0-silent

#7344 [sync] Let new subscribers know about already connected peers (backward-compatible)
  prdoc/pr_7344.prdoc
  substrate/client/network-gossip/src/bridge.rs
  substrate/client/network-gossip/src/lib.rs
  substrate/client/network/statement/src/lib.rs
  substrate/client/network/sync/src/engine.rs
  substrate/client/network/sync/src/types.rs
  substrate/client/network/transactions/src/lib.rs
Labels: T0-node, A4-needs-backport

#7042 `Arc` definition in `TransactionPool`
  prdoc/pr_7042.prdoc
  substrate/client/network/transactions/src/config.rs
  substrate/client/network/transactions/src/lib.rs
  substrate/client/service/src/lib.rs
Labels: R0-silent, T0-node

#6529 Add development chain-spec file for minimal/parachain templates for Omni Node compatibility
  .github/workflows/misc-sync-templates.yml
  templates/minimal/README.md
  templates/minimal/dev_chain_spec.json
  templates/minimal/zombienet-omni-node.toml
  templates/parachain/README.docify.md
  templates/parachain/README.md
  templates/parachain/dev_chain_spec.json
  templates/parachain/zombienet-omni-node.toml
Labels: R0-silent, T11-documentation, T17-Templates

#7169 xcm: fix for DenyThenTry Barrier
  Cargo.lock
  cumulus/parachains/runtimes/bridge-hubs/common/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/common/src/barriers.rs
  cumulus/parachains/runtimes/bridge-hubs/common/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/common/tests/tests.rs
  polkadot/xcm/xcm-builder/src/barriers.rs
  polkadot/xcm/xcm-builder/src/tests/barriers.rs
  polkadot/xcm/xcm-builder/src/tests/mock.rs
  polkadot/xcm/xcm-executor/src/traits/mod.rs
  polkadot/xcm/xcm-executor/src/traits/should_execute.rs
  prdoc/pr_7169.prdoc
Labels: T6-XCM

#6983 cumulus: bump PARENT_SEARCH_DEPTH and add test for 12-core elastic scaling
  .gitlab/pipeline/zombienet/polkadot.yml
  cumulus/client/consensus/aura/src/collators/mod.rs
  cumulus/test/runtime/Cargo.toml
  cumulus/test/runtime/build.rs
  cumulus/test/runtime/src/lib.rs
  cumulus/test/service/src/chain_spec.rs
  cumulus/test/service/src/cli.rs
  polkadot/zombienet-sdk-tests/tests/elastic_scaling/mod.rs
  polkadot/zombienet-sdk-tests/tests/elastic_scaling/slot_based_12cores.rs
  prdoc/pr_6983.prdoc
Labels: T9-cumulus

#7319 [pallet-revive] pack exceeding syscall arguments into registers
  prdoc/pr_7319.prdoc
  substrate/frame/revive/fixtures/contracts/call_diverging_out_len.rs
  substrate/frame/revive/fixtures/contracts/caller_contract.rs
  substrate/frame/revive/fixtures/contracts/create1_with_value.rs
  substrate/frame/revive/fixtures/contracts/create_storage_and_instantiate.rs
  substrate/frame/revive/fixtures/contracts/destroy_and_transfer.rs
  substrate/frame/revive/fixtures/contracts/instantiate_return_code.rs
  substrate/frame/revive/fixtures/contracts/return_data_api.rs
  substrate/frame/revive/proc-macro/src/lib.rs
  substrate/frame/revive/rpc/examples/js/pvm/FlipperCaller.polkavm
  substrate/frame/revive/rpc/examples/js/pvm/PiggyBank.polkavm
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/src/weights.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv64.rs
  substrate/frame/revive/uapi/src/lib.rs
Labels: R0-silent, T7-smart_contracts

#4722 Implement pallet view function queries
  .github/workflows/check-semver.yml
  Cargo.lock
  Cargo.toml
  cumulus/pallets/weight-reclaim/src/tests.rs
  docs/sdk/src/reference_docs/chain_spec_runtime/src/runtime.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_4722.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/examples/Cargo.toml
  substrate/frame/examples/src/lib.rs
  substrate/frame/examples/view-functions/Cargo.toml
  substrate/frame/examples/view-functions/src/lib.rs
  substrate/frame/examples/view-functions/src/tests.rs
  substrate/frame/support/procedural/examples/proc_main/main.rs
  substrate/frame/support/procedural/examples/proc_main/runtime.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/call.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/config.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/inherent.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/metadata.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/mod.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/origin.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/outer_enums.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/task.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/unsigned.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/view_function.rs
  substrate/frame/support/procedural/src/construct_runtime/mod.rs
  substrate/frame/support/procedural/src/construct_runtime/parse.rs
  substrate/frame/support/procedural/src/lib.rs
  substrate/frame/support/procedural/src/pallet/expand/mod.rs
  substrate/frame/support/procedural/src/pallet/expand/view_functions.rs
  substrate/frame/support/procedural/src/pallet/parse/mod.rs
  substrate/frame/support/procedural/src/pallet/parse/view_functions.rs
  substrate/frame/support/procedural/src/runtime/expand/mod.rs
  substrate/frame/support/procedural/src/runtime/parse/runtime_types.rs
  substrate/frame/support/src/lib.rs
  substrate/frame/support/src/tests/mod.rs
  substrate/frame/support/src/view_functions.rs
  substrate/frame/support/test/tests/construct_runtime_ui/deprecated_where_block.stderr
  substrate/frame/support/test/tests/derive_impl_ui/inject_runtime_type_invalid.stderr
  substrate/frame/support/test/tests/pallet.rs
  substrate/frame/support/test/tests/runtime.rs
  substrate/frame/support/test/tests/runtime_legacy_ordering.rs
  substrate/frame/support/test/tests/runtime_ui/invalid_runtime_type_derive.stderr
  substrate/frame/support/test/tests/runtime_ui/pass/basic.rs
  substrate/primitives/metadata-ir/src/lib.rs
  substrate/primitives/metadata-ir/src/types.rs
  substrate/primitives/metadata-ir/src/v15.rs
  templates/minimal/runtime/src/lib.rs
  templates/parachain/pallets/template/src/mock.rs
  templates/parachain/runtime/src/apis.rs
  templates/parachain/runtime/src/lib.rs
  templates/solochain/pallets/template/src/mock.rs
  templates/solochain/runtime/src/apis.rs
  templates/solochain/runtime/src/lib.rs
Labels: T1-FRAME, T4-runtime_API

#7359 Improve `set_validation_data` error message.
  cumulus/pallets/parachain-system/src/lib.rs
  prdoc/pr_7359.prdoc
Labels: T9-cumulus

#7366 ci: fix workflow permissions
  .github/workflows/check-runtime-migration.yml
Labels: R0-silent

#7362 remove old bench & revert the frame-weight-template
  .github/scripts/cmd/cmd.py
  .github/workflows/runtimes-matrix.json
  substrate/.maintain/frame-weight-template.hbs
  substrate/frame/multisig/src/weights.rs
Labels: R0-silent

#7372 move installation of frame-omni-bencher into a cmd.py itself
  .github/scripts/cmd/cmd.py
  .github/workflows/cmd.yml
Labels: R0-silent

#7365 Use checked math in frame-balances named_reserve
  prdoc/pr_7365.prdoc
  substrate/frame/balances/src/impl_currency.rs
Labels: T2-pallets, A4-needs-backport

#7198 [pallet-revive] implement the block author API
  Cargo.lock
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_7198.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/fixtures/contracts/block_author.rs
  substrate/frame/revive/fixtures/contracts/create_transient_storage_and_call.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/limits.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/src/weights.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv64.rs
Labels: R0-silent, T7-smart_contracts

#6564 Migrating cumulus-pallet-session-benchmarking to Benchmarking V2
  cumulus/pallets/session-benchmarking/src/inner.rs
Labels: R0-silent, T2-pallets, T12-benchmarks

#7383 Bridges small nits/improvements
  Cargo.lock
  bridges/modules/xcm-bridge-hub/src/lib.rs
  cumulus/pallets/xcmp-queue/src/bridging.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/test-utils/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/from_grandpa_chain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/from_parachain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/helpers.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_data/from_grandpa_chain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_data/from_parachain.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_data/mod.rs
  prdoc/pr_7383.prdoc
Labels: T15-bridges, A4-needs-backport

#7296 Fix Snowbridge benchmark tests
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
Labels: R0-silent, T10-tests

#7379 Add support for feature `pallet_balances/insecure_zero_ed` in benchmarks and testing
  prdoc/pr_7379.prdoc
  substrate/frame/balances/src/benchmarking.rs
  substrate/frame/balances/src/tests/currency_tests.rs
Labels: T2-pallets, T10-tests

#7324 Replace derivative dependency with derive-where
  Cargo.lock
  Cargo.toml
  cumulus/pallets/weight-reclaim/Cargo.toml
  cumulus/pallets/weight-reclaim/src/lib.rs
  polkadot/xcm/Cargo.toml
  polkadot/xcm/src/lib.rs
  polkadot/xcm/src/v3/mod.rs
  polkadot/xcm/src/v4/mod.rs
  polkadot/xcm/src/v5/mod.rs
  prdoc/pr_7324.prdoc
Labels: R0-silent

#7390 Improvements for Weekly bench
  .github/workflows/bench-all-runtimes.yml
Labels: R0-silent

#6897 `fatxpool`: use tracing for logging
  Cargo.lock
  prdoc/pr_6897.prdoc
  substrate/client/transaction-pool/Cargo.toml
  substrate/client/transaction-pool/src/common/mod.rs
  substrate/client/transaction-pool/src/common/tracing_log_xt.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/dropped_watcher.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/import_notification_sink.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/multi_view_listener.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/revalidation_worker.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/tx_mem_pool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/view.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs
  substrate/client/transaction-pool/src/graph/future.rs
  substrate/client/transaction-pool/src/graph/pool.rs
  substrate/client/transaction-pool/src/graph/validated_pool.rs
Labels: R0-silent, T0-node

#6924 malus-collator: implement malicious collator submitting same collation to all backing groups
  .gitlab/pipeline/zombienet/polkadot.yml
  Cargo.lock
  polkadot/node/test/service/src/chain_spec.rs
  polkadot/parachain/test-parachains/undying/Cargo.toml
  polkadot/parachain/test-parachains/undying/collator/Cargo.toml
  polkadot/parachain/test-parachains/undying/collator/src/cli.rs
  polkadot/parachain/test-parachains/undying/collator/src/lib.rs
  polkadot/parachain/test-parachains/undying/collator/src/main.rs
  polkadot/parachain/test-parachains/undying/collator/tests/integration.rs
  polkadot/parachain/test-parachains/undying/src/lib.rs
  polkadot/parachain/test-parachains/undying/src/wasm_validation.rs
  polkadot/zombienet-sdk-tests/tests/functional/duplicate_collations.rs
  polkadot/zombienet-sdk-tests/tests/functional/mod.rs
  polkadot/zombienet_tests/misc/0002-upgrade-node.toml
  prdoc/pr_6924.prdoc
Labels: T10-tests

#7378 fix pre-dispatch PoV underweight for ParasInherent
  polkadot/runtime/parachains/src/paras_inherent/weights.rs
  prdoc/pr_7378.prdoc
Labels: T8-polkadot

#7401 [Backport] Version bumps from stable2412-1 + prdocs reorg
  polkadot/node/primitives/src/lib.rs
  prdoc/stable2412-1/pr_6463.prdoc
  prdoc/stable2412-1/pr_6807.prdoc
  prdoc/stable2412-1/pr_6825.prdoc
  prdoc/stable2412-1/pr_6855.prdoc
  prdoc/stable2412-1/pr_6971.prdoc
  prdoc/stable2412-1/pr_6973.prdoc
  prdoc/stable2412-1/pr_7013.prdoc
  prdoc/stable2412-1/pr_7028.prdoc
  prdoc/stable2412-1/pr_7050.prdoc
  prdoc/stable2412-1/pr_7067.prdoc
  prdoc/stable2412-1/pr_7074.prdoc
  prdoc/stable2412-1/pr_7090.prdoc
  prdoc/stable2412-1/pr_7099.prdoc
  prdoc/stable2412-1/pr_7116.prdoc
  prdoc/stable2412-1/pr_7133.prdoc
  prdoc/stable2412-1/pr_7158.prdoc
  prdoc/stable2412-1/pr_7205.prdoc
  prdoc/stable2412-1/pr_7222.prdoc
  prdoc/stable2412-1/pr_7322.prdoc
  prdoc/stable2412-1/pr_7344.prdoc
Labels: R0-silent, A3-backport, D0-easy

#7351 poc(XCM): Deny Nested XCM Barriers
  polkadot/xcm/xcm-builder/src/barriers.rs
  polkadot/xcm/xcm-builder/src/lib.rs
  polkadot/xcm/xcm-builder/src/tests/barriers.rs
  polkadot/xcm/xcm-builder/src/tests/mock.rs
Labels: T6-XCM, C1-mentor, C2-good-first-issue

#7416 Remove warnings by cleaning up the `Cargo.toml`
  substrate/frame/examples/view-functions/Cargo.toml
Labels: R0-silent
