Repository paritytech/polkadot-sdk, pull requests merged in 2025-04, with the labels that each got.

#7986 runtime: assume elastic scaling MVP is always enabled
  polkadot/node/core/backing/src/lib.rs
  polkadot/node/core/backing/src/tests/mod.rs
  polkadot/node/core/provisioner/src/tests.rs
  polkadot/primitives/src/v8/mod.rs
  polkadot/primitives/src/vstaging/mod.rs
  polkadot/runtime/parachains/src/builder.rs
  polkadot/runtime/parachains/src/inclusion/mod.rs
  polkadot/runtime/parachains/src/inclusion/tests.rs
  polkadot/runtime/parachains/src/paras_inherent/mod.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
  prdoc/pr_7986.prdoc
Labels: T8-polkadot

#8109 rpc v2 archive: more verbose error types in API
  prdoc/pr_8109.prdoc
  substrate/client/rpc-spec-v2/src/archive/api.rs
  substrate/client/rpc-spec-v2/src/archive/archive.rs
  substrate/client/rpc-spec-v2/src/archive/error.rs
Labels: T3-RPC_API

#7669 Introduce ark-vrf
  .config/zepter.yaml
  Cargo.lock
  Cargo.toml
  prdoc/pr_7669.prdoc
  substrate/client/keystore/Cargo.toml
  substrate/frame/sassafras/Cargo.toml
  substrate/frame/sassafras/src/data/25_tickets_100_auths.bin
  substrate/frame/sassafras/src/lib.rs
  substrate/frame/sassafras/src/mock.rs
  substrate/frame/sassafras/src/tests.rs
  substrate/primitives/consensus/sassafras/Cargo.toml
  substrate/primitives/consensus/sassafras/src/vrf.rs
  substrate/primitives/core/Cargo.toml
  substrate/primitives/core/src/bandersnatch.rs
  substrate/primitives/io/Cargo.toml
  substrate/primitives/keyring/src/bandersnatch.rs
  substrate/primitives/keystore/src/testing.rs
Labels: T2-pallets

#8023 pallet-revive-fixtures: Support relative path for `CARGO_TARGET_DIR`
  substrate/frame/revive/fixtures/build.rs
Labels: R0-silent

#8105 Add chat channels to README
  README.md
Labels: R0-silent

#8011 `pallet-xmcp-queue`: Fix broken and ignored test
  cumulus/pallets/xcmp-queue/src/tests.rs
Labels: R0-silent

#8140 Add missing prdocs
  prdoc/pr_7598.prdoc
  prdoc/pr_7620.prdoc
  prdoc/pr_7627.prdoc
Labels: R0-silent, T11-documentation

#8143 Improve documentation around development environment configuration
  docs/sdk/src/reference_docs/development_environment_advice.rs
Labels: A1-insubstantial, R0-silent, T11-documentation

#8138 Bridges: Add missing initial primitives for AssetHub bridging
  Cargo.lock
  bridges/chains/chain-asset-hub-rococo/Cargo.toml
  bridges/chains/chain-asset-hub-rococo/src/lib.rs
  bridges/chains/chain-asset-hub-westend/Cargo.toml
  bridges/chains/chain-asset-hub-westend/src/lib.rs
Labels: R0-silent, T15-bridges

#8137 Preserve Original Message ID as Topic When Absent During XCM Send
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  cumulus/xcm/xcm-emulator/src/lib.rs
  polkadot/xcm/xcm-executor/src/lib.rs
Labels: T6-XCM

#8153 Introduce `SelectCore` digest in Cumulus
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/primitives/core/src/lib.rs
  polkadot/primitives/src/vstaging/mod.rs
  prdoc/pr_8153.prdoc
Labels: T9-cumulus

#8134 refactor: separate validation and collation protocols
  polkadot/node/core/approval-voting-parallel/src/lib.rs
  polkadot/node/core/approval-voting-parallel/src/tests.rs
  polkadot/node/network/approval-distribution/src/lib.rs
  polkadot/node/network/approval-distribution/src/tests.rs
  polkadot/node/network/bitfield-distribution/src/lib.rs
  polkadot/node/network/bridge/src/rx/tests.rs
  polkadot/node/network/bridge/src/tx/mod.rs
  polkadot/node/network/bridge/src/tx/tests.rs
  polkadot/node/network/collator-protocol/src/collator_side/mod.rs
  polkadot/node/network/collator-protocol/src/collator_side/tests/mod.rs
  polkadot/node/network/collator-protocol/src/collator_side/tests/prospective_parachains.rs
  polkadot/node/network/collator-protocol/src/validator_side/mod.rs
  polkadot/node/network/collator-protocol/src/validator_side/tests/mod.rs
  polkadot/node/network/collator-protocol/src/validator_side/tests/prospective_parachains.rs
  polkadot/node/network/gossip-support/src/lib.rs
  polkadot/node/network/protocol/src/lib.rs
  polkadot/node/network/protocol/src/request_response/mod.rs
  polkadot/node/network/protocol/src/request_response/outgoing.rs
  polkadot/node/network/protocol/src/request_response/v1.rs
  polkadot/node/network/protocol/src/request_response/v2.rs
  polkadot/node/network/statement-distribution/src/v2/grid.rs
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  polkadot/node/network/statement-distribution/src/v2/requests.rs
  polkadot/node/network/statement-distribution/src/v2/statement_store.rs
  polkadot/node/network/statement-distribution/src/v2/tests/cluster.rs
  polkadot/node/network/statement-distribution/src/v2/tests/grid.rs
  polkadot/node/network/statement-distribution/src/v2/tests/mod.rs
  polkadot/node/network/statement-distribution/src/v2/tests/requests.rs
  polkadot/node/subsystem-bench/src/lib/availability/test_state.rs
  polkadot/node/subsystem-bench/src/lib/mock/network_bridge.rs
  polkadot/node/subsystem-bench/src/lib/network.rs
  polkadot/node/subsystem-bench/src/lib/statement/mod.rs
  polkadot/node/subsystem-bench/src/lib/statement/test_state.rs
  prdoc/pr_8134.prdoc
Labels: T8-polkadot

#8136 Ban bandersnatch git dependency
  .github/scripts/check-workspace.py
  .github/scripts/deny-git-deps.py
  .github/scripts/generate-prdoc.py
  Cargo.lock
  Cargo.toml
  docs/sdk/Cargo.toml
  polkadot/xcm/docs/Cargo.toml
  substrate/primitives/runtime/Cargo.toml
Labels: A1-insubstantial, R0-silent

#8083 `xcm-emulator` improved callback triggering (`on_initialize`, `on_finalize`, `on_idle`, `OnSystemEvent`).
  Cargo.lock
  cumulus/xcm/xcm-emulator/Cargo.toml
  cumulus/xcm/xcm-emulator/src/lib.rs
  prdoc/pr_8083.prdoc
Labels: T6-XCM, T10-tests

#8130 rpc v2: move `archive MethodResult` to the archive mod
  prdoc/pr_8130.prdoc
  substrate/client/rpc-spec-v2/src/archive/api.rs
  substrate/client/rpc-spec-v2/src/archive/archive.rs
  substrate/client/rpc-spec-v2/src/archive/mod.rs
  substrate/client/rpc-spec-v2/src/archive/tests.rs
  substrate/client/rpc-spec-v2/src/archive/types.rs
  substrate/client/rpc-spec-v2/src/lib.rs
Labels: T0-node

#8173 expose current advertised xcm version
  polkadot/xcm/pallet-xcm/src/lib.rs
  prdoc/pr_8173.prdoc
Labels: T6-XCM, T2-pallets

#7867 benchmark: storage: Make read/write benchmarks more accurate
  cumulus/polkadot-omni-node/lib/src/common/command.rs
  cumulus/polkadot-omni-node/lib/src/tests/benchmark_storage_works.rs
  polkadot/cli/src/command.rs
  polkadot/tests/benchmark_storage_works.rs
  prdoc/pr_7867.prdoc
  substrate/bin/node/cli/src/command.rs
  substrate/bin/node/cli/tests/benchmark_storage_works.rs
  substrate/client/db/src/lib.rs
  substrate/utils/frame/benchmarking-cli/src/storage/cmd.rs
  substrate/utils/frame/benchmarking-cli/src/storage/read.rs
  substrate/utils/frame/benchmarking-cli/src/storage/write.rs
  templates/parachain/node/src/command.rs
  templates/solochain/node/src/command.rs
Labels: T12-benchmarks

#8122 Update to frame-metadata 21.0
  Cargo.lock
  Cargo.toml
  prdoc/pr_8122.prdoc
  substrate/primitives/metadata-ir/src/unstable.rs
Labels: R0-silent, T4-runtime_API

#8180 Add a full changelog as a file
  prdoc/stable2503/CHANGELOG.md
Labels: R0-silent

#8163 chore: idiomatic rust cleanup
  bridges/snowbridge/primitives/merkle-tree/src/lib.rs
  prdoc/pr_8163.prdoc
  substrate/bin/node/runtime/src/genesis_config_presets.rs
  substrate/frame/democracy/src/lib.rs
  substrate/frame/revive/src/evm/api/rlp_codec.rs
  substrate/frame/tips/src/lib.rs
Labels: T2-pallets

#8144 collator protocol revamp: add new empty collator protocol subsystem for validator side
  polkadot/node/network/collator-protocol/Cargo.toml
  polkadot/node/network/collator-protocol/src/collator_side/error.rs
  polkadot/node/network/collator-protocol/src/collator_side/mod.rs
  polkadot/node/network/collator-protocol/src/lib.rs
  polkadot/node/network/collator-protocol/src/validator_side/collation.rs
  polkadot/node/network/collator-protocol/src/validator_side/error.rs
  polkadot/node/network/collator-protocol/src/validator_side/mod.rs
  polkadot/node/network/collator-protocol/src/validator_side_experimental/metrics.rs
  polkadot/node/network/collator-protocol/src/validator_side_experimental/mod.rs
Labels: R0-silent, T8-polkadot

#8193 ci: mark build jobs as required
  .github/workflows/build-publish-images.yml
Labels: R0-silent

#8198 Remove `#[no_mangle]` from the panic handler
  prdoc/pr_8198.prdoc
  substrate/primitives/io/src/lib.rs
Labels: R0-silent, A4-backport-stable2407, A4-backport-stable2409, A4-backport-stable2412, A4-backport-stable2503

#6137 cumulus: `ParachainBlockData` support multiple blocks
  .github/workflows/zombienet-reusable-preflight.yml
  Cargo.lock
  cumulus/client/collator/src/lib.rs
  cumulus/client/collator/src/service.rs
  cumulus/client/consensus/aura/src/collator.rs
  cumulus/client/consensus/aura/src/collators/basic.rs
  cumulus/client/consensus/aura/src/collators/lookahead.rs
  cumulus/client/consensus/aura/src/collators/slot_based/collation_task.rs
  cumulus/client/pov-recovery/src/lib.rs
  cumulus/client/pov-recovery/src/tests.rs
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/parachain-system/src/validate_block/implementation.rs
  cumulus/pallets/parachain-system/src/validate_block/tests.rs
  cumulus/pallets/parachain-system/src/validate_block/trie_cache.rs
  cumulus/pallets/parachain-system/src/validate_block/trie_recorder.rs
  cumulus/primitives/core/Cargo.toml
  cumulus/primitives/core/src/lib.rs
  cumulus/primitives/core/src/parachain_block_data.rs
  cumulus/test/client/src/block_builder.rs
  cumulus/test/client/src/lib.rs
  cumulus/test/runtime/build.rs
  cumulus/test/service/benches/validate_block.rs
  cumulus/test/service/benches/validate_block_glutton.rs
  cumulus/zombienet/tests/0002-pov_recovery.zndsl
  cumulus/zombienet/tests/0009-elastic_pov_recovery.zndsl
  polkadot/node/collation-generation/src/lib.rs
  polkadot/node/core/candidate-validation/src/lib.rs
  polkadot/primitives/src/vstaging/mod.rs
  prdoc/pr_6137.prdoc
Labels: T9-cumulus

#8208 Omni Node: Enable OCW http
  cumulus/polkadot-omni-node/lib/src/common/spec.rs
  prdoc/pr_8208.prdoc
Labels: T0-node

#8210 [xcm-builder][origin_conversion] LocationAsSuperuser converter introduced
  polkadot/xcm/xcm-builder/src/lib.rs
  polkadot/xcm/xcm-builder/src/origin_conversion.rs
  prdoc/pr_8210.prdoc
Labels: T6-XCM, A4-backport-stable2412, A4-backport-stable2503

#8038 Snowbridge - Fix penpal runtime and more tests transfer PNA
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
  cumulus/polkadot-parachain/src/chain_spec/penpal.rs
  prdoc/pr_8038.prdoc
Labels: R0-silent

#8211 [CI/CD] Fix polkadot, polkadot-parachain and general bin docker images
  .github/workflows/release-50_publish-docker.yml
  .github/workflows/release-reusable-rc-buid.yml
  docker/dockerfiles/binary_injected.Dockerfile
  docker/dockerfiles/polkadot-parachain/polkadot-parachain_injected.Dockerfile
  docker/dockerfiles/polkadot/polkadot_builder.Dockerfile
  docker/dockerfiles/polkadot/polkadot_injected.Dockerfile
  docker/dockerfiles/polkadot/polkadot_injected_debian.Dockerfile
  docs/RELEASE.md
Labels: R0-silent, A4-backport-stable2503

#7955 impl ApprovedPeer UMP signal
  .gitlab/pipeline/zombienet/polkadot.yml
  Cargo.lock
  cumulus/pallets/parachain-system/src/validate_block/implementation.rs
  polkadot/node/collation-generation/src/lib.rs
  polkadot/node/collation-generation/src/tests.rs
  polkadot/node/core/candidate-validation/src/lib.rs
  polkadot/node/core/candidate-validation/src/tests.rs
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  polkadot/node/network/statement-distribution/src/v2/requests.rs
  polkadot/node/network/statement-distribution/src/v2/tests/requests.rs
  polkadot/node/primitives/src/lib.rs
  polkadot/parachain/test-parachains/undying/collator/src/cli.rs
  polkadot/parachain/test-parachains/undying/collator/src/lib.rs
  polkadot/parachain/test-parachains/undying/collator/src/main.rs
  polkadot/parachain/test-parachains/undying/collator/tests/integration.rs
  polkadot/parachain/test-parachains/undying/src/lib.rs
  polkadot/primitives/Cargo.toml
  polkadot/primitives/src/vstaging/mod.rs
  polkadot/runtime/parachains/src/builder.rs
  polkadot/runtime/parachains/src/paras_inherent/mod.rs
  polkadot/runtime/parachains/src/paras_inherent/tests.rs
  polkadot/zombienet-sdk-tests/tests/functional/approved_peer_mixed_validators.rs
  polkadot/zombienet-sdk-tests/tests/functional/duplicate_collations.rs
  polkadot/zombienet-sdk-tests/tests/functional/mod.rs
  prdoc/pr_7955.prdoc
Labels: T8-polkadot

#8162 tx/broadcast: Use client info for fetching the best block
  prdoc/pr_8162.prdoc
  substrate/client/rpc-spec-v2/src/transaction/tests/transaction_broadcast_tests.rs
  substrate/client/rpc-spec-v2/src/transaction/transaction_broadcast.rs
Labels: T3-RPC_API, A4-needs-backport

#8068 Migrate pipeline to gha
  .github/actions/zombienet-sdk/action.yml
  .github/actions/zombienet/action.yml
  .github/workflows/zombienet-reusable-preflight.yml
  .github/workflows/zombienet_polkadot.yml
  .github/zombienet-env
  .gitlab/pipeline/zombienet/polkadot.yml
Labels: R0-silent, T10-tests

#7833 add poke_deposit extrinsic to pallet-society
  prdoc/pr_7833.prdoc
  substrate/frame/society/src/benchmarking.rs
  substrate/frame/society/src/lib.rs
  substrate/frame/society/src/mock.rs
  substrate/frame/society/src/tests.rs
  substrate/frame/society/src/weights.rs
Labels: T1-FRAME, T2-pallets

#8118 Use `TryFrom` impls instead of `as` operator in `polkadot-runtime-parachains`
  polkadot/runtime/parachains/src/inclusion/mod.rs
  prdoc/pr_8118.prdoc
Labels: A4-backport-stable2412

#8187 Added locked flag to readmes that were missing it
  cumulus/polkadot-omni-node/README.md
  polkadot/roadmap/implementers-guide/README.md
  polkadot/xcm/xcm-simulator/fuzzer/README.md
  substrate/bin/utils/chain-spec-builder/README.docify.md
  substrate/bin/utils/chain-spec-builder/README.md
  substrate/utils/frame/omni-bencher/README.md
  templates/parachain/README.docify.md
  templates/parachain/README.md
Labels: R0-silent

#7970 Migrate pallet-nft-fractionalization to umbrella crate
  Cargo.lock
  substrate/frame/nft-fractionalization/Cargo.toml
  substrate/frame/nft-fractionalization/src/benchmarking.rs
  substrate/frame/nft-fractionalization/src/lib.rs
  substrate/frame/nft-fractionalization/src/mock.rs
  substrate/frame/nft-fractionalization/src/tests.rs
  substrate/frame/nft-fractionalization/src/types.rs
  substrate/frame/nft-fractionalization/src/weights.rs
Labels: R0-silent, T2-pallets

#8246 silent nomination-pools try-state check
  substrate/frame/nomination-pools/src/lib.rs
Labels: R0-silent

#7720 Clamp benchmark ranks to respect MaxRank
  cumulus/parachains/runtimes/collectives/collectives-westend/src/ambassador/mod.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/fellowship/mod.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_core_fellowship_ambassador_core.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_core_fellowship_fellowship_core.rs
  prdoc/pr_7720.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/core-fellowship/src/benchmarking.rs
  substrate/frame/core-fellowship/src/lib.rs
  substrate/frame/core-fellowship/src/migration.rs
  substrate/frame/core-fellowship/src/tests/integration.rs
  substrate/frame/core-fellowship/src/tests/unit.rs
  substrate/frame/core-fellowship/src/weights.rs
Labels: T2-pallets

#8102 Make min_peers_to_start_warp_sync configurable
  cumulus/client/service/src/lib.rs
  prdoc/pr_8102.prdoc
  substrate/client/cli/src/params/network_params.rs
  substrate/client/network/src/config.rs
  substrate/client/network/sync/src/strategy/polkadot.rs
  substrate/client/network/sync/src/strategy/warp.rs
  substrate/client/network/test/src/lib.rs
  substrate/client/network/test/src/service.rs
  substrate/client/service/src/builder.rs
Labels: T0-node

#7913 Fix assert_expected_events macro
  cumulus/parachains/integration-tests/emulated/common/src/xcm_helpers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/hybrid_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/xcm_fee_estimation.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/transact.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/xcm_fee_estimation.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge_v2_inbound.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge_v2_rewards.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/transact.rs
  cumulus/xcm/xcm-emulator/src/lib.rs
  prdoc/pr_7913.prdoc
Labels: R0-silent, T10-tests

#7220 YAP NG FTW!
  Cargo.lock
  Cargo.toml
  cumulus/parachains/runtimes/testing/yet-another-parachain/Cargo.toml
  cumulus/parachains/runtimes/testing/yet-another-parachain/build.rs
  cumulus/parachains/runtimes/testing/yet-another-parachain/src/lib.rs
  cumulus/parachains/runtimes/testing/yet-another-parachain/src/xcm_config.rs
  cumulus/polkadot-parachain/Cargo.toml
  cumulus/polkadot-parachain/src/chain_spec/mod.rs
  cumulus/polkadot-parachain/src/chain_spec/yet_another_parachain.rs
  prdoc/pr_7220.prdoc
  substrate/client/basic-authorship/src/basic_authorship.rs
  substrate/frame/system/src/extensions/weights.rs
Labels: T9-cumulus

#8248 Frame: Authorize pallet::error int discriminant
  prdoc/pr_8248.prdoc
  substrate/frame/revive/src/lib.rs
  substrate/frame/support/procedural/src/pallet/parse/error.rs
Labels: T1-FRAME

#7947 Update transfer token gas and fee
  bridges/snowbridge/pallets/outbound-queue-v2/src/test.rs
  bridges/snowbridge/pallets/system/src/lib.rs
  bridges/snowbridge/pallets/system/src/migration.rs
  bridges/snowbridge/primitives/outbound-queue/src/v1/message.rs
  bridges/snowbridge/primitives/outbound-queue/src/v2/message.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/snowbridge.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/snowbridge.rs
  prdoc/pr_7947.prdoc
Labels: T15-bridges, A4-backport-stable2412, A4-backport-stable2503

#8241 [Release|CI/CD] Fix sha256 checksum for mac bins
  .github/workflows/release-30_publish_release_draft.yml
Labels: R0-silent, A4-backport-stable2503

#7960 Stabilize pallet view functions
  prdoc/pr_7960.prdoc
  substrate/frame/examples/view-functions/src/lib.rs
  substrate/frame/proxy/src/lib.rs
  substrate/frame/support/procedural/src/lib.rs
  substrate/frame/support/procedural/src/pallet/parse/mod.rs
  substrate/frame/support/procedural/src/pallet/parse/view_functions.rs
  substrate/frame/support/src/lib.rs
  substrate/frame/support/test/tests/pallet.rs
  substrate/frame/support/test/tests/pallet_ui/pass/view_function_valid.rs
  substrate/frame/support/test/tests/pallet_ui/view_function_invalid_item.rs
  substrate/frame/support/test/tests/pallet_ui/view_function_invalid_item.stderr
  substrate/frame/support/test/tests/pallet_ui/view_function_no_return.rs
  substrate/frame/support/test/tests/pallet_ui/view_function_not_public.rs
  substrate/frame/support/test/tests/pallet_ui/view_function_not_public.stderr
Labels: T1-FRAME, T4-runtime_API

#8275 Preserve Original Topic ID in forward_id_for for Consistent XCM Tracking
  bridges/snowbridge/runtime/runtime-common/src/tests.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/send_xcm.rs
  cumulus/xcm/xcm-emulator/src/lib.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  polkadot/xcm/src/v5/mod.rs
  polkadot/xcm/xcm-builder/src/routing.rs
  polkadot/xcm/xcm-builder/src/universal_exports.rs
  polkadot/xcm/xcm-executor/src/lib.rs
Labels: T6-XCM

#8247 Refactor: Remove unused variable assignments for fallible functions
  bridges/modules/xcm-bridge-hub-router/src/lib.rs
  cumulus/primitives/utility/src/tests/swap_first.rs
  docs/sdk/src/reference_docs/frame_origin.rs
  polkadot/node/core/approval-voting/src/ops.rs
  polkadot/runtime/common/src/slots/mod.rs
  polkadot/runtime/parachains/src/hrmp.rs
  polkadot/runtime/rococo/src/impls.rs
  polkadot/runtime/westend/src/impls.rs
  polkadot/xcm/xcm-builder/src/universal_exports.rs
  substrate/bin/utils/chain-spec-builder/src/lib.rs
  substrate/client/consensus/grandpa/src/communication/mod.rs
  substrate/client/executor/wasmtime/src/tests.rs
  substrate/client/network/sync/src/engine.rs
  substrate/client/service/src/client/client.rs
  substrate/frame/asset-conversion/ops/src/lib.rs
  substrate/frame/assets/src/functions.rs
  substrate/frame/assets/src/lib.rs
  substrate/frame/bags-list/src/lib.rs
  substrate/frame/bags-list/src/list/mod.rs
  substrate/frame/bounties/src/lib.rs
  substrate/frame/broker/src/lib.rs
  substrate/frame/child-bounties/src/lib.rs
  substrate/frame/collective/src/lib.rs
  substrate/frame/contracts/src/exec.rs
  substrate/frame/contracts/src/wasm/prepare.rs
  substrate/frame/core-fellowship/src/lib.rs
  substrate/frame/delegated-staking/src/lib.rs
  substrate/frame/democracy/src/lib.rs
  substrate/frame/election-provider-multi-phase/src/lib.rs
  substrate/frame/election-provider-multi-phase/src/unsigned.rs
  substrate/frame/election-provider-support/solution-type/src/lib.rs
  substrate/frame/elections-phragmen/src/benchmarking.rs
  substrate/frame/elections-phragmen/src/lib.rs
  substrate/frame/fast-unstake/src/lib.rs
  substrate/frame/identity/src/benchmarking.rs
  substrate/frame/identity/src/lib.rs
  substrate/frame/membership/src/lib.rs
  substrate/frame/message-queue/src/lib.rs
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/revive/rpc/examples/extrinsic.rs
  substrate/frame/revive/src/exec/tests.rs
  substrate/frame/salary/src/lib.rs
  substrate/frame/session/src/historical/mod.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/state-trie-migration/src/lib.rs
  substrate/frame/support/procedural/src/match_and_insert.rs
  substrate/frame/support/procedural/src/tt_macro.rs
  substrate/frame/support/src/traits/try_runtime/decode_entire_state.rs
  substrate/frame/utility/src/tests.rs
  substrate/primitives/npos-elections/src/phragmen.rs
  substrate/primitives/npos-elections/src/phragmms.rs
  substrate/primitives/version/src/lib.rs
  substrate/utils/build-script-utils/src/git.rs
  substrate/utils/frame/benchmarking-cli/src/extrinsic/bench.rs
  substrate/utils/frame/benchmarking-cli/src/storage/cmd.rs
Labels: R0-silent

#8263 Document transactional extrinsic behavior.
  substrate/frame/support/src/lib.rs
Labels: A1-insubstantial, R0-silent, T1-FRAME

#8171 Add missing vested transfer event
  prdoc/pr_8171.prdoc
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/vesting/src/lib.rs
  substrate/frame/vesting/src/mock.rs
  substrate/frame/vesting/src/tests.rs
Labels: T2-pallets

#8277 Fix defensive public repo link
  substrate/frame/support/src/traits/misc.rs
Labels: R0-silent

#8276 sc-tracing-proc-macro: missing bump due to incomplete prdoc
  prdoc/stable2503/pr_7464.prdoc
Labels: R0-silent

#8100 Remove the redundant FRAME coders substrate rule
  .github/review-bot.yml
Labels: R0-silent

#8238 Added `checked_sqrt` to the `FixedPointNumber` trait
  prdoc/pr_8238.prdoc
  substrate/primitives/arithmetic/src/fixed_point.rs
Labels: T13-deprecation, R1-breaking_change, T17-primitives

#3811 Full Unbond in Staking
  prdoc/pr_3811.prdoc
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/lib.rs
  substrate/frame/nomination-pools/test-delegate-stake/src/lib.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/tests.rs
Labels: T2-pallets

#8148 [revive] eth-rpc refactoring
  prdoc/pr_8148.prdoc
  substrate/frame/revive/rpc/.sqlx/query-6345c84da6afad02d0fdf4e1657c53e64320c118d39db73f573510235baf4ba0.json
  substrate/frame/revive/rpc/.sqlx/query-d7377b5a09f075668d259d02e3fc7a12048a70a33b96381118d6c24210afce34.json
  substrate/frame/revive/rpc/.sqlx/query-e3d7860041663651866032e8fb054cff3e1707381845f47f693177dbce110448.json
  substrate/frame/revive/rpc/src/block_info_provider.rs
  substrate/frame/revive/rpc/src/cli.rs
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/rpc/src/example.rs
  substrate/frame/revive/rpc/src/lib.rs
  substrate/frame/revive/rpc/src/receipt_extractor.rs
  substrate/frame/revive/rpc/src/receipt_provider.rs
  substrate/frame/revive/rpc/src/receipt_provider/cache.rs
  substrate/frame/revive/rpc/src/receipt_provider/db.rs
  substrate/frame/revive/rpc/src/tests.rs
  substrate/frame/revive/src/evm/api/rlp_codec.rs
  substrate/frame/revive/src/evm/api/rpc_types.rs
  substrate/frame/revive/src/evm/runtime.rs
  substrate/frame/revive/src/lib.rs
Labels: R0-silent, T7-smart_contracts

#8283 Update README.md
  README.md
Labels: R0-silent

#8001 `txpool`: use tracing for structured logging
  Cargo.lock
  prdoc/pr_8001.prdoc
  substrate/client/transaction-pool/Cargo.toml
  substrate/client/transaction-pool/src/builder.rs
  substrate/client/transaction-pool/src/common/api.rs
  substrate/client/transaction-pool/src/common/enactment_state.rs
  substrate/client/transaction-pool/src/common/log_xt.rs
  substrate/client/transaction-pool/src/common/metrics.rs
  substrate/client/transaction-pool/src/common/mod.rs
  substrate/client/transaction-pool/src/graph/base_pool.rs
  substrate/client/transaction-pool/src/graph/listener.rs
  substrate/client/transaction-pool/src/graph/pool.rs
  substrate/client/transaction-pool/src/graph/ready.rs
  substrate/client/transaction-pool/src/graph/validated_pool.rs
  substrate/client/transaction-pool/src/single_state_txpool/revalidation.rs
  substrate/client/transaction-pool/src/single_state_txpool/single_state_txpool.rs
  substrate/client/transaction-pool/tests/fatp.rs
  substrate/client/transaction-pool/tests/fatp_common/mod.rs
  substrate/client/transaction-pool/tests/fatp_invalid.rs
  substrate/client/transaction-pool/tests/fatp_limits.rs
  substrate/client/transaction-pool/tests/fatp_prios.rs
  substrate/client/transaction-pool/tests/pool.rs
Labels: R0-silent, T0-node

#7882 add poke_deposit extrinsic to pallet-recovery
  Cargo.lock
  polkadot/runtime/rococo/src/weights/pallet_recovery.rs
  polkadot/runtime/westend/src/weights/pallet_recovery.rs
  prdoc/pr_7882.prdoc
  substrate/frame/recovery/Cargo.toml
  substrate/frame/recovery/src/benchmarking.rs
  substrate/frame/recovery/src/lib.rs
  substrate/frame/recovery/src/mock.rs
  substrate/frame/recovery/src/tests.rs
  substrate/frame/recovery/src/weights.rs
Labels: T1-FRAME, T2-pallets

#8274 [pallet-revive] add get_storage_var_key for variable-sized keys
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_8274.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/revive/src/lib.rs
Labels: T7-smart_contracts

#8228 [stable2412] Backport changes released in stable2412-3 to prdoc folder in stable2412 branch
  prdoc/stable2412-3/pr_7866.prdoc
Labels: R0-silent

#8294 Fix faulty pre-upgrade migration check in pallet-session
  substrate/frame/session/src/migrations/v1.rs
Labels: R0-silent, T10-tests, A4-backport-stable2503

#7944 Allow configuration of worst case buy execution weight
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/bridge-primitives/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/mock.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/mod.rs
  prdoc/pr_7944.prdoc
  substrate/frame/staking-async/runtimes/parachain/src/lib.rs
  substrate/frame/staking-async/runtimes/rc/src/lib.rs
Labels: T6-XCM

#8309 Enforce Consistent `SetTopic` Appending in Outbound XCM
  polkadot/xcm/xcm-builder/src/routing.rs
  polkadot/xcm/xcm-builder/src/tests/assets.rs
  polkadot/xcm/xcm-builder/src/tests/querying.rs
  polkadot/xcm/xcm-builder/src/tests/transacting.rs
  polkadot/xcm/xcm-builder/src/universal_exports.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  polkadot/xcm/xcm-executor/src/tests/initiate_transfer.rs
  polkadot/xcm/xcm-executor/src/tests/pay_fees.rs
  prdoc/pr_7691.prdoc
Labels: T6-XCM

#8021 XCMP: use batching when enqueuing inbound messages
  bridges/snowbridge/pallets/outbound-queue-v2/src/test.rs
  bridges/snowbridge/pallets/outbound-queue/src/test.rs
  cumulus/pallets/dmp-queue/src/mock.rs
  cumulus/pallets/xcmp-queue/src/benchmarking.rs
  cumulus/pallets/xcmp-queue/src/lib.rs
  cumulus/pallets/xcmp-queue/src/mock.rs
  cumulus/pallets/xcmp-queue/src/tests.rs
  cumulus/pallets/xcmp-queue/src/weights.rs
  cumulus/pallets/xcmp-queue/src/weights_ext.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/testing/yet-another-parachain/src/lib.rs
  polkadot/runtime/parachains/src/inclusion/mod.rs
  polkadot/runtime/parachains/src/ump_tests.rs
  prdoc/pr_8021.prdoc
  substrate/frame/message-queue/src/lib.rs
  substrate/frame/message-queue/src/tests.rs
  substrate/frame/staking-async/runtimes/parachain/src/weights/cumulus_pallet_xcmp_queue.rs
  substrate/frame/support/src/traits.rs
  substrate/frame/support/src/traits/messages.rs
Labels: T6-XCM, I9-optimisation

#8289 Extract create_pool_with_native_on macro to common crate
  cumulus/parachains/integration-tests/emulated/common/src/macros.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge_common.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/transact.rs
  prdoc/pr_8289.prdoc
Labels: T10-tests

#5620 New NFT traits: granular and abstract interface
  prdoc/pr_5620.prdoc
  substrate/frame/support/src/traits/tokens.rs
  substrate/frame/support/src/traits/tokens/asset_ops.rs
  substrate/frame/support/src/traits/tokens/asset_ops/common_strategies.rs
  substrate/frame/uniques/src/asset_ops/collection.rs
  substrate/frame/uniques/src/asset_ops/item.rs
  substrate/frame/uniques/src/asset_ops/mod.rs
  substrate/frame/uniques/src/lib.rs
  substrate/frame/uniques/src/tests.rs
  substrate/frame/uniques/src/types.rs
Labels: T1-FRAME

#8310 staking-async: add missing new_session_genesis
  prdoc/pr_8310.prdoc
  substrate/frame/staking-async/ah-client/src/lib.rs
Labels: I2-bug, T1-FRAME, T2-pallets, T10-tests

#8226 migrate parachain-templates tests to `gha`
  .github/workflows/build-publish-images.yml
  .github/workflows/zombienet-reusable-preflight.yml
  .github/workflows/zombienet_parachain-template.yml
  .gitlab/pipeline/zombienet/parachain-template.yml
Labels: R0-silent, T10-tests

#8335 Backport fix for pallet-multisig benchmarks
  prdoc/pr_8335.prdoc
  substrate/frame/multisig/src/benchmarking.rs
Labels: T12-benchmarks

#8250 Check umbrella version
  .github/workflows/checks-quick.yml
Labels: R0-silent

#8292 Bridge Permissionless Lanes - Emulated Tests
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/networks/rococo-westend-system/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/bridging.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/mod.rs
Labels: R0-silent, T15-bridges

#8322 push to dockerhub
  .github/actions/build-push-image/action.yml
  .github/workflows/build-publish-images.yml
Labels: R0-silent, A5-run-CI

#7857 Add new host APIs set_storage_or_clear and get_storage_or_zero
  prdoc/pr_7857.prdoc
  substrate/frame/revive/fixtures/contracts/clear_storage_on_zero_value.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv64.rs
Labels: T7-smart_contracts

#8329 [CI/CD] Use original PR name in prdoc check for the backport PR's to the stable branches
  .github/workflows/check-prdoc.yml
  docs/BACKPORT.md
  docs/RELEASE.md
Labels: R0-silent, A4-backport-stable2409, A4-backport-stable2412, A4-backport-stable2503

#8331 [CI] Improve GH build status checking
  .github/workflows/zombienet-reusable-preflight.yml
Labels: R0-silent, T9-cumulus, T10-tests

#8357 ci: change nextest test-threads to num-cpus
  .config/nextest.toml
Labels: R0-silent

#8338 fix synchronous backing test
  .github/workflows/zombienet_polkadot.yml
  cumulus/test/runtime/Cargo.toml
  cumulus/test/runtime/build.rs
  cumulus/test/runtime/src/lib.rs
  cumulus/test/service/src/chain_spec.rs
  cumulus/test/service/src/cli.rs
  polkadot/zombienet-sdk-tests/tests/functional/sync_backing.rs
Labels: R0-silent, T8-polkadot, T9-cumulus, T10-tests

#7995 Add event to pure proxy deletion
  prdoc/pr_7995.prdoc
  substrate/frame/proxy/src/lib.rs
  substrate/frame/proxy/src/tests.rs
Labels: T2-pallets, T10-tests, T14-system_parachains

#8360 Ep fix failing test
  polkadot/xcm/xcm-runtime-apis/tests/fee_estimation.rs
Labels: R0-silent

#8243 slot-based-collator: Do not skip slots
  cumulus/client/consensus/aura/src/collators/slot_based/slot_timer.rs
Labels: R0-silent

#8273 pallet-revive: Add net-listening rpc
  prdoc/pr_8273.prdoc
  substrate/frame/revive/rpc/src/apis/execution_apis.rs
  substrate/frame/revive/rpc/src/lib.rs
Labels: R0-silent, T7-smart_contracts

#8254 Introduce `remove_upgrade_cooldown`
  .github/workflows/check-prdoc.yml
  polkadot/runtime/common/src/assigned_slots/mod.rs
  polkadot/runtime/common/src/integration_tests.rs
  polkadot/runtime/common/src/paras_registrar/mock.rs
  polkadot/runtime/parachains/src/mock.rs
  polkadot/runtime/parachains/src/paras/benchmarking.rs
  polkadot/runtime/parachains/src/paras/mod.rs
  polkadot/runtime/parachains/src/paras/tests.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_parachains_paras.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_parachains_paras.rs
  prdoc/pr_8254.prdoc
  substrate/frame/staking-async/ahm-test/Cargo.toml
  substrate/frame/staking-async/runtimes/rc/src/lib.rs
  substrate/frame/staking-async/runtimes/rc/src/weights/polkadot_runtime_parachains_paras.rs
  substrate/frame/system/src/lib.rs
Labels: T8-polkadot

#8323 Allow genesis-presets to be patched and remove native runtime calls from the staging-node-cli
  cumulus/polkadot-parachain/src/chain_spec/asset_hubs.rs
  cumulus/polkadot-parachain/src/chain_spec/bridge_hubs.rs
  cumulus/polkadot-parachain/src/chain_spec/glutton.rs
  cumulus/polkadot-parachain/src/chain_spec/people.rs
  prdoc/pr_8323.prdoc
  substrate/bin/node/cli/src/chain_spec.rs
  substrate/client/chain-spec/src/chain_spec.rs
Labels: T17-primitives

#8361 Update URLs to use `polkadot.com` instead of outdated domains
  .config/lychee.toml
  .github/workflows/publish-check-compile.yml
  bridges/docs/running-relayer.md
  docs/sdk/src/guides/async_backing_guide.rs
  docs/sdk/src/guides/enable_elastic_scaling_mvp.rs
  docs/sdk/src/polkadot_sdk/mod.rs
  docs/sdk/src/polkadot_sdk/polkadot.rs
  polkadot/.rpm/polkadot.spec
  polkadot/Cargo.toml
  polkadot/README.md
  polkadot/node/core/pvf/src/lib.rs
  polkadot/roadmap/implementers-guide/src/node/backing/statement-distribution.md
  substrate/bin/utils/subkey/src/lib.rs
  substrate/frame/bags-list/src/lib.rs
  substrate/frame/examples/basic/src/lib.rs
  substrate/frame/fast-unstake/src/lib.rs
  substrate/frame/paged-list/src/lib.rs
  substrate/frame/revive/src/evm/api/rlp_codec.rs
  substrate/frame/scheduler/src/lib.rs
  substrate/frame/sudo/src/lib.rs
  substrate/frame/timestamp/src/lib.rs
  substrate/frame/treasury/src/lib.rs
  templates/minimal/node/README.md
Labels: R0-silent

#8197 [pallet-revive] add fee_history
  prdoc/pr_8197.prdoc
  substrate/frame/revive/rpc/src/apis/execution_apis.rs
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/rpc/src/fee_history.rs
  substrate/frame/revive/rpc/src/fee_history_provider.rs
  substrate/frame/revive/rpc/src/lib.rs
  substrate/frame/revive/rpc/src/receipt_extractor.rs
  substrate/frame/revive/rpc/src/receipt_provider.rs
  substrate/frame/revive/src/evm/api/rpc_types.rs
  substrate/frame/revive/src/evm/api/rpc_types_gen.rs
Labels: R0-silent, T7-smart_contracts

#8261 Fix FFI type diversion
  prdoc/pr_7375.prdoc
  substrate/frame/benchmarking/src/utils.rs
  substrate/primitives/core/src/lib.rs
  substrate/primitives/core/src/offchain/mod.rs
  substrate/primitives/io/src/lib.rs
  substrate/primitives/runtime-interface/src/pass_by.rs
Labels: R0-silent, T17-primitives

#8327 Update to frame-metadata 22
  Cargo.lock
  Cargo.toml
  prdoc/pr_8327.prdoc
  substrate/frame/examples/view-functions/src/tests.rs
  substrate/frame/support/procedural/src/deprecation.rs
  substrate/frame/support/procedural/src/pallet/expand/call.rs
  substrate/frame/support/procedural/src/pallet/expand/error.rs
  substrate/frame/support/procedural/src/pallet/expand/event.rs
  substrate/frame/support/procedural/src/pallet/expand/pallet_struct.rs
  substrate/frame/support/procedural/src/pallet/parse/call.rs
  substrate/frame/support/procedural/src/pallet/parse/error.rs
  substrate/frame/support/procedural/src/pallet/parse/event.rs
  substrate/frame/support/procedural/src/pallet/parse/tests/mod.rs
  substrate/frame/support/src/storage/types/counted_map.rs
  substrate/frame/support/src/storage/types/counted_nmap.rs
  substrate/frame/support/src/storage/types/double_map.rs
  substrate/frame/support/src/storage/types/map.rs
  substrate/frame/support/src/storage/types/mod.rs
  substrate/frame/support/src/storage/types/nmap.rs
  substrate/frame/support/src/storage/types/value.rs
  substrate/frame/support/src/tests/mod.rs
  substrate/frame/support/test/tests/enum_deprecation.rs
  substrate/frame/support/test/tests/instance.rs
  substrate/frame/support/test/tests/pallet.rs
  substrate/frame/support/test/tests/runtime_metadata.rs
  substrate/primitives/api/proc-macro/src/utils.rs
  substrate/primitives/metadata-ir/src/types.rs
  substrate/primitives/metadata-ir/src/unstable.rs
Labels: R0-silent, T4-runtime_API

#8386 [stable2412] Patch release 2412-5
  Cargo.lock
  Cargo.toml
  Plan.toml
  bridges/snowbridge/pallets/system/Cargo.toml
  bridges/snowbridge/primitives/core/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/Cargo.toml
  cumulus/polkadot-omni-node/lib/src/nodes/mod.rs
  polkadot/node/primitives/src/lib.rs
  polkadot/xcm/pallet-xcm-benchmarks/Cargo.toml
  polkadot/xcm/xcm-builder/Cargo.toml
  prdoc/stable2412-5/pr_6540.prdoc
  prdoc/stable2412-5/pr_8081.prdoc
  prdoc/stable2412-5/pr_8198.prdoc
  prdoc/stable2412-5/pr_8210.prdoc
  prdoc/stable2412-5/pr_8258.prdoc
  prdoc/stable2412-5/pr_8335.prdoc
  substrate/frame/multisig/Cargo.toml
  substrate/frame/nomination-pools/Cargo.toml
  substrate/frame/nomination-pools/runtime-api/Cargo.toml
  substrate/primitives/io/Cargo.toml
  substrate/utils/wasm-builder/Cargo.toml
  umbrella/Cargo.toml
Labels: R0-silent

#8072 RFC-0008: Store parachain bootnodes in the relay chain DHT
  Cargo.lock
  Cargo.toml
  cumulus/client/bootnodes/Cargo.toml
  cumulus/client/bootnodes/build.rs
  cumulus/client/bootnodes/src/advertisement.rs
  cumulus/client/bootnodes/src/config.rs
  cumulus/client/bootnodes/src/discovery.rs
  cumulus/client/bootnodes/src/lib.rs
  cumulus/client/bootnodes/src/schema/response.proto
  cumulus/client/bootnodes/src/task.rs
  cumulus/client/cli/src/lib.rs
  cumulus/client/consensus/common/Cargo.toml
  cumulus/client/network/Cargo.toml
  cumulus/client/pov-recovery/Cargo.toml
  cumulus/client/relay-chain-inprocess-interface/Cargo.toml
  cumulus/client/relay-chain-inprocess-interface/src/lib.rs
  cumulus/client/relay-chain-interface/Cargo.toml
  cumulus/client/relay-chain-minimal-node/Cargo.toml
  cumulus/client/relay-chain-minimal-node/src/collator_overseer.rs
  cumulus/client/relay-chain-minimal-node/src/lib.rs
  cumulus/client/relay-chain-rpc-interface/Cargo.toml
  cumulus/client/service/Cargo.toml
  cumulus/client/service/src/lib.rs
  cumulus/polkadot-omni-node/lib/Cargo.toml
  cumulus/polkadot-omni-node/lib/src/common/spec.rs
  cumulus/test/service/src/lib.rs
  cumulus/zombienet/zombienet-sdk-helpers/src/lib.rs
  cumulus/zombienet/zombienet-sdk/tests/bootnodes/mod.rs
  cumulus/zombienet/zombienet-sdk/tests/lib.rs
  prdoc/pr_8072.prdoc
  substrate/client/authority-discovery/src/worker.rs
  substrate/client/authority-discovery/src/worker/tests.rs
  substrate/client/network/src/behaviour.rs
  substrate/client/network/src/discovery.rs
  substrate/client/network/src/event.rs
  substrate/client/network/src/litep2p/discovery.rs
  substrate/client/network/src/litep2p/mod.rs
  substrate/client/network/src/litep2p/service.rs
  substrate/client/network/src/service.rs
  substrate/client/network/src/service/traits.rs
  templates/parachain/node/src/service.rs
  umbrella/Cargo.toml
  umbrella/src/lib.rs
Labels: T0-node, T9-cumulus
