Repository paritytech/polkadot-sdk, pull requests merged in 2025-02, with the labels that each got.

#7415 fix(sync-templates): empty matrix strategy expansion
  .github/workflows/misc-sync-templates.yml
Labels: R0-silent

#7408 add allow(dead_code) to substrate weight templates
  substrate/.maintain/frame-umbrella-weight-template.hbs
  substrate/.maintain/frame-weight-template.hbs
Labels: R0-silent

#7414 [pallet-revive] do not trap the caller on instantiations with duplicate contracts
  prdoc/pr_7414.prdoc
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/uapi/src/lib.rs
Labels: R0-silent, T7-smart_contracts

#7367 Align omni-node and polkadot-parachain versions
  .github/workflows/release-10_branchoff-stable.yml
  cumulus/polkadot-omni-node/lib/src/lib.rs
  cumulus/polkadot-omni-node/lib/src/nodes/mod.rs
  cumulus/polkadot-omni-node/src/main.rs
  cumulus/polkadot-parachain/src/main.rs
Labels: R0-silent

#7439 fix(sync-templates): keep parachain-template's workspace Cargo.toml
  .github/workflows/misc-sync-templates.yml
Labels: R0-silent

#7437 Fix Message codec indexes
  substrate/client/network/src/protocol/message.rs
Labels: R0-silent, I2-bug

#7316 `fatxpool`: do not use individual transaction listeners
  substrate/client/service/src/lib.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/dropped_watcher.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/mod.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/multi_view_listener.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/tx_mem_pool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/view.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs
  substrate/client/transaction-pool/src/graph/listener.rs
  substrate/client/transaction-pool/src/graph/mod.rs
  substrate/client/transaction-pool/src/graph/tracked_map.rs
  substrate/client/transaction-pool/src/graph/validated_pool.rs
  substrate/client/transaction-pool/tests/fatp_common/mod.rs
  substrate/client/transaction-pool/tests/fatp_limits.rs
Labels: R0-silent, T0-node

#7436 Snowbridge: Remove fee amount check from tests
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge.rs
Labels: R0-silent, T10-tests

#7377 Add missing events to nomination pool extrinsincs
  prdoc/pr_7377.prdoc
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/nomination-pools/src/tests.rs
  substrate/frame/nomination-pools/test-delegate-stake/src/lib.rs
  substrate/frame/staking/src/pallet/mod.rs
Labels: T1-FRAME, T2-pallets

#7454 Remove pallet_revive benchmarks from Westend AssetHub
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
Labels: R0-silent

#7451 omni-node: Adjust manual seal parameters
  cumulus/polkadot-omni-node/lib/src/nodes/manual_seal.rs
  prdoc/pr_7451.prdoc
  templates/parachain/dev_chain_spec.json
Labels: T9-cumulus, A4-needs-backport

#7479 omni-node: add offchain worker
  Cargo.lock
  cumulus/polkadot-omni-node/lib/Cargo.toml
  cumulus/polkadot-omni-node/lib/src/common/mod.rs
  cumulus/polkadot-omni-node/lib/src/common/spec.rs
  cumulus/polkadot-omni-node/lib/src/fake_runtime_api/utils.rs
  cumulus/polkadot-omni-node/lib/src/nodes/manual_seal.rs
  prdoc/pr_7479.prdoc
Labels: T0-node, T9-cumulus

#7488 litep2p: Increase keep-alive to 10 seconds to mirror libp2p
  prdoc/pr_7488.prdoc
  substrate/client/network/src/litep2p/mod.rs
Labels: T0-node

#7463 [pallet-revive] tx fee fixes
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_7463.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/revive/rpc/revive_chain.metadata
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/rpc/src/lib.rs
  substrate/frame/revive/src/evm/gas_encoder.rs
  substrate/frame/revive/src/evm/runtime.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/tests.rs
Labels: R0-silent, T7-smart_contracts

#6623 Update pallet society to support Block Number Provider
  polkadot/runtime/rococo/src/lib.rs
  prdoc/pr_6623.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/society/src/benchmarking.rs
  substrate/frame/society/src/lib.rs
  substrate/frame/society/src/migrations.rs
  substrate/frame/society/src/mock.rs
Labels: T2-pallets

#6913 Populate topology after restart if finality is lagging behind current session
  polkadot/node/network/bridge/src/rx/mod.rs
  polkadot/node/network/bridge/src/rx/tests.rs
  polkadot/node/network/gossip-support/src/lib.rs
  polkadot/node/network/gossip-support/src/tests.rs
  polkadot/node/overseer/src/lib.rs
  prdoc/pr_6913.prdoc
Labels: T8-polkadot

#6621 Update pallet conviction voting to support Block Number Provider
  polkadot/runtime/rococo/src/governance/mod.rs
  polkadot/runtime/westend/src/governance/mod.rs
  prdoc/pr_6621.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/conviction-voting/src/lib.rs
  substrate/frame/conviction-voting/src/tests.rs
  substrate/primitives/runtime/src/traits/mod.rs
Labels: T2-pallets

#7504 enable approval-voting-parallel on polkadot
  polkadot/cli/src/cli.rs
  polkadot/node/service/src/lib.rs
  prdoc/pr_7504.prdoc
Labels: T8-polkadot, A4-needs-backport

#7482 [pallet-revive] rpc - gas used fixes
  prdoc/pr_7482.prdoc
  substrate/frame/revive/rpc/examples/rust/deploy.rs
  substrate/frame/revive/rpc/examples/rust/rpc-playground.rs
  substrate/frame/revive/rpc/examples/rust/transfer.rs
  substrate/frame/revive/rpc/revive_chain.metadata
  substrate/frame/revive/rpc/src/cli.rs
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/rpc/src/eth-indexer.rs
  substrate/frame/revive/rpc/src/eth-rpc-tester.rs
  substrate/frame/revive/rpc/src/example.rs
  substrate/frame/revive/rpc/src/lib.rs
  substrate/frame/revive/rpc/src/receipt_extractor.rs
  substrate/frame/revive/rpc/src/receipt_provider.rs
  substrate/frame/revive/rpc/src/receipt_provider/cache.rs
  substrate/frame/revive/rpc/src/receipt_provider/db.rs
  substrate/frame/revive/rpc/src/tests.rs
Labels: R0-silent, T7-smart_contracts

#7412 Pallet view functions: improve metadata, API docs and testing
  prdoc/pr_7412.prdoc
  substrate/frame/examples/view-functions/src/lib.rs
  substrate/frame/examples/view-functions/src/tests.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/metadata.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/view_function.rs
  substrate/frame/support/procedural/src/lib.rs
  substrate/frame/support/procedural/src/pallet/expand/view_functions.rs
  substrate/frame/support/procedural/src/pallet/parse/view_functions.rs
  substrate/frame/support/src/lib.rs
  substrate/frame/support/src/view_functions.rs
  substrate/frame/support/test/tests/construct_runtime_ui/deprecated_where_block.stderr
  substrate/frame/support/test/tests/pallet_ui/pass/view_function_valid.rs
  substrate/frame/support/test/tests/pallet_ui/view_function_invalid_item.rs
  substrate/frame/support/test/tests/pallet_ui/view_function_invalid_item.stderr
  substrate/frame/support/test/tests/pallet_ui/view_function_no_return.rs
  substrate/frame/support/test/tests/pallet_ui/view_function_no_return.stderr
  substrate/frame/support/test/tests/pallet_ui/view_function_not_public.rs
  substrate/frame/support/test/tests/pallet_ui/view_function_not_public.stderr
  substrate/primitives/metadata-ir/src/lib.rs
  substrate/primitives/metadata-ir/src/types.rs
  substrate/primitives/metadata-ir/src/unstable.rs
  substrate/primitives/metadata-ir/src/v15.rs
Labels: T1-FRAME, T4-runtime_API

#7493 [pallet-revive] fix eth-rpc indexing
  .github/workflows/build-publish-eth-rpc.yml
  Cargo.lock
  prdoc/pr_7493.prdoc
  substrate/frame/revive/rpc/.sqlx/query-027a434a38822c2ba4439e8f9f9c1135227c1150f2c5083d1c7c6086b717ada0.json
  substrate/frame/revive/rpc/.sqlx/query-29af64347f700919dc2ee12463f332be50096d4e37be04ed8b6f46ac5c242043.json
  substrate/frame/revive/rpc/.sqlx/query-de639fe0ac0c3cfdfbbfa07e81a61dae3a284ad4f7979dacb0ccff32cdc39051.json
  substrate/frame/revive/rpc/Cargo.toml
  substrate/frame/revive/rpc/dockerfiles/eth-indexer/Dockerfile
  substrate/frame/revive/rpc/examples/js/.prettierrc.json
  substrate/frame/revive/rpc/examples/js/contracts/.solhint.json
  substrate/frame/revive/rpc/examples/js/package.json
  substrate/frame/revive/rpc/examples/js/src/geth-diff.test.ts
  substrate/frame/revive/rpc/examples/js/src/spammer.ts
  substrate/frame/revive/rpc/examples/js/src/util.ts
  substrate/frame/revive/rpc/migrations/0001_create_transaction_hashes.sql
  substrate/frame/revive/rpc/migrations/20241205165418_create_transaction_hashes.sql
  substrate/frame/revive/rpc/src/block_info_provider.rs
  substrate/frame/revive/rpc/src/cli.rs
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/rpc/src/eth-indexer.rs
  substrate/frame/revive/rpc/src/eth-rpc-tester.rs
  substrate/frame/revive/rpc/src/lib.rs
  substrate/frame/revive/rpc/src/receipt_extractor.rs
  substrate/frame/revive/rpc/src/receipt_provider.rs
  substrate/frame/revive/rpc/src/receipt_provider/cache.rs
  substrate/frame/revive/rpc/src/receipt_provider/db.rs
  substrate/frame/revive/src/evm/api/rpc_types_gen.rs
Labels: R0-silent, T7-smart_contracts

#7217 Zombienet gha substrate migration
  .github/actions/build-push-image/action.yml
  .github/workflows/build-publish-images.yml
  .github/workflows/zombienet-reusable-preflight.yml
  .github/workflows/zombienet_substrate.yml
  .github/zombienet-env
Labels: R0-silent, T10-tests

#7507 Fix compilation warnings
  prdoc/pr_7507.prdoc
  substrate/frame/examples/view-functions/Cargo.toml
  substrate/primitives/consensus/beefy/src/payload.rs
Labels: R0-silent

#6715 Update pallet nomination pool to support Block Number Provider
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_6715.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/delegated-staking/src/mock.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
  substrate/frame/nomination-pools/benchmarking/src/mock.rs
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/nomination-pools/src/mock.rs
  substrate/frame/nomination-pools/test-delegate-stake/src/mock.rs
Labels: T2-pallets

#7419 pallet-revive-fixtures: Support compilation on stable
  substrate/frame/revive/fixtures/build.rs
Labels: R0-silent

#7008 feat(wasm-builder): add support for new `wasm32v1-none` target
  prdoc/pr_7008.prdoc
  scripts/generate-umbrella.py
  substrate/utils/wasm-builder/src/builder.rs
  substrate/utils/wasm-builder/src/lib.rs
  substrate/utils/wasm-builder/src/prerequisites.rs
  substrate/utils/wasm-builder/src/wasm_project.rs
Labels: T17-primitives

#7430 [pallet-revive] fix tracing gas used
  prdoc/pr_7430.prdoc
  substrate/frame/revive/fixtures/contracts/caller_contract.rs
  substrate/frame/revive/fixtures/contracts/tracing.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/mod.rs
Labels: R0-silent, T7-smart_contracts

#7483 Bound some storage items for pallet `staking` and clean up deprecated exposures
  cumulus/parachains/integration-tests/emulated/chains/relays/westend/src/genesis.rs
  polkadot/runtime/common/src/try_runtime.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/genesis_config_presets.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/pallet_fast_unstake.rs
  polkadot/runtime/westend/src/weights/pallet_staking.rs
  substrate/bin/node/runtime/src/lib.rs
  substrate/bin/node/testing/src/genesis.rs
  substrate/frame/babe/src/mock.rs
  substrate/frame/beefy/src/mock.rs
  substrate/frame/delegated-staking/src/mock.rs
  substrate/frame/grandpa/src/mock.rs
  substrate/frame/root-offences/src/mock.rs
  substrate/frame/staking/src/benchmarking.rs
  substrate/frame/staking/src/lib.rs
  substrate/frame/staking/src/migrations.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/slashing.rs
  substrate/frame/staking/src/tests.rs
  substrate/primitives/staking/src/offence.rs
Labels: R0-silent, T1-FRAME

#7506 [pallet-revive] Add eth_get_logs
  Cargo.lock
  prdoc/pr_7506.prdoc
  substrate/frame/revive/rpc/.sqlx/query-76dd0f2460cfc0ffa93dda7a42893cbf05b3451cb8e4c4cb6cf86ec70930a11e.json
  substrate/frame/revive/rpc/Cargo.toml
  substrate/frame/revive/rpc/examples/js/src/build-contracts.ts
  substrate/frame/revive/rpc/examples/js/src/geth-diff.test.ts
  substrate/frame/revive/rpc/examples/js/src/spammer.ts
  substrate/frame/revive/rpc/examples/js/src/transfer.ts
  substrate/frame/revive/rpc/migrations/0002_create_log_table.sql
  substrate/frame/revive/rpc/src/block_info_provider.rs
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/rpc/src/lib.rs
  substrate/frame/revive/rpc/src/receipt_provider.rs
  substrate/frame/revive/rpc/src/receipt_provider/cache.rs
  substrate/frame/revive/rpc/src/receipt_provider/db.rs
  substrate/frame/revive/rpc/src/rpc_methods_gen.rs
  substrate/frame/revive/src/evm/api/rpc_types_gen.rs
  substrate/frame/revive/src/lib.rs
Labels: R0-silent, T7-smart_contracts

#7243 transfer function Preservation is changed to Expendable
  polkadot/xcm/xcm-builder/src/fungible_adapter.rs
  polkadot/xcm/xcm-builder/src/fungibles_adapter.rs
  prdoc/pr_7243.prdoc
Labels: T6-XCM, A4-needs-backport

#7411 update readme to link to the new polkadot-docs
  README.md
  docs/contributor/DEPRECATION_CHECKLIST.md
  docs/mermaid/IA.mmd
  docs/sdk/src/external_resources.rs
  docs/sdk/src/lib.rs
  docs/sdk/src/meta_contributing.rs
  substrate/frame/alliance/Cargo.toml
Labels: R0-silent

#7520 Use rpc_port in bridge tests
  .gitlab/pipeline/zombienet.yml
  bridges/testing/environments/rococo-westend/bridge_hub_rococo_local_network.toml
  bridges/testing/environments/rococo-westend/bridge_hub_westend_local_network.toml
Labels: R0-silent, T10-tests, T15-bridges

#7524 ci: add evm-test-suite
  .github/workflows/tests-evm.yml
Labels: R0-silent

#7429 Warn about cargo remote not copying hidden file by default
  docs/sdk/src/reference_docs/development_environment_advice.rs
Labels: R0-silent

#7147 migrate zombie past slashing test
  .gitlab/pipeline/zombienet/polkadot.yml
  Cargo.lock
  polkadot/zombienet-sdk-tests/Cargo.toml
  polkadot/zombienet-sdk-tests/tests/disabling/mod.rs
  polkadot/zombienet-sdk-tests/tests/disabling/slashing.rs
  polkadot/zombienet-sdk-tests/tests/helpers/mod.rs
  polkadot/zombienet-sdk-tests/tests/lib.rs
  polkadot/zombienet_tests/functional/0005-parachains-disputes-past-session.toml
  polkadot/zombienet_tests/functional/0005-parachains-disputes-past-session.zndsl
Labels: R0-silent, T8-polkadot, T10-tests

#5990 On-demand credits
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/coretime.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/coretime.rs
  polkadot/runtime/parachains/src/assigner_coretime/tests.rs
  polkadot/runtime/parachains/src/coretime/benchmarking.rs
  polkadot/runtime/parachains/src/coretime/mod.rs
  polkadot/runtime/parachains/src/mock.rs
  polkadot/runtime/parachains/src/on_demand/benchmarking.rs
  polkadot/runtime/parachains/src/on_demand/mod.rs
  polkadot/runtime/parachains/src/on_demand/tests.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_parachains_coretime.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_parachains_on_demand.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_parachains_coretime.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_parachains_on_demand.rs
  polkadot/zombienet-sdk-tests/tests/smoke/coretime_revenue.rs
  prdoc/pr_5990.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/broker/src/benchmarking.rs
  substrate/frame/broker/src/dispatchable_impls.rs
  substrate/frame/broker/src/lib.rs
  substrate/frame/broker/src/mock.rs
  substrate/frame/broker/src/tests.rs
Labels: T2-pallets, T8-polkadot

#7548 Update some dependencies
  Cargo.lock
  Cargo.toml
  substrate/frame/support/test/tests/construct_runtime_ui/deprecated_where_block.stderr
  substrate/frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr
  substrate/frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen_unnamed.stderr
Labels: R0-silent, T17-primitives

#7552 Fix build-linux-substrate
  .github/workflows/build-publish-images.yml
Labels: R0-silent, I2-bug

#7529 Move zombienet cumulus pipeline to gha
  .github/workflows/zombienet-reusable-preflight.yml
  .github/workflows/zombienet_cumulus.yml
Labels: R0-silent, T10-tests

#7457 fix prdoc cmd
  .github/scripts/generate-prdoc.py
Labels: R0-silent

#7441 Update Scheduler to have a configurable block provider #7434
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_7441.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/democracy/src/tests.rs
  substrate/frame/referenda/src/mock.rs
  substrate/frame/scheduler/src/benchmarking.rs
  substrate/frame/scheduler/src/lib.rs
  substrate/frame/scheduler/src/migration.rs
  substrate/frame/scheduler/src/mock.rs
  substrate/frame/scheduler/src/tests.rs
Labels: T2-pallets

#7505 `fatxpool`: transaction statuses metrics added
  prdoc/pr_7505.prdoc
  substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/metrics.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/multi_view_listener.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/tx_mem_pool.rs
Labels: R0-silent, T0-node

#7554 sc-informant: Print full hash when debug logging is enabled
  prdoc/pr_7554.prdoc
  substrate/client/informant/src/display.rs
  substrate/client/informant/src/lib.rs
Labels: T0-node

#7353 Shorter availability data retention period for testnets
  cumulus/client/relay-chain-inprocess-interface/src/lib.rs
  polkadot/cli/src/cli.rs
  polkadot/cli/src/command.rs
  polkadot/node/core/av-store/src/lib.rs
  polkadot/node/core/av-store/src/tests.rs
  polkadot/node/service/src/lib.rs
  polkadot/node/subsystem-bench/src/lib/availability/av_store_helpers.rs
  polkadot/node/test/service/src/lib.rs
  polkadot/parachain/test-parachains/adder/collator/src/main.rs
  polkadot/parachain/test-parachains/undying/collator/src/main.rs
  prdoc/pr_7353.prdoc
Labels: T0-node

#7570 [pallet-revive] fix subxt version
  Cargo.lock
  Cargo.toml
  prdoc/pr_7570.prdoc
Labels: R0-silent, T7-smart_contracts

#7562 pallet-revive: Add env var to allow skipping of validation for testing
  prdoc/pr_7562.prdoc
  substrate/frame/revive/src/limits.rs
  substrate/frame/revive/src/wasm/mod.rs
Labels: T7-smart_contracts

#7571 frame-benchmarking: Improve macro hygiene
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_7571.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/benchmarking/src/v1.rs
  templates/parachain/runtime/src/apis.rs
  templates/solochain/runtime/src/apis.rs
Labels: T1-FRAME

#7455 cumulus-client: use only valid syntax in Cargo.toml
  cumulus/client/relay-chain-rpc-interface/Cargo.toml
Labels: R0-silent

#7418 refactor: Move `T:Config` into where clause in `#[benchmarks]` macro if needed
  prdoc/pr_7418.prdoc
  substrate/frame/support/procedural/src/benchmark.rs
Labels: T1-FRAME, T12-benchmarks

#7361 network/tests: Add conformance testing for litep2p and libp2p
  Cargo.lock
  substrate/client/network/test/Cargo.toml
  substrate/client/network/test/src/conformance/high_level.rs
  substrate/client/network/test/src/conformance/mod.rs
  substrate/client/network/test/src/conformance/setup.rs
  substrate/client/network/test/src/lib.rs
Labels: R0-silent, T10-tests

#7568 pallet-revive: Fix the contract size related benchmarks
  Cargo.lock
  prdoc/pr_7568.prdoc
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/fixtures/Cargo.toml
  substrate/frame/revive/fixtures/build/_Cargo.toml
  substrate/frame/revive/fixtures/contracts/caller_contract.rs
  substrate/frame/revive/src/benchmarking/code.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/limits.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/mod.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/src/weights.rs
  substrate/frame/revive/uapi/Cargo.toml
Labels: T7-smart_contracts

#6661 `txpool api`: `remove_invalid` call improved
  Cargo.lock
  prdoc/pr_6661.prdoc
  substrate/bin/node/bench/Cargo.toml
  substrate/bin/node/bench/src/construct.rs
  substrate/client/basic-authorship/src/basic_authorship.rs
  substrate/client/rpc-spec-v2/src/transaction/tests/middleware_pool.rs
  substrate/client/rpc-spec-v2/src/transaction/transaction_broadcast.rs
  substrate/client/rpc/src/author/mod.rs
  substrate/client/transaction-pool/api/Cargo.toml
  substrate/client/transaction-pool/api/src/lib.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/dropped_watcher.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/metrics.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/multi_view_listener.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/revalidation_worker.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/tx_mem_pool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/view.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs
  substrate/client/transaction-pool/src/graph/listener.rs
  substrate/client/transaction-pool/src/graph/pool.rs
  substrate/client/transaction-pool/src/graph/validated_pool.rs
  substrate/client/transaction-pool/src/single_state_txpool/revalidation.rs
  substrate/client/transaction-pool/src/single_state_txpool/single_state_txpool.rs
  substrate/client/transaction-pool/src/transaction_pool_wrapper.rs
  substrate/client/transaction-pool/tests/fatp.rs
  substrate/client/transaction-pool/tests/fatp_invalid.rs
Labels: R0-silent, T0-node

#7553 Add minor improvements to `chill_other` test
  substrate/frame/staking/src/tests.rs
Labels: R0-silent

#7320 Add view functions to Proxy pallet for runtime-specific type configuration #7297
  .gitignore
  prdoc/pr_7320.prdoc
  substrate/frame/proxy/src/lib.rs
Labels: T2-pallets

#7368 Add chain properties to chain-spec-builder
  prdoc/pr_7368.prdoc
  substrate/bin/utils/chain-spec-builder/src/lib.rs
  substrate/bin/utils/chain-spec-builder/tests/expected/create_with_properties.json
  substrate/bin/utils/chain-spec-builder/tests/test.rs
Labels: T0-node

#7376 Documentation update for weight. #7354
  prdoc/pr_7376.prdoc
  substrate/frame/support/src/lib.rs
Labels: R0-silent

#6321 `pallet-utility: if_else`
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_utility.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_utility.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_utility.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_utility.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_utility.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_utility.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/pallet_utility.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/pallet_utility.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/pallet_utility.rs
  polkadot/runtime/rococo/src/weights/pallet_utility.rs
  polkadot/runtime/westend/src/weights/pallet_utility.rs
  prdoc/pr_6321.prdoc
  substrate/frame/utility/src/benchmarking.rs
  substrate/frame/utility/src/lib.rs
  substrate/frame/utility/src/tests.rs
  substrate/frame/utility/src/weights.rs
Labels: T2-pallets

#4530 [Assets] Implement `pallet-assets-holder`
  Cargo.lock
  Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/xcm-builder/src/asset_exchange/single_asset_adapter/mock.rs
  polkadot/xcm/xcm-builder/src/tests/pay/mock.rs
  polkadot/xcm/xcm-runtime-apis/tests/mock.rs
  prdoc/pr_4530.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/asset-conversion/ops/src/mock.rs
  substrate/frame/asset-conversion/src/mock.rs
  substrate/frame/asset-rewards/src/mock.rs
  substrate/frame/asset-rewards/src/tests.rs
  substrate/frame/assets-freezer/src/impls.rs
  substrate/frame/assets-freezer/src/mock.rs
  substrate/frame/assets-freezer/src/tests.rs
  substrate/frame/assets-holder/Cargo.toml
  substrate/frame/assets-holder/src/impl_fungibles.rs
  substrate/frame/assets-holder/src/lib.rs
  substrate/frame/assets-holder/src/mock.rs
  substrate/frame/assets-holder/src/tests.rs
  substrate/frame/assets/src/functions.rs
  substrate/frame/assets/src/impl_fungibles.rs
  substrate/frame/assets/src/lib.rs
  substrate/frame/assets/src/mock.rs
  substrate/frame/assets/src/tests.rs
  substrate/frame/assets/src/types.rs
  substrate/frame/contracts/mock-network/src/parachain.rs
  substrate/frame/nft-fractionalization/src/mock.rs
  substrate/frame/revive/mock-network/src/parachain.rs
  substrate/frame/transaction-payment/asset-conversion-tx-payment/src/mock.rs
  substrate/frame/transaction-payment/asset-tx-payment/src/mock.rs
  umbrella/Cargo.toml
  umbrella/src/lib.rs
Labels: T2-pallets

#7563 Bump frame-metadata v16 to 19.0.0
  Cargo.lock
  Cargo.toml
  prdoc/pr_7563.prdoc
  substrate/primitives/metadata-ir/src/unstable.rs
Labels: T4-runtime_API

#7589 [pallet-revive] rpc add --earliest-receipt-block
  prdoc/pr_7589.prdoc
  substrate/frame/revive/rpc/src/cli.rs
  substrate/frame/revive/rpc/src/receipt_extractor.rs
  substrate/frame/revive/rpc/src/receipt_provider/db.rs
Labels: R0-silent, T7-smart_contracts

#2072 Change pallet referenda TracksInfo::tracks to return an iterator
  cumulus/parachains/runtimes/collectives/collectives-westend/src/ambassador/tracks.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/fellowship/tracks.rs
  polkadot/runtime/rococo/src/governance/fellowship.rs
  polkadot/runtime/rococo/src/governance/tracks.rs
  polkadot/runtime/westend/src/governance/tracks.rs
  prdoc/pr_2072.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/referenda/src/benchmarking.rs
  substrate/frame/referenda/src/lib.rs
  substrate/frame/referenda/src/mock.rs
  substrate/frame/referenda/src/tests.rs
  substrate/frame/referenda/src/types.rs
Labels: T2-pallets

#7579 [AHM] Make pallet types public
  polkadot/runtime/common/src/claims/mod.rs
  polkadot/xcm/xcm-simulator/fuzzer/src/parachain.rs
  prdoc/pr_7579.prdoc
  substrate/frame/asset-conversion/src/types.rs
  substrate/frame/assets-freezer/src/lib.rs
  substrate/frame/assets/src/lib.rs
  substrate/frame/assets/src/types.rs
  substrate/frame/authority-discovery/src/lib.rs
  substrate/frame/bags-list/src/lib.rs
  substrate/frame/bags-list/src/list/mod.rs
  substrate/frame/conviction-voting/src/lib.rs
  substrate/frame/core-fellowship/src/lib.rs
  substrate/frame/delegated-staking/src/lib.rs
  substrate/frame/fast-unstake/src/types.rs
  substrate/frame/multisig/src/lib.rs
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/preimage/src/lib.rs
  substrate/frame/proxy/src/lib.rs
  substrate/frame/recovery/src/lib.rs
  substrate/frame/salary/src/lib.rs
  substrate/frame/scheduler/src/lib.rs
  substrate/frame/society/src/lib.rs
  substrate/frame/treasury/src/lib.rs
  substrate/frame/uniques/src/lib.rs
  substrate/frame/uniques/src/types.rs
  substrate/frame/vesting/src/lib.rs
Labels: T2-pallets

#7494 libp2p: Enhance logging targets for granular control
  prdoc/pr_7494.prdoc
  substrate/client/network/src/discovery.rs
  substrate/client/network/src/protocol/notifications/behaviour.rs
  substrate/client/network/src/protocol/notifications/handler.rs
  substrate/client/network/src/protocol/notifications/service/mod.rs
  substrate/client/network/src/protocol/notifications/upgrade/notifications.rs
  substrate/client/network/src/request_responses.rs
  substrate/client/network/src/service.rs
Labels: T0-node

#7576 integration tests: add more emulated bridge tests
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
Labels: R0-silent, T10-tests, T15-bridges

#7580 implement web3_clientVersion
  Cargo.lock
  prdoc/pr_7580.prdoc
  substrate/frame/revive/rpc/Cargo.toml
  substrate/frame/revive/rpc/build.rs
  substrate/frame/revive/rpc/src/apis/execution_apis.rs
  substrate/frame/revive/rpc/src/lib.rs
Labels: R0-silent, T7-smart_contracts

#7014 Remove `yamux_window_size` from network config
  prdoc/pr_7014.prdoc
  substrate/client/cli/src/params/network_params.rs
  substrate/client/network/src/config.rs
  substrate/client/network/src/litep2p/mod.rs
Labels: T0-node

#7595 [Backport] [Release|CI/CD] Fix audiences changelog template (#6444)
  .github/workflows/release-30_publish_release_draft.yml
  scripts/release/templates/audience.md.tera
Labels: R0-silent, A3-backport

#7424 [Staking] Bounded Slashing: Paginated Offence Processing & Slash Application
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/runtime/westend/src/weights/pallet_staking.rs
  prdoc/pr_7424.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/babe/src/mock.rs
  substrate/frame/beefy/src/mock.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
  substrate/frame/grandpa/src/mock.rs
  substrate/frame/offences/benchmarking/src/inner.rs
  substrate/frame/offences/benchmarking/src/mock.rs
  substrate/frame/root-offences/src/lib.rs
  substrate/frame/root-offences/src/mock.rs
  substrate/frame/root-offences/src/tests.rs
  substrate/frame/session/benchmarking/src/mock.rs
  substrate/frame/staking/src/benchmarking.rs
  substrate/frame/staking/src/lib.rs
  substrate/frame/staking/src/migrations.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/slashing.rs
  substrate/frame/staking/src/tests.rs
  substrate/frame/staking/src/weights.rs
Labels: I4-refactor, T2-pallets

#7582 Implementation of ah-client and rc-client staking pallets
  Cargo.lock
  Cargo.toml
  prdoc/pr_7582.prdoc
  substrate/frame/election-provider-multi-block/src/lib.rs
  substrate/frame/staking/ah-client/Cargo.toml
  substrate/frame/staking/ah-client/src/lib.rs
  substrate/frame/staking/rc-client/Cargo.toml
  substrate/frame/staking/rc-client/src/lib.rs
  substrate/frame/staking/src/pallet/impls.rs
  umbrella/Cargo.toml
  umbrella/src/lib.rs
Labels: T2-pallets, T8-polkadot, R1-breaking_change

#7581 [AHM] Moves disabling logic into pallet-session
  cumulus/pallets/collator-selection/src/mock.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_7581.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/authority-discovery/src/lib.rs
  substrate/frame/babe/src/mock.rs
  substrate/frame/beefy-mmr/src/mock.rs
  substrate/frame/beefy/src/mock.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/lib.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
  substrate/frame/grandpa/src/mock.rs
  substrate/frame/im-online/src/mock.rs
  substrate/frame/offences/benchmarking/src/mock.rs
  substrate/frame/root-offences/src/mock.rs
  substrate/frame/session/benchmarking/src/mock.rs
  substrate/frame/session/src/disabling.rs
  substrate/frame/session/src/lib.rs
  substrate/frame/session/src/migrations/historical.rs
  substrate/frame/session/src/migrations/mod.rs
  substrate/frame/session/src/migrations/v1.rs
  substrate/frame/session/src/mock.rs
  substrate/frame/session/src/tests.rs
  substrate/frame/staking/src/lib.rs
  substrate/frame/staking/src/migrations.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/slashing.rs
  substrate/frame/staking/src/tests.rs
  templates/parachain/runtime/src/configs/mod.rs
Labels: I4-refactor, T2-pallets

#7543 Make all prdoc valid and add CI job to check prdoc with `prdoc check`
  .github/workflows/check-prdoc.yml
  prdoc/pr_6440.prdoc
  prdoc/pr_6455.prdoc
  prdoc/pr_6549.prdoc
  prdoc/pr_6636.prdoc
  prdoc/pr_6988.prdoc
Labels: R0-silent

#7511 feat(integration test) test omni node dev mod work with dev_json file
  docs/sdk/src/guides/your_first_node.rs
Labels: R0-silent

#7590 [pallet-revive] move exec tests
  prdoc/pr_7590.prdoc
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/exec/tests.rs
Labels: R0-silent, T7-smart_contracts

#7407 Fixes #219
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_utility.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_utility.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_utility.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_utility.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_utility.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_utility.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/pallet_utility.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/pallet_utility.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/pallet_utility.rs
  polkadot/runtime/rococo/src/weights/pallet_utility.rs
  polkadot/runtime/westend/src/weights/pallet_utility.rs
  prdoc/pr_7407.prdoc
  substrate/frame/utility/src/benchmarking.rs
  substrate/frame/utility/src/lib.rs
  substrate/frame/utility/src/tests.rs
  substrate/frame/utility/src/weights.rs
Labels: T2-pallets

#7423 Fix issue with InitiateTransfer and UnpaidExecution
  polkadot/xcm/xcm-builder/src/barriers.rs
  polkadot/xcm/xcm-builder/src/matcher.rs
  polkadot/xcm/xcm-builder/src/tests/barriers.rs
  polkadot/xcm/xcm-builder/src/tests/mock.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  polkadot/xcm/xcm-executor/src/tests/initiate_transfer.rs
  polkadot/xcm/xcm-executor/src/tests/mock.rs
  prdoc/pr_7423.prdoc
Labels: T6-XCM, A4-needs-backport

#7518 ci: don't run CI on draft PRs
  .github/workflows/benchmarks-subsystem.yml
  .github/workflows/build-misc.yml
  .github/workflows/build-publish-eth-rpc.yml
  .github/workflows/build-publish-images.yml
  .github/workflows/check-cargo-check-runtimes.yml
  .github/workflows/check-frame-omni-bencher.yml
  .github/workflows/check-getting-started.yml
  .github/workflows/check-licenses.yml
  .github/workflows/check-links.yml
  .github/workflows/check-runtime-migration.yml
  .github/workflows/check-semver.yml
  .github/workflows/checks-quick.yml
  .github/workflows/checks.yml
  .github/workflows/cmd-tests.yml
  .github/workflows/docs.yml
  .github/workflows/gitspiegel-trigger.yml
  .github/workflows/publish-check-compile.yml
  .github/workflows/publish-check-crates.yml
  .github/workflows/reusable-isdraft.yml
  .github/workflows/tests-evm.yml
  .github/workflows/tests-linux-stable.yml
  .github/workflows/tests-misc.yml
  .github/workflows/tests.yml
  .github/workflows/zombienet_cumulus.yml
  .github/workflows/zombienet_substrate.yml
Labels: R0-silent

#7599 Fix link-checker reloaded
  .config/lychee.toml
Labels: R0-silent

#7549 Bridges: Remove obsolete relayer CLI args: host, port, path, secure
  bridges/relays/client-substrate/src/client/rpc.rs
  bridges/relays/client-substrate/src/lib.rs
  bridges/relays/lib-substrate-relay/src/cli/chain_schema.rs
  bridges/relays/lib-substrate-relay/src/cli/relay_headers_and_messages/mod.rs
  bridges/testing/environments/rococo-westend/bridges_rococo_westend.sh
  bridges/testing/scripts/start-relayer.sh
Labels: R0-silent, T15-bridges

#7608 [Release/CI|CD] Fix for the branch-off pipeline
  .github/workflows/release-10_branchoff-stable.yml
Labels: R0-silent, D0-easy

#7612 HashAndNumber: Ord, Eq, PartialOrd, PartialEq implemented
  prdoc/pr_7612.prdoc
  substrate/primitives/blockchain/src/header_metadata.rs
Labels: R0-silent, T0-node

#7200 XCM: Deny barrier checks for nested XCMs with specific instructions to be executed on the local chain
  Cargo.lock
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/people/people-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/people/people-westend/src/xcm_config.rs
  polkadot/xcm/xcm-builder/Cargo.toml
  polkadot/xcm/xcm-builder/src/barriers.rs
  polkadot/xcm/xcm-builder/src/lib.rs
  polkadot/xcm/xcm-builder/src/tests/barriers.rs
  polkadot/xcm/xcm-builder/tests/scenarios.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  prdoc/pr_7200.prdoc
  templates/parachain/runtime/src/configs/xcm_config.rs
Labels: T6-XCM, C1-mentor, C2-good-first-issue

#7476 add genesis presets for coretime parachains
  .github/workflows/runtimes-matrix.json
  Cargo.lock
  cumulus/parachains/runtimes/coretime/coretime-rococo/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/genesis_config_presets.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-westend/src/genesis_config_presets.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/polkadot-parachain/src/chain_spec/coretime.rs
  prdoc/pr_7476.prdoc
Labels: T14-system_parachains

#7630 backport/2412: Increase litep2p keep-alive to 10 seconds to mirror libp2p
  prdoc/pr_7488.prdoc
  substrate/client/network/src/litep2p/mod.rs
Labels: A3-backport

#7026 [pallet-broker] add extrinsic to remove a lease
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_broker.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/pallet_broker.rs
  prdoc/pr_7026.prdoc
  substrate/frame/broker/src/benchmarking.rs
  substrate/frame/broker/src/dispatchable_impls.rs
  substrate/frame/broker/src/lib.rs
  substrate/frame/broker/src/tests.rs
  substrate/frame/broker/src/weights.rs
Labels: T2-pallets

#7080 [pallet-broker] add extrinsic to remove an assignment
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_broker.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/pallet_broker.rs
  prdoc/pr_7080.prdoc
  substrate/frame/broker/src/benchmarking.rs
  substrate/frame/broker/src/dispatchable_impls.rs
  substrate/frame/broker/src/lib.rs
  substrate/frame/broker/src/tests.rs
  substrate/frame/broker/src/weights.rs
Labels: T2-pallets

#6960 Add sudo pallet to coretime-westend
  Cargo.lock
  cumulus/parachains/runtimes/coretime/coretime-westend/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  prdoc/pr_6960.prdoc
Labels: T14-system_parachains

#7616 Revert "[Assets] Implement `pallet-assets-holder` (#4530)" for stable 2503
  Cargo.lock
  Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/xcm-builder/src/asset_exchange/single_asset_adapter/mock.rs
  polkadot/xcm/xcm-builder/src/tests/pay/mock.rs
  polkadot/xcm/xcm-runtime-apis/tests/mock.rs
  prdoc/stable2503/pr_4530.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/asset-conversion/ops/src/mock.rs
  substrate/frame/asset-conversion/src/mock.rs
  substrate/frame/asset-rewards/src/mock.rs
  substrate/frame/asset-rewards/src/tests.rs
  substrate/frame/assets-freezer/src/impls.rs
  substrate/frame/assets-freezer/src/mock.rs
  substrate/frame/assets-freezer/src/tests.rs
  substrate/frame/assets-holder/Cargo.toml
  substrate/frame/assets-holder/src/impl_fungibles.rs
  substrate/frame/assets-holder/src/lib.rs
  substrate/frame/assets-holder/src/mock.rs
  substrate/frame/assets-holder/src/tests.rs
  substrate/frame/assets/src/functions.rs
  substrate/frame/assets/src/impl_fungibles.rs
  substrate/frame/assets/src/lib.rs
  substrate/frame/assets/src/mock.rs
  substrate/frame/assets/src/tests.rs
  substrate/frame/assets/src/types.rs
  substrate/frame/contracts/mock-network/src/parachain.rs
  substrate/frame/nft-fractionalization/src/mock.rs
  substrate/frame/revive/mock-network/src/parachain.rs
  substrate/frame/transaction-payment/asset-conversion-tx-payment/src/mock.rs
  substrate/frame/transaction-payment/asset-tx-payment/src/mock.rs
  umbrella/Cargo.toml
  umbrella/src/lib.rs
Labels: R0-silent, A3-backport, T2-pallets

#7617 Add stable2503 branch
  .github/workflows/command-backport.yml
Labels: R0-silent, D0-easy

#7634 derive `DecodeWithMemTracking` for `RuntimeCall`
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/bridge_common_config.rs
  prdoc/pr_7634.prdoc
  substrate/frame/support/procedural/src/construct_runtime/expand/call.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/freeze_reason.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/hold_reason.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/lock_id.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/origin.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/outer_enums.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/slash_reason.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/task.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/view_function.rs
  substrate/frame/support/procedural/src/dynamic_params.rs
  substrate/frame/support/procedural/src/pallet/expand/call.rs
  substrate/frame/support/procedural/src/pallet/expand/error.rs
  substrate/frame/support/procedural/src/pallet/expand/event.rs
  substrate/frame/support/procedural/src/pallet/expand/tasks.rs
  substrate/frame/support/procedural/src/pallet/expand/view_functions.rs
  substrate/frame/support/procedural/src/pallet/parse/composite.rs
  substrate/frame/support/test/tests/construct_runtime_ui/pallet_error_too_large.rs
  substrate/frame/support/test/tests/construct_runtime_ui/pallet_error_too_large.stderr
  substrate/frame/support/test/tests/pallet_ui/call_argument_invalid_bound_3.rs
  substrate/frame/support/test/tests/pallet_ui/error_does_not_derive_pallet_error.rs
  substrate/frame/support/test/tests/pallet_ui/pass/error_nested_types.rs
Labels: T17-primitives

#7640 net/litep2p: Bring the latest compatibility fixes via v0.9.1
  Cargo.lock
  Cargo.toml
  prdoc/pr_7640.prdoc
  substrate/client/network/src/litep2p/mod.rs
  substrate/client/network/src/protocol.rs
Labels: T0-node, A4-needs-backport

#7587 [AHM] Poke deposits: Indices pallet
  polkadot/runtime/rococo/src/weights/pallet_indices.rs
  polkadot/runtime/westend/src/weights/pallet_indices.rs
  prdoc/pr_7587.prdoc
  substrate/frame/indices/src/benchmarking.rs
  substrate/frame/indices/src/lib.rs
  substrate/frame/indices/src/mock.rs
  substrate/frame/indices/src/tests.rs
  substrate/frame/indices/src/weights.rs
Labels: T1-FRAME, T2-pallets

#7477 add genesis presets for the people chains
  .github/workflows/runtimes-matrix.json
  Cargo.lock
  cumulus/parachains/runtimes/people/people-rococo/Cargo.toml
  cumulus/parachains/runtimes/people/people-rococo/src/genesis_config_presets.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/Cargo.toml
  cumulus/parachains/runtimes/people/people-westend/src/genesis_config_presets.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/polkadot-parachain/src/chain_spec/people.rs
  prdoc/pr_7477.prdoc
Labels: R0-silent

#7659 remove redundant 0016-approval-voting-parallel test
  .gitlab/pipeline/zombienet/polkadot.yml
  polkadot/zombienet_tests/functional/0016-approval-voting-parallel.toml
  polkadot/zombienet_tests/functional/0016-approval-voting-parallel.zndsl
Labels: R0-silent

#7003 xcm-builder: added logging for xcm filters/helpers/matchers/types (#2408)
  Cargo.lock
  cumulus/parachains/runtimes/assets/common/Cargo.toml
  cumulus/parachains/runtimes/assets/common/src/benchmarks.rs
  cumulus/parachains/runtimes/assets/common/src/foreign_creators.rs
  cumulus/parachains/runtimes/assets/common/src/fungible_conversion.rs
  cumulus/parachains/runtimes/assets/common/src/lib.rs
  cumulus/parachains/runtimes/assets/common/src/matching.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/xcm_config.rs
  polkadot/xcm/xcm-builder/Cargo.toml
  polkadot/xcm/xcm-builder/src/asset_exchange/single_asset_adapter/adapter.rs
  polkadot/xcm/xcm-builder/src/barriers.rs
  polkadot/xcm/xcm-builder/src/currency_adapter.rs
  polkadot/xcm/xcm-builder/src/fee_handling.rs
  polkadot/xcm/xcm-builder/src/filter_asset_location.rs
  polkadot/xcm/xcm-builder/src/fungible_adapter.rs
  polkadot/xcm/xcm-builder/src/fungibles_adapter.rs
  polkadot/xcm/xcm-builder/src/lib.rs
  polkadot/xcm/xcm-builder/src/location_conversion.rs
  polkadot/xcm/xcm-builder/src/nonfungible_adapter.rs
  polkadot/xcm/xcm-builder/src/nonfungibles_adapter.rs
  polkadot/xcm/xcm-builder/src/origin_conversion.rs
  polkadot/xcm/xcm-builder/src/process_xcm_message.rs
  polkadot/xcm/xcm-builder/src/routing.rs
  polkadot/xcm/xcm-builder/src/weight.rs
  prdoc/pr_7003.prdoc
Labels: T6-XCM

#7670 Bandersnatch hot fix
  Cargo.lock
  substrate/frame/sassafras/src/data/25_tickets_100_auths.bin
  substrate/primitives/core/Cargo.toml
Labels: R0-silent, A4-needs-backport

#7619 effort towards getting chainspecbuilder into omni-node fix 5567
  Cargo.lock
  cumulus/polkadot-omni-node/lib/Cargo.toml
  cumulus/polkadot-omni-node/lib/src/cli.rs
  cumulus/polkadot-omni-node/lib/src/command.rs
  prdoc/pr_7619.prdoc
  substrate/bin/utils/chain-spec-builder/src/lib.rs
Labels: I5-enhancement, T9-cumulus

#7594 Enhance XCM Debugging with Log Capture in Unit Tests
  polkadot/xcm/xcm-simulator/example/Cargo.toml
  polkadot/xcm/xcm-simulator/example/src/tests.rs
  prdoc/pr_7594.prdoc
  substrate/primitives/tracing/Cargo.toml
  substrate/primitives/tracing/src/lib.rs
Labels: T6-XCM, T10-tests

#7438 Fix DryRunApi client-facing XCM versions
  Cargo.lock
  cumulus/pallets/xcmp-queue/Cargo.toml
  cumulus/pallets/xcmp-queue/src/lib.rs
  cumulus/parachains/integration-tests/emulated/common/src/macros.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/xcm_fee_estimation.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/xcm_fee_estimation.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  polkadot/node/service/Cargo.toml
  polkadot/node/service/src/fake_runtime_api.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  polkadot/xcm/Cargo.toml
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/src/lib.rs
  polkadot/xcm/xcm-runtime-apis/Cargo.toml
  polkadot/xcm/xcm-runtime-apis/src/dry_run.rs
  polkadot/xcm/xcm-runtime-apis/tests/fee_estimation.rs
  polkadot/xcm/xcm-runtime-apis/tests/mock.rs
  prdoc/pr_7438.prdoc
Labels: T6-XCM, T4-runtime_API, A4-needs-backport

#7649 optional rocksdb for frame-benchmarking-cli
  cumulus/client/cli/Cargo.toml
  cumulus/client/relay-chain-inprocess-interface/Cargo.toml
  cumulus/polkadot-omni-node/lib/Cargo.toml
  polkadot/node/metrics/Cargo.toml
  prdoc/pr_7649.prdoc
  substrate/client/cli/Cargo.toml
  substrate/test-utils/cli/Cargo.toml
  substrate/test-utils/client/Cargo.toml
  substrate/utils/frame/benchmarking-cli/Cargo.toml
Labels: T0-node

#7641 XCM: Process PayFees only once
  polkadot/xcm/src/v5/mod.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  polkadot/xcm/xcm-executor/src/tests/mock.rs
  polkadot/xcm/xcm-executor/src/tests/pay_fees.rs
  prdoc/pr_7641.prdoc
Labels: T6-XCM, A4-needs-backport

#7676 [pallet-revive] tracing should wrap around call stack execution
  prdoc/pr_7676.prdoc
  substrate/frame/revive/src/exec.rs
Labels: R0-silent, T7-smart_contracts

#7643 deps: remove unused feature `subxt/substrate-compat`
  Cargo.lock
  polkadot/zombienet-sdk-tests/Cargo.toml
Labels: A1-insubstantial, R0-silent

#7697 updated substrate-relay to v1.8.0
  bridges/testing/environments/rococo-westend/bridges_rococo_westend.sh
  cumulus/parachains/runtimes/bridge-hubs/README.md
  docker/dockerfiles/bridges_zombienet_tests_injected.Dockerfile
Labels: R0-silent, T15-bridges

#7637 Expose extension weights
  prdoc/pr_7637.prdoc
  substrate/frame/system/src/lib.rs
Labels: T2-pallets

#7607 Add Runtime Api version to metadata
  Cargo.lock
  Cargo.toml
  prdoc/pr_7607.prdoc
  substrate/frame/examples/view-functions/src/tests.rs
  substrate/frame/support/procedural/src/pallet/expand/view_functions.rs
  substrate/frame/support/test/tests/runtime_metadata.rs
  substrate/primitives/api/proc-macro/src/runtime_metadata.rs
  substrate/primitives/metadata-ir/src/types.rs
  substrate/primitives/metadata-ir/src/unstable.rs
Labels: T4-runtime_API

#7638 remove leftovers of the contracts-rococo parachain
  .github/workflows/release-30_publish_release_draft.yml
  .github/workflows/runtimes-matrix.json
  Cargo.lock
  Cargo.toml
  cumulus/README.md
  cumulus/parachains/chain-specs/contracts-rococo.json
  cumulus/parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  cumulus/parachains/runtimes/contracts/contracts-rococo/README.md
  cumulus/parachains/runtimes/contracts/contracts-rococo/build.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/contracts-overview.svg
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/contracts.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/weights/block_weights.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/weights/extrinsic_weights.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/weights/mod.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/weights/pallet_message_queue.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/weights/paritydb_weights.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/weights/rocksdb_weights.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/tests/tests.rs
Labels: R0-silent

#7481 add genesis presets for glutton westend
  .github/workflows/runtimes-matrix.json
  Cargo.lock
  cumulus/parachains/runtimes/glutton/glutton-westend/Cargo.toml
  cumulus/parachains/runtimes/glutton/glutton-westend/src/genesis_config_presets.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/polkadot-parachain/src/chain_spec/glutton.rs
  cumulus/polkadot-parachain/src/chain_spec/mod.rs
  prdoc/pr_7481.prdoc
Labels: R0-silent

#6615 Migration of polkadot-runtime-common crowdloan benchmarking to v2
  polkadot/runtime/common/src/crowdloan/mod.rs
Labels: R0-silent, T2-pallets, T12-benchmarks

#7712 Add `pallet-revive` to penpal westend runtime
  Cargo.lock
  cumulus/parachains/runtimes/testing/penpal/Cargo.toml
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
Labels: R0-silent, T6-XCM, T7-smart_contracts, T10-tests

#6606 Migrating polkadot-runtime-parachains paras_inherent benchmarking to V2
  polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs
Labels: R0-silent, T2-pallets, T12-benchmarks

#7652 [pallet-revive] ecrecover
  prdoc/pr_7652.prdoc
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/fixtures/contracts/call_and_return.rs
  substrate/frame/revive/fixtures/contracts/ecdsa_recover.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/pure_precompiles.rs
  substrate/frame/revive/src/pure_precompiles/ecrecover.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv64.rs
Labels: R0-silent, T7-smart_contracts

#7729 [pallet-revive] allow delegate calls to non-contract accounts
  prdoc/pr_7729.prdoc
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/exec/tests.rs
Labels: R0-silent, T7-smart_contracts

#7685 [Nomination Pool] Make staking restrictions configurable
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_7685.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/delegated-staking/src/lib.rs
  substrate/frame/delegated-staking/src/mock.rs
  substrate/frame/delegated-staking/src/tests.rs
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
  substrate/frame/nomination-pools/benchmarking/src/mock.rs
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/nomination-pools/src/mock.rs
  substrate/frame/nomination-pools/src/tests.rs
  substrate/frame/nomination-pools/test-delegate-stake/src/mock.rs
  substrate/frame/staking/src/lib.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/tests.rs
Labels: T1-FRAME, T2-pallets

#7585 feat(collator) add export pov on slot base collator
  cumulus/client/consensus/aura/src/collators/lookahead.rs
  cumulus/client/consensus/aura/src/collators/slot_based/collation_task.rs
  cumulus/client/consensus/aura/src/collators/slot_based/mod.rs
  cumulus/client/consensus/aura/src/lib.rs
  cumulus/polkadot-omni-node/lib/src/nodes/aura.rs
  cumulus/test/service/src/lib.rs
  prdoc/pr_7585.prdoc
Labels: T0-node

#7484 notifications/tests: Check compatiblity between litep2p and libp2p
  substrate/client/network/src/protocol/notifications/tests/conformance.rs
  substrate/client/network/src/protocol/notifications/tests/mod.rs
Labels: R0-silent, T10-tests

#7744 [Backport] Version bumps form stable2412-2
  cumulus/polkadot-omni-node/lib/src/nodes/mod.rs
  polkadot/node/primitives/src/lib.rs
  prdoc/stable2412-2/pr_7243.prdoc
  prdoc/stable2412-2/pr_7307.prdoc
  prdoc/stable2412-2/pr_7365.prdoc
  prdoc/stable2412-2/pr_7367.prdoc
  prdoc/stable2412-2/pr_7383.prdoc
  prdoc/stable2412-2/pr_7451.prdoc
  prdoc/stable2412-2/pr_7488.prdoc
  prdoc/stable2412-2/pr_7504.prdoc
  prdoc/stable2412-2/pr_7605.prdoc
  prdoc/stable2412-2/pr_7640.prdoc
Labels: R0-silent, A3-backport, D0-easy

#7700 [AHM] Poke deposits: Multisig pallet
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_multisig.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_multisig.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_multisig.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_multisig.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_multisig.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/weights/pallet_multisig.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_multisig.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/pallet_multisig.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/pallet_multisig.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/pallet_multisig.rs
  polkadot/runtime/rococo/src/weights/pallet_multisig.rs
  polkadot/runtime/westend/src/weights/pallet_multisig.rs
  prdoc/pr_7700.prdoc
  substrate/frame/multisig/src/benchmarking.rs
  substrate/frame/multisig/src/lib.rs
  substrate/frame/multisig/src/tests.rs
  substrate/frame/multisig/src/weights.rs
Labels: T1-FRAME, T2-pallets

#7734 Simplify event assertion with predicate-based check
  polkadot/xcm/xcm-simulator/example/src/tests.rs
  prdoc/pr_7734.prdoc
Labels: T6-XCM, T10-tests

#7745 [Release|CI/CD] Update pgpgkms to the latest version
  .github/workflows/release-10_branchoff-stable.yml
  .github/workflows/release-11_rc-automation.yml
  .github/workflows/release-40_publish-deb-package.yml
  .github/workflows/release-reusable-rc-buid.yml
Labels: R0-silent, A4-needs-backport

#7662 pallet_revive: Change address derivation to use hashing
  Cargo.lock
  prdoc/pr_7662.prdoc
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/fixtures/contracts/terminate_and_send_to_argument.rs
  substrate/frame/revive/src/address.rs
  substrate/frame/revive/src/evm/api/byte.rs
  substrate/frame/revive/src/evm/api/hex_serde.rs
  substrate/frame/revive/src/evm/api/rlp_codec.rs
  substrate/frame/revive/src/evm/api/signature.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/test_utils.rs
  substrate/frame/revive/src/tests.rs
Labels: T7-smart_contracts

#7750 Remove leftovers of leftovers of contracts-rococo
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/weights/cumulus_pallet_parachain_system.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/weights/cumulus_pallet_weight_reclaim.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/weights/frame_system.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/weights/frame_system_extensions.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/weights/pallet_balances.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/weights/pallet_collator_selection.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/weights/pallet_contracts.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/weights/pallet_multisig.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/weights/pallet_session.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/weights/pallet_sudo.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/weights/pallet_timestamp.rs
  cumulus/parachains/runtimes/contracts/contracts-rococo/src/weights/pallet_utility.rs
Labels: R0-silent, T9-cumulus

#7724 notifications/libp2p: Terminate the outbound notification substream on `std::io::Errors`
  prdoc/pr_7724.prdoc
  substrate/client/network/src/protocol/notifications/behaviour.rs
  substrate/client/network/src/protocol/notifications/handler.rs
  substrate/client/network/src/protocol/notifications/upgrade/notifications.rs
Labels: T0-node
