Repository paritytech/polkadot-sdk, pull requests merged in 2025-09, with the labels that each got.

#9285 [revive] revm backend
  .github/workflows/tests-misc.yml
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  prdoc/pr_9285.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/revive/fixtures/build.rs
  substrate/frame/revive/fixtures/contracts/Fibonacci.sol
  substrate/frame/revive/src/benchmarking.rs
  substrate/frame/revive/src/call_builder.rs
  substrate/frame/revive/src/evm/runtime.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/exec/mock_ext.rs
  substrate/frame/revive/src/exec/tests.rs
  substrate/frame/revive/src/gas.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/limits.rs
  substrate/frame/revive/src/migrations.rs
  substrate/frame/revive/src/migrations/v2.rs
  substrate/frame/revive/src/primitives.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/tests/pvm.rs
  substrate/frame/revive/src/tests/sol.rs
  substrate/frame/revive/src/tracing.rs
  substrate/frame/revive/src/vm/evm.rs
  substrate/frame/revive/src/vm/evm/instructions/arithmetic.rs
  substrate/frame/revive/src/vm/evm/instructions/bitwise.rs
  substrate/frame/revive/src/vm/evm/instructions/block_info.rs
  substrate/frame/revive/src/vm/evm/instructions/contract.rs
  substrate/frame/revive/src/vm/evm/instructions/contract/call_helpers.rs
  substrate/frame/revive/src/vm/evm/instructions/control.rs
  substrate/frame/revive/src/vm/evm/instructions/host.rs
  substrate/frame/revive/src/vm/evm/instructions/i256.rs
  substrate/frame/revive/src/vm/evm/instructions/macros.rs
  substrate/frame/revive/src/vm/evm/instructions/memory.rs
  substrate/frame/revive/src/vm/evm/instructions/mod.rs
  substrate/frame/revive/src/vm/evm/instructions/stack.rs
  substrate/frame/revive/src/vm/evm/instructions/system.rs
  substrate/frame/revive/src/vm/evm/instructions/tx_info.rs
  substrate/frame/revive/src/vm/evm/instructions/utility.rs
  substrate/frame/revive/src/vm/mod.rs
  substrate/frame/revive/src/vm/pvm.rs
  substrate/frame/revive/src/vm/pvm/env.rs
  substrate/frame/revive/src/vm/runtime_costs.rs
  substrate/frame/revive/src/weights.rs
Labels: T7-smart_contracts

#9414 [pallet-revive] EVM backend: Implement tx, block system and call stack instructions
  prdoc/pr_9414.prdoc
  substrate/frame/revive/fixtures/contracts/BlockInfo.sol
  substrate/frame/revive/fixtures/contracts/Callee.sol
  substrate/frame/revive/fixtures/contracts/Caller.sol
  substrate/frame/revive/fixtures/contracts/Dummy.sol
  substrate/frame/revive/fixtures/contracts/Host.sol
  substrate/frame/revive/fixtures/contracts/System.sol
  substrate/frame/revive/fixtures/contracts/TransactionInfo.sol
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/exec/mock_ext.rs
  substrate/frame/revive/src/exec/tests.rs
  substrate/frame/revive/src/limits.rs
  substrate/frame/revive/src/tests/sol.rs
  substrate/frame/revive/src/tests/sol/block_info.rs
  substrate/frame/revive/src/tests/sol/contract.rs
  substrate/frame/revive/src/tests/sol/system.rs
  substrate/frame/revive/src/tests/sol/tx_info.rs
  substrate/frame/revive/src/vm/evm.rs
  substrate/frame/revive/src/vm/evm/instructions/arithmetic.rs
  substrate/frame/revive/src/vm/evm/instructions/block_info.rs
  substrate/frame/revive/src/vm/evm/instructions/contract.rs
  substrate/frame/revive/src/vm/evm/instructions/contract/call_helpers.rs
  substrate/frame/revive/src/vm/evm/instructions/host.rs
  substrate/frame/revive/src/vm/evm/instructions/macros.rs
  substrate/frame/revive/src/vm/evm/instructions/memory.rs
  substrate/frame/revive/src/vm/evm/instructions/system.rs
  substrate/frame/revive/src/vm/evm/instructions/tx_info.rs
  substrate/frame/revive/src/vm/mod.rs
  substrate/frame/revive/src/vm/pvm.rs
Labels: R0-no-crate-publish-required, T7-smart_contracts

#9451 Call SingleBlockMigrations from frame_system::Config on try_on_runtime_upgrade
  prdoc/pr_9451.prdoc
  substrate/frame/executive/src/lib.rs
  substrate/frame/executive/src/tests.rs
  templates/parachain/runtime/src/configs/mod.rs
  templates/parachain/runtime/src/lib.rs
  templates/solochain/runtime/src/configs/mod.rs
  templates/solochain/runtime/src/lib.rs
Labels: A4-backport-stable2506, A4-backport-unstable2507

#9587 bump zombienet-sdk and subxt versions
  Cargo.lock
  Cargo.toml
  cumulus/zombienet/zombienet-sdk-helpers/src/lib.rs
  cumulus/zombienet/zombienet-sdk/tests/zombie_ci/statement_store.rs
  polkadot/zombienet-sdk-tests/Cargo.toml
  polkadot/zombienet-sdk-tests/tests/disabling/slashing.rs
  polkadot/zombienet-sdk-tests/tests/elastic_scaling/doesnt_break_parachains.rs
  polkadot/zombienet-sdk-tests/tests/functional/validator_disabling.rs
  substrate/frame/migrations/src/mock_helpers.rs
  substrate/frame/revive/rpc/src/client.rs
  substrate/utils/frame/benchmarking-cli/src/overhead/remark_builder.rs
Labels: R0-no-crate-publish-required, T10-tests, T18-zombienet_tests

#9581 fix: parachain informant
  cumulus/client/service/src/lib.rs
  prdoc/pr_9581.prdoc
Labels: T9-cumulus, A4-backport-stable2506

#9002 Forward `CoreInfo` via an digest to the runtime
  Cargo.lock
  cumulus/client/consensus/aura/src/collators/lookahead.rs
  cumulus/client/consensus/aura/src/collators/mod.rs
  cumulus/client/consensus/aura/src/collators/slot_based/block_builder_task.rs
  cumulus/client/consensus/aura/src/collators/slot_based/collation_task.rs
  cumulus/client/consensus/aura/src/collators/slot_based/mod.rs
  cumulus/client/consensus/aura/src/collators/slot_based/relay_chain_data_cache.rs
  cumulus/client/consensus/aura/src/collators/slot_based/tests.rs
  cumulus/pallets/aura-ext/src/test.rs
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/parachain-system/src/mock.rs
  cumulus/pallets/parachain-system/src/tests.rs
  cumulus/pallets/parachain-system/src/validate_block/implementation.rs
  cumulus/pallets/parachain-system/src/validate_block/tests.rs
  cumulus/pallets/xcmp-queue/src/mock.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  cumulus/parachains/runtimes/testing/rococo-parachain/src/lib.rs
  cumulus/parachains/runtimes/testing/yet-another-parachain/src/lib.rs
  cumulus/polkadot-omni-node/lib/src/common/mod.rs
  cumulus/polkadot-omni-node/lib/src/fake_runtime_api/utils.rs
  cumulus/primitives/core/src/lib.rs
  cumulus/test/client/src/block_builder.rs
  cumulus/test/client/src/lib.rs
  cumulus/test/runtime/src/lib.rs
  cumulus/test/runtime/src/test_pallet.rs
  cumulus/test/service/benches/validate_block.rs
  cumulus/test/service/benches/validate_block_glutton.rs
  cumulus/test/service/src/chain_spec.rs
  cumulus/test/service/src/lib.rs
  docs/sdk/src/guides/handling_parachain_forks.rs
  docs/sdk/src/polkadot_sdk/cumulus.rs
  polkadot/node/subsystem-util/src/runtime/mod.rs
  polkadot/parachain/Cargo.toml
  polkadot/parachain/src/primitives.rs
  prdoc/pr_9002.prdoc
  substrate/frame/staking-async/runtimes/parachain/src/lib.rs
  templates/parachain/runtime/src/configs/mod.rs
Labels: T0-node, T9-cumulus, A4-backport-stable2509

#9676 [backport] Regular version bumps from the stable2506-2
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/polkadot-omni-node/lib/src/nodes/mod.rs
  polkadot/node/primitives/src/lib.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/stable2506-2/pr_9451.prdoc
  prdoc/stable2506-2/pr_9514.prdoc
  prdoc/stable2506-2/pr_9516.prdoc
  prdoc/stable2506-2/pr_9544.prdoc
  prdoc/stable2506-2/pr_9564.prdoc
  prdoc/stable2506-2/pr_9581.prdoc
Labels: R0-no-crate-publish-required, A3-backport

#9682 [Release|CI/CD] Fix macos build in release pipeline
  .github/workflows/release-reusable-rc-build.yml
Labels: R0-no-crate-publish-required

#9677 Update elastic scaling documentation
  docs/sdk/src/guides/enable_elastic_scaling.rs
  docs/sdk/src/guides/enable_elastic_scaling_mvp.rs
  docs/sdk/src/guides/mod.rs
  prdoc/pr_9677.prdoc
Labels: T11-documentation, A4-backport-stable2509

#9731 Simulate `rank_to_votes` in `pallet-ranked-collective` benchmark.
  prdoc/pr_9731.prdoc
  substrate/frame/ranked-collective/src/benchmarking.rs
Labels: T1-FRAME, A4-backport-stable2409, A4-backport-stable2506, A4-backport-unstable2507

#9744 [pallet-revive] fix CodeInfo owner
  prdoc/pr_9744.prdoc
  substrate/frame/revive/fixtures/contracts/CallerWithConstructor.sol
  substrate/frame/revive/fixtures/src/lib.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/test_utils/builder.rs
  substrate/frame/revive/src/tests/sol/contract.rs
Labels: T7-smart_contracts

#9747 staking-async: handle uninitialized state in try-state checks
  prdoc/pr_9747.prdoc
  substrate/frame/staking-async/src/pallet/impls.rs
  substrate/frame/staking-async/src/tests/mod.rs
  substrate/frame/staking-async/src/tests/try_state.rs
Labels: T2-pallets, A4-backport-unstable2507, A4-backport-stable2509

#9742 `frame-support`: Move all macros from `lib.rs` to a new file
  substrate/frame/support/src/lib.rs
  substrate/frame/support/src/macros.rs
Labels: R0-no-crate-publish-required

#9701 revive-rpc: use generic RpcClient instead of ReconnectingRpcClient
  prdoc/pr_9701.prdoc
  substrate/frame/revive/rpc/src/client.rs
Labels: T7-smart_contracts

#9753 Fix Aura authorities tracker bug
  cumulus/client/consensus/aura/src/equivocation_import_queue.rs
  prdoc/pr_9753.prdoc
  substrate/client/consensus/aura/src/authorities_tracker.rs
  substrate/client/consensus/aura/src/import_queue.rs
Labels: T9-cumulus

#9757 ci: switch tests to new runners
  .github/workflows/reusable-preflight.yml
  .github/workflows/tests-linux-stable-xp.yml
  .github/workflows/tests-linux-stable.yml
Labels: R0-no-crate-publish-required

#9732 Remove the deprecated `CheckInherents` logic
  cumulus/pallets/aura-ext/src/lib.rs
  cumulus/pallets/parachain-system/proc-macro/src/lib.rs
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/parachain-system/src/validate_block/implementation.rs
  cumulus/pallets/parachain-system/src/validate_block/tests.rs
  prdoc/pr_9732.prdoc
Labels: T9-cumulus

#9752 [unstable2507] Post crates release changes
  Cargo.lock
  Plan.toml
  prdoc/unstable2507/pr_9747.prdoc
  substrate/frame/staking-async/Cargo.toml
Labels: R0-no-crate-publish-required

#9771 [pallet-revive] fix salt endianness
  prdoc/pr_9771.prdoc
  substrate/frame/revive/src/tests/sol/contract.rs
  substrate/frame/revive/src/vm/evm.rs
Labels: T7-smart_contracts

#9772 EPMB: ensure to have enough funds for benchmarking
  prdoc/pr_9772.prdoc
  substrate/frame/election-provider-multi-block/src/lib.rs
Labels: T2-pallets, A4-backport-unstable2507, A4-backport-stable2509

#9776 ci: pin all actions version
  .github/actions/build-push-image/action.yml
  .github/actions/download-artifact-extract/action.yml
  .github/actions/workflow-stopper/action.yml
  .github/actions/zombienet-sdk/action.yml
  .github/actions/zombienet/action.yml
  .github/workflows/bench-all-runtimes.yml
  .github/workflows/benchmarks-networking.yml
  .github/workflows/benchmarks-subsystem.yml
  .github/workflows/build-misc.yml
  .github/workflows/build-publish-eth-rpc.yml
  .github/workflows/build-publish-images.yml
  .github/workflows/check-cargo-check-runtimes.yml
  .github/workflows/check-frame-omni-bencher.yml
  .github/workflows/check-getting-started.yml
  .github/workflows/check-licenses.yml
  .github/workflows/check-runtime-migration.yml
  .github/workflows/checks-quick.yml
  .github/workflows/cmd-run.yml
  .github/workflows/cmd-tests.yml
  .github/workflows/cmd.yml
  .github/workflows/command-backport.yml
  .github/workflows/command-inform.yml
  .github/workflows/command-prdoc.yml
  .github/workflows/docs.yml
  .github/workflows/issues-auto-add-parachain.yml
  .github/workflows/misc-sync-templates.yml
  .github/workflows/misc-update-wishlist-leaderboard.yml
  .github/workflows/release-10_branchoff-stable.yml
  .github/workflows/release-11_rc-automation.yml
  .github/workflows/release-30_publish_release_draft.yml
  .github/workflows/release-99_notif-published.yml
  .github/workflows/release-srtool.yml
  .github/workflows/reusable-preflight.yml
  .github/workflows/review-bot.yml
  .github/workflows/review-trigger.yml
  .github/workflows/tests-evm.yml
  .github/workflows/tests-linux-stable-coverage.yml
  .github/workflows/tests-linux-stable-xp.yml
  .github/workflows/tests-linux-stable.yml
  .github/workflows/tests-misc.yml
  .github/workflows/tests.yml
  .github/workflows/zombienet-reusable-preflight.yml
  .github/workflows/zombienet_cumulus.yml
  .github/workflows/zombienet_parachain-template.yml
  .github/workflows/zombienet_polkadot.yml
  .github/workflows/zombienet_substrate.yml
Labels: R0-no-crate-publish-required

#8108 Use `total balance (free + reserved)` when performing liquidity checks for a new reserve
  prdoc/pr_8108.prdoc
  substrate/frame/balances/src/impl_currency.rs
  substrate/frame/balances/src/tests/currency_tests.rs
  substrate/frame/balances/src/tests/fungible_and_currency.rs
  substrate/frame/balances/src/tests/mod.rs
Labels: T2-pallets, A4-backport-unstable2507, A4-backport-stable2509

#9793 [unstable2507] Post crate release changes
  Cargo.lock
  Plan.toml
  prdoc/unstable2507/pr_8108.prdoc
  substrate/frame/balances/Cargo.toml
Labels: R0-no-crate-publish-required

#9791 revive-fixtures: Provide an env variable to disable compilation
  substrate/frame/revive/fixtures/build.rs
  substrate/frame/revive/fixtures/src/lib.rs
  substrate/frame/revive/src/call_builder.rs
Labels: R0-no-crate-publish-required

#9717 EIP-3607 added check to make sure a contract account cannot transfer funds as an EOA account
  prdoc/pr_9717.prdoc
  substrate/frame/assets/src/precompiles.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/storage.rs
  substrate/frame/revive/src/tests/pvm.rs
Labels: T7-smart_contracts

#9781 Limit the number of signals per XCMP page
  cumulus/pallets/xcmp-queue/src/lib.rs
  cumulus/pallets/xcmp-queue/src/tests.rs
  prdoc/pr_9781.prdoc
Labels: T6-XCM, A4-backport-stable2506, A4-backport-unstable2507, A4-backport-stable2509

#9799 Added pallet-root-offences to Westend RC runtime
  Cargo.lock
  polkadot/runtime/westend/Cargo.toml
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_9799.prdoc
Labels: T2-pallets, A4-backport-stable2509

#9828 ci: Use `--locked` for cargo doc steps
  .github/workflows/docs.yml
Labels: R0-no-crate-publish-required

#9811 Elastic scaling runtime upgrade test
  .github/workflows/build-publish-images.yml
  .github/workflows/zombienet_cumulus.yml
  .github/zombienet-tests/zombienet_cumulus_tests.yml
  Cargo.lock
  cumulus/test/runtime/Cargo.toml
  cumulus/test/runtime/build.rs
  cumulus/test/runtime/src/lib.rs
  cumulus/test/service/src/chain_spec.rs
  cumulus/test/service/src/cli.rs
  cumulus/zombienet/zombienet-sdk-helpers/Cargo.toml
  cumulus/zombienet/zombienet-sdk-helpers/src/lib.rs
  cumulus/zombienet/zombienet-sdk/Cargo.toml
  cumulus/zombienet/zombienet-sdk/tests/zombie_ci/elastic_scaling/mod.rs
  cumulus/zombienet/zombienet-sdk/tests/zombie_ci/elastic_scaling/multiple_blocks_per_slot.rs
  cumulus/zombienet/zombienet-sdk/tests/zombie_ci/elastic_scaling/pov_recovery.rs
  cumulus/zombienet/zombienet-sdk/tests/zombie_ci/elastic_scaling/slot_based_authoring.rs
  cumulus/zombienet/zombienet-sdk/tests/zombie_ci/elastic_scaling/slot_based_rp_offset.rs
  cumulus/zombienet/zombienet-sdk/tests/zombie_ci/elastic_scaling/upgrade_to_3_cores.rs
  cumulus/zombienet/zombienet-sdk/tests/zombie_ci/runtime_upgrade.rs
  prdoc/pr_9811.prdoc
Labels: T9-cumulus, T10-tests

#9713 Elastic-scaling-guide: Mention slot duration
  .github/workflows/check-links.yml
  docs/sdk/src/guides/enable_elastic_scaling.rs
  prdoc/pr_9713.prdoc
Labels: T11-documentation, A4-backport-stable2509

#9842 xcm: Do not require `Asset` to be sorted on `decode`
  polkadot/xcm/src/v3/multiasset.rs
  polkadot/xcm/src/v4/asset.rs
  polkadot/xcm/src/v5/asset.rs
  prdoc/pr_9842.prdoc
Labels: T6-XCM

#9780 [pallet_transaction_payment]: Share withdrawn tx fee credit with other pallets
  Cargo.lock
  prdoc/pr_9780.prdoc
  substrate/frame/origin-restriction/src/mock.rs
  substrate/frame/support/src/traits.rs
  substrate/frame/support/src/traits/storage.rs
  substrate/frame/support/src/traits/tokens/fungible/imbalance.rs
  substrate/frame/transaction-payment/Cargo.toml
  substrate/frame/transaction-payment/asset-tx-payment/src/lib.rs
  substrate/frame/transaction-payment/src/lib.rs
  substrate/frame/transaction-payment/src/payment.rs
Labels: T1-FRAME

#9796 `pallet-assets`: extract precompiles to a separate crate
  Cargo.lock
  Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_9796.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/assets/Cargo.toml
  substrate/frame/assets/precompiles/Cargo.toml
  substrate/frame/assets/precompiles/src/lib.rs
  substrate/frame/assets/precompiles/src/mock.rs
  substrate/frame/assets/precompiles/src/tests.rs
  substrate/frame/assets/src/functions.rs
  substrate/frame/assets/src/lib.rs
  substrate/frame/assets/src/mock.rs
  umbrella/Cargo.toml
  umbrella/src/lib.rs
Labels: T2-pallets

#9875 Stronger WASM compression
  prdoc/pr_9875.prdoc
  substrate/primitives/maybe-compressed-blob/src/lib.rs
Labels: T17-primitives

#9881 [stable2509] Fix prdoc 9479
  prdoc/stable2509/pr_9479.prdoc
Labels: R0-no-crate-publish-required

#9204 Snowbridge: Refactor with Alloy primitives and clean up code
  Cargo.lock
  Cargo.toml
  bridges/snowbridge/pallets/ethereum-client/src/impls.rs
  bridges/snowbridge/pallets/ethereum-client/src/lib.rs
  bridges/snowbridge/pallets/ethereum-client/src/tests.rs
  bridges/snowbridge/primitives/beacon/src/receipt.rs
  bridges/snowbridge/primitives/ethereum/Cargo.toml
  bridges/snowbridge/primitives/ethereum/src/header.rs
  bridges/snowbridge/primitives/ethereum/src/lib.rs
  bridges/snowbridge/primitives/ethereum/src/log.rs
  bridges/snowbridge/primitives/ethereum/src/receipt.rs
  bridges/snowbridge/primitives/verification/src/lib.rs
  prdoc/pr_9204.prdoc
Labels: T15-bridges

#9868 Fix the deadlock during statements gossiping
  prdoc/pr_9868.prdoc
  substrate/client/statement-store/src/lib.rs
Labels: T0-node

#9864 Adjust statement store configs to hold more data
  prdoc/pr_9864.prdoc
  substrate/client/network/statement/src/config.rs
  substrate/client/statement-store/src/lib.rs
Labels: T0-node
