Repository paritytech/polkadot-sdk, pull requests merged in 2025-03, with the labels that each got.

#7124 Remove `pallet::getter` usage from `pallet-nft-fractionalization`
  prdoc/pr_7124.prdoc
  substrate/frame/nft-fractionalization/src/lib.rs
Labels: T2-pallets

#7721 revive: Rework the instruction benchmark
  Cargo.lock
  prdoc/pr_7721.prdoc
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/fixtures/contracts/instr_benchmark.rs
  substrate/frame/revive/fixtures/src/lib.rs
  substrate/frame/revive/src/benchmarking/call_builder.rs
  substrate/frame/revive/src/benchmarking/code.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/gas.rs
  substrate/frame/revive/src/wasm/mod.rs
  substrate/frame/revive/src/weights.rs
Labels: T7-smart_contracts

#7756 Fix unspecified Hash in NodeBlock
  cumulus/polkadot-omni-node/lib/src/common/mod.rs
  prdoc/pr_7756.prdoc
Labels: T9-cumulus

#7776 [stable2503] Backport `pallet-revive` fixes
  Cargo.lock
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_7614.prdoc
  prdoc/pr_7652.prdoc
  prdoc/pr_7662.prdoc
  prdoc/pr_7676.prdoc
  prdoc/pr_7721.prdoc
  prdoc/pr_7729.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/fixtures/contracts/call_and_return.rs
  substrate/frame/revive/fixtures/contracts/ecdsa_recover.rs
  substrate/frame/revive/fixtures/contracts/terminate_and_send_to_argument.rs
  substrate/frame/revive/fixtures/contracts/terminate_and_send_to_eve.rs
  substrate/frame/revive/fixtures/src/lib.rs
  substrate/frame/revive/rpc/revive_chain.metadata
  substrate/frame/revive/src/address.rs
  substrate/frame/revive/src/benchmarking/call_builder.rs
  substrate/frame/revive/src/benchmarking/code.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/evm/api/byte.rs
  substrate/frame/revive/src/evm/api/debug_rpc_types.rs
  substrate/frame/revive/src/evm/api/hex_serde.rs
  substrate/frame/revive/src/evm/api/rlp_codec.rs
  substrate/frame/revive/src/evm/api/signature.rs
  substrate/frame/revive/src/evm/tracing.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/exec/tests.rs
  substrate/frame/revive/src/gas.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/pure_precompiles.rs
  substrate/frame/revive/src/pure_precompiles/ecrecover.rs
  substrate/frame/revive/src/test_utils.rs
  substrate/frame/revive/src/test_utils/builder.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/mod.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/src/weights.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv64.rs
Labels: R0-silent

#7741 [kitchensink] migrate to use genesis presets
  .github/workflows/runtimes-matrix.json
  Cargo.lock
  substrate/bin/node/cli/src/chain_spec.rs
  substrate/bin/node/cli/tests/benchmark_pallet_works.rs
  substrate/bin/node/runtime/Cargo.toml
  substrate/bin/node/runtime/src/genesis_config_presets.rs
  substrate/bin/node/runtime/src/lib.rs
Labels: R0-silent

#7764 Add Serialize & Deserialize to umbrella crate derive module
  Cargo.lock
  prdoc/pr_7764.prdoc
  substrate/frame/Cargo.toml
  substrate/frame/src/lib.rs
Labels: T17-primitives

#7784 [pallet-revive] block.timestamps should return seconds
  prdoc/pr_7784.prdoc
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/uapi/src/host.rs
Labels: R0-silent, T7-smart_contracts

#6607 Migrating polkadot-runtime-parachains configuration benchmarking to V2
  polkadot/runtime/parachains/src/configuration/benchmarking.rs
  polkadot/runtime/rococo/src/weights/polkadot_runtime_parachains_configuration.rs
  polkadot/runtime/westend/src/weights/polkadot_runtime_parachains_configuration.rs
Labels: R0-silent, T2-pallets, T12-benchmarks

#7792 [backport][pallet-revive] block.timestamps should return seconds (#7784)
  prdoc/pr_7784.prdoc
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/uapi/src/host.rs
Labels: R0-silent

#7531 pallet-bridge-relayers - migrate benchmarks to v2
  bridges/modules/relayers/src/benchmarking.rs
  bridges/modules/relayers/src/lib.rs
Labels: R0-silent

#7786 pallet revive: rpc build script should not panic
  docs/sdk/src/guides/your_first_node.rs
  prdoc/pr_7786.prdoc
  substrate/frame/revive/rpc/build.rs
Labels: T2-pallets

#7793 notifications/tests: Fix tests to avoid overflow on adding duration to instant
  substrate/client/network/src/protocol/notifications/tests/conformance.rs
Labels: R0-silent

#7708 Support adding extra request-response protocols to the node
  polkadot/node/service/src/builder/mod.rs
  polkadot/node/service/src/builder/partial.rs
  polkadot/node/service/src/lib.rs
  prdoc/pr_7708.prdoc
Labels: T0-node

#7798 ci: update credentials for command-backport
  .github/workflows/command-backport.yml
Labels: R0-silent

#7790 pallet-scheduler: Put back postponed tasks into the agenda
  prdoc/pr_7790.prdoc
  substrate/frame/scheduler/src/lib.rs
  substrate/frame/scheduler/src/mock.rs
  substrate/frame/scheduler/src/tests.rs
Labels: T2-pallets

#7818 [pallet-revive] eth-rpc-tester quick fixes
  prdoc/pr_7818.prdoc
  substrate/frame/revive/rpc/src/eth-rpc-tester.rs
Labels: R0-silent, T7-smart_contracts

#7760 Dynamic uncompressed code size limit
  cumulus/bin/pov-validator/src/main.rs
  cumulus/client/relay-chain-minimal-node/src/blockchain_rpc_client.rs
  cumulus/client/relay-chain-rpc-interface/src/rpc_client.rs
  polkadot/node/core/candidate-validation/src/lib.rs
  polkadot/node/core/candidate-validation/src/tests.rs
  polkadot/node/core/pvf/benches/host_prepare_rococo_runtime.rs
  polkadot/node/core/pvf/common/src/pvf.rs
  polkadot/node/core/pvf/prepare-worker/benches/prepare_rococo_runtime.rs
  polkadot/node/core/pvf/prepare-worker/src/lib.rs
  polkadot/node/core/pvf/tests/it/main.rs
  polkadot/node/core/runtime-api/src/cache.rs
  polkadot/node/core/runtime-api/src/lib.rs
  polkadot/node/core/runtime-api/src/tests.rs
  polkadot/node/primitives/src/lib.rs
  polkadot/node/subsystem-types/src/messages.rs
  polkadot/node/subsystem-types/src/runtime_client.rs
  polkadot/node/subsystem-util/src/runtime/mod.rs
  polkadot/primitives/src/runtime_api.rs
  polkadot/runtime/parachains/src/configuration.rs
  polkadot/runtime/parachains/src/runtime_api_impl/vstaging.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_7760.prdoc
Labels: T0-node, T4-runtime_API, T8-polkadot

#7769 Ensure Logs Are Captured for Assertions and Printed During Tests
  Cargo.lock
  polkadot/xcm/xcm-simulator/example/src/tests.rs
  prdoc/pr_7769.prdoc
  substrate/primitives/tracing/Cargo.toml
  substrate/primitives/tracing/src/lib.rs
Labels: T6-XCM, T10-tests

#7826 Backport 2503: westend asset hub next trusted teleporter
  polkadot/runtime/westend/constants/src/lib.rs
  polkadot/runtime/westend/src/xcm_config.rs
  prdoc/pr_7826.prdoc
Labels: T6-XCM, A3-backport

#7814 [Release|CI/CD] Update runtime artefact's name before upload to a GitHub draft release
  .github/workflows/release-30_publish_release_draft.yml
Labels: R0-silent, D0-easy, A4-needs-backport

#7794 [glutton-westend] and add sudo key to genesis config
  cumulus/parachains/runtimes/glutton/glutton-westend/src/genesis_config_presets.rs
  cumulus/polkadot-parachain/src/chain_spec/glutton.rs
  prdoc/pr_7794.prdoc
Labels: T9-cumulus

#7809 [XCM] Add generic location to account converter that also works with external ecosystems for bridge hubs
  Cargo.lock
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/tests.rs
  prdoc/pr_7809.prdoc
Labels: T6-XCM

#7698 adding verbose rustdoc to diff between build-spec and chain-spec-builder
  cumulus/polkadot-omni-node/lib/src/cli.rs
  cumulus/polkadot-omni-node/lib/src/command.rs
Labels: R0-silent, T9-cumulus, T11-documentation

#7711 cmd-bot: divide workflow into 2 steps
  .github/workflows/cmd-run.yml
  .github/workflows/cmd.yml
Labels: R0-silent

#7801 add poke_deposit extrinsic to pallet-proxy
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_proxy.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_proxy.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_proxy.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_proxy.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/pallet_proxy.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/pallet_proxy.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/pallet_proxy.rs
  polkadot/runtime/rococo/src/weights/pallet_proxy.rs
  polkadot/runtime/westend/src/weights/pallet_proxy.rs
  prdoc/pr_7801.prdoc
  substrate/frame/proxy/src/benchmarking.rs
  substrate/frame/proxy/src/lib.rs
  substrate/frame/proxy/src/tests.rs
  substrate/frame/proxy/src/weights.rs
Labels: T1-FRAME, T2-pallets

#7813 Improve metadata for `SkipCheckIfFeeless`
  prdoc/pr_7813.prdoc
  substrate/frame/transaction-payment/skip-feeless-payment/src/lib.rs
  substrate/frame/transaction-payment/skip-feeless-payment/src/tests.rs
Labels: T2-pallets

#7812 `apply_authorized_upgrade`: Remote authorization if the version check fails
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/parachain-system/src/tests.rs
  prdoc/pr_7812.prdoc
  substrate/frame/system/src/lib.rs
Labels: T2-pallets

#7257 `fatxpool`: add heavy load tests based on zombienet
  .config/taplo.toml
  Cargo.lock
  Cargo.toml
  substrate/client/transaction-pool/Cargo.toml
  substrate/client/transaction-pool/tests/integration.rs
  substrate/client/transaction-pool/tests/zombienet/mod.rs
  substrate/client/transaction-pool/tests/zombienet/network-specs/asset-hub-high-pool-limit-fatp.toml
  substrate/client/transaction-pool/tests/zombienet/network-specs/asset-hub-low-pool-limit-fatp.toml
  substrate/client/transaction-pool/tests/zombienet/network-specs/rococo-local-high-pool-limit-fatp.toml
Labels: R0-silent

#7827 [revive-rpc] allow using legacy data field
  substrate/frame/revive/rpc/revive_chain.metadata
  substrate/frame/revive/rpc/src/example.rs
  substrate/frame/revive/src/evm/api/rpc_types.rs
  substrate/frame/revive/src/evm/api/rpc_types_gen.rs
  substrate/frame/revive/src/evm/runtime.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/tests.rs
Labels: R0-silent, T7-smart_contracts

#7847 Bump trie-db to latest version
  Cargo.lock
  Cargo.toml
Labels: R0-silent

#7820 Make pallet-transaction-payment-benchmark work with ed 0
  prdoc/pr_7820.prdoc
  substrate/frame/transaction-payment/src/benchmarking.rs
Labels: T2-pallets

#7846 Incrementable: return None instead of saturating
  prdoc/pr_7846.prdoc
  substrate/frame/support/src/traits/storage.rs
Labels: T17-primitives

#7838 `CheckOnlySudoAccount`: Provide some tags
  cumulus/parachains/runtimes/glutton/glutton-westend/src/lib.rs
  prdoc/pr_7838.prdoc
  substrate/frame/sudo/src/extension.rs
Labels: T2-pallets

#7864 Do some more checks for `authorized_upgrade`.
  substrate/frame/system/src/lib.rs
Labels: R0-silent

#7870 Remove gitlab zombienet tests for cumulus/substrate
  .gitlab/pipeline/zombienet.yml
  .gitlab/pipeline/zombienet/cumulus.yml
  .gitlab/pipeline/zombienet/substrate.yml
Labels: R0-silent

#7856 Fix XCM decoding inconsistencies
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/xcmp-queue/src/benchmarking.rs
  cumulus/pallets/xcmp-queue/src/lib.rs
  cumulus/pallets/xcmp-queue/src/tests.rs
  cumulus/parachains/runtimes/test-utils/src/lib.rs
  cumulus/primitives/utility/src/lib.rs
  polkadot/runtime/common/src/xcm_sender.rs
  polkadot/xcm/src/lib.rs
  polkadot/xcm/src/utils.rs
  polkadot/xcm/src/v3/mod.rs
  polkadot/xcm/src/v4/mod.rs
  polkadot/xcm/src/v5/mod.rs
  polkadot/xcm/xcm-builder/src/process_xcm_message.rs
  polkadot/xcm/xcm-builder/src/routing.rs
  polkadot/xcm/xcm-simulator/fuzzer/src/fuzz.rs
  prdoc/pr_7856.prdoc
Labels: T6-XCM

#7848 [pallet-revive] Add support for eip1898 block notation
  prdoc/pr_7848.prdoc
  substrate/frame/revive/src/evm/api/rpc_types_gen.rs
Labels: R0-silent, T7-smart_contracts

#7869 [Release|Ci/CD] Update path to `ci-unfied` Dockerfile to grab a right Rust version
  .github/workflows/release-30_publish_release_draft.yml
Labels: R0-silent

#7877 [Release|CI/CD] Fixes for the promote rc to final flow
  .github/scripts/common/lib.sh
  .github/scripts/release/release_lib.sh
  .github/workflows/release-11_rc-automation.yml
  .github/workflows/release-40_publish-deb-package.yml
  .github/workflows/release-reusable-promote-to-final.yml
  .github/workflows/release-reusable-rc-buid.yml
Labels: R0-silent, A4-needs-backport

#7866 network: Make litep2p the default backend in Kusama
  Cargo.lock
  Cargo.toml
  cumulus/client/relay-chain-minimal-node/src/lib.rs
  cumulus/polkadot-omni-node/lib/Cargo.toml
  cumulus/polkadot-omni-node/lib/src/common/spec.rs
  cumulus/polkadot-omni-node/lib/src/nodes/mod.rs
  cumulus/test/service/src/lib.rs
  cumulus/test/service/src/main.rs
  polkadot/node/service/src/lib.rs
  polkadot/node/test/service/src/lib.rs
  prdoc/pr_7866.prdoc
  substrate/bin/node/cli/src/service.rs
  substrate/client/cli/src/params/network_params.rs
  substrate/client/network/src/config.rs
  templates/minimal/node/src/command.rs
  templates/solochain/node/src/command.rs
Labels: T0-node

#7887 backport/2412: network: Make litep2p the default backend in Kusama (#7866)
  Cargo.lock
  Cargo.toml
  cumulus/client/relay-chain-minimal-node/src/lib.rs
  cumulus/polkadot-omni-node/lib/Cargo.toml
  cumulus/polkadot-omni-node/lib/src/common/spec.rs
  cumulus/polkadot-omni-node/lib/src/nodes/mod.rs
  cumulus/test/service/src/lib.rs
  cumulus/test/service/src/main.rs
  polkadot/node/service/src/lib.rs
  polkadot/node/test/service/src/lib.rs
  prdoc/pr_7866.prdoc
  substrate/bin/node/cli/src/service.rs
  substrate/client/cli/src/params/network_params.rs
  substrate/client/network/src/config.rs
  templates/minimal/node/src/command.rs
  templates/solochain/node/src/command.rs
Labels: A3-backport

#7763 [staking] Currency Migration and Overstake fix
  polkadot/runtime/westend/src/tests.rs
  prdoc/pr_7763.prdoc
  substrate/frame/staking/src/lib.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/tests.rs
Labels: A3-backport, T2-pallets

#7889 Remove execute_with_origin implementation in the XCM executor
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/claim_assets.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  polkadot/xcm/xcm-executor/src/tests/execute_with_origin.rs
  polkadot/xcm/xcm-executor/src/tests/mod.rs
  prdoc/pr_7889.prdoc
Labels: T6-XCM, A4-needs-backport

#7805 staking: add `manual_slash` extrinsic
  polkadot/runtime/westend/src/weights/pallet_staking.rs
  prdoc/pr_7805.prdoc
  substrate/frame/election-provider-multi-phase/test-staking-e2e/src/mock.rs
  substrate/frame/staking/src/benchmarking.rs
  substrate/frame/staking/src/mock.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/tests.rs
  substrate/frame/staking/src/weights.rs
Labels: T1-FRAME, T8-polkadot

#7873 Improve error message in benchmark macro
  substrate/frame/support/procedural/src/benchmark.rs
  substrate/frame/support/test/tests/benchmark_ui/extrinsic_call_wrong_origin.rs
  substrate/frame/support/test/tests/benchmark_ui/extrinsic_call_wrong_origin.stderr
  substrate/frame/support/test/tests/benchmark_ui/invalid_origin.stderr
Labels: R0-silent

#7879 [pallet-revive] Support blocktag in eth_getLogs RPC
  prdoc/pr_7879.prdoc
  substrate/frame/revive/rpc/src/receipt_provider/db.rs
  substrate/frame/revive/src/evm/api/rpc_types_gen.rs
Labels: R0-silent, T7-smart_contracts

#7120 Remove `pallet::getter` usage from bridges/modules
  bridges/modules/beefy/src/lib.rs
  bridges/modules/grandpa/src/lib.rs
  bridges/modules/messages/src/lib.rs
  bridges/modules/relayers/src/lib.rs
  bridges/modules/xcm-bridge-hub-router/src/lib.rs
  bridges/primitives/runtime/src/lib.rs
  prdoc/pr_7120.prdoc
Labels: T2-pallets

#7892 [Release|CI/CD] Update version of the cache action in the Publish docker ci
  .github/workflows/release-50_publish-docker.yml
Labels: R0-silent, A4-needs-backport

#7781 notifications/libp2p: Punish notification protocol misbehavior on outbound substreams
  prdoc/pr_7781.prdoc
  substrate/client/network/src/protocol.rs
  substrate/client/network/src/protocol/notifications/behaviour.rs
  substrate/client/network/src/protocol/notifications/handler.rs
  substrate/client/network/src/protocol/notifications/upgrade.rs
  substrate/client/network/src/protocol/notifications/upgrade/notifications.rs
Labels: T0-node

#7871 [CI] bump timeout wait for build in zombienet workflows.
  .github/workflows/zombienet-reusable-preflight.yml
Labels: R0-silent, T10-tests

#7893 Use non-native token to benchmark xcm on asset hub
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/fungible/benchmarking.rs
  prdoc/pr_7893.prdoc
Labels: T6-XCM, A4-needs-backport

#7810 [pallet-revive] precompiles 2->9
  Cargo.lock
  Cargo.toml
  prdoc/pr_7810.prdoc
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/fixtures/contracts/call_and_return.rs
  substrate/frame/revive/fixtures/contracts/crypto_hashes.rs
  substrate/frame/revive/src/benchmarking/mod.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/pure_precompiles.rs
  substrate/frame/revive/src/pure_precompiles/blake2f.rs
  substrate/frame/revive/src/pure_precompiles/blake2f/eip_152.rs
  substrate/frame/revive/src/pure_precompiles/bn128.rs
  substrate/frame/revive/src/pure_precompiles/ecrecover.rs
  substrate/frame/revive/src/pure_precompiles/identity.rs
  substrate/frame/revive/src/pure_precompiles/modexp.rs
  substrate/frame/revive/src/pure_precompiles/ripemd160.rs
  substrate/frame/revive/src/pure_precompiles/sha256.rs
  substrate/frame/revive/src/pure_precompiles/testdata/1-ecRecover.json
  substrate/frame/revive/src/pure_precompiles/testdata/2-sha256.json
  substrate/frame/revive/src/pure_precompiles/testdata/3-ripemd160.json
  substrate/frame/revive/src/pure_precompiles/testdata/5-modexp_eip2565.json
  substrate/frame/revive/src/pure_precompiles/testdata/6-bn128add-failure.json
  substrate/frame/revive/src/pure_precompiles/testdata/6-bn128add.json
  substrate/frame/revive/src/pure_precompiles/testdata/7-bn128mul.json
  substrate/frame/revive/src/pure_precompiles/testdata/8-bn128pairing.json
  substrate/frame/revive/src/pure_precompiles/testdata/9-blake2f-failures.json
  substrate/frame/revive/src/pure_precompiles/testdata/9-blake2f.json
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/revive/src/weights.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv64.rs
Labels: R0-silent, T7-smart_contracts

#7917 Remove clones from block seal function
  cumulus/client/consensus/aura/src/collator.rs
  substrate/client/consensus/aura/src/standalone.rs
Labels: R0-silent, T0-node

#7923 cumulus: fix pov exporter format
  cumulus/bin/pov-validator/src/main.rs
  cumulus/client/consensus/aura/src/collators/lookahead.rs
  cumulus/client/consensus/aura/src/collators/slot_based/block_builder_task.rs
  cumulus/client/consensus/aura/src/collators/slot_based/collation_task.rs
  cumulus/client/consensus/aura/src/collators/slot_based/mod.rs
  cumulus/client/consensus/aura/src/lib.rs
Labels: R0-silent

#7928 [pallet-revive] Fix pallet-revive-fixtures build.rs
  prdoc/pr_7928.prdoc
  substrate/frame/revive/fixtures/build.rs
Labels: R0-silent, T7-smart_contracts

#7934 remove compromised action
  .github/workflows/reusable-preflight.yml
  .github/workflows/zombienet-reusable-preflight.yml
Labels: R0-silent

#7918 Add an extra_constant to pallet-treasury
  prdoc/pr_7918.prdoc
  substrate/frame/treasury/src/lib.rs
Labels: T2-pallets

#7888 backport/2503: network: Make litep2p the default backend in Kusama (#7866)
  Cargo.lock
  Cargo.toml
  cumulus/client/relay-chain-minimal-node/src/lib.rs
  cumulus/polkadot-omni-node/lib/Cargo.toml
  cumulus/polkadot-omni-node/lib/src/common/spec.rs
  cumulus/polkadot-omni-node/lib/src/nodes/mod.rs
  cumulus/test/service/src/lib.rs
  cumulus/test/service/src/main.rs
  polkadot/node/service/src/lib.rs
  polkadot/node/test/service/src/lib.rs
  prdoc/pr_7866.prdoc
  substrate/bin/node/cli/src/service.rs
  substrate/client/cli/src/params/network_params.rs
  substrate/client/network/src/config.rs
  templates/minimal/node/src/command.rs
  templates/solochain/node/src/command.rs
Labels: A3-backport

#7464 Follow up for: Use the umbrella crate for the parachain template #5993
  Cargo.lock
  prdoc/pr_7464.prdoc
  substrate/client/tracing/proc-macro/src/lib.rs
  templates/parachain/node/Cargo.toml
Labels: R0-silent, T17-Templates

#7930 Update README.md for Cumulus
  cumulus/README.md
Labels: R0-silent

#7459 run frame-omni-bencher overhead command in CI for all runtimes in the runtime matrix
  .github/workflows/check-frame-omni-bencher.yml
Labels: R0-silent

#7723 pallet-bounties: allow bounties to never expire
  prdoc/pr_7723.prdoc
  substrate/frame/bounties/src/benchmarking.rs
  substrate/frame/bounties/src/lib.rs
  substrate/frame/bounties/src/tests.rs
  substrate/frame/child-bounties/src/benchmarking.rs
Labels: T2-pallets

#7946 Cumulus: Remove some old scripts
  cumulus/scripts/generate_genesis_value.sh
  cumulus/scripts/generate_genesis_values/index.js
  cumulus/scripts/generate_genesis_values/package.json
  cumulus/scripts/generate_genesis_values/yarn.lock
  cumulus/scripts/scale_encode_genesis/index.js
  cumulus/scripts/scale_encode_genesis/package.json
  cumulus/scripts/scale_encode_genesis/yarn.lock
Labels: R0-silent

#7950 Updating readmes
  README.md
  docker/dockerfiles/polkadot/polkadot_Dockerfile.README.md
  docs/contributor/DOCUMENTATION_GUIDELINES.md
  polkadot/README.md
  templates/minimal/README.md
  templates/parachain/README.docify.md
  templates/parachain/README.md
Labels: R0-silent, T11-documentation, T17-Templates

#7874 Upgrade link-checker cache to v4
  .config/lychee.toml
  .github/workflows/check-links.yml
Labels: R0-silent

#7610 runtime-api: remove redundant version checks
  polkadot/node/collation-generation/src/lib.rs
  polkadot/node/collation-generation/src/tests.rs
  polkadot/node/core/av-store/src/lib.rs
  polkadot/node/core/av-store/src/tests.rs
  polkadot/node/core/backing/src/lib.rs
  polkadot/node/core/dispute-coordinator/src/tests.rs
  polkadot/node/core/provisioner/src/error.rs
  polkadot/node/core/provisioner/src/lib.rs
  polkadot/node/network/availability-distribution/src/error.rs
  polkadot/node/network/availability-distribution/src/requester/session_cache.rs
  polkadot/node/network/availability-distribution/src/tests/state.rs
  polkadot/node/network/availability-recovery/src/lib.rs
  polkadot/node/network/availability-recovery/src/tests.rs
  polkadot/node/network/collator-protocol/src/error.rs
  polkadot/node/network/collator-protocol/src/validator_side/mod.rs
  polkadot/node/network/statement-distribution/src/error.rs
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  polkadot/node/network/statement-distribution/src/v2/tests/mod.rs
  polkadot/node/subsystem-bench/src/lib/availability/test_state.rs
  polkadot/node/subsystem-util/src/availability_chunks.rs
  polkadot/node/subsystem-util/src/lib.rs
  polkadot/node/subsystem-util/src/runtime/mod.rs
  prdoc/pr_7610.prdoc
Labels: T0-node, T4-runtime_API

#7843 Fix XCM Barrier Rejection Handling to Return Incomplete with Weight
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/governance.rs
  polkadot/xcm/xcm-builder/src/tests/origins.rs
  polkadot/xcm/xcm-builder/src/tests/querying.rs
  polkadot/xcm/xcm-builder/src/tests/version_subscriptions.rs
  polkadot/xcm/xcm-builder/tests/scenarios.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  prdoc/pr_7843.prdoc
Labels: T6-XCM, A4-needs-backport

#7777 `fatxpool`: report_invalid: do not ban Future/Stale txs from re-entering the view
  prdoc/pr_7777.prdoc
  substrate/client/transaction-pool/src/common/tracing_log_xt.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/view.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs
  substrate/client/transaction-pool/src/graph/validated_pool.rs
Labels: R0-silent, T0-node

#7959 Treasury: update expire date on payout (#7958)
  prdoc/pr_7959.prdoc
  substrate/frame/treasury/src/lib.rs
  substrate/frame/treasury/src/tests.rs
Labels: T2-pallets

#7978 `bp-runtime`: make macro expansion not rely on `sp-std` in scope.
  bridges/primitives/runtime/src/chain.rs
  bridges/primitives/runtime/src/lib.rs
Labels: R0-silent, T15-bridges

#7981 Bump parachains runtime api to 13
  cumulus/parachains/integration-tests/emulated/chains/relays/rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/relays/westend/src/lib.rs
  polkadot/node/subsystem-types/src/messages.rs
  polkadot/primitives/src/runtime_api.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/test-runtime/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_7981.prdoc
Labels: T4-runtime_API, T8-polkadot

#7885 rpc-v2/archive: Rename archive call method result to value
  prdoc/pr_7885.prdoc
  substrate/client/rpc-spec-v2/src/lib.rs
Labels: T3-RPC_API

#7883 [stable-2503] Backport #7569 and #7585
  .github/workflows/build-publish-images.yml
  .github/workflows/zombienet-reusable-preflight.yml
  .github/workflows/zombienet_cumulus.yml
  .github/zombienet-env
  Cargo.toml
  cumulus/client/consensus/aura/Cargo.toml
  cumulus/client/consensus/aura/src/collators/lookahead.rs
  cumulus/client/consensus/aura/src/collators/slot_based/block_builder_task.rs
  cumulus/client/consensus/aura/src/collators/slot_based/collation_task.rs
  cumulus/client/consensus/aura/src/collators/slot_based/mod.rs
  cumulus/client/consensus/aura/src/collators/slot_based/slot_timer.rs
  cumulus/client/consensus/aura/src/lib.rs
  cumulus/pallets/aura-ext/Cargo.toml
  cumulus/pallets/aura-ext/src/consensus_hook.rs
  cumulus/pallets/aura-ext/src/test.rs
  cumulus/polkadot-omni-node/lib/src/cli.rs
  cumulus/polkadot-omni-node/lib/src/command.rs
  cumulus/polkadot-omni-node/lib/src/common/mod.rs
  cumulus/polkadot-omni-node/lib/src/nodes/aura.rs
  cumulus/test/runtime/Cargo.toml
  cumulus/test/runtime/build.rs
  cumulus/test/runtime/src/lib.rs
  cumulus/test/service/src/chain_spec.rs
  cumulus/test/service/src/cli.rs
  cumulus/test/service/src/lib.rs
  cumulus/test/service/src/main.rs
  cumulus/zombienet/tests/0008-elastic_authoring.toml
  cumulus/zombienet/tests/0009-elastic_pov_recovery.toml
  cumulus/zombienet/zombienet-sdk-helpers/Cargo.toml
  cumulus/zombienet/zombienet-sdk-helpers/src/lib.rs
  cumulus/zombienet/zombienet-sdk/Cargo.toml
  cumulus/zombienet/zombienet-sdk/README.md
  cumulus/zombienet/zombienet-sdk/src/lib.rs
  cumulus/zombienet/zombienet-sdk/tests/elastic_scaling/elastic_scaling_multiple_blocks_per_slot.rs
  cumulus/zombienet/zombienet-sdk/tests/elastic_scaling/mod.rs
  cumulus/zombienet/zombienet-sdk/tests/lib.rs
  docs/sdk/src/guides/enable_elastic_scaling_mvp.rs
  polkadot/zombienet-sdk-tests/Cargo.toml
  polkadot/zombienet-sdk-tests/tests/elastic_scaling/slot_based_12cores.rs
  polkadot/zombienet-sdk-tests/tests/elastic_scaling/slot_based_3cores.rs
  polkadot/zombienet_tests/functional/0018-shared-core-idle-parachain.toml
  polkadot/zombienet_tests/functional/0019-coretime-collation-fetching-fairness.toml
  prdoc/pr_7569.prdoc
  prdoc/pr_7585.prdoc
Labels: R0-silent, T0-node

#7964 bump version of zombienet-sdk
  Cargo.lock
  Cargo.toml
Labels: R0-silent, T10-tests

#7671 Fix: [Referenda Tracks] Resolve representation issues that are breaking PJS apps
  prdoc/pr_7671.prdoc
  substrate/frame/referenda/src/lib.rs
  substrate/frame/referenda/src/types.rs
Labels: T2-pallets, A4-backport-stable2503

#7915 Add digest processor xcm emulator
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-westend/src/lib.rs
  cumulus/xcm/xcm-emulator/src/lib.rs
Labels: R0-silent, T10-tests

#7916 Removed `pallet:getter` from XCM pallets
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/xcm-executor/integration-tests/src/lib.rs
  polkadot/xcm/xcm-simulator/fuzzer/src/parachain.rs
  prdoc/pr_7916.prdoc
Labels: R0-silent

#8003 docs: update local ci execution instruction
  docs/contributor/container.md
Labels: R0-silent

#7993 switch polkadot zombienet-sdk tests to use cumulus test helpers
  .github/workflows/build-publish-images.yml
  .gitlab/pipeline/build.yml
  cumulus/zombienet/zombienet-sdk-helpers/Cargo.toml
  cumulus/zombienet/zombienet-sdk-helpers/src/lib.rs
  polkadot/zombienet-sdk-tests/Cargo.toml
  polkadot/zombienet-sdk-tests/build.rs
  polkadot/zombienet-sdk-tests/tests/disabling/slashing.rs
  polkadot/zombienet-sdk-tests/tests/elastic_scaling/basic_3cores.rs
  polkadot/zombienet-sdk-tests/tests/elastic_scaling/doesnt_break_parachains.rs
  polkadot/zombienet-sdk-tests/tests/functional/async_backing_6_seconds_rate.rs
  polkadot/zombienet-sdk-tests/tests/functional/duplicate_collations.rs
  polkadot/zombienet-sdk-tests/tests/functional/sync_backing.rs
  polkadot/zombienet-sdk-tests/tests/helpers/mod.rs
  polkadot/zombienet-sdk-tests/tests/lib.rs
  polkadot/zombienet-sdk-tests/tests/smoke/coretime_revenue.rs
  polkadot/zombienet-sdk-tests/tests/smoke/mod.rs
Labels: R0-silent, T10-tests

#7903 Update RELEASE.md
  README.md
  docs/RELEASE.md
Labels: R0-silent, T11-documentation

#8024 Snowbridge - Change the hash of the outbound queue PendingOrders storage item
  bridges/snowbridge/pallets/outbound-queue-v2/src/lib.rs
  prdoc/pr_8024.prdoc
Labels: R0-silent, A4-backport-stable2503

#7657 Rewrite zombienet-polkadot-functional-0012-spam-statement-distribution-requests
  .github/workflows/zombienet_polkadot.yml
  .gitlab/pipeline/zombienet/polkadot.yml
  polkadot/zombienet-sdk-tests/tests/functional/mod.rs
  polkadot/zombienet-sdk-tests/tests/functional/spam_statement_distribution_requests.rs
  polkadot/zombienet_tests/functional/0012-spam-statement-distribution-requests.toml
  polkadot/zombienet_tests/functional/0012-spam-statement-distribution-requests.zndsl
Labels: R0-silent, T10-tests

#8037 Snowbridge - Deny ExportMessage from everywhere except for root of AH
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge_edge_case.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/xcm_config.rs
Labels: R0-silent, A4-backport-stable2503

#8034 Cumulus Zombienet: Fix readme + provide a script
  cumulus/zombienet/zombienet-sdk/README.md
  cumulus/zombienet/zombienet-sdk/run.sh
Labels: R0-silent

#8042 [CI/CD] Fix failing backports to release branches if something was changed in the .github/workflows folder
  .github/workflows/command-backport.yml
Labels: R0-silent

#6514 Migrate `pallet-whitelist` to umbrella crate
  Cargo.lock
  substrate/frame/whitelist/Cargo.toml
  substrate/frame/whitelist/src/benchmarking.rs
  substrate/frame/whitelist/src/lib.rs
  substrate/frame/whitelist/src/mock.rs
  substrate/frame/whitelist/src/tests.rs
  substrate/frame/whitelist/src/weights.rs
Labels: R0-silent, T1-FRAME

#7835 XCM: Some weight fixes for `InitiateTransfer`
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/transact.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge_v2_inbound.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge_v2_inbound_to_rococo.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge_v2_outbound.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge_v2_outbound_edge_case.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge_v2_outbound_from_rococo.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/transact.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/xcm/mod.rs
  polkadot/runtime/rococo/src/weights/xcm/mod.rs
  polkadot/runtime/westend/src/weights/xcm/mod.rs
  polkadot/xcm/pallet-xcm-benchmarks/src/fungible/benchmarking.rs
  polkadot/xcm/procedural/src/builder_pattern.rs
  polkadot/xcm/src/v4/asset.rs
  polkadot/xcm/src/v5/asset.rs
  polkadot/xcm/src/v5/mod.rs
  polkadot/xcm/xcm-executor/src/assets.rs
  polkadot/xcm/xcm-executor/src/tests/initiate_transfer.rs
  prdoc/pr_7835.prdoc
Labels: T6-XCM, A4-backport-stable2412, A4-backport-stable2503

#8045 Updated readme and shell script bash version
  .github/scripts/check-missing-readme-generation.sh
  bridges/snowbridge/scripts/contribute-upstream.sh
  bridges/snowbridge/scripts/hexliteral.sh
  bridges/snowbridge/scripts/make-build-config.sh
  bridges/testing/README.md
  bridges/testing/environments/rococo-westend/bridges_rococo_westend.sh
  bridges/testing/environments/rococo-westend/explorers.sh
  bridges/testing/environments/rococo-westend/helper.sh
  bridges/testing/environments/rococo-westend/spawn.sh
  bridges/testing/environments/rococo-westend/start_relayer.sh
  bridges/testing/framework/utils/bridges.sh
  bridges/testing/framework/utils/common.sh
  bridges/testing/framework/utils/zombienet.sh
  bridges/testing/run-test.sh
  bridges/testing/scripts/invoke-script.sh
  bridges/testing/scripts/sync-exit.sh
  bridges/testing/tests/0001-asset-transfer/run.sh
  bridges/testing/tests/0002-free-headers-synced-while-idle/run.sh
  bridges/testing/tests/0003-required-headers-synced-while-active/run.sh
  polkadot/zombienet_tests/misc/0002-download-polkadot-from-pr.sh
  polkadot/zombienet_tests/misc/0002-update-cmd.sh
  scripts/snowbridge_update_subtree.sh
  substrate/.maintain/rename-crates-for-2.0.sh
Labels: R0-silent, T11-documentation

#8059 [AHM] Revert v17 migration of pallet-staking in Westend
  substrate/frame/election-provider-multi-block/src/lib.rs
  substrate/frame/election-provider-multi-block/src/types.rs
  substrate/frame/election-provider-multi-block/src/verifier/mod.rs
  substrate/frame/staking/src/pallet/mod.rs
Labels: R0-silent, A4-backport-stable2503

#7952 Add expensive scenario for asset exchange
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/exchange_asset.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  polkadot/xcm/pallet-xcm-benchmarks/Cargo.toml
  polkadot/xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  prdoc/pr_7952.prdoc
Labels: T6-XCM, T12-benchmarks, A4-backport-stable2409, A4-backport-stable2412, A4-backport-stable2503

#7663 Validator disabling in session enhancements
  prdoc/pr_7663.prdoc
  substrate/frame/session/src/lib.rs
  substrate/frame/session/src/migrations/v1.rs
  substrate/frame/session/src/tests.rs
  substrate/frame/staking/src/migrations.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/tests.rs
  substrate/primitives/staking/src/offence.rs
Labels: T8-polkadot, T10-tests, A4-backport-stable2503

#8040 Make the default 85% usage of the PoV
  cumulus/client/cli/src/lib.rs
  cumulus/client/consensus/aura/Cargo.toml
  cumulus/client/consensus/aura/src/collators/basic.rs
  cumulus/client/consensus/aura/src/collators/lookahead.rs
  cumulus/client/consensus/aura/src/collators/slot_based/block_builder_task.rs
  cumulus/client/consensus/aura/src/collators/slot_based/mod.rs
  cumulus/polkadot-omni-node/lib/src/cli.rs
  cumulus/polkadot-omni-node/lib/src/common/mod.rs
  cumulus/polkadot-omni-node/lib/src/nodes/aura.rs
  cumulus/test/service/src/lib.rs
  prdoc/pr_8040.prdoc
  templates/parachain/node/src/service.rs
Labels: A4-backport-stable2412, A4-backport-stable2503

#7286 Cleanup Elastic Scaling Checks for FeatureIndex::ElasticScalingMVP
  Cargo.lock
  polkadot/node/core/backing/Cargo.toml
  polkadot/node/core/backing/src/lib.rs
  polkadot/node/core/backing/src/tests/mod.rs
  polkadot/node/core/provisioner/Cargo.toml
  polkadot/node/core/provisioner/src/lib.rs
  polkadot/node/core/provisioner/src/tests.rs
  polkadot/node/test/service/src/chain_spec.rs
  prdoc/pr_7286.prdoc
Labels: T8-polkadot

#7983 [XCM] allow signed account to be aliased between system chains
  Cargo.lock
  cumulus/parachains/common/src/xcm_config.rs
  cumulus/parachains/integration-tests/emulated/common/src/macros.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/aliases.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/aliases.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/src/tests/aliases.rs
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-westend/src/tests/aliases.rs
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/aliases.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/identity.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/people/people-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/testing/penpal/src/xcm_config.rs
  prdoc/pr_7983.prdoc
Labels: T6-XCM, A4-backport-stable2503

#8063 Bridges: Add initial primitives for AssetHub bridging
  Cargo.lock
  bridges/chains/chain-asset-hub-rococo/Cargo.toml
  bridges/chains/chain-asset-hub-rococo/src/lib.rs
  bridges/chains/chain-asset-hub-westend/Cargo.toml
  bridges/chains/chain-asset-hub-westend/src/lib.rs
  bridges/chains/chain-bridge-hub-cumulus/src/lib.rs
  prdoc/pr_8063.prdoc
Labels: T15-bridges

#8057 Remove primitives
  Cargo.lock
  Cargo.toml
  bridges/chains/chain-bridge-hub-kusama/Cargo.toml
  bridges/chains/chain-bridge-hub-kusama/src/lib.rs
  bridges/chains/chain-bridge-hub-polkadot/Cargo.toml
  bridges/chains/chain-bridge-hub-polkadot/src/lib.rs
  bridges/chains/chain-kusama/Cargo.toml
  bridges/chains/chain-kusama/src/lib.rs
  bridges/chains/chain-polkadot/Cargo.toml
  bridges/chains/chain-polkadot/src/lib.rs
  bridges/testing/README.md
  bridges/testing/run-test.sh
  prdoc/pr_8057.prdoc
  umbrella/Cargo.toml
  umbrella/src/lib.rs
Labels: T15-bridges

#8071 Update zombienet version to `1.3.127`
  .gitlab/pipeline/zombienet.yml
Labels: R0-silent, T10-tests

#7703 Voting hook
  polkadot/runtime/rococo/src/governance/mod.rs
  polkadot/runtime/westend/src/governance/mod.rs
  prdoc/pr_7703.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/conviction-voting/src/benchmarking.rs
  substrate/frame/conviction-voting/src/lib.rs
  substrate/frame/conviction-voting/src/tests.rs
  substrate/frame/conviction-voting/src/traits.rs
  substrate/frame/conviction-voting/src/vote.rs
Labels: T2-pallets

#8062 frame-system: Don't underflow the sufficients
  prdoc/pr_8062.prdoc
  substrate/frame/system/src/lib.rs
  substrate/frame/system/src/tests.rs
Labels: T1-FRAME

#7933 [Staking] Extrinsic `migrate_currency` handles any scenario where an old staking lock exists
  polkadot/runtime/westend/src/tests.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/tests.rs
Labels: R0-silent, I2-bug, T2-pallets, A4-backport-stable2503

#8000 Optimize origin checks
  bridges/snowbridge/pallets/system/src/mock.rs
  bridges/snowbridge/runtime/runtime-common/src/v2/register_token.rs
  cumulus/parachains/runtimes/assets/common/src/foreign_creators.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/ambassador/origins.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/fellowship/origins.rs
  polkadot/runtime/rococo/src/governance/origins.rs
  polkadot/runtime/westend/src/governance/origins.rs
  polkadot/xcm/pallet-xcm/src/lib.rs
  prdoc/pr_8000.prdoc
  substrate/frame/collective/src/lib.rs
  substrate/frame/ranked-collective/src/lib.rs
  substrate/frame/society/src/lib.rs
  substrate/frame/support/src/lib.rs
  substrate/frame/support/src/traits/dispatch.rs
  substrate/frame/system/src/lib.rs
  substrate/frame/treasury/src/tests.rs
Labels: T1-FRAME

#8020 Snowbridge - Various minor improvements
  Cargo.lock
  bridges/snowbridge/pallets/ethereum-client/Cargo.toml
  bridges/snowbridge/pallets/ethereum-client/fixtures/Cargo.toml
  bridges/snowbridge/pallets/ethereum-client/fixtures/src/lib.rs
  bridges/snowbridge/pallets/ethereum-client/src/impls.rs
  bridges/snowbridge/pallets/ethereum-client/src/mock.rs
  bridges/snowbridge/pallets/ethereum-client/src/mock_electra.rs
  bridges/snowbridge/pallets/ethereum-client/src/tests.rs
  bridges/snowbridge/pallets/ethereum-client/src/tests_electra.rs
  bridges/snowbridge/pallets/inbound-queue-v2/Cargo.toml
  bridges/snowbridge/pallets/inbound-queue-v2/fixtures/src/register_token.rs
  bridges/snowbridge/pallets/inbound-queue-v2/src/lib.rs
  bridges/snowbridge/pallets/inbound-queue-v2/src/mock.rs
  bridges/snowbridge/pallets/inbound-queue-v2/src/test.rs
  bridges/snowbridge/pallets/inbound-queue/fixtures/src/register_token.rs
  bridges/snowbridge/pallets/inbound-queue/fixtures/src/send_native_eth.rs
  bridges/snowbridge/pallets/inbound-queue/fixtures/src/send_token.rs
  bridges/snowbridge/pallets/inbound-queue/fixtures/src/send_token_to_penpal.rs
  bridges/snowbridge/pallets/outbound-queue-v2/Cargo.toml
  bridges/snowbridge/pallets/outbound-queue-v2/src/benchmarking.rs
  bridges/snowbridge/pallets/outbound-queue-v2/src/fixture.rs
  bridges/snowbridge/pallets/outbound-queue-v2/src/lib.rs
  bridges/snowbridge/pallets/outbound-queue-v2/src/mock.rs
  bridges/snowbridge/pallets/outbound-queue-v2/src/process_message_impl.rs
  bridges/snowbridge/pallets/outbound-queue-v2/src/send_message_impl.rs
  bridges/snowbridge/pallets/outbound-queue-v2/src/test.rs
  bridges/snowbridge/pallets/system-frontend/src/mock.rs
  bridges/snowbridge/pallets/system-v2/src/benchmarking.rs
  bridges/snowbridge/pallets/system-v2/src/mock.rs
  bridges/snowbridge/primitives/inbound-queue/src/lib.rs
  bridges/snowbridge/primitives/outbound-queue/src/v1/message.rs
  bridges/snowbridge/primitives/outbound-queue/src/v2/converter/convert.rs
  bridges/snowbridge/primitives/outbound-queue/src/v2/converter/tests.rs
  bridges/snowbridge/primitives/outbound-queue/src/v2/delivery_receipt.rs
  bridges/snowbridge/primitives/verification/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/snowbridge.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge_v2_outbound.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/bridge_to_ethereum_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/bridge_to_ethereum_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/snowbridge_pallet_outbound_queue_v2.rs
  cumulus/parachains/runtimes/constants/src/westend.rs
Labels: R0-silent, A4-backport-stable2503

#8070 link-checker: Remove broken URL to claim statement.
  .config/lychee.toml
Labels: R0-silent, T1-FRAME

#8094 fix(substrate/client): cast `MAJOR_SYNC_BLOCKS` to usize
  substrate/client/network/sync/src/strategy/chain_sync.rs
Labels: R0-silent

#7449 network: remove handling of validation protocol versions 1 and 2
  Cargo.lock
  polkadot/node/core/approval-voting-parallel/src/lib.rs
  polkadot/node/core/approval-voting-parallel/src/tests.rs
  polkadot/node/network/approval-distribution/src/lib.rs
  polkadot/node/network/approval-distribution/src/tests.rs
  polkadot/node/network/bitfield-distribution/Cargo.toml
  polkadot/node/network/bitfield-distribution/src/lib.rs
  polkadot/node/network/bitfield-distribution/src/tests.rs
  polkadot/node/network/bridge/src/network.rs
  polkadot/node/network/bridge/src/rx/mod.rs
  polkadot/node/network/bridge/src/rx/tests.rs
  polkadot/node/network/bridge/src/tx/mod.rs
  polkadot/node/network/bridge/src/tx/tests.rs
  polkadot/node/network/protocol/src/peer_set.rs
  polkadot/node/network/statement-distribution/benches/statement-distribution-regression-bench.rs
  polkadot/node/network/statement-distribution/src/error.rs
  polkadot/node/network/statement-distribution/src/legacy_v1/mod.rs
  polkadot/node/network/statement-distribution/src/legacy_v1/requester.rs
  polkadot/node/network/statement-distribution/src/legacy_v1/responder.rs
  polkadot/node/network/statement-distribution/src/legacy_v1/tests.rs
  polkadot/node/network/statement-distribution/src/lib.rs
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  polkadot/node/network/statement-distribution/src/v2/tests/cluster.rs
  polkadot/node/network/statement-distribution/src/v2/tests/grid.rs
  polkadot/node/network/statement-distribution/src/v2/tests/mod.rs
  polkadot/node/network/statement-distribution/src/v2/tests/requests.rs
  polkadot/node/service/src/builder/mod.rs
  polkadot/node/service/src/overseer.rs
  polkadot/node/subsystem-bench/src/cli/subsystem-bench.rs
  polkadot/node/subsystem-bench/src/lib/availability/test_state.rs
  polkadot/node/subsystem-bench/src/lib/mock/network_bridge.rs
  polkadot/node/subsystem-bench/src/lib/statement/mod.rs
  polkadot/roadmap/implementers-guide/src/node/backing/statement-distribution-legacy.md
  prdoc/pr_7449.prdoc
Labels: T8-polkadot

#6630 Migrate `pallet-tx-pause` to umbrella crate
  Cargo.lock
  substrate/frame/src/lib.rs
  substrate/frame/tx-pause/Cargo.toml
  substrate/frame/tx-pause/src/benchmarking.rs
  substrate/frame/tx-pause/src/lib.rs
  substrate/frame/tx-pause/src/mock.rs
  substrate/frame/tx-pause/src/tests.rs
  substrate/frame/tx-pause/src/weights.rs
Labels: R0-silent, T1-FRAME

#8104 Stabilize V2 archive RPC methods
  prdoc/pr_8104.prdoc
  substrate/client/rpc-spec-v2/src/archive/api.rs
  substrate/client/rpc-spec-v2/src/archive/archive.rs
  substrate/client/rpc-spec-v2/src/archive/tests.rs
  substrate/client/rpc-spec-v2/src/chain_head/api.rs
Labels: T3-RPC_API, R1-breaking_change
