Repository paritytech/polkadot-sdk, pull requests merged in 2025-06, with the labels that each got.

#8708 feat: add collator peer ID to ParachainInherentData
  cumulus/client/parachain-inherent/src/lib.rs
  cumulus/client/parachain-inherent/src/mock.rs
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/parachain-system/src/mock.rs
  cumulus/pallets/parachain-system/src/tests.rs
  cumulus/parachains/runtimes/test-utils/src/lib.rs
  cumulus/primitives/parachain-inherent/src/lib.rs
  cumulus/test/client/src/block_builder.rs
  cumulus/test/service/src/bench_utils.rs
  cumulus/xcm/xcm-emulator/src/lib.rs
  prdoc/pr_8708.prdoc
Labels: T9-cumulus

#8662 [pallet-revive] update dry-run logic
  cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
  prdoc/pr_8662.prdoc
  substrate/frame/revive/rpc/src/tests.rs
  substrate/frame/revive/src/call_builder.rs
  substrate/frame/revive/src/evm/runtime.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/exec/tests.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/test_utils/builder.rs
  substrate/frame/revive/src/tests.rs
Labels: T7-smart_contracts

#8718 Record ed as part of the storage deposit
  prdoc/pr_8718.prdoc
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/exec/tests.rs
  substrate/frame/revive/src/storage/meter.rs
Labels: T7-smart_contracts

#8704 [AHM] Report the weights of epmb pallet to expose kusama and polkadot weights
  prdoc/pr_8704.prdoc
  substrate/frame/election-provider-multi-block/src/lib.rs
  substrate/frame/election-provider-multi-block/src/signed/mod.rs
  substrate/frame/election-provider-multi-block/src/template.hbs
  substrate/frame/election-provider-multi-block/src/unsigned/mod.rs
  substrate/frame/election-provider-multi-block/src/verifier/impls.rs
  substrate/frame/election-provider-multi-block/src/verifier/mod.rs
  substrate/frame/election-provider-multi-block/src/weights/comp_weights.sh
  substrate/frame/election-provider-multi-block/src/weights/display_weights.sh
  substrate/frame/election-provider-multi-block/src/weights/kusama/measured/pallet_election_provider_multi_block.rs
  substrate/frame/election-provider-multi-block/src/weights/kusama/measured/pallet_election_provider_multi_block_signed.rs
  substrate/frame/election-provider-multi-block/src/weights/kusama/measured/pallet_election_provider_multi_block_unsigned.rs
  substrate/frame/election-provider-multi-block/src/weights/kusama/measured/pallet_election_provider_multi_block_verifier.rs
  substrate/frame/election-provider-multi-block/src/weights/measured/mod.rs
  substrate/frame/election-provider-multi-block/src/weights/measured/pallet_election_provider_multi_block.rs
  substrate/frame/election-provider-multi-block/src/weights/measured/pallet_election_provider_multi_block_signed.rs
  substrate/frame/election-provider-multi-block/src/weights/measured/pallet_election_provider_multi_block_unsigned.rs
  substrate/frame/election-provider-multi-block/src/weights/measured/pallet_election_provider_multi_block_verifier.rs
  substrate/frame/election-provider-multi-block/src/weights/mod.rs
  substrate/frame/election-provider-multi-block/src/weights/pallet_election_provider_multi_block_dot_size.rs
  substrate/frame/election-provider-multi-block/src/weights/pallet_election_provider_multi_block_ksm_size.rs
  substrate/frame/election-provider-multi-block/src/weights/pallet_election_provider_multi_block_signed_dot_size.rs
  substrate/frame/election-provider-multi-block/src/weights/pallet_election_provider_multi_block_signed_ksm_size.rs
  substrate/frame/election-provider-multi-block/src/weights/pallet_election_provider_multi_block_unsigned_dot_size.rs
  substrate/frame/election-provider-multi-block/src/weights/pallet_election_provider_multi_block_unsigned_ksm_size.rs
  substrate/frame/election-provider-multi-block/src/weights/pallet_election_provider_multi_block_verifier_dot_size.rs
  substrate/frame/election-provider-multi-block/src/weights/pallet_election_provider_multi_block_verifier_ksm_size.rs
  substrate/frame/election-provider-multi-block/src/weights/polkadot/measured/pallet_election_provider_multi_block.rs
  substrate/frame/election-provider-multi-block/src/weights/polkadot/measured/pallet_election_provider_multi_block_signed.rs
  substrate/frame/election-provider-multi-block/src/weights/polkadot/measured/pallet_election_provider_multi_block_unsigned.rs
  substrate/frame/election-provider-multi-block/src/weights/polkadot/measured/pallet_election_provider_multi_block_verifier.rs
  substrate/frame/election-provider-multi-block/src/weights/zero.rs
  substrate/frame/staking-async/ahm-test/src/ah/mock.rs
  substrate/frame/staking-async/runtimes/parachain/bench.sh
  substrate/frame/staking-async/runtimes/parachain/bench_all.sh
  substrate/frame/staking-async/runtimes/parachain/src/staking.rs
Labels: T2-pallets

#8709 Unflake `returns_status_for_pruned_blocks`
  substrate/client/service/test/src/client/mod.rs
Labels: R0-silent, T10-tests

#8461 client/net: Use litep2p as the default network backend
  Cargo.lock
  Cargo.toml
  cumulus/client/relay-chain-inprocess-interface/src/lib.rs
  cumulus/client/relay-chain-minimal-node/src/lib.rs
  cumulus/polkadot-omni-node/lib/src/common/spec.rs
  cumulus/polkadot-omni-node/lib/src/nodes/mod.rs
  cumulus/test/service/src/lib.rs
  cumulus/test/service/src/main.rs
  polkadot/node/metrics/src/tests.rs
  polkadot/node/service/src/lib.rs
  polkadot/node/test/service/src/lib.rs
  polkadot/node/test/service/tests/build-blocks.rs
  polkadot/node/test/service/tests/call-function.rs
  polkadot/parachain/test-parachains/adder/collator/tests/integration.rs
  polkadot/parachain/test-parachains/undying/collator/tests/integration.rs
  prdoc/pr_8461.prdoc
  substrate/bin/node/cli/src/service.rs
  substrate/client/cli/src/params/network_params.rs
  substrate/client/network/src/config.rs
  substrate/client/network/src/litep2p/shim/request_response/mod.rs
  substrate/client/service/src/lib.rs
  templates/minimal/node/src/command.rs
  templates/solochain/node/src/command.rs
Labels: T0-node, A4-backport-stable2409, A4-backport-stable2503

#8164 [PoP] Add personhood tracking pallets
  Cargo.lock
  Cargo.toml
  prdoc/pr_8164.prdoc
  substrate/frame/dummy-dim/Cargo.toml
  substrate/frame/dummy-dim/README.md
  substrate/frame/dummy-dim/src/benchmarking.rs
  substrate/frame/dummy-dim/src/lib.rs
  substrate/frame/dummy-dim/src/mock.rs
  substrate/frame/dummy-dim/src/tests.rs
  substrate/frame/dummy-dim/src/weights.rs
  substrate/frame/origin-restriction/Cargo.toml
  substrate/frame/origin-restriction/src/benchmarking.rs
  substrate/frame/origin-restriction/src/lib.rs
  substrate/frame/origin-restriction/src/mock.rs
  substrate/frame/origin-restriction/src/tests.rs
  substrate/frame/origin-restriction/src/weights.rs
  substrate/frame/people/Cargo.toml
  substrate/frame/people/README.md
  substrate/frame/people/src/benchmarking.rs
  substrate/frame/people/src/extension.rs
  substrate/frame/people/src/lib.rs
  substrate/frame/people/src/mock.rs
  substrate/frame/people/src/tests.rs
  substrate/frame/people/src/types.rs
  substrate/frame/people/src/weights.rs
  substrate/frame/support/src/traits.rs
  substrate/frame/support/src/traits/reality.rs
  substrate/frame/system/src/extensions/check_nonce.rs
  substrate/frame/system/src/lib.rs
  umbrella/Cargo.toml
  umbrella/src/lib.rs
Labels: T1-FRAME

#8731 Handle and suppress "New unknown `FromSwarm` libp2p event" warning
  substrate/client/network/src/discovery.rs
  substrate/client/network/src/peer_info.rs
  substrate/client/network/src/protocol/notifications/behaviour.rs
Labels: R0-silent, T0-node

#8594 omni-node: fix `benchmark pallet` to work with `--runtime`
  cumulus/polkadot-omni-node/lib/src/command.rs
  prdoc/pr_8594.prdoc
  substrate/utils/frame/benchmarking-cli/src/pallet/command.rs
  substrate/utils/frame/omni-bencher/src/command.rs
Labels: I2-bug

#8749 Don't read storage items in logging
  docs/sdk/src/reference_docs/frame_logging.rs
  substrate/frame/staking-async/src/pallet/impls.rs
Labels: R0-silent

#8702 [AHM] Relax the requirement for RC-Client to receive +1 session reports
  prdoc/pr_8702.prdoc
  substrate/frame/staking-async/ahm-test/src/ah/test.rs
  substrate/frame/staking-async/ahm-test/src/lib.rs
  substrate/frame/staking-async/rc-client/src/lib.rs
  substrate/frame/staking-async/src/session_rotation.rs
Labels: T2-pallets

#8745 Actually use RP offset in YAP parachain
  cumulus/parachains/runtimes/testing/yet-another-parachain/src/lib.rs
  prdoc/pr_8745.prdoc
Labels: T9-cumulus

#8715 [AHM] Prepare For Westend Cleanup
  prdoc/pr_8715.prdoc
  substrate/frame/balances/src/types.rs
  substrate/frame/conviction-voting/src/types.rs
  substrate/frame/conviction-voting/src/vote.rs
  substrate/frame/election-provider-multi-block/src/lib.rs
  substrate/frame/election-provider-multi-block/src/types.rs
  substrate/frame/nomination-pools/src/lib.rs
  substrate/frame/proxy/src/lib.rs
  substrate/frame/referenda/src/types.rs
  substrate/frame/scheduler/src/lib.rs
  substrate/frame/staking-async/src/ledger.rs
  substrate/frame/staking-async/src/lib.rs
  substrate/frame/staking-async/src/pallet/mod.rs
  substrate/frame/staking/src/ledger.rs
  substrate/frame/staking/src/lib.rs
  substrate/frame/staking/src/pallet/mod.rs
  substrate/frame/staking/src/slashing.rs
  substrate/frame/sudo/src/lib.rs
  substrate/frame/support/src/lib.rs
  substrate/frame/support/src/traits.rs
  substrate/frame/support/src/traits/misc.rs
Labels: T1-FRAME, T2-pallets

#6827 Introduction of Approval Slashes [Disabling Strategy Stage 4]
  polkadot/primitives/src/v8/slashing.rs
  polkadot/primitives/src/vstaging/mod.rs
  polkadot/runtime/parachains/src/disputes.rs
  polkadot/runtime/parachains/src/disputes/slashing.rs
  polkadot/runtime/parachains/src/disputes/slashing/benchmarking.rs
  prdoc/pr_6827.prdoc
Labels: I1-security, T8-polkadot, A4-backport-stable2503

#8771 [stable2503] Prepare stable2503-6 release
  Cargo.lock
  Plan.toml
  bridges/snowbridge/pallets/inbound-queue-v2/Cargo.toml
  bridges/snowbridge/pallets/inbound-queue/Cargo.toml
  bridges/snowbridge/pallets/system-v2/Cargo.toml
  bridges/snowbridge/pallets/system/Cargo.toml
  bridges/snowbridge/primitives/inbound-queue/Cargo.toml
  bridges/snowbridge/primitives/outbound-queue/Cargo.toml
  bridges/snowbridge/test-utils/Cargo.toml
  cumulus/client/consensus/aura/Cargo.toml
  cumulus/client/relay-chain-inprocess-interface/Cargo.toml
  cumulus/client/relay-chain-minimal-node/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/polkadot-omni-node/lib/Cargo.toml
  cumulus/polkadot-omni-node/lib/src/nodes/mod.rs
  polkadot/node/primitives/src/lib.rs
  polkadot/node/service/Cargo.toml
  prdoc/stable2503-6/pr_8461.prdoc
  prdoc/stable2503-6/pr_8473.prdoc
  prdoc/stable2503-6/pr_8630.prdoc
  prdoc/stable2503-6/pr_8650.prdoc
  prdoc/stable2503-6/pr_8669.prdoc
  substrate/client/cli/Cargo.toml
  substrate/client/network/Cargo.toml
  substrate/client/network/types/Cargo.toml
  substrate/client/offchain/Cargo.toml
  substrate/frame/broker/Cargo.toml
Labels: R0-silent

#8179 Do not make pallet-identity benchmarks signature-dependent
  cumulus/parachains/runtimes/people/people-rococo/src/people.rs
  cumulus/parachains/runtimes/people/people-westend/src/people.rs
  polkadot/runtime/common/src/integration_tests.rs
  polkadot/runtime/rococo/src/lib.rs
  polkadot/runtime/westend/src/lib.rs
  prdoc/pr_8179.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/alliance/src/mock.rs
  substrate/frame/identity/src/benchmarking.rs
  substrate/frame/identity/src/lib.rs
  substrate/frame/identity/src/tests.rs
  substrate/frame/staking-async/runtimes/rc/src/lib.rs
Labels: T2-pallets

#8790 Docker hub 'master' image short sha
  .github/actions/build-push-image/action.yml
Labels: R0-silent

#8725 Snowbridge: enforce fee when registering Polkadot native asset
  bridges/snowbridge/pallets/system-frontend/src/backend_weights.rs
  bridges/snowbridge/pallets/system-frontend/src/benchmarking.rs
  bridges/snowbridge/pallets/system-frontend/src/lib.rs
  bridges/snowbridge/pallets/system-frontend/src/mock.rs
  bridges/snowbridge/pallets/system-frontend/src/tests.rs
  bridges/snowbridge/pallets/system-v2/src/benchmarking.rs
  bridges/snowbridge/pallets/system-v2/src/lib.rs
  bridges/snowbridge/pallets/system-v2/src/tests.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge_v2_outbound.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge_v2_outbound_edge_case.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge_v2_outbound_from_rococo.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/bridge_to_ethereum_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/snowbridge_pallet_system_backend.rs
  prdoc/pr_8725.prdoc
Labels: T15-bridges, A4-backport-stable2503, A4-backport-stable2506

#8795 Update `RemoteExporter` docs to reflect removal of `forward_id_for`
  polkadot/xcm/xcm-builder/src/universal_exports.rs
Labels: R0-silent, T6-XCM

#8799 Fix typos in 3 files in Implementers Guide
  docs/contributor/CONTRIBUTING.md
  polkadot/roadmap/implementers-guide/src/node/availability/availability-recovery.md
  polkadot/roadmap/implementers-guide/src/node/backing/statement-distribution.md
  polkadot/roadmap/implementers-guide/src/runtime-api/candidate-pending-availability.md
Labels: R0-silent

#8801 rename the name of new staking pallets in all runtimes
  cumulus/pallets/ah-ops/src/benchmarking.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/staking.rs
  polkadot/runtime/westend/src/lib.rs
  substrate/frame/staking-async/runtimes/parachain/src/lib.rs
  substrate/frame/staking-async/runtimes/parachain/src/staking.rs
  substrate/frame/staking-async/runtimes/rc/src/genesis_config_presets.rs
  substrate/frame/staking-async/runtimes/rc/src/lib.rs
Labels: R0-silent

#8693 Add XCM Precompile to `pallet-xcm`
  Cargo.lock
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/pallet_xcm.rs
  polkadot/runtime/rococo/src/weights/pallet_xcm.rs
  polkadot/runtime/westend/src/weights/pallet_xcm.rs
  polkadot/xcm/pallet-xcm/Cargo.toml
  polkadot/xcm/pallet-xcm/src/benchmarking.rs
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/pallet-xcm/src/precompiles.rs
  polkadot/xcm/pallet-xcm/src/precompiles/IXcm.sol
  prdoc/pr_8693.prdoc
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/precompiles/builtin/modexp.rs
  substrate/frame/staking-async/runtimes/parachain/src/weights/pallet_xcm.rs
  substrate/frame/staking-async/runtimes/rc/src/weights/pallet_xcm.rs
Labels: T6-XCM

#8816 release/build-macos-binaries: add missing FEATURES argument
  .github/scripts/release/build-macos-release.sh
  .github/workflows/release-reusable-rc-build.yml
Labels: R0-silent, A4-backport-stable2412, A4-backport-stable2503, A4-backport-stable2506

#8794 renamed wasm module in pallet-revive to vm
  prdoc/pr_8794.prdoc
  substrate/frame/revive/README.md
  substrate/frame/revive/fixtures/src/lib.rs
  substrate/frame/revive/proc-macro/src/lib.rs
  substrate/frame/revive/src/benchmarking.rs
  substrate/frame/revive/src/call_builder.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/exec/tests.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/precompiles.rs
  substrate/frame/revive/src/precompiles/builtin/blake2f.rs
  substrate/frame/revive/src/precompiles/builtin/bn128.rs
  substrate/frame/revive/src/precompiles/builtin/ecrecover.rs
  substrate/frame/revive/src/precompiles/builtin/identity.rs
  substrate/frame/revive/src/precompiles/builtin/modexp.rs
  substrate/frame/revive/src/precompiles/builtin/ripemd160.rs
  substrate/frame/revive/src/precompiles/builtin/sha256.rs
  substrate/frame/revive/src/precompiles/tests.rs
  substrate/frame/revive/src/primitives.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/vm/mod.rs
  substrate/frame/revive/src/vm/runtime.rs
Labels: T2-pallets

#8832 increase session index cache
  polkadot/node/subsystem-util/src/runtime/mod.rs
  prdoc/pr_8832.prdoc
Labels: A4-backport-stable2503, A4-backport-stable2506

#8742 [pallet-revive] prestate tracer
  prdoc/pr_8742.prdoc
  substrate/frame/revive/rpc/revive_chain.metadata
  substrate/frame/revive/rpc/src/apis/debug_apis.rs
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/rpc/src/client/runtime_api.rs
  substrate/frame/revive/rpc/src/lib.rs
  substrate/frame/revive/rpc/src/receipt_extractor.rs
  substrate/frame/revive/src/benchmarking.rs
  substrate/frame/revive/src/evm/api/debug_rpc_types.rs
  substrate/frame/revive/src/evm/runtime.rs
  substrate/frame/revive/src/evm/tracing.rs
  substrate/frame/revive/src/evm/tracing/prestate_tracing.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/storage.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/tracing.rs
  substrate/frame/revive/src/vm/runtime.rs
Labels: T7-smart_contracts

#8829 Eth transaction do not double bump the nonce
  cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
  prdoc/pr_8829.prdoc
  substrate/frame/revive/rpc/src/tests.rs
  substrate/frame/revive/src/call_builder.rs
  substrate/frame/revive/src/evm/runtime.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/exec/tests.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/primitives.rs
  substrate/frame/revive/src/test_utils/builder.rs
  substrate/frame/revive/src/tests.rs
Labels: T7-smart_contracts

#8666 EPMB: Handle empty solution pages gracefully in verifier
  prdoc/pr_8666.prdoc
  substrate/frame/election-provider-multi-block/src/lib.rs
  substrate/frame/election-provider-multi-block/src/mock/mod.rs
  substrate/frame/election-provider-multi-block/src/mock/signed.rs
  substrate/frame/election-provider-multi-block/src/signed/mod.rs
  substrate/frame/election-provider-multi-block/src/signed/tests.rs
  substrate/frame/election-provider-multi-block/src/types.rs
  substrate/frame/election-provider-multi-block/src/unsigned/miner.rs
  substrate/frame/election-provider-multi-block/src/unsigned/mod.rs
  substrate/frame/election-provider-multi-block/src/verifier/benchmarking.rs
  substrate/frame/election-provider-multi-block/src/verifier/impls.rs
  substrate/frame/election-provider-multi-block/src/verifier/mod.rs
  substrate/frame/election-provider-multi-block/src/verifier/tests.rs
  substrate/frame/staking-async/ahm-test/src/ah/test.rs
  substrate/frame/staking-async/runtimes/parachain/src/staking.rs
Labels: T2-pallets

#8436 Fix calling nominate on a validator that doesn’t exist silently succeeds
  prdoc/pr_8436.prdoc
  substrate/frame/staking-async/src/benchmarking.rs
  substrate/frame/staking-async/src/pallet/mod.rs
  substrate/frame/staking-async/src/tests/bonding.rs
  substrate/frame/staking-async/src/tests/election_data_provider.rs
  substrate/frame/staking-async/src/tests/election_provider.rs
Labels: T2-pallets

#8855 Mute a lot of logs in Staking-async and EPMB
  substrate/frame/election-provider-multi-block/src/lib.rs
  substrate/frame/election-provider-multi-block/src/signed/mod.rs
  substrate/frame/election-provider-multi-block/src/unsigned/miner.rs
  substrate/frame/election-provider-multi-block/src/unsigned/mod.rs
  substrate/frame/election-provider-multi-block/src/verifier/impls.rs
  substrate/frame/staking-async/src/pallet/impls.rs
  substrate/frame/staking-async/src/session_rotation.rs
Labels: R0-silent

#8537 Allow RelaychainDataProvider set_block_number to be used in tests
  cumulus/pallets/parachain-system/src/lib.rs
  prdoc/pr_8537.prdoc
Labels: T9-cumulus

#8781 [pallet-revive] fix call-trace create calls
  prdoc/pr_8781.prdoc
  substrate/frame/revive/fixtures/contracts/create2_with_value.rs
  substrate/frame/revive/rpc/revive_chain.metadata
  substrate/frame/revive/rpc/src/client/runtime_api.rs
  substrate/frame/revive/src/evm/api/debug_rpc_types.rs
  substrate/frame/revive/src/evm/tracing/call_tracing.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/tracing.rs
Labels: T7-smart_contracts

#8862 docs: fix XCM docs for AlwaysV4 and AlwaysV5
  polkadot/xcm/src/lib.rs
Labels: R0-silent, T11-documentation

#8878 Fix `zombienet-substrate-0002-validators-warp-sync`
  substrate/zombienet/0002-validators-warp-sync/test-validators-warp-sync.toml
  substrate/zombienet/0002-validators-warp-sync/test-validators-warp-sync.zndsl
Labels: R0-silent, T10-tests, T18-zombienet_tests

#8881 [pallet-revive] only record diff if value changed
  prdoc/pr_8881.prdoc
  substrate/frame/revive/src/evm/tracing/prestate_tracing.rs
Labels: T7-smart_contracts

#8897 [pallet-revive-rpc] fix sqlite in-memory connection pool issue
  prdoc/pr_8897.prdoc
  substrate/frame/revive/rpc/src/cli.rs
  substrate/frame/revive/rpc/src/receipt_provider.rs
Labels: R0-silent, T7-smart_contracts

#8903 ParachainSystem: Do not emit the `SelectCore` digest
  cumulus/pallets/parachain-system/src/lib.rs
  prdoc/pr_8903.prdoc
Labels: A4-backport-stable2506

#8922 fix shared-core-idle-parachain test
  .github/workflows/zombienet_polkadot.yml
  polkadot/runtime/parachains/src/paras/mod.rs
  polkadot/zombienet-sdk-tests/tests/functional/mod.rs
  polkadot/zombienet-sdk-tests/tests/functional/shared_core_idle_parachain.rs
  polkadot/zombienet_tests/functional/0018-shared-core-idle-parachain.toml
  polkadot/zombienet_tests/functional/0018-shared-core-idle-parachain.zndsl
  prdoc/pr_8922.prdoc
Labels: T18-zombienet_tests

#8925 Multisig::as_multi_threshold_1: Send `MultisigExecuted` event
  prdoc/pr_8925.prdoc
  substrate/frame/multisig/src/lib.rs
  substrate/frame/multisig/src/tests.rs
Labels: T2-pallets, A4-backport-stable2506

#8949 [stable2412] Preparations for the patch release stable2412-7
  Cargo.lock
  Cargo.toml
  Plan.toml
  bridges/modules/xcm-bridge-hub/Cargo.toml
  cumulus/client/consensus/aura/Cargo.toml
  cumulus/client/relay-chain-inprocess-interface/Cargo.toml
  cumulus/client/relay-chain-minimal-node/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-rococo/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-westend/Cargo.toml
  cumulus/polkadot-omni-node/lib/Cargo.toml
  cumulus/polkadot-omni-node/lib/src/nodes/mod.rs
  polkadot/node/primitives/src/lib.rs
  polkadot/node/service/Cargo.toml
  polkadot/xcm/pallet-xcm/Cargo.toml
  prdoc/stable2412-7/pr_8173.prdoc
  prdoc/stable2412-7/pr_8461.prdoc
  prdoc/stable2412-7/pr_8615.prdoc
  prdoc/stable2412-7/pr_8627.prdoc
  prdoc/stable2412-7/pr_8630.prdoc
  prdoc/stable2412-7/pr_8650.prdoc
  prdoc/stable2412-7/pr_8669.prdoc
  substrate/bin/utils/chain-spec-builder/README.md
  substrate/client/cli/Cargo.toml
  substrate/client/network/Cargo.toml
  substrate/client/network/types/Cargo.toml
  substrate/client/offchain/Cargo.toml
  substrate/frame/broker/Cargo.toml
  substrate/frame/scheduler/Cargo.toml
  umbrella/Cargo.toml
Labels: R0-silent

#8955 Token matching trait typo
  polkadot/xcm/xcm-executor/src/traits/token_matching.rs
Labels: R0-silent, T6-XCM

#8948 make sure dispute_coordinator/approval-voting parallel can receive priority messages
  polkadot/node/overseer/src/lib.rs
  polkadot/node/overseer/src/tests.rs
  polkadot/node/service/src/tests.rs
  prdoc/pr_8948.prdoc
Labels: A4-backport-stable2503, A4-backport-stable2506

#8894 remove enable_approval_voting_parallel cli flag
  cumulus/client/relay-chain-inprocess-interface/src/lib.rs
  polkadot/cli/src/cli.rs
  polkadot/cli/src/command.rs
  polkadot/node/core/dispute-coordinator/src/initialized.rs
  polkadot/node/core/dispute-coordinator/src/lib.rs
  polkadot/node/core/dispute-coordinator/src/tests.rs
  polkadot/node/network/bridge/src/rx/mod.rs
  polkadot/node/network/bridge/src/rx/tests.rs
  polkadot/node/overseer/src/lib.rs
  polkadot/node/service/src/builder/mod.rs
  polkadot/node/service/src/overseer.rs
  polkadot/node/service/src/relay_chain_selection.rs
  polkadot/node/service/src/tests.rs
  polkadot/node/subsystem-bench/src/lib/approval/mod.rs
  polkadot/node/subsystem-bench/src/lib/availability/mod.rs
  polkadot/node/subsystem-bench/src/lib/mock/network_bridge.rs
  polkadot/node/subsystem-bench/src/lib/statement/mod.rs
  polkadot/node/test/service/src/lib.rs
  polkadot/parachain/test-parachains/adder/collator/src/main.rs
  polkadot/parachain/test-parachains/undying/collator/src/main.rs
  prdoc/pr_8894.prdoc
Labels: T8-polkadot, T18-zombienet_tests

#8965 Decrease too wide line in markdown
  docs/contributor/DOCUMENTATION_GUIDELINES.md
Labels: R0-silent

#8596 `fatxpool`: limits handling optimizations and fixes
  Cargo.lock
  prdoc/pr_8596.prdoc
  substrate/client/transaction-pool/Cargo.toml
  substrate/client/transaction-pool/benches/basics.rs
  substrate/client/transaction-pool/src/common/api.rs
  substrate/client/transaction-pool/src/common/mod.rs
  substrate/client/transaction-pool/src/common/sliding_stat.rs
  substrate/client/transaction-pool/src/common/tests.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/revalidation_worker.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/tx_mem_pool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/tx_mem_pool/tx_mem_pool_map.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/view.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs
  substrate/client/transaction-pool/src/graph/mod.rs
  substrate/client/transaction-pool/src/graph/pool.rs
  substrate/client/transaction-pool/src/graph/tracked_map.rs
  substrate/client/transaction-pool/src/graph/validated_pool.rs
  substrate/client/transaction-pool/src/lib.rs
  substrate/client/transaction-pool/src/single_state_txpool/revalidation.rs
  substrate/client/transaction-pool/src/single_state_txpool/single_state_txpool.rs
  substrate/client/transaction-pool/tests/fatp.rs
  substrate/client/transaction-pool/tests/fatp_common/mod.rs
  substrate/client/transaction-pool/tests/fatp_invalid.rs
  substrate/client/transaction-pool/tests/fatp_limits.rs
  substrate/client/transaction-pool/tests/fatp_prios.rs
  substrate/test-utils/runtime/transaction-pool/src/lib.rs
Labels: R0-silent, T0-node

#8838 `fatxpool`: fork aware transaction pool is now default
  prdoc/pr_8838.prdoc
  substrate/client/cli/src/params/transaction_pool_params.rs
Labels: T0-node

#8938 Make `NoOpPoll` generic over `Moment`
  prdoc/pr_8938.prdoc
  substrate/frame/core-fellowship/src/tests/integration.rs
  substrate/frame/ranked-collective/src/benchmarking.rs
  substrate/frame/salary/src/tests/integration.rs
  substrate/frame/support/src/traits/voting.rs
Labels: T1-FRAME

#8836 `fatxpool`: `report_invalid` is now aync
  prdoc/pr_8836.prdoc
  substrate/bin/node/bench/src/construct.rs
  substrate/client/basic-authorship/src/basic_authorship.rs
  substrate/client/rpc-api/src/author/mod.rs
  substrate/client/rpc-spec-v2/src/transaction/tests/middleware_pool.rs
  substrate/client/rpc-spec-v2/src/transaction/transaction_broadcast.rs
  substrate/client/rpc/src/author/mod.rs
  substrate/client/transaction-pool/api/src/lib.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs
  substrate/client/transaction-pool/src/single_state_txpool/single_state_txpool.rs
  substrate/client/transaction-pool/src/transaction_pool_wrapper.rs
  substrate/client/transaction-pool/tests/fatp_invalid.rs
Labels: R0-silent, T0-node

#8973 Add polkadot_parachain_peer_connectivity metric
  polkadot/node/network/bridge/src/metrics.rs
  prdoc/pr_8973.prdoc
Labels: T0-node, T8-polkadot

#8752 transfer_assets benchmarking and weights for coretime chains
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-rococo/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-rococo/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-westend/src/tests/teleport.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/pallet_xcm.rs
  prdoc/pr_8752.prdoc
Labels: T6-XCM, T10-tests, T12-benchmarks

#8980 Fix revive-fixtures build script
  prdoc/pr_8980.prdoc
  substrate/frame/revive/fixtures/build.rs
Labels: T2-pallets, A4-backport-stable2506

#8875 `fatxpool`: `ChainApi` is now async
  Cargo.lock
  prdoc/pr_8875.prdoc
  substrate/client/transaction-pool/benches/basics.rs
  substrate/client/transaction-pool/src/common/api.rs
  substrate/client/transaction-pool/src/common/tests.rs
  substrate/client/transaction-pool/src/graph/pool.rs
  substrate/test-utils/runtime/transaction-pool/Cargo.toml
  substrate/test-utils/runtime/transaction-pool/src/lib.rs
Labels: T0-node

#8848 Snowbridge: Improve local and testnet setup
  Cargo.lock
  bridges/snowbridge/pallets/ethereum-client/fixtures/src/lib.rs
  bridges/snowbridge/pallets/ethereum-client/src/lib.rs
  bridges/snowbridge/pallets/ethereum-client/src/mock.rs
  bridges/snowbridge/pallets/ethereum-client/src/mock_electra.rs
  bridges/snowbridge/pallets/ethereum-client/src/tests_electra.rs
  bridges/snowbridge/pallets/ethereum-client/tests/electra/execution-proof.json
  bridges/snowbridge/pallets/ethereum-client/tests/electra/finalized-header-update.json
  bridges/snowbridge/pallets/ethereum-client/tests/electra/inbound-message.json
  bridges/snowbridge/pallets/ethereum-client/tests/electra/initial-checkpoint.json
  bridges/snowbridge/pallets/ethereum-client/tests/electra/next-finalized-header-update.json
  bridges/snowbridge/pallets/ethereum-client/tests/electra/next-sync-committee-update.json
  bridges/snowbridge/pallets/ethereum-client/tests/electra/sync-committee-update.json
  bridges/snowbridge/pallets/ethereum-client/tests/fixtures/execution-proof.json
  bridges/snowbridge/pallets/ethereum-client/tests/fixtures/finalized-header-update.json
  bridges/snowbridge/pallets/ethereum-client/tests/fixtures/inbound-message.json
  bridges/snowbridge/pallets/ethereum-client/tests/fixtures/initial-checkpoint.json
  bridges/snowbridge/pallets/ethereum-client/tests/fixtures/interim-finalized-header-update.json
  bridges/snowbridge/pallets/ethereum-client/tests/fixtures/next-finalized-header-update.json
  bridges/snowbridge/pallets/ethereum-client/tests/fixtures/next-sync-committee-update.json
  bridges/snowbridge/pallets/ethereum-client/tests/fixtures/sync-committee-update-period-0-newer.json
  bridges/snowbridge/pallets/ethereum-client/tests/fixtures/sync-committee-update-period-0-older.json
  bridges/snowbridge/pallets/ethereum-client/tests/fixtures/sync-committee-update-period-0.json
  bridges/snowbridge/pallets/ethereum-client/tests/fixtures/sync-committee-update.json
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_to_ethereum_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/bridge_to_ethereum_config.rs
  cumulus/parachains/runtimes/testing/penpal/Cargo.toml
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  prdoc/pr_8848.prdoc
Labels: T15-bridges

#8932 pallet-balances: Do not create account in benchmarking
  prdoc/pr_8932.prdoc
  substrate/frame/balances/src/benchmarking.rs
Labels: T2-pallets, A4-backport-stable2503, A4-backport-stable2506

#9014 contracts-fixtures: Rebuild `core` and `alloc` for MVP
  substrate/frame/contracts/fixtures/build.rs
Labels: R0-no-crate-publish-required

#8935 Fix prestate create traces
  .github/workflows/tests-evm.yml
  prdoc/pr_8935.prdoc
  substrate/frame/revive/src/evm/api/debug_rpc_types.rs
  substrate/frame/revive/src/evm/tracing/prestate_tracing.rs
  substrate/frame/revive/src/tests.rs
Labels: T7-smart_contracts

#8851 Add address revive runtime API
  prdoc/pr_8851.prdoc
  substrate/frame/revive/src/lib.rs
Labels: T7-smart_contracts

#9001 revive: Precompiles should return dummy code when queried
  .github/workflows/tests-evm.yml
  prdoc/pr_9001.prdoc
  substrate/frame/revive/rpc/revive_chain.metadata
  substrate/frame/revive/rpc/src/client/runtime_api.rs
  substrate/frame/revive/rpc/src/client/storage_api.rs
  substrate/frame/revive/rpc/src/lib.rs
  substrate/frame/revive/src/benchmarking.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/exec/tests.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/precompiles.rs
  substrate/frame/revive/src/precompiles/builtin.rs
  substrate/frame/revive/src/precompiles/tests.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/revive/src/vm/runtime.rs
  substrate/frame/revive/src/weights.rs
  substrate/frame/revive/uapi/src/host.rs
  substrate/frame/revive/uapi/src/host/riscv64.rs
Labels: T7-smart_contracts
