Repository paritytech/polkadot-sdk, pull requests merged in 2025-05, with the labels that each got.

#8373 networking: Update litep2p network backend to v0.9.4
  Cargo.lock
  Cargo.toml
  prdoc/pr_8373.prdoc
Labels: T0-node, A4-backport-stable2412, A4-backport-stable2503

#8307 fix westend's election currency to vote conversion
  polkadot/runtime/westend/src/lib.rs
  substrate/frame/staking-async/src/pallet/impls.rs
  substrate/frame/staking/src/pallet/impls.rs
  substrate/primitives/staking/src/currency_to_vote.rs
Labels: R0-silent

#8337 add staking/election related view functions
  prdoc/pr_8337.prdoc
  substrate/frame/bags-list/src/lib.rs
  substrate/frame/election-provider-multi-block/src/signed/mod.rs
Labels: T2-pallets

#8400 make assert_expected_events fail on missing event
  cumulus/xcm/xcm-emulator/src/lib.rs
Labels: R0-silent, T10-tests, A4-backport-stable2503

#8411 [stable2503] Fix macos build
  .github/workflows/release-reusable-rc-buid.yml
Labels: R0-silent

#8376 Remove TakeFirstAssetTrader from AH Westend and Rococo
  cumulus/parachains/integration-tests/emulated/common/src/macros.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/send.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/send.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/transact.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge_common.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge_v2_inbound.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/transact.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
  prdoc/pr_8376.prdoc
Labels: T6-XCM

#8314 Add methods in the statement store RPCs to get the statements and not just the statement data.
  prdoc/pr_8314.prdoc
  substrate/client/rpc-api/src/statement/mod.rs
  substrate/client/rpc/src/statement/mod.rs
  substrate/client/statement-store/src/lib.rs
  substrate/primitives/statement-store/src/store_api.rs
Labels: T0-node

#8240 Snowbridge V2 Audit Fixes
  Cargo.lock
  bridges/snowbridge/pallets/inbound-queue-v2/src/lib.rs
  bridges/snowbridge/pallets/inbound-queue-v2/src/mock.rs
  bridges/snowbridge/pallets/outbound-queue-v2/src/benchmarking.rs
  bridges/snowbridge/pallets/outbound-queue-v2/src/lib.rs
  bridges/snowbridge/pallets/outbound-queue-v2/src/test.rs
  bridges/snowbridge/pallets/system-frontend/src/lib.rs
  bridges/snowbridge/pallets/system-v2/src/lib.rs
  bridges/snowbridge/primitives/core/src/sparse_bitmap.rs
  bridges/snowbridge/primitives/inbound-queue/Cargo.toml
  bridges/snowbridge/primitives/inbound-queue/src/lib.rs
  bridges/snowbridge/primitives/inbound-queue/src/mock.rs
  bridges/snowbridge/primitives/inbound-queue/src/tests.rs
  bridges/snowbridge/primitives/inbound-queue/src/v1.rs
  bridges/snowbridge/primitives/inbound-queue/src/v2/converter.rs
  bridges/snowbridge/primitives/outbound-queue/src/v2/converter/mod.rs
  bridges/snowbridge/primitives/outbound-queue/src/v2/converter/tests.rs
  bridges/snowbridge/test-utils/Cargo.toml
  bridges/snowbridge/test-utils/src/lib.rs
  bridges/snowbridge/test-utils/src/mock_converter.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge_v2_outbound.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/bridge_to_ethereum_config.rs
  prdoc/pr_8240.prdoc
Labels: T15-bridges, A4-backport-stable2503

#8390 docs (DOCUMENTATION_GUIDELINES.md): fix invalid links
  docs/contributor/DOCUMENTATION_GUIDELINES.md
Labels: R0-silent

#8434 Properly fix template generation
  .github/workflows/misc-sync-templates.yml
  templates/parachain/Cargo.toml
Labels: R0-silent, T17-Templates

#8435 [CI] Adjust `check-semver` job so that it uses original PR number to check prdoc for the backports PRs
  .github/scripts/common/lib.sh
  .github/workflows/check-prdoc.yml
  .github/workflows/check-semver.yml
Labels: R0-silent, A4-backport-stable2409, A4-backport-stable2412, A4-backport-stable2503

#8405 DHT bootnodes: get randomness from the next epoch descriptor
  cumulus/client/bootnodes/src/advertisement.rs
Labels: R0-silent, T0-node, T9-cumulus

#7719 adding command export_chain_spec for polkadot-omni node
  Cargo.lock
  cumulus/polkadot-omni-node/Cargo.toml
  cumulus/polkadot-omni-node/lib/Cargo.toml
  cumulus/polkadot-omni-node/lib/src/command.rs
  cumulus/polkadot-omni-node/lib/src/extra_subcommand.rs
  cumulus/polkadot-omni-node/lib/src/lib.rs
  cumulus/polkadot-omni-node/src/main.rs
  cumulus/polkadot-omni-node/tests/extra_subcommand_parsing_test.rs
  cumulus/polkadot-parachain/Cargo.toml
  cumulus/polkadot-parachain/src/main.rs
  cumulus/polkadot-parachain/tests/extra_subcommand_parsing_test.rs
  cumulus/test/service/src/cli.rs
  cumulus/test/service/src/main.rs
  polkadot/cli/src/cli.rs
  polkadot/cli/src/command.rs
  prdoc/pr_7719.prdoc
  substrate/bin/node/cli/src/cli.rs
  substrate/bin/node/cli/src/command.rs
  substrate/client/cli/src/commands/export_chain_spec_cmd.rs
  substrate/client/cli/src/commands/mod.rs
  substrate/client/cli/src/lib.rs
  templates/minimal/node/src/cli.rs
  templates/minimal/node/src/command.rs
  templates/parachain/node/src/cli.rs
  templates/parachain/node/src/command.rs
  templates/solochain/node/src/cli.rs
  templates/solochain/node/src/command.rs
Labels: I5-enhancement, T9-cumulus, T17-Templates

#6931 Migrate pallet-paged-list to umbrella crate
  Cargo.lock
  substrate/frame/paged-list/Cargo.toml
  substrate/frame/paged-list/src/lib.rs
  substrate/frame/paged-list/src/mock.rs
  substrate/frame/paged-list/src/paged_list.rs
  substrate/frame/paged-list/src/tests.rs
  substrate/frame/src/lib.rs
Labels: R0-silent, T1-FRAME

#8441 Add all touched crates in #8327 to prdoc to fix release issue
  prdoc/pr_8327.prdoc
  prdoc/pr_8441.prdoc
Labels: R0-silent

#8447 Drop useless rep change.
  polkadot/node/network/dispute-distribution/src/receiver/mod.rs
  polkadot/node/network/dispute-distribution/src/tests/mod.rs
  prdoc/pr_8447.prdoc
Labels: T8-polkadot, A4-backport-stable2503

#8427 BEEFY: adjust equivocation slash fraction
  prdoc/pr_8427.prdoc
  substrate/frame/beefy/src/equivocation.rs
  substrate/frame/beefy/src/tests.rs
Labels: T15-bridges, A4-backport-stable2412, A4-backport-stable2503

#8351 XCM: treat BelowMinimum deposit errors as non-fatal and burn non-depositable dust
  polkadot/xcm/xcm-executor/src/lib.rs
  polkadot/xcm/xcm-executor/src/tests/initiate_transfer.rs
  polkadot/xcm/xcm-executor/src/tests/mock.rs
  prdoc/pr_8351.prdoc
Labels: T6-XCM

#8428 [Backport] Version bumps and prdocs reordering from stable2503-1 back to master
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/lib.rs
  cumulus/polkadot-omni-node/lib/src/nodes/mod.rs
  polkadot/node/primitives/src/lib.rs
  prdoc/stable2503-1/pr_7913.prdoc
  prdoc/stable2503-1/pr_7947.prdoc
  prdoc/stable2503-1/pr_8083.prdoc
  prdoc/stable2503-1/pr_8162.prdoc
  prdoc/stable2503-1/pr_8170.prdoc
  prdoc/stable2503-1/pr_8198.prdoc
  prdoc/stable2503-1/pr_8210.prdoc
  prdoc/stable2503-1/pr_8218.prdoc
  prdoc/stable2503-1/pr_8259.prdoc
  prdoc/stable2503-1/pr_8373.prdoc
Labels: R0-silent, A3-backport

#8370 fix(collator-protocol): address unneeded collator connection issue
  polkadot/node/network/collator-protocol/src/collator_side/mod.rs
  polkadot/node/network/collator-protocol/src/collator_side/tests/mod.rs
  prdoc/pr_8370.prdoc
Labels: I2-bug

#6905 Migrate pallet safe mode to umbrella crate
  Cargo.lock
  substrate/frame/safe-mode/Cargo.toml
  substrate/frame/safe-mode/src/benchmarking.rs
  substrate/frame/safe-mode/src/lib.rs
  substrate/frame/safe-mode/src/mock.rs
  substrate/frame/safe-mode/src/tests.rs
  substrate/frame/safe-mode/src/weights.rs
  substrate/frame/src/lib.rs
Labels: R0-silent, T2-pallets

#8459 Fix template generation
  .github/workflows/misc-sync-templates.yml
Labels: R0-silent

#8316 [StakingAsync] Remove SlashingSpan Logic
  prdoc/pr_8316.prdoc
  substrate/frame/staking-async/runtimes/parachain/src/weights/pallet_staking_async.rs
  substrate/frame/staking-async/src/benchmarking.rs
  substrate/frame/staking-async/src/mock.rs
  substrate/frame/staking-async/src/pallet/impls.rs
  substrate/frame/staking-async/src/pallet/mod.rs
  substrate/frame/staking-async/src/slashing.rs
  substrate/frame/staking-async/src/tests/bonding.rs
  substrate/frame/staking-async/src/tests/force_unstake_kill_stash.rs
  substrate/frame/staking-async/src/tests/mod.rs
  substrate/frame/staking-async/src/tests/slashing.rs
  substrate/frame/staking-async/src/weights.rs
  substrate/frame/staking/src/pallet/impls.rs
Labels: T2-pallets

#8468 [Release] Scripts to align stable branch with CI checks after the crates releases
  scripts/release/delete-version-from-umbrella.sh
  scripts/release/delete-versions-if-path-is-present.sh
  scripts/release/replace-all-path-deps.sh
Labels: R0-silent

#8483 No disputes and no CandidateReceiptV2 on Kusama
  Cargo.lock
  polkadot/cli/src/command.rs
  polkadot/node/collation-generation/src/lib.rs
  polkadot/node/core/dispute-coordinator/src/initialized.rs
  polkadot/node/core/dispute-coordinator/src/lib.rs
  polkadot/node/core/dispute-coordinator/src/participation/mod.rs
  polkadot/node/core/dispute-coordinator/src/tests.rs
  polkadot/node/network/collator-protocol/Cargo.toml
  polkadot/node/network/collator-protocol/src/validator_side/mod.rs
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  polkadot/node/network/statement-distribution/src/v2/tests/mod.rs
  polkadot/node/network/statement-distribution/src/v2/tests/requests.rs
  polkadot/zombienet-sdk-tests/tests/disabling/slashing.rs
  polkadot/zombienet_tests/functional/0004-parachains-garbage-candidate.zndsl
  polkadot/zombienet_tests/functional/0008-dispute-old-finalized.zndsl
  polkadot/zombienet_tests/functional/0010-validator-disabling.zndsl
Labels: R0-silent

#8484 Bump node version 1.18.3
  cumulus/polkadot-omni-node/lib/src/nodes/mod.rs
  polkadot/node/primitives/src/lib.rs
Labels: R0-silent

#8442 Align `zombienet-sdk`-based tests with breaking change
  .github/actions/zombienet-sdk/action.yml
  .github/workflows/zombienet_cumulus.yml
  .github/workflows/zombienet_polkadot.yml
  Cargo.lock
  Cargo.toml
  cumulus/zombienet/zombienet-sdk/Cargo.toml
  cumulus/zombienet/zombienet-sdk/tests/bootnodes/mod.rs
  polkadot/zombienet-sdk-tests/Cargo.toml
  polkadot/zombienet-sdk-tests/tests/disabling/slashing.rs
  polkadot/zombienet-sdk-tests/tests/functional/approved_peer_mixed_validators.rs
  polkadot/zombienet-sdk-tests/tests/functional/duplicate_collations.rs
  polkadot/zombienet-sdk-tests/tests/functional/spam_statement_distribution_requests.rs
Labels: R0-silent, T8-polkadot, T9-cumulus, T10-tests

#8477 FeeTracker deduplications
  Cargo.lock
  bridges/modules/xcm-bridge-hub-router/Cargo.toml
  bridges/modules/xcm-bridge-hub-router/src/lib.rs
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/xcmp-queue/src/lib.rs
  polkadot/runtime/common/src/xcm_sender.rs
  polkadot/runtime/parachains/src/dmp.rs
  polkadot/runtime/parachains/src/dmp/tests.rs
  polkadot/runtime/parachains/src/lib.rs
  prdoc/pr_8477.prdoc
Labels: T6-XCM, T15-bridges

#7980 `fatxpool`: optimize txs prunning based on inactive views provides tags
  Cargo.lock
  Cargo.toml
  prdoc/pr_7980.prdoc
  substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs
  substrate/client/transaction-pool/src/graph/pool.rs
  substrate/client/transaction-pool/src/single_state_txpool/single_state_txpool.rs
  substrate/client/transaction-pool/tests/fatp.rs
Labels: I9-optimisation

#8358 Migrate sync block test to zombienet sdk
  .github/workflows/zombienet_cumulus.yml
  cumulus/zombienet/tests/0001-sync_blocks_from_tip_without_connected_collator.toml
  cumulus/zombienet/tests/0001-sync_blocks_from_tip_without_connected_collator.zndsl
  cumulus/zombienet/zombienet-sdk/tests/lib.rs
  cumulus/zombienet/zombienet-sdk/tests/sync_blocks/mod.rs
  cumulus/zombienet/zombienet-sdk/tests/sync_blocks/sync_blocks_from_tip_without_connected_collator.rs
Labels: R0-silent, T9-cumulus, T10-tests

#8506 Revert "No disputes and no CandidateReceiptV2 on Kusama"
  Cargo.lock
  polkadot/cli/src/command.rs
  polkadot/node/collation-generation/src/lib.rs
  polkadot/node/core/dispute-coordinator/src/initialized.rs
  polkadot/node/core/dispute-coordinator/src/lib.rs
  polkadot/node/core/dispute-coordinator/src/participation/mod.rs
  polkadot/node/core/dispute-coordinator/src/tests.rs
  polkadot/node/network/collator-protocol/Cargo.toml
  polkadot/node/network/collator-protocol/src/validator_side/mod.rs
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  polkadot/node/network/statement-distribution/src/v2/tests/mod.rs
  polkadot/node/network/statement-distribution/src/v2/tests/requests.rs
  polkadot/zombienet-sdk-tests/tests/disabling/slashing.rs
  polkadot/zombienet_tests/functional/0004-parachains-garbage-candidate.zndsl
  polkadot/zombienet_tests/functional/0008-dispute-old-finalized.zndsl
  polkadot/zombienet_tests/functional/0010-validator-disabling.zndsl
Labels: R0-silent

#8511 [Release|CICD] Automatically sync forked release branch if needed before the rc build starts
  .github/workflows/release-20_build-rc.yml
  .github/workflows/release-30_publish_release_draft.yml
  .github/workflows/release-31_promote-rc-to-final.yml
  .github/workflows/release-40_publish-deb-package.yml
  .github/workflows/release-50_publish-docker.yml
Labels: R0-silent, A4-backport-stable2412, A4-backport-stable2503

#8492 [stable2503] Add missing prdoc for 8306
  prdoc/pr_8306.prdoc
Labels: R0-silent, A3-backport

#8514 cumulus/fix: Allow block-announce to exist in the background of minimal relay chains
  cumulus/client/relay-chain-minimal-node/src/network.rs
  prdoc/pr_8514.prdoc
Labels: T0-node, I2-bug, A4-backport-stable2412, A4-backport-stable2503

#8515 [stable2503] Bump node versions
  cumulus/polkadot-omni-node/lib/src/nodes/mod.rs
  polkadot/node/primitives/src/lib.rs
Labels: R0-silent

#8503 dispute-coordinator: populate disabled state on startup
  polkadot/node/core/dispute-coordinator/src/initialized.rs
  polkadot/node/core/dispute-coordinator/src/lib.rs
  prdoc/pr_8503.prdoc
Labels: T0-node, T8-polkadot, A4-backport-stable2503

#8510 statement-distribution: skip leafs where we can't fetch the state
  polkadot/node/network/statement-distribution/src/v2/mod.rs
  prdoc/pr_8510.prdoc
Labels: T0-node, T8-polkadot, A4-backport-stable2503

#8470 Stabilize the FRAME umbrella crate
  prdoc/pr_8470.prdoc
  substrate/frame/Cargo.toml
  substrate/frame/src/MAINTAIN.md
  substrate/frame/src/README.md
  substrate/frame/src/lib.rs
  umbrella/README.md
  umbrella/src/lib.rs
Labels: T1-FRAME

#8312 net/tests: Ensure litep2p discovery works for local networks
  substrate/client/network/src/litep2p/discovery.rs
Labels: R0-silent, T0-node, T10-tests

#8531 Added `OnNewHead` to `pallet-bridge-parachains`
  bridges/bin/runtime-common/src/mock.rs
  bridges/modules/parachains/src/lib.rs
  bridges/modules/parachains/src/mock.rs
  bridges/modules/relayers/src/mock.rs
  bridges/primitives/parachains/src/lib.rs
  bridges/primitives/polkadot-core/src/parachains.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_common_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/bridge_to_rococo_config.rs
  prdoc/pr_8531.prdoc
Labels: T15-bridges

#8191 collator-protocol-revamp: add PeerManager
  Cargo.lock
  polkadot/node/network/bridge/src/tx/mod.rs
  polkadot/node/network/collator-protocol/Cargo.toml
  polkadot/node/network/collator-protocol/src/collator_side/mod.rs
  polkadot/node/network/collator-protocol/src/collator_side/tests/mod.rs
  polkadot/node/network/collator-protocol/src/validator_side/mod.rs
  polkadot/node/network/collator-protocol/src/validator_side/tests/mod.rs
  polkadot/node/network/collator-protocol/src/validator_side_experimental/common.rs
  polkadot/node/network/collator-protocol/src/validator_side_experimental/error.rs
  polkadot/node/network/collator-protocol/src/validator_side_experimental/mod.rs
  polkadot/node/network/collator-protocol/src/validator_side_experimental/peer_manager/backend.rs
  polkadot/node/network/collator-protocol/src/validator_side_experimental/peer_manager/connected.rs
  polkadot/node/network/collator-protocol/src/validator_side_experimental/peer_manager/db.rs
  polkadot/node/network/collator-protocol/src/validator_side_experimental/peer_manager/mod.rs
  polkadot/node/network/collator-protocol/src/validator_side_experimental/state.rs
  polkadot/node/subsystem-types/src/messages.rs
Labels: R0-silent, T8-polkadot

#7682 Make SharedTrieCache/LocalTrieCache work with entire state in memory
  Cargo.lock
  cumulus/client/relay-chain-inprocess-interface/src/lib.rs
  cumulus/pallets/parachain-system/src/validate_block/trie_recorder.rs
  prdoc/pr_7682.prdoc
  substrate/bin/node/testing/src/bench.rs
  substrate/client/api/src/backend.rs
  substrate/client/api/src/in_mem.rs
  substrate/client/basic-authorship/src/basic_authorship.rs
  substrate/client/cli/src/commands/chain_info_cmd.rs
  substrate/client/consensus/beefy/src/import.rs
  substrate/client/db/Cargo.toml
  substrate/client/db/benches/state_access.rs
  substrate/client/db/src/bench.rs
  substrate/client/db/src/lib.rs
  substrate/client/service/src/client/call_executor.rs
  substrate/client/service/src/client/client.rs
  substrate/client/service/src/client/code_provider.rs
  substrate/client/service/src/config.rs
  substrate/client/service/test/src/client/mod.rs
  substrate/primitives/state-machine/src/trie_backend.rs
  substrate/primitives/trie/Cargo.toml
  substrate/primitives/trie/src/cache/metrics.rs
  substrate/primitives/trie/src/cache/mod.rs
  substrate/primitives/trie/src/cache/shared_cache.rs
  substrate/utils/frame/benchmarking-cli/src/overhead/command.rs
  substrate/utils/frame/benchmarking-cli/src/storage/write.rs
  substrate/utils/frame/rpc/state-trie-migration-rpc/src/lib.rs
Labels: T0-node

#8443 Stabilize V16 metadata
  Cargo.lock
  Cargo.toml
  prdoc/pr_8443.prdoc
  substrate/client/runtime-utilities/src/lib.rs
  substrate/frame/support/test/tests/pallet.rs
  substrate/primitives/metadata-ir/Cargo.toml
  substrate/primitives/metadata-ir/src/lib.rs
  substrate/primitives/metadata-ir/src/v16.rs
  substrate/utils/frame/benchmarking-cli/src/overhead/remark_builder.rs
Labels: T4-runtime_API, R1-breaking_change

#8409 check XCM size in VMP routing
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/parachain-system/src/tests.rs
  cumulus/parachains/runtimes/assets/test-utils/src/test_cases.rs
  cumulus/parachains/runtimes/assets/test-utils/src/xcm_helpers.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/tests.rs
  cumulus/primitives/core/src/lib.rs
  cumulus/primitives/utility/src/lib.rs
  prdoc/pr_8409.prdoc
Labels: T6-XCM

#8547 Disable check-runtime-migration
  .github/workflows/check-runtime-migration.yml
  prdoc/pr_8547.prdoc
Labels: R0-silent

#8545 [pallet-revive] eth-rpc improved healthcheck
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_8545.prdoc
  substrate/client/rpc-servers/src/middleware/node_health.rs
  substrate/frame/revive/rpc/src/apis/health_api.rs
  substrate/frame/revive/rpc/src/client.rs
Labels: T7-smart_contracts

#8528 FeeTracker: remove `get_min_fee_factor()`
  bridges/modules/xcm-bridge-hub-router/src/benchmarking.rs
  bridges/modules/xcm-bridge-hub-router/src/lib.rs
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/xcmp-queue/src/lib.rs
  cumulus/pallets/xcmp-queue/src/tests.rs
  polkadot/runtime/common/src/xcm_sender.rs
  polkadot/runtime/parachains/src/dmp.rs
  polkadot/runtime/parachains/src/dmp/tests.rs
  polkadot/runtime/parachains/src/lib.rs
  prdoc/pr_8528.prdoc
Labels: T6-XCM, T15-bridges

#8551 [stable2503] Crates bumps + preparations for the 2503-5
  .github/workflows/check-runtime-migration.yml
  Cargo.lock
  Plan.toml
  bridges/snowbridge/pallets/inbound-queue-v2/Cargo.toml
  bridges/snowbridge/pallets/outbound-queue-v2/Cargo.toml
  bridges/snowbridge/pallets/system-frontend/Cargo.toml
  bridges/snowbridge/pallets/system-v2/Cargo.toml
  bridges/snowbridge/primitives/core/Cargo.toml
  bridges/snowbridge/primitives/inbound-queue/Cargo.toml
  cumulus/client/relay-chain-minimal-node/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/testing/penpal/Cargo.toml
  cumulus/polkadot-omni-node/lib/src/nodes/mod.rs
  polkadot/node/core/dispute-coordinator/Cargo.toml
  polkadot/node/network/statement-distribution/Cargo.toml
  polkadot/node/primitives/src/lib.rs
  polkadot/xcm/xcm-executor/Cargo.toml
  prdoc/stable2503-4/pr_8240.prdoc
  prdoc/stable2503-4/pr_8306.prdoc
  prdoc/stable2503-4/pr_8351.prdoc
  prdoc/stable2503-4/pr_8427.prdoc
  prdoc/stable2503-4/pr_8503.prdoc
  prdoc/stable2503-4/pr_8510.prdoc
  prdoc/stable2503-4/pr_8514.prdoc
  prdoc/stable2503-5/pr_8495.prdoc
  scripts/release/replace-all-path-deps.sh
  substrate/frame/beefy/Cargo.toml
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/mock-network/Cargo.toml
  substrate/frame/revive/rpc/Cargo.toml
  substrate/frame/session/Cargo.toml
Labels: R0-silent

#8558 Fix broken link to call_ext.rs in parachains README
  bridges/modules/parachains/README.md
Labels: R0-silent

#8234 UncheckedExtrinsic: limit the decoded call size + simpllifications
  cumulus/pallets/parachain-system/src/validate_block/implementation.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/src/lib.rs
  prdoc/pr_8234.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/bin/node/testing/src/bench.rs
  substrate/bin/node/testing/src/keyring.rs
  substrate/frame/executive/src/lib.rs
  substrate/frame/executive/src/tests.rs
  substrate/frame/revive/src/evm/runtime.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/inherent.rs
  substrate/frame/support/procedural/src/construct_runtime/expand/metadata.rs
  substrate/frame/support/src/traits.rs
  substrate/frame/support/src/traits/misc.rs
  substrate/frame/support/test/tests/pallet.rs
  substrate/primitives/runtime/src/generic/unchecked_extrinsic.rs
  substrate/primitives/runtime/src/traits/mod.rs
Labels: I9-optimisation, T17-primitives

#7785 pallet scheduler: fix weight and add safety checks
  prdoc/pr_7785.prdoc
  substrate/frame/benchmarking/src/v1.rs
  substrate/frame/scheduler/src/lib.rs
  substrate/utils/frame/benchmarking-cli/src/pallet/command.rs
  substrate/utils/frame/benchmarking-cli/src/pallet/mod.rs
Labels: T2-pallets, T12-benchmarks, A4-backport-stable2412, A4-backport-stable2503

#8561 fix: Resolve compile errors with new nested error structure
  bridges/snowbridge/runtime/test-common/src/lib.rs
  cumulus/parachains/integration-tests/emulated/common/src/impls.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge_v2_outbound.rs
  cumulus/parachains/runtimes/test-utils/src/lib.rs
  cumulus/parachains/runtimes/test-utils/src/test_cases.rs
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/pallet-xcm/src/tests/mod.rs
  polkadot/xcm/src/v5/traits.rs
  polkadot/xcm/xcm-builder/src/process_xcm_message.rs
  polkadot/xcm/xcm-builder/src/tests/aliases.rs
  polkadot/xcm/xcm-builder/src/tests/assets.rs
  polkadot/xcm/xcm-builder/src/tests/bridging/universal_exports.rs
  polkadot/xcm/xcm-builder/src/tests/expecting.rs
  polkadot/xcm/xcm-builder/src/tests/locking.rs
  polkadot/xcm/xcm-builder/src/tests/origins.rs
  polkadot/xcm/xcm-builder/src/tests/querying.rs
  polkadot/xcm/xcm-builder/src/tests/transacting.rs
  polkadot/xcm/xcm-builder/src/tests/version_subscriptions.rs
  polkadot/xcm/xcm-builder/src/tests/weight.rs
  polkadot/xcm/xcm-builder/tests/scenarios.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  polkadot/xcm/xcm-simulator/fuzzer/src/parachain.rs
  polkadot/xcm/xcm-simulator/src/mock_message_queue.rs
  prdoc/pr_7730.prdoc
  substrate/frame/contracts/mock-network/src/mocks/msg_queue.rs
  substrate/frame/revive/mock-network/src/mocks/msg_queue.rs
Labels: T6-XCM

#8559 [pallet-revive] rename DepositLimit::Unchecked & minor code cleanup
  prdoc/pr_8559.prdoc
  substrate/frame/revive/rpc/src/block_info_provider.rs
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/rpc/src/fee_history.rs
  substrate/frame/revive/rpc/src/lib.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/primitives.rs
Labels: R0-silent, T7-smart_contracts

#8565 [cmd-bot] Temporary fix for weights output
  .github/workflows/cmd-run.yml
Labels: R0-silent

#7691 Ensure Consistent Topic IDs for Traceable Cross-Chain XCM
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/common/Cargo.toml
  cumulus/parachains/integration-tests/emulated/common/src/lib.rs
  cumulus/parachains/integration-tests/emulated/common/src/xcm_helpers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/asset_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/mod.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/send_xcm.rs
  cumulus/xcm/xcm-emulator/Cargo.toml
  cumulus/xcm/xcm-emulator/src/lib.rs
  polkadot/xcm/pallet-xcm/Cargo.toml
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/pallet-xcm/src/mock.rs
  polkadot/xcm/pallet-xcm/src/tests/assets_transfer.rs
  polkadot/xcm/pallet-xcm/src/tests/mod.rs
  polkadot/xcm/pallet-xcm/src/xcm_helpers.rs
  polkadot/xcm/src/v5/mod.rs
  polkadot/xcm/xcm-builder/Cargo.toml
  polkadot/xcm/xcm-builder/src/tests/assets.rs
  polkadot/xcm/xcm-builder/src/tests/bridging/mod.rs
  polkadot/xcm/xcm-builder/src/tests/mock.rs
  polkadot/xcm/xcm-builder/src/tests/querying.rs
  polkadot/xcm/xcm-builder/src/tests/transacting.rs
  polkadot/xcm/xcm-builder/src/universal_exports.rs
  polkadot/xcm/xcm-builder/tests/mock/mod.rs
  polkadot/xcm/xcm-builder/tests/scenarios.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  polkadot/xcm/xcm-executor/src/tests/initiate_transfer.rs
  polkadot/xcm/xcm-executor/src/tests/pay_fees.rs
  polkadot/xcm/xcm-runtime-apis/Cargo.toml
  polkadot/xcm/xcm-runtime-apis/tests/fee_estimation.rs
  polkadot/xcm/xcm-runtime-apis/tests/mock.rs
  polkadot/xcm/xcm-simulator/example/src/tests.rs
  polkadot/xcm/xcm-simulator/src/lib.rs
  prdoc/pr_7691.prdoc
Labels: T6-XCM, A4-backport-stable2412, A4-backport-stable2503

#8546 Bridges: Fix - Improve try-state for pallet-xcm-bridge-hub
  bridges/modules/xcm-bridge-hub/src/lib.rs
Labels: R0-silent, T15-bridges

#8580 [stable2503] Release stable2503-5 continuing
  Cargo.lock
  Plan.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  polkadot/runtime/westend/Cargo.toml
  prdoc/pr_8265.prdoc
  substrate/frame/benchmarking/Cargo.toml
  substrate/frame/benchmarking/pov/Cargo.toml
  substrate/frame/scheduler/Cargo.toml
  substrate/frame/staking/Cargo.toml
  substrate/frame/support/procedural/Cargo.toml
  substrate/utils/frame/benchmarking-cli/Cargo.toml
  substrate/utils/frame/omni-bencher/Cargo.toml
Labels: R0-silent

#8582 [stable2503] Move prdocs to release folder
  prdoc/stable2503-5/pr_7785.prdoc
  prdoc/stable2503-5/pr_8265.prdoc
Labels: R0-silent

#8577 Update `parity-scale-codec` to `v3.7.5`
  Cargo.lock
  Cargo.toml
  substrate/frame/support/test/tests/construct_runtime_ui/deprecated_where_block.stderr
Labels: R0-silent, T17-primitives

#8344 XCMP weight metering: account for the MQ page position
  Cargo.lock
  cumulus/pallets/xcmp-queue/Cargo.toml
  cumulus/pallets/xcmp-queue/src/benchmarking.rs
  cumulus/pallets/xcmp-queue/src/lib.rs
  cumulus/pallets/xcmp-queue/src/mock.rs
  cumulus/pallets/xcmp-queue/src/tests.rs
  cumulus/pallets/xcmp-queue/src/weights.rs
  cumulus/pallets/xcmp-queue/src/weights_ext.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/coretime/coretime-rococo/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/cumulus_pallet_xcmp_queue.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/cumulus_pallet_xcmp_queue.rs
  prdoc/pr_8344.prdoc
  substrate/frame/message-queue/src/lib.rs
  substrate/frame/message-queue/src/tests.rs
  substrate/frame/staking-async/runtimes/parachain/src/weights/cumulus_pallet_xcmp_queue.rs
  substrate/frame/support/src/traits.rs
  substrate/frame/support/src/traits/messages.rs
Labels: T6-XCM

#8500 txpool: fix tx removal from unlocks set
  Cargo.lock
  prdoc/pr_8500.prdoc
  substrate/client/transaction-pool/src/graph/ready.rs
Labels: I2-bug

#8604 [stable2412] Post crates release activities
  Cargo.lock
  Cargo.toml
  Plan.toml
  bridges/modules/xcm-bridge-hub/Cargo.toml
  cumulus/client/relay-chain-minimal-node/Cargo.toml
  cumulus/parachains/integration-tests/emulated/common/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/polkadot-omni-node/lib/src/nodes/mod.rs
  cumulus/xcm/xcm-emulator/Cargo.toml
  polkadot/node/primitives/src/lib.rs
  polkadot/runtime/westend/Cargo.toml
  polkadot/xcm/Cargo.toml
  polkadot/xcm/pallet-xcm/Cargo.toml
  polkadot/xcm/xcm-builder/Cargo.toml
  polkadot/xcm/xcm-executor/Cargo.toml
  polkadot/xcm/xcm-runtime-apis/Cargo.toml
  polkadot/xcm/xcm-simulator/Cargo.toml
  polkadot/xcm/xcm-simulator/example/Cargo.toml
  prdoc/stable2412-6/pr_7691.prdoc
  prdoc/stable2412-6/pr_7785.prdoc
  prdoc/stable2412-6/pr_8373.prdoc
  prdoc/stable2412-6/pr_8427.prdoc
  prdoc/stable2412-6/pr_8514.prdoc
  prdoc/stable2412-6/pr_8585.prdoc
  prdoc/stable2412-6/pr_8589.prdoc
  substrate/client/network/Cargo.toml
  substrate/frame/beefy/Cargo.toml
  substrate/frame/benchmarking/Cargo.toml
  substrate/frame/election-provider-multi-phase/Cargo.toml
  substrate/frame/election-provider-support/Cargo.toml
  substrate/frame/election-provider-support/solution-type/Cargo.toml
  substrate/frame/scheduler/Cargo.toml
  substrate/primitives/npos-elections/Cargo.toml
  substrate/utils/frame/benchmarking-cli/Cargo.toml
  umbrella/Cargo.toml
Labels: R0-silent

#8612 Bridges: Fix - Improve try-state for pallet-xcm-bridge
  bridges/modules/xcm-bridge/src/lib.rs
  bridges/modules/xcm-bridge/src/tests.rs
Labels: R0-silent, T15-bridges

#8614 [stable2503] Post crates release stable2503-5
  Cargo.lock
  Plan.toml
  bridges/modules/xcm-bridge-hub/Cargo.toml
  cumulus/parachains/integration-tests/emulated/common/Cargo.toml
  cumulus/xcm/xcm-emulator/Cargo.toml
  polkadot/xcm/Cargo.toml
  polkadot/xcm/pallet-xcm/Cargo.toml
  polkadot/xcm/xcm-builder/Cargo.toml
  polkadot/xcm/xcm-executor/Cargo.toml
  polkadot/xcm/xcm-runtime-apis/Cargo.toml
  polkadot/xcm/xcm-simulator/Cargo.toml
  polkadot/xcm/xcm-simulator/example/Cargo.toml
  prdoc/stable2503-5/pr_7691.prdoc
  prdoc/stable2503-5/pr_8546.prdoc
  prdoc/stable2503-5/pr_8585.prdoc
  substrate/frame/election-provider-multi-phase/Cargo.toml
  substrate/frame/election-provider-support/Cargo.toml
  substrate/frame/election-provider-support/solution-type/Cargo.toml
  substrate/primitives/npos-elections/Cargo.toml
Labels: R0-silent

#8533 `fatxpool`: add fallback for ready at light
  prdoc/pr_8533.prdoc
  substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/mod.rs
  substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs
  substrate/client/transaction-pool/tests/fatp.rs
Labels: I5-enhancement

#8230 collator-protocol: add more collation observability
  polkadot/node/network/bridge/src/rx/mod.rs
  polkadot/node/network/collator-protocol/src/collator_side/collation.rs
  polkadot/node/network/collator-protocol/src/collator_side/metrics.rs
  polkadot/node/network/collator-protocol/src/collator_side/mod.rs
  polkadot/node/network/collator-protocol/src/collator_side/tests/mod.rs
  polkadot/node/network/collator-protocol/src/collator_side/tests/prospective_parachains.rs
  polkadot/node/network/collator-protocol/src/lib.rs
  polkadot/node/subsystem-util/src/backing_implicit_view.rs
  prdoc/pr_8230.prdoc
Labels: T0-node, T9-cumulus

#8611 Revert 7934 es/remove tj changes
  .github/workflows/reusable-preflight.yml
  .github/workflows/zombienet-reusable-preflight.yml
Labels: R0-silent, T10-tests

#8069 Benchmark storage access on block validation
  Cargo.lock
  Cargo.toml
  cumulus/pallets/parachain-system/src/validate_block/mod.rs
  cumulus/pallets/parachain-system/src/validate_block/trie_cache.rs
  cumulus/pallets/parachain-system/src/validate_block/trie_recorder.rs
  prdoc/pr_8069.prdoc
  substrate/utils/frame/benchmarking-cli/Cargo.toml
  substrate/utils/frame/benchmarking-cli/src/storage/cmd.rs
  substrate/utils/frame/benchmarking-cli/src/storage/mod.rs
  substrate/utils/frame/benchmarking-cli/src/storage/read.rs
  substrate/utils/frame/benchmarking-cli/src/storage/template.rs
  substrate/utils/frame/benchmarking-cli/src/storage/weights.hbs
  substrate/utils/frame/benchmarking-cli/src/storage/write.rs
  substrate/utils/frame/storage-access-test-runtime/Cargo.toml
  substrate/utils/frame/storage-access-test-runtime/build.rs
  substrate/utils/frame/storage-access-test-runtime/src/lib.rs
Labels: T12-benchmarks

#8617 cumulus: adjust unincluded segment size metric buckets
  cumulus/client/service/src/lib.rs
Labels: R0-silent, T9-cumulus

#8600 🔪 flaky and Zombienet tests
  .github/workflows/zombienet_cumulus.yml
  .github/workflows/zombienet_parachain-template.yml
  .github/workflows/zombienet_polkadot.yml
  .github/workflows/zombienet_substrate.yml
  .github/zombienet-env
  Cargo.toml
  substrate/client/consensus/babe/src/tests.rs
  substrate/client/network/src/discovery.rs
  substrate/client/network/test/src/sync.rs
Labels: R0-silent, T10-tests

#8624 [stable2503] Push sp-api-proc-macro & frame-executive for the stable2503
  Cargo.lock
  Plan.toml
  substrate/frame/executive/Cargo.toml
  substrate/primitives/api/proc-macro/Cargo.toml
Labels: R0-silent

#8606 Use hashbrown hashmap/hashset in validation context
  Cargo.lock
  Cargo.toml
  cumulus/pallets/parachain-system/Cargo.toml
  cumulus/pallets/parachain-system/src/validate_block/trie_cache.rs
  cumulus/pallets/parachain-system/src/validate_block/trie_recorder.rs
  prdoc/pr_8606.prdoc
Labels: T9-cumulus

#8345 tx/metrics: Add metrics for the RPC v2 `transactionWatch_v1_submitAndWatch`
  Cargo.lock
  prdoc/pr_8345.prdoc
  substrate/client/rpc-spec-v2/Cargo.toml
  substrate/client/rpc-spec-v2/src/transaction/event.rs
  substrate/client/rpc-spec-v2/src/transaction/metrics.rs
  substrate/client/rpc-spec-v2/src/transaction/mod.rs
  substrate/client/rpc-spec-v2/src/transaction/tests/setup.rs
  substrate/client/rpc-spec-v2/src/transaction/transaction.rs
  substrate/client/service/src/builder.rs
Labels: T0-node

#8587 [pallet-revive] make subscription task panic on error
  Cargo.lock
  Cargo.toml
  cumulus/zombienet/zombienet-sdk-helpers/Cargo.toml
  cumulus/zombienet/zombienet-sdk-helpers/src/lib.rs
  cumulus/zombienet/zombienet-sdk/Cargo.toml
  cumulus/zombienet/zombienet-sdk/tests/bootnodes/mod.rs
  cumulus/zombienet/zombienet-sdk/tests/elastic_scaling/elastic_scaling_multiple_blocks_per_slot.rs
  cumulus/zombienet/zombienet-sdk/tests/sync_blocks/sync_blocks_from_tip_without_connected_collator.rs
  polkadot/zombienet-sdk-tests/Cargo.toml
  polkadot/zombienet-sdk-tests/tests/disabling/slashing.rs
  polkadot/zombienet-sdk-tests/tests/elastic_scaling/basic_3cores.rs
  polkadot/zombienet-sdk-tests/tests/elastic_scaling/doesnt_break_parachains.rs
  polkadot/zombienet-sdk-tests/tests/elastic_scaling/slot_based_12cores.rs
  polkadot/zombienet-sdk-tests/tests/elastic_scaling/slot_based_3cores.rs
  polkadot/zombienet-sdk-tests/tests/functional/approval_voting_coalescing.rs
  polkadot/zombienet-sdk-tests/tests/functional/approved_peer_mixed_validators.rs
  polkadot/zombienet-sdk-tests/tests/functional/async_backing_6_seconds_rate.rs
  polkadot/zombienet-sdk-tests/tests/functional/duplicate_collations.rs
  polkadot/zombienet-sdk-tests/tests/functional/spam_statement_distribution_requests.rs
  polkadot/zombienet-sdk-tests/tests/functional/sync_backing.rs
  polkadot/zombienet-sdk-tests/tests/smoke/coretime_revenue.rs
  prdoc/pr_8587.prdoc
  substrate/frame/revive/rpc/src/apis/health_api.rs
  substrate/frame/revive/rpc/src/cli.rs
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/rpc/src/subxt_client.rs
  substrate/utils/frame/benchmarking-cli/src/overhead/remark_builder.rs
Labels: T7-smart_contracts

#8648 Charge deposit based on key length
  prdoc/pr_8648.prdoc
  substrate/frame/revive/src/storage.rs
  substrate/frame/revive/src/tests.rs
Labels: T7-smart_contracts, A4-backport-stable2503

#8650 litep2p/peerset: Reject non-reserved peers in the reserved-only mode
  prdoc/pr_8650.prdoc
  substrate/client/network/src/litep2p/shim/notification/peerset.rs
  substrate/client/network/src/litep2p/shim/notification/tests/peerset.rs
Labels: T0-node, I2-bug

#8382 add poke_deposit extrinsic to pallet-bounties
  polkadot/runtime/rococo/src/weights/pallet_bounties.rs
  prdoc/pr_8382.prdoc
  substrate/frame/bounties/src/benchmarking.rs
  substrate/frame/bounties/src/lib.rs
  substrate/frame/bounties/src/tests.rs
  substrate/frame/bounties/src/weights.rs
Labels: T1-FRAME, T2-pallets

#8664 [pallet-revive] Fix rpc-types
  prdoc/pr_8664.prdoc
  substrate/frame/revive/rpc/src/client.rs
  substrate/frame/revive/src/evm/api/rpc_types.rs
  substrate/frame/revive/src/evm/api/rpc_types_gen.rs
Labels: T7-smart_contracts

#8652 [pallet-revive] impl_revive_api macro
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  prdoc/pr_8652.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/revive/src/lib.rs
Labels: T7-smart_contracts

#8674 [stable2503] RC4 preparations
  Cargo.lock
  Plan.toml
  bridges/modules/xcm-bridge-hub/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  polkadot/runtime/westend/Cargo.toml
  polkadot/xcm/pallet-xcm/Cargo.toml
  prdoc/pr_7785.prdoc
  prdoc/stable2503-5/pr_8173.prdoc
  prdoc/stable2503-5/pr_8615.prdoc
  prdoc/stable2503-5/pr_8648.prdoc
  substrate/frame/benchmarking/Cargo.toml
  substrate/frame/revive/Cargo.toml
  substrate/frame/scheduler/Cargo.toml
  substrate/utils/frame/benchmarking-cli/Cargo.toml
Labels: R0-silent

#7556 Add trie cache warmup
  Cargo.lock
  cumulus/test/service/src/lib.rs
  polkadot/node/test/service/src/lib.rs
  prdoc/pr_7556.prdoc
  substrate/bin/node/cli/benches/block_production.rs
  substrate/bin/node/cli/benches/transaction_pool.rs
  substrate/client/cli/src/config.rs
  substrate/client/cli/src/params/import_params.rs
  substrate/client/cli/src/runner.rs
  substrate/client/db/Cargo.toml
  substrate/client/db/src/lib.rs
  substrate/client/service/src/builder.rs
  substrate/client/service/src/config.rs
  substrate/client/service/test/src/lib.rs
Labels: T0-node

#8632 CI: Enforce SemVer restrictions on backport PRs with optional override via `validate: false`
  .github/workflows/check-semver.yml
  docs/contributor/prdoc.md
Labels: R0-silent, A4-backport-stable2412, A4-backport-stable2503

#7762 ERC20 Asset Transactor
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/chains/parachains/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/mod.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/assets/common/Cargo.toml
  cumulus/parachains/runtimes/assets/common/src/erc20_transactor.rs
  cumulus/parachains/runtimes/assets/common/src/lib.rs
  cumulus/parachains/runtimes/testing/penpal/Cargo.toml
  polkadot/xcm/xcm-executor/src/lib.rs
  polkadot/xcm/xcm-executor/src/traits/transact_asset.rs
  prdoc/pr_7762.prdoc
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/fixtures/contracts/dummy.polkavm
  substrate/frame/revive/fixtures/contracts/dummy.sol
  substrate/frame/revive/fixtures/contracts/erc20.polkavm
  substrate/frame/revive/fixtures/contracts/erc20.sol
  substrate/frame/revive/fixtures/contracts/expensive_erc20.polkavm
  substrate/frame/revive/fixtures/contracts/expensive_erc20.sol
  substrate/frame/revive/fixtures/contracts/fake_erc20.polkavm
  substrate/frame/revive/fixtures/contracts/fake_erc20.sol
  substrate/frame/revive/src/impl_fungibles.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/tests.rs
  substrate/frame/staking-async/runtimes/parachain/Cargo.toml
  umbrella/Cargo.toml
Labels: T6-XCM, T7-smart_contracts

#8535 Make `WeightBounds` return `XcmError` to surface failures
  Cargo.lock
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/xcm-builder/Cargo.toml
  polkadot/xcm/xcm-builder/src/tests/weight.rs
  polkadot/xcm/xcm-builder/src/weight.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  polkadot/xcm/xcm-executor/src/tests/mock.rs
  polkadot/xcm/xcm-executor/src/traits/weight.rs
  prdoc/pr_8535.prdoc
Labels: T6-XCM, A3-backport

#8696 ci: trigger zombienet tests if 'T18-zombienet_tests' label set
  .github/workflows/zombienet-reusable-preflight.yml
  .github/workflows/zombienet_cumulus.yml
  .github/workflows/zombienet_parachain-template.yml
  .github/workflows/zombienet_polkadot.yml
  .github/workflows/zombienet_substrate.yml
  .github/zombienet-env
Labels: R0-silent, T10-tests, T18-zombienet_tests

#8700 transfer_assets benchmarking and weights for people chains
  cumulus/parachains/runtimes/people/people-rococo/src/lib.rs
  cumulus/parachains/runtimes/people/people-rococo/src/weights/pallet_xcm.rs
  cumulus/parachains/runtimes/people/people-westend/src/lib.rs
  cumulus/parachains/runtimes/people/people-westend/src/weights/pallet_xcm.rs
  prdoc/pr_8700.prdoc
Labels: T6-XCM, T12-benchmarks

#8369 Sync xcm related test utils impls with runtimes repo
  Cargo.lock
  cumulus/parachains/integration-tests/emulated/common/Cargo.toml
  cumulus/parachains/integration-tests/emulated/common/src/macros.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/claim_assets.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/hybrid_transfers.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/reserve_transfer.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/reward_pool.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/src/tests/treasury.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/aliases.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/claim_assets.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/claim_assets.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/Cargo.toml
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/aliases.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/claim_assets.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/src/tests/aliases.rs
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/src/tests/fellowship.rs
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/src/tests/fellowship_salary.rs
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/src/tests/fellowship_treasury.rs
  cumulus/parachains/integration-tests/emulated/tests/collectives/collectives-westend/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-rococo/src/tests/claim_assets.rs
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-westend/src/tests/aliases.rs
  cumulus/parachains/integration-tests/emulated/tests/coretime/coretime-westend/src/tests/claim_assets.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-rococo/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-rococo/src/tests/claim_assets.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-rococo/src/tests/teleport.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/aliases.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/claim_assets.rs
  cumulus/parachains/integration-tests/emulated/tests/people/people-westend/src/tests/teleport.rs
  polkadot/runtime/common/src/xcm_sender.rs
  prdoc/pr_8369.prdoc
Labels: T6-XCM, T10-tests, T12-benchmarks

#8599 Snowbridge: Unpaid execution when bridging to Ethereum
  bridges/snowbridge/runtime/runtime-common/src/lib.rs
  bridges/snowbridge/runtime/runtime-common/src/tests.rs
  bridges/snowbridge/runtime/runtime-common/src/v1/fee_handler.rs
  bridges/snowbridge/runtime/runtime-common/src/v1/mod.rs
  bridges/snowbridge/runtime/test-common/src/lib.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/snowbridge.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/src/xcm_config.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/snowbridge.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/tests.rs
  polkadot/xcm/xcm-builder/src/universal_exports.rs
  prdoc/pr_8599.prdoc
Labels: T15-bridges

#8687 Staking (EPMB): Add defensive error handling to voter snapshot creation and solution verification
  prdoc/pr_8687.prdoc
  substrate/frame/election-provider-multi-block/src/lib.rs
  substrate/frame/election-provider-multi-block/src/verifier/impls.rs
Labels: T2-pallets

#8554 pallet-assets ERC20 precompile
  Cargo.lock
  cumulus/parachains/common/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_assets_foreign.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_assets_local.rs
  cumulus/parachains/runtimes/assets/asset-hub-rococo/src/weights/pallet_assets_pool.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_assets_foreign.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_assets_local.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_assets_pool.rs
  cumulus/parachains/runtimes/assets/common/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/Cargo.toml
  cumulus/parachains/runtimes/collectives/collectives-westend/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-rococo/Cargo.toml
  cumulus/parachains/runtimes/coretime/coretime-westend/Cargo.toml
  cumulus/parachains/runtimes/glutton/glutton-westend/Cargo.toml
  cumulus/parachains/runtimes/people/people-rococo/Cargo.toml
  cumulus/parachains/runtimes/people/people-westend/Cargo.toml
  cumulus/parachains/runtimes/testing/penpal/Cargo.toml
  cumulus/polkadot-omni-node/lib/Cargo.toml
  cumulus/polkadot-parachain/Cargo.toml
  prdoc/pr_8554.prdoc
  substrate/bin/node/runtime/src/lib.rs
  substrate/frame/assets/Cargo.toml
  substrate/frame/assets/src/benchmarking.rs
  substrate/frame/assets/src/lib.rs
  substrate/frame/assets/src/mock.rs
  substrate/frame/assets/src/precompiles.rs
  substrate/frame/assets/src/weights.rs
  substrate/frame/revive/mock-network/src/parachain/contracts_config.rs
  substrate/frame/revive/src/address.rs
  substrate/frame/revive/src/exec.rs
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/precompiles.rs
  substrate/frame/revive/src/wasm/runtime.rs
  substrate/frame/staking-async/runtimes/parachain/Cargo.toml
  substrate/frame/staking-async/runtimes/parachain/src/weights/pallet_assets_foreign.rs
  substrate/frame/staking-async/runtimes/parachain/src/weights/pallet_assets_local.rs
  substrate/frame/staking-async/runtimes/parachain/src/weights/pallet_assets_pool.rs
  umbrella/Cargo.toml
Labels: T7-smart_contracts

#7730 Nest errors in pallet-xcm
  bridges/snowbridge/primitives/core/src/reward.rs
  bridges/snowbridge/runtime/test-common/src/lib.rs
  bridges/snowbridge/test-utils/src/mock_xcm.rs
  cumulus/parachains/integration-tests/emulated/common/src/impls.rs
  cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/exchange_asset.rs
  cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge_v2_outbound.rs
  cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend/tests/tests.rs
  cumulus/parachains/runtimes/bridge-hubs/test-utils/src/test_cases/mod.rs
  cumulus/parachains/runtimes/collectives/collectives-westend/tests/tests.rs
  cumulus/parachains/runtimes/coretime/coretime-westend/tests/tests.rs
  cumulus/parachains/runtimes/people/people-westend/tests/tests.rs
  cumulus/parachains/runtimes/test-utils/src/lib.rs
  cumulus/parachains/runtimes/test-utils/src/test_cases.rs
  polkadot/xcm/pallet-xcm/src/errors.rs
  polkadot/xcm/pallet-xcm/src/lib.rs
  polkadot/xcm/pallet-xcm/src/tests/mod.rs
  polkadot/xcm/src/v5/mod.rs
  polkadot/xcm/src/v5/traits.rs
  polkadot/xcm/xcm-builder/src/process_xcm_message.rs
  polkadot/xcm/xcm-builder/src/tests/aliases.rs
  polkadot/xcm/xcm-builder/src/tests/assets.rs
  polkadot/xcm/xcm-builder/src/tests/basic.rs
  polkadot/xcm/xcm-builder/src/tests/bridging/mod.rs
  polkadot/xcm/xcm-builder/src/tests/bridging/universal_exports.rs
  polkadot/xcm/xcm-builder/src/tests/expecting.rs
  polkadot/xcm/xcm-builder/src/tests/locking.rs
  polkadot/xcm/xcm-builder/src/tests/origins.rs
  polkadot/xcm/xcm-builder/src/tests/querying.rs
  polkadot/xcm/xcm-builder/src/tests/transacting.rs
  polkadot/xcm/xcm-builder/src/tests/version_subscriptions.rs
  polkadot/xcm/xcm-builder/src/tests/weight.rs
  polkadot/xcm/xcm-builder/src/weight.rs
  polkadot/xcm/xcm-builder/tests/scenarios.rs
  polkadot/xcm/xcm-executor/integration-tests/src/lib.rs
  polkadot/xcm/xcm-executor/src/lib.rs
  polkadot/xcm/xcm-executor/src/tests/mock.rs
  polkadot/xcm/xcm-executor/src/tests/set_asset_claimer.rs
  polkadot/xcm/xcm-executor/src/traits/weight.rs
  polkadot/xcm/xcm-simulator/fuzzer/src/parachain.rs
  polkadot/xcm/xcm-simulator/src/mock_message_queue.rs
  prdoc/pr_7730.prdoc
  substrate/frame/contracts/mock-network/src/mocks/msg_queue.rs
  substrate/frame/revive/mock-network/src/mocks/msg_queue.rs
Labels: T6-XCM
