Repository paritytech/polkadot-sdk, pull requests merged in 2025-10, with the labels that each got.

#9894 Adjust statement store configs to hold more data
  prdoc/pr_9894.prdoc
  substrate/client/network/statement/src/config.rs
  substrate/client/statement-store/src/lib.rs
Labels: T0-node

#9902 [stable2509] Move prdocs to release folder stable2509
  prdoc/stable2509/pr_9319.prdoc
  prdoc/stable2509/pr_9796.prdoc
  prdoc/stable2509/pr_9868.prdoc
Labels: R0-no-crate-publish-required

#9670 Move revive fixtures into release directory
  prdoc/pr_9670.prdoc
  substrate/frame/revive/fixtures/build.rs
Labels: T10-tests

#9928 pallet-revive: Bump PolkaVM
  Cargo.lock
  prdoc/pr_9928.prdoc
  substrate/frame/revive/Cargo.toml
  substrate/frame/revive/fixtures/Cargo.toml
  substrate/frame/revive/uapi/Cargo.toml
Labels: T7-smart_contracts

#9907 CheckWeight: Take transaction length into account during validation
  prdoc/pr_9907.prdoc
  substrate/frame/system/src/extensions/check_weight.rs
Labels: T1-FRAME

#9911 [pallet-revive] Allows setting evm balance for non-existing account
  prdoc/pr_9911.prdoc
  substrate/frame/revive/src/lib.rs
  substrate/frame/revive/src/tests/pvm.rs
Labels: T7-smart_contracts

#9936 Additional Kusama and Polkadot invulnerable collator peer ids
  polkadot/cli/src/command.rs
  prdoc/pr_9936.prdoc
Labels: T8-polkadot, A4-backport-stable2509

#9904 FinalityNotification: Directly include stale blocks
  cumulus/client/pov-recovery/src/tests.rs
  prdoc/pr_9904.prdoc
  substrate/client/api/src/backend.rs
  substrate/client/api/src/client.rs
  substrate/client/consensus/babe/src/lib.rs
  substrate/client/db/src/lib.rs
  substrate/client/merkle-mountain-range/src/offchain_mmr.rs
  substrate/client/rpc-spec-v2/src/chain_head/chain_head_follow.rs
  substrate/client/rpc-spec-v2/src/chain_head/test_utils.rs
  substrate/client/service/src/client/client.rs
  substrate/client/service/test/src/client/mod.rs
  substrate/primitives/blockchain/src/backend.rs
Labels: T0-node

#9958 RPC Spec V2: Fix flaky test
  substrate/client/rpc-spec-v2/src/transaction/tests/transaction_tests.rs
  substrate/client/rpc/src/utils.rs
Labels: R0-no-crate-publish-required

#9967 Finally remove the `experimental-ump-signals` feature
  cumulus/pallets/parachain-system/Cargo.toml
  cumulus/pallets/parachain-system/src/lib.rs
  cumulus/pallets/parachain-system/src/validate_block/implementation.rs
  cumulus/pallets/parachain-system/src/validate_block/tests.rs
  cumulus/test/runtime/Cargo.toml
  cumulus/test/runtime/build.rs
  docs/sdk/src/guides/enable_elastic_scaling.rs
  prdoc/pr_9967.prdoc
Labels: T9-cumulus

#9913 [DNM] Zombienet fix process logs
  .github/actions/download-artifact-extract/action.yml
  .github/actions/zombienet-sdk/action.yml
  .github/actions/zombienet/action.yml
  .github/scripts/process-logs-zombienet-sdk.sh
  .github/scripts/process-logs-zombienet.sh
  .github/workflows/zombienet-reusable-preflight.yml
  .github/workflows/zombienet_cumulus.yml
  .github/workflows/zombienet_parachain-template.yml
  .github/workflows/zombienet_polkadot.yml
  .github/workflows/zombienet_substrate.yml
Labels: R0-no-crate-publish-required, T10-tests
